### ISSUE TITLE
[Bug] One of my repo doesn't render 

### ISSUE THREAD

**Issue by ucalyptus** [anuraghazra/github-readme-stats#10]
This link leads to the screenshot https://github-readme-stats.anuraghazra1.vercel.app/api/pin/?username=ucalyptus&repo=keras-notify
Check that https://github.com/ucalyptus/keras-notify exists
cc: @anuraghazra 

![Screenshot from 2020-07-10 11-18-54](https://user-images.githubusercontent.com/36279638/87120898-3bf93d80-c29f-11ea-9b86-e05eb3c182c5.png)

**Comment by anuraghazra** [comment]
Thanks for reporting the bug @ucalyptus this happened because your repo does not have a description i'll fix this now.

**Comment by anuraghazra** [comment]
Hello @ucalyptus it should be fixed in a moment. 

BTW sorry i accidentally added the preview links in the docs and you are using that use this link ->

```md
[![ReadMe Card](https://github-readme-stats.vercel.app/api/pin/?username=anuraghazra&repo=github-readme-stats)](https://github.com/anuraghazra/github-readme-stats)
```
