### ISSUE TITLE
Automatically switch between day and night themes

### ISSUE THREAD

**Issue by chachako** [anuraghazra/github-readme-stats#1001]
I hope that two themes can be set, which are displayed during the day and night respectively.

In the github night mode, displaying the white README element is really bad~~

**Comment by vaporwavy** [comment]
I totally agree. Since we can't use CSS in README.md, we need to do something about it.

**Comment by rickstaa** [comment]
Putting [this guide](https://github.com/anuraghazra/github-readme-stats/discussions/1684) here as a reference. I will probably update the README in the future so that we can close this PR.

**Comment by rickstaa** [comment]
Related to:
- #1645
- #1182
- #897
- #777
- #739
- #1036 
- #689
- #414
- #79
- #693
- #1415 
- #690
- #1880
- #1684
- #1920
 
People are now advised to use [this trick](https://github.com/anuraghazra/github-readme-stats/discussions/1415#discussioncomment-2152317).

**Comment by rickstaa** [comment]
Things that need to be done to close this issue:
- [ ] Merge one of the following transparent themes:
    - #1824, #1785, #1088, #1010.
- [ ] Document this theme in the README.
- [ ] Document auto theme change code in README (see https://github.com/anuraghazra/github-readme-stats/discussions/1684).

**Comment by rickstaa** [comment]
I just included a default transparent theme which has a contrast ratio of more than 4.5 in both black and white. We will only include this transparent theme for now. If you want to make your own transparent theme, you can set the `bg_color` to `ffffff00`.

https://github-readme-stats.vercel.app/api?username=anuraghazra&title_color=006AFF&icon_color=0579C3&text_color=417E87&bg_color=ffffff00&show_icons=true

```md
[![Anurag's GitHub stats](https://github-readme-stats.vercel.app/api?username=anuraghazra&theme=transparent&show_icons=true)](https://github.com/anuraghazra/github-readme-stats)
```

[![Anurag's GitHub stats](https://github-readme-stats.vercel.app/api?username=anuraghazra&theme=transparent&show_icons=true)](https://github.com/anuraghazra/github-readme-stats)

**Comment by rickstaa** [comment]
Closing this since we have included all the currently available methods for creating a dynamic theme in documentation #2229 (see https://github.com/anuraghazra/github-readme-stats#responsive-card-theme).
