### ISSUE TITLE
Error Fetching Resource

### ISSUE THREAD

**Issue by tkxkd0159** [anuraghazra/github-readme-stats#1002]
**Describe the bug**
All features are not working now on github 
the resources are not fetched now
original link works well but it doesn't work after redirect github's anonymized image URLs (camo)
so I guess this problem is related to camo.
when I get header from api request, the content-type is text/plain but camo doesn't support this so I guess it makes fetching error
I checked api code and saw that the headers are already set "res.setHeader("Content-Type", "image/svg+xml");"
so I don't know how to resolve this issue

**Expected behavior**
I wanna display my github stats, top langs, extra pin cards on my github profile but there is a issue.

**Screenshots / Live demo link (paste the github-readme-stats link as markdown image)**
https://camo.githubusercontent.com/8fa95e5d6d7adaf2c893ebebf1b3abdc2336aa2a7cbbbb4b9500bdf8c882f181/68747470733a2f2f6769746875622d726561646d652d73746174732d6a31343961343769392d746b786b64303135392e76657263656c2e6170702f6170693f757365726e616d653d746b786b643031353926686964653d636f6e74726962732c7072732c73746172732c6973737565732673686f775f69636f6e733d74727565267468656d653d726561637426696e636c7564655f616c6c5f636f6d6d6974733d74727565

**Additional context**

**Comment by tkxkd0159** [comment]
It was a temporary failure of https://camo.githubusercontent.com/

**Comment by Beki78** [comment]
same here my github streak graph is not working it says error etching resource [https://camo.githubusercontent.com/87a3a1497d81151295ca2593460f7433fd4ad1332002dabd54b11897f58ad5d8/68747470733a2f2f73747265616b2d73746174732e64656d6f6c61622e636f6d3f757365723d42656b693738266c6f63616c653d656e266d6f64653d6461696c79267468656d653d68696768636f6e747261737426686964655f626f726465723d66616c736526626f726465725f7261646975733d35266f726465723d33](url)
