### ISSUE TITLE
Private Commits

### ISSUE THREAD

**Issue by LucaTanks** [anuraghazra/github-readme-stats#1004]
Hello, this is less of a big report and more of a question. I put the private commits thing in my link for my stats, however it still shows 5 and I have over 100 on a private repository. What should I do?

**Comment by anuraghazra** [comment]
Make sure to tick this checkmark and press the "Update contributions" button under your github profile settings

![image](https://user-images.githubusercontent.com/35374649/115272755-647e6400-a15c-11eb-8d31-26489477a283.png)

**Comment by DaBigEgg** [comment]
It now says "NaN"

https://github-readme-stats.vercel.app/api?username=dabigegg&?count_private=true&show_icons=true&theme=yeblu&hide=contribs,prs&custom_title=Da%20Egg%27s%20Stats&include_all_commits=true&hide_rank=true

**Comment by gabrielv33** [comment]
This is still not working. Private commits are not shown at all for me.

**Comment by anuraghazra** [comment]
> It now says "NaN"
> 
> https://github-readme-stats.vercel.app/api?username=dabigegg&?count_private=true&show_icons=true&theme=yeblu&hide=contribs,prs&custom_title=Da%20Egg%27s%20Stats&include_all_commits=true&hide_rank=true

Aha that's interesting. never saw NaN as a result thus far in any of the stats card.

**Comment by anuraghazra** [comment]
Okay seems like github is failing to fetch your total commits thats the issue here. 

```js
  // https://developer.github.com/v3/search/#search-commits
  const fetchTotalCommits = (variables, token) => {
    return axios({
      method: "get",
      url: `https://api.github.com/search/commits?q=author:${variables.login}`,
      headers: {
        "Content-Type": "application/json",
        Accept: "application/vnd.github.cloak-preview+json",
        Authorization: `bearer ${token}`,
      },
    });
  };

```

This is returning undefined.

I would recommend you to remove the `include_all_commits` flag & [deploy github-readme-stats on your own instance](https://github.com/anuraghazra/github-readme-stats#deploy-on-your-own-vercel-instance) that way `count_private` flag can fetch all your private commits since it will be using your github token.

**Comment by DaBigEgg** [comment]
How do I do this?

**Comment by gabrielv33** [comment]
I can confirm that after creating my own deployment, the number of commits seems to have increased significantly. Will Vercel automatically apply any changes to this repository though?

**Comment by DaBigEgg** [comment]
I don’t know what you mean by your own deployment

**Comment by gabrielv33** [comment]
Read the project ReadMe page. It's all there.
