### ISSUE TITLE
[Bug] The color option at the very end does not work.

### ISSUE THREAD

**Issue by minji-o-j** [anuraghazra/github-readme-stats#101]
### Describe the bug
The color option at the very end does not work.

### Expected behavior
There was an error when trying to change the colors of icons and titles.
When modifying Customization Options, it doesn't seem to be reflected if the color option comes at the end.

### Screenshots / Live demo link (paste the github-readme-stats link as markdown image)

```
![Minji's Stats](https://github-readme-stats.vercel.app/api?username=minji-o-j&hide=["stars"]&hide_title=true&show_icons=true&text_color=777&icon_color=333&title_color=333")
```
![Minji's Stats](https://github-readme-stats.vercel.app/api?username=minji-o-j&hide=["stars"]&hide_title=true&show_icons=true&text_color=777&icon_color=333&title_color=333")

`title_color=333` was written at the end, but it was not reflected.

---
```
![Minji's Stats](https://github-readme-stats.vercel.app/api?username=minji-o-j&hide=["stars"]&hide_title=true&show_icons=true&text_color=777&title_color=333&icon_color=333")
```
![Minji's Stats](https://github-readme-stats.vercel.app/api?username=minji-o-j&hide=["stars"]&hide_title=true&show_icons=true&text_color=777&title_color=333&icon_color=333")

`icon_color=333` was written at the end, but it was not reflected.

---
```
![Minji's Stats](https://github-readme-stats.vercel.app/api?username=minji-o-j&hide=["stars"]&hide_title=true&text_color=777&title_color=333&icon_color=333&show_icons=true")
```
![Minji's Stats](https://github-readme-stats.vercel.app/api?username=minji-o-j&hide=["stars"]&hide_title=true&text_color=777&title_color=333&icon_color=333&show_icons=true")

But when I wrote something other than the color option at the end, it reflects well.

**Comment by anuraghazra** [comment]
Hi @minji-o-j it actually works correctly as expected, I think you've missed that you have an extra " Quote at the end of each live preview, which is wrong. 



Live demo works nicely. 
![Minji's Stats](https://github-readme-stats.vercel.app/api?username=minji-o-j&hide=["stars"]&hide_title=true&show_icons=true&text_color=777&title_color=333&icon_color=f00)

```md
![Minji's Stats](https://github-readme-stats.vercel.app/api?username=minji-o-j&hide=["stars"]&hide_title=true&show_icons=true&text_color=777&title_color=333&icon_color=f00)
```

**Comment by minji-o-j** [comment]
Ohh.. The error came from my typo.
Now I've solved it completely. Thanks @anuraghazra !
