### ISSUE TITLE
LaTeX not shown in language distribution

### ISSUE THREAD

**Issue by gabrielv33** [anuraghazra/github-readme-stats#1017]
LaTeX is not shown in the top language distribution.

**Comment by anuraghazra** [comment]
Please provide more information on

- Why you think it should appear.
- Check your repos and see how many repos with that language you have

And note that we count language stats by how much code in bytes you have in the repo. So it's likely that your specified language did not pass the cutoff. 

We don't control any of the data ourselves it's all coming from the API. We just filter it out and show it.

**Comment by rickstaa** [comment]
@gabrielv33 I closed this since we did not receive an answer from you. Please feel free to comment below if you still need this feature.

**Comment by qwerty541** [comment]
Hello @gabriel-vanca 

You can use [GraphQL Explorer](https://docs.github.com/en/graphql/overview/explorer) with the following query:

```graphql
query userInfo($login: String!) {
  user(login: $login) {
    # fetch only owner repos & not forks
    repositories(ownerAffiliations: OWNER, isFork: false, first: 100) {
      nodes {
        name
        languages(first: 10, orderBy: {field: SIZE, direction: DESC}) {
          edges {
            size
            node {
              color
              name
            }
          }
        }
      }
    }
  }
}
```

And with following query variables:

```
{"login": "gabriel-vanca"}
```
