### ISSUE TITLE
Something went wrong!

### ISSUE THREAD

**Issue by saswatsamal** [anuraghazra/github-readme-stats#1021]
**Describe the bug**
I tried to use your **Repo Card** on my README.md and it showed me the following error (screenshot):
![image](https://user-images.githubusercontent.com/39031660/116130761-38795a80-a6e9-11eb-995c-b6d0d068d9c4.png)

**Expected behavior**
It should have returned the card of my entered repository wrt to my GitHub account.

**Screenshots / Live demo link (paste the github-readme-stats link as markdown image)**
![image](https://user-images.githubusercontent.com/39031660/116130814-49c26700-a6e9-11eb-8689-5a906a8e6b7c.png)

**Comment by saswatsamal** [comment]
This is happening when I'm adding a new theme (`?theme=THEME_NAME`) to it.

**Comment by anuraghazra** [comment]
@saswatsamal which repo? please provide the link. Cannot debug the issue without it.

**Comment by saswatsamal** [comment]
> @saswatsamal which repo? please provide the link. Cannot debug the issue without it.

Link for the repo: [saswatsamal](http://github.com/saswatsamal/saswatsamal/)

**Comment by saswatsamal** [comment]
> > @saswatsamal which repo? please provide the link. Cannot debug the issue without it.
> 
> Link for the repo: [saswatsamal](https://github.com/saswatsamal/saswatsamal/)

For more reference:

- This is where I want to use the card with the theme:
![image](https://user-images.githubusercontent.com/39031660/116138059-fa346900-a6f1-11eb-844c-2738808026b1.png)

- But after adding the theme, it is showing the error:
![image](https://user-images.githubusercontent.com/39031660/116138133-0f10fc80-a6f2-11eb-8362-2484daa1cd0f.png)

**Comment by anuraghazra** [comment]
Works as expected

https://github-readme-stats.vercel.app/api/pin?username=saswatsamal&repo=saswatsamal&theme=highcontrast

You have an error in your link URL you put `?` instead of `&` before theme.

**Comment by saswatsamal** [comment]
> Works as expected
> 
> https://github-readme-stats.vercel.app/api/pin?username=saswatsamal&repo=saswatsamal&theme=highcontrast
> 
> You have an error in your link URL you put `?` instead of `&` before theme.

Oh! Okay! Thank You. ✨
Actually, its been mentioned [here](https://github.com/anuraghazra/github-readme-stats/tree/master/themes#available-themes) to put `?theme=THEME_NAME`.
