### ISSUE TITLE
Please include the ownership and contributions to organizations in the metrics.

### ISSUE THREAD

**Issue by ManuelSchneid3r** [anuraghazra/github-readme-stats#1035]
Not much more to say. I dont see the point In rating private repos only

**Comment by GMkonan** [comment]
Agree, A lot of people contribute a lot for organizations and there is no mention of it in the cards. But to be fair I don't know how possible or impossible is to make this feature, will probably investigate myself :)

**Comment by anuraghazra** [comment]
Duplicate of #1
