### ISSUE TITLE
top langs mistake

### ISSUE THREAD

**Issue by averak** [anuraghazra/github-readme-stats#1037]
**Describe the bug**
I use this service with the following parameters.

- `langs_count` = 10
- `hide` = html, css

Then, Objective-C is displayed at the 10th place, but I have never use it.

I think that it's failing to fetch the top languages.

```
![Top Langs](https://github-readme-stats.vercel.app/api/top-langs/?username=averak&layout=compact&langs_count=10&hide=html,css)
```

**Screenshots / Live demo link (paste the github-readme-stats link as markdown image)**

![image](https://user-images.githubusercontent.com/50389029/116758076-5e389380-aa4a-11eb-8a4a-340006bceaa5.png)

Thank you.

**Comment by averak** [comment]
I think this bug is due to interfering `hide` and `langs_count`.

Increasing the number of `hide` will increase the number of languages ​​displayed.

**Comment by florianbussmann** [comment]
> It seems that the number of displayed language is hide.length + langsCount. parms: langs_count=10&hide=rust,go

This is fixed on a development branch of mine https://github.com/anuraghazra/github-readme-stats/pull/989
![image](https://user-images.githubusercontent.com/3610244/116811445-ab4f5f00-ab49-11eb-8085-b274aa5b1d69.png)

> Then, Objective-C is displayed at the 10th place, but I have never use it.

Afaik the stats indicate the amount of source code of a language in your repositories (incl. forks), so you don't have to actually use a language to get it listed there. I would propose a parameter to hide languages below a user-defined threshold (x percent).

> Result of fetchTopLanguages("averak", 10) is follows. However, it seems that Jupyter Notebook is not displayed in card and Objective-C is displayed instead.

I don't know whats happening there. I get different results for your profile and `Jupyter Notebook` is not listed. Filtering your public repositories also gives no results: https://github.com/averak?tab=repositories&language=jupyter+notebook

```ts
{
  Python: { name: 'Python', color: '#3572A5', size: 342925 },
  'C#': { name: 'C#', color: '#178600', size: 226800 },
  PHP: { name: 'PHP', color: '#4F5D95', size: 204574 },
  JavaScript: { name: 'JavaScript', color: '#f1e05a', size: 128838 },
  Ruby: { name: 'Ruby', color: '#701516', size: 110222 },
  CSS: { name: 'CSS', color: '#563d7c', size: 108813 },
  TypeScript: { name: 'TypeScript', color: '#2b7489', size: 51124 },
  Shell: { name: 'Shell', color: '#89e051', size: 40347 },
  HTML: { name: 'HTML', color: '#e34c26', size: 38528 },
  'Vim script': { name: 'Vim script', color: '#199f4b', size: 33183 },
  C: { name: 'C', color: '#555555', size: 6722 },
  'Objective-C': { name: 'Objective-C', color: '#438eff', size: 6117 },
  Java: { name: 'Java', color: '#b07219', size: 2485 },
  'C++': { name: 'C++', color: '#f34b7d', size: 1983 },
  Jinja: { name: 'Jinja', color: '#a52a22', size: 867 },
  Makefile: { name: 'Makefile', color: '#427819', size: 726 },
  Dockerfile: { name: 'Dockerfile', color: '#384d54', size: 634 },
  Rust: { name: 'Rust', color: '#dea584', size: 546 },
  'Rich Text Format': { name: 'Rich Text Format', color: null, size: 436 },
  Batchfile: { name: 'Batchfile', color: '#C1F12E', size: 115 },
  Assembly: { name: 'Assembly', color: '#6E4C13', size: 70 }
}
```
