### ISSUE TITLE
Style collapses happened when showing icons on stats card

### ISSUE THREAD

**Issue by hi120ki** [anuraghazra/github-readme-stats#104]
When displaying the icon, the characters "contributedTo" and the value appear to overlap.(MacOS Chrome)

![Anurag's github stats](https://github-readme-stats.vercel.app/api?username=anuraghazra&hide=["issues"]&show_icons=true)

The ":" in the "contributedTo: 63" line is not visible on this stats card.

I think this is because the value of x (x="135") in line 21 of src/renderStatsCard.js remains constant without changing by "showIcons".

Can I send a Pull-Request that introduce a new variable "valueOffset" to set x="160" if showIcons is true and x="135" if false?

Thank you for making a great application.I am waiting for comments.

**Comment by anuraghazra** [comment]
Hi @hi120ki thanks for reporting the issue, can you please provide a screenshot instead of that live link

**Comment by hi120ki** [comment]
![screen](https://user-images.githubusercontent.com/12624257/87874877-57cfb280-ca08-11ea-84ff-a60e789abd8d.jpg)

**Comment by anuraghazra** [comment]
Actually this happens because of different systems are rendering the fonts differently and very slight adjustments are leading to whole layout overlapping,, maybe i would make the gap between them larger to solve the issue :D

**Comment by hi120ki** [comment]
Thank you for your reply.
Yes, I think values(2.2k, 1k, 201, 603) should be moved to the right by the width of the icon.(change x=135 into x=160)

![screen](https://user-images.githubusercontent.com/12624257/87875239-dfb6bc00-ca0a-11ea-891f-89826dc1831a.jpg)

This is a screenshot that change x=160 by DevTool. It displays well.

**Comment by hi120ki** [comment]
I change css like this by DevTool.

```
    .stat { 
      font: 600 14px 'Segoe UI', Ubuntu, "Helvetica Neue", Sans-Serif; fill: #333;
    }
```

![screen](https://user-images.githubusercontent.com/12624257/87876985-82c10300-ca16-11ea-8ad7-458a7d4528a3.jpg)

It looks very good. Can I send a Pull-Request?

**Comment by anuraghazra** [comment]
Yup do it :D

**Comment by FOSSforlife** [comment]
Has #106 been deployed yet? I'm still seeing this issue on Linux.

![Screenshot from 2020-07-19 09-48-18](https://user-images.githubusercontent.com/22383534/87880280-5c16b400-c9a5-11ea-83ab-f4e417dcdff6.png)

**Comment by FOSSforlife** [comment]
Interestingly, Chromium doesn't seem to have this issue. Both of them are using the browser `sans-serif` default since they don't have access to Segoe UI or Ubuntu font (I'm on Manjaro). 

![Screenshot from 2020-07-19 10-35-42](https://user-images.githubusercontent.com/22383534/87881146-3a6cfb00-c9ac-11ea-9bc7-2ef41e722927.png)

**Comment by hi120ki** [comment]
Characters seem to be covered in some fonts.
It is impossible to specify a font that will display correctly on all OS by CSS font family settings.
So when showing the icon, the space between characters should be larger.

How about introduce a new variable "valueOffset" to set x="160" if showIcons is true and x="135" if false in src/renderStatsCard.js ?
