### ISSUE TITLE
How to get stars counted from repositories that I'm the main (sole) contributor?

### ISSUE THREAD

**Issue by JunweiLiang** [anuraghazra/github-readme-stats#1042]
**Is your feature request related to a problem? Please describe.**
How to get stars counted from repositories that I'm the main (sole) contributor? Currently they are not counted if the repositories are not owned by me. I'm the main/sole contributor to this [repo](https://github.com/google/next-prediction) of Google so I think this deserves to be credited.

**Describe the solution you'd like**
I'd like the stars from these repo to be counted. This could be a common situation as people go into internships where they have to release code through the companies' accounts.

**Describe alternatives you've considered**
Not sure if there are any easy alternatives.

**Additional context**
My main page: https://github.com/JunweiLiang
The [Google repo](https://github.com/google/next-prediction) is pinned on the main page.

Thanks for the great work!

**Comment by anuraghazra** [comment]
Hi @JunweiLiang this is related to #1

And we are got some good progress on how we can do this and possible solutions to it in this issue please read the discussions, I've also discussed about the star counting issue too! 
https://github.com/anuraghazra/github-readme-stats/issues/1043#issuecomment-833812538

The star counting part is a bit dilemma for me, I'm unable to decide what should be done, Both of the arguments of not counting and counting the stars are viable.

**Comment by JunweiLiang** [comment]
Thanks. It makes sense. Closing this and will follow the other threads.
