### ISSUE TITLE
Language Card `/api/top-langs/` params langs_count is mistake?

### ISSUE THREAD

**Issue by yuiseki** [anuraghazra/github-readme-stats#1045]
**Describe the bug**

When specify params `langs_count` , this app shows more than one langs.

**Expected behavior**

On `/api/top-langs/` , show only rows specify by params `langs_count` .

**Screenshots / Live demo link (paste the github-readme-stats link as markdown image)**

`https://github-readme-stats.vercel.app/api/top-langs/?username=yuiseki&exclude_repo=unity-oculus-quest-template&hide=c&langs_count=4` shows 5 langs!!

![test](https://github-readme-stats.vercel.app/api/top-langs/?username=yuiseki&exclude_repo=unity-oculus-quest-template&hide=c&langs_count=4)

So if you want to show 4 langs, you should specify params to `langs_count=3` .
It's very wired...

![test](https://github-readme-stats.vercel.app/api/top-langs/?username=yuiseki&exclude_repo=unity-oculus-quest-template&hide=c&langs_count=3)

**Additional context**

It happens at my GitHub profile README.md

**Comment by florianbussmann** [comment]
This has been fixed some time ago on my PR #989 and is waiting to be merged @anuraghazra 

https://github-readme-stats-b75kypm3q-florianbussmann.vercel.app/api/top-langs/?langs_count=4&exclude_repo=unity-oculus-quest-template&username=yuiseki&hide=c

![image](https://user-images.githubusercontent.com/3610244/116914462-0cab2700-ac4b-11eb-9999-2ad15e244bbb.png)

**Comment by anuraghazra** [comment]
Fixed via #989

**Comment by yuiseki** [comment]
Thanks for fix this issue!
I love this project and send $5 via paypal.
