### ISSUE TITLE
Add loading animation to Most used language card

### ISSUE THREAD

**Issue by Andre601** [anuraghazra/github-readme-stats#1046]
**Is your feature request related to a problem? Please describe.**
N/A

**Describe the solution you'd like**
The main stats card seems to be the only one having an animation when being loaded*, which is sad when you use other cards like the Most languages one**.

My feature request is to have an animation for this card type too. Right now my idea would be to make the languages appear similar to the text on the stats card (Ease-in-out with 100 transparent to 0 transparent) and have the line showing the distribution of languages "load" (extend from left to right) with each separate language, where each new line will cover less of the previous line to achieve the current look of it.

*I don't use Wakka-time so idk if that one has animations.
**I talk about the compact version.

**Describe alternatives you've considered**
Only alternative I can see is, if I would implement my own solutions, which isn't as easy for me, especially since I can't code in this particular language.

**Additional context**

**Comment by NoushadBug** [comment]
you can check out this, **https://github.com/NoushadBug**

**this stat theme is for any GitHub theme, made by me. It will be suitable. Have a check -** 
`https://github-readme-stats.vercel.app/api?username=noushadBug&title_color=FA8C00&icon_color=CC5160&text_color=949CA5&bg_color=00000000&show_icons=true`

**Comment by Andre601** [comment]
Not really what I was asking for... at all.

**Comment by RedHeadphone** [comment]
[screen-capture.webm](https://user-images.githubusercontent.com/55500003/195656261-62ab7e56-d711-4071-8953-008264a45ebd.webm)
@Andre601 @rickstaa 
Is this animation good? right now it only works on compact

**Comment by rickstaa** [comment]
> [screen-capture.webm](https://user-images.githubusercontent.com/55500003/195656261-62ab7e56-d711-4071-8953-008264a45ebd.webm) @Andre601 @rickstaa Is this animation good? right now it only works on compact

I think it looks great. Looking forward to your PR! 🔥

**Comment by RedHeadphone** [comment]
non compact layout animation
[screen-capture.webm](https://user-images.githubusercontent.com/55500003/195972887-c4a6ec0b-1425-4e90-8d51-59eb5a10ef7f.webm)

**Comment by rickstaa** [comment]
@RedHeadphone I like this! Your animation skills are on fire 🔥.
