### ISSUE TITLE
Weird display error on android

### ISSUE THREAD

**Issue by AdvaitDhingra** [anuraghazra/github-readme-stats#1048]
**Describe the bug**
This is what the readme stats look like on my Android phone (see image)
**Expected behavior**
It look normal

**Screenshots / Live demo link (paste the github-readme-stats link as markdown image)**
![Screenshot_20210505-190359.jpg](https://user-images.githubusercontent.com/62119114/117180827-e2857080-add4-11eb-98fc-6590496ab9b1.jpg)
**Additional context**
Phone: OnePlus 8T

**Comment by AdvaitDhingra** [comment]
@anuraghazra any thoughts ?

**Comment by florianbussmann** [comment]
Duplicates #899

**Comment by AdvaitDhingra** [comment]
Oh, oops 😬
