### ISSUE TITLE
Showing the wrong PR numbers

### ISSUE THREAD

**Issue by Showrin** [anuraghazra/github-readme-stats#1055]
**Describe the bug**
I have 140 closed PRs and 1 open or. But it's showing only 47 prs in the `Total PR` field. Also, I put `true` in the `count_private` param. Here's the link that I used: https://github-readme-stats.vercel.app/api?username=showrin&count_private=true
And here's my profile link: https://github.com/Showrin
Is it showing the PR of this year only? If it is, then I think there should an identifier with the field like `Total PR (2021)`.

**Expected behavior**
It should show 141 in the `Total PR` field.

**Comment by florianbussmann** [comment]
@Showrin I just tried it myself and unfortunately `count_private` has no effect in this case.

However I get the total PR count, including those from private repos, on my own instance of `github-readme-stats` which uses a personal access token of my account that can read my private repositories. If you want to do the same you can find the base instructions to do this here: https://github.com/anuraghazra/github-readme-stats#deploy-on-your-own-vercel-instance

Contrary to the instructions, PRs from private repos still didn't show up until I added the repo scope as shown below

![image](https://user-images.githubusercontent.com/3610244/117886757-fa1a9880-b2af-11eb-8844-2617d00fe90c.png)

https://github.com/anuraghazra/github-readme-stats/blob/fef8bc3a4a4ddb12a5c779e7cae18438231845a7/CONTRIBUTING.md#L72-L74

**Comment by Showrin** [comment]
@florianbussmann Great man, Thanks so much. I deployed it on my own vercel instance and It worked for me. 🚀 🚀 

I think we can close this issue. Thanks again.

**Comment by anuraghazra** [comment]
Great! thanks @florianbussmann for the clarification. And for helping on other issues too. :) 

Closing it now.
