### ISSUE TITLE
Self-deployed Wakapi hints Wakatime user not found, make sure you have a wakatime profile

### ISSUE THREAD

**Issue by jeffxjh** [anuraghazra/github-readme-stats#1059]
**Describe the bug**
Self-deployed Wakapi hints Wakatime user not found, make sure you have a wakatime profile

**Expected behavior**
https://github-readme-stats.vercel.app/api/wakatime?username=xxx&api_domain=mydomain&bg_color=2D3748&title_color=fafafa&icon_color=2F855A&text_color=ffffff&custom_title=My%20Stats%20%F0%9F%9A%80&layout=compact

![image](https://user-images.githubusercontent.com/44387640/118257101-d12d1a00-b4e0-11eb-8334-8cbc5a9203bc.png)

**Comment by florianbussmann** [comment]
As you didn't state your wakapi instance, can you confirm that the following link returns the data that should be visualized?

https://`mydomain`/api/v1/users/`xxx`/stats/last_7_days

**Comment by jeffxjh** [comment]
yes，i can get json data.but the url is  http://mydomain/api/v1/users/xxx/stats/last_7_days.not https ,does that make a difference?

**Comment by florianbussmann** [comment]
Yes @jeffxjh, currently `https` is required

https://github.com/anuraghazra/github-readme-stats/blob/fef8bc3a4a4ddb12a5c779e7cae18438231845a7/src/fetchers/wakatime-fetcher.js#L3-L8

**Comment by jeffxjh** [comment]
thank，After changed domain to SSL, the problem was resolved.
