### ISSUE TITLE
Incorrect total commit count

### ISSUE THREAD

**Issue by priyanshurav** [anuraghazra/github-readme-stats#1061]
**Describe the bug**
The total commit count when `include_all_commits` is set to true is less than the total commit count when `include_all_commits` if set to false.

**Expected behavior**
The total commit count when `include_all_commits` is set to true should be either greater than or equal to the total commit count when `include_all_commits` if set to false.

**Screenshots / Live demo link (paste the github-readme-stats link as markdown image)**
[![First screenshot](https://github-readme-stats.vercel.app/api?username=priyanshurav&show_icons=true)](https://github-readme-stats.vercel.app/api?username=priyanshurav&show_icons=true)

[![Second screenshot](https://github-readme-stats.vercel.app/api?username=priyanshurav&show_icons=true&include_all_commits=true)](https://github-readme-stats.vercel.app/api?username=priyanshurav&show_icons=true&include_all_commits=true)

**Comment by florianbussmann** [comment]
Duplicate of #518
Beware that `include_all_commits=true` uses an experimental API as stated here https://github.com/anuraghazra/github-readme-stats/pull/211/

**Comment by Mohamed-Ayaan358** [comment]
So in that case is there any way for us to fix this issue by ourselves, considering my number of commits has been reduced to 175 from 227.

**Comment by sabertazimi** [comment]
Same issue.

**Comment by rickstaa** [comment]
Duplicate of #1515. Let's track this issue there.
