### ISSUE TITLE
Website for this project

### ISSUE THREAD

**Issue by glaukiol1** [anuraghazra/github-readme-stats#1062]
##  Website for this project

I made a simple website, and deployed it to Vercel. You can find the website [here](https://github-user-stats-glaukiol1.vercel.app/).

This website has the following features;

- You can see your current calculated score! People want to see how close they are to the next rank, for example, I wanted to see how close I am to A++, and I found out using my website.
- You can search anyone on GitHub by username, just type their username, and you will get all of their stats, including their score!
- It shows you the stats card for the user you searched.

Tell me what you think about it, and any suggestions are welcome. Also, the source code can be found [here](https://github.com/glaukiol1/github-user-stats-website), its a detached fork. Thanks!

**Comment by anuraghazra** [comment]
Hi @glaukiol1 very nice work! 

One thing i just want to emphasis that you don't have to copy paste the original code of the github-readme-stats you can just do this via a fetch. just fetching the github-readme-stats URL should also work, that way it will get new features and you don't have to manually update any changes.

**Comment by glaukiol1** [comment]
Yes, but as far as i know, the github-readme-stats doesnt provide the score, thats why im using my own version of the code.
