### ISSUE TITLE
Added fork num

### ISSUE THREAD

**Issue by Han-YLun** [anuraghazra/github-readme-stats#1063]
Can I add a fork number to my personal card?

**Comment by filiptronicek** [comment]
@Han-YLun could you please elaborate a little bit? It is not really clear what you're trying to achieve. A number of forks on your profile? A number of commits to forks?

**Comment by jukamonk** [comment]
> @Han-YLun could you please elaborate a little bit? It is not really clear what you're trying to achieve. A number of forks on your profile? A number of commits to forks?

I think he means "number of forks"

**Comment by net-on** [comment]
> I think he means "number of forks"

I agree.

**Comment by rickstaa** [comment]
Closing in favour of #1247
