### ISSUE TITLE
How to add yaml or yml to the top languages ?

### ISSUE THREAD

**Issue by jinkyler** [anuraghazra/github-readme-stats#1068]

**Comment by rickstaa** [comment]
I'm not sure if I understand your question but adding `yaml` or `yml` to the top languages is quite straightforward. This language shows up when the number of bytes in your repositories is more than the other languages you use. Using the `hide` and `language_count` arguments (see https://github.com/anuraghazra/github-readme-stats#language-card-exclusive-options).
