### ISSUE TITLE
Spanish translation request

### ISSUE THREAD

**Issue by JoseDeFreitas** [anuraghazra/github-readme-stats#107]
Hello 👋, my name is José De Freitas, I'm a native Spanish speaker.

I'm opening this issue because I saw that recently there was added Chinese translation, This had me wondering if you're looking for translations. If so, I could help translate this project into Spanish.
I could translate the all this project into Spanish. Let me know if you're interested.

Have a great day ✌.

**Comment by anuraghazra** [comment]
Yes! That would be awesome @JoseDeFreitas thank you very much!! 😄

**Comment by nombrekeff** [comment]
I could also help with this @anuraghazra & @JoseDeFreitas if you want, I'm also Spanish!

**Comment by anuraghazra** [comment]
Help is always appreciated @nombrekeff :D

**Comment by JoseDeFreitas** [comment]
Hello 👋.
I've just completed the Spanish translation of the README file (#116)
@nombrekeff you can check the file and change/fix something if you consider ✌.

**Comment by nombrekeff** [comment]
Sure, I will take a look right now!

**Comment by nombrekeff** [comment]
This can be closed, as it has been added in #116

**Comment by anuraghazra** [comment]
Thanks @JoseDeFreitas @nombrekeff for helping with translation :D
