### ISSUE TITLE
stats and languages card not updated automatically.

### ISSUE THREAD

**Issue by predator2v0** [anuraghazra/github-readme-stats#1073]
**Describe the bug**
A clear and concise description of what the bug is.:
- The GitHub stats card counters and data in the most used languages card in the README file are not updated automatically after changes are made to my repositories. however, when I open the links of the corresponding cards in separate tabs manually, they show the correct data.

**Expected behavior**
- It is supposed to appear the changes in the cards in the readme of the profile after some changes are made to the repositories of the user.

**Comment by florianbussmann** [comment]
This may be related to the caching used by GitHub https://github.com/anuraghazra/github-readme-stats/issues/935#issuecomment-803246873
