### ISSUE TITLE
More than 10 languages

### ISSUE THREAD

**Issue by mateusfg7** [anuraghazra/github-readme-stats#1074]
Add a param to show all the languages on the profile, not only the top 10 languages.

**Comment by anuraghazra** [comment]
We do have langs_count flag which you can use. 

http://github-readme-stats.vercel.app/api/top-langs/?username=mateusfg7&langs_count=20

**Comment by florianbussmann** [comment]
@anuraghazra but the param `langs_count` is currently clamped to 1 .. 10. Shouldn't we lift this limitation?

https://github.com/anuraghazra/github-readme-stats/blob/2b0efb8d299e614d1baf17c8a41a645146c5249b/src/cards/top-languages-card.js#L89

Also see this comment about the arbitrary limit of 10 languages: https://github.com/anuraghazra/github-readme-stats/issues/909#issuecomment-788896431
