### ISSUE TITLE
Maximum retries exceeded

### ISSUE THREAD

**Issue by YuZaGa** [anuraghazra/github-readme-stats#1077]
Maximum retries exceeded 
Make sure the provided username is not an organization

This is the error message comes instead of displaying the stats.

**Comment by jrbenriquez** [comment]
Getting the same as above :)

**Comment by YuZaGa** [comment]
> UPDATE:
> Working now just used the link on the Readme. All good!

Same. Replaced the link in my readme with the link in project's readme and it started working again.
