### ISSUE TITLE
How to set background image and `https://xxx.github.io` page

### ISSUE THREAD

**Issue by englianhu** [anuraghazra/github-readme-stats#1085]
### 1st

1stly, how to add background image to `Readme`?

I tried to use RStudio & css to set it as we can see via https://player.vimeo.com/video/554768907, its work but doesn't shows on GitHub page. 

Expect outcome:

![GitHub Readme CSS background](https://i.imgur.com/piL8omI.png)

Actual Outcome:

![2021-05-26_00-15](https://user-images.githubusercontent.com/7227582/119523225-8c926000-bdb7-11eb-9024-77acda57bd42.png)

### 2nd

2ndly, how to add `https://xxx.github.io` to `Readme`?

![https://xxx.github.io](https://user-images.githubusercontent.com/7227582/119521335-01649a80-bdb6-11eb-81e1-46825fe3e43b.png)

---

Reference:

- [How to add a background image to Github README.md](https://stackoverflow.com/questions/60426626/how-to-add-a-background-image-to-github-readme-md)

**Comment by florianbussmann** [comment]
> 1stly, how to add background image to `Readme`?
> 

afaik this is not possible on GitHub.




> 2ndly, how to add `https://xxx.github.io` to `Readme`?
> 

Using repo cards as shown below

```html
<a href="https://github.com/englianhu/englianhu.github.io">
  <img align="center" src="https://github-readme-stats.vercel.app/api/pin/?username=englianhu&repo=englianhu.github.io&title_color=A10115&icon_color=DEG,EDAE01&text_color=EDAE01&bg_color=DEG,002C54,4CB5F5&show_icons=true" />
</a>
```

<a href="https://github.com/englianhu/englianhu.github.io">
  <img align="center" src="https://github-readme-stats.vercel.app/api/pin/?username=englianhu&repo=englianhu.github.io&title_color=A10115&icon_color=DEG,EDAE01&text_color=EDAE01&bg_color=DEG,002C54,4CB5F5&show_icons=true" />
</a>

**Comment by anuraghazra** [comment]
This seems like an github specific issue not related to grs, and seems like florain already answered your second question. So closing this now. 

Feel free to open another one if any questions.
