### ISSUE TITLE
Something went wrong Error 

### ISSUE THREAD

**Issue by CanasDev** [anuraghazra/github-readme-stats#1093]
Hi, I'm getting this error : 
![Screenshot_20210530_073309](https://user-images.githubusercontent.com/70149057/120094629-605d4300-c119-11eb-837a-5c968f61e75a.jpg)

**Comment by CanasDev** [comment]
How can I solve
My account isn't an organization

**Comment by kazuhitonakayama** [comment]
@CanasDev 
Hi, can I see your code in README.md for the relevant part.

I also encountered same error and I fixed this error by rewrite code in README.md.
Please write your code like below

`https://github-readme-stats.vercel.app/api?username=[your username]`

**Comment by kazuhitonakayama** [comment]
Please refer to README.md👍
https://github.com/anuraghazra/github-readme-stats#adding-private-contributions-count-to-total-commits-count

**Comment by CanasDev** [comment]
Thanks! It's Solved!

**Comment by FelipeFama** [comment]
Eu também estou com o mesmo erro que foi publicado acima.

**Comment by palomarizzon** [comment]
@FelipeFama vc pode recordar o código, salvar e depois colar novamente.

**Comment by anic4cio** [comment]
Basta apagar o conteúdo do README, faz um commit e depois reverte o commit com o comando git revert <commit hash>.
Vc pegar o hash do commit com o comando git log

**Comment by FelipeFama** [comment]
@palomarizzon conseguir resolver.

**Comment by LucasLuisBorges** [comment]
Arrumei só tirando as letras maiúsculas do username: de LucasLuisBorges => lucasluisborges

**Comment by CinthyaSSoares** [comment]
O meu não resolveu mesmo salvando e colando ou tirando as letras maiúsculas, alguém sabe como resolver?

**Comment by LucasLuisBorges** [comment]
> O meu não resolveu mesmo salvando e colando ou tirando as letras maiúsculas, alguém sabe como resolver?

Fiz um commit para você, dá uma olhadinha!

**Comment by Marco-Merini** [comment]
> Arrumei só tirando as letras maiúsculas do username: de LucasLuisBorges => lucasluisborges

arrumei tirando as letras maiúsculas do username tbm

**Comment by evelyneds** [comment]
O próprio site com os exemplos está com essa mensagem de erro:

https://github.com/anuraghazra/github-readme-stats#adding-private-contributions-count-to-total-commits-count

Não consegui resolver

**Comment by guirdy** [comment]
I solved this problem by adding (sigma-five) in url
Before: https://github-readme-stats.vercel.app/api
After: https://github-readme-stats-sigma-five.vercel.app/api

**Comment by hasan-ylmz** [comment]
ı had this problem and tried use gitHub's new media feature solved this . 
Reference link: https://www.javascripting.com/view/github-readme-stats

**Comment by MarVinReisSantos** [comment]
> Arrumei só tirando as letras maiúsculas do username: de LucasLuisBorges => lucasluisborges

Sua resposta me ajudou a resolver o problema, muito obrigado.

**Comment by lucasnds** [comment]
Estou o esse erro, como resolver?
