### ISSUE TITLE
❗[URGENT] Maximum Retries Exceeded | Github Stats README Error For All Users❗

### ISSUE THREAD

**Issue by aryashah2k** [anuraghazra/github-readme-stats#1095]
![image](https://user-images.githubusercontent.com/73865728/120110395-dcdc3a00-c18a-11eb-8569-0c99dbdcccd1.png)

It seems that the feature has surely blown up throughout Github Users who have their own README and I cross-checked with all the users I knew, they face the same problem.

I'm not sure if I should tag you guys but either you could help fix this or bring it to Anurag's notice. @panosru @Awilum @omrilotan @ahmadawais @koppor . Prior apologies for tagging everyone but I hope this can be figured out.

Shall close this issue as soon as it gets resolved

**Comment by povsister** [comment]
👀  +1 got this error.

**Comment by erdkse** [comment]
+1

**Comment by predator2v0** [comment]
this will help: https://www.youtube.com/watch?v=n6d4KHSKqGk&t=107s or refer #1094

**Comment by aryashah2k** [comment]
> this will help: https://www.youtube.com/watch?v=n6d4KHSKqGk&t=107s or refer #1094
 Thanks, shall refer and reopen this issue in case errors persist!

**Comment by panosru** [comment]
@aryashah2k I will look into it as soon as possible, I can't now because I have to deliver a TOGAF & ADM by tomorrow. @predator2v0  thanks for sharing the link, I will take a look into that as well.

**Comment by panosru** [comment]
@aryashah2k sorry for my late reply, and yes, as @predator2v0 mentioned this is exactly what you should do. I did that on day 1 of using that stats feature, I created my own vercel instance just to have peace of mind in the future and it works fine.
