### ISSUE TITLE
github-readme-stats stopped working due to vercel error

### ISSUE THREAD

**Issue by DEMON1A** [anuraghazra/github-readme-stats#1096]
https://github.com/DEMON1A/DEMON1A
![image](https://user-images.githubusercontent.com/54229853/120110561-38e49580-c16e-11eb-97d7-979e6139107b.png)

**Comment by jspw** [comment]
same here...

**Comment by IslamShg** [comment]
same

**Comment by DEMON1A** [comment]
The issue is fixed now btw

**Comment by phoebe-leong** [comment]
yeah its fixed

**Comment by dfalis** [comment]
Same issue here

**Comment by DEMON1A** [comment]
Sorry I forgot to close this issue, Thanks for your work fixing this <3

**Comment by MrLivixx** [comment]
this problem is relevant
![image](https://user-images.githubusercontent.com/54632865/127412936-657950f2-652a-4863-85b7-9b733800a1eb.png)
