### ISSUE TITLE
Github-Readme-Stats not working

### ISSUE THREAD

**Issue by Jassi10000** [anuraghazra/github-readme-stats#1097]
**Describe the bug**

Github Readme Stats is not working , it shows error 
I attached the screenshot of that below

**Expected behavior**
I expected it to show my daily readme stats

**Screenshots / Live demo link (paste the github-readme-stats link as markdown image)**

![image](https://user-images.githubusercontent.com/64856348/120111137-5d506a00-c18e-11eb-97dc-ce04d35be499.png)

**Additional context**

**Comment by florianbussmann** [comment]
Duplicates #1096

**Comment by anuraghazra** [comment]
Seems to be working, but I'll figure out the cause of the error. Probably because the github tokens got expired.

**Comment by Carson3377** [comment]
having the same issue, can sb help me

**Comment by rickstaa** [comment]
> having the same issue, can sb help me https://github.com/Carson3377/CreativeCoderz3377

This is a known issue please checkout #1471.

**Comment by aimedivin** [comment]
For me I use this read me stat generator -> https://gprm.itsvg.in/
and it worked on my side

**Comment by vitorabujamra** [comment]
> For me I use this read me stat generator -> https://gprm.itsvg.in/ and it worked on my side
> 
> or
> 
> replace your src value with these ones below, remember to use your usernames
> 
> https://github-readme-stats.vercel.app/api?username=aimedivin&theme=highcontrast&hide_border=false&include_all_commits=false&count_private=false
> 
> https://github-readme-stats.vercel.app/api/top-langs/?username=aimedivin&theme=highcontrast&hide_border=false&include_all_commits=false&count_private=false&layout=compact

Hello my friend,
I tried use this with my username with no success.
But when i use the GraphQL API Explorer works perfect.

What i'm doing wrong?

**Comment by qwerty541** [comment]
> > For me I use this read me stat generator -> https://gprm.itsvg.in/ and it worked on my side
> > or
> > replace your src value with these ones below, remember to use your usernames
> > https://github-readme-stats.vercel.app/api?username=aimedivin&theme=highcontrast&hide_border=false&include_all_commits=false&count_private=false
> > https://github-readme-stats.vercel.app/api/top-langs/?username=aimedivin&theme=highcontrast&hide_border=false&include_all_commits=false&count_private=false&layout=compact
> 
> Hello my friend, I tried use this with my username with no success. But when i use the GraphQL API Explorer works perfect.
> 
> What i'm doing wrong?

Answered your question there https://github.com/anuraghazra/github-readme-stats/discussions/1878#discussioncomment-8806918
