### ISSUE TITLE
Top Languages Card can be misleading as it only looks at public repos, let me specify title in querystring

### ISSUE THREAD

**Issue by jtara1** [anuraghazra/github-readme-stats#1099]
**Is your feature request related to a problem? Please describe.**
Top Languages Card can be misleading as it only looks at public repos

**Describe the solution you'd like**
Top Languages Card should either default to something else, or let me decide what to title it in the querystring. 
Or, if you want control over what we can title it, just enumerate some possibilities and let me specify in querystring like `titleType=2` which could then title it "Most Used Languages in Public Repositories".

**Additional context**

**Comment by florianbussmann** [comment]
> let me decide what to title it in the querystring.

You can already do that using the param `custom_title`:

`[![My Most Used Languages in Public Repos](https://github-readme-stats.vercel.app/api/top-langs/?username=jtara1&layout=compact&hide=html,OpenEdge%20ABL,ShaderLab&custom_title=Most%20Used%20Languages%20in%20Public%20Repos)](https://github.com/anuraghazra/github-readme-stats)`

[![My Most Used Languages in Public Repos](https://github-readme-stats.vercel.app/api/top-langs/?username=jtara1&layout=compact&hide=html,OpenEdge%20ABL,ShaderLab&custom_title=Most%20Used%20Languages%20in%20Public%20Repos)](https://github.com/anuraghazra/github-readme-stats)

⚠ the card won't scale with large titles

> Top Languages Card can be misleading as it only looks at public repos

you can also let it count private repos if you like by deploying your own instance of `github-readme-stats` on vercel

**Comment by Cubik65536** [comment]
> you can also let it count private repos if you like by deploying your own instance of `github-readme-stats` on vercel

I deployed my own instance of `github-readme-stats` on vercel, and also used a token with access to private repos for `PAT_1`, but the languages of private repo is still not counted, what should I do then?
