### ISSUE TITLE
Transparent Theme

### ISSUE THREAD

**Issue by FayasNoushad** [anuraghazra/github-readme-stats#1100]
Please add transparent theme

**Comment by NoushadBug** [comment]
you can check out this, **https://github.com/NoushadBug**

**this stat theme is for any GitHub theme, made by me. It will be suitable. Have a check -** 
`https://github-readme-stats.vercel.app/api?username=noushadBug&title_color=FA8C00&icon_color=CC5160&text_color=949CA5&bg_color=00000000&show_icons=true`

**Comment by FayasNoushad** [comment]
Thanks
