### ISSUE TITLE
Maximum Tries Exceeded

### ISSUE THREAD

**Issue by mattfrancis888** [anuraghazra/github-readme-stats#1103]
The Bug looks like this:
![image](https://user-images.githubusercontent.com/22691408/120239390-2d57a400-c22c-11eb-826e-f4be811a46cb.png)

My code:
`<img align="center" alt="Github Stats" src="https://github-readme-stats.codestackr.vercel.app/api?username=mattfrancis888&show_icons=true&hide_border=true&include_all_commits=true" />`

Not sure why it's occurring.

**Comment by florianbussmann** [comment]
It looks like you are using an outdated fork

> github-readme-stats.**codestackr**.vercel.app

=> https://github.com/codeSTACKr/github-readme-stats/branches (last activity 10 months ago)

The master repo works

`<img align="center" alt="Github Stats" src="https://github-readme-stats.vercel.app/api?username=mattfrancis888&show_icons=true&hide_border=true&include_all_commits=true" />`

<img align="center" alt="Github Stats" src="https://github-readme-stats.vercel.app/api?username=mattfrancis888&show_icons=true&hide_border=true&include_all_commits=true" />

**Comment by alhassanv** [comment]
https://github-readme-stats.codestackr.vercel.app/api?username=alhassanv&show_icons=true&hide_border=true&theme=tokyonight

Mine doesn't work either.

**Comment by mattfrancis888** [comment]
Thank you @florianbussmann and @alhassanv!
