### ISSUE TITLE
Include Forks for Language Cards

### ISSUE THREAD

**Issue by StrangeRanger** [anuraghazra/github-readme-stats#1108]
**Is your feature request related to a problem? Please describe.**
I have several forked repositories that I do quite a bit of active development on. As it stands right now, the language used in the repos isn't calculated by the language card, which kind of results in an inaccurate representation of what languages I used, and which I use most often/is my most used. 

**Describe the solution you'd like**
Add the ability to include foked repos in the language card.

**Note**
It looks like someone had already made an [issue on this](https://github.com/anuraghazra/github-readme-stats/issues/905), but no one ever got back to them on it.

**Comment by florianbussmann** [comment]
This is true and it seems fairly easy to change that (add a query parameter to the top languages card that will include forks)
https://github.com/anuraghazra/github-readme-stats/blob/fef8bc3a4a4ddb12a5c779e7cae18438231845a7/src/fetchers/top-languages-fetcher.js#L11-L12

However afaik this part will just include the overall repo stats for your forks, not the actual commits you made on the fork

**Comment by StrangeRanger** [comment]
By overall stats, do you just mean the language card stuff? Also, I have no idea how to do query stuff with JS, though I did find that if I remove the `isFork: false` part, it will include forked repos for the language card.

**Comment by florianbussmann** [comment]
Regarding the overall stats I wanted to highlight that this change will only include further repos (your forks) to be used for the top languages card. It won't filter on your commits to gather which languages you actually used.
So if you fork a repo it will automatically add the current language stats of this fork, even though you never contributed to this fork.


For the query parameter look at the changes I would propose: https://github.com/florianbussmann/github-readme-stats/commit/2cd6f422d020e181fbde7eec71eae702dfdbce31

And here is a before and after (`include_forks=true`) for your language card 

`https://github-readme-stats-i270cdk5i-florianbussmann.vercel.app/api/top-langs/?username=StrangeRanger&custom_title=Most%20Used%20Languages%20including%20forks&layout=compact&theme=material-palenight&include_forks=true&exclude_repo=EWU-CSCD,customized-unix-terminal,github-readme-stats`

<a href="https://github.com/anuraghazra/github-readme-stats">
  <img align="center" src="https://github-readme-stats-i270cdk5i-florianbussmann.vercel.app/api/top-langs/?username=StrangeRanger&custom_title=Most%20Used%20Languages%20without%20forks&layout=compact&theme=material-palenight&include_forks=false&exclude_repo=EWU-CSCD,customized-unix-terminal,github-readme-stats" />
</a>
<a href="https://github.com/anuraghazra/convoychat">
  <img align="center" src="https://github-readme-stats-i270cdk5i-florianbussmann.vercel.app/api/top-langs/?username=StrangeRanger&custom_title=Most%20Used%20Languages%20including%20forks&layout=compact&theme=material-palenight&include_forks=true&exclude_repo=EWU-CSCD,customized-unix-terminal,github-readme-stats" />
</a>

**Comment by StrangeRanger** [comment]
Alright, that makes sense. Thank you.

**Comment by zach83** [comment]
@florianbussmann has there been any update on a possible pull request regarding this issue?

**Comment by zach83** [comment]
#505
