### ISSUE TITLE
Having trouble Deploying it 

### ISSUE THREAD

**Issue by anushkrishnav** [anuraghazra/github-readme-stats#111]
I deployed the project and clicked on the domain which lead me to the index of/ page where I clicked on the api folder I am getting an error not able to access the folder https://user-stats.vercel.app/api?username=anushkrishnav
It says Maximum retries exceeded

**Comment by anuraghazra** [comment]
Please provide more info :) 

Which link you tried?

**Comment by anushkrishnav** [comment]
I deployed the project and clicked on the domain which lead me to the index of/ page  when I clicked on the api folder I am getting an error not able to access the folder

**Comment by anuraghazra** [comment]
It says "Maximum retries exceeded" go to your vercel project settings and instead of the GITHUB_TOKEN rename it to PAT_1 [read the docs for more info](https://github.com/anuraghazra/github-readme-stats#deploy-on-your-own-vercel-instance)

**Comment by anushkrishnav** [comment]
> It says "Maximum retries exceeded" go to your vercel project settings and instead of the GITHUB_TOKEN rename it to PAT_1 [read the docs for more info](https://github.com/anuraghazra/github-readme-stats#deploy-on-your-own-vercel-instance)

I did it still no change ... Should I promote the deployment to production ?
