### ISSUE TITLE
Missing s in possessive for names ending with x?

### ISSUE THREAD

**Issue by unixfy** [anuraghazra/github-readme-stats#1110]
**Describe the bug**

It seems like there is an "s" missing after the apostrophe in the possessive for names ending in x. For instance, my name "Alex" displays as "Alex' GitHub Stats" rather than "Alex's GitHub Stats". 

**Expected behavior**

I would expect that it is displayed as "Alex's" rather than "Alex'".

**Screenshots / Live demo link (paste the github-readme-stats link as markdown image)**

![Unixfy's GitHub stats](https://github-readme-stats.vercel.app/api?username=unixfy&show_icons=true&count_private=true&theme=vue)

**Comment by florianbussmann** [comment]
Duplicates #636 and seems to be on purpose
