### ISSUE TITLE
Can`t find wakaTime data  

### ISSUE THREAD

**Issue by shaoxiongdu** [anuraghazra/github-readme-stats#1112]
**Describe the [bug**](url)
The user name is set in wakatime, as shown in the figure below 

![imageUrlOnline](https://gitee.com/ShaoxiongDu/imageBed/raw/master/image-20210604173932751.png)
The corresponding API request interface is set in the readme file of GitHub 
https://github-readme-stats.vercel.app/api/wakatime?&username=shaoxiongdu&compact=layout

But [no coding activity this week] is always displayed

Actually, there are, as shown in the figure below

![imageUrlOnline](https://gitee.com/ShaoxiongDu/imageBed/raw/master/20210604174456.png)

Thank you so much!

**Comment by florianbussmann** [comment]
Have you checked the option "Display languages, editors, os, categories publicly" at https://wakatime.com/settings/profile ? Because on your public profile (https://wakatime.com/@shaoxiongdu) the coding time is available but no languages are listed..

**Comment by shaoxiongdu** [comment]
thank you !  is ok

**Comment by Muhammadyusuf96** [comment]
In my case, the statistics have not been updated for a week

**Comment by nemchik** [comment]
I seem to be having strange issues with this, probably related.

Here are all the URLs I tried
| URL | Status |
|-|-|
| https://github-readme-stats.vercel.app/api/wakatime?username=nemchik&theme=dark&layout=compact&range=last_7_days | does not work |
| https://github-readme-stats.vercel.app/api/wakatime?username=nemchik&theme=dark&layout=compact | half working? |
| https://github-readme-stats.vercel.app/api/wakatime?username=nemchik&theme=dark | works |
| https://github-readme-stats.vercel.app/api/wakatime?username=nemchik | works |
|-|-|
| https://github-readme-stats.vercel.app/api/wakatime?username=@nemchik&theme=dark&layout=compact&range=last_7_days | does not work |
| https://github-readme-stats.vercel.app/api/wakatime?username=@nemchik&theme=dark&layout=compact | works |
| https://github-readme-stats.vercel.app/api/wakatime?username=@nemchik&theme=dark | works |
| https://github-readme-stats.vercel.app/api/wakatime?username=@nemchik | works |

It's odd that the `@` in the username makes a difference for one of the links.

**Comment by Kalsyc** [comment]
I tried the above but it seems like my wakatime is still not being updated? The only time I manage to update it is when I change the link.

**Comment by florianbussmann** [comment]
@Muhammadyusuf96 @nemchik @Kalsyc 
Could you try changing `Display code time publicly` to `Last 7 Days` at https://wakatime.com/settings/profile?
The wakatime card should then update every 4 hours or whatever timerange you specify in the card parameter `cache_seconds`.

@nemchik specifying `last_7_days` (https://github-readme-stats.vercel.app/api/wakatime?username=nemchik&theme=dark&layout=compact&range=last_7_days) does not work because wakatime returns `{"error":"Forbidden"}` at https://wakatime.com/api/v1/users/muhammadyusuf96/stats/last_7_days
The same error occurs on the other profiles that reported issues with stats that are not up to date. It should be resolved if you change the privacy setting to `Last 7 Days`

**Comment by nemchik** [comment]
After changing `Display code time publicly` to `Last 7 Days` at https://wakatime.com/settings/profile it seems all of the URLs in the table I originally posted work correctly (including the ones with the `range=last_7_days` URL parameter).

Is this a bug with the wakatime API? I would think I should be able to set `All Time` but still request `last_7_days` from the API?

**Comment by florianbussmann** [comment]
> Is this a bug with the wakatime API? I would think I should be able to set `All Time` but still request `last_7_days` from the API?

I don't think this is a bug, but it may be a limitation of the free plan of wakatime.
The selected time range also seems to affect the caching on wakatimes end: `For accounts subscribed to the free plan, time ranges >= one year are updated on the first request. It’s best to always check is_up_to_date and retry your request when the response is stale.` (https://wakatime.com/developers#stats)

> Additional thought: If I set Display code time publicly to Last 7 Days then the range=last_7_days URL parameter should not be needed, because only the last 7 days would be shared by the API anyway.

Thats true. I think the parameter `range` is only interesting for users with a paid membersip or a self-hosted instance of wakatime, because the allowed values `last_7_days`, `last_30_days`, `last_6_months`, or `last_year` all return `Forbidden` unless you change the option `Display code time publicly` beforehand, but some of them aren't even provided in the dropdown.

**Comment by nemchik** [comment]
That makes sense. I was unaware that free/paid affected this. My account with wakatime is only a few days old at this point (started using it because of the widget in this repo).

Maybe it would be beneficial if the readme included some information about this?

**Comment by Kalsyc** [comment]
> @Muhammadyusuf96 @nemchik @Kalsyc
> Could you try changing `Display code time publicly` to `Last 7 Days` at https://wakatime.com/settings/profile?
> The wakatime card should then update every 4 hours or whatever timerange you specify in the card parameter `cache_seconds`.
> 
> @nemchik specifying `last_7_days` (https://github-readme-stats.vercel.app/api/wakatime?username=nemchik&theme=dark&layout=compact&range=last_7_days) does not work because wakatime returns `{"error":"Forbidden"}` at https://wakatime.com/api/v1/users/muhammadyusuf96/stats/last_7_days
> The same error occurs on the other profiles that reported issues with stats that are not up to date. It should be resolved if you change the privacy setting to `Last 7 Days`

Yes, it seems like that updated instantly once I changed the setting to `Last 7 Days` on my profile. Thanks for the help!

**Comment by Muhammadyusuf96** [comment]
@florianbussmann Prior to my comment here, was tuned in for "Last 7 Days". An hour later, in my opinion, changed to "All time".  But then statistics was updated at evening.

**Comment by carepollo** [comment]
I have the same problem

**Comment by rickstaa** [comment]
**Shaoxiongdu**

@shaoxiongdu I can not reproduce.

[![Harlok's wakatime stats](https://github-readme-stats.vercel.app/api/wakatime?username=shaoxiongdu)](https://github.com/anuraghazra/github-readme-stats)

[![Harlok's wakatime stats](https://github-readme-stats.vercel.app/api/wakatime?username=shaoxiongdu)](https://github.com/anuraghazra/github-readme-stats)

**Carepollo**

@carepollo your profile doesn't appear to be public (see https://wakatime.com/@Carepollo).

[![Harlok's wakatime stats](https://github-readme-stats.vercel.app/api/wakatime?username=Carepollo)](https://github.com/anuraghazra/github-readme-stats)

[![Harlok's wakatime stats](https://github-readme-stats.vercel.app/api/wakatime?username=Carepollo)](https://github.com/anuraghazra/github-readme-stats)

**Comment by carepollo** [comment]
> **Shaoxiongdu**
> 
> @shaoxiongdu I can not reproduce.
> 
> [![Harlok's wakatime stats](https://camo.githubusercontent.com/26d24bf3be238ee0c26c76edc6150624472a6eb9f16a3b7706888ab744caa38a/68747470733a2f2f6769746875622d726561646d652d73746174732e76657263656c2e6170702f6170692f77616b6174696d653f757365726e616d653d7368616f78696f6e676475)](https://github.com/anuraghazra/github-readme-stats)
> 
> [![Harlok's wakatime stats](https://camo.githubusercontent.com/26d24bf3be238ee0c26c76edc6150624472a6eb9f16a3b7706888ab744caa38a/68747470733a2f2f6769746875622d726561646d652d73746174732e76657263656c2e6170702f6170692f77616b6174696d653f757365726e616d653d7368616f78696f6e676475)](https://github.com/anuraghazra/github-readme-stats)
> 
> **Carepollo**
> 
> @carepollo your profile doesn't appear to be public (see https://wakatime.com/@Carepollo).
> 
> [![Harlok's wakatime stats](https://camo.githubusercontent.com/9e95b4d2d7082e1e59d33a1f72fa41fe81caf5f2b52178ced5572f67ad39218f/68747470733a2f2f6769746875622d726561646d652d73746174732e76657263656c2e6170702f6170692f77616b6174696d653f757365726e616d653d43617265706f6c6c6f)](https://github.com/anuraghazra/github-readme-stats)
> 
> [![Harlok's wakatime stats](https://camo.githubusercontent.com/9e95b4d2d7082e1e59d33a1f72fa41fe81caf5f2b52178ced5572f67ad39218f/68747470733a2f2f6769746875622d726561646d652d73746174732e76657263656c2e6170702f6170692f77616b6174696d653f757365726e616d653d43617265706f6c6c6f)](https://github.com/anuraghazra/github-readme-stats)

My username in wakatime is @chickenface

**Comment by rickstaa** [comment]
> > **Shaoxiongdu**
> > @shaoxiongdu I can not reproduce.
> > [![Harlok's wakatime stats](https://camo.githubusercontent.com/26d24bf3be238ee0c26c76edc6150624472a6eb9f16a3b7706888ab744caa38a/68747470733a2f2f6769746875622d726561646d652d73746174732e76657263656c2e6170702f6170692f77616b6174696d653f757365726e616d653d7368616f78696f6e676475)](https://github.com/anuraghazra/github-readme-stats)
> > [![Harlok's wakatime stats](https://camo.githubusercontent.com/26d24bf3be238ee0c26c76edc6150624472a6eb9f16a3b7706888ab744caa38a/68747470733a2f2f6769746875622d726561646d652d73746174732e76657263656c2e6170702f6170692f77616b6174696d653f757365726e616d653d7368616f78696f6e676475)](https://github.com/anuraghazra/github-readme-stats)
> > **Carepollo**
> > @carepollo your profile doesn't appear to be public (see https://wakatime.com/@Carepollo).
> > [![Harlok's wakatime stats](https://camo.githubusercontent.com/9e95b4d2d7082e1e59d33a1f72fa41fe81caf5f2b52178ced5572f67ad39218f/68747470733a2f2f6769746875622d726561646d652d73746174732e76657263656c2e6170702f6170692f77616b6174696d653f757365726e616d653d43617265706f6c6c6f)](https://github.com/anuraghazra/github-readme-stats)
> > [![Harlok's wakatime stats](https://camo.githubusercontent.com/9e95b4d2d7082e1e59d33a1f72fa41fe81caf5f2b52178ced5572f67ad39218f/68747470733a2f2f6769746875622d726561646d652d73746174732e76657263656c2e6170702f6170692f77616b6174696d653f757365726e616d653d43617265706f6c6c6f)](https://github.com/anuraghazra/github-readme-stats)
> 
> My username in wakatime is @ChickenFace

Thanks! Your problem will be resolved when https://github.com/anuraghazra/github-readme-stats/pull/2707 is merged!

**Comment by rickstaa** [comment]
> > **Shaoxiongdu**
> > @shaoxiongdu I can not reproduce.
> > [![Harlok's wakatime stats](https://camo.githubusercontent.com/26d24bf3be238ee0c26c76edc6150624472a6eb9f16a3b7706888ab744caa38a/68747470733a2f2f6769746875622d726561646d652d73746174732e76657263656c2e6170702f6170692f77616b6174696d653f757365726e616d653d7368616f78696f6e676475)](https://github.com/anuraghazra/github-readme-stats)
> > [![Harlok's wakatime stats](https://camo.githubusercontent.com/26d24bf3be238ee0c26c76edc6150624472a6eb9f16a3b7706888ab744caa38a/68747470733a2f2f6769746875622d726561646d652d73746174732e76657263656c2e6170702f6170692f77616b6174696d653f757365726e616d653d7368616f78696f6e676475)](https://github.com/anuraghazra/github-readme-stats)
> > **Carepollo**
> > @carepollo your profile doesn't appear to be public (see https://wakatime.com/@Carepollo).
> > [![Harlok's wakatime stats](https://camo.githubusercontent.com/9e95b4d2d7082e1e59d33a1f72fa41fe81caf5f2b52178ced5572f67ad39218f/68747470733a2f2f6769746875622d726561646d652d73746174732e76657263656c2e6170702f6170692f77616b6174696d653f757365726e616d653d43617265706f6c6c6f)](https://github.com/anuraghazra/github-readme-stats)
> > [![Harlok's wakatime stats](https://camo.githubusercontent.com/9e95b4d2d7082e1e59d33a1f72fa41fe81caf5f2b52178ced5572f67ad39218f/68747470733a2f2f6769746875622d726561646d652d73746174732e76657263656c2e6170702f6170692f77616b6174696d653f757365726e616d653d43617265706f6c6c6f)](https://github.com/anuraghazra/github-readme-stats)
> 
> My username in wakatime is @ChickenFace

Thanks! Your problem will be resolved when https://github.com/anuraghazra/github-readme-stats/pull/2707 is merged!
