### ISSUE TITLE
Add theme names to README theme section

### ISSUE THREAD

**Issue by nombrekeff** [anuraghazra/github-readme-stats#112]
Hey there!

**Is your feature request related to a problem? Please describe.**
I just tried the themes, but I had to try every theme to get the one I liked.

**Describe the solution you'd like**
I would suggest adding the name of the theme next/on top of the image, so it's easier to know which image corresponds to what theme.

> PD: I can do this if accepted.

**Comment by anuraghazra** [comment]
Hmmm i see yes. you can probably help it out :D thanks!

**Comment by nombrekeff** [comment]
Yeah sure, I will work something out later.

What do you think if we create another MD file containing a table with all available themes with preview and name? But leave some previews in the main readme.

**Comment by anuraghazra** [comment]
Yeah thats what i was exactly thinking

**Comment by nombrekeff** [comment]
Okay, I will do that then.

Do you prefer it if I create the new file in the root or inside the themes folder?

**Comment by nombrekeff** [comment]
Also, do you have screenshots for each theme? I can do them myself if not

**Comment by anuraghazra** [comment]
@nombrekeff we can probably just use live previews, it won't matter too much.

**Comment by nombrekeff** [comment]
Okay, that will look cooler like this, and when/if we implement the custom cache max-age, we could add a long cache to that.

**Comment by nombrekeff** [comment]
This was added in #115
