### ISSUE TITLE
Contributed to in Github stats?

### ISSUE THREAD

**Issue by hu1won** [anuraghazra/github-readme-stats#1125]
How do I increase the number of Contributed to in Github stats? Please tell me the exact way.

**Comment by florianbussmann** [comment]
You can increase the number of `Contributed to` using three ways

- create a `commit`
- create an `issue`
- create a `pull request`

Various actions on the same repository won't add up, as the metric indicates the number of repositories you contributed to. Also note that this metric only counts contributions to other repositories, i.e. your own repositories will be ignored.

**Comment by hu1won** [comment]
Thank you! It helped a lot.

**Comment by iRupam** [comment]
@florianbussmann Are code reviews included in the stats? Also, how to code review in GitHub? Can I review my own repositories' code?

**Comment by anuraghazra** [comment]
I hope @hu1won your question has been answered, closing this now. 

And thanks for the answer @florianbussmann :)
