### ISSUE TITLE
Hide Languages on Wakatime Card

### ISSUE THREAD

**Issue by Quantalabs** [anuraghazra/github-readme-stats#1138]
**Is your feature request related to a problem? Please describe.**
The wakatime card displays languages like TOML and Markdown, which isn't something you want on the card. 

**Describe the solution you'd like**
Perhaps add a `?hide` feature like there is on the github language repo card.

**Comment by anuraghazra** [comment]
Hi @Quantalabs thanks for requesting the feature. 

Yup that makes sense we will surely add it in. 💯

**Comment by aaroosh-07** [comment]
hi @anuraghazra can i take up this issue

**Comment by Morphclue** [comment]
I think this issue can be closed now since #1212 got merged.

**Comment by anuraghazra** [comment]
shipped in #1212
