### ISSUE TITLE
Wakatime "range" argument doesn't work.

### ISSUE THREAD

**Issue by AlphaNecron** [anuraghazra/github-readme-stats#1144]
Without "range" argument:
[![Wakatime](https://github-readme-stats.vercel.app/api/wakatime?username=AlphaNecron&hide_border=true&theme=discord_old_blurple)](https://github-readme-stats.vercel.app/api/wakatime?username=AlphaNecron&hide_border=true&theme=discord_old_blurple)

With "range" argument:
[![Wakatime](https://github-readme-stats.vercel.app/api/wakatime?username=AlphaNecron&hide_border=true&theme=discord_old_blurple&range=last_month)](https://github-readme-stats.vercel.app/api/wakatime?username=AlphaNecron&hide_border=true&theme=discord_old_blurple&range=last_month)

**Comment by florianbussmann** [comment]
`last_month` is not listed as possible value in the [wakatime api docs](https://wakatime.com/developers#stats)

Regarding the `range` parameter also see my comment on another issue https://github.com/anuraghazra/github-readme-stats/issues/1112#issuecomment-861760030

**Comment by AlphaNecron** [comment]
Neither `last_7_days`, `last_30_days`, `last_6_months`, nor `last_year` works.

**Comment by florianbussmann** [comment]
You have to change the `Display code time publicly` to `Last 7 Days` or `Last Year` at https://wakatime.com/settings/profile
`last_30_days` and `last_6_months` are not available for the free plan afaik

**Comment by AlphaNecron** [comment]
How about `All time`? @florianbussmann

**Comment by florianbussmann** [comment]
You can also set `All time` and drop the `range` argument. It will default to whatever you set at `Display code time publicly` so the parameter is useless anyway if you don't host your own wakatime instance or have a paid membership

**Comment by AlphaNecron** [comment]
Ok, thanks.
