### ISSUE TITLE
Circle around "A+" rating only goes halfway

### ISSUE THREAD

**Issue by Gitoffthelawn** [anuraghazra/github-readme-stats#1147]
**Describe the bug**
The circle that goes around the rating only goes halfway for an "A+" rating.

**Expected behavior**
Perhaps it would be best if the circle extends all the way around and change the a color to bright green (`#00E000` preferred) or yellow (`#E0E000` preferred).

**Live demo link (when this issue is fixed, the reported issue will no longer be visible**
![Example using my stats](https://github-readme-stats.vercel.app/api?username=gitoffthelawn&show_icons=true&title_color=fff&icon_color=79ff97&text_color=ddd&bg_color=151515)

**Comment by anuraghazra** [comment]
> The circle that goes around the rating only goes halfway for an "A+" rating.

Thats the way it is, It's a circular progress bar, It goes up to S+.

> change the a color to bright green (#00E000 preferred) or yellow (#E0E000 preferred).
You can control the overall color of them via the query params but we want to keep that in sync with the primary color. And don't have any plans on giving a fine grain control over that color as well.
