### ISSUE TITLE
Top Languages Colors

### ISSUE THREAD

**Issue by igorskyflyer** [anuraghazra/github-readme-stats#1149]
My repos contain Pascal and JavaScript - among other languages and what I noticed is that the colors for Pascal and JavaScript are quite similar and it's not easy to distinguish between the two, see the image.
![top](https://user-images.githubusercontent.com/20957750/122646434-672b1480-d11f-11eb-98cc-1e2f4a5ab4e6.png)

**Comment by igorskyflyer** [comment]
Is there a way to customize that and/or are you planning to change the color scheme for the Top Languages card?

**Comment by anuraghazra** [comment]
Currently we don't have any plans on changing the color of languages. We can change it but we don't want to because all those colors are actually provided by GitHub API itself.
