### ISSUE TITLE
wrong starts number

### ISSUE THREAD

**Issue by 532910** [anuraghazra/github-readme-stats#1155]
https://github-readme-stats.vercel.app/api?username=532910&show_icons=true&theme=merko

![image](https://user-images.githubusercontent.com/14617699/123138427-aded7700-d45d-11eb-9cd8-a67bce46e6ba.png)

![image](https://user-images.githubusercontent.com/14617699/123138636-ee4cf500-d45d-11eb-91cc-70248246f2f7.png)

**Comment by John8790909** [comment]
@532910 the stars on your profile are the repositories you have stared and the stars in the GitHub stats are the stars people have given your repositories so I think it is displaying the right amount of stars you just go mixed up.

**Comment by 532910** [comment]
This way it should be `Total stars received`.

**Comment by John8790909** [comment]
Maybe, but that would be too long don't you think?

**Comment by 532910** [comment]
I think the word `Total` should be removed.

**Comment by John8790909** [comment]
Well, then make an issue suggesting that change.

**Comment by andreakaye** [comment]
I wish I had time for this but I work three jobs now because someone went
and fucked up my whole game

GOODBYE

**Comment by rickstaa** [comment]
Closing as this is no longer an issue.
