### ISSUE TITLE
Contributing new theme of Tokyo Night gradient palette

### ISSUE THREAD

**Issue by NguyenD-Nam** [anuraghazra/github-readme-stats#1160]
Hello Anuraghazra, your have done amazing work and I really like your app.

I want to contribute a little bit with a theme of the color palette that I like a lot called **Tokyo Night Palette**.
- Here is the link for you to have a quick look at it: ![My_gitHub_Stats](https://github-readme-stats.vercel.app/api?username=NguyenD-Nam&show_icons=true&icon_color=fd00ff&bg_color=30,711c91,091833&title_color=0abdc6&text_color=ff0677)

- Here are the colors I used:
  - linear-gradient(30deg, `#711c91`, `#091833`) for *bg_color*
  - `#fd00ff` for *icon_color*
  - `#0abdc6` for *title_color*
  - `#ff0677` for *text_color*

Hope you consider my request and I'm looking forward to seeing more of these kinds of app from you, keep on the amazing work.

**Comment by anuraghazra** [comment]
Hi @NguyenD-Nam, I assume you are talking about this https://marketplace.visualstudio.com/items?itemName=enkia.tokyo-night

But we already have it: 

![](https://github-readme-stats.vercel.app/api?username=anuraghazra&theme=tokyonight)

**Comment by NguyenD-Nam** [comment]
Oh I'm sorry I didn't notice that.
