### ISSUE TITLE
Option to change the color of languages in Top Languages card

### ISSUE THREAD

**Issue by Maaz-Code** [anuraghazra/github-readme-stats#1164]
**Is your feature request related to a problem? Please describe.**
No, it's not a problem but I came across a situation wherein the top languages card my two languages (C++ and SCSS) had similar colour and it did not look good in the compact layout and there is nothing I could do about it.

**Describe the solution you'd like**
I would like an option where we can set our choice of colour for any language or we can change the allotted colour of the languages in the top languages card. This way if someone wants to change the colour then they can set their own colour to make it look good in the compact layout of the top languages card.

**Describe alternatives you've considered**
I don't think there is a way to do this right now.

**Additional context**
![issue](https://user-images.githubusercontent.com/65590762/123753953-00081f80-d8d8-11eb-821c-2e5694f52cdd.png)

**Comment by anuraghazra** [comment]
Hi @Maaz-Code thanks for requesting this feature.

But I think this is not a impactful feature to implement & will cause maintenance burden, All the language colors are officially taken from github, and we don't want to modify those.

And also If we add option to customize, this is gonna make the URLs very long & cluttery too, users have to do `&html=ff2244&css=00000&scss=222222`

Maybe we could think about it in future if majority of people find this feature to be necessary.

**Comment by tgoyal63** [comment]
Please do this, it would be really great, as we can customize colors according to our website theme.

**Comment by kriks999** [comment]
**Yep, do this!** Not a lot of people will use it, but those people who will use it will be **very grateful** to you for such a feature!

**Comment by PablooDario** [comment]
Yes, please add this option to customize the colors, because in my chart it is not possible to distinguish the separation between Jupyter and HTML.
![image](https://github.com/anuraghazra/github-readme-stats/assets/92002964/e9b7994a-ba24-4c99-86fc-92aea5ce2b00)
