### ISSUE TITLE
Increase the parameter of the number of displayed languages for language cards 

### ISSUE THREAD

**Issue by dejavudwh** [anuraghazra/github-readme-stats#1166]
like
`https://github-readme-stats.vercel.app/api/top-langs/?username=dejavudwh&count=10&hide=html,css,makefile
`

This will display the 10 most commonly used languages in the language card.

**Comment by anuraghazra** [comment]
We already have `langs_count` flag. well documented on the readme. 
https://github-readme-stats.vercel.app/api/top-langs/?username=dejavudwh&langs_count=10&hide=html,css,makefile

**Comment by dejavudwh** [comment]
> We already have `langs_count` flag. well documented on the readme here: https://github.com/anuraghazra/github-readme-stats#language-card-exclusive-options
> 
> https://github-readme-stats.vercel.app/api/top-langs/?username=dejavudwh&langs_count=10&hide=html,css,makefile

But it can only be set to a maximum of 10, if more than 10 it still shows 10, I think it is necessary to increase the cap.

BTW, this project is really great, thanks for your work! @anuraghazra
