### ISSUE TITLE
Can we have an option to style the text like say make it bold or change the font?

### ISSUE THREAD

**Issue by AnishDe12020** [anuraghazra/github-readme-stats#1169]
**Is your feature request related to a problem? Please describe.**
No, it is not related to a problem. It is an enhancement where we can changed the style of the text used in the repo or stats or wakatime cards. Customizations can include font weight, font style, font family, font size etc.

**Describe the solution you'd like**
As I said, if we can save the customization parameters mentioned above as parameters in the url or as a part of a theme, it is going to increase the potential of this application quite a bit.

**Describe alternatives you've considered**
None yet

**Additional context**
Nothing. Will add more with comments or by editing this commend if needed.

**Comment by rickstaa** [comment]
Related to pull request #1468. This pull request allows users to toggle the boldness of the stats card text on and off.

**Comment by rickstaa** [comment]
I implemented the `use_bold` option to change the boldness. @AnishDe12020 is this what you had in mind, or did you want to change the font?
