### ISSUE TITLE
Add card_width for stats Card repo cards

### ISSUE THREAD

**Issue by trackmasters** [anuraghazra/github-readme-stats#1170]
**Is your feature request related to a problem? Please describe.**
The GitHub Stats Card is too wide and I cannot fit two panels in my `README.md`.

**Describe the solution you'd like**
Allow customizing the width of GitHub Stats Card like it is allowed for the Language Card using card_width.

**Describe alternatives you've considered**
Make the GitHub Stats Card smaller (width) might be also a solution.

**Additional context**
**Current look:**
<img src="https://user-images.githubusercontent.com/21295587/105180646-222c9300-5b2b-11eb-945c-74147c2803fb.png"></img>

**Requested feature:** I would like to achieve something like this (edited in MS Paint):
<img src="https://user-images.githubusercontent.com/21295587/105180731-37092680-5b2b-11eb-99ae-76efbd6e6ac9.png"></img>

**Note:**
This is my 2nd attempt (the 1st one is [here](https://github.com/anuraghazra/github-readme-stats/issues/780)) to draw attention and get feedback as one of my feature requests remained inactive despite the overall activity in the issues section.

**Comment by anuraghazra** [comment]
Hey @trackmasters thanks for requesting this feature. sorry I totally missed your issue, I believe there was some similar issues too which got unnoticed. 

I'll take a look on how we can do this without making things overlap each other.

**Comment by simran2104** [comment]
@trackmasters You can write your code like this:

```
<p align="center">
<img height="180em" src="https://github-readme-stats.vercel.app/api?username=usernamecount_private=true&show_icons=true" align = "center"/>
<img height="180em" src="https://github-readme-stats.vercel.app/api/top-langs?username=username&show_icons=true&locale=en&layout=compact" align = "center"/>
</p>
```

**Comment by rickstaa** [comment]
@simran2104 Thanks a lot for the workaround!

Please be aware that the work-around sometimes leads to Github timing out. In that case, only URLs will be shown. This appears to happen more often when the `<img>` tags are used instead of the markdown syntax. I am not sure why this happens but it might be another reason to implement a `width` variable.

**Comment by rickstaa** [comment]
#1334 created by @postatum adds this feature.

**Comment by rickstaa** [comment]
Related to #1051

**Comment by rokejulianlockhart** [comment]
@simran2104, that method (`height="{value}em"`) forces the card to ignore things like the browser text scale, since it scales the output entirely. Is there no way for multiple cards to negotiate their size?
