### ISSUE TITLE
Is this a bug or what i code using py and js and also php

### ISSUE THREAD

**Issue by Rohith-sreedharan** [anuraghazra/github-readme-stats#1179]
BTW In private repo's i code it. 

so is this bug or what idk  it just shows blank

![image](https://user-images.githubusercontent.com/86031501/124930957-62bb9280-e01f-11eb-804b-fa648ea5ee1b.png)

**Comment by anuraghazra** [comment]
We cannot get language data from private repos. 

You need to deploy on your own instance in order to see any stats: https://github.com/anuraghazra/github-readme-stats#deploy-on-your-own-vercel-instance
