### ISSUE TITLE
Toggle for the themes background color to match  the GitHub dark/light mode background  color

### ISSUE THREAD

**Issue by arndom** [anuraghazra/github-readme-stats#1182]
**Feature Description.**
I would like for there to be a toggle for the themes background color to match  the GitHub dark/light mode background color

**How it could be implemented*
A custom URL parameter that accepts Boolean to make the background color of any theme match the GitHub theme

**What I currently do**
I take a theme I like and change the background color to that of GitHub dark mode

**Additional context**
An example would be the recent PR I made for a new theme (tokyoblend); it's the Tokyo night theme with just the background matching GitHub Dark mode background

**Comment by ronilaukkarinen** [comment]
This would be nice. One upvote from me. 👍

**Comment by anuraghazra** [comment]
We have a github_dark theme no need for any other booleans to switch between it. 

![](https://github-readme-stats.vercel.app/api?username=anuraghazra&theme=github_dark)

You can also use a transparent background color which will be compatible with any background ![](https://github-readme-stats.vercel.app/api?username=anuraghazra&bg_color=ffffff00&text_color=0055ff)

**Comment by ronilaukkarinen** [comment]
Transparent background color does the trick. Thanks!

**Comment by aleen42** [comment]
@anuraghazra when the background colour is set as transparent, is it better to support the dynamic fore colour of text when not passing any text colour value.
