### ISSUE TITLE
A bug with the "top-langs" in frensh language

### ISSUE THREAD

**Issue by dalmatheo** [anuraghazra/github-readme-stats#1185]
In frensh language, the "top-langs' in compact doesn't work. The languages doesn't appear.
![Capture1](https://user-images.githubusercontent.com/53833947/125466796-e22f6031-cbc8-4931-a3ab-c5dc87e40812.PNG)
![Capture2](https://user-images.githubusercontent.com/53833947/125466803-68243081-29d3-43f7-b03d-35198b39bb91.PNG)
Screen for the proof.
I think you can fix that. Thx

**Comment by rickstaa** [comment]
@dalmatheo Closing this since I don't have enough information to debug your problem. Please give me the exact markdown code you use to render the card. Further, I think the comment by @murattishkul will fix it.
