### ISSUE TITLE
how is "contributed to" calculated

### ISSUE THREAD

**Issue by shubham-shahh** [anuraghazra/github-readme-stats#1187]
Hi, what does "contributed to " represent? and how is it contributed?
Thanks

**Comment by francois-rozet** [comment]
It is the number of repositories, not own by the user, to which the user contributed, either with a commit, an issue or a pull request.

**Comment by anuraghazra** [comment]
I hope that answered your question for more info see https://github.com/anuraghazra/github-readme-stats/issues/1125#issuecomment-856646890  and https://github.com/anuraghazra/github-readme-stats/discussions/1129
