### ISSUE TITLE
Incorrect calculated in https://github.com/splincode

### ISSUE THREAD

**Issue by splincode** [anuraghazra/github-readme-stats#1191]
**Describe the bug**

I contributed every time to https://github.com/Angular-RU/angular-ru-sdk and write code on TypeScript.

But why PHP?
https://github.com/splincode

**Expected behavior**

Show TypeScript need more than PHP

![image](https://user-images.githubusercontent.com/12021443/125764386-77aa3d5a-209e-471d-a876-09cac93f8c92.png)

**Comment by anuraghazra** [comment]
We don't count forked repositories, we only count your own repos. 

And language stats are calculated based on "how much" code you have in bytes the more bytes of code you have in a specific lang it will be on top.  

So this is expected behaiviour. closing this for now, feel free to open another.
