### ISSUE TITLE
GitHub Extra Pins -  issue with caching

### ISSUE THREAD

**Issue by sitemapxml** [anuraghazra/github-readme-stats#1198]
After updating the readme file in one of the pinned repositories, old description is still in the pinned repository card. I have tried cleaning cache and even opening in new browser but with no success, so I suppose that have something to do with server side caching.

Does anyone know something more about this? @anuraghazra?

**Comment by anuraghazra** [comment]
It is all documented in the readme 
![image](https://user-images.githubusercontent.com/35374649/127118627-e86e4e4b-7ae0-4d01-9d21-b7f0fb02a648.png)

https://github.com/anuraghazra/github-readme-stats#common-options

**Comment by sitemapxml** [comment]
I somehow missed that. Thank you :smile:

**Comment by anuraghazra** [comment]
You can fork and change the constants here https://github.com/anuraghazra/github-readme-stats/blob/fede678fa250e17682f66340fb2166d30add5fba/src/common/utils.js#L175-L180 or in the specific /api files
