### ISSUE TITLE
Slow render in Safari sometimes (random)

### ISSUE THREAD

**Issue by eddiejaoude** [anuraghazra/github-readme-stats#120]
Mac Safari has rendering issues

<img width="1477" alt="Screenshot 2020-07-20 20 08 18" src="https://user-images.githubusercontent.com/624760/87976291-c83c0980-cac4-11ea-99e7-75247b3511c4.png">

**Comment by anuraghazra** [comment]
Hi @eddiejaoude  thanks for reporting the issues, I'll look into this ASAP. 

If you provide me exact system information of your setup then I could debug this with ease (eg: Mac OS, browser versions) 

Thanks!

**Comment by eddiejaoude** [comment]
I think you are right, it looks very similar and my versions are similar too.

Mac `15.15.5`
Safari `13.1.1`

**Comment by anuraghazra** [comment]
@filiptronicek @edisonlee55 maybe you guys can help us debug this? that would be very helpful. thanks! :heart:

**Comment by filiptronicek** [comment]
@anuraghazra I was trying to reproduce it, but have no luck. I am trying on Catalina Safari 13.1.1 so that shouldn't be the problem. @eddiejaoude can you please provide further information (or try on a different machine) on how the loading looks like. Thanks!

P.S. might be because of some in-browser issue, which we cannot fix. Just throwing it in here.

**Comment by anuraghazra** [comment]
> @anuraghazra I was trying to reproduce it, but have no luck. I am trying on Catalina Safari 13.1.1 so that shouldn't be the problem. @eddiejaoude can you please provide further information (or try on a different machine) on how the loading looks like. Thanks!
> 
> P.S. might be because of some in-browser issue, which we cannot fix. Just throwing it in here.

The most straightforward solution would be to disable the animations completely. but the issue is we cannot detect the User-Agent from the server because User agent will be "camo" (Github's UA)

**Comment by filiptronicek** [comment]
> 
> 
> > @anuraghazra I was trying to reproduce it, but have no luck. I am trying on Catalina Safari 13.1.1 so that shouldn't be the problem. @eddiejaoude can you please provide further information (or try on a different machine) on how the loading looks like. Thanks!
> > P.S. might be because of some in-browser issue, which we cannot fix. Just throwing it in here.
> 
> The most straightforward solution would be to disable the animations completely. but the issue is we cannot detect the User-Agent from the server because User-agent will be "camo" (Github's UA)
> 
> Maybe we could try this? seems legit
> https://stackoverflow.com/questions/16348489/is-there-a-css-hack-for-safari-only-not-chrome

Yeah.... so, I think we, unfortunately, cannot use that, we cannot pass any styling info (as previously noted on #79.) the important thing is now to get a hold of what it looks like, see if anyone has this issue also and then either
 1. do it ourselves
 2. contact Apple and see what we can do

**Comment by filiptronicek** [comment]
https://github.com/anuraghazra/github-readme-stats/issues/79#issuecomment-659883166

**Comment by anuraghazra** [comment]
> Yeah.... so, I think we, unfortunately, cannot use that, we cannot pass any styling info (as previously noted on #79.) the important thing is now to get a hold of what it looks like, see if anyone has this issue also and then either
> 
> 1. do it ourselves
> 2. contact Apple and see what we can do

I see but i'm already using CSS & CSS Keyframes i'm pretty sure we can use media queries because github serves the image as SVG (and it does render the CSS with it) so i think it should work.  and in https://github.com/anuraghazra/github-readme-stats/issues/79#issuecomment-659883166 the author is refering to <picture> tag media queries it does not work because github wont render the picture tag

**Comment by filiptronicek** [comment]
> > Yeah.... so, I think we, unfortunately, cannot use that, we cannot pass any styling info (as previously noted on #79.) the important thing is now to get a hold of what it looks like, see if anyone has this issue also and then either
> 
> > 
> 
> > 1. do it ourselves
> 
> > 2. contact Apple and see what we can do
> 
> 
> 
> I see but i'm already using CSS & CSS Keyframes i'm pretty sure we can use media queries because github serves the image as SVG (and it does render the CSS with it) so i think it should work.  and in https://github.com/anuraghazra/github-readme-stats/issues/79#issuecomment-659883166 the author is refering to <picture> tag media queries it does not work because github wont render the picture tag, 
> 
> 
> 
> Oh wait @filiptronicek i think you already tried that right? https://github.com/anuraghazra/github-readme-stats/issues/79#issuecomment-660005136

As I remember doing it, I just did the plain HTML Img with the media=prefers color scheme thing, didn't try the svg styles yet

**Comment by eddiejaoude** [comment]
Sorry I should have said, **it is random**, it sometimes works and sometimes does not 🤦‍♂️ - it makes it very hard to debug and reproduce consistently 😞
