### ISSUE TITLE
Username does not work!

### ISSUE THREAD

**Issue by rjarman** [anuraghazra/github-readme-stats#1203]
If I replace the URL with API based URL like the following:
https://wakatime.com/api/v1/users/current/stats/last_year?api_key=****&is_including_today=true
then Wakatime gives my stats. 
But there is no option to include api_key as param on the following line of code:
https://github.com/anuraghazra/github-readme-stats/blob/fede678fa250e17682f66340fb2166d30add5fba/src/fetchers/wakatime-fetcher.js#L8

**Comment by florianbussmann** [comment]
https://wakatime.com/api/v1/users/rjarman/stats/?is_including_today=true works for your profile
If you want `last_year` to work you can change `Display code time publicly` in your [profile settings](https://wakatime.com/settings/profile) to `Last Year`.

If you still want to use your api key for some reason I would advice to resolve the parameter through an environment variable

**Comment by rjarman** [comment]
Thank you, it's solved my issue!
