### ISSUE TITLE
Toggle bold off or on for stats card

### ISSUE THREAD

**Issue by BxileyCS** [anuraghazra/github-readme-stats#1204]
**Is your feature request related to a problem? Please describe.**
I don't like the bold styling on the stats card (total stars, commits, ect) especially when the top languages card doesn't have bold on the language names.

**Describe the solution you'd like**
A simple attribute named bold_body that you can toggle on and off

**Describe alternatives you've considered**
I tried to fork the repo and debold it myself but I don't know enough about js for make that happen.

**Additional context**
I would just like to see the body text for the stats card have a bold option that I disable.

**Comment by paulmowat** [comment]
I'll take a look at doing this for title, text and rank.

**Comment by rickstaa** [comment]
Related to #1169. A pr for the stats card has been created see #1468.
