### ISSUE TITLE
Bug(StatsCard): Padding of items seem to be related to the title-length.

### ISSUE THREAD

**Issue by Morphclue** [anuraghazra/github-readme-stats#1206]
# Describe the bug
I've tried to implement #1155 and noticed, that the padding of the stat-items seems to be related to the title length.

## Actual behavior
"Insgesamt erhaltene Sterne" (see german card for reference) overlaps with the total star count.

## Expected behavior
"Insgesamt erhaltene Sterne" (see german card for reference) should have a padding like "Liczba Gwiazdek dostanych" (see polish card for reference)

#### English
![image](https://user-images.githubusercontent.com/43741877/126891719-385919f2-f622-4c02-9f47-e55a51bd65cf.png)
#### German
![image](https://user-images.githubusercontent.com/43741877/126891742-1dd25f4f-98b6-4b8f-8605-11acc50c4b0e.png)
#### Dutch
![image](https://user-images.githubusercontent.com/43741877/126891789-48eb87a3-a2f7-4321-a8aa-568f8f881d31.png)
#### Polish
![image](https://user-images.githubusercontent.com/43741877/126891926-f8535284-78db-4918-9755-409ee4af3bcd.png)

**Comment by distrustME** [comment]
This bug should be fixed now in #1207. I'll close this issue if the PR gets merged.
