### ISSUE TITLE
What's wrong?

### ISSUE THREAD

**Issue by wangrongding** [anuraghazra/github-readme-stats#1216]
## How to  ->  "Please add an env variable called PAT_1 with your github token in vercel" ?

---

![image](https://user-images.githubusercontent.com/42437658/127419919-597c52d5-feb3-4c40-88e0-030954c0ee1b.png)

**Comment by xiaozuo7** [comment]
Try refresh. It seems that there is a problem with their service

**Comment by JohannSuarez** [comment]
Same here, refreshed several times.

**Comment by rjarman** [comment]
https://github.com/anuraghazra/github-readme-stats/issues/1215#issue-955350279

**Comment by wangrongding** [comment]
> Same here, refreshed several times.
> EDIT: Nvm, it's back to normal ^_^

Indeed,refreshed several times, it is back to normal

**Comment by anuraghazra** [comment]
Seems to be fixed now.
