### ISSUE TITLE
WakaTime status card not showing coding activity

### ISSUE THREAD

**Issue by davidgao7** [anuraghazra/github-readme-stats#1222]
**Describe the bug**
Dear @anuraghazra, thanks for writing this awesome app!
Unfortunately, I met a problem and I have no idea how to fix it...

I write the md like this
```
### Waketime
[![davidgao7's wakatime stats](https://github-readme-stats.vercel.app/api/wakatime?username=davidgao7)](https://github.com/anuraghazra/github-readme-stats)
```
- I checked the wakaTime dashboard and it's properly working
<img width="988" alt="Screen Shot 2021-08-01 at 7 00 39 AM" src="https://user-images.githubusercontent.com/39502459/127754266-15f5a5da-4653-4fc3-9df5-3b7e1bfd2381.png">

**Expected behavior**

I expected to see at least some of the infos could display on the status card but it appears 'no coding activity this week'

It shows not stats after rendering
<img width="845" alt="Screen Shot 2021-08-01 at 7 10 07 AM" src="https://user-images.githubusercontent.com/39502459/127754385-e468ae63-f5c3-4f90-9c6b-136e58a49f9c.png">

**Additional context**
Did I do anything wrong? 

Thank you so much!

**Comment by curly210102** [comment]
It doesn't show coding activity in [your wakatime public leaderboard](https://wakatime.com/@davidgao7), have the "Display code time publicly" been enabled?

https://wakatime.com/settings/profile -> Display code time publicly

![image](https://user-images.githubusercontent.com/76864176/127794895-5f1b14e2-d268-4bf6-a0c4-5d73cd24594d.png)

**Comment by davidgao7** [comment]
<img width="557" alt="Screen Shot 2021-08-02 at 10 34 08 AM" src="https://user-images.githubusercontent.com/39502459/127797002-0ed6354c-d02c-4f5c-b828-0eb2ea23216e.png">
I changed to 'all time' and its still not workin(https://github.com/davidgao7)

**Comment by curly210102** [comment]
@davidgao7 It works with https://github-readme-stats.vercel.app/api/wakatime?username=davidgao7&v=2.
github-readme-stats.vercel.app set a cache, thus it doesn't update immediately.

**Comment by davidgao7** [comment]
> @davidgao7 It works with https://github-readme-stats.vercel.app/api/wakatime?username=davidgao7&v=2.
> github-readme-stats.vercel.app set a cache, thus it doesn't update immediately.

Thanks curly! It's working now! Thanks for your hard work!
