### ISSUE TITLE
What is going on here?

### ISSUE THREAD

**Issue by Genius398** [anuraghazra/github-readme-stats#1226]
Hi! I am Genius398, a coder. I code in HTML, CSS, JS and JSON. I would like to contribute here. If someone can just brief me about what happens here?

**Comment by Genius398** [comment]
@anuraghazra pls tell me about this?

**Comment by Genius398** [comment]
J

**Comment by Genius398** [comment]
@anuraghazra  @anuraghazra @anuraghazra @anuraghazra @anuraghazra @anuraghazra @@anuraghazra @@@anuraghazra @anuraghazra

**Comment by Genius398** [comment]
- [x]

**Comment by anuraghazra** [comment]
Hi thanks for raising the issue and taking an interest in contributing to the project. 

As much as I love maintaining this project I still have my own life, a full-time job and not to mention I might be busy so, 
[this is definetly not the right way to get my attention in your issue.](https://github.com/anuraghazra/github-readme-stats/issues/1226#issuecomment-898531558)


And for your query you can contribute anything to any OSS project from making small changes, fixes or just updating or fixing the readmes. 
You should know basics of git to figure out how to contribute the code and how to open a pull request properly. I would suggest  https://opensource.guide/ if you are starting out. 

Thanks!

**Comment by Genius398** [comment]
> Hi thanks for raising the issue and taking an interest in contributing to the project.
> 
> As much as I love maintaining this project I still have my own life, a full-time job and not to mention I might be busy so,
> [this is definetly not the right way to get my attention in your issue.](https://github.com/anuraghazra/github-readme-stats/issues/1226#issuecomment-898531558)
> 
> And for your query you can contribute anything to any OSS project from making small changes, fixes or just updating or fixing the readmes.
> You should know basics of git to figure out how to contribute the code and how to open a pull request properly. I would suggest https://opensource.guide/ if you are starting out.
> 
> Thanks!

Sorry
