### ISSUE TITLE
Wakatime stats not showing

### ISSUE THREAD

**Issue by gokul-369** [anuraghazra/github-readme-stats#1229]
I have been using readme stats for quite a while now, but i am new to wakatime, just today i created my wakatime account and started working, now the stats are showing in my dashboard but its not showing in my profile, should i wait for the stats to show up or am i missing something...

PS: i made my coding activity public, the problem is its showing is dashboard but not in the profile and readme...

my wakatime profile: https://wakatime.com/@Gokul_369

![2021-08-04 (11)](https://user-images.githubusercontent.com/64262019/128220793-d58b2c21-d19c-4ed3-b8ff-1ff666b46fde.png)
![2021-08-04 (10)](https://user-images.githubusercontent.com/64262019/128220799-08f487c7-c208-4ca6-bb7a-454334ca64ce.png)

**Comment by c12yptonic** [comment]
Hi I am having the same problem. Any insights on how you solved it ?

**Comment by gokul-369** [comment]
> Hi I am having the same problem. Any insights on how you solved it ?

It got resolved for me ..wait for a day or two till it collects insights on your coding activity ..then it will be automatically updated, i didn't do anything extra , I  just waited and it worked
