### ISSUE TITLE
Observing a message requesting to lodge an issue here

### ISSUE THREAD

**Issue by timgates42** [anuraghazra/github-readme-stats#1233]
**Describe the bug**
I get the message

```
Something went wrong! file an issue at https://git.io/JJmN9
Cannot read property 'data' of undefined
```

but not consistently if I view 

https://github-readme-stats.vercel.app/api?username=timgates42&theme=dark

It helpfully asks to lodge an issue here.

**Expected behavior**

If I refresh enough a nice GitHub stats image is presented.

**Screenshots / Live demo link (paste the github-readme-stats link as markdown image)**

https://github-readme-stats.vercel.app/api?username=timgates42&theme=dark

![image](https://user-images.githubusercontent.com/47873678/128615679-200f11e6-ad3f-4876-8048-ec9634b1fc98.png)

**Comment by anuraghazra** [comment]
Hi @timgates42 seems like there is something wrong with your username, while fetching your data github is sending a 502 bad gateway response.

**Comment by anuraghazra** [comment]
Also pin pointed the issue.

Seems like the GraphQL query is failing while fetching your repos. 

```
repositories(first: 100, ownerAffiliations: OWNER, orderBy: {direction: DESC, field: STARGAZERS}) {
            totalCount
            nodes {
              stargazers {
                totalCount
              }
            }
          }
```
removing this part from graphql query returns other data without failing.

**Comment by anuraghazra** [comment]
This issue seems not originating from our side, it has something to do with github and your particular profile. Please refer to github support for further help. 


Closing this as "wontfix"
