### ISSUE TITLE
Dark mode based on CSS media query

### ISSUE THREAD

**Issue by JingBh** [anuraghazra/github-readme-stats#1236]
**Is your feature request related to a problem? Please describe.**

As #66 and #79 suggests, dark mode could be implemented by the `prefers-color-scheme` CSS media query.

**Describe the solution you'd like**

So I forked and did a little experiment in the CSS inside the SVG, here's a demo:
![GitHub Stats](https://github-readme-stats-jingbh.vercel.app/api?username=JingBh&show_icons=true&count_private=true&dark_theme=blue-green)

Change your system's color scheme to see if it works.

I tested it on the latest Chrome browser and Windows 11, found that for whatever-it-is reason (maybe GitHub camo or the `<img>` tag?), the browser needs a few minutes to make a change. A force refresh (clear browser cache) would also be effective.

Although this is not a perfect solution, it actually works. I wonder why this isn't already in the codebase 😂

**Describe alternatives you've considered**
None

**Additional context**

I'm Chinese, sorry if my English confuses you.

**Comment by JingBh** [comment]
Although I want to, I can't just start a PR with my fork. As I mentioned, it's just an experiment, did breaking change to the API and the codebase. Further work is definitely needed before a PR.

**Comment by anuraghazra** [comment]
Oh i see so in https://github.com/anuraghazra/github-readme-stats/issues/79 we overlooked that the cache is a thing. 

Yes it is working, but the cache is the main issue here. There is no way to invalidate the cache here.

**Comment by JingBh** [comment]
I'm using the solution from https://github.com/anuraghazra/github-readme-stats/discussions/1415#discussioncomment-2152317 instead.
