### ISSUE TITLE
Stats problem

### ISSUE THREAD

**Issue by matte0s** [anuraghazra/github-readme-stats#1246]
**Describe the bug**
All of my stats are stuck on "1" and dont change

**Expected behavior**
My stats should be shown accordingly to for example my stars wich are stuck at a value of "2" while i have stared more than that. 

**Screenshots**
![image](https://user-images.githubusercontent.com/63752298/129269429-46fc27f8-2920-4cff-ba76-1112bf46146f.png)

**Comment by matte0s** [comment]
Only my commits are acurate.

**Comment by AyushShahh** [comment]
> **Describe the bug**
> All of my stats are stuck on "1" and dont change
> 
> **Expected behavior**
> My stats should be shown accordingly to for example my stars wich are stuck at a value of "2" while i have stared more than that.
> 
> **Screenshots**
> ![image](https://user-images.githubusercontent.com/63752298/129269429-46fc27f8-2920-4cff-ba76-1112bf46146f.png)

Total stars means total number of people who have starred **your** repositories. It is not the same as the stars shown on your profile.

Total PRs and contributions are the ones **you** have made till now.
Total issues refer to the total number of issues in **your** repositories.

Recent changes may take two hours or more to update.

**Comment by matte0s** [comment]
Ahh thx for the information, i got it now.
