### ISSUE TITLE
How can I delete the 'Unspecified' field? (add.gitignore)

### ISSUE THREAD

**Issue by minji-o-j** [anuraghazra/github-readme-stats#126]
**Describe the bug**
How can I delete the 'Unspecified' field? 

**Expected behavior**
I use this repository to resume, so I didn't upload codes here. only README.md.

**Screenshots / Live demo link (paste the github-readme-stats link as markdown image)**
![image](https://user-images.githubusercontent.com/45448731/88029023-64711980-cb74-11ea-9a30-4bcf5f21dd8c.png)
> I  want to show like that

![image](https://user-images.githubusercontent.com/45448731/88029042-6dfa8180-cb74-11ea-823f-c09b0c231dde.png)
> How can I delete this?

Live demo link
[![ReadMe Card](https://github-readme-stats.vercel.app/api/pin/?username=minji-o-j&repo=hi.hii)](https://github.com/minji-o-j/hi.hii)

**Comment by anuraghazra** [comment]
Hi @minji-o-j thanks for opening the issue.

No you cannot hide it.

Yes i see the original github card does not show language if it's not defined, i'll do the same.

**Comment by nombrekeff** [comment]
Work being done in #157
