### ISSUE TITLE
Rank doesn't take into account whether include_all_commits is taken into account

### ISSUE THREAD

**Issue by jmarrec** [anuraghazra/github-readme-stats#1260]
**Describe the bug**

What is passed to the `calculateRank` function depends on whether `include_all_commits`  was orignally true or not.
So if you pass include_all_commits=True you generally get a much better rank than if you do not.

In my case normal commits (for the current year) was ~2000 giving me an A++ rank. If I use include_all_commits=true then 12000 is passed and I get an S rank.

https://github.com/anuraghazra/github-readme-stats/blob/7907a5d33892bdfd4af707fd670f9b364bc8e17f/src/fetchers/stats-fetcher.js#L119-L142

**Expected behavior**

one of these two values (total for the year, or total for all periods) should be passed to the function probably.

**Screenshots / Live demo link (paste the github-readme-stats link as markdown image)**

**Additional context**

**Comment by rickstaa** [comment]
Will be fixed when https://github.com/anuraghazra/github-readme-stats/pull/1186 is merged.
