### ISSUE TITLE
Languages not showing

### ISSUE THREAD

**Issue by DracoClaw** [anuraghazra/github-readme-stats#1265]
This `Most Used Languages` is not showing for me. Here is my code

![image](https://user-images.githubusercontent.com/34274162/130362629-b3e83e95-e203-4ec4-81fe-4cfeefcde823.png)

`![DracoClaw's GitHub stats](https://github-readme-stats.vercel.app/api?username=DracoClaw&theme=midnight-purple&show_icons=true&count_private=true)
[![Top Langs](https://github-readme-stats.vercel.app/api/top-langs/?username=DracoClaw&theme=midnight-purple&layout=compact)](https://github.com/DracoClaw/github-readme-stats)`

**Comment by anuraghazra** [comment]
You have 3 forked repos (which we don't count) and 1 is your own github profile repo which does not have any language data thus the language card is empty. 

If you have your own repo with code it will fillup. Thanks!

**Comment by DracoClaw** [comment]
Well thats a bit upsetting, I have many commits to repos, It would be appreciated if those counted towards the languges i used. additionally i have many private repos, is there a way to include those?
