### ISSUE TITLE
[Feature Request] Card theme sync with GitHub theme

### ISSUE THREAD

**Issue by lunarwhite** [anuraghazra/github-readme-stats#1268]
**Is your feature request related to a problem? Please describe.**
The GitHub Stats Card maybe visually incongruous(dark vs light) with the [GitHub theme](https://github.com/settings/appearance). 

**Describe the solution you'd like**
Allow setting 2 different card themes for Github's "day theme" and "night theme".

**Describe alternatives you've considered**
Maybe a possible solution: 
1. Split the `theme` option into `day_theme` and `night_theme`.
2. Try to get the current Github theme, and then activate the corresponding card theme.

It would be cool if the card theme can sync with different visitors' GitHub theme. Thanks in advance. :)

**Comment by mmohajer9** [comment]
I am really yearning for this feature. It's somewhat annoying to see a white-colored box in the totally black area of your profile.

@anuraghazra

**Comment by anuraghazra** [comment]
> Try to get the current Github theme

Sorry but this is not possible.

We cannot detect which theme user is using when the request is actually done from the `github-camo` server.

**Comment by l-zeuch** [comment]
As a workaround (or the only way, really), I set the background colour of my card to no colour with full transparency, like such:

```
...&bg_color=bg_color=00000000
```
Maybe this'll work for you.

**Comment by mmohajer9** [comment]
That was quite interesting, but it's not a fix, you know, It's a hack.
Also, when the theme is dark, the texts on the cards are not visible; thus, you can not read them because, with this approach, we are only changing the background color, and we are not making something adaptive to the Github theme.
Anyway, it is better than the bright color of white on a completely dark screen, though 👍🏻 .
Thanks!

**Comment by l-zeuch** [comment]
> That was quite interesting, but it's not a fix, you know, It's a hack.

I agree, it is quite hacky.

However, after digging around in GitHub's documentation, I see no way to check what theme the user viewing is using, which is kind of a bummer.
Consider using a balanced colour for the text colour if it's too hard to read; I've found `9f9f9f` to be good on all themes. And you're right, it's definitely better than nothing.
As a rough guideline I'll include my colour settings, and you'll see that I've completely ditched the theme approach:
```
&title_color=4F8CC9&text_color=9f9f9f&bg_color=00000000
```

Kind regards

**Comment by mmohajer9** [comment]
> > That was quite interesting, but it's not a fix, you know, It's a hack.
> 
> I agree, it is quite hacky.
> 
> However, after digging around in GitHub's documentation, I see no way to check what theme the user viewing is using, which is kind of a bummer.
> Consider using a balanced colour for the text colour if it's too hard to read; I've found `9f9f9f` to be good on all themes. And you're right, it's definitely better than nothing.
> As a rough guideline I'll include my colour settings, and you'll see that I've completely ditched the theme approach:
> 
> ```
> &title_color=4F8CC9&text_color=9f9f9f&bg_color=00000000
> ```
> 
> Kind regards

Now it's better :)
Thanks!

**Comment by anuraghazra** [comment]
fixed by https://github.com/anuraghazra/github-readme-stats/discussions/1415#discussioncomment-2152317
