### ISSUE TITLE
502: BAD_GATEWAY

### ISSUE THREAD

**Issue by vasugamdha** [anuraghazra/github-readme-stats#127]
**Describe the bug**
Application Error: The error occurred in the hosted application.

**Expected behavior**
There occurred an application error while fetching stats of some user. 
username = <code>[cclauss](https://github-readme-stats.vercel.app/api?username=cclauss)</code>
code = NO_RESPONSE_FROM_FUNCTION

**Screenshots / Live demo link (paste the github-readme-stats link as markdown image)**
<img src="https://user-images.githubusercontent.com/40864108/88039874-c413f880-cb65-11ea-8720-4920f1ec594f.png" width="50%" height="50%">

**Comment by anuraghazra** [comment]
Thanks @vasugamdha for reporting the issue.

![gh_error](https://user-images.githubusercontent.com/35374649/88049680-2fb09280-cb73-11ea-8b02-a1242232d731.PNG)
looks like Github is being nice to us :) thats why vercel task is timingout

**Comment by anuraghazra** [comment]
Hi @vasugamdha is this still happening?

**Comment by vasugamdha** [comment]
hey @anuraghazra , its still happening.
Idk but it can be the issue for this specific username and many be similar very active users.

**Comment by anuraghazra** [comment]
> hey @anuraghazra , its still happening.
> Idk but it can be the issue for this specific username and many be similar very active users.

I vercel console i can see the request is timing out after 10sec

**Comment by vasugamdha** [comment]
I will look up for similar usernames where 502 is happening.

**Comment by anuraghazra** [comment]
I think this is not an issue anymore. closing it.
