### ISSUE TITLE
Calculation of Total commit

### ISSUE THREAD

**Issue by prabormukherjee** [anuraghazra/github-readme-stats#1275]
**Describe the bug**
I am not sure if anything is wrong here or not. But previously I have a `total commit` of 1.1k, and now it decreases to 987. I think some problem is there as I haven't deleted any repo. I have `count_private` and `include_all_commits` turned on.

**Expected behavior**
According to my GitHub, I should have 1.2k commits, including private and public repos. They are showing my commits as follows:
+ 2019 => 2 commit
+ 2020 => 1009 commit
+ 2021 => 246 commit

**Screenshots / Live demo link (paste the github-readme-stats link as markdown image)**
I didn't take any screenshot of `github-readme-stats` showing 1.1k commits, but you can check my current state ![here](https://github-readme-stats.vercel.app/api?username=prabormukherjee&count_private=true&show_icons=true&include_all_commits=true)

**Additional context**
You can check my total commit according to GitHub from [here](https://github.com/prabormukherjee)

**Comment by prabormukherjee** [comment]
Also I have found, I have 39 PR, but for some reason it's only counting 19. Any idea @anuraghazra

**Comment by anuraghazra** [comment]
> According to my GitHub, I should have 1.2k commits, including private and public repos. They are showing my commits as follows:
2019 => 2 commit
2020 => 1009 commit
2021 => 246 commit

What github shows is "contribution" 
Contribution is not same as commits, commits are counted separately. 
Contribution also includes PRs,Issues,Repo creation etc etc activities. 

> I have count_private and include_all_commits turned on.

To count private infos you need to deploy readme-stats on your own vercel instance with your own Personal access token.

**Comment by prabormukherjee** [comment]
Ooh!! Thanks for your reply. Yes, I got the contribution part. But previously I had 1.1k commit showing in the app, is there any recent change in GitHub api?
Also, 
``` To count private infos you need to deploy readme-stats on your own vercel instance with your own Personal access token.```
, but even without deploying, I'm getting different infos like this  

`&count_private=true&show_icons=true&include_all_commits=true`  
![](https://github-readme-stats.vercel.app/api?username=prabormukherjee&count_private=true&show_icons=true&include_all_commits=true)
`&count_private=true&show_icons=true&include_all_commits=true`
![](https://github-readme-stats.vercel.app/api?username=prabormukherjee&show_icons=true&include_all_commits=true)  
and so on...

**Comment by prabormukherjee** [comment]
Hi @anuraghazra,
> To count private infos you need to deploy readme-stats on your own vercel instance with your own Personal access token.  

I have deployed it on my own vercel [here](https://github-readme-stats-pro.vercel.app/api?username=prabormukherjee&count_private=true&include_all_commits=true). But still I didn't see any changes. Also my commit went down from 993 to 936. Can you tell me how I can add all private commmits and PRs

**Comment by prabormukherjee** [comment]
This issue got solved after I added the repo permission with the PAT. Thanks
