### ISSUE TITLE
give me idea for simple project 

### ISSUE THREAD

**Issue by sudhakarharin** [anuraghazra/github-readme-stats#1276]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by anuraghazra** [comment]
Hi @sudhakarharin sorry but this is not the right place to ask these type of questions, feel free to DM me on [twitter](http://twitter.com/anuraghazru) if you have some questions not relating to github-readme-stats 

Thanks!
