### ISSUE TITLE
GitHub Readme Stats card Bug

### ISSUE THREAD

**Issue by michalspano** [anuraghazra/github-readme-stats#1280]
**Describe the bug**
I have been using this feature for some time. However, upon checking my GitHub page today, I realized that the card shows incorrect amount of __commits__. I have around 400-500 public commits listed (this year) and such expected behaviour was working up until today. On the other hand, all other stats seem to work correctly (including _language cards_, etc.).

**Expected behavior**
Personal stats card be reviewed, more specifically the __commits counter__.

**Screenshots / Live demo link (paste the github-readme-stats link as markdown image)**

![marked-screenshot](https://user-images.githubusercontent.com/71947840/131543871-9b034b93-3bdb-43fd-8913-b98fbc97c2a4.png)

**Additional context**
Specified above.

**Comment by anuraghazra** [comment]
Seems fine to me.

**Comment by michalspano** [comment]
It seems to be working now!

![fix](https://user-images.githubusercontent.com/71947840/131559191-da13bf5f-a4ef-4e49-8a20-da8533ea4233.png)

I'm closing this issue. #1280
Thanks, @anuraghazra for viewing this issue.
