### ISSUE TITLE
Keep getting this issue

### ISSUE THREAD

**Issue by staticalliam7** [anuraghazra/github-readme-stats#1298]
**Describe the bug**
Card will not pull my information and instead throws error
**Expected behavior**
Display my stats
**Screenshots / Live demo link (paste the github-readme-stats link as markdown image)**
![](https://camo.githubusercontent.com/d7291aed9beca0e5b8963a1b1ff07da2fa3a3880f500c161be7af1f546d5d66b/68747470733a2f2f6769746875622d726561646d652d73746174732e76657263656c2e6170702f6170693f757365726e616d653d737461746963616c6c69616d372673686f775f69636f6e733d74727565267468656d653d6461726b26696e636c7564655f616c6c5f636f6d6d6974733d74727565?_sm_au_=iVVjDP7vjSrWM5Hr2VtWjKHQBH3M2)

**Additional context**

**Comment by anuraghazra** [comment]
> Card will not pull my information and instead throws error

Seems to be working.

**Comment by staticalliam7** [comment]
Yeah, after messing around for a while it worked, forgot to close
