### ISSUE TITLE
Sorting in Language Card is wrong when the percentage is in float

### ISSUE THREAD

**Issue by saurabhdaware** [anuraghazra/github-readme-stats#130]
**Describe the bug**

![A screenshot that shows PHP is placed over TypeScript, even though typescript is used more](https://user-images.githubusercontent.com/30949385/88065995-e409e300-cb8a-11ea-805e-db0718ad6bc9.png)
PHP 5.29% is placed above TypeScript 5.44%

**Expected behavior**
TypeScript is supposed to be above PHP

**Comment by anuraghazra** [comment]
@saurabhdaware Thanks for reporting this issue, i'll fix it. :)
