### ISSUE TITLE
Name of one theme wrong in /themes/README.md

### ISSUE THREAD

**Issue by rakshit087** [anuraghazra/github-readme-stats#1301]
**Describe the bug**
This [theme](https://camo.githubusercontent.com/303b3a950e8044175e5024609b7c81ce9c9d4cdd469e96a6cd1ad4dd4e3cbdc4/68747470733a2f2f6769746875622d726561646d652d73746174732e76657263656c2e6170702f6170693f757365726e616d653d616e7572616768617a72612673686f775f69636f6e733d7472756526686964653d636f6e74726962732c7072732663616368655f7365636f6e64733d3836343030267468656d653d64617263756c61)'s name is not written correctly in /theme/README.md. 

**Expected behavior**
The given name is `dracula` which is already the name of the original `dracula` theme.

**Screenshots / Live demo link (paste the github-readme-stats link as markdown image)**
![image](https://user-images.githubusercontent.com/50898928/132574211-bb4bb970-2c8b-423d-a31b-87c8221e2f4e.png)
![image](https://user-images.githubusercontent.com/50898928/132574400-dec17bf1-25f5-417f-8bfd-7b03e6fa6afe.png)
**Additional context**

**Comment by anuraghazra** [comment]
Darcula: 
https://marketplace.visualstudio.com/items?itemName=rokoroku.vscode-theme-darcula

![image](https://user-images.githubusercontent.com/35374649/132700590-df7982ba-a061-4ad0-ac78-aa2b253ebee4.png)


Dracula:
https://marketplace.visualstudio.com/items?itemName=dracula-theme.theme-dracula

![image](https://user-images.githubusercontent.com/35374649/132700544-8adfbcab-dfb6-47ce-a1a4-78064dc0325f.png)


They are different themes. it is correct.

**Comment by rakshit087** [comment]
Oh, Sorry I didn't notice.
