### ISSUE TITLE
Stats don't work/update.

### ISSUE THREAD

**Issue by lorenzotsouza** [anuraghazra/github-readme-stats#1303]
**Describe the bug**
The stats on my page isn't working/updating.

**Expected behavior**
Function normally.

**Screenshots / Live demo link (paste the github-readme-stats link as markdown image)**
  <img align="center" src="https://github-readme-stats.vercel.app/api?username=lorenzotsouza&show_icons=true&theme=github_dark&include_all_commits=true&count_private=true" />
  <img height="127.5" align="center" src="https://github-readme-stats.vercel.app/api/top-langs/?username=lorenzotsouza&layout=compact&langs_count=7&theme=github_dark" />

**Additional context**
I've changed my username yesterday, but it already passed more than 12 hours, I don't know if it needs 24 hours to update and function normally.

**Comment by anuraghazra** [comment]
I see no problem here, your github has no data in. 

Data is correct and is updated.

**Comment by lorenzotsouza** [comment]
Oh, in my "projects" folder on GitHub, I have some projects that use HTML, CSS and Javascript. Does it need to be somewhere specific to show it in the statistics?
Link about what I'm saying - https://github.com/lorenzotsouza/Projects/tree/main/Docs

**Comment by anuraghazra** [comment]
As far as I know github ignores language data on folders which are called "docs" That's why there is no data

**Comment by lorenzotsouza** [comment]
Great thanks!
Now it's working.
