### ISSUE TITLE
Top Languages Card

### ISSUE THREAD

**Issue by DTS-11** [anuraghazra/github-readme-stats#1306]
**Describe the bug**
The Top Languages Card doesn't show Python language even tho I've repos with Python as language.

**Expected behavior**
Show Python language on the Top Languages Card.

**Screenshots / Live demo link (paste the github-readme-stats link as markdown image)**
On my GitHub profile, readme.md.

**Comment by anuraghazra** [comment]
We don't count forked repos. thats why it isn't showing.

**Comment by DTS-11** [comment]
I do have another python files other than forks
