### ISSUE TITLE
Create a custom 404 that links back to this project.

### ISSUE THREAD

**Issue by stemount** [anuraghazra/github-readme-stats#132]
**Is your feature request related to a problem? Please describe.**
there is no custom page for the `/` route so it shows you the directory listing.

**Describe the solution you'd like**
a page instead ideally with the API documentation! :O

**Describe alternatives you've considered**
a custom 404 in vercel

**Additional context**
![image](https://user-images.githubusercontent.com/150512/88075867-4655ea00-cb71-11ea-88e5-810061834204.png)

**Comment by anuraghazra** [comment]
@stemount Thanks for opening the issue, right i should redirect the users to github page :D will do it. Thanks!

**Comment by stemount** [comment]
MAGIC!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
