### ISSUE TITLE
Compact Layout For `Top Languages Card`

### ISSUE THREAD

**Issue by anuraghazra** [anuraghazra/github-readme-stats#134]
**Is your feature request related to a problem? Please describe.**
The current language card is good but it takes too much space, so a good idea would be to make a compact layout.

**Describe the solution you'd like**
We can introduce a new ?layout parameter to switch between two layouts.

**Additional context**
It would exactly look like github's language stats
![languages_gh](https://user-images.githubusercontent.com/35374649/88078293-eb84b880-cb99-11ea-9429-bbc39fd16808.PNG)

**Comment by nombrekeff** [comment]
I like this, what about making this the default layout? Is the other one actually needed?

**Comment by anuraghazra** [comment]
No i won't make this default layout and introduce sudden breaking change. i would have both as options. and will implement a option to switch the layout like we are doing with vertical orientation of stats card

**Comment by nombrekeff** [comment]
Ok, makes sense. Having both options gives some flexibility to the user.

**Comment by shahzebgit** [comment]
Hey,
How about having a language card layout for the individual repository? just feature idea.
 if you want I can make a separate request for it.😄

**Comment by anuraghazra** [comment]
> Hey,
> How about having a language card layout for the individual repository? just feature idea.
> if you want I can make a separate request for it.

Hi @shahzebgit 
I have plans for doing `repo stats` but individual language card for each repo is totally redundant because github already shows that.

**Comment by shahzebgit** [comment]
> Hi @shahzebgit
> I have plans for doing `repo stats` but individual language card for each repo is totally redundant because github already shows that.
yes , yes that makes more sense actually having a repo stats.

**Comment by sagar-gavhane** [comment]
@anuraghazra @nombrekeff Can I take this feature?

**Comment by anuraghazra** [comment]
Of course @sagar-gavhane go ahead!

**Comment by anuraghazra** [comment]
Implemented in #179
