### ISSUE TITLE
Followers 

### ISSUE THREAD

**Issue by ComputerTech312** [anuraghazra/github-readme-stats#1347]
I'd like to see how many followers the user has, added, would be nice :)

thanks in advanced

**Comment by anuraghazra** [comment]
Hi @ComputerTech312 thanks for the feature request, but our core goal is to not show any stats which is already present in the GitHub UI.

**Comment by ComputerTech312** [comment]
Ah! gotcha mate, that's wise :), could it be made that a user has to achieve a certain amount of commits or whatever before they Achieve rank "+A" ? like maybe lower amount of commits they get +B or something :)

**Comment by anuraghazra** [comment]
> Ah! gotcha mate, that's wise :) although the Available ranks aren't seem to be working, as i tested on another github profile with only one commit, and it has "+A" rank, any ideas?

Ah yup.. Thats actually intentional. We intentionally curved the ranks to be higher to make people feel more engaged, the stats are not mathematically accurate, although we do have some research going on in #960 #1186

**Comment by ComputerTech312** [comment]
Cool, i saw in a example that there is a "+S" rank, can one achieve that? or is everyone stuck with "+A" ?

**Comment by anuraghazra** [comment]
> Cool, i saw in a example that there is a "+S" rank, can one achieve that? or is everyone stuck with "+A" ?

S+ rank is the most highest and very hard to get. only 2percentile of people can currently get it.
