### ISSUE TITLE
Wakatime API last 7 days

### ISSUE THREAD

**Issue by AbhJ** [anuraghazra/github-readme-stats#1348]
In the wakatime integration, using the api token for last 7 days does not provide the intended. It outputs the previous 24 hours statistics.

**Comment by paulmowat** [comment]
I'll take a look at this one if thats ok.

**Comment by rickstaa** [comment]
Looks like something strange is going on for some users.

[![Harlok's wakatime stats](https://github-readme-stats.vercel.app/api/wakatime?username=AbhJ)](https://github.com/anuraghazra/github-readme-stats)

```md
[![Harlok's wakatime stats](https://github-readme-stats.vercel.app/api/wakatime?username=AbhJ)](https://github.com/anuraghazra/github-readme-stats)
```

You can track this issue on https://github.com/anuraghazra/github-readme-stats/issues/2671 and https://github.com/anuraghazra/github-readme-stats/issues/2698.
