### ISSUE TITLE
Description is not shown 

### ISSUE THREAD

**Issue by fluorspar20** [anuraghazra/github-readme-stats#135]
**Describe the bug**
I have given a description to each of the repos but it's not being displayed on the repo card.

**Expected behavior**
It should show the description of the repo.

**Screenshots / Live demo link**

![Screenshot_2020-07-21 fluorspar20 - Overview](https://user-images.githubusercontent.com/59736770/88084087-7f0db780-cba1-11ea-94d5-8b78391f7f6a.png)

**Comment by anuraghazra** [comment]
Hi @fluorspar20 thanks for opening the issue, I'll check it out tomorrow. :)

**Comment by anuraghazra** [comment]
Hi @fluorspar20 i think it's working now, looks like for some reason github's server was down and because of that the "no description" was shown and the cards were cached, same happened with #127

**Comment by fluorspar20** [comment]
> 
> 
> Hi @fluorspar20 i think it's working now, looks like for some reason github's server was down and because of that the "no description" was shown and the cards were cached, same happened with #127

Yeah it's working fine now. Thanks a lot!

**Comment by fluorspar20** [comment]
The issue has been resolved

**Comment by Neel-G-png** [comment]
Im facing the same issue, I have listed two repositories in my overview README.md , one is showing the description i wrote but the other one says "No description provided" even after saving the description and changing it multiple times. What seems to  be the problem?
