### ISSUE TITLE
Add Indian language doc translation

### ISSUE THREAD

**Issue by susheelg1197** [anuraghazra/github-readme-stats#1351]
Hi, kindly assign me this issue. I will translate the repository into "HINDI" language.

**Comment by rickstaa** [comment]
Related to #1349.

@susheelg1197 Thanks for your issue. Feel free to create a pull request.

**Comment by yavinash249** [comment]
Please assign me this issue. I'll do it in two languages.

**Comment by qwerty541** [comment]
Hey, @yavinash249! Thanks for your interest in our project! We are going to remove docs translations at all in future because we are unable to properly maintain them. Most of docs translations currently outdated and confuse users. I think this issue can be closed.
