### ISSUE TITLE
URL builder with live visual preview

### ISSUE THREAD

**Issue by NabiKAZ** [anuraghazra/github-readme-stats#1355]
You can have a visual generator for create URL and showing live preview, that users can simple change each params and real time can see preview.
Like this URL builder: https://ga-dev-tools.web.app/ga4/campaign-url-builder/ (Of course with the visual preview)

**Comment by anuraghazra** [comment]
Already working on it, just didn't got time to finish it. 

![grs-builder-update](https://user-images.githubusercontent.com/35374649/135898659-8450e680-5e8d-428b-a4f1-f45e1feca7a4.gif)


https://twitter.com/anuraghazru/status/1436748546926014475

**Comment by NabiKAZ** [comment]
Wonderful, that's preview is cool and exactly is I means. I waiting for it. 👍

**Comment by rickstaa** [comment]
This was replaced by #1761.
