### ISSUE TITLE
Retire letter-based grades. Instead display (mode rating - rating)/sigma.

### ISSUE THREAD

**Issue by KOLANICH** [anuraghazra/github-readme-stats#1369]
**Describe the bug**
>Available ranks are S+ (top 1%), S (top 25%), A++ (top 45%), A+ (top 60%), and B+ (everyone).

Do you seriously think that `top 60%` means `A+`, and `everyone` deserves `B+`?
IMHO it feels like bullshit. 

**Expected behavior**
Because grades are arbitrary, just retire them and show the numeric value. Assumming that the distribution is Gaussian, the standardized deviation from mean should be a goodk compact and intuitively understandable measure.

**Comment by rasel3800** [comment]
francois-rozet:patch-rank
