### ISSUE TITLE
PCDATA Invalid Char Error - Same as #177

### ISSUE THREAD

**Issue by Jongseong0111** [anuraghazra/github-readme-stats#1373]
**Describe the bug**

Same Issue as https://github.com/anuraghazra/github-readme-stats/issues/177.
I Think my username causes the issue.

>This page contains the following errors:
>error on line 110 at column 27: PCDATA invalid Char value 28
>Below is a rendering of the page up to the first error.

https://github-readme-stats.vercel.app/api?username=Jongseong0111

**Expected behavior**

Below is a picture when i directly paste url to browser
![image](https://user-images.githubusercontent.com/84963683/136659193-8686bccf-c835-43d1-8253-3925f495e55b.png)

**Screenshots / Live demo link (paste the github-readme-stats link as markdown image)**

Below is a picture when i paste url in my README.md
`![Anurag's GitHub stats](https://github-readme-stats.vercel.app/api?username=Jongseong0111)`

![image](https://user-images.githubusercontent.com/84963683/136659178-74599b3b-b513-4a37-9336-5f9362072e1c.png)

![image](https://user-images.githubusercontent.com/84963683/136659167-44627407-6281-4b38-a725-650a4c4649b7.png)

**Additional context**

As you suggest to fix a problem in  https://github.com/anuraghazra/github-readme-stats/issues/177, i add `&hide_title=true` to my url link.
However in that issue, you mentioned that this problem is fixed now.
I just wonder that if you can fix this problem with my username, so i can use title include my namein github stats.
Sorry for bothering with same issue. Thanks for your work!

**Comment by anuraghazra** [comment]
It's working, it was maybe just cached 

![](https://github-readme-stats.vercel.app/api?username=Jongseong0111)

**Comment by Jongseong0111** [comment]
Thanks a lot!!
