### ISSUE TITLE
Add code review to Github Stats Card

### ISSUE THREAD

**Issue by FayasNoushad** [anuraghazra/github-readme-stats#1394]
Please add `code reviews` to the [Github Stats Card](GitHub Stats Card) and improve ranks based on the number of code reviews. This would be implemented as a `Total Reviews` option next to `Total Prs`.

**Comment by rickstaa** [comment]
@FayasNoushad I updated your issue to better reflect the feature you are requesting. I did this so we can use this issue to track this feature request. Feel free to change it back.

**Comment by rickstaa** [comment]
This feature has not yet been released to the master branch. People that already want to use it can use @Marcholio PR on their own fork.

**Comment by rickstaa** [comment]
@FayasNoushad is it okay to keep this open? We use 👍🏻 to judge which pull requests and issues to merge (see https://github.com/anuraghazra/github-readme-stats/issues/1935). If this issue or the accompanying pull requests gets enough likes, I will merge it into the master.

**Comment by rickstaa** [comment]
If you need it closed, I can create a new issue 👍🏻.
