### ISSUE TITLE
[Feature Request] Hide specific languages in Top Languages Card

### ISSUE THREAD

**Issue by Jasonnor** [anuraghazra/github-readme-stats#140]
**Is your feature request related to a problem? Please describe.**

Because some languages inherently have more code lines than other languages,
I want to hide these exaggerated language statistics. 😥
Thanks!

[![Top Langs](https://github-readme-stats.vercel.app/api/top-langs/?username=Jasonnor)](https://github.com/anuraghazra/github-readme-stats)

**Describe the solution you'd like**

Maybe add a option like `Hiding individual stats` does, e.g.,
```
&hide=["Jupyter Notebook", "HTML"]
```

**Describe alternatives you've considered**

Not yet 😅

**Comment by terror** [comment]
We currently have the option to hide languages below a certain percentage. 

Either we implement the option to hide languages above a percentage or we add the option to hide specific languages and forget the idea of hiding languages that fall into a percentage category.

**Comment by Jasonnor** [comment]
Yes, as title says, what I want is to hide a specific language 😃

**Comment by nombrekeff** [comment]
I suggested this when adding this feature, but Anurag preferred to add the below percentage option.

I think this would be a nice option to have.

**Comment by anuraghazra** [comment]
> I suggested this when adding this feature, but Anurag preferred to add the below percentage option.
> 
> I think this would be a nice option to have.

I think we can remove the below percentage option maybe? if we are adding specific language hiding features they i don't think hide_langs_below option would be useful anymore.

**Comment by nombrekeff** [comment]
I agree. I think it would be a bit redundant to keep hide_langs_below if we add the hide languages option.

**Comment by martinRenou** [comment]
> Either we implement the option to hide languages above a percentage

This might not make sense for this specific issue actually, because in this particular issue (Jupyter Notebook being a predominant language that the person does not want to see) the percentage for other languages will need to be recomputed.

**Comment by martinRenou** [comment]
Ideally we could remove multiple languages?

**Comment by terror** [comment]
@martinRenou Yeah I didn't think about that. I think hiding specific languages is the way to go.

@anuraghazra I've done some work on this and got this to work over at https://github-readme-stats-69lhfhxhs.vercel.app/api/top-langs/?username=Jasonnor&hide_langs=[%22Jupyter%20Notebook%22]

Let me know what you guys think

**Comment by anuraghazra** [comment]
resolved in #150
