### ISSUE TITLE
Most Used Languages Not Showing Exact Result

### ISSUE THREAD

**Issue by rexardiente** [anuraghazra/github-readme-stats#1424]
**Describe the bug**
I noticed that its not showing the right calculations, since I'm always working on Scala language this past few months now but still showing html, CSS  and Javascript has higher result.

**Expected behavior**
I think my Scala and Java language should be much higher in percentage 

**Screenshots / Live demo link (paste the github-readme-stats link as markdown image)**
[github-readme-stats link](https://github-readme-stats.vercel.app/api/top-langs/?username=rexardiente&hide_border=true&theme=vue-dark)

**Comment by BlackdestinyXX** [comment]
Same problem

**Comment by yok4i** [comment]
I have this feeling as well. For comparison, please see the difference between the results of this app and another that I found.

https://github-readme-stats.vercel.app/api/top-langs?username=yok4i&show_icons=true&theme=dracula&locale=en&layout=compact
http://ionicabizau.github.io/github-profile-languages/?user=yok4i

How could I change the query so that the results would reflect the second graphic?

**Comment by anuraghazra** [comment]
> I have this feeling as well. For comparison, please see the difference between the results of this app and another that I found.
> 
> https://github-readme-stats.vercel.app/api/top-langs?username=yok4i&show_icons=true&theme=dracula&locale=en&layout=compact http://ionicabizau.github.io/github-profile-languages/?user=yok4i

Set langs_count param to 10 and will show all the data. 
https://github-readme-stats.vercel.app/api/top-langs?username=yok4i&show_icons=true&theme=dracula&locale=en&layout=compact&langs_count=10

**Comment by anuraghazra** [comment]
@rexardiente it doesn't matter if you have 10, 20, 30 or 100 repos in scala... we calculate languages by looking at which languages has most code in bytes in your repositories. 

And looking at your repos your js,html,php files are way larger than any of the scala repo codes. 
https://github.com/rexardiente/Real-Estate-Theme-2 

You even uploaded the whole node_modules folder in this repo, so of course javascript will saturate/dominate the language stats
https://github.com/rexardiente/Trade-Engine-Balance/tree/master/node_modules


It seems the stats are fine thus closing this issue, feel free to open another one if you have any further issues.

**Comment by avgupta456** [comment]
If you are still running into this issue, consider [github.com/avgupta456/github-trends](https://github.com/avgupta456/github-trends). This project calculates stats based on your individual commits and filters extremely large files for (hopefully) more accurate language stats. Check it out at [githubtrends.io](https://www.githubtrends.io) and let me know if you have any questions!
