### ISSUE TITLE
Ranking does not appear to reflect contributions

### ISSUE THREAD

**Issue by bartenbach** [anuraghazra/github-readme-stats#1425]
**Describe the bug**
The contributions do not appear to impact the ranking.

**Expected behavior**
I would expect a person with over a decade of contributions to have a higher ranking than someone who has nothing reported on the card.

**Screenshots / Live demo link (paste the github-readme-stats link as markdown image)**
Here are my personal stats including all commits and my private contributions:
![](https://github-readme-stats.vercel.app/api?username=bartenbach&include_all_commits=true&count_private=true)
Here are my buddy's stats (he hardly uses GH at all, also an A+ ranking):
![](https://github-readme-stats.vercel.app/api?username=koreden).

**Comment by rickstaa** [comment]
@bartenbach, @edoardottt The ranking system is currently being improved. There are two pull requests that are currently under review:
- https://github.com/anuraghazra/github-readme-stats/pull/1186
- https://github.com/anuraghazra/github-readme-stats/pull/960

You can add your support for any of these pull requests.

**Comment by rickstaa** [comment]
@bartenbach I think we can close this issue for now?
