### ISSUE TITLE
Most Used Language

### ISSUE THREAD

**Issue by thiagodalsanto** [anuraghazra/github-readme-stats#1430]
My Most Used Language Card is not showing all languages from my repositories. It's only showing the public repositories, I'm using `&count_private=true` and `&include_all_commits=true`. 
Should be marking more JavaScript in percentages and should have at least 5% C 

  <a href="https://github-readme-stats.vercel.app/api/top-langs/?username=thiagodalsanto&count_private=true&layout=compact&include_all_commits=true"> What github-readme-stats is showing
  </a>

How can I deploy on my own instance and use my own PAT ?

@anuraghazra

**Comment by anuraghazra** [comment]
You should deploy on your own instance in that case, 

There literally a whole section in the readme, find it 😉
