### ISSUE TITLE
Improve theme pull request filtering ability

### ISSUE THREAD

**Issue by rickstaa** [anuraghazra/github-readme-stats#1436]
**Is your feature request related to a problem? Please describe.**

While working through the pull request I noticed that `75` of the `146` pull requests are related to new themes (see https://github.com/anuraghazra/github-readme-stats/pulls?q=is%3Apr+is%3Aopen+theme). Most of these pull requests should be closed since they do not include vscode themes. 

**Describe the solution you'd like**

Maybe we can improve the [preview-theme.yml](https://github.com/anuraghazra/github-readme-stats/blob/master/.github/workflows/preview-theme.yml) GitHub action to automatically close the theme-related pull request for which no `vscode` theme is found? I think this will make it easier for us to maintain the repository. We can do this by using the [visualstudio marketplace API](https://marketplace.visualstudio.com/_apis). This API is not well documented but I managed to find out the right syntax (see [my StackOverflow answer](https://stackoverflow.com/a/69838929/8135687):

```json
{
    "filters": [
        {
            "criteria": [
                {
                	"filterType": 8,
                	"value": "Microsoft.VisualStudio.Code"
                },
                {
                	"filterType": 5,
                	"value": "Themes"
                },
                {
                  "filterType": 10,
                  "value": "<THEME_NAME>"
                }
            ]
        }
    ]
}
```

Here `<THEME_NAME>` will be read from the pull request that triggered the action (see https://github.com/anuraghazra/github-readme-stats/pull/1429/files). You can test this syntax out on [reqbin.com](https://reqbin.com/)

Additionally, we might need to update the [contribution guidelines](https://github.com/anuraghazra/github-readme-stats/blob/master/CONTRIBUTING.md#themes-contribution) to specify that we only accept pull requests to themes related to released vscode themes. Maybe we can add something similar to the text that is added in the preview-theme script.

https://github.com/anuraghazra/github-readme-stats/blob/bc6c22ea1727987542eef29f57b890f3a678a769/scripts/preview-theme.js#L15-L20

We can add the following to give users the ability to let us know that our action wrongly classified their theme as invalid:

```text
Please comment below if your theme is a valid vscode theme and you think your pull request should not have been closed.
```

We can then re-open the pull request on which the author replies.

### Invalid pull request example

Let's use our newest theme pull request as an example (i.e https://github.com/anuraghazra/github-readme-stats/pull/1429):

![image](https://user-images.githubusercontent.com/17570430/140312426-7b754e03-b88b-44c5-b02a-db15d76d28a8.png)

No vscode theme is found so this pull request would be closed.

### Valid pull request example

Let's use an accepted theme (i.e. https://github.com/anuraghazra/github-readme-stats/pull/1343):

![image](https://user-images.githubusercontent.com/17570430/140313365-9d2b8d02-95fd-44d7-b389-6ef42e68e3d7.png)

A vscode theme was found so this pull request will stay open for us to review.

### Problematic case

However, there is one problem with this approach when people add a `_light` or `_dark` suffix to the theme name (i.e. https://github.com/anuraghazra/github-readme-stats/pull/1379). In this case, the theme is a valid vscode theme, but the API finds no themes. This can, however, be solved by parsing the text to remove any light and dark prefixes.

## Alternative solution

We can also add a new  `vscode_theme_url` or `vscode_theme_name` the `theme description`. We can close a pull request for which the link/name is not valid if we do this.

**Comment by anuraghazra** [comment]
Hi @rickstaa 

Thanks for the detailed thoughts and high quality issue description on this.

Yeah I think we can improve the script with vscode API. 
It won't be a full proof system but will definitely improve the detection. 

> Also note that, the rule of "only vscode themes are accepted" is not truly strict, If i find a combination which passes a11y checks and has a very unique color combination I accept those too. (I know i know, thats very subjective)

**Comment by rickstaa** [comment]
Do you mean [a11y](https://www.a11yproject.com/checklist/). Mm, do you know if there are any automated tests we can do for checking the [a11y](https://www.a11yproject.com/checklist/) criteria? I saw multiple ones online but I do not directly see how they relate to theme colours (i.e. https://www.adrianbolonio.com/en/accessibility-github-actions/ and https://github.com/microsoft/accessibility-insights-action).

**Comment by rickstaa** [comment]
Amazing then I think automation just checking the WCAG AAA standards is the best way to go?

**Comment by anuraghazra** [comment]
I've implemented the color contrast check on this PR https://github.com/anuraghazra/github-readme-stats/pull/1439

**Comment by rickstaa** [comment]
@anuraghazra Looks great thanks for implementing this!
