### ISSUE TITLE
Stars 

### ISSUE THREAD

**Issue by VulcanWM** [anuraghazra/github-readme-stats#1441]
**Describe the bug**
The amount of stats you earned in total includes the stars you have done to your repository yourself.

**Expected behaviour**
It should remove the amount of stars you have done to your own repositories.

**Comment by anuraghazra** [comment]
A star is a star it doesn't matter if you starred your own repo or not. It is expected behaviour.

**Comment by VulcanWM** [comment]
But there might be people who star their own repos just to get their star amount higher
