### ISSUE TITLE
top language not adding kotlin

### ISSUE THREAD

**Issue by dayo05** [anuraghazra/github-readme-stats#1444]
**Describe the bug**
I have a source that upload as public written in kotlin. And after that, I add top-lang into my dayo05/readme.md. And Kotlin is not displaying on my image.

**Expected behavior**
Kotlin language is not calculated.

**Screenshots / Live demo link (paste the github-readme-stats link as markdown image)**
https://github.com/dayo05/GBS_Es 
this is the link of repo which is using Kotlin the most.

This is the image
https://camo.githubusercontent.com/9b00f344c72588eeedb686bb48d7ae0dfda59d683d559c4d2d257541505ce632/68747470733a2f2f6769746875622d726561646d652d73746174732e76657263656c2e6170702f6170692f746f702d6c616e67732f3f757365726e616d653d6461796f3035266c616e67735f636f756e743d38

**Comment by anuraghazra** [comment]
Forked repos are not calculated.
