### ISSUE TITLE
Error when loading my profile with all include_all_commits

### ISSUE THREAD

**Issue by SuperSandro2000** [anuraghazra/github-readme-stats#1455]
**Describe the bug**

I get an ``Cannot read property 'data' of undefined`` when loading my card with all commits.

**Expected behavior**

A image should be displayed like in the past.

**Screenshots / Live demo link (paste the github-readme-stats link as markdown image)**

![image](https://user-images.githubusercontent.com/7258858/141342785-c9a70686-ee71-4387-a052-f14dcdfb86e7.png)

**Additional context**

https://github-readme-stats.vercel.app/api?username=SuperSandro2000&include_all_commits=true

**Comment by kidonng** [comment]
Maybe you just need to use lowercased username: https://github-readme-stats.vercel.app/api?username=supersandro2000&include_all_commits=true

**Comment by SuperSandro2000** [comment]
Same behavior

**Comment by kidonng** [comment]
Alright, we see different results because of cache.

I guess the fundamental issue is that you have too many commits and the site is triggering rate/quota limit. It doesn't handle failed requests very well and shows a generic error instead.

**Comment by rickstaa** [comment]
I can not reproduce this issue.

[![Anurag's GitHub stats](https://github-readme-stats.vercel.app/api?username=SuperSandro2000&include_all_commits=true)](https://github.com/anuraghazra/github-readme-stats)

```md
[![Anurag's GitHub stats](https://github-readme-stats.vercel.app/api?username=SuperSandro2000&include_all_commits=true)](https://github.com/anuraghazra/github-readme-stats)
```
