### ISSUE TITLE
getting the language data without rendering the card

### ISSUE THREAD

**Issue by arndom** [anuraghazra/github-readme-stats#1458]
**Is your feature request related to a problem? Please describe.**

- I'd like for it to be possible to get the language data without rendering the card

**Describe the solution you'd like**

- Something like an endpoint call could work

**Comment by rickstaa** [comment]
@arndom thanks for your feature request. In my opinion, it however is outside the scope of this repository as you can easily request this information using the GitHub [GraphHQ](https://docs.github.com/en/graphql)  API. The following query syntax can be used:

```grapql
query userInfo($login: String!) {
  user(login: $login) {
    repositories(ownerAffiliations: OWNER, isFork: false, first: 100) {
      nodes {
        name
        languages(first: 10, orderBy: {field: SIZE, direction: DESC}) {
          edges {
            size
            node {
              color
              name
            }
          }
        }
      }
    }
  }
}
```
Query variables:

```grapql
{"login":"rickstaa"}
```

You can test this out using the [GraphHQ explorer](https://docs.github.com/en/graphql/overview/explorer).

**Comment by arndom** [comment]
Yeah, after I read through the code I saw that and was able to use it,
thanks for the awesome repo 👍👍

**Comment by rickstaa** [comment]
@arndom Great! Maybe we can close this issue?
