### ISSUE TITLE
Email not found

### ISSUE THREAD

**Issue by FayasNoushad** [anuraghazra/github-readme-stats#1465]
https://github.com/anuraghazra/github-readme-stats/blob/1cef6aca1b5ba2ccc7ecdef6d144c23fc225d223/scripts/push-theme-readme.sh#L7

This email not found

**Comment by rickstaa** [comment]
@FayasNoushad I think that email is added to highlight that the actions are done by a bot:

https://github.com/anuraghazra/github-readme-stats/blob/1cef6aca1b5ba2ccc7ecdef6d144c23fc225d223/scripts/push-theme-readme.sh#L8

What problems are you having because of this email not existing?

**Comment by anuraghazra** [comment]
It's just a dummy email, shouldn't cause any issues.
