### ISSUE TITLE
Count Jupyter as the language it contains

### ISSUE THREAD

**Issue by jorislimonier** [anuraghazra/github-readme-stats#1467]
Jupyter takes way more line than are actually written by the author, I'm guessing this is because you consider all of the raw JSON file.
Would it be possible to:
- only consider the content of the cells (inside `source` in the raw JSON)
- count is as a the language it is written in (inside `kernelspec` in the raw JSON)

Thanks

**Comment by anuraghazra** [comment]
No sorry this isn't possible all data comes from github's API we don't have any control over how github collects data. We only process and render it to the card.

**Comment by jorislimonier** [comment]
Right, thank you for your answer.
