### ISSUE TITLE
Please add an env variable called PAT_1 with your github token in vercel

### ISSUE THREAD

**Issue by donno2048** [anuraghazra/github-readme-stats#1473]
**Describe the bug**

> Please add an env variable called PAT_1 with your github token in vercel

instead of output

**Screenshots / Live demo link (paste the github-readme-stats link as markdown image)**

<img src="https://github-readme-stats.vercel.app/api/pin/?username=anuraghazra&repo=gatsby"/>

**Comment by donno2048** [comment]
It didn't work for some time, but it works now, closing

**Comment by priority3** [comment]
I also encountered the same bug. Have you solved it now？

**Comment by Chi20** [comment]
Same bug.Any solutions?

**Comment by MohdRash** [comment]
same bug spotted 

https://github-readme-stats.vercel.app/api?username=mohdrash&show_icons=true&count_private=true&theme=react&hide_border=true&bg_color=0D1117

**Comment by anuraghazra** [comment]
You can [deploy on your own vercel ](https://github.com/anuraghazra/github-readme-stats#deploy-on-your-own-vercel-instance)instance in the meanwhile to fix the issue.

For more info see https://github.com/anuraghazra/github-readme-stats/issues/1471

**Comment by guilhermeforprojeto** [comment]
Ainda mesmo bug

**Comment by guilhermeforprojeto** [comment]
bug ok
