### ISSUE TITLE
Bug report

### ISSUE THREAD

**Issue by william0620** [anuraghazra/github-readme-stats#1475]
**Describe the bug**
Maximum retries exceeded Please add  an env called PAT_1 with your github token in vercel

**Expected behavior**
Expected to show the star achieved.

**Additional context**
Just told me to file an issue

**Comment by ggssh** [comment]
> **Describe the bug** Maximum retries exceeded Please add an env called PAT_1 with your github token in vercel
> 
> **Expected behavior** Expected to show the star achieved.
> 
> **Additional context** Just told me to file an issue

I also have the same problem .

**Comment by FuckingToasters** [comment]
can relate - same issue here

**Comment by HeXavi8** [comment]
+1

**Comment by karimkohel** [comment]
same issue

**Comment by anuraghazra** [comment]
See #1471
