### ISSUE TITLE
Top language cards not working properly.

### ISSUE THREAD

**Issue by AnthonyGriffith** [anuraghazra/github-readme-stats#1480]
**Describe the bug**
The TOP languages generated in the profile readme is showing 99% of python, but I only have one **small** python project with less than 100 lines. (Azure-Cognitive-Services-Analizer). I even have another project (notes-manager) with a lot more of js files and lines than that project, also I have another project (tourney-manager) which has 500+ lines of c++. So this is quite confusing and I wouldn't like people to see false information in my profile.

**Expected behavior**
The top languages card should not have that much of python and have more of javascript, html, css and c++ instead.

**Screenshots / Live demo link (paste the github-readme-stats link as markdown image)**
![image](https://user-images.githubusercontent.com/58449215/143792144-1d477bfa-25e3-4d33-87ea-f5902647b47a.png)
**Link:**  https://github-readme-stats.vercel.app/api/top-langs/?username=AnthonyGriffith&langs_count=8&count_private=false&layout=compact&theme=react&hide_border=true&bg_color=0D1117
I hope someone can help.

**Comment by AustinCaudill** [comment]
I believe I am having the same problem. My top language is shown as "Jupyter Notebook" when I've only got one small repo that consists of it.

**Comment by anuraghazra** [comment]
Hi @AnthonyGriffith looking at your python repo, it's certainly not "small" 
There is this whole libraries included in it thats why language card is showing python at top. We don't calculate the language stats all the data is coming from GitHub's API and we just format and render it to the page. 

https://github.com/AnthonyGriffith/Azure-Cognitive-Services-Analizer/tree/master/venv/Lib/site-packages

**Comment by anuraghazra** [comment]
@AustinCaudill You have a huge 15mbJupyter Notebook file, since certainly saturates all other language sizes in your repos. 
https://github.com/AustinCaudill/Hackathon-No-1/blob/main/.ipynb_checkpoints/Submission-checkpoint.ipynb

Try considering hiding `Jupyter Notebook` from your profile card. 

https://github-readme-stats.vercel.app/api/top-langs?username=AustinCaudill&hide=Jupyter%20Notebook

**Comment by vincentmunene49** [comment]
i think i have more kotlin code than javascript am not even quite sure i have used scss but i do not see any kotlin.

link: https://github.com/vincentmunene49/
