### ISSUE TITLE
GitHub Extra Pins can put 2 repos in one column by some config?

### ISSUE THREAD

**Issue by techzealot** [anuraghazra/github-readme-stats#1490]
**Is your feature request related to a problem? Please describe.**
It’s great that GitHub Extra Pins can put 2 repos in a row by some config as github pins.It will look nice when we pin a lot repos

**Describe the solution you'd like**
as the compact layout config,we can add layout=compact to support this

**Describe alternatives you've considered**

**Additional context**

**Comment by anuraghazra** [comment]
You can use tables to organize them side by side.

**Comment by techzealot** [comment]
> You can use tables to organize them side by side.

that's great idea, thank you very much!
