### ISSUE TITLE
Release count

### ISSUE THREAD

**Issue by FLAK-ZOSO** [anuraghazra/github-readme-stats#1495]
**Count languages in releases**
It would be useful having the stats counting the files attached in the releases. 

Is it possible?

**Comment by rickstaa** [comment]
@FLAK-ZOSO Thanks for your feature request. Can you give an example of a repository with files in the releases you want to test? I have not encountered a release that contains non compiled or compressed formats (`exe`,  `zip` and `tar.gz` etc.).

**Comment by FLAK-ZOSO** [comment]
@rickstaa I sometimes attached to the release some files like `test.py` to show the usage of the module for example.
Now I know releases aren't used this way, but when I created this issue I didn't.

**Comment by rickstaa** [comment]
@FLAK-ZOSO Ah, I see. Thanks for explaining! Including these files will require us also to fetch all releases of a repository. As you already mentioned, it is quite a unique use case. I will therefore close this issue for now.
