### ISSUE TITLE
count_private not working

### ISSUE THREAD

**Issue by gabzin** [anuraghazra/github-readme-stats#1498]
The amount still the same with count_private off or on

**Comment by Minituff** [comment]
I think you need to add `count_private=true` instead of `private_count=true` according to their docs.
https://github.com/anuraghazra/github-readme-stats#adding-private-contributions-count-to-total-commits-count

**Comment by gabzin** [comment]
Just misspelled. I do have `count_private=true` at parameters

**Comment by Minituff** [comment]
Okay, then I had this problem too. I had to host my own instance on Vercel, since you need to give it your private Personal Access Token (PAT) so it can securely ready your private commits. You can follow the instructions [here](https://github.com/anuraghazra/github-readme-stats/pull/1508), it's actually really easy and free. 

Also, I had to give the PAT `repo` permissions in order for it to work. See [this](https://github.com/anuraghazra/github-readme-stats/pull/1508) issue for more details.

**Comment by hui-shao** [comment]
> Okay, then I had this problem too. I had to host my own instance on Vercel, since you need to give it your GitHub Personal Access Token (PAT) so it can securely read your private commits. You can follow the instructions [here](https://github.com/anuraghazra/github-readme-stats#check-out-step-by-step-video-tutorial-by-codestackr) (you need to expand it), it's actually really easy and free.
> 
> Also, I had to give the PAT `repo` permissions in order for it to work. See [this](https://github.com/anuraghazra/github-readme-stats/pull/1508) issue for more details.

Thanks  a lot. It works.

**Comment by qwerty541** [comment]
> I've had already gave the PAT repo permissions but it's still not working, can anyone tell me how to fix that?

Hey, @ahsanzizan! As specified in [our Vercel deployment documentation](https://github.com/anuraghazra/github-readme-stats#on-vercel) (see nineth step), to show your private contributions you should enable `repo` and `user` permissions.

![image](https://github.com/anuraghazra/github-readme-stats/assets/53787217/9c94bb06-a59d-402e-8014-5f821046b630)

![image](https://github.com/anuraghazra/github-readme-stats/assets/53787217/c835b969-9850-4cc9-82ed-b9207214b47f)

Also for your information, `count_private` querystring parameter is not longer supported. Private contributions will be automatically shown on your stats card if you deploy own instance using PAT with correct permissions.
