### ISSUE TITLE
Label repositories with Jupyter Notebook as Python instead

### ISSUE THREAD

**Issue by yudhiesh** [anuraghazra/github-readme-stats#1509]
**Is your feature request related to a problem? Please describe.**
If you look at my Top Languages: 

[![Top Languages](https://github-readme-stats.vercel.app/api/top-langs/?username=yudhiesh&langs_count=8)](https://github.com/anuraghazra/github-readme-stats)

Jupyter Notebook is the overwhelming leader when the actual underlying language is Python

**Describe the solution you'd like**

I would like to be able to consider Jupyter Notebooks as Python instead of treating them separately. 

**Describe alternatives you've considered**
I have tried adding `hide=jupyter%20notebook`, which sort of fixes it but I think this ignores `Jupyter Notebooks` completely. 

 [![Top Languages](https://github-readme-stats.vercel.app/api/top-langs/?username=yudhiesh&langs_count=8&hide=jupyter%20notebook)](https://github.com/anuraghazra/github-readme-stats)

**Comment by mike-tr** [comment]
same jupiter notebook shows way to much even if i use it maybe for 1% of all projects.

**Comment by anuraghazra** [comment]
Sorry but we don't control any of the data, all the language data is coming from the GitHub's API and we only show them as is, we don't have any plans to add substitute languages.
