### ISSUE TITLE
Erroneous language count.

### ISSUE THREAD

**Issue by MUzairS15** [anuraghazra/github-readme-stats#1516]
In most used lang Dart is appearing on top, but I have never contributed in dart language, I just have a repo in which I have contributed in javascript and my friend has contributed in Dart.
<img width="308" alt="Screenshot 2022-01-02 at 11 14 31 AM" src="https://user-images.githubusercontent.com/79860504/147867413-40ef7bbe-edc1-4ecb-8463-d645cf2818cc.png">
Also, I have done contributions in Java language and have merged PRs in the central repo, but still, Java doesn't have even 0.1% weight.
(Even if I make counts to 50 or so Java doesn't appear)

**Comment by elsowiny** [comment]
Dealing with this too, wondering if there is an active fix in place?

**Comment by AdaoBMF** [comment]
Same  here, my card is showing C and C# that I never had never committed and don't show any of Java that I have used a lot. 
![langCard](https://user-images.githubusercontent.com/81498416/148903336-d96b0e4d-1202-45ba-a6eb-5569a85e4851.png)

**Comment by stscoundrel** [comment]
If you want to ignore some languages, you can just add `hide` parameter in the request. In your case, `&hide=dart`

So for example:

<img src="https://github-readme-stats.vercel.app/api/top-langs/?username=MUzairS15&layout=compact&hide=dart&langs_count=10" />

Unsure if your Java is counted as Kotlin, as it does appear in there.

**Comment by MUzairS15** [comment]
Hiding dart doesn't work, I tried, I also increased language counts but it didn't helped.

**Comment by rickstaa** [comment]
@elsowiny Thanks for your comment. We are aware of the limitations of the current language card. Several improvements have been proposed in https://github.com/anuraghazra/github-readme-stats/issues/1801#issuecomment-1177338295. Let's close #1516 and continue the discussion on #1801.
