### ISSUE TITLE
The "hide_langs_below" query param is not working on "Top Language" cards

### ISSUE THREAD

**Issue by ming-tsai** [anuraghazra/github-readme-stats#152]
**The "hide_langs_below" query param is not working on "Top Language" cards**
The `hide_langs_below` query param is not working when the username has a **-(dash)**

**Expected behavior**
![image](https://user-images.githubusercontent.com/37890026/88235806-9c965c00-cc49-11ea-81d3-9c650a1494ce.png)
**ScreenShots**
![image](https://user-images.githubusercontent.com/37890026/88235876-c3ed2900-cc49-11ea-907a-3853e3c7f9fa.png)
**Live demo**
![Live demo](https://github-readme-stats.anuraghazra1.vercel.app/api/top-langs/?username=ming-tsai&hide_langs_below=2)

**Comment by terror** [comment]
Looks fine to me, use this query https://github-readme-stats.vercel.app/api/top-langs/?username=ming-tsai&hide_langs_below=8

**Comment by ming-tsai** [comment]
I thought `hide_langs_below` start subtracting from the top 4 languages.

**Comment by terror** [comment]
> I thought `hide_langs_below` start subtracting from showing languages

Currently hide_langs_below takes in a percentage value and every language under that percentage value gets hidden. 

However pretty soon you'll be able to hide specific languages as well.
