### ISSUE TITLE
Star count is wrong

### ISSUE THREAD

**Issue by kapoorlab** [anuraghazra/github-readme-stats#1522]
**Describe the bug**
The count of the stars shown on my profile is 9, however just by counting the stars on my public pinned repos gives you a count of 15, hence the way your code is counting the stars seem to be erroneous.

**Expected behavior**
Correct star count else the other values displayed could also have the same error.

**Screenshots / Live demo link (paste the github-readme-stats link as markdown image)**
See the stats on my Readme file and you will see the error https://github.com/kapoorlab

**Comment by maslick** [comment]
I think he is calculating the Stars **given**, but not **received**

**Comment by garronej** [comment]
It's counting stars on project that belongs to the account.
