### ISSUE TITLE
[Top Languages] Blog repositories(xxxx.github.io) should not be counted.

### ISSUE THREAD

**Issue by MrBenWang** [anuraghazra/github-readme-stats#153]
Like this. HTML should not be Top1，because it's automatically generated by Hugo .🤣🤣🤣

![top-languages](https://user-images.githubusercontent.com/9692054/88248186-e1b2a080-ccd2-11ea-8861-1a7c23ba7e23.jpg)

**Comment by nombrekeff** [comment]
Hmm I see, this will be solved when/if https://github.com/anuraghazra/github-readme-stats/issues/140 is implemented. You could manually specify which languages to hide.

**Comment by MirayXS** [comment]
`/docs/` folder is also a blog site ( a way to "load" the website ) so it should also not be counted.

**Comment by MirayXS** [comment]
Was this fixed, @anuraghazra ?

I saw a big change in my stats card, that's why i ask.

**Comment by anuraghazra** [comment]
Hi @MrBenWang @MirayXS currently we cannot exclude certain folders from get counted because github does not provide any ways to fetch folder sizes of exclude particular folders.

**Comment by anuraghazra** [comment]
Hi @MrBenWang i think there is a possible solution to this,

Maybe we can use .gitattributes to ignore some directories to be counted with the languages, which is a [github lisgust](https://github.com/github/linguist) feature.


Add a new file named `.gitattributes` with the contents :

```sh
dist/* linguist-vendored=false
```

replace the `dist` with the folder name you want to ignore.

**Comment by MrBenWang** [comment]
@anuraghazra Sorry, I am late to reply you.  `linguist-vendored=false` may not work.  https://github.community/t/linguist-vendored-false-not-working/940

My `.gitattributes` file,: 
``` 
./* linguist-vendored=true
```

Wait a few days................

**Comment by anuraghazra** [comment]
This issue should be solved by the new exclude_repo option which let's you exclude specified repo from getting counted. Implemented in #493
