### ISSUE TITLE
Looks like env var PAT_1 has some problem.

### ISSUE THREAD

**Issue by zachjonesnoel** [anuraghazra/github-readme-stats#1531]
**Describe the bug**
Looks like env var PAT_1 has some problem.
**Expected behavior**
The stats for the user handle specified should be fetched and displayed.

**Screenshots / Live demo link (paste the github-readme-stats link as markdown image)**
![image](https://user-images.githubusercontent.com/12515425/149528556-5d529d7c-1db3-403e-9c82-4bbd6b279577.png)

**Additional context**

**Comment by darkRaspberry** [comment]
Reproducible

**Comment by francois-rozet** [comment]
```
![](https://github-readme-stats.vercel.app/api?username=francois-rozet)
```

![](https://github-readme-stats.vercel.app/api?username=francois-rozet)

**Comment by VCNinc** [comment]
Having this issue too

**Comment by anuraghazra** [comment]
see #1471
