### ISSUE TITLE
Maximum retries exceeded

### ISSUE THREAD

**Issue by mrhrifat** [anuraghazra/github-readme-stats#1538]
**Describe the bug**
I have added `2` **GitHub Extra Pins** in my profile at past . Now I want to add `1` more. But I'm getting an error of 
> Something Went Wrong. File an issue at https://git.io/JJmN9
Maximum retries exceeded
Please add an env variable called PAT_! with your github token in vercel

Here is my code of Extra Pins
```
![](https://github-readme-stats.vercel.app/api/pin/?username=mrhrifat&repo=spur-quote)
```

**Expected behavior**
[![Readme Card](https://github-readme-stats.vercel.app/api/pin/?username=anuraghazra&repo=github-readme-stats)](https://github.com/anuraghazra/github-readme-stats)

**Screenshots**
![image](https://user-images.githubusercontent.com/45077312/149663463-396de322-22b5-4648-818d-85c7e0dbda08.png)

**Comment by KillaBoi** [comment]
Seems to be back up, I think there was a small hiccup with the service...

**Comment by Cactooz** [comment]
Yeah, my ones are also back now!
