### ISSUE TITLE
Repos Not showing

### ISSUE THREAD

**Issue by Jona-Walpert** [anuraghazra/github-readme-stats#1547]
The Image wont Show my repos

It should say 4 Repos but IT says 0

github.com/Jona-Walpert/

I'm new to GitHub, so I don't know how to write an issue Report.
Bye

**Comment by Maghil** [comment]
does it display repos count in the card? I tried using it and it doesn't show repo count for me

and regarding issue report. try to attach related logs, instruction on how to reproduce or in this case some screen shots

**Comment by Jona-Walpert** [comment]
I found the Problem. I'm new to GitHub and thought PRs means repositories. My bad.(and i'm
 sorry for my bad Englisch).
