### ISSUE TITLE
Language color not shown if primary language color unknown

### ISSUE THREAD

**Issue by WEGFan** [anuraghazra/github-readme-stats#155]
**Describe the bug**
I have a repo which primary language is Mathematica, and the language color is not shown on the repo card. (in svg the color's `fill` is `null`)

**Expected behavior**
The color should be `#ccc`

**Screenshots / Live demo link (paste the github-readme-stats link as markdown image)**
![image](https://github-readme-stats.vercel.app/api/pin/?username=ZSCTF&repo=ZSCTF2019)

**Additional context**
This is the `primaryLanguage` section of the response from Github API

```json
"primaryLanguage": {
    "color": null,
    "id": "MDg6TGFuZ3VhZ2UzNTU=",
    "name": "Mathematica"
}
```

And the code here only applies a default color (should be `#ccc`? not sure why it's `#333`) when `primaryLanguage` is `null`

https://github.com/anuraghazra/github-readme-stats/blob/03f55e809e417abcc0e4b462d52f3c3c52dd1a27/src/renderRepoCard.js#L30

**Comment by anuraghazra** [comment]
Hi @WEGFan thanks for opening the issue we will look at the bug asap. 

Yes `const langColor = primaryLanguage ? primaryLanguage.color : "#333"; ` this logic fails because the color is returning null from github's api
