### ISSUE TITLE
rank_color parameter

### ISSUE THREAD

**Issue by sevenc-nanashi** [anuraghazra/github-readme-stats#1567]
**Is your feature request related to a problem? Please describe.**
It would be good if we can change rank(`A++`) color, like:
![image](https://user-images.githubusercontent.com/59691627/152305463-6d8390cb-63ba-4b87-8dc6-00da05ff8291.png)

**Describe the solution you'd like**
`rank_color` parameter for Rank card.

**Describe alternatives you've considered**
(None)

**Additional context**

**Comment by rickstaa** [comment]
@sevenc-nanashi Thanks for your feature request. Unfortunately, at the current time, we decided to add this feature to keep the cards consistent (see https://github.com/anuraghazra/github-readme-stats/issues/221#issuecomment-664835328).
