### ISSUE TITLE
Centre Text Inside Circle

### ISSUE THREAD

**Issue by jgphilpott** [anuraghazra/github-readme-stats#1589]
**Describe the Bug**

Maybe it's just me but the grade score (A, A+, A++) inside the circle looks to be a little bit off centre... it looks a little to high and possibly slightly to the right as well. I think it should be perfectly centred vertically and horizontally.

**Comment by rickstaa** [comment]
@jgphilpott Thanks for letting us know. It looks that #1628 fixes your issue.

**Comment by jgphilpott** [comment]
Yes, it looks like a good fix! Can't wait for it to get merged!
