### ISSUE TITLE
Add review state 

### ISSUE THREAD

**Issue by kerthcet** [anuraghazra/github-readme-stats#1599]
**Is your feature request related to a problem? Please describe.**
No problem, but I was wondering whether we can add the review state. I think it's also reasonable.

**Describe the solution you'd like**
None.

**Describe alternatives you've considered**
None.

**Additional context**
None

**Comment by rickstaa** [comment]
@kerthcet Ah, I see. I think your feature request makes sense. There is already an issue open for this feature request see https://github.com/anuraghazra/github-readme-stats/issues/1394. You can add your support for this feature on this issue. I will close this issue for now.

**Comment by rickstaa** [comment]
@kerthcet There appears to be a pull request for this feature request see #1404. We did not review it yet but you can use it on your own instance.
