### ISSUE TITLE
[Proposal] New Top Language Detection Algorithm 

### ISSUE THREAD

**Issue by kitswas** [anuraghazra/github-readme-stats#1600]
**Is your feature request related to a problem? Please describe.**

This is related to an [earlier issue](https://github.com/anuraghazra/github-readme-stats/issues/481).  
I am not quite happy with the way Top Languages are calculated (just counting the bytes).

**Describe the solution you'd like**

The new method is inspired by the [h-index](https://en.wikipedia.org/wiki/H-index?wprov=sfla1). 

For a language L,  
let `x = byte count`(currently in use) and `y = number of repositories using L`.  
```
x*y = k^2
k = sqrt(xy)
```
Now we can use this k-metric to find the top languages and their weightage.
The higher the value of `k`, the more used is the language.

While this method is an improvement over both byte count and the number of repositories, it is in no way a magic wand.

**Describe alternatives you've considered**

None at the moment.

**Additional context**

I have gone through [this issue](https://github.com/anuraghazra/github-readme-stats/issues/136) mentioned in the FAQ.

_P.S.: This is the first time I am trying to contribute to open source. Please point out if I make a mistake._

**Comment by anuraghazra** [comment]
Hi @kitswas thanks for the proposal, quite interesting. 

What do you think of the downsides of this approach? Can you mention any examples? 
And also how exactly this method is better than just counting bytes? Will be better to have a comparison.

**Comment by kitswas** [comment]
> What do you think are the downsides of this approach? 

The size of a program to perform the same task varies when written in different languages. This metric does not take it into consideration.  
The alternatives (counting bytes and [number of repositories with the language](https://ionicabizau.github.io/github-profile-languages/)) are no better though.

> And also how exactly this method is better than just counting bytes?

When a language appears in multiple repositories, it means that the developer has some degree of reliance on it. This is an attempt to factor it into the calculation.

> Will be better to have a comparison.

Here's a theoretical comparison.
[Comparsion.pdf](https://github.com/anuraghazra/github-readme-stats/files/8102608/Comparsion.pdf)

**Comment by rickstaa** [comment]
Just for reference, in case people want to chip in the discussion relating to the algorithm used to determine the 'top languages '. This issue is also discussed in the related PR #1732.

**Comment by rickstaa** [comment]
This was implemented in https://github.com/anuraghazra/github-readme-stats/pull/1732.
