### ISSUE TITLE
Research Publication Citation and Status Display Card

### ISSUE THREAD

**Issue by jyotirmay123** [anuraghazra/github-readme-stats#1601]
**Is your feature request related to a problem? Please describe.**
With currently available cards to show on GitHub pages, there is no availability to integrate google scholar citation index. 

**Describe the solution you'd like**
However, it is possible to extract the citations and other stats from scholar.google.com and need to deploy with a similar strategy as it happens here for other services.

**Describe alternatives you've considered**
No dynamic alternative solution exists as such as per my findings till now.

**Comment by anuraghazra** [comment]
Hi @jyotirmay123 
Thanks for the feature request. 
But I don't think we will be adding any cards related to google scholar, since github-readme-stats mostly focuses on statistics of developer focused data collected from GitHub API.

**Comment by jyotirmay123** [comment]
Thank you @anuraghazra for clarifying this.
