### ISSUE TITLE
Not showing commits right

### ISSUE THREAD

**Issue by mikesjak** [anuraghazra/github-readme-stats#1609]
**Describe the bug**
On my account after my last commit the number of commits came down to 0.
And yes, these commits should appear because they are on two of mine public repositories.

**Expected behavior**
There should appear something abour 25/30.

**Screenshots / Live demo link (paste the github-readme-stats link as markdown image)**
This appears on my profile.
<img width="473" alt="Snímek obrazovky 2022-02-23 v 17 05 21" src="https://user-images.githubusercontent.com/97596417/155358384-7c1dce33-e464-441b-bc22-b660772a6ce7.png">

**Comment by rickstaa** [comment]
@mikesjak Thanks for your issue. I checked your profile and the commit count seems to be updated.

<a href="https://github.com/anuraghazra/github-readme-stats"><img align="center" src="https://github-readme-stats.vercel.app/api?username=mikesjak&show_icons=true&include_all_commits=true&theme=dark&hide_border=true" alt="Mikesjak's github stats" /></a>  

Please be aware that we cache the results to decrease the API load, so it takes some time to update the card (see https://github.com/anuraghazra/github-readme-stats/issues/1571#issuecomment-1047850921).

**Comment by mikesjak** [comment]
I know that. I had the commits right but it suddenly dropped to 0. It is ok now. Thanks for your help.

**Comment by rickstaa** [comment]
@mikesjak I will close this for now. Feel free to comment below if the problem re-appears.
