### ISSUE TITLE
Missing params "username" 

### ISSUE THREAD

**Issue by REEKRAJROY** [anuraghazra/github-readme-stats#1610]
WakaTime stats stopped showing, and the following message came up:-
Missing params "username"

**Comment by anuraghazra** [comment]
What's your username?

**Comment by REEKRAJROY** [comment]
REEKRAJROY

**Comment by anuraghazra** [comment]
Is that your wakatime username? 

because it doesn't seem to exist. 
https://github-readme-stats.vercel.app/api/wakatime?username=REEKRAJROY

**Comment by REEKRAJROY** [comment]
It actually has been working all this while

**Comment by rickstaa** [comment]
@REEKRAJROY Thanks for letting us know. I will close this issue for now. Please comment below if you run into issues in the future.
