### ISSUE TITLE
Allow to hide specific languages

### ISSUE THREAD

**Issue by yonatankarp** [anuraghazra/github-readme-stats#1629]
As a backend developer, I'm ofter using pre-defined CSS files for my personal projects. As they're pretty big they're ending up being ~70-75% of my language usage even though in practice I didn't make any actual CSS work.

I would like to be able to disable some languages from being shown on the languages graph (e.g. CSS, JS)

**Comment by rickstaa** [comment]
@yonatankarp Thanks for your issue. Did you already try the language card `hide` argument (see https://github.com/anuraghazra/github-readme-stats#language-card-exclusive-options)?

**Comment by yonatankarp** [comment]
I've missed it, this issue can be closed ❤️
