### ISSUE TITLE
Auto close themes that don't adhere to our guidlines in 10 days

### ISSUE THREAD

**Issue by rickstaa** [anuraghazra/github-readme-stats#1631]
It would increase maintainability if we automatically close themes that do not adhere to our guidelines after 30 days if they do not receive commits. This would give users enough time to fix issues and keep our pull request backlog clean.

**Comment by anuraghazra** [comment]
Yeah nice idea, we can do that. Although will probably add 10days limit. 30days is bit too long.

**Comment by rickstaa** [comment]
I agree. I will review #1633 and start these theme GH-action updates later this week.
