### ISSUE TITLE
[Feature Request] New card type: Most used topics

### ISSUE THREAD

**Issue by tobiasvl** [anuraghazra/github-readme-stats#164]
On organization profile pages (such as https://github.com/github), there's a list of the top 5 most used topics on repos in the organization.

Now that we can show our top languages (another feature organizations had already), It'd be cool to be able to display my most used topics too!

![image](https://user-images.githubusercontent.com/80824/88339202-e9f1f680-cd39-11ea-9277-62def2d18494.png)

**Comment by terror** [comment]
This could be cool, I like it.

**Comment by anuraghazra** [comment]
Thanks for requesting the feature @tobiasvl 

yeah it's a good idea but i really don't want to bloat the service with lots of features which might not be too useful.
maybe i'll wait for some upvotes before implementing this.
