### ISSUE TITLE
Top languages stat is somewhat misleading ?

### ISSUE THREAD

**Issue by Koushikphy** [anuraghazra/github-readme-stats#1642]
I feel the top languages card calculation is somewhat misleading. For me, it shows https://github-readme-stats.vercel.app/api/top-langs/?username=koushikphy&layout=compact

[![Top Langs](https://github-readme-stats.vercel.app/api/top-langs/?username=koushikphy&layout=compact)](https://github.com/anuraghazra/github-readme-stats)

But this is somewhat misleading for me. This shows more than half of my codes are in Fortran, which is not true. I believe the calculation is done by counting all the sizes of the repo languages (here https://github.com/anuraghazra/github-readme-stats/blob/master/src/fetchers/top-languages-fetcher.js#L47). It would be better to only consider one language, the primary one, for one repo and count them up. In such a condition my stats would look like:
```
Python: 15  
HTML: 10  
JavaScript: 8  
Fortran: 8  
Dart: 3  
TeX: 2  
Jupyter Notebook: 2  
Julia: 1  
Shell: 1
```
Which is a fairly accurate representation of my overall coding activity. So, I believe there should be an option to represent only one primary language per repo.

**Comment by rickstaa** [comment]
@Koushikphy thanks for reporting this. There has been a lot of debate about the accuracy of the language count mechanism (see https://github.com/anuraghazra/github-readme-stats/discussions/1027). The latest proposal can be found in #1600. I will close this issue for now.
