### ISSUE TITLE
Support different themes on light and dark mode.

### ISSUE THREAD

**Issue by fernvenue** [anuraghazra/github-readme-stats#1645]
**Is your feature request related to a problem? Please describe.**
GitHub has been [supporting a feature](https://docs.github.com/en/get-started/writing-on-github/getting-started-with-writing-and-formatting-on-github/basic-writing-and-formatting-syntax#specifying-the-theme-an-image-is-shown-to) that allows us to display an image for a specific color theme since last November, so I thought maybe we could show different card themes for the light and dark modes of the GitHub profile page? As stated in the documentation, I tried appending `#gh-dark-mode-only` and `#gh-light-mode-only` to the end of cards URL in Markdown. Unfortunately, it doesn't work.

**Describe the solution you'd like**
I would like the card theme to work properly with the `#gh-dark-mode-only` and `#gh-light-mode-only` tags. If it already works with tags, can anyone please tell me how? And I hope this can be explained in the README file.

**Describe alternatives you've considered**
I don't have any other ideas at the moment, but it would be great if there was any way to help us make the light and dark mode users both have the best experience :)

**Additional context**
Let me show some examples.

- Theme `github_dark` on dark mode:

![screen](https://user-images.githubusercontent.com/84565547/158271282-78c5ede9-7344-4e97-86d9-bac36e8f11ab.png)

:)

- Theme `github_dark` on light mode:

![screen](https://user-images.githubusercontent.com/84565547/158271491-ceb12b4d-ea2f-4ee8-89f3-ec0ca477a983.png)

:(

- Theme `default` on dark mode:

![screen](https://user-images.githubusercontent.com/84565547/158271343-a9e9edb1-fc0d-4375-94e5-4bb731879287.png)

:(

- Theme `default` on light mode:

![screen](https://user-images.githubusercontent.com/84565547/158271454-47a4fbed-8885-414b-a944-9ab4dcb192f8.png)

:)

**Comment by rickstaa** [comment]
Related to #1236.

**Comment by anuraghazra** [comment]
You can use this trick https://github.com/anuraghazra/github-readme-stats/discussions/1415#discussioncomment-2152317

**Comment by fernvenue** [comment]
> You can use this trick [#1415 (comment)](https://github.com/anuraghazra/github-readme-stats/discussions/1415#discussioncomment-2152317)

Awsome! Thank you so much :)
