### ISSUE TITLE
Increase language count in top languages

### ISSUE THREAD

**Issue by Santanu29** [anuraghazra/github-readme-stats#1651]
**Is your feature request related to a problem? Please describe.**
Please increase the total number of languages in the top languages section. As a programming and development enthusiast I love trying out new programming languages and frameworks and I want that to be showcased on my Github profile. As it has come to my notice that I am not the only individual with this request. There have been previous instances of users requesting the feature [#1074 (comment)](https://github.com/anuraghazra/github-readme-stats/issues/1074#issuecomment-858408843) and [#909 (comment)](https://github.com/anuraghazra/github-readme-stats/issues/909#issuecomment-788896431). 

**Describe the solution you'd like**
The maximum allowed limit of languages to be displayed be increased (I was hoping for 20).
A different solution might be to display all the languages (option can be added) where the user can decide to display all the languages used sorted in order of most used to least used. 

**Additional context**
This solution can help recruiters as the person can display their profiles and will give a clear-cut look at the programming experience of the person.

![Screenshot 2022-03-16 212221](https://user-images.githubusercontent.com/69161246/158631883-b53410c7-7fb2-43ff-8242-61fafc49b415.png)

**Comment by RohitSingh107** [comment]
Really It's very important to increase languages count as lot of people work with tons of languages way more than limit of 10. I hope language count will increase as soon as possible.

**Comment by RohitSingh107** [comment]
Please increase language count to 30 or 50!

**Comment by rickstaa** [comment]
@RohitSingh107, @Santanu29 not sure how we can increase the `langs_count` above 10 without making the card look very bulky. I would therefore prefer to keep it on 10 since I think it will suit most people's needs. People that still want to show more languages can easily achieve this by forking the repository, changing the following code

https://github.com/anuraghazra/github-readme-stats/blob/112efb4b920d34e3b959c341c0ba3d6d8b9cebe4/src/cards/top-languages-card.js#L160

and deploying their [own Vercel instance](https://github.com/anuraghazra/github-readme-stats#deploy-on-your-own-vercel-instance).

@anuraghazra, what do you think?

**Comment by rickstaa** [comment]
With the compact layout, it still looks reasonable:

![image](https://user-images.githubusercontent.com/17570430/193549693-d021c679-0be5-487f-b21b-5a8eb26a1d38.png)

The non-compact layout is problematic

**Comment by RohitSingh107** [comment]
> 

How you got this? Please tell

**Comment by rickstaa** [comment]
> People that still want to show more languages can easily achieve this by forking the repository, changing the following code
> 
> https://github.com/anuraghazra/github-readme-stats/blob/112efb4b920d34e3b959c341c0ba3d6d8b9cebe4/src/cards/top-languages-card.js#L160
> 
> and deploying their [own Vercel instance](https://github.com/anuraghazra/github-readme-stats#deploy-on-your-own-vercel-instance).

Like I stated above:

> People that still want to show more languages can easily achieve this by forking the repository, changing the following code
>
>[github-readme-stats/src/cards/top-languages-card.js](https://github.com/anuraghazra/github-readme->stats/blob/112efb4b920d34e3b959c341c0ba3d6d8b9cebe4/src/cards/top-languages-card.js#L160)
>
>Line 160 in [112efb4](https://github.com/anuraghazra/github-readme->stats/commit/112efb4b920d34e3b959c341c0ba3d6d8b9cebe4)
>
> let langsCount = clampValue(parseInt(langs_count), 1, 10); 
>and deploying their [own Vercel instance](https://github.com/anuraghazra/github-readme-stats#deploy-on-your-own-vercel->instance).

I hope that helps!

**Comment by rickstaa** [comment]
Maybe we can allow up to `20` when the layout is `compact` and up to `10` when the layout is `default`?

![image](https://user-images.githubusercontent.com/17570430/193622663-55445108-83a3-410f-b307-4f185f9503e0.png)

![image](https://user-images.githubusercontent.com/17570430/193622717-0b07bd3f-a635-44c5-aeb8-75beaa65e901.png)

**Comment by RohitSingh107** [comment]
> above 10 without making the card look very bulky

I haven't said it should be enabled by default, I just said there should a option if anyone want it despite that bulky look.

**Comment by rickstaa** [comment]
> > above 10 without making the card look very bulky
> 
> I haven't said it should be enabled by default, I just said there should a option if anyone want it despite that bulky look.

I was aware of that. I meant that we can increase the max to `20` for the compact layout and keep it at `10` for the default layout. This way, our cards look clean by default (see https://github.com/anuraghazra/github-readme-stats#language-card-exclusive-options for more information about these layouts). Users that really want bigger cards still have the option to fork the repository and change the maximum as explained in https://github.com/anuraghazra/github-readme-stats/issues/1651#issuecomment-1265196187.

**Comment by rickstaa** [comment]
@qwerty541 I'm curious to know what you think about this feature request 😄?

**Comment by qwerty541** [comment]
> @qwerty541 I'm curious to know what you think about this feature request smile?

I think that the main thing is that the number of default languages should remain the same as it is now. I don't see any problems in giving users the opportunity to increase the number of languages through query options. If the card starts to look worse, it will already be the responsibility of the user.

**Comment by rickstaa** [comment]
> > @qwerty541 I'm curious to know what you think about this feature request smile?
> 
> I think that the main thing is that the number of default languages should remain the same as it is now. I don't see any problems in giving users the opportunity to increase the number of languages through query options. If the card starts to look worse, it will already be the responsibility of the user.

I agree. I just merged #2832 👍🏻.
