### ISSUE TITLE
Gradiant color

### ISSUE THREAD

**Issue by ShivaShirsath** [anuraghazra/github-readme-stats#1663]
gradiant color accepting only two colors

**add more color support as like preivius ( two or more )**

**Comment by ZawadiSumba66** [comment]
Hi @rickstaa I would like to take on this task. Could please expound more on it?

**Comment by rickstaa** [comment]
@ZawadiSumba66 Thanks for offering to work on this. This feature, however, is already possible with the current version of GRS. The following syntax should work.

```md 
![Anurag's GitHub stats](https://github-readme-stats.vercel.app/api?username=anuraghazra&count_private=true&bg_color=30,e96443,904e95,f0f,555)
```

![Anurag's GitHub stats](https://github-readme-stats.vercel.app/api?username=anuraghazra&count_private=true&bg_color=30,e96443,904e95,f0f,555)


Please check [the documentation](https://github.com/anuraghazra/github-readme-stats#gradient-in-bg_color).
