### ISSUE TITLE
Not showing `dart` in `Top Languages` card

### ISSUE THREAD

**Issue by NikhilCodes** [anuraghazra/github-readme-stats#167]
**Describe the bug**
The Top Language card doesn't count dart, C/C++ and java.

**Comment by TJMusiitwa** [comment]
Hope this is fixed soon. Most of my project repos are Flutter/Dart based projects

**Comment by anuraghazra** [comment]
@NikhilCodes Thanks for reporting the issue, We'll see what we can do to fix it, meanwhile see #136

**Comment by anuraghazra** [comment]
Should be fixed in #204
