### ISSUE TITLE
How do the PR stats work?

### ISSUE THREAD

**Issue by ionknowmyname** [anuraghazra/github-readme-stats#1687]
### Discussed in https://github.com/anuraghazra/github-readme-stats/discussions/1686

<div type='discussions-op-text'>

<sup>Originally posted by **ionknowmyname** March 28, 2022</sup>
I've made a couple of PR's that have been approved and merged, yet it keeps showing me 0 PR's for my github. And my commits aren't accurate. I've made more commits than what's showing there for this year</div>

**Comment by rickstaa** [comment]
Please don't cross post. I have answered your question in #1686.
