### ISSUE TITLE
Git stats report for an organization

### ISSUE THREAD

**Issue by Gopinath-MEST564** [anuraghazra/github-readme-stats#1690]
**Describe the bug**
How to use stats report for an organization

**Expected behavior**
I expect to use similar kind of dashboard presentation for my organization along with each member's activityt 

**Screenshots / Live demo link (paste the github-readme-stats link as markdown image)**

**Additional context**

**Comment by rickstaa** [comment]
@Gopinath-MEST564 Thanks for your feature request. This feature has already been requested and can be tracked on #654.
