### ISSUE TITLE
incorrect number of stars shown

### ISSUE THREAD

**Issue by Delta456** [anuraghazra/github-readme-stats#170]
**Describe the bug**
incorrect number of stars shown

![Swastik Baranwal's GitHub Stats](https://github-readme-stats.vercel.app/api?username=Delta456&show_icons=true)

**Expected behavior**

Show 626 stars as shown on my profile https://github.com/Delta456

**Comment by anuraghazra** [comment]
Hi @Delta456 Total Stars shows "How many stars you gained" and github shows  "How many repos you've starred"

**Comment by Delta456** [comment]
Oh it wasn't clear at all. I remember it was showing 600+ earlier.

**Comment by anuraghazra** [comment]
Duplicate of #69

**Comment by anuraghazra** [comment]
> Oh it wasn't clear at all. I remember it was showing 600+ earlier.

If you have gained 600 stars then it will show 600 stars.

**Comment by Delta456** [comment]
It was showing this earlier

![image](https://user-images.githubusercontent.com/28479139/88383041-56ff9d80-cdc7-11ea-867d-198b38559ada.png)

**Comment by anuraghazra** [comment]
Probably it was before the change when we filtered out owner repos, now it only counts repos which you own.

**Comment by Delta456** [comment]
Ok then. Thanks.

**Comment by anuraghazra** [comment]
@Delta456 check out https://github.com/anuraghazra/github-readme-stats/issues/39 for more info

**Comment by Delta456** [comment]
@anuraghazra ok 👍
