### ISSUE TITLE
not work for organizations

### ISSUE THREAD

**Issue by DWhirlpool** [anuraghazra/github-readme-stats#1700]
It does not work for organizations, it will display an error

**Comment by Ruzie** [comment]
It's ain't support organisation, you can read the information about usage, its only for GitHub user accounts.

**Comment by rickstaa** [comment]
@Ruzie Thanks a lot for jumping in on this one!

@DWhirlpool If you're talking about making a card that displays stats and language information for organisation accounts, @Ruzie is correct. We currently do not have this feature and do not have plans to add it in the short future. 

If you want to see the contributions you made to repositories that are contained in organisations,  there is a highly requested pull request open (see https://github.com/anuraghazra/github-readme-stats/issues/1#issuecomment-855681098).

I hope that helps. I will close this for now; please let us know if you have more questions.
