### ISSUE TITLE
Total commits is 0 when `include_all_commits=true`

### ISSUE THREAD

**Issue by MontejoJorge** [anuraghazra/github-readme-stats#1711]
**Describe the bug**
When `include_all_commits=true` the total commit count is 0, but when `include_all_commits=true"` works right.

**Expected behavior**
it is expected that using: `include_all_commits=true` without `"` at the end will display the total number of commits of the user.

**Screenshots / Live demo link (paste the github-readme-stats link as markdown image)**
![image](https://user-images.githubusercontent.com/56157795/164474636-e91c2a1b-fa20-4aec-9363-1fc20ab4404e.png)
![image](https://user-images.githubusercontent.com/56157795/164474705-ef47f7b6-eea9-42c1-b0e9-72aa9b459482.png)

**Comment by MontejoJorge** [comment]
Today it works fine, it seems to have been a temporary glitch.

**Comment by rickstaa** [comment]
@MontejoJorge Great to hear your problem is solved! The delay might be caused by the fact that we cache the cards to save some bandwidth (see https://github.com/anuraghazra/github-readme-stats#common-options).

**Comment by Iron-E** [comment]
I'm seeing a similar issue:

[Doesn't Work](https://github-readme-stats.vercel.app/api?username=Iron-E&count_private=true&include_all_commits=true&show_icons=true&theme=tokyonight) (shows 0 commits)

[Does Work](https://github-readme-stats.vercel.app/api?username=Iron-E&count_private=true&include_all_commits=true&include_all_commits=true&show_icons=true&theme=tokyonight) (shows thousands of commits)

Notice the only difference between the working and non-working links is that the working one has a duplicate `include_all_commits` field.

**Comment by rickstaa** [comment]
@Iron-E I checked your example and I was not able to reproduce the issue. Maybe again a cache issue.

```markdown
[![Iron-E's GitHub stats](https://github-readme-stats.vercel.app/api?username=Iron-E&count_private=true&include_all_commits=true&show_icons=true&theme=tokyonight)]
```

[![Iron-E's GitHub stats](https://github-readme-stats.vercel.app/api?username=Iron-E&count_private=true&include_all_commits=true&show_icons=true&theme=tokyonight)]

```markdown
[![Iron-E's GitHub stats](https://github-readme-stats.vercel.app/api?username=Iron-E&count_private=true&include_all_commits=true&show_icons=true&theme=tokyonight&include_all_commits=true)]
```

[![Iron-E's GitHub stats](https://github-readme-stats.vercel.app/api?username=Iron-E&count_private=true&include_all_commits=true&show_icons=true&theme=tokyonight&include_all_commits=true)]

**Comment by Iron-E** [comment]
Yup. Seems like it was a cache issue
