### ISSUE TITLE
Incorrect number of commits

### ISSUE THREAD

**Issue by novialriptide** [anuraghazra/github-readme-stats#1713]
**Describe the bug**
Incorrect number of commits

**Expected behavior**
The number of commits to be in the thousands.

**Screenshots / Live demo link
https://github-readme-stats.vercel.app/api?username=novialriptide&show_icons=true&include_all_commits=true&count_private=true
![image](https://user-images.githubusercontent.com/35881688/164738921-63f108a7-fb74-4de6-88c9-07efc6d5e933.png)

**Additional context**
Before, it read "1.9k commits", so I'm wondering where my other commits went? I did not change the README.md file at all when this happened.

**Comment by rjborba** [comment]
Probable duplicated
[1515](https://github.com/anuraghazra/github-readme-stats/issues/1515)

**Comment by novialriptide** [comment]
This seemed to have fixed itself..

**Comment by rjborba** [comment]
I still with the same issue.

https://github-readme-stats.vercel.app/api?username=rjborba&show_icons=true&include_all_commits=true&count_private=true

**Comment by rickstaa** [comment]
@rjborba Thanks for letting us know and bringing 1515 to our attention. We haven't had the time to look at it yet. Pull requests are welcome.

**Comment by Iron-E** [comment]
I'm seeing a similar issue:

[Doesn't Work](https://github-readme-stats.vercel.app/api?username=Iron-E&count_private=true&include_all_commits=true&show_icons=true&theme=tokyonight)

[Does Work](https://github-readme-stats.vercel.app/api?username=Iron-E&count_private=true&include_all_commits=true&include_all_commits=true&show_icons=true&theme=tokyonight)

Notice the only difference between the working and non-working links is that the working one has a duplicate `include_all_commits` field.
