### ISSUE TITLE
A streak view

### ISSUE THREAD

**Issue by probro27** [anuraghazra/github-readme-stats#1755]
**Is your feature request related to a problem? Please describe.**
I would prefer a feature that allows users to see their current streak and longest streak. That would really be able to showcase my skills.

**Describe the solution you'd like**
Something like this, 
    <img width="49.5%" src="https://github-readme-streak-stats.herokuapp.com/?user=probro27&theme=gruvbox&hide_border=true" />

**Comment by tejas-nagchandi** [comment]
Kindly have a look at https://github.com/DenverCoder1/github-readme-streak-stats

**Comment by rickstaa** [comment]
> Kindly have a look at https://github.com/DenverCoder1/github-readme-streak-stats

Great! I think we can close this issue. 🔥👍

**Comment by rickstaa** [comment]
@tejas-nagchandi great cards! If #1867 ever gets implemented, we can merge your cards and the GitHub readme cards under one organisation if you would be interested.

**Comment by tejas-nagchandi** [comment]
@rickstaa, I am not owner of the above card, @DenverCoder1 is!

**Comment by rickstaa** [comment]
@tejas-nagchandi ha, I overlooked that. Anyway, thanks for bringing it to our attention.
