### ISSUE TITLE
Server is down?

### ISSUE THREAD

**Issue by gzzyyxh** [anuraghazra/github-readme-stats#1757]
Today  my stat card is not visible with an error:
Please add an env variable called PAT_1 with your Github token in vercel
So, what can I do?

**Comment by ww8007** [comment]
I have the same issue

**Comment by Leoooo333** [comment]
Same with you.

**Comment by jeff082chen** [comment]
same

**Comment by Arslanoov** [comment]
Same

**Comment by SuperBruceJia** [comment]
+1

**Comment by SuperBruceJia** [comment]
> Today my stat card is not visible with an error: Please add an env variable called PAT_1 with your Github token in vercel So, what can I do?

Any solution?

**Comment by manojuppala** [comment]
+1

**Comment by gzzyyxh** [comment]
> 

Confused, I was looking around for a solution, but after a while he returned to normal.

**Comment by gzzyyxh** [comment]
> > Today my stat card is not visible with an error: Please add an env variable called PAT_1 with your Github token in vercel So, what can I do?
> 
> Any solution?

**Comment by anuraghazra** [comment]
No need to comment `+1`, `same here` every time. I'm just getting bombarded with notification. 

You can [deploy on your own vercel ](https://github.com/anuraghazra/github-readme-stats#deploy-on-your-own-vercel-instance)instance in the meanwhile to fix the issue.  

Duplicate of #1471

**Comment by gzzyyxh** [comment]
> > Today my stat card is not visible with an error: Please add an env variable called PAT_1 with your Github token in vercel So, what can I do?
> 
> Any solution?
Confused, I was looking around for a solution, but after a while he returned to normal

**Comment by manojuppala** [comment]
> No need to comment `+1`, `same here` every time. I'm just getting bombarded with notification.
> 
> You can [deploy on your own vercel ](https://github.com/anuraghazra/github-readme-stats#deploy-on-your-own-vercel-instance)instance in the meanwhile to fix the issue.
> 
> Duplicate of #1471

@anuraghazra i am using my own vercel deployment. but still facing the issue.

**Comment by rickstaa** [comment]
@manojuppala I checked forked and checked your profile and the cards seem to be working. I think caching issues caused your problem.
