### ISSUE TITLE
Improve caching documentation

### ISSUE THREAD

**Issue by rickstaa** [anuraghazra/github-readme-stats#1760]
**Is your feature request related to a problem? Please describe.**

I noticed many problems people have in issues and discussions are caused by the fact that they are not aware that we use caching to reduce the server load.

**Describe the solution you'd like**

 Although this is explained in the README, it is placed under the gradient section (See https://github.com/anuraghazra/github-readme-stats#gradient-in-bg_color). Let's add a separate area to describe the caching behaviour.

**Comment by coderboy-exe** [comment]
I'm Interested in tackling this. Can you assign to me?

Thanks

**Comment by rickstaa** [comment]
@coderboy-exe Thanks for your interest in contributing to GRS. 🚀 I assigned you to this issue. Tale your time. Let me know if you have any questions, and feel free to request a review from me at the PR.

**Comment by coderboy-exe** [comment]
Awesome! I'll keep in touch

**Comment by muhib7353** [comment]
Well,I think you can do @coderboy-exe

**Comment by rickstaa** [comment]
@coderboy-exe Are you still working on this issue, or can others take it on for their Hacktoberfest?

**Comment by rickstaa** [comment]
Implemented in d7451d8288d700d9695689a8d2a3076994e29d22.
