### ISSUE TITLE
How to hide contributions on stat card?

### ISSUE THREAD

**Issue by nico-i** [anuraghazra/github-readme-stats#1767]
### Discussed in https://github.com/anuraghazra/github-readme-stats/discussions/1210

<div type='discussions-op-text'>

<sup>Originally posted by **toharifqi** July 27, 2021</sup>
Would it be possible to link to the [mentioned section](https://github.com/anuraghazra/github-readme-stats#hiding-individual-stats) in the [Stats Card Exclusive Options](https://github.com/anuraghazra/github-readme-stats#stats-card-exclusive-options) section? That is at least where I would expect the input values of a URL param to be, namely aside of the corresponding query paramater. 😁</div>

**Comment by rickstaa** [comment]
@nico-i Thanks again for your contribution!
