### ISSUE TITLE
Issue in vercel

### ISSUE THREAD

**Issue by camipozas** [anuraghazra/github-readme-stats#1769]
**Describe the bug**
Vercel is down, I can't see my statistics or my top lang.

**Expected behavior**
If I'm not mistaken yesterday everything was ok, today I go to check my readme and I find it down, I thought it was me but it's global.

**Screenshots / Live demo link (paste the github-readme-stats link as markdown image)**
<img width="495" alt="image" src="https://user-images.githubusercontent.com/89259499/169097149-d4f921c8-038e-4c2c-a604-13b90b201e6b.png">

**Comment by Sarabhian** [comment]
what can be done here ?

**Comment by camipozas** [comment]
Sorry I only explain the issue. I don't know the solution..sorry

**Comment by Sarabhian** [comment]
ok :) let me tell you the solution then ..ha ha..
solution is **Deploy on your own Vercel instance**
I am pasting a link you just have to go there and authenticate your vercel api using your own github authentication and its done.

[Deploy](https://vercel.com/new/clone?repository-url=https%3A%2F%2Fgithub.com%2Fanuraghazra%2Fgithub-readme-stats)
click on deploy and authenticate using your own account and it's done .. 
tell me if iit resolves your issue...

**Comment by rickstaa** [comment]
@Sarabhian Thanks a lot for jumping in on this issue! 

This is a known problem that is affecting all users of the public Vercel instance (see https://github.com/anuraghazra/github-readme-stats/issues/1763 and https://github.com/anuraghazra/github-readme-stats/issues/1471). For people who experience this problem, please wait until we fix this issue upstream or as mentioned in https://github.com/anuraghazra/github-readme-stats/issues/1471 deploy your own Vercel instance.
