### ISSUE TITLE
This page contains the following errors

### ISSUE THREAD

**Issue by zendy199x** [anuraghazra/github-readme-stats#177]
**Describe the bug**
This page contains the following errors:
error on line 88 at column 42: PCDATA invalid Char value 8
Below is a rendering of the page up to the first error.

https://github-readme-stats.vercel.app/api?username=zendy199x&theme=merko&show_icons=true

**Expected behavior**
![Screen Shot 2020-07-25 at 00 36 37](https://user-images.githubusercontent.com/50132805/88419187-e9775f80-ce0e-11ea-9476-ab408589736e.png)

**Screenshots / Live demo link (paste the github-readme-stats link as markdown image)**

**Additional context**

**Comment by anuraghazra** [comment]
@zendy199x Thanks for opening the issue, I'll investigate the issue ASAP.

**Comment by anuraghazra** [comment]
Okay i think your name is causing the issue, try `&hide_title=true` and it should work fine, i'm working on a fix.

**Comment by anuraghazra** [comment]
Hi @zendy199x This should be fixed now, thanks for reporting :D

**Comment by anuraghazra** [comment]
![](https://github-readme-stats.vercel.app/api?username=zendy199x)
