### ISSUE TITLE
New tiny error url does not fit on card

### ISSUE THREAD

**Issue by rickstaa** [anuraghazra/github-readme-stats#1774]
**Describe the bug**

It looks like the new tiny URL that was introduced in 2fb452c119e9cb4706a1ecf708295db9b77b4b7e that is shown when an error is thrown does not fit on the card. Not a pressing issue but just putting this here so that we don't forget.

![image](https://user-images.githubusercontent.com/17570430/169273808-75921d34-9432-466b-905b-deb6f45c8413.png)

**Comment by Crazypersonalph** [comment]
Same here

**Comment by DrkTheDon** [comment]
bug happening to me too

**Comment by zhaifanhua** [comment]
Yes, and it's serious! So is mine.

**Comment by rickstaa** [comment]
This issue is only relating the *design* of the card when error messages are shown. This is the reason I state that it is not pressing. I added this issue I want to fix in the future. I however understand the confusion. I will lock this issue for now. 🤔 

The reason for the `maximum retries exceeded` error can be found in [Common Error Codes](https://github.com/anuraghazra/github-readme-stats/issues/1772). The status of this error is tracked in #1471.

**Comment by rickstaa** [comment]
If somebody wants to contribute, I think the best way is to enlarge the card a bit if an error is thrown.
