### ISSUE TITLE
null for name AymanArif

### ISSUE THREAD

**Issue by AymanArif** [anuraghazra/github-readme-stats#18]
I am using Github Stats in this form:

```
![Ayman's GitHub stats](https://github-readme-stats.vercel.app/api?username=aymanarif&hide=["stars","prs"])
```

**Output:** 

![null](https://user-images.githubusercontent.com/13992816/87161498-3d982500-c2e2-11ea-8d87-31ea85fc6a88.png)
)

I think it could be because my name is in Camel-Case.

Appreciate any help. :smiley:

**Comment by anuraghazra** [comment]
Well, i think you don't have a name
![noname](https://user-images.githubusercontent.com/35374649/87163460-05461600-c2e5-11ea-81b5-1b93a0085313.PNG)

Github API is returning null also.
![noname-gql](https://user-images.githubusercontent.com/35374649/87163491-142cc880-c2e5-11ea-82a2-bc6963c6947a.PNG)

**Comment by AymanArif** [comment]
Hi @anuraghazra.
Is there onboarding to Github's GraphQL API? If so, can you share link to the documentation?

**Comment by nombrekeff** [comment]
@AymanArif It seems like you only have your username set. 

Maybe we could add an option where the user specifies if he wants the username or name to be rendered?

**Comment by anuraghazra** [comment]
> Hi @anuraghazra.
> Is there onboarding to Github's GraphQL API? If so, can you share link to the documentation?

Do you mean any learning resources? well you don't need any documentation links because graphql is self documenting try it out https://developer.github.com/v4/explorer/

https://graphql.github.io/

**Comment by anuraghazra** [comment]
> @AymanArif It seems like you only have your username set.
> 
> Maybe we could add an option where the user specifies if he wants the username or name to be rendered?

Hmm yes that could be an option

**Comment by anuraghazra** [comment]
Looks like it worked @AymanArif 

![Ayman's GitHub stats](https://github-readme-stats.vercel.app/api?username=aymanarif&hide=["stars","prs"])

**Comment by AymanArif** [comment]
Silly from my part. There was no username in GitHub settings. 😂

Anyway, thanks for replying swiftly.
