### ISSUE TITLE
Support for Stackoverflow stats

### ISSUE THREAD

**Issue by kshtj24** [anuraghazra/github-readme-stats#1806]
**Is your feature request related to a problem? Please describe.**
It would be good to have a Stackoverflow stats card.

**Describe the solution you'd like**
Create a stackoverflow stats card which includes the reputation, number of gold, silver and bronze badges achieved by the user and user impact.
![image](https://user-images.githubusercontent.com/16714838/172593633-ab49526d-2d93-49e1-a570-888590acd3f7.png)

**Comment by kurt-liao** [comment]
I think this idea is interesting, so I create a [repository](https://github.com/kurt-liao/so-stats) to do it.

The project is in the very beginning, and also I'm not that good about coding. 
So, just feel free to give me some feedback to make me getting better. 
Thanks!

**Comment by tejas-nagchandi** [comment]
Kindly have a look at https://github.com/nschloe/stackoverflow-card

**Comment by rickstaa** [comment]
Amazing! Will close it it here for now.
