### ISSUE TITLE
Transparent card of stats

### ISSUE THREAD

**Issue by mjovanc** [anuraghazra/github-readme-stats#1807]
**Is your feature request related to a problem? Please describe.**
The card does not work well when switching by light/dark mode. 

**Describe the solution you'd like**
Would like to have a transparent card of stats with black/white text that adjusts based on current GitHub theme (if possible).

**Describe alternatives you've considered**
Nothing to add here.

**Additional context**
No screenshots or material to share.

**Comment by rickstaa** [comment]
@mjovanc Thanks for your feature request. Some PR is open to achieving the desired behaviour (see #1785 & #1010). We, however, did not yet find the time to look at them. You can already use them on your fork and provide feedback to these PRs.

**Comment by rickstaa** [comment]
@mjovanc You can also use the solutions provided in #1415. An example of a dynamic card can be seen on [my profile](https://github.com/rickstaa).

**Comment by mjovanc** [comment]
Sweet. Thanks @rickstaa !

**Comment by rickstaa** [comment]
No problem. I think we can keep this open as a feature request for tracking https://github.com/anuraghazra/github-readme-stats/pull/1785 & https://github.com/anuraghazra/github-readme-stats/pull/1010. Feel free to unsubscribe if my previous commentx already are what you had in mind.

**Comment by rickstaa** [comment]
We can also add the `bg_color=00000000` property to the card tag to make it transparent.

_Originally posted by @HaiderSultanArc in https://github.com/anuraghazra/github-readme-stats/issues/1981#issuecomment-1229209505_

**Comment by jsolly** [comment]
@rickstaa You are the MAN! This works beautifully!

**Comment by rickstaa** [comment]
This feature was implemented in 406dbc5656ea8e12ff224967cd7ebacc5f0d8729.
