### ISSUE TITLE
Total Commits in GitHub Stats are decreasing

### ISSUE THREAD

**Issue by hashfx** [anuraghazra/github-readme-stats#1814]
**Describe the bug**
Number of total commits in GitHub Stats are decreasing day by day (8.7K to 8.6K to 8K to 7.8K...)

**Expected behaviour**
Total Commits should be equal to addition of all commits throughout the GitHub history (My Total Contributions are about 8.6K).

**Screenshots / Live demo link (paste the github-readme-stats link as markdown image)**
_What is Shown_
![image](https://user-images.githubusercontent.com/69109482/173346485-7f263c6b-4867-4be4-b4fc-6a84d6928a88.png)

_Total Contribution in 2022_
![image](https://user-images.githubusercontent.com/69109482/173346777-1890a849-1570-49aa-bde2-23ecc90cc064.png)

_Total Contribution in 2021_
![image](https://user-images.githubusercontent.com/69109482/173346668-bcbea83b-384f-472c-994d-33286fbacbc6.png)

_Total Contributions throughout the GitHub_
![image](https://user-images.githubusercontent.com/69109482/173347033-f0e4ab4c-578a-4068-b52a-78d4f2322a2c.png)

**Additional context**
Stats should show all Contributions and not of current year, would appreciate parameter command, if any.

**Comment by rickstaa** [comment]
@hashfx Thanks for your bug report. I think the distinction between contributions and commits causes this. Please check https://github.com/anuraghazra/github-readme-stats/discussions/1770#number-of-commits-is-incorrect about the difference. I check the data we receive from GitHub, and it looks like the card is correct. You can test this out by running the following code in the GraphQL API:

```graphql
query userInfo($login: String!) {
  user(login: $login) {
    name
    login
    contributionsCollection {
      totalCommitContributions
      restrictedContributionsCount
    }
    repositoriesContributedTo(
      first: 1
      contributionTypes: [COMMIT, ISSUE, PULL_REQUEST, REPOSITORY]
    ) {
      totalCount
    }
    pullRequests(first: 1) {
      totalCount
    }
    openIssues: issues(states: OPEN) {
      totalCount
    }
    closedIssues: issues(states: CLOSED) {
      totalCount
    }
    followers {
      totalCount
    }
    repositories(
      first: 100
      ownerAffiliations: OWNER
      orderBy: {direction: DESC, field: STARGAZERS}
    ) {
      totalCount
      nodes {
        stargazers {
          totalCount
        }
      }
    }
  }
}
```

With variables:

```graphql
{"login": "hashfx"}
```

This gives me 7.8k commits for your account.

**Comment by hashfx** [comment]
> @hashfx Thanks for your bug report. I think the distinction between contributions and commits causes this. Please check [#1770 (comment)](https://github.com/anuraghazra/github-readme-stats/discussions/1770#number-of-commits-is-incorrect) about the difference. I check the data we receive from GitHub, and it looks like the card is correct. You can test this out by running the following code in the GraphQL API:
> 
> ```graphql
> query userInfo($login: String!) {
>   user(login: $login) {
>     name
>     login
>     contributionsCollection {
>       totalCommitContributions
>       restrictedContributionsCount
>     }
>     repositoriesContributedTo(
>       first: 1
>       contributionTypes: [COMMIT, ISSUE, PULL_REQUEST, REPOSITORY]
>     ) {
>       totalCount
>     }
>     pullRequests(first: 1) {
>       totalCount
>     }
>     openIssues: issues(states: OPEN) {
>       totalCount
>     }
>     closedIssues: issues(states: CLOSED) {
>       totalCount
>     }
>     followers {
>       totalCount
>     }
>     repositories(
>       first: 100
>       ownerAffiliations: OWNER
>       orderBy: {direction: DESC, field: STARGAZERS}
>     ) {
>       totalCount
>       nodes {
>         stargazers {
>           totalCount
>         }
>       }
>     }
>   }
> }
> ```
> 
> With variables:
> 
> ```graphql
> {"login": "hashfx"}
> ```
> 
> This gives me 7.8k commits for your account.

I understood the issue, thanks @rickstaa for replying😀

**Comment by rickstaa** [comment]
No problem. Feel free to comment below if you have any other questions.

**Comment by hashfx** [comment]
> No problem. Feel free to comment below if you have any other questions.

Sure, thanks😇🙏🏻
