### ISSUE TITLE
GitHub Stats should display total stats instead of current year stats

### ISSUE THREAD

**Issue by hashfx** [anuraghazra/github-readme-stats#1815]
**Is your feature request related to a problem? Please describe.**
My GitHub stats are decreasing day by day vide issue #1814 

**Describe the solution you'd like**
_What is Shown_
![image](https://user-images.githubusercontent.com/69109482/173346485-7f263c6b-4867-4be4-b4fc-6a84d6928a88.png)

_Total Contribution in 2022_
![image](https://user-images.githubusercontent.com/69109482/173346777-1890a849-1570-49aa-bde2-23ecc90cc064.png)

_Total Contribution in 2021_
![image](https://user-images.githubusercontent.com/69109482/173346668-bcbea83b-384f-472c-994d-33286fbacbc6.png)

_Total Contributions throughout the GitHub_
![image](https://user-images.githubusercontent.com/69109482/173347033-f0e4ab4c-578a-4068-b52a-78d4f2322a2c.png)

**Describe alternatives you've considered**
Total Stats must be displayed or should have an option to choose between year-wise, current year or total

**Additional context**
Issue Opened as bug #1814

**Comment by rickstaa** [comment]
@hashfx Thanks for your bug report/feature request. I agree that our current behaviour is misleading or strange at best. There is a feature request open for changing this on #1053. Sadly, we haven't had time yet to address this issue. Feel free to discuss the implementation of this feature request or add a pull request to solve this issue.

**Comment by hashfx** [comment]
> @hashfx Thanks for your bug report/feature request. I agree that our current behaviour is misleading or strange at best. There is a feature request open for changing this on #1053. Sadly, we haven't had time yet to address this issue. Feel free to discuss the implementation of this feature request or add a pull request to solve this issue.

Thanks for your action, I would surely be planning for a solution
