### ISSUE TITLE
Bug Report: Pin Card displays too short description

### ISSUE THREAD

**Issue by HaaLeo** [anuraghazra/github-readme-stats#184]
**Describe the bug**
When generating a pin card for a repository with a very long repository description like for the [HaaLeo/swarmlib](https://www.github.com/HaaLeo/swarmlib) repository, the description of the repository is truncated after a single line instead of three

**Expected behavior**
The repository description is truncated after three lines. The screenshot shows GitHub's original pin card.
<img width="461" alt="image" src="https://user-images.githubusercontent.com/23164374/88454386-9f729600-ce6f-11ea-9e85-da316fb3ac39.png">

**Actual behavior**
Below is the actual generated pin card via `github-readme-stats`
[![ReadMe Card](https://github-readme-stats.vercel.app/api/pin/?username=HaaLeo&repo=swarmlib&theme=prussian)](https://github.com/anuraghazra/github-readme-stats)

**Comment by HaaLeo** [comment]
Just found #94 which also mentions the single line text.

**Comment by xiaoyu2006** [comment]
That's the default behavior I think. @ HaaLeo

**Comment by anuraghazra** [comment]
@HaaLeo Thanks for reporting the issue, we are currently looking at this on #94 and trying to figure out the best way to handle the auto resizing of height and multiple lines in SVG, it's doable of course but kinda messy. So we are trying to figure out a best approach.

**Comment by anuraghazra** [comment]
This should be fixed now let's check

![](https://github-readme-stats.vercel.app/api/pin/?username=HaaLeo&repo=swarmlib)
