### ISSUE TITLE
Add repository stats card

### ISSUE THREAD

**Issue by rickstaa** [anuraghazra/github-readme-stats#1866]
**Is your feature request related to a problem? Please describe.**
Add the number of open issues and PRs to repo card.

**Comment by thevinitgupta** [comment]
I would like to work on this

**Comment by rickstaa** [comment]
Great! I assigned you to this issue 🚀.

**Comment by thevinitgupta** [comment]
Thanks @rickstaa

**Comment by thevinitgupta** [comment]
I am not able to install vercel to test.
Is there any other way than mentioned in the Contributing.md file?

**Comment by rickstaa** [comment]
@thevinitgupta What error are you getting? The `npm i -g vercel` command should work. Please note that I broke the test yesterday to prevent our PATs from emptying. You can commit using the `--no-verify` flag.

**Comment by thevinitgupta** [comment]
Actually after running the above command, I am still getting
```sh
 vercel:command not found
```

**Comment by rickstaa** [comment]
@thevinitgupta I think https://github.com/vercel/vercel/discussions/5019 will solve your issue. On second thought, however, I think adding these values to the (repo) pin card might not be desired. 😅 @anuraghazra created this card to allow users to add extra pins to their readme since GitHub only will enable users to pin six repositories. I, therefore, think it is best to keep the pin card as close as possible to GitHub's repo pins. 🤔

![image](https://user-images.githubusercontent.com/17570430/194642854-25db04ce-5248-4093-bfae-54c9c3ab9067.png)

Maybe in the future, if there is enough interest from the community, we can add a repository-specific card like is explained in #2141.
