### ISSUE TITLE
Add CONTRIBUTING.md

### ISSUE THREAD

**Issue by yashguptaz** [anuraghazra/github-readme-stats#187]
It can be a bad experince as a beginner exploring the repo when the repo doesn't have a `CONTRIBUTING.md`
Add a `CONTRIBUTING.md` file to at least the root of the repo, and if possible then even in `/themes/`, this will ensure that even newbies are able to contribute properly.

**Comment by yashguptaz** [comment]
Closing as a PR is already opened
See #121

**Comment by anuraghazra** [comment]
@yashguptaz thanks for opening the issue, i'll add it.
