### ISSUE TITLE
Github readme stats not able to update the streaks record

### ISSUE THREAD

**Issue by prathikshetty2002** [anuraghazra/github-readme-stats#1871]
**Describe the bug**
I have been consistently working on github from last 15 days my current streak was 13 till 2 days ago. Now it is only 2 but i didn;t break it. The readme stats is not showing the streak record properly. 

**Expected behaviour**
The current streak should be of 15 days but is instead of 2 days

![Screenshot 2022-07-19 010816](https://user-images.githubusercontent.com/63772910/179603568-b8b12278-4f18-44f2-9884-84cbbc5b8243.png)

**Screenshots / Live demo link (paste the github-readme-stats link as markdown image)**

![Screenshot 2022-07-19 005827](https://user-images.githubusercontent.com/63772910/179602695-9c533f5f-cd66-48cb-bc88-381bf8b84e82.png)

I have private contributions enabled and also have read the existing contribution guidelines of readme stats card.

**Comment by rickstaa** [comment]
Hey @prathikshetty2002 thanks for your questions. If I'm not mistaken, however this issue should be at https://github.com/DenverCoder1/github-readme-streak-stats

**Comment by prathikshetty2002** [comment]
> Hey @prathikshetty2002 thanks for your questions. If I'm not mistaken, however this issue should be at https://github.com/DenverCoder1/github-readme-streak-stats

ok thanks for letting me know, i will close this and raise a new issue there.

**Comment by codewithastro** [comment]
guys it's not showing the streak card what should I do I tried to fork it and see what the problem but it seems like a bug

**Comment by qwerty541** [comment]
> guys, it's not showing the streak card what should I do I tried to fork it and see what the problem but it seems like a bug

@codewithastro This repository does not provide streak stats card, if you have some problems with it you can open an issue or discussion there https://github.com/DenverCoder1/github-readme-streak-stats. By the way streak card in your profile currently works well.

**Comment by ashiqYousuf** [comment]
I have observed the same issue! This is so irritating, when I open my  github account in incognito mode (or some different user visits my github account) the github streak is 2, but when I navigate to my github profile (from the same google account linked with github) it shows other value (8).

**Comment by devLucenaPinheiro** [comment]
> I have observed the same issue! This is so irritating, when I open my github account in incognito mode (or some different user visits my github account) the github streak is 2, but when I navigate to my github profile (from the same google account linked with github) it shows other value (8).

Same error here, even the same number (8)

**Comment by qwerty541** [comment]
@ashiqYousuf @devLucenaPinheiro here is a comment about your problem from streak stats card creator: https://github.com/DenverCoder1/github-readme-streak-stats/issues/288#issuecomment-1200029137. Hope this will help to resolve your problem.
