### ISSUE TITLE
Stats for an organization

### ISSUE THREAD

**Issue by mendax1234** [anuraghazra/github-readme-stats#1881]
**Is your feature request related to a problem? Please describe.**

l want the organization on GitHub can have a stats.

**Describe the solution you'd like**

l want the organization on GitHub can have a stats.

**Describe alternatives you've considered**

Not yet.

**Additional context**

**Comment by rickstaa** [comment]
Duplicate of #1.

**Comment by mendax1234** [comment]
> Duplicate of #1.

Thanks! l will close this issue!
