### ISSUE TITLE
Steam card

### ISSUE THREAD

**Issue by ZhiyuanChen** [anuraghazra/github-readme-stats#1893]
**Is your feature request related to a problem? Feature 

Is it possible to have a Steam stats like https://github.com/Ananto30/steam-stat ?

**Comment by rickstaa** [comment]
@ZhiyuanChen Adding a steam card is currently not under the scope of this repository (see https://github.com/anuraghazra/github-readme-stats/issues/1563#issuecomment-1137509321). We might be able to add in the future if this repository is converted into an organization (see https://github.com/anuraghazra/github-readme-stats/issues/1867).
