### ISSUE TITLE
Top Languages Card not hiding C++

### ISSUE THREAD

**Issue by thisispratt** [anuraghazra/github-readme-stats#194]
### Description
The top languages card is unable to hide the C++ language.
I tried it both ways: 
1. PHP was hidden but c++ was not.
https://github-readme-stats.vercel.app/api/top-langs/?username=thisispratt&hide=c++,php

![image](https://user-images.githubusercontent.com/40731031/88471788-ac07f480-cf2a-11ea-90fb-8db7b5a9bd48.png)

2. https://github-readme-stats.vercel.app/api/top-langs/?username=thisispratt&hide=["PHP","C++"]

![image](https://user-images.githubusercontent.com/40731031/88471855-4f590980-cf2b-11ea-878a-e99c5cc376bb.png)

### Expected behavior
C++ should be hidden with the <code>&hide=c++</code> or <code>&hide=cpp</code>

**Comment by terror** [comment]
It is because we currently don't encode the symbols for you in the URL query. 

Try this query: https://github-readme-stats.vercel.app/api/top-langs/?username=thisispratt&hide=c%2B%2B,php

**Comment by thisispratt** [comment]
> It is because we currently don't encode the symbols for you in the URL query.
> 
> Try this query: https://github-readme-stats.vercel.app/api/top-langs/?username=thisispratt&hide=c%2B%2B,php

Thanks! it works fine.
Can you please explain what this 2B does?

**Comment by terror** [comment]
Some characters in URLs have special roles, so you if you're not using them for their specific role you have to encode them. %2B is the encoded version of "+".

See https://en.wikipedia.org/wiki/Percent-encoding for further reference

**Comment by anuraghazra** [comment]
Hi @thisispratt i hope you get your answer :) closing this now.
