### ISSUE TITLE
Language card card width should not allow cards smaller than the title

### ISSUE THREAD

**Issue by rickstaa** [anuraghazra/github-readme-stats#1945]
**Is your feature request related to a problem? Please describe.**

The language card layout breaks when the card_width is set to low

**Card_width 250**

[![Top Langs](https://github-readme-stats.vercel.app/api/top-langs/?username=anuraghazra&card_width=250&langs_count=10)](https://github.com/anuraghazra/github-readme-stats)

```md
[![Top Langs](https://github-readme-stats.vercel.app/api/top-langs/?username=anuraghazra&card_width=250&langs_count=10)](https://github.com/anuraghazra/github-readme-stats)
```

**Card_width 200**

[![Top Langs](https://github-readme-stats.vercel.app/api/top-langs/?username=anuraghazra&card_width=200&langs_count=10)](https://github.com/anuraghazra/github-readme-stats)

```md
[![Top Langs](https://github-readme-stats.vercel.app/api/top-langs/?username=anuraghazra&card_width=200&langs_count=10)](https://github.com/anuraghazra/github-readme-stats)
```

**Describe the solution you'd like**

We should implement a minimum card width like was done in https://github.com/anuraghazra/github-readme-stats/pull/1334.

**Comment by qimolin** [comment]
@rickstaa the commit that implements this issue is merged. Shouldn't this issue be closed?

**Comment by rickstaa** [comment]
Your right! Thanks a lot for your contribution. 🎉 It is contributors like you that make this project so great 🚀!
