### ISSUE TITLE
Create empty issues check github action

### ISSUE THREAD

**Issue by rickstaa** [anuraghazra/github-readme-stats#1950]
**Is your feature request related to a problem? Please describe.**

Several people create a bug or feature request while only changing the title (see #1947). This makes it very hard to understand what these issues are about.

**Describe the solution you'd like**

I think we could add a simple GitHub action that closes and re-opens these issues based on whether the user did modify the issues template.

**Comment by PrashubhAtri** [comment]
Hi @rickstaa I would like to take this issue

**Comment by rickstaa** [comment]
@PrashubhAtri Great to hear that you want to contribute! I assigned you to the issue.

**Comment by rickstaa** [comment]
@PrashubhAtri, I just remembered that I worked on a similar action for another private repository some time ago. I changed it to be more in line with what we are trying to do here and added some tests and documentation. You can check it out [here](https://github.com/rickstaa/empty-issues-closer-action). Let me know what you think. I think we can directly use the recipe in this repository. Feel free to create a pull request. Sorry if you already started working on this issue. :sweat:

**Comment by rickstaa** [comment]
@PrashubhAtri I implemented this in #2004 while adding you as a co-author.
