### ISSUE TITLE
[REQUEST] Add catppuccin theme

### ISSUE THREAD

**Issue by CloudyWhale** [anuraghazra/github-readme-stats#1977]
**Is your feature request related to a problem? Please describe.**
No, I just want a different colorscheme

**Describe the solution you'd like**
Add a catppuccin theme style based off the catppuccin mocha colorscheme. You can view it <a href="https://github.com/catppuccin/palette/blob/main/png/catppuccin-mocha.png">here</a>

**Describe alternatives you've considered**

**Additional context**
I really love the catppuccin color scheme and I wish I could get this widget in the catppuccin colorscheme

**Comment by rickstaa** [comment]
@CloudyWhale Thanks for your feature request. There was a pull request open that implemented this theme (see #1568). It, however, was closed since https://github.com/catppuccin/github-readme-stats was created. Are you okay with using https://github.com/catppuccin/github-readme-stats, or would you like me to reopen that pull request? I can, however, not give a promise it will get merged soon.

**Comment by rickstaa** [comment]
#1568 Has been deleted, so it can not be reopened. Feel free to create a new pull request if you, instead of https://github.com/catppuccin/github-readme-stats want this theme in the RGS themes. I will close this issue for now.

**Comment by CloudyWhale** [comment]
> @CloudyWhale Thanks for your feature request. There was a pull request open that implemented this theme (see #1568). It, however, was closed since https://github.com/catppuccin/github-readme-stats was created. Are you okay with using https://github.com/catppuccin/github-readme-stats? I can also re-open that pull request but can not give a promise when it is merged.

Yes, I am fine using the catppuccin version. I did not know that existed

**Comment by cosmojg** [comment]
> #1568 Has been deleted, so it can not be reopened. Feel free to create a new pull request if you, instead of https://github.com/catppuccin/github-readme-stats want this theme in the RGS themes. I will close this issue for now.

@rickstaa I'm taking you up on that offer!
