### ISSUE TITLE
I can't comment the locked created discussion

### ISSUE THREAD

**Issue by APN-Pucky** [anuraghazra/github-readme-stats#1984]
### Discussed in https://github.com/anuraghazra/github-readme-stats/discussions/1968

@rickstaa 
I edited my issue/discussion, but it is locked so I can't comment, but only edit my texts:
I realized that this issues might just be due to some caching from Github.

This issue can be deleted/closed, but I wanted to notify you about this for future issues->discussion.

**Comment by rickstaa** [comment]
> ### Discussed in #1968
> @rickstaa I edited my issue/discussion, but it is locked so I can't comment, but only edit my texts: I realized that this issues might just be due to some caching from Github.
> 
> This issue can be deleted/closed, but I wanted to notify you about this for future issues->discussion.
