### ISSUE TITLE
missing env variable PAT_1

### ISSUE THREAD

**Issue by AntonyOnScript** [anuraghazra/github-readme-stats#1986]
**Describe the bug**
look at that below, it was happening on my profile README:
![image](https://user-images.githubusercontent.com/62514607/187503587-a379176d-9cc8-4d53-82bb-d5afe9f715bb.png)

**Comment by gouravkhunger** [comment]
Same issue, @anuraghazra I think it's [time to increase tokens](https://github.com/anuraghazra/github-readme-stats/issues/58#issuecomment-728797939) 😄

**Comment by gouravkhunger** [comment]
@AntonyOnScript Or you could [deploy the api yourself](https://github.com/anuraghazra/github-readme-stats#deploy-on-your-own-vercel-instance)

**Comment by MichelZero** [comment]
> **Describe the bug** look at that below, it was happening on my profile README: ![image](https://user-images.githubusercontent.com/62514607/187503587-a379176d-9cc8-4d53-82bb-d5afe9f715bb.png)

Same issue,

**Comment by Jewgah** [comment]
same issue over here

**Comment by Sam44323** [comment]
Yeps, just encountered this same thing 😅 @anuraghazra

**Comment by augustoaraujoo** [comment]
i have this error too

**Comment by Barry-Flynn** [comment]
`Please add an env variable called PAT_1 with github tocken in vercel.`

Same problem, what is the reason? How to solve it, does anyone know? thanks.

**Comment by Barry-Flynn** [comment]
The problem has been resolved, and it has now returned to normal display.

**Comment by gouravkhunger** [comment]
Ah yes @Barry-Flynn, I suppose the hourly rate limit from GitHub was reset as it's been time. Still, @anuraghazra I think the number of stored PATs should be increased because the project has grown so much and these rate limit errors would occur more often.

**Comment by rickstaa** [comment]
@AntonyOnScript, thanks for letting us know. Closed since this is a duplicate of #1471.
