### ISSUE TITLE
Update Vercel Deploy documentation

### ISSUE THREAD

**Issue by rickstaa** [anuraghazra/github-readme-stats#1990]
**Describe the bug**
As pointed out by @noraj in https://github.com/anuraghazra/github-readme-stats/issues/1471#issuecomment-1232677597 the guide on deploying your own Vercel instance is no longer up to date. 

> > @noraj You are correct the video was done before we needed to increase the `maxDuration` parameter. Thanks for elaborating on that point! 👍🏻 However, we updated the text guide some time ago to include the `maxDuration` step (see step 6). Do you think the documentation can still be improved?
> 
> Yeah, for example there is no longer an import button on the dashboard but that instead 👍🏻
> 
> ![image](https://user-images.githubusercontent.com/16578570/187642129-4a26d2a7-bd00-4817-bc37-492d66686c74.png)
> 
> old import button
> 
> ![image](https://user-images.githubusercontent.com/16578570/187641860-44428c2c-5515-48f9-8201-172aee739a6f.png)
> 
> this is what you got on new project creation now (looking on you organization / namespace repository or a small link to import git repo external to your oAuth app)
> 
> ![image](https://user-images.githubusercontent.com/16578570/187641924-1252f446-c208-430e-bef4-cfa620a09fcf.png)
> 
> old import form
> 
> ![](https://camo.githubusercontent.com/a30b3cd359d366c62498360f5f7c7eb2b679fe31a063982d44876f11b7e85892/68747470733a2f2f66696c65732e636174626f782e6d6f652f7071756239712e706e67)
> 
> etc. the interface and workflow totally changed so the video and screenshots must all be redone from scratch unfortunately

> <img alt="" height="40" src="https://github.githubassets.com/images/email/sponsors/mona.png">
> Show your support for [anuraghazra](/anuraghazra) by sponsoring them.

**Expected behaviour**
We should update the text guide (and video) to prevent confusion.

**Comment by DecryptAG** [comment]
Hey, I would like to work on this issue. Pls assign me this.

**Comment by rickstaa** [comment]
@DecryptAG Great 🚀! Thanks a lot. I assigned you to this issue. Let me know if you need any help. Take your time! 👍🏻

**Comment by DecryptAG** [comment]
@rickstaa I have made the PR regarding this issue. Pls merge it using under the hacktoberfest tag.

**Comment by rickstaa** [comment]
@DecryptAG Amazing. Thanks again for your conribution. I merged it as a hacktoberfest submission under the master!

**Comment by rickstaa** [comment]
Solved by 388ba06a8fb3880cae8734498c8564bb70a99e7c.
