### ISSUE TITLE
[Feature Request] JSON output

### ISSUE THREAD

**Issue by franky47** [anuraghazra/github-readme-stats#2]
At the moment, requests are made every time someone visits a user's profile, which will quickly go over your free limits on Vercel.

Since those stats don't really require a real-time update, they could be updated periodically and cached. Because the username/username repository is (for now) only used for profile READMEs, one way to do this could be to use GitHub Actions in cron mode and update the README (pull the stats, output Markdown and commit the updated file).

For the sake of composability, and following the Unix principles (multiple simple programs composed together), adding a JSON output to this API could work as the source for other tools (GitHub Action, Markdown generator).

**Comment by anuraghazra** [comment]
> one way to do this could be to use GitHub Actions in cron mode and update the README (pull the stats, output Markdown and commit the updated file).

Yes this is a possibility but i don't want to do this because i want it to be simple as pasting a URL into markdown thats why i avoided github actions and cron job stuffs.

Yes caching is an issue, i'll try to add a request cacher with vercel. let me see what i can do

**Comment by franky47** [comment]
It makes sense, I agree that simplicity is paramount.
