### ISSUE TITLE
Showing .. after the repo description

### ISSUE THREAD

**Issue by abhisheknaiidu** [anuraghazra/github-readme-stats#20]
idk why it's showing .. after every repo description. It's looks wierd.

<img width="868" alt="Screenshot 2020-07-11 at 1 21 26 PM" src="https://user-images.githubusercontent.com/55599878/87219520-8818b080-c379-11ea-8b18-2735971773e9.png">

**Comment by anuraghazra** [comment]
Well it's because i'm trimming the text if it's too long, but appending ".." after the text to indicate the text is trimmed.. i'll fix it :D thanks for reporting

**Comment by abhisheknaiidu** [comment]
yea i got it, but i think it's better to trim text only if it crosses certain limit, not for shorter texts also 😅
BTW, Nice Work bro, really liked it 👍🏽

**Comment by anuraghazra** [comment]
Yes the fix is already on its way. Thanks!

**Comment by anuraghazra** [comment]
Thanks @abhisheknaiidu it should be fixed now

<a href="https://github.com/abhisheknaiidu/A-POP">
  <img align="left" src="https://github-readme-stats.vercel.app/api/pin/?username=abhisheknaiidu&repo=A-POP" />
</a>

<a href="https://github.com/abhisheknaiidu/IIITDMJ-GPA">
  <img align="left" src="https://github-readme-stats.vercel.app/api/pin/?username=abhisheknaiidu&repo=IIITDMJ-GPA" />
</a>
