### ISSUE TITLE
code refactor

### ISSUE THREAD

**Issue by rjoydip** [anuraghazra/github-readme-stats#200]
**Is your feature request related to a problem? Please describe.**
> No.

**Refactor the code base**

- [x] Folder structure
- [ ] Simplify code
- [ ] Code style & format [eslint, prettier]
- [ ] Improve code coverage
- [ ] Improve styling
- [x] Removed redundant code
- [ ] Server side rendering

Ref: #200

**Comment by anuraghazra** [comment]
@rjoydip i would say go slow, lets first get the Code Style & Eslint infra ready & merged.

**Comment by rjoydip** [comment]
Correct. That will be better in first try.
