### ISSUE TITLE
Add theme: Vitesse

### ISSUE THREAD

**Issue by Mosaab-Emam** [anuraghazra/github-readme-stats#2000]
**Is your feature request related to a problem? Please describe.**
No

**Describe the solution you'd like**
Add a new theme inspired by Vitesse theme by @antfu

![Screenshot from 2022-09-05 21-06-06](https://user-images.githubusercontent.com/26435307/188504115-f1a6da70-d84d-4b76-9d7a-7080613d7973.png)

**Additional context**
[antfu/vscode-theme-vitesse](https://github.com/antfu/vscode-theme-vitesse)
[antfu/prism-theme-vars](https://github.com/antfu/prism-theme-vars)

**Comment by rickstaa** [comment]
@Mosaab-Emam Thanks for your contribution. I will close this for now since we simply track themes by their respective PR.
