### ISSUE TITLE
How to hide jupyter Notebook?

### ISSUE THREAD

**Issue by Donghoon759** [anuraghazra/github-readme-stats#201]
My top language is Jupyter Notebook and I want to hide it. Then, how can I write the query string to hide it?
I tried
hide=jupyter_notebook
hide=jupyterNotebook
hide=Jupyter_notebook
hide=JupyterNotebook
hide=jupyter-notebook
hide=jupyter_notebook

**Comment by anuraghazra** [comment]
You tried everything except SPACE.

**Comment by Donghoon759** [comment]
hide=jupyter%20notebook is the answer. Nice :) Thx.

**Comment by shaunthom** [comment]
Wow, this is so handy! Thanks @donghoon-song
