### ISSUE TITLE
Feature Request ( / question). Organization stars.

### ISSUE THREAD

**Issue by ethanaobrien** [anuraghazra/github-readme-stats#2025]
**Is your feature request related to a problem? Please describe.**

I recently transferred a big project I had into a new organization I just made, to keep my repositories more organized. When I did so the stats card on my profile dropped by hundreds of stars (because the repository was transferred to my organization)

**Describe the solution you'd like**

I request the stats card to also count stars on any organizations you own, or to add an option for this feature.

<br>

Thank you for your time!

**Comment by rickstaa** [comment]
@ethanaobrien Thanks for your question. I think https://github.com/anuraghazra/github-readme-stats/discussions/1808 will answer it. Feel free to re-open this issue if it does not.
