### ISSUE TITLE
Add GitLab backend

### ISSUE THREAD

**Issue by tonka3000** [anuraghazra/github-readme-stats#203]
I would be nice when you can also query data also from https://gitlab.com (as option in your API). I've already filed a issue on GitLab.com for [profile README.md for GitLab](https://gitlab.com/gitlab-org/gitlab/-/issues/232157).

Here is a link to the [GraphQL API of GitLab](https://docs.gitlab.com/ee/api/graphql)

**Comment by anuraghazra** [comment]
Hi @tonka3000 thanks for requesting the feature, yeah maybe it would be a good idea. but i'm not sure i would support gitlab backend.

I'll keep you posted after doing some experiments with the gitlab gql api

**Comment by tonka3000** [comment]
It should not be that hard to support GitLab, because the base structure is more or less the same as GitHub.

I will also try out the GraphQL API from GitLab, always used the REST API before.
