### ISSUE TITLE
Add option defaults to README.

### ISSUE THREAD

**Issue by rickstaa** [anuraghazra/github-readme-stats#2030]
**Is your feature request related to a problem? Please describe.**

Currently, we do not list the option defaults in the readme.

**Describe the solution you'd like**

I think adding the option defaults will improve the documentation. Maybe something like:

```diff
- hide_border - Hides the card's border (boolean)
+ hide_border - Hides the card's border (boolean). Defaults to false.
```

**Comment by asifurrahaman754** [comment]
hi, is this sovled, i would like to work on this

**Comment by adi-uchiha** [comment]
I want to fix this. any changes to #2051 ?

**Comment by Ayushi96** [comment]
Hey @rickstaa, could you please assign this issue to me ?

**Comment by rickstaa** [comment]
@Ayushi96, @adi-uchiha and @asifurrahaman754, @Jagrutiti already fixed several sections from the readme in https://github.com/anuraghazra/github-readme-stats/pull/2051. The only sections that still need to be done are:
- https://github.com/anuraghazra/github-readme-stats#repo-card-exclusive-options
- https://github.com/anuraghazra/github-readme-stats#language-card-exclusive-options
- https://github.com/anuraghazra/github-readme-stats#language-card-exclusive-options

@Ayushi96 I assigned you to this issue since @adi-uchiha and @asifurrahaman754 already have other issues assigned to them. 👍🏻

**Comment by Ayushi96** [comment]
Thanks for assigning me the issue @rickstaa

**Comment by rickstaa** [comment]
@Ayushi96, I merged your contribution to the master. Thanks!

@adi-uchiha Something went wrong while also trying to merge your PR to the master (see https://github.com/anuraghazra/github-readme-stats/pull/2092#issuecomment-1265049367). Please create a new PR with the default values that were not yet done by @Ayushi96, and I will include it as a Hacktoberfest contribution.

**Comment by rickstaa** [comment]
@Ayushi96 and @adi-uchiha, thanks again for your contribution! 🔥 🚀
