### ISSUE TITLE
github-readme-stats.vercel.app does not works

### ISSUE THREAD

**Issue by ImKunYoung** [anuraghazra/github-readme-stats#2048]
## **✔️ Describe the bug**
github-readme-stats.vercel.app does not works

---

**- 📸 ScreenShot - Code**
![image](https://user-images.githubusercontent.com/46955032/192092764-a67f0f82-06a6-4d49-b241-90253b64343e.png)

**- 📸 ScreenShot - result**
![image](https://user-images.githubusercontent.com/46955032/192092751-7d543b14-2963-4a6d-a3f0-afa2996b4c7f.png)

---

**- 📋 MarkDown Code**
```
<p align="center">
  <a href=""><img src="https://github-readme-stats.vercel.app/api/top-langs/?username=ImKunYoung&layout=compact&langs_count=10"/></a>&nbsp
  <a href=""><img src="https://github-readme-stats.vercel.app/api?username=ImKunYoung&count_private=true&show_icons=true"/></a>
</p>
```

**- 📋 MarkDown Result**
<p align="center">
  <a href=""><img src="https://github-readme-stats.vercel.app/api/top-langs/?username=ImKunYoung&layout=compact&langs_count=10"/></a>&nbsp
  <a href=""><img src="https://github-readme-stats.vercel.app/api?username=ImKunYoung&count_private=true&show_icons=true"/></a>
</p>

<br/>

---

**- 📋 MarkDown Demo Code**
```
[![Top Langs](https://github-readme-stats.vercel.app/api/top-langs/?username=anuraghazra&layout=compact)](https://github.com/anuraghazra/github-readme-stats)
```

**- 📋 MarkDown Demo Result**

[![Top Langs](https://github-readme-stats.vercel.app/api/top-langs/?username=anuraghazra&layout=compact)](https://github.com/anuraghazra/github-readme-stats)

<br/>

## **✔️ Expected behaviour**
![image](https://user-images.githubusercontent.com/46955032/192092715-84cbd558-245b-4e5f-85e9-893a6c774bb1.png)

<br/>
<br/>

sorry for my short english

**Comment by schmittsfn** [comment]
Here the error logs:
```
[GET] /api/pin/?username=schmittsfn&repo=STSRotateAround&theme=dark&show_owner=false
12:28:00:91
RequestId: dc88f527-1cb0-476d-8c17-fbcdbf2ea59a Error: Runtime exited with error: exit status 1
Runtime.ExitError
2022-09-24T10:28:00.985Z	undefined	ERROR	Error [ERR_MODULE_NOT_FOUND]: Cannot find module '/var/task/src/common/utils' imported from /var/task/api/pin.js
    at new NodeError (node:internal/errors:372:5)
    at finalizeResolution (node:internal/modules/esm/resolve:437:11)
    at moduleResolve (node:internal/modules/esm/resolve:1009:10)
    at defaultResolve (node:internal/modules/esm/resolve:1218:11)
    at ESMLoader.resolve (node:internal/modules/esm/loader:580:30)
    at ESMLoader.getModuleJob (node:internal/modules/esm/loader:294:18)
    at ModuleWrap.<anonymous> (node:internal/modules/esm/module_job:80:40)
    at link (node:internal/modules/esm/module_job:78:36) {
  code: 'ERR_MODULE_NOT_FOUND'
}
RequestId: caa2e2b4-728e-49f9-b8d7-7311587cf6ac Error: Runtime exited with error: exit status 1
Runtime.ExitError
```

**Comment by schmittsfn** [comment]
Possibly caused by changes in this commit: https://github.com/anuraghazra/github-readme-stats/commit/107f7ca52c3431bf989e7c3624ad130e98cb4f5a

Maybe Vercel cannot interpret more modern js syntax?

<img width="1393" alt="Screenshot 2022-09-24 at 12 53 43" src="https://user-images.githubusercontent.com/1940017/192094023-55395027-7fc9-4062-b21a-d65a0e7debc5.png">

**Comment by rickstaa** [comment]
@schmittsfn Thanks for letting me know. I think https://github.com/anuraghazra/github-readme-stats/commit/107f7ca52c3431bf989e7c3624ad130e98cb4f5a indeed causes it. I will spend some minutes debugging it and otherwise revert #1995.

**Comment by schmittsfn** [comment]
@rickstaa Thank you for looking into this 🙏
I saw that the default vercel instance seems to have stopped throwing `500`s. Was there a config that needed changing on Vercel? (I'm asking because there is no commit yet on this repo)

**Comment by schmittsfn** [comment]
Oh there is a commit now. Lag on my side

**Comment by schmittsfn** [comment]
Never mind, saw your commit. Thank you for the fix
