### ISSUE TITLE
Server is crashed

### ISSUE THREAD

**Issue by Dominik48N** [anuraghazra/github-readme-stats#2049]
## The GitHub README server is down and therefore unavailable.

![image](https://user-images.githubusercontent.com/46966988/192093682-3dae7483-7a72-460d-8a33-6e65420e8c51.png)

**Comment by asiryan** [comment]
me too

**Comment by Amaroke** [comment]
Same problem here.

**Comment by akielaries** [comment]
Experiencing the same.

**Comment by rickstaa** [comment]
Thanks for letting me know it is caused by the last PR I will try to fix it or revert the PR.

**Comment by rickstaa** [comment]
Found the error. I will push a fix in a mintue.

**Comment by XdpCS** [comment]
me too

**Comment by Amaroke** [comment]
The fix works! Thanks!

**Comment by Dominik48N** [comment]
It works. Thank you!
