### ISSUE TITLE
Theme can sync with system

### ISSUE THREAD

**Issue by rainofsilence** [anuraghazra/github-readme-stats#2071]
**Is your feature request related to a problem? Please describe.**
I wanted to change the light and dark theme based on the system settings, but I can't do it now

**Describe the solution you'd like**
I think the theme can change automatically like the system configuration, or depending on the time of day

**Describe alternatives you've considered**
I think can also come up with a theme without a background color

**Additional context**
<img width="799" alt="pic1" src="https://user-images.githubusercontent.com/47657375/192829481-8175c2da-3438-4e50-8046-241ff19d9261.png">

**Comment by rickstaa** [comment]
Duplicate of https://github.com/anuraghazra/github-readme-stats/issues/1001.

**Comment by rainofsilence** [comment]
Thank you
