### ISSUE TITLE
Document auto theme change in README

### ISSUE THREAD

**Issue by rickstaa** [anuraghazra/github-readme-stats#2074]
**Is your feature request related to a problem? Please describe.**

As explained in #690, it is not yet possible to switch the theme automatically on the Vercel instance. Nevertheless, there are multiple ways to get the card to switch themes on the client side. The methods for doing this (i.e. `transparent background`, `#gh-dark-mode-only` and `source media`) need to be explained in the README so that users are aware these options exist.

**Describe the solution you'd like**

It would be great if README would have a section for setting up dynamic themes. This section should explain:
- We can not infer the browser theme on the server since GitHub will re-upload the cards and serve them from their CDN (see https://github.com/anuraghazra/github-readme-stats/issues/79#issuecomment-663706819).
- That users can use the `transparent` theme.

![Anurag's GitHub stats](https://github-readme-stats.vercel.app/api?username=anuraghazra&show_icons=true&theme=transparent)

```md
![Anurag's GitHub stats](https://github-readme-stats.vercel.app/api?username=anuraghazra&show_icons=true&theme=transparent)
```

- That users can use `bg_color=00000000` to set a transparent background.

![Anurag's GitHub stats](https://github-readme-stats.vercel.app/api?username=anuraghazra&show_icons=true&theme=default&bg_color=00000000)

```md
![Anurag's GitHub stats](https://github-readme-stats.vercel.app/api?username=anuraghazra&show_icons=true&theme=dark&bg_color=00000000)
```

- They can use GitHub's theme context tags to switch the theme automatically (see https://github.blog/changelog/2021-11-24-specify-theme-context-for-images-in-markdown/) based on the set GitHub theme.

[![Anurag's GitHub stats](https://github-readme-stats.vercel.app/api?username=anuraghazra&theme=dark#gh-dark-mode-only)](https://github.com/anuraghazra/github-readme-stats#gh-dark-mode-only)
[![Anurag's GitHub stats](https://github-readme-stats.vercel.app/api?username=anuraghazra&theme=default#gh-light-mode-only)](https://github.com/anuraghazra/github-readme-stats#gh-light-mode-only)

```markdown
[![Anurag's GitHub stats](https://github-readme-stats.vercel.app/api?username=anuraghazra&theme=dark#gh-dark-mode-only)](https://github.com/anuraghazra/github-readme-stats#gh-dark-mode-only)
[![Anurag's GitHub stats](https://github-readme-stats.vercel.app/api?username=anuraghazra&theme=default#gh-light-mode-only)](https://github.com/anuraghazra/github-readme-stats#gh-light-mode-only)
````

- That they can use GitHub's [new media feature](https://github.blog/changelog/2022-05-19-specify-theme-context-for-images-in-markdown-beta/) in the HTML `<picture>` element to switch the theme automatically based on the set GitHub theme. This option, however, requires the user to refresh the page before the card theme is updated.

```html
<a href="https://github.com/anuraghazra/github-readme-stats">
<picture>
  <source media="(prefers-color-scheme: dark)" srcset="https://github-readme-stats.vercel.app/api?username=anuraghazra&theme=dark">
  <img alt="Shows Anuraghazra's GitHub Stats." src="https://github-readme-stats.vercel.app/api?username=anuraghazra&theme=default">
</picture>
</a>
```

<a href="https://github.com/anuraghazra/github-readme-stats">
<picture>
  <source media="(prefers-color-scheme: dark)" srcset="https://github-readme-stats.vercel.app/api?username=anuraghazra&theme=dark">
  <img alt="Shows Anuraghazra's GitHub Stats." src="https://github-readme-stats.vercel.app/api?username=anuraghazra&theme=default">
</picture>
</a>

**Comment by asifurrahaman754** [comment]
Hi, i would like work on this

**Comment by rickstaa** [comment]
@asifurrahaman754 Great that you want to take this on! I think it will help many people if this feature is clearly documented. I assigned you to this issue. 🚀

**Comment by rickstaa** [comment]
I just added one default `transparent` theme you can mention.

https://github-readme-stats.vercel.app/api?username=anuraghazra&title_color=006AFF&icon_color=0579C3&text_color=417E87&bg_color=ffffff00&show_icons=true

```md
[![Anurag's GitHub stats](https://github-readme-stats.vercel.app/api?username=anuraghazra&theme=transparent&show_icons=true)](https://github.com/anuraghazra/github-readme-stats)
```

[![Anurag's GitHub stats](https://github-readme-stats.vercel.app/api?username=anuraghazra&theme=transparent&show_icons=true)](https://github.com/anuraghazra/github-readme-stats)

**Comment by rickstaa** [comment]
Given your comment in https://github.com/anuraghazra/github-readme-stats/issues/764#issuecomment-1264670133 I was wondering if you still want to be assigned to this issue?

**Comment by asifurrahaman754** [comment]
Oh, yes i forgot to tell u, u can assigned this to someone

**Comment by rickstaa** [comment]
No problem. Thanks for letting me know. 👍🏻

**Comment by rickstaa** [comment]
For people taking this on, I think you can add a `Responsive Theme` section under the https://github.com/anuraghazra/github-readme-stats#themes section.

**Comment by rickstaa** [comment]
For this issue, I was looking for the following:
- [ ] Add Responsive Card Theme section under themes.
- [ ] Explain why we can not change the theme on the server side (see https://github.com/anuraghazra/github-readme-stats/issues/79#issuecomment-663706819).
- [ ] Quickly give the four methods people can use to create dynamics themes on the client side.
    - [ ] Simplest one: Use the `transparent theme`.
    - [ ] Set the `bg_color` to a color with a transparent alpha channel `bg_color=00000000`.
    - [ ] Use GitHub's theme context tags to automatically switch the theme based (see https://github.blog/changelog/2021-11-24-specify-theme-context-for-images-in-markdown/). See the snippet above.
    - [ ] Use GitHub's [new media feature](https://github.blog/changelog/2022-05-19-specify-theme-context-for-images-in-markdown-beta/) in the HTML <picture> element automatically switch the theme based. See the snippet above.

**Comment by lostgirljourney** [comment]
I want to get assigned to this.

**Comment by cjdomacena** [comment]
I would like to contribute to this issue

**Comment by rickstaa** [comment]
@cjdomacena Unfortunately, I already assigned @lostgirljourney to this issue some hours ago. 😅

**Comment by rickstaa** [comment]
@lostgirljourney How is your Hacktoberfest PR going 😃? Feel free to tag me if anything is unclear. No hurries 👍🏻.

**Comment by lostgirljourney** [comment]
hey @rickstaa, sorry for delay, caught in office work. but i am on it.

**Comment by rickstaa** [comment]
@lostgirljourney No worries! Take your time 👍🏻.

**Comment by rickstaa** [comment]
Done in #2229.
