### ISSUE TITLE
:hammer_and_wrench: Hacktoberfest 2022 - Guidelines

### ISSUE THREAD

**Issue by rickstaa** [anuraghazra/github-readme-stats#2077]
Please check [this discussion post](https://github.com/anuraghazra/github-readme-stats/discussions/2076) for this year's Hacktoberfest guidelines.

**Comment by prathikshetty2002** [comment]
I can work on this , can prepare markdown file with details on contributing to hacktoberfest and guidelines. just let me know where to append

**Comment by rickstaa** [comment]
@prathikshetty2002 Sorry for the confusion. This is not an issue that needs to be worked on. I opened this issue to point to the GRS Hacktoberfest guidelines (see https://github.com/anuraghazra/github-readme-stats/discussions/2076).

**Comment by prathikshetty2002** [comment]
> @prathikshetty2002 Sorry for the confusion. This is not an issue that needs to be worked on. I opened this issue to point to the GRS Hacktoberfest guidelines (see #2076).

ok no problem👍

**Comment by qwerty541** [comment]
Closing this because it's outdated.
