### ISSUE TITLE
[ A Doubt ] How does api code works without express?

### ISSUE THREAD

**Issue by hmble** [anuraghazra/github-readme-stats#208]
Sorry to ask such a question here. But I was reading through code the other day and `api` part of code got me curious about how it works.

My doubt is how does this api `https://github-readme-stats.vercel.app/api?username=anuraghazra` works without any server library like express in `package.json` ?

Although the code for server part looks the same as express.
Well it will help my curiosity if @anuraghazra you could answer this question. :)

**Comment by anuraghazra** [comment]
Hi @hmble it's actually a serverless function. runs on vercel. 

more info: https://vercel.com/docs/v2/serverless-functions/introduction

**Comment by hmble** [comment]
Thank you for clearing my doubt. Now I understand use case of Serverless functions.
