### ISSUE TITLE
Request For New Feature

### ISSUE THREAD

**Issue by arsondog** [anuraghazra/github-readme-stats#2095]
**Feature Request!** 

I think you should add a description box as part of the read me! It would be a great way to contribute back to the people using it and plus it would also make the readme much cooler!

**Comment by arsondog** [comment]
P.S. By description box I mean like a custom user description, **NOT the repository description.**

**Comment by rickstaa** [comment]
@arsondog, I'm not sure what you mean. Can you elaborate? A description of which user?

**Comment by arsondog** [comment]
For example, it's like a textbox but it's for the description and it has the themes that the statistics have. I think it would make the user profiles much more unique. However, I understand as its not statistics, it probably wouldn't be added but it would be a cool feature if it is implemented.

**Comment by rickstaa** [comment]
@arsondog thanks for elloberating. If I understand you correctly, you want a card that displays something like this.

![image](https://user-images.githubusercontent.com/17570430/193761775-44a08367-34d9-4f8c-a503-601d8020748e.png)

A photo and a text?

**Comment by rickstaa** [comment]
Does https://github.com/rocktimsaikia/github-card suit your need? A handful of projects do just that (see https://github.com/topics/profile-card).

**Comment by rickstaa** [comment]
Closing this for now. Feel free to elaborate and I will reopen this issue. 👍🏻
