### ISSUE TITLE
Can we do auto card_width?

### ISSUE THREAD

**Issue by sangeethkc** [anuraghazra/github-readme-stats#2097]
It's frustrating when the card width is not auto adjusting for profile page. I have 3 cards the needs to auto align to center but i am having to give the card_width = 200 each to get the cards to align manually on profile page.

It would be great to have a feature to align cards to center by giving align = "center" and card_width=auto.

**Comment by rickstaa** [comment]
@sangeethkc Great idea. Not sure if it can be done on the server side, though, as GitHub will re-upload the cards and serve them from their CDNs. I, therefore, suspect the only way to do this is on the client side through HTML and CSS. You can, however, give me a try if you want.

**Comment by rickstaa** [comment]
Closing this for now. Feel free to re-open if you think it is possible.
