### ISSUE TITLE
'Robotframework' is not displaying in top language

### ISSUE THREAD

**Issue by adiralashiva8** [anuraghazra/github-readme-stats#210]
**Describe the bug**
In top language card robotframework is not displaying

**Expected behavior**
Previously 'robotframework' used to display under top language cards

**Screenshots / Live demo link (paste the github-readme-stats link as markdown image)**
Test Data (my profile link) - https://github.com/adiralashiva8/adiralashiva8/blob/master/README.md

Extension of robotframework is '.robot'

**Comment by anuraghazra** [comment]
It fetches the top languages ordered by update date & size (in bytes) of the language used 

```gql
repositories(isFork: false, first: 100, orderBy: {field: UPDATED_AT, direction: DESC}) {
            nodes {
              languages(first: 1, orderBy: {field: SIZE, direction: DESC}) {
```

**Comment by adiralashiva8** [comment]
So, if there is no update for long time. Respective language won't display in language card?

Can we make it consider overrall instead of latest?

**Comment by anuraghazra** [comment]
> So, if there is no update for long time. Respective language won't display in language card?
> 
> Can we make it to consider overrall instead of latest?

You have 33 repos & we are calculating max 100 repos, which means we are calculating all of your repos so the UPDATE_AT is not does not matter here. 

We are sorting the languages by their amount of size and you have less amount of robotframework code than HTML so it's not showing. which is expected behaviour.

**Comment by adiralashiva8** [comment]
Thank you @anuraghazra for explanation 

As a user when i hide html, i expect calculation should be on other languages (may be enhancement)

Please close the bug since its working as expected

**Comment by anuraghazra** [comment]
closing this in favor of #136
