### ISSUE TITLE
There is an issue

### ISSUE THREAD

**Issue by wb-ts** [anuraghazra/github-readme-stats#2113]
[https://prnt.sc/NRmsgWA6CDPK](url)

**Comment by kachkaev** [comment]
Same here: https://github.com/kachkaev

<img width="1306" alt="Screenshot 2022-10-04 at 13 30 42" src="https://user-images.githubusercontent.com/608862/193819853-82b36e5a-2917-4336-b86a-f8edbd4fa0d0.png">

Code:

```
<p align="center">
  <img src="https://github-readme-stats.vercel.app/api?username=kachkaev&count_private=true" alt="Alexander Kachkaev's github stats">
</p>
```

**Comment by rickstaa** [comment]
Thanks for letting us know. It is related to https://github.com/anuraghazra/github-readme-stats/issues/1471. I will send @anuraghazra a new PAT token.

**Comment by kachkaev** [comment]
Thanks @rickstaa! It works again 🎉
