### ISSUE TITLE
Sizes of Repo Cards

### ISSUE THREAD

**Issue by ApurvShah007** [anuraghazra/github-readme-stats#212]
**Describe the bug**
The sizes of repo cards as of now differ due to the size of the description of the repo.

**Expected behavior**
Would be great if all the repo cards ore of same size as it looks uneven on the readme. 

![Screen Shot 2020-07-27 at 1 48 54 PM](https://user-images.githubusercontent.com/43690373/88534030-eb5c4100-d00f-11ea-8358-7365da1c965f.png)

**Comment by ApurvShah007** [comment]
@anuraghazra worth giving it a look?

**Comment by anuraghazra** [comment]
@ApurvShah007 This is not a bug actually, this is expected behaviour which is implemented in #206 

Well your request is valid tho, maybe we can add a option to limit the maximum line wraps to "1" so that all cards stay same height

**Comment by ApurvShah007** [comment]
@anuraghazra My bad, I had not gone in and seen if it had been discussed before. I would appreciate if it was possible to make them all in a size limit.

**Comment by HaaLeo** [comment]
We could make the height fixed to the multi line behaviour. This is also what github does when you pin two repo cards with different description length next to each other:

<img width="922" alt="image" src="https://user-images.githubusercontent.com/23164374/88557565-a691d380-d02a-11ea-99f2-0231f3de5c08.png">

**Comment by anuraghazra** [comment]
> @anuraghazra We could make the height fixed to the multi line behaviour. This is also what github does when you pin two repo cards with different description length next to each other:
> 
> <img alt="image" width="922" src="https://user-images.githubusercontent.com/23164374/88557565-a691d380-d02a-11ea-99f2-0231f3de5c08.png">

It does that because of CSS auto flex height. it stretches both rows.
But we can't do that in markdown/readme, because there is no flex layouts in markdown & we cannot determine how & where users placed the images.

**Comment by HaaLeo** [comment]
@anuraghazra sure. However, we can hard code the card's `height` to the multiline case for consistency. So every card, no matter how long the description is, will have the height of the multiline case. 

Consequently, every single line case card will look like the `emilast/vscode-logfile-highlighter` card above. Even when it's placed next to another single line description card.

**Comment by anuraghazra** [comment]
> we can hard code the card's height to the multiline case for consistency. So every card, no matter how long the description is, will have the height of the multiline case.

Yes we can do this, but thats what i'm avoiding. the extra 2 line space in the cards looks kinda odd to me.

**Comment by HaaLeo** [comment]
jup, there is no right or wrong decision here 😉. This is a pure design decision.

Also an additional parameter like `forceSingleLineDescription` or `forceMultiLineDescription` could be an option.

**Comment by anuraghazra** [comment]
Yeah that's what i proposed earlier

> maybe we can add a option to limit the maximum line wraps to "1" so that all cards stay same height

**Comment by ApurvShah007** [comment]
@anuraghazra any updates on how I can make them same size?
