### ISSUE TITLE
Ability to change `Total commits` human formatting

### ISSUE THREAD

**Issue by CaedenPH** [anuraghazra/github-readme-stats#2128]
**Is your feature request related to a problem? Please describe.**
The ability to change the `total commits` rounding system. For example, if you have `1978` commits, it is automatically humanly formatted to `1.9k`

**Describe the solution you'd like**
This feature should be in the form of an argument, for example, it could be a boolean; `format_commits=false` results in `1978`, or it could be in the form of the rounding, to how many digits somehow.

**Describe alternatives you've considered**

**Additional context**

**Comment by rickstaa** [comment]
@CaedenPH thanks for your feature request. I, however, think the `k`, which stands for kilo, is a well-accepted abbreviation. We use it to keep the card from going bulky. Currently, we will therefore keep this behaviour and use it over human-readable text.

**Comment by rickstaa** [comment]
> > @CaedenPH thanks for your feature request. I, however, think the `k`, which stands for kilo, is a well-accepted abbreviation. We use it to keep the card from going bulky. Currently, we will therefore keep this behaviour and use it over human-readable text.
> 
> In my opinion, adding an optional to add a couple extra characters won't make the card much less bulkier. For example, my commits is `1878`, which is formatted to `1.9k` only adds 1 extra character.

I see your point. 🤔 I think it is mainly a matter of preference. Let's keep this issue open. If enough people upvote this issue, we might reconsider. 👍🏻
