### ISSUE TITLE
Total views/unique visitors and clones/unique cloners of all repos

### ISSUE THREAD

**Issue by peppelongo96** [anuraghazra/github-readme-stats#213]
Hi! Is it possible to add a counter that tooks track af all views/unique visitors and clones/unique cloners of all repos? I think could be appreciatable to have them as stats option

**Comment by anuraghazra** [comment]
Hi @peppelongo96 thanks for requesting the feature.

As far as i know, it is not possible to fetch/get those stats without granting full access to other user's account (maybe possible with self hosted forks of github-readme-stats) because those are user's private informations.

**Comment by peppelongo96** [comment]
@anuraghazra what a fast answer! 
I think you are talking about some OAuth (I'm very noob about). Howewer, thanks for your job!

**Comment by anuraghazra** [comment]
> I think you are talking about some OAuth

No, Personal Access tokens of github.
