### ISSUE TITLE
error 

### ISSUE THREAD

**Issue by LuizFernandoDeveloper** [anuraghazra/github-readme-stats#2131]
my readme : https://github.com/LuizFernandoDeveloper/LuizFernandoDeveloper
![LuizFernandoDeveloper_README md at main · LuizFernandoDeveloper_LuizFernandoDeveloper - Google Chrome 05_10_2022 09_24_10](https://user-images.githubusercontent.com/104641055/194059894-9b3881e7-e511-40c6-8f4e-1ef9e888cd6c.png)

**Comment by GorlikItsMe** [comment]
Duplicate: https://github.com/anuraghazra/github-readme-stats/issues/2130
