### ISSUE TITLE
[error] github stats error

### ISSUE THREAD

**Issue by Jacobkyalo** [anuraghazra/github-readme-stats#2133]
please am getting an error in my GitHub stats card,  need some help
![error](https://user-images.githubusercontent.com/94710630/194114686-803f4392-729f-4c71-81d6-70c00aca213b.png)

**Comment by duberlyguarnizofuentesrivera** [comment]
This is noted in issue #1772 (first comment). The only thing you can do is wait.

**Comment by rickstaa** [comment]
Duplicate of #2130.
