### ISSUE TITLE
Not showing correct number of commits

### ISSUE THREAD

**Issue by CaedenPH** [anuraghazra/github-readme-stats#2135]
**Describe the bug**
The github stats is not showing the correct number of commits.

**Expected behaviour**

**Screenshots / Live demo link (paste the github-readme-stats link as markdown image)**
![image](https://user-images.githubusercontent.com/23421705/194122237-8f611b54-0d0d-4095-997b-222b2962a0b8.png)

Here is the url; https://github-readme-stats.vercel.app/api?username=caedenph&show_icons=true&theme=dark&include_all_commits=true&count_private=true

This isn't possible, as my official github number (returned from the raw api and working as such for the past couple months has been around 1.8k)

**Additional context**
When changing `include_all_commits` to `false`, it goes up to `1.6k` which is the correct number for this year I believe

**Comment by CaedenPH** [comment]
Some reason its fixed now 🙃

**Comment by rickstaa** [comment]
@CaedenPH Thanks for your questions. This is a know issue (see #1515). It will be fixed by merging #1691.
