### ISSUE TITLE
Why diffrence Contributions total commits 

### ISSUE THREAD

**Issue by jameslee214** [anuraghazra/github-readme-stats#2139]
**Describe the bug**
The Total Contribution count value is different from the Total commit count value.

**Expected behaviour**
It also included the private_count and include_all_commit properties. However, the Total Commit is reduced. Why is that?

**Screenshots / Live demo link (paste the github-readme-stats link as markdown image)**

<p align="center">
  <img src="http://github-readme-streak-stats.herokuapp.com?user=jameslee214&theme=merko&hide_border=true&date_format=j%20M%5B%20Y%5D" alt="My GitHub Streak Stats">
  <br>
  <img src="https://github-readme-stats.vercel.app/api?username=jameslee214&theme=merko&show_icons=true&hide_border=true&count_private=true&include_all_commits=true" alt="My GitHub Stats">
</p>

**Additional context**

```html
<p align="center">
  <img src="http://github-readme-streak-stats.herokuapp.com?user=jameslee214&theme=radial&hide_border=true&date_format=j%20M%5B%20Y%5D" alt="My GitHub Streak Stats">
  <br>
  <img src="https://github-readme-stats.vercel.app/api?username=jameslee214&theme=dark&show_icons=true&hide_border=true&count_private=true&include_all_commits=true" alt="My GitHub Stats">
</p>
```

**Comment by rickstaa** [comment]
No problem. A 3.3k difference is possible if you did a lot of non-commit actions on GitHub. You can check the data we receive from github using the GraphQL explorer:

```graphql
query userInfo($login: String!) {
  user(login: $login) {
    name
    login
    contributionsCollection {
      totalCommitContributions
      restrictedContributionsCount
    }
  }
}
```

```graphql
{"login": "jameslee214"}
```

There, however, is a small bug with the `include_all_commits` parameter that sometimes leads to wrong commit numbers. #1691 should fix this but requires some changes before merging it.

**Comment by jameslee214** [comment]
@rickstaa  Thank you again for your reply.

I look forward to solving the problem.!!
