### ISSUE TITLE
Mobile app display fails

### ISSUE THREAD

**Issue by ajmeese7** [anuraghazra/github-readme-stats#215]
**Describe the bug**
When you view any stat cards on mobile, they do not show any of the information.

**Expected behavior**
They should behave exactly like they do on desktop, albeit smaller.

**Screenshots / Live demo link (paste the github-readme-stats link as markdown image)**
![stats_mobile](https://user-images.githubusercontent.com/17814535/88550216-ea62e980-cfe6-11ea-98ec-1e6e84a9d0ca.jpg)

**Additional context**
I have noticed this problem on every repo with the stat cards, not just the README of this repository.

**Comment by anuraghazra** [comment]
Hi @ajmeese7 thanks for opening the issue, please provide us with your mobile's specifications & which browser you are using

**Comment by ajmeese7** [comment]
I am using a Note 10+, and I am using the official GitHub app from the Play Store

**Comment by cybarspace** [comment]
An interesting thing to note is that the cards work as expected on Mobile browsers. It's only in the app that it breaks. Maybe the app renders things differently than browsers?

**Comment by rickstaa** [comment]
This appears to be fixed. See https://github.com/anuraghazra/github-readme-stats/issues/899#issuecomment-877199309. I will close the related issues for now. If anyone is still experiencing issues feel free to leave a comment.
