### ISSUE TITLE
Grade description in the report card.

### ISSUE THREAD

**Issue by brundabharadwaj** [anuraghazra/github-readme-stats#2157]
### Is your feature request related to a problem? Please describe.

Feature request is not related any of the existing problem.

Instead of just displaying the Grade as A+, A++, S and more, alongside we can also provide  description on when these grades are achieved.

### Describe the solution you'd like

From the code's perspective I can see these details available:
![image](https://user-images.githubusercontent.com/49773125/194684764-5e6848d2-9214-474d-9e0d-8c2e54a20673.png)

Utilizing this and  displaying it on the report card.

**Comment by rickstaa** [comment]
@brundabharadwaj I'm not sure if I understand your request correctly. Do you want us to display more information about the ranks? Do you mean the explanation in the [readme](https://github.com/anuraghazra/github-readme-stats#github-stats-card) but then displayed when hovering the rank circle (see https://stackoverflow.com/questions/41768657/display-text-over-svg-element-on-hover).

> **Note**
> Available ranks are S+ (top 1%), S (top 25%), A++ (top 45%), A+ (top 60%), and B+ (everyone). The values are calculated by using the [cumulative distribution function](https://en.wikipedia.org/wiki/Cumulative_distribution_function) using commits, contributions, issues, stars, pull requests, followers, and owned repositories. The implementation can be investigated at [src/calculateRank.js](https://github.com/anuraghazra/github-readme-stats/blob/master/src/calculateRank.js).

**Comment by brundabharadwaj** [comment]
> Available ranks are S+ (top 1%), S (top 25%), A++ (top 45%), A+ (top 60%), and B+ (everyone).
 --> Exactly! as you have explained over here! @rickstaa
