### ISSUE TITLE
Can I add a Vietnamese readme documentation?

### ISSUE THREAD

**Issue by hhpr98** [anuraghazra/github-readme-stats#2166]
### Is your feature request related to a problem? Please describe.

I would like to add a new documentation that supporting Vietnamese

### Describe the solution you'd like

add new readme_vi.md

**Comment by rickstaa** [comment]
@hhpr98 Of course, feel free to create a PR. 👍🏻 However, please be aware that we do not accept [translation-related PRs](https://github.com/anuraghazra/github-readme-stats/pulls?q=is%3Aopen+is%3Apr+label%3Athemes+label%3Adoc-translation) for the current Hacktoberfest (see #2076). In addition, we are trying to automate the translations, but we haven't yet found a practical way to do this (see #2053).

**Comment by hhpr98** [comment]
ok, got it. Ty.
