### ISSUE TITLE
Background gradient color

### ISSUE THREAD

**Issue by judicaelandria** [anuraghazra/github-readme-stats#218]
Having a repo card with gradient color in the background would be cool too, what do you think?
![Path 4](https://user-images.githubusercontent.com/46365844/88565954-fcbc4200-d03d-11ea-95ed-d655019f2f52.png)

**Comment by anuraghazra** [comment]
@judicaelandria Thanks for requesting the feature, yeah might be a good idea & would give a card more unique and modern look to. i'll see what i can do.

**Comment by nthnchu** [comment]
I'd like to try working on it, but I don't know what format I should use for gradients. Would `?bg_color=90,0000ff,00ff00` be okay with you (the format is angle, start color, end color)? Or do you have another suggestion @anuraghazra?

**Comment by anuraghazra** [comment]
@nthnchu some things to consider
- should not break the current api
- should not break the current themes
- should also support the themes collection (maybe with an array)

Yeah i think angle,start,end is a good format. I'll have to check the svg docs tho to see what works best. (or maybe we can just use CSS gradients)

**Comment by judicaelandria** [comment]
This is useful link, if you want to take this issue
[gradients in svg](https://developer.mozilla.org/en-US/docs/Web/SVG/Tutorial/Gradients)

**Comment by judicaelandria** [comment]
adding the bg color as array for the linear gradient
check if the bg color passed is an arrary we apply the linear gradient background color if not just one color in the background

**Comment by nthnchu** [comment]
I assume you just want linear gradients and not radial @anuraghazra and @judicaelandria. That's all my PR (#246) covers...

**Comment by judicaelandria** [comment]
yeah, it's just linear gradient, didn't try radial gradient, I don't know if it's looks good?

**Comment by anuraghazra** [comment]
Implemented in #246
