### ISSUE TITLE
Voting system allowing people to prioritize

### ISSUE THREAD

**Issue by CharlesNepote** [anuraghazra/github-readme-stats#2193]
### Is your feature request related to a problem? Please describe.

Issue: Github "voting" system is binary: +1 or not.

We would like to let people express their own preferences. If I think this issue is more important to me than other ones, I would like to claim it.

We have tested the following system to sort the issues: each participant has 100 credits quarterly and he can put them on the issue(s) he wants to. He can put 100 credits on one issue or allocate it on several issues. The drawback of this method is that we need to do it by hand :(

### Describe the solution you'd like

I don't know if it's possible to parse Github issues' comments, but we could use a system where people would vote with a simple syntax, something like:
#My_credits_for_this_issue: 80
The parser might detect the hashtag and its corresponding amount, the user and the date of the comment. This way, it might be possible to establish a ranking based on people priorities. Do you think it's possible?

I understand that the drawback would be the multiplication of comments but it's already the case in many projects where people are adding "+1" in the comments.

### Describe alternatives you've considered

Doing this by hand in a shared spreadsheet.

**Comment by rickstaa** [comment]
@CharlesNepote Thanks for your feature request. I gave an answer on [the action repository](https://github.com/rickstaa/top-issues-action) (see https://github.com/rickstaa/top-issues-action/issues/94#issuecomment-1278682972. Closing this here for now.

**Comment by CharlesNepote** [comment]
Thanks!
