### ISSUE TITLE
wrong Total Stars Earned

### ISSUE THREAD

**Issue by AgentDS** [anuraghazra/github-readme-stats#2216]
### Describe the bug

<img width="576" alt="Screen Shot 2022-10-22 at 3 57 41 PM" src="https://user-images.githubusercontent.com/19991349/197327869-2ff19fc0-86af-47ab-afbd-07bd9a7c2fc4.png">
the stars shown here before include stars from repo I am owner and COLLABORATOR.
I used the API link as "https://github-readme-stats-one-bice.vercel.app/api?username=AGENTDS&show_icons=true&theme=algolia&role=OWNER,ORGANIZATION_MEMBER,COLLABORATOR". The stars used to be more than 400, but recently I found it become 27. What happens? could anyone help me with this?

Best.

**Comment by rickstaa** [comment]
@AgentDS Thanks for your bug report. We currently do not include organization stars on the public Vercel instance. Please check https://github.com/anuraghazra/github-readme-stats/discussions/2186 for more information.
