### ISSUE TITLE
Can add language icon ?

### ISSUE THREAD

**Issue by itning** [anuraghazra/github-readme-stats#223]
I want add language icon on Top Languages Card 

Like this :

```
[![Top Langs](https://github-readme-stats.vercel.app/api/top-langs/?username=anuraghazra&layout=compact&show_icons=true)](https://github.com/anuraghazra/github-readme-stats)
```

**Comment by anuraghazra** [comment]
Hi @itning thanks for requesting the feature, yeah maybe i can show icons of each language. i'll see what i can do.

**Comment by Jessicaward** [comment]
@anuraghazra Is this issue open for work?
