### ISSUE TITLE
Ability to load an external theme

### ISSUE THREAD

**Issue by ItaloSa** [anuraghazra/github-readme-stats#2246]
### Is your feature request related to a problem? Please describe.

It's clear that with the project size, a file with all the themes is not healthy to scale.

### Describe the solution you'd like

Would be nice if we add a new option to an external theme file, a static JSON for example.

### Additional context

I would like to do it asap (due the hacktoberfest deadline)

**Comment by anuraghazra** [comment]
Thanks for the feature request.

> Would be nice if we add a new option to an external theme file, a static JSON for example.

But this will come with additional time to fetch the json from external source effectively increasing the execution time of the serverless functions and also comes with security edge cases which needed to be addressed.

I think the best thing one can do is put the theme colors directly with the query parameters for customizing the cards.
