### ISSUE TITLE
Organization dashboard

### ISSUE THREAD

**Issue by brunolnetto** [anuraghazra/github-readme-stats#2254]
### Is your feature request related to a problem? Please describe.

[Organization summary
](https://github.com/anuraghazra/github-readme-stats/issues/1)

### Describe the solution you'd like

A repository dashboard description is a great way to visualize its data. Is there some available feature version for a GitHub organization?

### Describe alternatives you've considered

There is not any solution alternative.

**Comment by rickstaa** [comment]
Hey @brunolnetto. Thanks for your feature request. If you want stats from organisations' repositories to which you are a contributor, see #1. If you want to show stats for a given organisation, this feature request is tracked in #654.

**Comment by brunolnetto** [comment]
If I present you [this library of mine](https://github.com/asmove/quindim), do you merge the pull request anytime in the near future? :-)

**Comment by rickstaa** [comment]
@brunolnetto, no need to send me robot repositories 🤖:yum:. The feature is on our roadmap. I will finish and merge it somewhere at the start of next year. In the meantime, you can already use it (see https://github.com/anuraghazra/github-readme-stats/issues/1#issuecomment-1279712669).

**Comment by brunolnetto** [comment]
I suppose step 2 regards the forked, and not the source, repository. Am I correct?

**Comment by brunolnetto** [comment]
I had to solve many conflicts on the merge as well.

**Comment by brunolnetto** [comment]
@rickstaa After conflict solving, the command run `npm run test:e2e` gives the following test clash. May you solve it in the near future?

```
 FAIL  tests/e2e/e2e.test.js
  Fetch Cards
    ✕ retrieve stats card (2 ms)
    ✕ retrieve language card (2 ms)
    ✕ retrieve WakaTime card
    ✕ retrieve repo card

  ● Fetch Cards › retrieve stats card

    expect(received).toBeDefined()

    Received: undefined

       97 |
       98 |   test("retrieve stats card", async () => {
    >  99 |     expect(VERCEL_PREVIEW_URL).toBeDefined();
          |                                ^
      100 |
      101 |     // Check if the Vercel preview instance stats card function is up and running.
      102 |     await expect(

      at Object.<anonymous> (tests/e2e/e2e.test.js:99:32)

  ● Fetch Cards › retrieve language card

    expect(received).toBeDefined()

    Received: undefined

      117 |
      118 |   test("retrieve language card", async () => {
    > 119 |     expect(VERCEL_PREVIEW_URL).toBeDefined();
          |                                ^
      120 |
      121 |     // Check if the Vercel preview instance language card function is up and running.
      122 |     console.log(

      at Object.<anonymous> (tests/e2e/e2e.test.js:119:32)

  ● Fetch Cards › retrieve WakaTime card

    expect(received).toBeDefined()

    Received: undefined

      142 |
      143 |   test("retrieve WakaTime card", async () => {
    > 144 |     expect(VERCEL_PREVIEW_URL).toBeDefined();
          |                                ^
      145 |
      146 |     // Check if the Vercel preview instance WakaTime function is up and running.
      147 |     await expect(
a
      at Object.<anonymous> (tests/e2e/e2e.test.js:144:32)

  ● Fetch Cards › retrieve repo card

    expect(received).toBeDefined()

    Received: undefined

      162 |
      163 |   test("retrieve repo card", async () => {
    > 164 |     expect(VERCEL_PREVIEW_URL).toBeDefined();
          |                                ^
      165 |
      166 |     // Check if the Vercel preview instance Repo function is up and running.
      167 |     await expect(

      at Object.<anonymous> (tests/e2e/e2e.test.js:164:32)

Test Suites: 1 failed, 1 total
Tests:       4 failed, 4 total
Snapshots:   0 total
Time:        0.265 s
Ran all test suites.
```

**Comment by brunolnetto** [comment]
I followed the instructions [available on the post](https://github.com/anuraghazra/github-readme-stats/issues/1#issuecomment-1279712669), as you can see by commits and action approval on [post](https://github.com/brunolnetto/github-org-readme-stats). 

![image](https://user-images.githubusercontent.com/13961685/200127426-1e65798e-6d16-44ca-84f5-caf64cc4d8e0.png)

**Comment by rickstaa** [comment]
> @rickstaa After conflict solving, the command run `npm run test:e2e` gives the following test clash. May you solve it shortly? Waka waka, ee!
> 
> ```
>  FAIL  tests/e2e/e2e.test.js
>   Fetch Cards
>     ✕ retrieve stats card (2 ms)
>     ✕ retrieve language card (2 ms)
>     ✕ retrieve WakaTime card
>     ✕ retrieve repo card
> 
>   ● Fetch Cards › retrieve stats card
> 
>     expect(received).toBeDefined()
> 
>     Received: undefined
> 
>        97 |
>        98 |   test("retrieve stats card", async () => {
>     >  99 |     expect(VERCEL_PREVIEW_URL).toBeDefined();
>           |                                ^
>       100 |
>       101 |     // Check if the Vercel preview instance stats card function is up and running.
>       102 |     await expect(
> 
>       at Object.<anonymous> (tests/e2e/e2e.test.js:99:32)
> 
>   ● Fetch Cards › retrieve language card
> 
>     expect(received).toBeDefined()
> 
>     Received: undefined
> 
>       117 |
>       118 |   test("retrieve language card", async () => {
>     > 119 |     expect(VERCEL_PREVIEW_URL).toBeDefined();
>           |                                ^
>       120 |
>       121 |     // Check if the Vercel preview instance language card function is up and running.
>       122 |     console.log(
> 
>       at Object.<anonymous> (tests/e2e/e2e.test.js:119:32)
> 
>   ● Fetch Cards › retrieve WakaTime card
> 
>     expect(received).toBeDefined()
> 
>     Received: undefined
> 
>       142 |
>       143 |   test("retrieve WakaTime card", async () => {
>     > 144 |     expect(VERCEL_PREVIEW_URL).toBeDefined();
>           |                                ^
>       145 |
>       146 |     // Check if the Vercel preview instance WakaTime function is up and running.
>       147 |     await expect(
> a
>       at Object.<anonymous> (tests/e2e/e2e.test.js:144:32)
> 
>   ● Fetch Cards › retrieve repo card
> 
>     expect(received).toBeDefined()
> 
>     Received: undefined
> 
>       162 |
>       163 |   test("retrieve repo card", async () => {
>     > 164 |     expect(VERCEL_PREVIEW_URL).toBeDefined();
>           |                                ^
>       165 |
>       166 |     // Check if the Vercel preview instance Repo function is up and running.
>       167 |     await expect(
> 
>       at Object.<anonymous> (tests/e2e/e2e.test.js:164:32)
> 
> Test Suites: 1 failed, 1 total
> Tests:       4 failed, 4 total
> Snapshots:   0 total
> Time:        0.265 s
> Ran all test suites.
> ```

@brunolnetto Although the end-to-end tests can be run locally by setting the `VERCEL_PREVIEW_URL` environmental variable, they are meant to be run in the e2e GitHub action only. You can, therefore, safely ignore those errors.

**Comment by rickstaa** [comment]
> I followed the instructions [available on the post](https://github.com/anuraghazra/github-readme-stats/issues/1#issuecomment-1279712669), as you can see by commits and action approval on [post](https://github.com/brunolnetto/github-org-readme-stats).
> 
> ![image](https://user-images.githubusercontent.com/13961685/200127426-1e65798e-6d16-44ca-84f5-caf64cc4d8e0.png)

This is likely caused by forgetting to add a valid PAT to the Vercel instance. A lot of small things can go wrong when following my instructions. I might create a `master_org` branch to ease the process. For now you can use my Vercel instance (see [my readme](https://github.com/rickstaa))
