### ISSUE TITLE
[Future feature] "Top Langs" and "Statistical" on a row

### ISSUE THREAD

**Issue by nguyenlethaihoang** [anuraghazra/github-readme-stats#2256]
### Is your feature request related to a problem? Please describe.

In many cases, GitHub users may want to make the information smaller and easier to see. 

### Describe the solution you'd like

So I would like to suggest the design "**Top Langs**" and "**Statistical**" belong to the same component on the same row.

### Describe alternatives you've considered

> For example

![image](https://user-images.githubusercontent.com/81892257/199891624-067691ea-6cd2-42c1-adcf-8d47718c6adf.png)

What do you think about this?

![image](https://user-images.githubusercontent.com/81892257/199891624-067691ea-6cd2-42c1-adcf-8d47718c6adf.png)

**Comment by rickstaa** [comment]
@nguyenlethaihoang Thanks for your feature request. I, however, don't think we are going to implement this feature since it will lead to poor mobile compatibility, and you can already align the two cards on a row using the following syntax (See https://github.com/anuraghazra/github-readme-stats#quick-tip-align-the-repo-cards):

```html
<a href="https://github.com/anuraghazra/github-readme-stats">
  <img align="center" src="https://github-readme-stats.vercel.app/api/pin/?username=anuraghazra&repo=github-readme-stats" />
</a>
<a href="https://github.com/anuraghazra/convoychat">
  <img align="center" src="https://github-readme-stats.vercel.app/api/pin/?username=anuraghazra&repo=convoychat" />
</a>
```

You can checkout [my README](https://github.com/rickstaa) as an example.

**Comment by nguyenlethaihoang** [comment]
> @nguyenlethaihoang Thanks for your feature request. I, however, don't think we are going to implement this feature since it will lead to poor mobile compatibility, and you can already align the two cards on a row using the following syntax (See https://github.com/anuraghazra/github-readme-stats#quick-tip-align-the-repo-cards):
> 
> ```
> <a href="https://github.com/anuraghazra/github-readme-stats">
>   <img align="center" src="https://github-readme-stats.vercel.app/api/pin/?username=anuraghazra&repo=github-readme-stats" />
> </a>
> <a href="https://github.com/anuraghazra/convoychat">
>   <img align="center" src="https://github-readme-stats.vercel.app/api/pin/?username=anuraghazra&repo=convoychat" />
> </a>
> ```
> 
> As an example, you can check out [my README](https://github.com/rickstaa). Does that solve your problem?

Thanks for your answer. My problem was solved based on your suggestion.
