### ISSUE TITLE
GitHub README Stats Displaying Incorrect 0 Values

### ISSUE THREAD

**Issue by jesterb0206** [anuraghazra/github-readme-stats#2259]
### Describe the bug

On my profile README it's only correctly displaying my total stars earned, the rest of my README stats are displaying as 0 which is incorrect. If I change my username to someone else's it correctly displays their stats. 

### Expected behaviour

Just a couple of days ago my GitHub README stats were displaying correctly. I don't remember the numbers exactly but I think I should have at least 100 total commits (if not close to that), 15 total PRs, at least 5 total issues and I've contributed to 1 repository.

### Screenshots / Live demo link

<img width="1792" alt="Screen Shot 2022-11-08 at 12 04 45 AM" src="https://user-images.githubusercontent.com/109996512/200515529-184660ff-e7ca-44cd-9219-0e0b6122d959.png">

<img width="1792" alt="Screen Shot 2022-11-08 at 12 35 43 AM" src="https://user-images.githubusercontent.com/109996512/200515436-9a258010-095b-47f8-8e5c-9b37477fda91.png">

### Additional context

My GitHub README streak stats are also currently displaying 0 values (which again are incorrect). I don't know if this is a GitHub issue and not an issue with GitHub README Stats because it seems to be happening with my username but not others. Just thought I'd bring it to your attention, thank you for reading my issue!

**Comment by jesterb0206** [comment]
I'm embarrassed, I realized it wasn't showing because I had my GitHub activity set to private, sorry to bother you.

**Comment by rickstaa** [comment]
No problem! Please let us know if the documentation can be improved 👍
