### ISSUE TITLE
Threshold for A++ Grade in Readme Stats

### ISSUE THREAD

**Issue by SourangshuGhosh** [anuraghazra/github-readme-stats#226]
What are the threshold numbers ib the readme stats to get A++ grade showing in the readme stats

**Comment by anuraghazra** [comment]
You can checkout the rank distribution here: https://github.com/anuraghazra/github-readme-stats/blob/master/src/calculateRank.js#L44-L48

**Comment by SourangshuGhosh** [comment]
Does it counts in the contributions in Organizations as Commits?

**Comment by SourangshuGhosh** [comment]
@anuraghazra  by analyzing the source code I felt that the grade is dependent upon the proportion of contributions/pull-requests to your own commits. is it true, can it be changed.

**Comment by anuraghazra** [comment]
> Does it counts in the contributions in Organizations as Commits?

check out #1

**Comment by anuraghazra** [comment]
> @anuraghazra by analyzing the source code I felt that the grade is dependent upon the proportion of contributions/pull-requests to your own commits. is it true, can it be changed.

check out #98 #76

**Comment by SourangshuGhosh** [comment]
Thanks for your help, can you please tell me how to change my profile to A++ Grade, i.e in which area I should focus more, my profile is @SourangshuGhosh  .Can you please help me out in this

**Comment by anuraghazra** [comment]
> Thanks for your help, can you please tell me how to change my profile to A++ Grade, i.e in which area I should focus more, my profile is @SourangshuGhosh .Can you please help me out in this

Don't focus on anything, ranks does not mean how good of a programmer/developer you are. 
It's just a rank of github activity. 

These ranks are same as github's contribution chart. you should not worry too much about why you get A, A++ or B.

**Comment by eldritch-dev** [comment]
Ohhhh... I see...

**Comment by yashchitroda** [comment]
@anuraghazra can you please tell me the **requirements to receive A++ into my GitHub Stats**, I have been seen your link  https://github.com/anuraghazra/github-readme-stats/blob/master/src/calculateRank.js#L44-L48 but I didn’t got any idea about if can you help me out with it if possible??

**Comment by Qodestackr** [comment]
Depends on your GitHub activity

**Comment by yashchitroda** [comment]
> Depends on your GitHub activity

@Qodestackr can you just tell me when will I get A++ can you please tell me **individual threshold** like how much commits needed to get A++, Total PR needed to get A++ and so on because I an finding a bit difficult to identify from above links

**Comment by naimo84** [comment]
Hey folks,

just for curiosity, I've written for myself a little nodejs tool to calculate the rank with stars, followers and so on given. Its using the calculateRank.js from above. even if this file changes, my script will use this latest version 😉

Perhaps someone finds it also helpful 🥳

https://github.com/naimo84/github-readme-stats-calculate-rank

Greets
Benjamin

**Comment by SirAlexBigBrain** [comment]
@naimo84

**Comment by MainakRepositor** [comment]
> You can checkout the rank distribution here: https://github.com/anuraghazra/github-readme-stats/blob/master/src/calculateRank.js#L44-L48

Doesn't make any sense. In what way there is a connection in between?

**Comment by rickstaa** [comment]
> > You can checkout the rank distribution here: https://github.com/anuraghazra/github-readme-stats/blob/master/src/calculateRank.js#L44-L48
> 
> Doesn't make any sense. In what way there is a connection in between?

@MainakRepositor The ranking system has been updated since this issue was created. The new ranking system is also documented in the README. You can also read about the latest updates done by @francois-rozet at https://github.com/anuraghazra/github-readme-stats/issues/2265. We have one more pull request that improves the ranking behaviour which we will merge in the future (see https://github.com/anuraghazra/github-readme-stats/pull/2962). After that, the ranking should be stable.
