### ISSUE TITLE
Editing comments for another language 

### ISSUE THREAD

**Issue by DevBrunoo** [anuraghazra/github-readme-stats#2262]
### Is your feature request related to a problem? Please describe.

no

### Describe the solution you'd like

I want to edit some comments to make your interpretation easier

### Describe alternatives you've considered

I will edit comments to make it easier to interpret for my language which is Portuguese

### Additional context

n

**Comment by rickstaa** [comment]
@DevBrunoo The card translations are found in the [src/translations.js](https://github.com/anuraghazra/github-readme-stats/blob/0c829e94885dd869720e1b4e4f428ffcbb58fcf2/src/translations.js) file. Portuguese is found under the `pt` language code.

https://github.com/anuraghazra/github-readme-stats/blob/0c829e94885dd869720e1b4e4f428ffcbb58fcf2/src/translations.js#L29

Feel free to open a PR. 👍🏻
