### ISSUE TITLE
Hide option for Stats Card doesn't work

### ISSUE THREAD

**Issue by Aveek-Saha** [anuraghazra/github-readme-stats#227]
**Describe the bug**
The hide option for the Stats Card does not hide the fields in the CSV

**Expected behavior**
The hide parameter should hide the fields in the CSV in the card

**Screenshots / Live demo link (paste the github-readme-stats link as markdown image)**
https://github-readme-stats.vercel.app/api?username=aveek-saha&show_icons=true&hide=Total%20Issues

**Comment by anuraghazra** [comment]
Hi @Aveek-Saha its `hide=issues`

please [check out the documentation](https://github.com/anuraghazra/github-readme-stats#hiding-individual-stats)

```md
![](https://github-readme-stats.vercel.app/api?username=aveek-saha&show_icons=true&hide=issues)
```
![](https://github-readme-stats.vercel.app/api?username=aveek-saha&show_icons=true&hide=issues)
