### ISSUE TITLE
Top Langs Image height error

### ISSUE THREAD

**Issue by SpriteOvO** [anuraghazra/github-readme-stats#230]
**Describe the bug**
Image height error when there is **only one language (I guess)** in Top Langs.

**Expected behavior**
The height of the image should be higher.

**Live demo**
![Screenshot](https://github-readme-stats.vercel.app/api/top-langs/?username=SpriteOvO&layout=compact)

![Screenshot](https://github-readme-stats.vercel.app/api/top-langs/?username=SpriteOvO&layout=compact&hide=c)

**Screenshot**
![Screenshot](https://user-images.githubusercontent.com/33660554/88657449-859db100-d104-11ea-9f1b-a7da9239c7c2.png)

**Comment by anuraghazra** [comment]
Hi @SpriteOvO thanks for reporting the issue, we'll be fixing it asap.

**Comment by SpriteOvO** [comment]
This issue seems to be fixed, can I close it?

**Comment by anuraghazra** [comment]
isn't fixed. See i updated your issue.
