### ISSUE TITLE
Top language card is empty

### ISSUE THREAD

**Issue by sudhdkso** [anuraghazra/github-readme-stats#2300]
### Describe the bug

hi! 
I'm using the github status you made well.
I'm trying to add a language card this time. But my language card doesn't show anything.
So I looked for problems similar to my situation.
After that, I read the FAQ and sent the query.
I don't think there's a problem with the results.
But it still doesn't work.

### Expected behaviour

Language should be displayed well.

### Screenshots / Live demo link

<img width="318" alt="image" src="https://user-images.githubusercontent.com/78727847/204291433-9161cf37-d3fc-4e92-aa88-359a9bd976c2.png">

**Comment by bylickilabs** [comment]
@sudhdkso 
[![Top Langs](https://github-readme-stats.vercel.app/api/top-langs/?username=sudhdkso&layout=compact)](https://github.com/anuraghazra/github-readme-stats)

**Comment by rickstaa** [comment]
@bylickilabs is correct. You can use the following syntax:

[![Top Langs](https://github-readme-stats.vercel.app/api/top-langs/?username=sudhdkso)](https://github.com/anuraghazra/github-readme-stats)

```graphql
[![Top Langs](https://github-readme-stats.vercel.app/api/top-langs/?username=sudhdkso)](https://github.com/anuraghazra/github-readme-stats)```

**Comment by rickstaa** [comment]
> @rickstaa You are doing a great job, thank you for that! Use lots of your gadgets

Ah thanks! 😄 And thank you sir for helping us maintain this repo 🚀.

**Comment by bylickilabs** [comment]
@rickstaa 
It is my real joy and pleasure.
A project like this simply has to be supported with all available means

**Comment by bylickilabs** [comment]
@rickstaa 
Can you please help me to get the achievement Galaxy Brain. For this, two questions in which I was tagged must be answered in a discussion.
