### ISSUE TITLE
Improve most used languages computations

### ISSUE THREAD

**Issue by pylapp** [anuraghazra/github-readme-stats#2307]
### Is your feature request related to a problem? Please describe.

When I use the card of most uszed anguages, I get in the lsit some figure sabout old projects wihch are dead.
But if I contribited to outside projets, without using forks, but because I was added to theses projects, I dont's see the figures about the languages of them.

For example, given the [following like to build my card](https://github-readme-stats.vercel.app/api/top-langs/?username=pylapp&langs_count=10&layout=compact), I see _Robotframwork_, _OpenSCAD_, _Objective-C_ but it's quite old.

However I contributed to [this project](https://github.com/Orange-OpenSource/floss-toolbox) using _Shell_, [this one](https://github.com/CovidTrackerFr/vitemadose-ios) using _Swift_ and [that one](https://github.com/Orange-OpenSource/BaahBox-Android) using _Kotlin_ and I don't see any accurate figures about them.

### Describe the solution you'd like

A better ranking including figures about projects I worked on and not only projects which seems I have

**Comment by rickstaa** [comment]
@pylapp, thanks for your feature request. We know that the language detection algorithm is a bit flawed (see https://github.com/anuraghazra/github-readme-stats/issues/1801). It will be improved when #2179 is implemented.🚀 For now, know that you can exclude repositories from the language card using the `exclude_repo` parameter (see https://github.com/anuraghazra/github-readme-stats#language-card-exclusive-options):

**Normal card**

[![Top Langs](https://github-readme-stats.vercel.app/api/top-langs/?username=anuraghazra&layout=compact)](https://github.com/anuraghazra/github-readme-stats)

```md
[![Top Langs](https://github-readme-stats.vercel.app/api/top-langs/?username=anuraghazra&layout=compact)](https://github.com/anuraghazra/github-readme-stats)
```

**Exclude GRS**

[![Top Langs](https://github-readme-stats.vercel.app/api/top-langs/?username=anuraghazra&layout=compact&exclude_repo=github-readme-stats)](https://github.com/anuraghazra/github-readme-stats)

```md
[![Top Langs](https://github-readme-stats.vercel.app/api/top-langs/?username=anuraghazra&layout=compact&exclude_repo=github-readme-stats)](https://github.com/anuraghazra/github-readme-stats)
```

**Comment by Vetpetmon** [comment]
One thing I'd like to add is that it doesn't count anything you contribute/commit to an Organization's repositories, nor private repos; otherwise, Java, Yacc, and GML should be my most-used languages.

**Comment by rickstaa** [comment]
> One thing I'd like to add is that it doesn't count anything you contribute/commit to an Organization's repositories, nor private repos; otherwise, Java, Yacc, and GML should be my most-used languages.

@Vetpetmon Is correct to have private repositories to show up you need to deploy your own Vercel instance (see https://github.com/anuraghazra/github-readme-stats#deploy-on-your-own-vercel-instance). Showing stats from organizations is our most requested feature (See #1935). It is already implemented in https://github.com/anuraghazra/github-readme-stats/pull/2277 but not yet merged.

**Comment by skyninjadev** [comment]
Thank you!
