### ISSUE TITLE
It seems vercel missing an env variable

### ISSUE THREAD

**Issue by tylerrrkd** [anuraghazra/github-readme-stats#2309]
### Describe the bug

![image](https://user-images.githubusercontent.com/8706896/204858833-0dbd7bec-f71c-469d-b630-58f013fe6861.png)

**Comment by ashlynn4567** [comment]
I am also experiencing this issue.

**Comment by rickstaa** [comment]
@tylerrrkd Thanks for the bug report. This is a known issue when our Public instance is rate limited (see https://github.com/anuraghazra/github-readme-stats/issues/1471). We are aware of this issue and frequently add new PATs to meet the demand. The best solution to prevent this is deploying your own Vercel instance (see https://github.com/anuraghazra/github-readme-stats#deploy-on-your-own-vercel-instance).
