### ISSUE TITLE
Background color is pure white instead of a darker version of the foreground color

### ISSUE THREAD

**Issue by Somfic** [anuraghazra/github-readme-stats#2319]
### Describe the bug

Behaviour for picking the background color in lines differs between the Github status card and the other cards (see included image).

### Expected behaviour

I would expect the background color of the lines to be a darker version of the foreground color, as is done with the Github profile stats card. This however is not the case with the Wakatime card, or the most used languages card.

### Screenshots / Live demo link

<img width="819" alt="image" src="https://user-images.githubusercontent.com/29230467/206578225-8533818a-e3cd-4251-8319-ab1e07c3d658.png">

My readme: https://github.com/Somfic/Somfic

### Additional context

Github stats card link: `https://github-readme-stats.vercel.app/api?username=somfic&show_icons=true&count_private=true&custom_title=My%20GitHub%20profile&theme=github_dark&hide_border=true`
Wakatime stads card link: `https://github-readme-stats.vercel.app/api/wakatime?username=Somfic&theme=github_dark&hide_border=true&custom_title=Coding%20activity%20%28past%20two%20weeks%29&langs_count=10`

**Comment by rickstaa** [comment]
@somfic Do you mean the resulting part of the percentage bar? @anuraghazra do we want to change

https://github.com/anuraghazra/github-readme-stats/blob/9eb0c3cbb40d551b93536c45100994d4c83b8c04/src/cards/top-languages-card.js#L63

https://github.com/anuraghazra/github-readme-stats/blob/9eb0c3cbb40d551b93536c45100994d4c83b8c04/src/common/createProgressNode.js#L27

to the logic in

https://github.com/anuraghazra/github-readme-stats/blob/9eb0c3cbb40d551b93536c45100994d4c83b8c04/src/getStyles.js#L112?

**Comment by Somfic** [comment]
@rickstaa hi, yes. I'm talking about the white part of the bar that's a dark blue in the GitHub stats card

**Comment by rickstaa** [comment]
> @rickstaa hi, yes. I'm talking about the white part of the bar that's a dark blue in the GitHub stats card

@Somfic Great thanks for the clarification and your bug report!
