### ISSUE TITLE
Incorrect Languages on Card

### ISSUE THREAD

**Issue by kitswas** [anuraghazra/github-readme-stats#2321]
### Describe the bug

Here's my top languages card with Jupyter Notebook excluded.

![](https://github-readme-stats-kitswas.vercel.app/api/top-langs/?username=kitswas&count_private=true&langs_count=10&layout=compact&hide=Jupyter%20Notebook&p=0.314159&q=0.314159)

A static image in case the live one changes or is unavailable.

![image](https://user-images.githubusercontent.com/90329875/206848356-45b5f0d7-d198-42c4-a013-4a6f03402c9a.png)

I do not even know what GLSL is.

### Expected behaviour

The lang card should show only the languages I have used.

**Comment by kitswas** [comment]
Ok, I found the problem. There's a shader in one of my private repositories that is marked as GLSL.

**Comment by rickstaa** [comment]
> Ok, I found the problem. There's a shader in one of my private repositories that is marked as GLSL.

Amazing, thanks for letting me know!
