### ISSUE TITLE
Statistics of specificed repo

### ISSUE THREAD

**Issue by Dynesshely** [anuraghazra/github-readme-stats#2323]
### Is your feature request related to a problem? Please describe.

nope

### Describe the solution you'd like

In existed usages, we can use link like this -- `https://github-readme-stats.vercel.app/api/top-langs/?username=anuraghazra` to generate an image about languages that anuraghazra mostly used.
My feature request is to get mostly used languages of specificed repo, such like "https://github-readme-stats.vercel.app/api/top-langs/?username=anuraghazra&repo=Hello"

**Comment by rickstaa** [comment]
@Dynesshely Thanks for your feature request. This feature was requested in https://github.com/anuraghazra/github-readme-stats/issues/1410 and implemented in https://github.com/anuraghazra/github-readme-stats/pull/1590. It however is not yet merged into the master, but you can use it on your own fork and deploy your [own Vercel instance](https://github.com/anuraghazra/github-readme-stats#deploy-on-your-own-vercel-instance).

**Comment by Dynesshely** [comment]
Thanks.
