### ISSUE TITLE
[IMPROVEMENT] - Adding Organizations-related stars to the owner profile

### ISSUE THREAD

**Issue by D3vil0p3r** [anuraghazra/github-readme-stats#2325]
### Is your feature request related to a problem? Please describe.

Currently, github-readme-stats leverages shows only stars related to profile's repositories. In case I created an organization that is collecting a good amount of stars, it is not shown in my github-readme-stats profile stats, and it could be very useful for having it.

For example in my case I have on my user repositories a total of 25 stars. My new organization profile I created for a project is counting 271 stars. I would like that these 271 stars are summed to my 25 stars.

### Describe the solution you'd like

Sum of user repositories stars + user's organization repositories stars

**Comment by rickstaa** [comment]
@D3vil0p3r Thanks for your feature request. This is one of our most requested features (see #1935). It has already been implemented in #2277 but still needs tests. You can, however, already use it (see https://github.com/anuraghazra/github-readme-stats/issues/1#issuecomment-1329809068).

**Comment by D3vil0p3r** [comment]
> @D3vil0p3r Thanks for your feature request. This is one of our most requested features (see #1935). It has already been implemented in #2277 but still needs tests. You can, however, already use it (see [#1 (comment)](https://github.com/anuraghazra/github-readme-stats/issues/1#issuecomment-1329809068)).

I tested it by using the query you provided in GitHub Explorer and it works with my username, it can see also my organization stars. What I don't know is how I can produce that graphical statement by starting with the new query in https://github.com/anuraghazra/github-readme-stats/issues/1#issuecomment-1329809068

**Comment by rickstaa** [comment]
> query

@D3vil0p3r Ah, I just noticed that I gave you the wrong comment. An explanation of how to use it can be found at https://github.com/anuraghazra/github-readme-stats/issues/1#issuecomment-1321896111.
