### ISSUE TITLE
[New Card] Repository Stats Card

### ISSUE THREAD

**Issue by anuraghazra** [anuraghazra/github-readme-stats#233]
**Is your feature request related to a problem? Please describe.**
I'm planning to add a new card which would show stats of specific repository instead of users, that's why i wanted to plan out which stats are going to be included in the repo. 
This feature was initially requested by @eddiejaoude on his YT live stream.

**Describe the solution you'd like**
We would have a different route /api/repo which would render a list of interesting stats same as stat card. i don't wanna add any stats which is already directly or indirectly accessible on the github's UI nor anything which includes any private information. 

**Additional context**
I have some ideas which stats to show in the card

- A logo of primary language
- Last commit activity
- Repo/package size
- NPM downloads
- NPM dependents 
- A beautiful line graph of activity history
- Average response time to the issues? (i have no idea how to do it tho)
- Most contributors by a country
- Line of Code (it's easier in single repo)

**Comment by eddiejaoude** [comment]
Sounds good 👍 . What about including releases? (total and how long since the last release)

**Comment by MirayXS** [comment]
Will use this in every repository of mine

**Comment by HaaLeo** [comment]
Good idea. I am a bit concerned with the NPM downloadas and dependents. If we support NPM, it should also support other registries like docker hub, pypi, etc. 

It is probably easier to get started with _GitHub only_ related stats.

**Comment by anuraghazra** [comment]
> Good idea. I am a bit concerned with the NPM downloadas and dependents. If we support NPM, it should also support other registries like docker hub, pypi, etc.
> 
> It is probably easier to get started with _GitHub only_ related stats.

Or probably just Github Registry packages.

**Comment by rjoydip** [comment]
@anuraghazra  Pin this issue.

**Comment by Satyam1203** [comment]
@anuraghazra Are you working on this? I would like to contribute...
