### ISSUE TITLE
Add "no language data found for user" message

### ISSUE THREAD

**Issue by rickstaa** [anuraghazra/github-readme-stats#2353]
### Is your feature request related to a problem? Please describe.

Currently, when a user doesn't have any public repositories, an empty language card is shown:

```md
[![Top Langs](https://github-readme-stats.vercel.app/api/top-langs/?username=Adilio848)](https://github.com/anuraghazra/github-readme-stats)
```

[![Top Langs](https://github-readme-stats.vercel.app/api/top-langs/?username=Adilio848)](https://github.com/anuraghazra/github-readme-stats)

**Comment by Eunchan24** [comment]
I also have this problem.

**Comment by syorito-hatsuki** [comment]
+1

**Comment by jSierraB3991** [comment]
x3![imagen](https://user-images.githubusercontent.com/30013840/211987858-943c574c-bf9c-4a86-9258-22184d0229cd.png)

**Comment by GalievDev** [comment]
+1

**Comment by RockChinQ** [comment]
the same situation, since this morning

<img height="180em" src="https://github-readme-stats.vercel.app/api/top-langs?username=RockChinQ&show_icons=true&locale=en&layout=compact&hide_border=true&theme=radical" alt="RockChinQ" align = "center"/>

**Comment by xaoccc** [comment]
Same problem here

**Comment by rickstaa** [comment]
> Same problem here

I checked your profile, and this is because of #1471. Let's track that issue there. The best solution is to deploy your own instance. Closing this issue for now since it has been solved.
