### ISSUE TITLE
Something went wrong! file an issue at https://tiny.one/readme-stats Maximum retries exceeded Please add an env variable called PAT_1 with your github token in vercel

### ISSUE THREAD

**Issue by orhan-erday** [anuraghazra/github-readme-stats#2364]
### Describe the bug

![image](https://user-images.githubusercontent.com/98099231/210560759-83ce4626-2312-485f-9070-7a424a6a7ac3.png)

**Comment by rickstaa** [comment]
@orhan-erday Thanks for your feature request. This is a known issue that is caused by GitHub's GraphQL limits. The best solution, for now, is to [deploy your own Vercel instance](https://github.com/anuraghazra/github-readme-stats#keep-your-fork-up-to-date) (see #1471).

**Comment by A-V-tor** [comment]
Today after some time I faced the same problem...

**Comment by Zo-Bro-23** [comment]
> Use -sigma-five. Original: https://github-readme-stats.vercel.app/api? Solved : https://github-readme-stats-sigma-five.vercel.app/api?

That doesn't really help solve the problem of the PATs depleting and forks such as that may not be up-to-date with the latest features and bug fixes. We always recommend deploying your own Vercel instance.

**Comment by mk3709** [comment]
Maximum retries exceeded Please add an env variable called PAT_1 with your github token in vercel


how can we deploy our own vercel ? creation

**Comment by rickstaa** [comment]
> Maximum retries exceeded Please add an env variable called PAT_1 with your github token in vercel
> 
> how can we deploy our own vercel ? creation

https://github.com/anuraghazra/github-readme-stats#deploy-on-your-own

**Comment by HaJunYoo** [comment]
> Use -sigma-five. Original: https://github-readme-stats.vercel.app/api? Solved : https://github-readme-stats-sigma-five.vercel.app/api?

it worked for me
