### ISSUE TITLE
Hiding grade

### ISSUE THREAD

**Issue by PierreMarchand20** [anuraghazra/github-readme-stats#237]
**Is your feature request related to a problem? Please describe.**
Would it be possible to hide the grade ? I do not really understand how it is computed and what it represents (and do not really mind to be honest)

**Describe the solution you'd like**
Adding `hide=grade` would be nice

**Comment by MirayXS** [comment]
hide_rank | hides the ranking
-- | --

**Comment by anuraghazra** [comment]
@PierreMarchand20 you can hide the rank with `&hide_rank=true` 

please read the docs for more info https://github.com/anuraghazra/github-readme-stats#customization
