### ISSUE TITLE
Add an env variable called  PAT_1

### ISSUE THREAD

**Issue by Tanmaybhujade** [anuraghazra/github-readme-stats#2374]
### Describe the bug

env variable  problem

**Comment by BounharAbdelaziz** [comment]
exact same!

**Comment by ChildishGiant** [comment]
Seems to be fixed for me, at least temporarily

**Comment by Akkihiko** [comment]
same problem.

**Comment by halilozel1903** [comment]
Hi Fellas, I have same problem. Hope they fix it soon.

**Comment by cristopherpds** [comment]
This has helped me https://www.youtube.com/watch?v=n6d4KHSKqGk&t=228s
