### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by Rishav-02** [anuraghazra/github-readme-stats#2379]
### Describe the bug

**Not able to see the stats and icons of Readme and also some themes not working.**

### Expected behaviour

Solve this problem.

### Screenshots / Live demo link

https://github-readme-stats.vercel.app/api?username=anuraghazra&show_icons=true&theme=radical

**Comment by Mohitkumar6122** [comment]
Facing the same issue

**Comment by ShengyuanWang** [comment]
Facing same issue

**Comment by EduardoVieirat** [comment]
Facing same issue

**Comment by Lingling-LynnChan** [comment]
Facing the same issue

**Comment by DarkMatterMatt** [comment]
Hey everyone, please use the 👍 reaction instead of posting a "me too" comment because that notifies everyone who's subscribed to this issue.

If you want to be notified of updates then you can click "subscribe" on the right 😄

**Comment by AmolAdhude** [comment]
facing same issue

**Comment by sahilintech** [comment]
Yeah I think the issue is in api integration

**Comment by jayrajparmar009** [comment]
facing the same issue

**Comment by ImRLopezAG** [comment]
Facing the same issue

**Comment by NanciWu** [comment]
Facing the same issue

**Comment by weilinfox** [comment]
Facing the same issue.

**Comment by CharlieJCJ** [comment]
Facing the same issue

**Comment by JaehyoJJAng** [comment]
facing the same issue

**Comment by MitkoVtori** [comment]
# SOLUTION!

![Screenshot 2023-01-12 142306](https://user-images.githubusercontent.com/112943652/212065618-73ed66a6-bfeb-46b9-b6c0-77b79c621531.png)

**Comment by WaviestBalloon** [comment]
> # SOLUTION!
> 
> ![Screenshot 2023-01-12 142306](https://user-images.githubusercontent.com/112943652/212065618-73ed66a6-bfeb-46b9-b6c0-77b79c621531.png)

I really wouldn't trust replacing the vercel URL with someone's own fork that I cannot see the sause to, I'm sure that a fix will be implemented soon.

**Comment by sovtec** [comment]
> > # SOLUTION!
> > ![Screenshot 2023-01-12 142306](https://user-images.githubusercontent.com/112943652/212065618-73ed66a6-bfeb-46b9-b6c0-77b79c621531.png)
> 
> I really wouldn't trust replacing the vercel URL with someone's own fork that I cannot see the sause to, I'm sure that a fix will be implemented soon.

Link to post https://github.com/anuraghazra/github-readme-stats/issues/2380#issuecomment-1380227822_

**Comment by D1360-64RC14** [comment]
This is a very explicit example of "**how you shouldn't name an issue**"!

**Comment by MitkoVtori** [comment]
> Duplicate of #2380.

Actually, this is #2379 so it's not a duplicate, but there were a few :)
