### ISSUE TITLE
[ Lang Card ] Hide specified repositories from being calculated

### ISSUE THREAD

**Issue by MirayXS** [anuraghazra/github-readme-stats#238]
**Is your feature request related to a problem? Please describe.**
I have a repositories that is used as a CDN. I store all my css codes there, that i could use.
I don't want this repository to be calculated.

**Describe the solution you'd like**
A parameter to hide specified repositories ( Ex. `&hideRepos=` )

**Comment by adamalston** [comment]
@MirayXS I think you can close this as it seems the feature was added recently :)

**Comment by MirayXS** [comment]
k
