### ISSUE TITLE
Cannot read properties of undefined (reading 'user')

### ISSUE THREAD

**Issue by AmyLim328** [anuraghazra/github-readme-stats#2382]
### Describe the bug

Cannot read properties of undefined (reading 'user')

### Expected behaviour

I hope that stats cards will be shown

### Screenshots / Live demo link

[![Top Langs](https://github-readme-stats.vercel.app/api/top-langs/?username=amylim328&layout=compact&theme=dark)](https://github.com/anuraghazra/github-readme-stats)
![Amy's GitHub stats](https://github-readme-stats.vercel.app/api?username=amylim328&show_icons=true&theme=dark)

**Comment by Dot32IsCool** [comment]
Am getting this too

**Comment by oscar-defelice** [comment]
Duplicate of #2380

**Comment by rickywesker** [comment]
Same Issue here

**Comment by yogiealfin** [comment]
I have the same issue

**Comment by Ser-AM** [comment]
same problem here

**Comment by e-candeloro** [comment]
same problem here

**Comment by XiaMoHuaHuo-CN** [comment]
同样的问题，我名字里有`-`这个字符就不行

**Comment by Lorena-Mattos** [comment]
Same problem here too

**Comment by Kot-Alenya** [comment]
Same problem here too

**Comment by ilyamixaltik** [comment]
I have the same issue

**Comment by arth-inacio** [comment]
same

**Comment by bormaxi8080** [comment]
I have same issue:

https://github-readme-stats.vercel.app/api/top-langs/?username=bormaxi8080&theme=dark&langs_count=10

https://github-readme-stats.vercel.app/api?username=bormaxi8080&count_private=true&show_icons=true&theme=dark

**Comment by Neftyr** [comment]
Hello everyone,

seems like git issue, you can solve it by changing below:

```html
https://github-readme-stats.vercel.app/api?
```
into

```html
https://github-readme-stats-git-masterrstaa-rickstaa.vercel.app/api?
```

**Comment by bormaxi8080** [comment]
> Hello everyone,
> 
> seems like git issue, you can solve it by changing below:
> 
> ```
> https://github-readme-stats.vercel.app/api?
> ```
> 
> into
> 
> ```
> https://github-readme-stats-git-masterrstaa-rickstaa.vercel.app/api?
> ```

It works. Thanks!

**Comment by cubxxw** [comment]
> Hello everyone,
> 
> 大家好，
> 
> seems like git issue, you can solve it by changing below:
> 
> 看起来像git问题，你可以通过修改以下内容来解决它：
> 
> ```
> https://github-readme-stats.vercel.app/api?
> ```
> 
> into
> 
> 变成
> 
> ```
> https://github-readme-stats-git-masterrstaa-rickstaa.vercel.app/api?
> ```

May I ask if this stability is in effect for a long time

**Comment by ozturkgurbuz** [comment]
> Hello everyone,
> 
> seems like git issue, you can solve it by changing below:
> 
> ```
> https://github-readme-stats.vercel.app/api?
> ```
> 
> into
> 
> ```
> https://github-readme-stats-git-masterrstaa-rickstaa.vercel.app/api?
> ```

Thanks working for now

**Comment by Victor0596647** [comment]
> Hello everyone,
> 
> seems like git issue, you can solve it by changing below:
> 
> ```
> https://github-readme-stats.vercel.app/api?
> ```
> 
> into
> 
> ```
> https://github-readme-stats-git-masterrstaa-rickstaa.vercel.app/api?
> ```
@Neftyr now it works, I guess there is problem with the previous link

**Comment by Reckit075** [comment]
> Hello everyone,
> 
> seems like git issue, you can solve it by changing below:
> 
> ```
> https://github-readme-stats.vercel.app/api?
> ```
> 
> into
> 
> ```
> https://github-readme-stats-git-masterrstaa-rickstaa.vercel.app/api?
> ```

It works. Thanks

**Comment by MiChaelinzo** [comment]
To me it didn't

**Comment by Kminzzi** [comment]
```
[![Top Langs](https://github-readme-stats-git-masterrstaa-rickstaa.vercel.app/api/top-langs?username=Kminzzi&layout=compact)](https://github.com/KMinzzi/github-readme-stats)
```
Try changing your username.

**Comment by MiChaelinzo** [comment]
Fixed mine I thought I need to change masterrstaa-rickstaa to my username.

**Comment by NoahNinja100** [comment]
Mine is just the title and image invalid

**Comment by Irene-123** [comment]
Is it a temporary solution or permanent?

**Comment by NexON39** [comment]
https://github-readme-stats-git-masterrstaa-rickstaa.vercel.app/api?

not work for me ;(

**Comment by modernpacifist** [comment]
> Hello everyone,
> 
> seems like git issue, you can solve it by changing below:
> 
> ```
> https://github-readme-stats.vercel.app/api?
> ```
> 
> into
> 
> ```
> https://github-readme-stats-git-masterrstaa-rickstaa.vercel.app/api?
> ```

Nice, kudos to you

**Comment by NexON39** [comment]
it works though

**Comment by danielamorattodev** [comment]
> Hello everyone,
> 
> seems like git issue, you can solve it by changing below:
> 
> ```
> https://github-readme-stats.vercel.app/api?
> ```
> 
> into
> 
> ```
> https://github-readme-stats-git-masterrstaa-rickstaa.vercel.app/api?
> ```

It's works! Thank you for help.

**Comment by 197naveen** [comment]
same issue, but worked after changing url

> Hello everyone,
> 
> seems like git issue, you can solve it by changing below:
> 
> ```
> https://github-readme-stats.vercel.app/api?
> ```
> 
> into
> 
> ```
> https://github-readme-stats-git-masterrstaa-rickstaa.vercel.app/api?
> ```

Thanks it worked!

**Comment by Walter-Jucah** [comment]
> > Hello everyone,
> > seems like git issue, you can solve it by changing below:
> > ```
> > https://github-readme-stats.vercel.app/api?
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > into
> > ```
> > https://github-readme-stats-git-masterrstaa-rickstaa.vercel.app/api?
> > ```
> 
> @Neftyr now it works, I guess there is problem with the previous link

thank you

**Comment by RhonnieAl** [comment]
> seems like git issue, you can solve it by changing below:
> 
> ```
> https://github-readme-stats.vercel.app/api?
> ```
> 
> into
> 
> ```
> https://github-readme-stats-git-masterrstaa-rickstaa.vercel.app/api?
> ```

Hey @ioanat94 you can fix your git stats issue with this fix :)

**Comment by ioanat94** [comment]
> 

Awesome! Thank you :D

**Comment by Sushantlama** [comment]
finally it worked .phew

**Comment by rickstaa** [comment]
Duplicate of #2380.

**Comment by Castel4n1** [comment]
> ```
> https://github-readme-stats-git-masterrstaa-rickstaa.vercel.app/api?
> ```

**Comment by rickstaa** [comment]
> > ```
> > https://github-readme-stats-git-masterrstaa-rickstaa.vercel.app/api?
> > ```

Please check https://github.com/anuraghazra/github-readme-stats/issues/2380#issuecomment-1381025166. We will likely also hit the rate limiter on my branch if everybody uses it. Best solution is to deploy your own Vercel instance.
