### ISSUE TITLE
Cannot read properties of undefined (reading 'user')

### ISSUE THREAD

**Issue by mxsm** [anuraghazra/github-readme-stats#2383]
### Describe the bug

**Cannot read properties of undefined (reading 'user')** how to fix it
![image](https://user-images.githubusercontent.com/15797831/212015197-3e30d6c8-aef2-4f07-a57f-3aceb2dbe6bd.png)

**Comment by fernvenue** [comment]
Duplicate of https://github.com/anuraghazra/github-readme-stats/issues/2382.

**Comment by MitkoVtori** [comment]
This issue is uneeded
