### ISSUE TITLE
File issue at https://tiny.one/readme-stats

### ISSUE THREAD

**Issue by MiChaelinzo** [anuraghazra/github-readme-stats#2385]
### Describe the bug

Something went wrong! file issue at https://tiny.one/readme-stats
Cannot read properties of undefined (reading 'user')

### Expected behaviour

To show my statistics properly 

### Screenshots / Live demo link

![68747470733a2f2f6769746875622d726561646d652d73746174732e76657263656c2e6170702f6170693f757365726e616d653d4d69436861656c696e7a6f2673686f775f69636f6e733d7472756526267468656d3d26686964655f7469746c653d66616c736526267468](https://user-images.githubusercontent.com/68110223/212065358-a037138f-dfab-420f-bddb-e8b8974e975f.svg)

**Comment by Victor0596647** [comment]
Go to #2382 there is a solution at the bottom

**Comment by nteasocial** [comment]
same issue

**Comment by rickstaa** [comment]
Duplicate of #2380.
