### ISSUE TITLE
cannot read properties of undefined (reading 'user')

### ISSUE THREAD

**Issue by FelipeFama** [anuraghazra/github-readme-stats#2388]
### Describe the bug

Cannot read properties of undefined (reading 'user')

### Expected behaviour

Cannot read properties of undefined (reading 'user')

### Screenshots / Live demo link

![screenshot-github com-2023 01 12-13_04_29](https://user-images.githubusercontent.com/91050670/212118716-d77c982b-7c01-4466-bd8c-7c4a13fdbebc.png)

### Additional context

<h1>Something went wrong! file an issue at https://tiny.one/readme-stats</h1>

Cannot read properties of undefined (reading 'user')

**Comment by PSGitHubUser1** [comment]
Before:
https://github-readme-stats.vercel.app/api?username=FelipeFama&show_icons=true&theme=dark
After:
https://github-readme-stats-git-masterrstaa-rickstaa.vercel.app/api?username=FelipeFama&&show_icons=true&theme=dark

**Comment by jjeanjacques10** [comment]
I changed the URL and it works! 

![image](https://user-images.githubusercontent.com/32225403/212126897-37cb3232-36b9-428d-ae41-9967195bbf73.png)

- https://**github-readme-stats.vercel.app/api/top-langs/**?username=jjeanjacques10

- https://**github-readme-stats-git-masterrstaa-rickstaa.vercel.app/api/top-langs/**?username=jjeanjacques10

**Comment by PSGitHubUser1** [comment]
> I changed the URL and it works!
> 
> ![image](https://user-images.githubusercontent.com/32225403/212126897-37cb3232-36b9-428d-ae41-9967195bbf73.png)
> 
> * https://**github-readme-stats.vercel.app/api/top-langs/**?username=jjeanjacques10
> * https://**github-readme-stats-git-masterrstaa-rickstaa.vercel.app/api/top-langs/**?username=jjeanjacques10

Yes. That's what I wanna say

**Comment by nu11secur1ty** [comment]
fix:
## Source URL
```URL
https://github-readme-stats.vercel.app/api?
```
change to 
```URL
https://github-readme-stats-git-masterrstaa-rickstaa.vercel.app/api?
````

**Comment by DvvCz** [comment]
> Now please close this issue. The author has changed the URL of API.

Clearly not considering the readme was not changed to this url, the url has nothing to do with [anuraghazra](https://github.com/anuraghazra), his own profile hasn't been changed to reflect it and the fact a random url change like this would break everyone's profiles.

Please don't spread random urls for this.

**Comment by alannovais** [comment]
I replace URL and its worked for me as well!

> Before: https://github-readme-stats.vercel.app/api?username=FelipeFama&show_icons=true&theme=dark After: https://github-readme-stats-git-masterrstaa-rickstaa.vercel.app/api?username=FelipeFama&&show_icons=true&theme=dark
> 
> Now please close this issue. The author has changed the URL of API.

**Comment by FelipeFama** [comment]
Thank you very much.

**Comment by anuraghazra** [comment]
The issue has been fixed in https://github.com/anuraghazra/github-readme-stats/pull/2400, for more info see https://github.com/anuraghazra/github-readme-stats/issues/2380#issuecomment-1381436516

you may revert back to the original URL since rick's vercel account might not be able to handle millions of requests
