### ISSUE TITLE
count_private differs only in commit number

### ISSUE THREAD

**Issue by kam193** [anuraghazra/github-readme-stats#239]
**Is your feature request related to a problem? Please describe.**
The flag `count_private` is related only to commits count. I want to see the difference between total count of all my contributions and public only, so I suggest support also counting private/public PR and so.

**Describe the solution you'd like**
* `count_private=false` => commits, PRs, issues, repositories stats count only public events. 
* `count_private=true` => all stats count sum of public and private events.

**Describe alternatives you've considered**
If not possible, maybe would be better to rename `count_private` to e.g. `private_commits` to avoid confusions.

**Additional context**
I found [ContributionsCollection](https://docs.github.com/en/graphql/reference/objects#contributionscollection) in Github API, but I'm not sure if it's enough to implement proposed behavior.

**Comment by anuraghazra** [comment]
Hi @kam193 

AFAIK there is no way to fetch private issues,pr count

**Comment by kam193** [comment]
Ok :/ But we still can differ `RepostoriesContributedTo` and/or add number of private contributions (maybe subtracted by counted private commits?)
