### ISSUE TITLE
Cannot read properties of undefined (reading 'user')

### ISSUE THREAD

**Issue by MKJ07** [anuraghazra/github-readme-stats#2398]
### Describe the bug

Something went wrong! file an issue at https://tiny.one/readme-stats
It is not responding may be api or vercel.app is not working properly
If anyone has any idea how to fix it.. Share the ideas

### Expected behaviour

It should show the github stats about all the commits, pr and many more based on what the user want to show in their stats in various no of themes.

### Screenshots / Live demo link

[
![Screenshot_20230113_081915](https://user-images.githubusercontent.com/87239664/212226009-761603d8-a3bd-418d-9e9d-f5c7a23efcb0.png)
](url)

**Comment by ProsperousHeart** [comment]
this is a duplicate to #2380

**Comment by ZbWeR** [comment]
I face the same problem and I solved it by referring to this link [PiyushKumar-18-AI 's answer](https://github.com/anuraghazra/github-readme-stats/issues/2380#issuecomment-1381090309)

**Comment by MKJ07** [comment]
> I face the same problem and I solved it by referring to this link [PiyushKumar-18-AI 's answer](https://github.com/anuraghazra/github-readme-stats/issues/2380#issuecomment-1381090309)


Ya! the probem is solved thanks for the reference and also it will help others to fix it

**Comment by anuraghazra** [comment]
The issue has been fixed in #2400, for more info see https://github.com/anuraghazra/github-readme-stats/issues/2380#issuecomment-1381436516
