### ISSUE TITLE
Bug on github stats and most languages used

### ISSUE THREAD

**Issue by Nilson360** [anuraghazra/github-readme-stats#2405]
### Describe the bug

Something went wrong! file a issue at https://tiny.one/readme-stats : Please add env variable called PAT_1 with your github token in vercel

**Comment by TheGamer3514** [comment]
i am also getting this issue.

**Comment by claudiotancredi** [comment]
Duplicate of #2404

**Comment by claudiotancredi** [comment]
Duplicate of #2402

**Comment by wang-yurin** [comment]
change `https://github-readme-stats.vercel.app` to `https://github-readme-stats-ruby-one.vercel.app`

**Comment by Devarshi0-1** [comment]
It worked! Thanks!

**Comment by rickstaa** [comment]
It should be fixed for now! Feel free to comment on https://github.com/anuraghazra/github-readme-stats/issues/1515 if things break again.
