### ISSUE TITLE
Error : Maximum retries

### ISSUE THREAD

**Issue by Abhijeetbyte** [anuraghazra/github-readme-stats#2412]
### Describe the bug

Something went wrong, it doesn't shows my GitHub stats 

### Expected behaviour

It should show my GitHub stats 

### Screenshots / Live demo link

![Screenshot_2023-01-14-23-48-31-941~2](https://user-images.githubusercontent.com/80936610/212489768-39ab0bbd-e54a-4e9f-8979-691d0421faf3.jpeg)

**Comment by qfoxb** [comment]
Also happening here

**Comment by Kian738** [comment]
Ye same for me

**Comment by AlexPresso** [comment]
Same here

**Comment by georgekwan** [comment]
Same here😭

**Comment by yilmazgokhan** [comment]
Same

**Comment by TONYOG12** [comment]
same here

**Comment by claudiotancredi** [comment]
Read [this](https://github.com/anuraghazra/github-readme-stats/issues/2402#issuecomment-1382721986).

**Comment by nagarajpandith** [comment]
same here :/
i think we gotta deploy our [own vercel instance](https://github.com/anuraghazra/github-readme-stats#deploy-on-your-own-vercel-instance). he had addressed this issue under this https://github.com/anuraghazra/github-readme-stats/issues/1471

**Comment by Abhijeetbyte** [comment]
solved the issue by changing from https://github-readme-stats.vercel.app to https://github-readme-stats-ruby-one.vercel.app

**Comment by qfoxb** [comment]
This issue has been resolved and that is not a fix please close

> solved the issue by changing from https://github-readme-stats.vercel.app to https://github-readme-stats-ruby-one.vercel.app

**Comment by anuraghazra** [comment]
This has been fixed. We've updated few PATs which were expired before. 

But to ensure ZERO runtime, it's recommended to deploy on your own vercel instance.
