### ISSUE TITLE
blocks disappear over time

### ISSUE THREAD

**Issue by Ceyhun1999** [anuraghazra/github-readme-stats#2423]
### Describe the bug

blocks disappear over time [https://github.com/Ceyhun1999](url)

**Comment by rickstaa** [comment]
@Ceyhun1999 can you elaborate? Do you mean the card?

**Comment by Zo-Bro-23** [comment]
Your GitHub profile seems to show the cards properly. Can you please include a screenshot of the "blocks disappearing"?
