### ISSUE TITLE
Maximum retries exceeded

### ISSUE THREAD

**Issue by briansu2004** [anuraghazra/github-readme-stats#2425]
### Describe the bug

Something went wrong! file an issue at https://tiny.one/readme-stats
Maximum retries exceeded Please add an env variable called PAT_1 with your github token in vercel

![image](https://user-images.githubusercontent.com/6775994/212892983-97d1392a-afbe-4c93-878f-e40fab6848ea.png)

### Expected behaviour

Business as usual

**Comment by vibhorag101** [comment]
Same issue with me as well

**Comment by Zo-Bro-23** [comment]
See #2415 for solution.

**Comment by rickstaa** [comment]
Duplicate of #https://github.com/anuraghazra/github-readme-stats/issues/1471.
