### ISSUE TITLE
Maximum Retries Exceeded!

### ISSUE THREAD

**Issue by YashIndane** [anuraghazra/github-readme-stats#2426]
### Describe the bug

Asking to add an env variable called **PAT_1** with Github token in vercel. Not sure what to do...Please help!

### Expected behaviour

Previous normal behavior.

### Screenshots / Live demo link

![er](https://user-images.githubusercontent.com/53041219/212898224-920b6719-ace6-4531-bce1-73892e07e225.png)

**Comment by Zo-Bro-23** [comment]
See #2415 for solution.

**Comment by YashIndane** [comment]
> See #2415 for solution.

Thanks it worked!
