### ISSUE TITLE
Maximum retries exceeded. (deployed to my own Vercel)

### ISSUE THREAD

**Issue by CLCK0622** [anuraghazra/github-readme-stats#2428]
### Describe the bug

As mentioned above, I met the same problem even if I deploy it to my own Vercel. 

It asked me to add my `PAT_1` env variable, but I had added one with access to my repos. 

You can see my repo [here](https://readme-stats.clckblog.space/).

It appears like the following. 

Sincere thanks.

### Screenshots / Live demo link

![CLCK's GitHub stats](https://readme-stats.clckblog.space/api?username=CLCK0622)

### Additional context

Moreover, after configuring my personal domain, I will be very glad to provided it for others to use! :)

**Comment by Zo-Bro-23** [comment]
It's working right? It usually takes a few minutes for everything to get set up, so maybe that's why it didn't work at first.

**Comment by CLCK0622** [comment]
> It's working right? It usually takes a few minutes for everything to get set up, so maybe that's why it didn't work at first.

alright, I'll check it later as Vercel told me it was ready before...

**Comment by CLCK0622** [comment]
> It's working right? It usually takes a few minutes for everything to get set up, so maybe that's why it didn't work at first.

Oops, it still worked improperly even after an hour, could you check it up for me? 
Many thanks.

**Comment by CLCK0622** [comment]
> It's working right? It usually takes a few minutes for everything to get set up, so maybe that's why it didn't work at first.

I'm grateful that it finally worked perfectly now, and I'm willing to provide my domain for others:

From @CLCK0622 

```
https://readme-stats.clckblog.space/
```

**Comment by Zo-Bro-23** [comment]
It took a while for me too; don't know why. Glad it's working now!

**Comment by DylanDevelops** [comment]
My readme stats are currently having this issue. How exactly did you fix it?

**Comment by CLCK0622** [comment]
> My readme stats are currently having this issue. How exactly did you fix it?

Eh, I just waited for about an hour and it worked well. I'm also not that clear why this is so weird.

**Comment by CLCK0622** [comment]
@anuraghazra Excuse me, it seems that many people also have the same issue that the component will work well in about half an hour after deploying. I don't really know if this is by design but I think it would be better if you can add this to your tutorial for deployment on Vercel. (this really worried me before)

**Comment by kidpaul94** [comment]
I also have the same issue with my own Vercel. It's been like this the entire day and still not working. I even tried to redeploy the project but did not have any luck so far.

**Comment by CLCK0622** [comment]
> I also have the same issue with my own Vercel. It's been like this the entire day and still not working. I even tried to redeploy the project but did not have any luck so far.
> 
> Updates: It came back suddenly.

This kind of problem do happen before, and it's hard to say when it will return normal. Anyway, happy to hear that good message!

**Comment by Samuel-luo** [comment]
In my case
seems like `&count_private=true` problem
remove it and everything is working again
i try to revert it but the same issue is back. /sad
so i can only remove it

**Comment by trrapp12** [comment]
so having the same problem.  Trying to understand if the issue self-resolved or if everyone is saying they updated their Vercel and then it resolved after an amount of time passed???

**Comment by dAtiuyy** [comment]
yes im experiencing the same issue atm.  
![image](https://user-images.githubusercontent.com/49157326/213377414-c4e9f5c2-ace6-441a-a1fd-afeb18a68077.png)
```
[![dAtiuyy's Github Stats](https://github-readme-stats.vercel.app/api?username=dAtiuyy)](https://github.com/anuraghazra/github-readme-stats)
```

**Comment by Zo-Bro-23** [comment]
@dAtiuyy, this issue is for those who have deployed to their own Vercel instance.

Since you're using Anurag's instance, please see #2415.

**Comment by CLCK0622** [comment]
> so having the same problem. Trying to understand if the issue self-resolved or if everyone is saying they updated their Vercel and then it resolved after an amount of time passed???

I suppose it's due to some strange problems of the project. However, it seems really strange that it will be solved after a moment. Maybe due to the local cache? idk why

**Comment by CLCK0622** [comment]
> In my case
> seems like `&count_private=true` problem
> remove it and everything is working again
> i try to revert it but the same issue is back. /sad
> so i can only remove it

maybe you can try to add it back now? I didn't do anything but waited and it recovered automatically.

**Comment by Samuel-luo** [comment]
> > In my case
> > seems like `&count_private=true` problem
> > remove it and everything is working again
> > i try to revert it but the same issue is back. /sad
> > so i can only remove it
> 
> maybe you can try to add it back now? I didn't do anything but waited and it recovered automatically.

yeah，it's working now，maybe the local cache causing this issue

**Comment by murtuzaalisurti** [comment]
> @dAtiuyy, this issue is for those who have deployed to their own Vercel instance.
> 
> Since you're using Anurag's instance, please see #2415.

thanks, I am facing the same issue! deploying own instance might solve it!

**Comment by rickstaa** [comment]
It should be fixed for now. If you run into problems please comment below. 👍

**Comment by CLCK0622** [comment]
> It should be fixed for now. If you run into problems, please comment below. 👍

y exactly, I just wanted to let more people see this issue. now that there's new solution, it no longer matters.
thx anyway
