### ISSUE TITLE
removal from deby list

### ISSUE THREAD

**Issue by gasha76** [anuraghazra/github-readme-stats#2436]
### Describe the bug

Respect,
as you will see in the pictures, I bought a hot spot from an acquaintance on 01/08/2023, it didn't work for two days at my place, I didn't even manage to mount it in the attic, but I taped the antenna to the window until I had time to connect everything. After two days of work I'm on the denial list, I'm a beginner and I barely managed to find and write this. I am really asking you to allow me to prove that I had intentions to work honestly, I paid properly for the change of location as I would have paid for the other items after the assembly, do not condemn the innocent and immediately kill my will to continue working.
Thank in advance.
![IMG_20230117_182533](https://user-images.githubusercontent.com/122916036/212975766-44e3772d-2bef-4c3e-a286-8ca8ca156427.jpg)
![IMG_20230116_192245](https://user-images.githubusercontent.com/122916036/212975787-6bbc6cbd-34bf-4af3-8535-37f7e3aeb743.jpg)
![IMG_20230116_192243](https://user-images.githubusercontent.com/122916036/212975877-eaafea39-336a-4cdf-ab9e-056d93838aa3.jpg)
![IMG_20230116_192256](https://user-images.githubusercontent.com/122916036/212975951-0a304ef3-807e-4cef-a4d6-71d5e51cd84a.jpg)

### Expected behaviour

im expected to see all this and take me from denz list

### Screenshots / Live demo link

112YC3yZNPbrBJCzwEnidaTffBaxhDuAMyGqPYKM2wXFMwPe2PnQ
COLOSSAL BLACK FERRET

### Additional context

PLEASE HELP ME

**Comment by Happyrobot33** [comment]
tf is this issue?

**Comment by gasha76** [comment]
Issue. I buy this miner from one friend on 01.08.2023. I have proof,I puy
to change location and don't poot it on the roof even because I'm waiting
cable for antena. Work only 2 day and I'm on deny list. Why? Can you please
help me.
Thanks


Colossal black ferret

уто, 17. јан 2023. 21:03 Matthew Herber ***@***.***> је
написао/ла:

**Comment by mustafaozhan** [comment]
😄 @gasha76 can you please double-check where are you reporting this issue ?
You are obviously looking for a help in wrong place 🙂

**Comment by gasha76** [comment]
Send me link wear to write.

**Comment by PencilNavigator** [comment]
This is the github-readme-status repository, you are obviosly asking in the wrong place.

**Comment by rickstaa** [comment]
Closing this since it is unrelated to the GRS repo.
