### ISSUE TITLE
[Discussion] New possible card ideas

### ISSUE THREAD

**Issue by HPaulson** [anuraghazra/github-readme-stats#244]
Discussion of new possible card ideas & options for existing cards!
--
### Possible Card Ideas:

**Compact Stats Card**
- Having a compact stats card, so it can fit side-by-side with the compact language card, and decrease unnecessary whitespace and wording in the card
- [Concept 1](https://cdn.smc.wtf/NrQ.png), [Concept 2](https://user-images.githubusercontent.com/20476002/88905874-15537480-d257-11ea-91ef-e0b6d319f5aa.png)

**Pie chart language card**
- Having an additional option for the language card, which would format the languages into a pie chart shape rather than the traditional github style, or the default language card style
- [Concept](https://user-images.githubusercontent.com/20476002/88953719-a0edf500-d299-11ea-983d-747d078deb12.png)

**Comment by Ryyn-Sd** [comment]
I'll fix it!

**Comment by Angelk90** [comment]
@HPaulson , @Ryyn-Sd : 
An even more compact shape.
![68747470733a2f2f63646e2e736d632e7774662f4e72512e706e67](https://user-images.githubusercontent.com/20476002/88905874-15537480-d257-11ea-91ef-e0b6d319f5aa.png)

**Comment by nthnchu** [comment]
Or the rank circle could be hidden to make room for the stats. I do like your idea though @Angelk90.

**Comment by HPaulson** [comment]
@Angelk90 Yup! Even better!👍

**Comment by Angelk90** [comment]
@HPaulson : 

![Schermata 2020-07-30 alle 19 08 16 (1)](https://user-images.githubusercontent.com/20476002/88953719-a0edf500-d299-11ea-983d-747d078deb12.png)

What do you think of such a graph instead of what you see below.

![68747470733a2f2f63646e2e736d632e7774662f4e72512e706e67](https://user-images.githubusercontent.com/20476002/88905874-15537480-d257-11ea-91ef-e0b6d319f5aa.png)

**Comment by HPaulson** [comment]
@Angelk90 Yeah that looks kinda bad in my opinion... The compact lang graph now that looks just like github's is very very nice, and this pie chart kinda loses the pleasing ascetic of the current compact one... also, this concept pie chart you have only displays the rank, which as I see it, is the most useless information on the card compared to the actual stats... Personally I really like your original  [concept](https://user-images.githubusercontent.com/47159695/88954307-2fe21980-d268-11ea-95c5-161b10ae8626.png) the best.

I'm curious other people's thoughts on this pie chart though, since obviously my opinion is just one of many!

**Comment by anuraghazra** [comment]
> @HPaulson :
> 
> ![Schermata 2020-07-30 alle 19 08 16 (1)](https://user-images.githubusercontent.com/20476002/88953719-a0edf500-d299-11ea-983d-747d078deb12.png)
> 

I like this Pie chart, but i don't think it would look good if we mix it up with stats card, maybe we can make it a new layout option in the Languages card `&layout=pie-chart`

**Comment by anuraghazra** [comment]
> @HPaulson , @Ryyn-Sd :
> An even more compact shape.
> ![68747470733a2f2f63646e2e736d632e7774662f4e72512e706e67](https://user-images.githubusercontent.com/20476002/88905874-15537480-d257-11ea-91ef-e0b6d319f5aa.png)

Issue with this compact card is people would get really confused with just the numbers, and it also looks too much cramped IMO. 

@HPaulson's original card is better because it shows some context of what those numbers means.

**Comment by HPaulson** [comment]
@anuraghazra I'm pretty sure the idea behind the pie chart was to mix the stats & lang cards... I think this since the pie chart itself is langs, and the center uses the rank as the stats card does. If this was the intention, I think it's kinda poor. However just having a pie chart for langs isn't a bad idea at all, I'd also like to point out that the current compact lang card is a pie chart, just in a straight line instead of the traditional pie shape.
![Img](https://cdn.smc.wtf/9Pp.png)

**Comment by anuraghazra** [comment]
> Currently you're able to hide any of the specific stats on the left, but you aren't able to hide the rank circle.

You can hide the rank circle `&hide_rank=true`

**Comment by anuraghazra** [comment]
> I think this since the pie chart itself is langs, and the center uses the rank as the stats card does. If this was the intention, I think it's kinda poor.

No, I'm not talking about the centered rank on the pie chart. Just the pie chart in the langs card.

**Comment by HPaulson** [comment]
@anuraghazra Ah okay, I'll mark my comment as off-topic then haha. Didn't see that option in docs, sorry about that!

**Comment by HPaulson** [comment]
> No, I'm not talking about the centered rank on the pie chart. Just the pie chart in the langs card.

Yeah as I mentioned later in that comment-
> However just having a pie chart for langs isn't a bad idea at all
What I meant there was just that it seemed the intention of the concept was to merge the rank from stats & lang cards, which I thought was a bit poor. Having just a pie chart for langs is a great idea like I mentioned, however I'll mention again that the current compact one is a pie chart just in a line and not a circle, so it may be a bit repetitive. However if people prefer the circle shape, then it's a great idea. Having more options isn't a bad thing!

**Comment by HPaulson** [comment]
Also, I have some other possible card ideas that I think could possibly excel this project... Should I make a new issue for them or just change the title here to "Possible card ideas" and leave it as more of an open discussion for more possible ideas, rather than just the compact stats card?

**Comment by anuraghazra** [comment]
> Also, I have some other possible card ideas that I think could possibly excel this project... Should I make a new issue for them or just change the title here to "Possible card ideas" and leave it as more of an open discussion for more possible ideas, rather than just the compact stats card, since we're already talking about other card ideas such as the pie chart?


Of course do it!

**Comment by anuraghazra** [comment]
> so it may be a bit repetitive

No it won't be repetitive, it would be just a stylistic choice of which type of design users would like to use.

**Comment by HPaulson** [comment]
Additionally, I had an idea about having a card to show recent activity and contributions - I used to use [this repo](https://github.com/JasonEtco/activity-box) to update a pinned gist to do so, however I think that with the addition of readme it could be much much more improved by being an image, rather than being text in a gist; The design could be much more improved, and it could be a cool card to add! What are everyone's thoughts on something like this? Also, I'm going to edit the initial comment on this thread to include the ideas we've shared so far.

**Comment by HPaulson** [comment]
Just a quick update on this, I did actually make some changes to the stats card to see how this would come out, and I think it looks great!

@anuraghazra What are your thoughts?
![](https://cdn.smc.wtf/hJA.png)

#### Changes:
```diff
- 34      <text class="stat bold" ${labelOffset} y="12.5">${label}:</text>

+ 35      ${labelOffset}

- 37      x="${shiftValuePos ? (showIcons ? 200 : 170) : 150}" 

+ 40      <text class="stat bold" x="60" y="12.5">${label}</text>

- 85      label: "Total Stars",
+ 85      label: "Stars Received",

- 91      label: `Total Commits${
+ 91      label: `Commits${

- 99      label: "Total PRs",
+ 99      label: "PRs",

- 105     label: "Total Issues",
+ 105     label: "Issues",

- 111     label: "Contributed to",

- 134     hide_rank ? 0 : 150
+ 134     hide_rank ? 0 : 75

- 141     hide_rank ? 0 : 75
+ 141     transform="translate(300, ${height / 2 - 50})">

- 171     width: 495,
+ 171     width: 350,
```

**Comment by Angelk90** [comment]
@anuraghazra : 
1) Is there any news regarding the pie chart?
2) Is there any news regarding the possibility of having only the icons in the github stats card without having the labels?

**Comment by HPaulson** [comment]
@Angelk90 This thread is just a basic discussion of different possible card ideas- if you want one added, I'd suggest opening a PR & creating it!

**Comment by Angelk90** [comment]
@anuraghazra : Are there any news?

**Comment by Angelk90** [comment]
@anuraghazra : Are there any news?

**Comment by ArpadGBondor** [comment]
Hi!

I just started discovering how to "pimp" my profile, and I really like this tool :) Thank you!
I'd really like a feature where I can use custom titles for my Repo Stat cards, because I'm using too long repo names, and they can't fit in the cards.

**Comment by Ryyn-Sd** [comment]
I decided to not do it

**Comment by Angelk90** [comment]
@anuraghazra : Are there any news?

**Comment by Ryyn-Sd** [comment]
Sorry, but I decided to not offer open projects anymore. Therefore, I am not doing your project. Sorry
