### ISSUE TITLE
The midnight-purple theme doesn't work!

### ISSUE THREAD

**Issue by nsbb** [anuraghazra/github-readme-stats#2441]
### Describe the bug

!!!midnight-purple theme doesn't work, but other theme works well!

### Screenshots / Live demo link

![Screen Shot 2023-01-19 at 15 13 20](https://user-images.githubusercontent.com/9316959/213369019-a2d2d50e-48eb-43e1-b200-7074047cf4c0.png)
![Screen Shot 2023-01-19 at 15 15 44](https://user-images.githubusercontent.com/9316959/213369352-6481ba15-0f61-4e4d-ad03-f948292a465a.png)

**Comment by Zo-Bro-23** [comment]
See #2415 please.

**Comment by PencilNavigator** [comment]
https://github.com/PencilNavigator/readme-stats-URL
Change your URL by finding one here.
