### ISSUE TITLE
Need to update env variables for github token

### ISSUE THREAD

**Issue by CoderMayhem** [anuraghazra/github-readme-stats#2444]
### Describe the bug

Error in fetching display data from vercel app, says maximum retries reached. See attached screenshot for info.

### Screenshots / Live demo link

![Screenshot 2023-01-19 17:53:39](https://user-images.githubusercontent.com/56952811/213442444-212c0a94-04fa-469e-b192-11795b8e2f0f.png)

**Comment by Zo-Bro-23** [comment]
Please see #2415 and #1471 for solution.

(@rickstaa please close)
