### ISSUE TITLE
vercel.json maxDuration is between 1 to 10 only During deployment on vercel

### ISSUE THREAD

**Issue by Abhishek-00** [anuraghazra/github-readme-stats#2451]
### Describe the bug

On deploying on vercel showing error maxDuration is between 1 to 10 

### Screenshots / Live demo link

![image](https://user-images.githubusercontent.com/101923614/213870728-9a8c2fdc-aac1-4a7c-90a4-d06ef925a705.png)

**Comment by rickstaa** [comment]
@Abhishek-00 Thanks for your bug report. We need the `30` seconds for the public Vercel instance. This is documentation in step 6 of the step-by-step guide (see https://github.com/anuraghazra/github-readme-stats#deploy-on-your-own-vercel-instance). We are trying to make the process of changing the `maxDuration` for forks automatic (see https://github.com/anuraghazra/github-readme-stats/pull/2424).
