### ISSUE TITLE
Card content overflow

### ISSUE THREAD

**Issue by angristan** [anuraghazra/github-readme-stats#2452]
### Describe the bug

I have recently noticed an issue where the content of the card overflow on the right, and is thus cropped. 

I have not found an existing issue for this.

### Expected behaviour

The width should match the content of the card.

### Screenshots / Live demo link

Link: https://github-readme-stats.vercel.app/api?username=angristan&count_private=true&show_icons=true&include_all_commits=true&hide_rank=true&hide_title=true&theme=buefy

Screenshot: 
<img width="424" alt="image" src="https://user-images.githubusercontent.com/11699655/213879880-9d74b5ad-2f74-4e1c-a62e-cc52e96a986a.png">

**Comment by rickstaa** [comment]
@angristan Thanks for your bug report. We are of the bug, but we did not yet have time to fix it. Let's track the progress here. As a workaround, you can use the [card_width ](https://github.com/anuraghazra/github-readme-stats#stats-card-exclusive-options) option to enlarge the card.

**Comment by angristan** [comment]
Awesome, thanks for the prompt answer. Adding `card_width=300` fixes the issue for me.

**Comment by rickstaa** [comment]
Related to #2297. This issue was introduced in ad3726ee491492ab6d312cba09f738986192fd0e.

**Comment by rickstaa** [comment]
#2460 will fix this.

**Comment by anuraghazra** [comment]
Fixed in #2460
