### ISSUE TITLE
Users should be able to know the name of the theme when they hover

### ISSUE THREAD

**Issue by Vee339** [anuraghazra/github-readme-stats#2455]
### Is your feature request related to a problem? Please describe.

Today, I used the GitHub stats for the first time. But when I was changing the theme, by just looking at the image I was not able to decide which name is of which theme and I had to try many names to implement my desired theme.
![theme-problem](https://user-images.githubusercontent.com/81091817/213906578-3af8cb62-9c6d-4b86-9e23-acc4a765eab9.png)
try many names to implement my desired theme.

### Describe the solution you'd like

I think we should use individual images for each theme and the user should know the name of the theme by hovering on it or we can just write it under the image.

**Comment by rickstaa** [comment]
@Vee339, that is a good suggestion! We did not yet investigate if showing [a hover](https://stackoverflow.com/questions/41768657/display-text-over-svg-element-on-hover) on a Vercel-generated card is possible, but we will likely look into this in the future since we also need it for the ranking (see https://github.com/anuraghazra/github-readme-stats/issues/2157).

**Comment by anuraghazra** [comment]
@Vee339 you don't need to hover, that screenshot is there just for demo purposes, you can explore the whole [catalog of themes here](https://github.com/anuraghazra/github-readme-stats/tree/master/themes)

**Comment by rickstaa** [comment]
> the first time. But when I was changing the theme, by just looking at the image I was not able to decide which name is of which theme and I had to try many names to implement my desired theme.

O wow, I fully misinterpreted the question. I thought @Vee339 wanted to see the theme somebody is using on somebodies README card on hover. 😅 Which in my opinion would be a feature request that is cool but I think has a small user base. 🤔 Thanks for clearing that up @anuraghazra.

**Comment by anuraghazra** [comment]
Plus, doing any kind of hover interaction in readmes is not possible right now.

**Comment by rickstaa** [comment]
> Plus, doing any kind of hover interaction in readmes is not possible right now.

Think we can also close https://github.com/anuraghazra/github-readme-stats/issues/2157 then?

**Comment by Zo-Bro-23** [comment]
> Plus, doing any kind of hover interaction in readmes is not possible right now. 

That's what I thought 😥
