### ISSUE TITLE
Not working

### ISSUE THREAD

**Issue by aswingt65** [anuraghazra/github-readme-stats#2461]
### Describe the bug

The profile status is not working even after adding the env variable PAT_1

### Screenshots / Live demo link

https://github.com/aswingt65/aswingt65

**Comment by rickstaa** [comment]
@aswingt65 thanks for your question. It seems to be working on my end:

![Aswin's GitHub stats](https://github-readme-stats.vercel.app/api?username=aswingt65&env=PAT_1&show_icons=true&theme=dark&border=true)

[![Top Langs](https://github-readme-stats.vercel.app/api/top-langs/?username=aswingt65&env=PAT_1&layout=compact&theme=dark)](https://github.com/aswingt65/github-readme-stats)

I think you were dealing with https://github.com/anuraghazra/github-readme-stats/issues/1471. Deploying your own Vercel instance will help.

**Comment by aswingt65** [comment]
It started working at my end also.
Thanks for responding fast.
