### ISSUE TITLE
Top langs are not working when I add exclude_repo

### ISSUE THREAD

**Issue by Adamekka** [anuraghazra/github-readme-stats#2462]
### Describe the bug

when I add exclude_repo, it stops working
![image](https://user-images.githubusercontent.com/68786400/214398452-ae1fc909-14c5-4d1d-a808-6560a3fbff49.png)
but when I remove it, it works
![image](https://user-images.githubusercontent.com/68786400/214398526-fedd1ad8-0a99-453c-a772-e717065fcfb6.png)
this problem appeared out of nowhere

**Comment by rickstaa** [comment]
@Adamekka Thanks for the bug report. I see you are using my branch. No problem; there are, however, some experimental features on there. There was a bug in one of those features. I now fixed it 👍. Thanks for letting me know.

**Comment by rickstaa** [comment]
Please be aware that we use a 4-hour caching period. The card will likely work in 4 hours. If you want it to work now, you have to purge GitHub's cache (see https://docs.github.com/en/authentication/keeping-your-account-and-data-secure/about-anonymized-urls#an-image-that-changed-recently-is-not-updating).

**Comment by Adamekka** [comment]
Thanks a lot! Everything works.
