### ISSUE TITLE
2e2 tests are failing on forked repo

### ISSUE THREAD

**Issue by ruchernchong** [anuraghazra/github-readme-stats#2465]
### Describe the bug

As per the screenshot below, the test is failing on a forked repo.

### Expected behaviour

Test should pass just like the repo from upstream.

### Screenshots / Live demo link

![image](https://user-images.githubusercontent.com/10343662/214473968-401a9ce0-a56a-4c31-8edd-6a897294313e.png)

**Comment by rickstaa** [comment]
> ### Describe the bug
> As per the screenshot below, the test is failing on a forked repo.
> 
> ### Expected behaviour
> Test should pass just like the repo from upstream.
> 
> ### Screenshots / Live demo link
> ![image](https://user-images.githubusercontent.com/10343662/214473968-401a9ce0-a56a-4c31-8edd-6a897294313e.png)
> 
> ### Additional context
> _No response_

@ruchernchong don't worry; that action is a double-check that the APIs work when a change is deployed to Vercel. It doesn't matter unless you are doing development and want to merge a change into the upstream. More importantly, in this case, the Wakatime API timed out. This happens from time to time. The problem will likely go away when you re-run the action.

**Comment by ruchernchong** [comment]
> > ### Describe the bug
> 
> > As per the screenshot below, the test is failing on a forked repo.
> 
> > 
> 
> > ### Expected behaviour
> 
> > Test should pass just like the repo from upstream.
> 
> > 
> 
> > ### Screenshots / Live demo link
> 
> > ![image](https://user-images.githubusercontent.com/10343662/214473968-401a9ce0-a56a-4c31-8edd-6a897294313e.png)
> 
> > 
> 
> > ### Additional context
> 
> > _No response_
> 
> 
> 
> @ruchernchong don't worry; that action is a double-check that the APIs work when a change is deployed to Vercel. It only matters if you are doing development and want to merge a change into the upstream. More importantly, in this case, the Wakatime API timed out. This happens from time to time. The problem will likely go away when you re-run the action.

Got it. Thank you!
