### ISSUE TITLE
Something went wrong! 'maximum retries exceeded' error

### ISSUE THREAD

**Issue by faarukbulut** [anuraghazra/github-readme-stats#2469]
### Describe the bug

There is an error indicated in the screenshot.

### Screenshots / Live demo link

![This is an image](https://i.hizliresim.com/94mfd0i.png)

**Comment by Zo-Bro-23** [comment]
@rickstaa did the PAT accounts get banned again? Hoping they still work 🤞

**Comment by rickstaa** [comment]
> @rickstaa did the PAT accounts get banned again? Hoping they still work 🤞

I checked the PATs I supplied and they are still working. We might simply need another PAT due to growing in popularity and traffic @anuraghazra?

**Comment by rickstaa** [comment]
This issue should now be fixed👍.
