### ISSUE TITLE
'maximum retries exceeded' error

### ISSUE THREAD

**Issue by Ceyhun1999** [anuraghazra/github-readme-stats#2472]
### Describe the bug

I know that this problem is solved if you create your own api vercel. Only I can't create api vercel. Watched anuraghazra video on youtube. There's an old version of vercel. Help create api vercel in updated version

**Comment by Zo-Bro-23** [comment]
Can you try following the step-by-step guide [here](https://github.com/anuraghazra/github-readme-stats#deploy-on-your-own-vercel-instance) (not the video)? Let us know where you're having trouble.

**Comment by rickstaa** [comment]
Duplicate of #2469 and #1471.
