### ISSUE TITLE
Prototype Pollution in JSON5 via Parse Method

### ISSUE THREAD

**Issue by vedxp** [anuraghazra/github-readme-stats#2477]
### Describe the bug

The parse method of the JSON5 library before and including version 2.2.1 does not restrict parsing of keys named __proto__, allowing specially crafted strings to pollute the prototype of the resulting object.

This vulnerability pollutes the prototype of the object returned by JSON5.parse and not the global Object prototype, which is the commonly understood definition of Prototype Pollution. However, polluting the prototype of a single object can have significant security impact for an application if the object is later used in trusted operations.

[Checkout the complete alert](https://github.com/advisories/GHSA-9c47-m6qq-7p4h)

**Comment by rickstaa** [comment]
Thanks for your security bug report. I checked the code, and we don't use `json5` directly. Can you maybe create a PR with the dependency that needs to be updated with `json5` as a dependency?

**Comment by anuraghazra** [comment]
Dependabot alerts are already tracked here, https://github.com/anuraghazra/github-readme-stats/security/dependabot/1 no need to open an issue for it.

**Comment by anuraghazra** [comment]
And json5 is used by some other package which is a dev dependency so doesn't affect us.

**Comment by rickstaa** [comment]
> Dependabot alerts are already tracked here, https://github.com/anuraghazra/github-readme-stats/security/dependabot/1 no need to open an issue for it.

This URL is, I think not visible to normal members 🤔.

**Comment by rickstaa** [comment]
> And json5 is used by some other package which is a dev dependency so doesn't affect us.

Nice thanks for letting me know.
