### ISSUE TITLE
Language Card: Add ability to show private repos

### ISSUE THREAD

**Issue by kongtaoxing** [anuraghazra/github-readme-stats#2478]
### Is your feature request related to a problem? Please describe.

Sometimes I make some repos invisable, but I want to show that in **_Most Used Languages_** tab, jsut like _**One's Github Stats**_.

### Describe the solution you'd like

`&count_private=true`
`&count_private=false`
and default is `false`

**Comment by rickstaa** [comment]
@kongtaoxing We don't have access to private dependencies on the Public Vercel instance. The `count_private` parameter exists on the stats card because people can share the number of private commits on their GitHub profile.

**Comment by kongtaoxing** [comment]
Thank you, sir. That's a very useful solution.
