### ISSUE TITLE
Theme github_dark

### ISSUE THREAD

**Issue by Burnout156** [anuraghazra/github-readme-stats#2493]
### Describe the bug

I had to comment the theme I had posted (github_dark) because it doesn't work with the url https://github-readme-stats-sigma-five.vercel.app

### Screenshots / Live demo link

![imagem_2023-02-03_131019636](https://user-images.githubusercontent.com/9204362/216651455-981d98b6-8791-4e19-9d83-7d872088bbc7.png)

**Comment by rickstaa** [comment]
@Burnout156, thanks for your bug report. The theme appears to be working on the official public Vercel instance.

![Anurag's GitHub stats](https://github-readme-stats.vercel.app/api?username=anuraghazra&show_icons=true&theme=github_dark)

```md
![Anurag's GitHub stats](https://github-readme-stats.vercel.app/api?username=anuraghazra&show_icons=true&theme=radical)
```

We fixed the downtime issues for now. Nevertheless, it still is better to deploy your Vercel instance.
