### ISSUE TITLE
Parameter `hide=stars` breaks statistics column

### ISSUE THREAD

**Issue by Olf0** [anuraghazra/github-readme-stats#2495]
### Describe the bug

Appending the parameter `hide=stars` to the parameter set breaks the statistics column.  In my specific case only the (then) first line was displaying a erroneous value, "Total Commits: **2**" instead of the correct value "Total Commits: 3.2k".

### Expected behaviour

Adding the parameter `hide=stars` to the parameter set solely lets the row "Total Stars Earned:" disappear.

### Screenshots / Live demo link

Broken statistics column with parameter `hide=stars` as last parameter:
![broken-statistics-colum-with-hide_stars.svg](https://user-images.githubusercontent.com/16547876/216742538-e2df5169-0a15-464d-a60b-6478809f9e4b.svg)

Correct statistics column without parameter `hide=stars`:
![correct-statistics-colum-without-hide_stars.svg](https://user-images.githubusercontent.com/16547876/216742536-c41b13b5-e1b9-4f82-b9b0-e80a495c9bc3.svg)

### Additional context

Ultimately [I omitted the parameter `hide=stars`](https://github.com/Olf0/Olf0/commit/4c9d7bc4185189a6bc497093d52ca64170d59ed3) as a workaround.

**Comment by rickstaa** [comment]
@Olf0, thanks for the bug report. I, however, can not reproduce the issue (see images below). Could you provide me with the exact command you are using?

#### Without icons

[![Anurag's GitHub stats](https://github-readme-stats.vercel.app/api?username=olf0&hide=stars&include_all_commits=true)](https://github.com/anuraghazra/github-readme-stats)

```md
[![Anurag's GitHub stats](https://github-readme-stats.vercel.app/api?username=olf0&hide=stars&include_all_commits=true)](https://github.com/anuraghazra/github-readme-stats)
```

[![Anurag's GitHub stats](https://github-readme-stats.vercel.app/api?username=rickstaa&hide=stars&include_all_commits=true)](https://github.com/anuraghazra/github-readme-stats)

```md
[![Anurag's GitHub stats](https://github-readme-stats.vercel.app/api?username=rickstaa&hide=stars&include_all_commits=true)](https://github.com/anuraghazra/github-readme-stats)
```

#### With icons

[![Anurag's GitHub stats](https://github-readme-stats.vercel.app/api?username=olf0&hide=stars&include_all_commits=true&show_icons=true)](https://github.com/anuraghazra/github-readme-stats)

```md
[![Anurag's GitHub stats](https://github-readme-stats.vercel.app/api?username=olf0&hide=stars&include_all_commits=true&show_icons=true)](https://github.com/anuraghazra/github-readme-stats)
```

[![Anurag's GitHub stats](https://github-readme-stats.vercel.app/api?username=rickstaa&hide=stars&include_all_commits=true&show_icons=true)](https://github.com/anuraghazra/github-readme-stats)

```md
[![Anurag's GitHub stats](https://github-readme-stats.vercel.app/api?username=rickstaa&hide=stars&include_all_commits=true&show_icons=true)](https://github.com/anuraghazra/github-readme-stats)
```

**Comment by Olf0** [comment]
> Could you provide me with the exact command you are using?

I already did [in the section "Additional context"](https://github.com/anuraghazra/github-readme-stats/issues/2495#issue-1570726194).

**Comment by rickstaa** [comment]
> > Could you provide me with the exact command you are using?
> 
> I already did [in the section "Additional context"](https://github.com/anuraghazra/github-readme-stats/issues/2495#issue-1570726194).
> 
> Side notes:
> 
> * Yes, I already suspected some interference between options, obviously it is not `show_icons` (which I never set to `false` before).
> * I wanted to check if the option parser may bear some position dependence of options: It is JavaScript, hence I am out (sorry).

@Olf0 I am not able to reproduce your problems. Please take a look at my message above. Please add the live cards with the associated markdown in a comment below. Please take a look at my note above for an example.

**Comment by Olf0** [comment]
O.K., here is an expanded copy of the link [https://github.com/Olf0/Olf0/commit/4c9d7bc4185189a6bc497093d52ca64170d59ed3](https://github.com/Olf0/Olf0/commit/4c9d7bc4185189a6bc497093d52ca64170d59ed3) provided inn my initial message, plus a copy of the results form my initial message.

#### Does not work as documented:
```
<a href="https://github.com/anuraghazra/github-readme-stats#readme">
  <img align="center" width="100%" src="https://github-readme-stats.vercel.app/api?username=Olf0&custom_title=olf's%20statistics&show_icons=true&disable_animations=false&line_height=25&cache_seconds=86399&theme=transparent&locale=en&include_all_commits=true&count_private=true&hide=stars" />
</a>
```
results in ![broken-statistics-colum-with-hide_stars.svg](https://user-images.githubusercontent.com/16547876/216742538-e2df5169-0a15-464d-a60b-6478809f9e4b.svg)

#### Omitting `&hide=stars` lets it work correctly (but with the unwanted stars row):
```
<a href="https://github.com/anuraghazra/github-readme-stats#readme">
  <img align="center" width="100%" src="https://github-readme-stats.vercel.app/api?username=Olf0&custom_title=olf's%20statistics&show_icons=true&disable_animations=false&line_height=25&cache_seconds=86399&theme=transparent&locale=en&include_all_commits=true&count_private=true" />
</a>
```
results in ![correct-statistics-colum-without-hide_stars.svg](https://user-images.githubusercontent.com/16547876/216742536-c41b13b5-e1b9-4f82-b9b0-e80a495c9bc3.svg)


IIRC I had formatting issues with markdown, hence I resorted to HTML.
I assume(d) it does not make a difference for the scripts, as they are called with the same parameters.

Is that the information you wanted, or did I misunderstand your request?

**Comment by rickstaa** [comment]
Thanks for the information. With Live cards, I mean the exact Markdown or HTML code you used. 👍These can be placed into the comment to let the cards render live on the screen instead of showing it as a static SVG. When I use your command, I can still not reproduce the errors (see below). 🤔 

#### With hide=stars

<a href="https://github.com/anuraghazra/github-readme-stats#readme">
  <img align="center" width="100%" src="https://github-readme-stats.vercel.app/api?username=Olf0&custom_title=olf's%20statistics&show_icons=true&disable_animations=false&line_height=25&cache_seconds=86399&theme=transparent&locale=en&include_all_commits=true&count_private=true&hide=stars" />
</a>

```HTML
<a href="https://github.com/anuraghazra/github-readme-stats#readme">
  <img align="center" width="100%" src="https://github-readme-stats.vercel.app/api?username=Olf0&custom_title=olf's%20statistics&show_icons=true&disable_animations=false&line_height=25&cache_seconds=86399&theme=transparent&locale=en&include_all_commits=true&count_private=true&hide=stars" />
</a>
````

#### Without hide=stars

<a href="https://github.com/anuraghazra/github-readme-stats#readme">
  <img align="center" width="100%" src="https://github-readme-stats.vercel.app/api?username=Olf0&custom_title=olf's%20statistics&show_icons=true&disable_animations=false&line_height=25&cache_seconds=86399&theme=transparent&locale=en&include_all_commits=true&count_private=true" />
</a>

```HTML
<a href="https://github.com/anuraghazra/github-readme-stats#readme">
  <img align="center" width="100%" src="https://github-readme-stats.vercel.app/api?username=Olf0&custom_title=olf's%20statistics&show_icons=true&disable_animations=false&line_height=25&cache_seconds=86399&theme=transparent&locale=en&include_all_commits=true&count_private=true" />
</a>
````

**Comment by Olf0** [comment]
> When I use your command, I can still not reproduce the errors (see below). :thinking:

Your check made my retry: Now I cannot reproduce it either! :confused: 

Hey, I tried this back and forth two times, before I saved the images as PNGs, which I embedded in to the initial post here.
So I returned to my intended setting and will continue to watch it: https://github.com/Olf0/Olf0/blob/master/README.md :eyes:

Sorry!  Puzzled.

**Comment by rickstaa** [comment]
> > When I use your command, I can still not reproduce the errors (see below). 🤔
> 
> Your check made me retry: Now I cannot reproduce it either! 😕
> 
> Hey, I tried this back and forth two times, before I saved the images as PNGs, which I embedded in the initial post here. So I returned to my intended setting and will continue to watch it: https://github.com/Olf0/Olf0/blob/master/README.md 👀
> 
> Sorry! Puzzled.

No problem. Thanks for letting us know. The GraphQL and REST APIs are buggy sometimes. It could be that the card cached a temporary error (see https://github.com/anuraghazra/github-readme-stats/issues/1515).

**Comment by rickstaa** [comment]
> @rickstaa, thank you for the explanation, which actually makes sense when looking at the wrong value returned: "**2**" is very likely then number of private commits I ever did at GitHub.
> 
> As [your comment in issue #1515](https://github.com/anuraghazra/github-readme-stats/issues/1515#issuecomment-1256977725) describes and the code nicely shows: If `include_all_commits` is set `true` GitHub's REST API returns "**0**" in the error case; then the number of private commits is added to this value, if `count_private` is set `true`.
> 
> As I was experimenting with these "live cards", I switched on all possible parameters to play with them and went through some iterations trying different values, then looking at the result. In hindsight this was a good scheme to trigger this bug.
> 
> Now I understand what likely happened, thus I appreciate your explanation and pointing to issue #1515 very much!

Thanks for your detailed investigation report! When I perform tests, I make sure a random string is added to the query (i.e. `random=234234sfds`). This will break the cache.

**Comment by rickstaa** [comment]
> > @rickstaa, thank you for the explanation, which actually makes sense when looking at the wrong value returned: "**2**" is very likely then number of private commits I ever did at GitHub.
> > As [your comment in issue #1515](https://github.com/anuraghazra/github-readme-stats/issues/1515#issuecomment-1256977725) describes and the code nicely shows: If `include_all_commits` is set `true` GitHub's REST API returns "**0**" in the error case; then the number of private commits is added to this value, if `count_private` is set `true`.
> > As I was experimenting with these "live cards", I switched on all possible parameters to play with them and went through some iterations trying different values, then looking at the result. In hindsight this was a good scheme to trigger this bug.
> > Now I understand what likely happened, thus I appreciate your explanation and pointing to issue #1515 very much!
> 
> Thanks for your detailed investigation report! When I perform tests, I make sure a random string is added to the query (i.e. `&random=234234sfds`). This will break the cache.
