### ISSUE TITLE
GitHub Dark Theme

### ISSUE THREAD

**Issue by MarcinK50** [anuraghazra/github-readme-stats#25]
Hello! 
I'm using the <a href="https://chrome.google.com/webstore/detail/github-dark-theme/odkdlljoangmamjilkamahebpkgpeacp" target="_blank">Github Dark Theme</a> extension and your add-ons don't look good. Can you fix it?

Greetings Marcin
![image](https://user-images.githubusercontent.com/55882206/87229794-823bc300-c3ab-11ea-8978-88346ec324d4.png)

**Comment by anuraghazra** [comment]
@MarcinK50 thanks for reporting,  i see, i don't think there is anything i can do to fix it. 

Only thing i can do is just remove the background color from that card but then the text will blend with the dark color.

Or i might give user's option to choose dark theme card with a url param `?theme=dark` but you have to do it manually then, there is no way i can do it automatically.

**Comment by MarcinK50** [comment]
Thanks for the quick reply! Tes, you can make a special url for dark mode

**Comment by anuraghazra** [comment]
@MarcinK50 yup i will see what i can do :D

**Comment by anuraghazra** [comment]
Meanwhile, you can also try to implement it too :D

**Comment by anuraghazra** [comment]
@MarcinK50 I think you can make use of #27 to make the cards look good on darkmode 😄 after it gets merged.

**Comment by MarcinK50** [comment]
Thanks!

**Comment by anuraghazra** [comment]
Hey @MarcinK50 now you can make use of card customization feature to make it look good on darkmode! :partying_face: 



[![Anurag's github stats](https://github-readme-stats.vercel.app/api?username=MarcinK50&show_icons=true&title_color=fff&icon_color=79ff97&text_color=9f9f9f&bg_color=151515)](https://github.com/anuraghazra/github-readme-stats)

**Comment by anuraghazra** [comment]
I hope it solves your issue, feel free to open any issue if you have any question or found any bugs :D Thanks!

**Comment by vishalsingh2972** [comment]
> ?theme=dark

@anuraghazra how to change the heading text "Marcin's Github Stats" ?
