### ISSUE TITLE
Github Stats card: Private commits count actually counts private contributions

### ISSUE THREAD

**Issue by harry-graham** [anuraghazra/github-readme-stats#2500]
Discussed in https://github.com/anuraghazra/github-readme-stats/discussions/2498.

## Overview

On the Github stats card, when using the option `count_private`, it is supposed to include private commits in the total commits count. However, it actually includes **private contributions** in the total commits count, which is not the same thing, as explained [here](https://github.com/anuraghazra/github-readme-stats/discussions/1679).

## Details

The [option](https://github.com/anuraghazra/github-readme-stats#stats-card-exclusive-options) on the stats card:

![image](https://user-images.githubusercontent.com/35763376/216847128-6e1d98c9-22e6-427a-a47c-c365048271c5.png)

The [code](https://github.com/anuraghazra/github-readme-stats/blob/112000667c01f18fd161f204ae3ee796ec2e3011/src/fetchers/stats-fetcher.js#L235-L248) used to generate the total commit number actually uses a private contributions value from the Github API:

![image](https://user-images.githubusercontent.com/35763376/216847204-618ca8ab-38d9-4608-b3c8-644b105d361e.png)

The property in the [Github GraphQL API schema file](https://github.com/octokit/graphql-schema/blob/main/schema.graphql#L5708-L5712), along with the comment of what it represents:

![image](https://user-images.githubusercontent.com/35763376/216847292-33d2437c-c4fd-46e0-a8b0-7c613bc516dd.png)

**Comment by rickstaa** [comment]
@harry-graham Thanks for bringing the distinction to our attention! The documentation could indeed be updated. Please feel free to create a PR, and I will review it. The best way to get correct commits is to remove the `count_private` property and deploy your Vercel instance (see https://github.com/anuraghazra/github-readme-stats#deploy-on-your-own-vercel-instance). GRS will then have access to your private commits.

**Comment by Zo-Bro-23** [comment]
I think we should remove the `count_private` option altogether, unless we plan to add a `totalContributions` field in the future.

See [#2504 (comment)](https://github.com/anuraghazra/github-readme-stats/pull/2504#issuecomment-1423864367).

**Comment by rickstaa** [comment]
Followed up by #2517.
