### ISSUE TITLE
Help, i want to get stats for my orgs repos

### ISSUE THREAD

**Issue by duckytutorials** [anuraghazra/github-readme-stats#2511]
### Describe the bug

I cant get the stats

### Expected behaviour

To show image of repo stats

**Comment by Zo-Bro-23** [comment]
Hi @duckytutorials, can you please show us the code (image URL) you are using? The repo pin card should technically work for organizations too:

![](https://github-readme-stats.vercel.app/api/pin?username=git&repo=git&theme=onedark&show_owner=true)

**Comment by Zo-Bro-23** [comment]
We currently don't support organization stats (#1). You can pin org repos, but you can't use org accounts for stats or top langs.
