### ISSUE TITLE
Stats card in an iframe does not displayed properly in Firefox

### ISSUE THREAD

**Issue by Soham52** [anuraghazra/github-readme-stats#2512]
### Describe the bug

When displaying the stats card in an iframe in a website the size of the stats card is much less than that of the iframe.
Given below are a few comparisons done in Chrome and Firefox -

### Screenshots / Live demo link

Chrome -
![image](https://user-images.githubusercontent.com/73898737/218245778-71f4ab9d-4564-468f-806d-f0c150df634b.png)
Fireox -
![image](https://user-images.githubusercontent.com/73898737/218245803-ba6f97cb-f54c-4c77-bf79-fe2784286ec0.png)

### Additional context

This can also be seen in your personal website @anuraghazra 
![image](https://user-images.githubusercontent.com/73898737/218245860-61a91546-d8f3-4306-9349-cfc11de6606b.png)

P.S - To make sure this is not an bug on my side I have reinstalled both chrome and Firefox but the results remain the same, though I am not sure if I'm doing everything correctly.

**Comment by Zo-Bro-23** [comment]
Hi @Soham52, thanks for the bug report! Could you please provide links to the website you're hosting these images in, as well as Anurag's personal website? Thanks :)

**Comment by Soham52** [comment]
> Hi @Soham52, thanks for the bug report! Could you please provide links to the website you're hosting these images in, as well as Anurag's personal website? Thanks :)

Well.. my website was hosted using live server so its not public, but here's Anurag's website [Anurag](https://anuraghazra.dev/)

**Comment by Zo-Bro-23** [comment]
Okay, I see that [Anurag's website](https://anuraghazra.dev/#projects) uses an iFrame too, but I don't really get the error you describe. What do you mean when you say that the size of the card is less than the size of the iFrame?

**Comment by Soham52** [comment]
> Okay, I see that [Anurag's website](https://anuraghazra.dev/#projects) uses an iFrame too, but I don't really get the error you describe. What do you mean when you say that the size of the card is less than the size of the iFrame?
![image](https://user-images.githubusercontent.com/73898737/218247858-c88b60c5-be87-408c-9b5b-b6d1cf25ffec.png)
This is how it looks in Chrome
![image](https://user-images.githubusercontent.com/73898737/218247927-6967649b-4cea-494b-b615-31c58089db69.png)
This is how it looks in Firefox
I think now you'll be able to understand what I described originally

**Comment by Zo-Bro-23** [comment]
Oh. It's likely an issue with SVGs and iFrames in general, and nothing particular with the github-readme-stats card. Try StackOverflow?

@rickstaa do you have any idea why this is?

**Comment by rickstaa** [comment]
> Oh. It's likely an issue with SVGs and iFrames in general, and nothing particular with the github-readme-stats card. Try StackOverflow?
> 
> @rickstaa do you have any idea why this is?

I did not have time to dive into this, but this looks like a problem with how Firefox handles SVGs inside Iframes. And is, therefore, an upstream issue:

- https://bugzilla.mozilla.org/show_bug.cgi?id=1342800
- https://stackoverflow.com/questions/45550864/my-svg-wont-scale
- https://stackoverflow.com/questions/28702218/svg-with-mask-injected-in-iframe-is-broken-in-firefox
- https://support.mozilla.org/en-US/questions/1236443

There might be a patch we can apply to GRS to fix this, but this seems like a specific use case. Feel free to create PRs if you find a solution 👍🏻.

**Comment by Zo-Bro-23** [comment]
Upstream issue :(
