### ISSUE TITLE
I think we should remove the `count_private` option altogether, unless we plan to add a `totalContributions` field in the future.

### ISSUE THREAD

**Issue by mrsanchez90** [anuraghazra/github-readme-stats#2517]
I think we should remove the `count_private` option altogether, unless we plan to add a `totalContributions` field in the future.

See [#2504 (comment)](https://github.com/anuraghazra/github-readme-stats/pull/2504#issuecomment-1423864367).

_Originally posted by @Zo-Bro-23 in https://github.com/anuraghazra/github-readme-stats/issues/2500#issuecomment-1423936231_

**Comment by rickstaa** [comment]
I agree. @anuraghazra, see my comment in https://github.com/anuraghazra/github-readme-stats/issues/2500#issuecomment-1420570545.

**Comment by mrsanchez90** [comment]
We’re are u all from im in wa

**Comment by RinSoftwareDeveloper** [comment]
I think that it should be left in because it is a feature with the basic default GitHub activity page.
