### ISSUE TITLE
Border radius not working

### ISSUE THREAD

**Issue by IshanJ25** [anuraghazra/github-readme-stats#2523]
#### I tried applying custom value to the corner radius field, but it is not showing any effect even after many hours:

```md
![](https://github-readme-stats-sigma-five.vercel.app/api?username=IshanJ25&include_all_commits=true&count_private=true&hide=stars&show_icons=true&hide_rank=true&include_all_commits=true&line_height=28&title_color=0C5851&text_color=0C5851&icon_color=0C5851&bg_color=315,1DE7CF,7880E2&hide_border=true&cache_seconds=14400&locale=en&border_radius=8&card_width=300)<br>
```
i used `border_radius=8` here but it doesn't seem to work.

![](https://github-readme-stats-sigma-five.vercel.app/api?username=IshanJ25&include_all_commits=true&count_private=true&hide=stars&show_icons=true&hide_rank=true&include_all_commits=true&line_height=28&title_color=0C5851&text_color=0C5851&icon_color=0C5851&bg_color=315,1DE7CF,7880E2&hide_border=true&cache_seconds=14400&locale=en&border_radius=8&card_width=300)<br>

see how the corner radius is still 4.5:
![image](https://user-images.githubusercontent.com/86649457/219364238-69917298-ed31-411a-9772-490c4e163f10.png)

**Comment by Zo-Bro-23** [comment]
![](https://github-readme-stats.vercel.app/api?username=IshanJ25&include_all_commits=true&count_private=true&hide=stars&show_icons=true&hide_rank=true&include_all_commits=true&line_height=28&title_color=0C5851&text_color=0C5851&icon_color=0C5851&bg_color=315,1DE7CF,7880E2&hide_border=true&cache_seconds=14400&locale=en&border_radius=8&card_width=300)<br>

```md
![](https://github-readme-stats.vercel.app/api?username=IshanJ25&include_all_commits=true&count_private=true&hide=stars&show_icons=true&hide_rank=true&include_all_commits=true&line_height=28&title_color=0C5851&text_color=0C5851&icon_color=0C5851&bg_color=315,1DE7CF,7880E2&hide_border=true&cache_seconds=14400&locale=en&border_radius=8&card_width=300)<br>
```

Please use the public Vercel deployment. The `sigma-five` deployment is likely not up-to-date with `master`.
