### ISSUE TITLE
"Shadow" themes are meant to be darker...

### ISSUE THREAD

**Issue by Etanarvazac** [anuraghazra/github-readme-stats#2530]
The themes in the pull request #2529 are meant to be darker. In my opinion, if it was up to WebAIM, even dark modes would be too bright. If anything, these three Shadow Themes could be accompanied by a warning that notes "These themes might not be visible to all audiences!". Below is first the theme previews I made, and then the quoted comment left by the accursed bot.

![GitHub_Stats_Shadow_Dark](https://user-images.githubusercontent.com/55290878/219927614-7b5c6518-2db0-4ab6-8d94-a8dbbfb27054.PNG)
![GitHub_Stats_Shadow_Light](https://user-images.githubusercontent.com/55290878/219927618-cb134044-500d-4223-ab60-bcff26855b80.PNG)

              Some themes are invalid. See the [Automated Theme Preview](https://github.com/anuraghazra/github-readme-stats/pull/2529#issuecomment-1435872256) comment above for more information.

_Originally posted by @github-actions[bot] in https://github.com/anuraghazra/github-readme-stats/pull/2529#pullrequestreview-1304719326_

**Comment by Zo-Bro-23** [comment]
See [#2529 (comment)](https://github.com/anuraghazra/github-readme-stats/pull/2529#issuecomment-1435905229).
