### ISSUE TITLE
Language card_width is `50px` more than the assigned value.

### ISSUE THREAD

**Issue by MD-REHMAN** [anuraghazra/github-readme-stats#2534]
### Describe the bug

I found a really small bug, mostly happening because of the below line.

https://github.com/anuraghazra/github-readme-stats/blob/ba7c2f8b55eac8452e479c8bd38b044d204d0424/src/cards/top-languages-card.js#L320

Or maybe because of the default padding.

### Expected behaviour

The card width should not exceed the provided width.

### Screenshots / Live demo link

This can view on my [Profile's README.md](https://github.com/MD-REHMAN)

### Additional context

Expected solution:
1. At least mention the behaviour in docs (README.md).
2. Update the code, so that the added padding would not affect the assigned card width.

**Comment by MD-REHMAN** [comment]
@anuraghazra I can create PR for the fix. But which solution is ideal according to you?

**Comment by Zo-Bro-23** [comment]
![](https://github-readme-stats.vercel.app/api/top-langs/?username=MD-REHMAN&layout=compact&theme=dark&bg_color=0C1116&title_color=F6882B&card_width=445)

<img src="https://github-readme-stats.vercel.app/api/top-langs/?username=MD-REHMAN&layout=compact&theme=dark&bg_color=0C1116&title_color=F6882B" width="445">

Can reproduce.

**Comment by Zo-Bro-23** [comment]
@rickstaa thoughts? @MD-REHMAN feel free to create a PR for this!

**Comment by Zo-Bro-23** [comment]
> @anuraghazra I can create PR for the fix. But which solution is ideal according to you?

I'm not very familiar with SVG and CSS, so I'm not sure if changing padding will break anything else. I'll let @rickstaa decide.

**Comment by rickstaa** [comment]
> > @anuraghazra I can create PR for the fix. But which solution is ideal according to you?
> 
> I'm not very familiar with SVG and CSS, so I'm not sure if changing padding will break anything else. I'll let @rickstaa decide.

I'm aware of this issue, bit didn't think it was a big deal. I, however, understand that people might be confused by the current behaviour. I'm happy to review a PR if somebody creates one. Should be a simple change making sure that the padding is applied while having the width be the width supplied by the user. 👍🏻

**Comment by rickstaa** [comment]
This was fixed in https://github.com/anuraghazra/github-readme-stats/pull/2536. @MD-REHMAN thanks a lot for the fix!
