### ISSUE TITLE
Stats overlapping in stats card

### ISSUE THREAD

**Issue by sumitrana31** [anuraghazra/github-readme-stats#254]
The value of stats in some cases is overlapping the key. As you can see in the screen shot, the values of 'total commits' and 'contributed to' section :
![image](https://user-images.githubusercontent.com/38491769/88793935-454d3a00-d1bb-11ea-86e9-91b84b2f6bac.png)

**Comment by anuraghazra** [comment]
Hi @sumitrana31 thanks for reporting the issue, can you please provide information about your system & browser. Thanks!

**Comment by sumitrana31** [comment]
I am using Mozilla Firefox 68.10.0esr on kali linux 5.7.0-kali1-amd64
 @anuraghazra

**Comment by karate** [comment]
"Contributed" looks good to me, but Total commits are overlapping.
Firefox 76 on Fedora and Firefox 81 on Arch.

![2020-10-19--16-19-21--490x188-scrot](https://user-images.githubusercontent.com/1358965/96456385-15945800-1227-11eb-927a-4f4943c827b6.png)
