### ISSUE TITLE
This Serverless Function has crashed.

### ISSUE THREAD

**Issue by razonyang** [anuraghazra/github-readme-stats#2540]
### Describe the bug

```log
This Serverless Function has crashed.

Your connection is working correctly.

Vercel is working correctly.

500: INTERNAL_SERVER_ERROR
Code: FUNCTION_INVOCATION_FAILED
ID: hkg1::ndb9q-1677309790425-d1a54ae45668
```

### Screenshots / Live demo link

https://github-readme-stats.vercel.app/api/pin/?username=razonyang&repo=hugo-theme-bootstrap

**Comment by MR-Addict** [comment]
Yeah, I find it just crashed too.

![image](https://user-images.githubusercontent.com/75357598/221344904-b1d2b11a-e0b6-4d92-bb9c-18beb8684e7c.png)

**Comment by Zo-Bro-23** [comment]
@anuraghazra? Or does @rickstaa have access to the logs?

**Comment by FarmerChillax** [comment]
Same!

**Comment by taham8875** [comment]
Same for mew

**Comment by jventura1738** [comment]
I am guessing this is causing:
<img width="517" alt="Cards not loading" src="https://user-images.githubusercontent.com/55901784/221346703-1f89240a-e7be-4906-861d-c23225f312d7.png">

**Comment by Zo-Bro-23** [comment]
#2542 messed things up. I'm trying to get it fixed.

**Comment by mathewbushuru** [comment]
I think is is being  caused by a missing `}` at the end of `themes/index.js`. I just tested it and it is working with my own deployment ([here](https://mathewb-github-stats.vercel.app/api?hide=stars%2Cissues&count_private=true&username=mathewbushuru&show_icons=true))

**Comment by Zo-Bro-23** [comment]
> I think is is being  caused by a missing `}` at the end of `themes/index.js`. I just tested it and it is working with my own deployment ([here](https://mathewb-github-stats.vercel.app/api?hide=stars%2Cissues&count_private=true&username=mathewbushuru&show_icons=true))

I figured that out, but I need two approvals to revert the merge. Pinging the other collaborators now.

**Comment by rickstaa** [comment]
Fixed 👍🏻.
