### ISSUE TITLE
Top languages sorted by repositories or commits

### ISSUE THREAD

**Issue by MR-Addict** [anuraghazra/github-readme-stats#2545]
### Is your feature request related to a problem? Please describe.

It seems that default top languages is sorted by repositories that contains corresponding language.

But that's not always the case. Top languages sorted by **commits** could be more precise.

### Describe the solution you'd like

Add an options to API like this:

```bash
https://github-readme-stats.vercel.app/api/top-langs?method=repos;
#or
https://github-readme-stats.vercel.app/api/top-langs?method=commits;
```

### Additional context

A similar profile summary project given these two options:

- [https://github-profile-summary-cards.vercel.app/demo.html](https://github-profile-summary-cards.vercel.app/demo.html)

![image](https://user-images.githubusercontent.com/75357598/221354234-9d5ef278-7ec7-4ea5-a3f4-0ff53bedce41.png)

**Comment by Zo-Bro-23** [comment]
Sorting by lines of code would be even better :) Not sure how many API calls this will require though, so maybe we can try to implement it in the [GitHub Action](https://github.com/Zo-Bro-23/grs-action) that's going to be released. This is a low priority though, so feel free to take it up yourselves!

**Comment by MR-Addict** [comment]
I understand that implementing this feature may require additional API calls or resources, and I appreciate your consideration of implementing it in a GitHub Action.
 
 I'll keep an eye on the project and would be happy to contribute to this feature if and when resources become available.

Thank you for maintaining this great project!

**Comment by Zo-Bro-23** [comment]
Let's keep the issue open!

**Comment by rickstaa** [comment]
> Sorting by lines of code would be even better :) Not sure how many API calls this will require though, so maybe we can try to implement it in the [GitHub Action](https://github.com/Zo-Bro-23/grs-action) that's going to be released. This is a low priority though, so feel free to take it up yourselves!

A lot of things can be implemented in the GitHub action 🚀. 

Btw, @MR-Addict the pie chart you show in the examples has already been implemented https://github.com/anuraghazra/github-readme-stats/pull/2099. It just needs a last review from @Zo-Bro-23 or @anuraghazra.

**Comment by Zo-Bro-23** [comment]
Yeah I'll take a look at that when I get some time.

**Comment by rickstaa** [comment]
> Yeah I'll take a look at that when I get some time.

Take your time!

**Comment by anuraghazra** [comment]
I think we've evaluated this long ago, its not feasible to fetch each and every commit of users to calculate the top languages. Way to many api requests will need to be invoked.

**Comment by rickstaa** [comment]
> I think we've evaluated this long ago, its not feasible to fetch each and every commit of users to calculate the top languages. Way to many api requests will need to be invoked.

With the Vercel model, this feature request is indeed infeasable. With the Action, this could be done, but it will change the codebase too much. I think we should merge https://github.com/anuraghazra/github-readme-stats/pull/2111 and make it available under an ENV variable so that we can use it in the GitHub action. For this feature request, I think if people need it, they should create a separate repository when the npm package is released (see https://github.com/anuraghazra/github-readme-stats/pull/2473). I think we can close this one.

**Comment by MR-Addict** [comment]
Ok, I'll keep an eye on it. And I'll take a look at github action.

Again, thinks for your efforts.
