### ISSUE TITLE
[Feature request]: Can you add a parameter that makes the card float to the left or right?

### ISSUE THREAD

**Issue by isArtJay** [anuraghazra/github-readme-stats#256]
**Describe the solution you'd like**
Can you add a parameter that makes the card float to the left or right? This way I can align the two sides of the cards in the same row. Thaks！

**Comment by isArtJay** [comment]
My English is not good, I believe you can understand.

**Comment by nthnchu** [comment]
[**I believe you want to do what this section of the docs outlines.**](https://github.com/anuraghazra/github-readme-stats#quick-tip-align-the-repo-cards) I don't think it is possible to control this in the svg code, so I don't think a parameter could be added, if I understand you correctly.

---

### Quick Tip (Align The Repo Cards)

You usually won't be able to layout the images side by side. To do that you can use this approach:

```md
<a href="https://github.com/anuraghazra/github-readme-stats">
  <img align="left" src="https://github-readme-stats.vercel.app/api/pin/?username=anuraghazra&repo=github-readme-stats" />
</a>
<a href="https://github.com/anuraghazra/convoychat">
  <img align="left" src="https://github-readme-stats.vercel.app/api/pin/?username=anuraghazra&repo=convoychat" />
</a>
```

**Comment by isArtJay** [comment]
> [**I believe you want to do what this section of the docs outlines.**](https://github.com/anuraghazra/github-readme-stats#quick-tip-align-the-repo-cards) I don't think it is possible to control this in the svg code, so I don't think a parameter could be added, if I understand you correctly.
> 
> ### Quick Tip (Align The Repo Cards)
> You usually won't be able to layout the images side by side. To do that you can use this approach:
> 
> ```lisp
> <a href="https://github.com/anuraghazra/github-readme-stats">
>   <img align="left" src="https://github-readme-stats.vercel.app/api/pin/?username=anuraghazra&repo=github-readme-stats" />
> </a>
> <a href="https://github.com/anuraghazra/convoychat">
>   <img align="left" src="https://github-readme-stats.vercel.app/api/pin/?username=anuraghazra&repo=convoychat" />
> </a>
> ```

Thanks, let me try

**Comment by nthnchu** [comment]
Did this work? If so can you close this @isArtJay?

**Comment by isArtJay** [comment]
> Did this work? If so can you close this @isArtJay?

yes，thanks！
