### ISSUE TITLE
Resizing of card - Dynamic

### ISSUE THREAD

**Issue by brundabharadwaj** [anuraghazra/github-readme-stats#2565]
### Is your feature request related to a problem? Please describe.

Based on our ReadMe.md content , it would be great if we get an option to resize the card accordingly

### Describe the solution you'd like

 Expectation: an option to provide size of the card
 Eg : height:100px&width:75px

**Comment by Zo-Bro-23** [comment]
![](https://github-readme-stats.vercel.app/api?username=Zo-Bro-23&theme=onedark&card_width=750)
```md
![](https://github-readme-stats.vercel.app/api?username=Zo-Bro-23&theme=onedark&card_width=75)
```

Use the `card_width` option. Height is calculated automatically, but you can use `line_height` to customize it. `75px` won't work for width though, since we have a minimum width.
