### ISSUE TITLE
Show users's primary language in stats card

### ISSUE THREAD

**Issue by rjoydip** [anuraghazra/github-readme-stats#257]
**Is your feature request related to a problem? Please describe.**
No

**Describe the solution you'd like**
It would be better to add user's primary language in the stats card.

**Additional context**
Related work reference #241 

![image](https://user-images.githubusercontent.com/15318294/88830694-f075e780-d1eb-11ea-81ce-f4414f5961eb.png)
![image](https://user-images.githubusercontent.com/15318294/88830795-13080080-d1ec-11ea-807e-b92ce1c97732.png)

**Comment by anuraghazra** [comment]
This looks good, @rjoydip but i want icons which are uniform & consistent rather than the official icons. :thinking:

**Comment by rjoydip** [comment]
@anuraghazra Right. Do you have any reference for getting icons? I'm struggling to finding out proper site.

**Comment by anuraghazra** [comment]
Let's extract from Icon packages instead of websites, because websites will mostly have inconsistent icon groups. 

Let's try https://react-icons.netlify.com/

**Comment by rjoydip** [comment]
Thanks for the reference I have used this before in react apps.

**Comment by Anish-Shobith** [comment]
Hi there @rjoydip this is a excellent idea , but the above repo you shared seems to be old , not sure if the author is gonna update it anymore , so i found this [devicon](https://github.com/devicons/devicon), and seems to me that it is up to date.

**Comment by rjoydip** [comment]
@Anish-Shobith Do it have public API for getting icons? Like: https://devicons.github.io/devicon/devicon.git/icons/{LANG_NAME}/{LANG_NAME}-original.svg

**Comment by Anish-Shobith** [comment]
@rjoydip are you looking for something like this https://devicons.github.io/devicon/devicon.git/icons/java/java-original.svg
When I visted the main page and clicked on the svg icon and opened it in a new tab I got the same link you shared so I am unsure if both are related anyways
