### ISSUE TITLE
Stats number update

### ISSUE THREAD

**Issue by pchchv** [anuraghazra/github-readme-stats#2583]
### Describe the bug

Stats numbers are not updating. 
I have encountered a problem not updating statistics. In the discussions, there are mentions of people with the same problem, [e.g.](https://github.com/anuraghazra/github-readme-stats/discussions/2582)

### Screenshots / Live demo link

[My bio](https://github.com/pchchv/pchchv) with this problem

### Additional context

Been seeing the problem for about a week

**Comment by ShorenaK** [comment]
I have same issue

**Comment by Zo-Bro-23** [comment]
We cache responses for around four hours by default. This means that stats will only update after four hours. If you want to avoid this for testing purposes you can add a random string to the URL: `?HDJS=hsjdj`. If you want more accurate stats that update more frequently, you can use the GRS GitHub Action (#) which we will be releasing soon.

**Comment by pchchv** [comment]
> accurate

I mean, the stats haven't been updated for about a week

**Comment by pchchv** [comment]
> We cache responses for around four hours by default.

I mean, the stats haven't been updated for about a week

**Comment by Zo-Bro-23** [comment]
> > We cache responses for around four hours by default.
> 
> I mean, the stats haven't been updated for about a week

What stats aren't updating? The contributions need to be for public repos.

**Comment by pchchv** [comment]
> > > We cache responses for around four hours by default.
> > 
> > I mean, the stats haven't been updated for about a week
> 
> What stats aren't updating? The contributions need to be for public repos. 

Yes, only public repos

**Comment by Zo-Bro-23** [comment]
> > > > We cache responses for around four hours by default.
> > > 
> > > I mean, the stats haven't been updated for about a week
> > 
> > What stats aren't updating? The contributions need to be for public repos. 
> 
> Yes, only public repos

Which stats?

**Comment by pchchv** [comment]
> > > > > We cache responses for around four hours by default.
> > > > 
> > > > I mean, the stats haven't been updated for about a week
> > > 
> > > What stats aren't updating? The contributions need to be for public repos. 
> > 
> > Yes, only public repos
> 
> Which stats? 

Top Languages Card 
![Screenshot_20230321-080110_GitHub.jpg](https://user-images.githubusercontent.com/56176644/226523055-ff816e2b-bb5a-4a45-bc68-618a5b002332.jpg)

These numbers persist for about a week, despite several dozen committees to public repositories that are not pics.

**Comment by pchchv** [comment]
@Zo-Bro-23 Is there anything I can do to help find and fix the bug that causes this?

**Comment by Zo-Bro-23** [comment]
@rickstaa knows more about how the stats are calculated. I remember seeing a similar issue and explanation sometime, but I'm not sure on the specifics. I'll let him take this one.

**Comment by pchchv** [comment]
Thank [you](@Zo-Bro-23).
Perhaps we should reopen the issue? Or will the "Closed" status not prevent us from solving the problem?

**Comment by rickstaa** [comment]
This is a known issue (see https://github.com/anuraghazra/github-readme-stats/issues/455). It will be fixed by merging https://github.com/anuraghazra/github-readme-stats/pull/1186.

**Comment by rickstaa** [comment]
> > This is a known issue (see #455). It will be fixed by merging #1186.
> 
> 1. I see discussions only about stat cards, I understand correctly that it works the same for language cards?
> 2. This is a very old problem, and discussed for a long time, I had it only a week ago.
> 3. Is it possible to predict the timing of the merging [Ranking System v2 #1186](https://github.com/anuraghazra/github-readme-stats/pull/1186)?

@1186 is ready to be merged if the weighting is adjusted slightly and @anuraghazra approves it. The incorrect language results can be tracked in https://github.com/anuraghazra/github-readme-stats/issues/1801.
