### ISSUE TITLE
Calculations are wrong

### ISSUE THREAD

**Issue by Lui22** [anuraghazra/github-readme-stats#2585]
### Describe the bug

User with 0 everything gets "A+" level

### Expected behaviour

User with 0 everything gets at least "B" level

### Screenshots / Live demo link

<img width="343" alt="image" src="https://user-images.githubusercontent.com/30185757/226596141-269a675e-3fac-4488-a5d4-9c5338931b1e.png">

### Additional context

I pasted the [calculation code](https://github.com/anuraghazra/github-readme-stats/blob/master/src/calculateRank.js) into my browser's console and tried to calculate rating for all the zeros.
I've got "A+" level.

**Comment by rickstaa** [comment]
@Lui22 thanks for your bug report. This is a known issue and tracked in https://github.com/anuraghazra/github-readme-stats/issues/2265.
