### ISSUE TITLE
Bug: Maximum retries exceeded

### ISSUE THREAD

**Issue by lucasgonze** [anuraghazra/github-readme-stats#2586]
### Describe the bug

The embed on my profile at github.com/lucasgonze is throwing a "Maximum retries exceeded" error.

### Expected behaviour

Not a fail

### Screenshots / Live demo link

<img width="593" alt="image" src="https://user-images.githubusercontent.com/111581/226965358-6f449f7f-5f60-439a-9c6a-8c1875c0cfed.png">

### Additional context

Error message suggests "please add an env variable called pat_1 with your github token in vercel"

**Comment by joshysmart** [comment]
I have the same issue. I just noticed it just now

**Comment by mrmrinal** [comment]
Same here!

![image](https://user-images.githubusercontent.com/77235299/226980894-59009235-4e38-4cba-8a56-3d4cc56b4686.png)

**Comment by Abhijeetbyte** [comment]
# Not again !
![Screenshot_2023-03-23-21-34-58-027](https://user-images.githubusercontent.com/80936610/227264404-89247e26-da0b-472d-812f-98e2db3faeba.jpeg)

**Comment by rickstaa** [comment]
> # Not again !
> ![Screenshot_2023-03-23-21-34-58-027](https://user-images.githubusercontent.com/80936610/227264404-89247e26-da0b-472d-812f-98e2db3faeba.jpeg)

This is a known limitation. I have sent @anuraghazra a new PAT. Meanwhile, [deploy your own Vercel instance](https://github.com/anuraghazra/github-readme-stats#deploy-on-your-own) or try [the experimental GitHub action](https://github.com/marketplace/actions/grs-action).

**Comment by Abhijeetbyte** [comment]
> > # Not again !
> > ![Screenshot_2023-03-23-21-34-58-027](https://user-images.githubusercontent.com/80936610/227264404-89247e26-da0b-472d-812f-98e2db3faeba.jpeg)
> 
> This is a known limitation of GitHub's GraphQL API (see #1471). I have sent @anuraghazra a new PAT. Meanwhile, [deploy your own Vercel instance](https://github.com/anuraghazra/github-readme-stats#deploy-on-your-own) or try [the experimental GitHub action](https://github.com/marketplace/actions/grs-action).

@rickstaa Thanks for your insights
