### ISSUE TITLE
Not again ! Maximum retries exceeded

### ISSUE THREAD

**Issue by Abhijeetbyte** [anuraghazra/github-readme-stats#2588]
### Describe the bug

Crashed 

### Expected behaviour

To show my Stats 

### Screenshots / Live demo link

![Screenshot_2023-03-23-21-34-58-027](https://user-images.githubusercontent.com/80936610/227265033-b9f7066b-38a2-437c-8c5b-0680b9ddefb7.jpeg)

**Comment by LeBeDevCode** [comment]
I am experiencing this problem right now

**Comment by OblivionNoirV2** [comment]
Same thing happening here, it's not just you

**Comment by kms0219kms** [comment]
Duplicate of https://github.com/anuraghazra/github-readme-stats/issues/1471.

**Comment by chrisK824** [comment]
Just fork the repo and deploy in your own vercel instance as per readme instructions, then you will never have downtimes again
