### ISSUE TITLE
Stats not updated in github readme stats card

### ISSUE THREAD

**Issue by krushnatkhawale** [anuraghazra/github-readme-stats#259]
**Describe the bug**

Stats not updated in github readme stats card.

**Expected behavior**
Stats should be updated in github readme stats card.

**Screenshots / Live demo link (paste the github-readme-stats link as markdown image)**
Link to the repository: https://github.com/krushnatkhawale

![image](https://user-images.githubusercontent.com/10601963/88832012-0e315580-d1c8-11ea-83bb-defc84dd1e35.png)

**Additional context**

It worked fine initially and was showing correct stats, I loved the functionality of your repo so I decided to star it so I clicked  ⭐ on your repository so my github count got updated but the card is still showing old value. I thought it could be page refresh but it wasn't, I refreshed(force refreshed as well) more than 5 times but the stats are still old. Visit the repo for live demonstration https://github.com/krushnatkhawale

Operating system: Windows 10
Browser: Google chrome

# Thanks and congrats for such a amazing tool.

**Comment by anuraghazra** [comment]
Thanks for opening the issue @krushnatkhawale 

duplicate of #69 
Checkout this https://github.com/anuraghazra/github-readme-stats/issues/69#issuecomment-658883614

**Comment by krushnatkhawale** [comment]
@anuraghazra  Thanks for the reference links, I think this was 3rd or 4th similar issue reported meaning count label is confusing. I think it should it be changed to avoid confusion, happy for PR it but wanted to know in advance if yes, what should be the label.

**Comment by anuraghazra** [comment]
"Total Stars Gained"
"Total Stars Achieved"


Or maybe something smaller
