### ISSUE TITLE
Complaining about not having a token set

### ISSUE THREAD

**Issue by galaxine-senpai** [anuraghazra/github-readme-stats#2590]
### Describe the bug

When embedded in a profile, it complains that there is not a token provided on some of the "embeds" but not others.

### Expected behaviour

It should display the stats as normal

### Screenshots / Live demo link

***WILL EDIT THIS LATER AS I AM NOT HOME***

### Additional context

This is happening on the link provided by the repo and one I self-hosted on vercel, I am also using a brand new token.

***ISSUE HAS RESOLVED ITSELF BUT WILL LEAVE OPEN FOR THE PROBLEM WITH THE MAIN LINK***

**Comment by 000rosiu** [comment]
The same for me... `Something went wrong! file an issue at https://tiny.one/readme-stats
Maximum retries exceeded Please add an env variable called PAT_1 with your github token in vercel`

**Comment by bnylund** [comment]
Same issue over here.

![image](https://user-images.githubusercontent.com/31191383/228041805-178902da-9cc8-4dca-9259-51e259b31581.png)

**Comment by xPoke-glitch** [comment]
Same for me. It seems like the problem is related to the username - I've tried changing it with the username of one of my friend and it works. But when I change it back to mine, it doesn't work.

**Comment by galaxine-senpai** [comment]
> Same for me. It seems like the problem is related to the username - I've tried changing it with the username of one of my friend and it works. But when I change it back to mine, it doesn't work.

Have you tried using all lowercase? (xpoke-glitch)

**Comment by xPoke-glitch** [comment]
> 

Fixed by changing the API URL like this: `https://github-readme-stats-sigma-five.vercel.app/api` (I added sigma-five to it)

**Comment by galaxine-senpai** [comment]
It should work regardless of which link you use.

**Comment by PencilNavigator** [comment]
> > 
> 
> Fixed by changing the API URL like this: `https://github-readme-stats-sigma-five.vercel.app/api` (I added sigma-five to it)

https://github.com/PencilNavigator/readme-stats-URL
here are also some url that you can use.
