### ISSUE TITLE
The stats card width adjustment not working properly

### ISSUE THREAD

**Issue by slashedzer0** [anuraghazra/github-readme-stats#2591]
### Describe the bug

width adjustment using `card_width` option works just fine if `hide_title` value is `false`.

for example: 
`https://github-readme-stats.vercel.app/api?username=slashedzer0&hide_title=false&card_width=350`

but if `hide_title` value is `true` like this:
`https://github-readme-stats.vercel.app/api?username=slashedzer0&hide_title=true&card_width=350`

the stats card' width still remain in default value (`500`?).

### Expected behaviour

when `hide_title` value is `true`, the stats card' width should follow the appropriate value in the `card_width` option if the value is changed.

**Comment by rickstaa** [comment]
@slashedzer0 Thanks for your bug report. I, checked, but I could not reproduce it (see examples below).

### Hide_title FALSE

#### Default with

[![Anurag's GitHub stats](https://github-readme-stats.vercel.app/api?username=anuraghazra)](https://github.com/anuraghazra/github-readme-stats)

```md
[![Anurag's GitHub stats](https://github-readme-stats.vercel.app/api?username=anuraghazra)](https://github.com/anuraghazra/github-readme-stats)
```

#### Width 399

[![Anurag's GitHub stats](https://github-readme-stats.vercel.app/api?username=anuraghazra&card_width=399)](https://github.com/anuraghazra/github-readme-stats)

```md
[![Anurag's GitHub stats](https://github-readme-stats.vercel.app/api?username=anuraghazra&card_width=399)](https://github.com/anuraghazra/github-readme-stats)
```

#### Width 500

[![Anurag's GitHub stats](https://github-readme-stats.vercel.app/api?username=anuraghazra&card_width=500)](https://github.com/anuraghazra/github-readme-stats)

```md
[![Anurag's GitHub stats](https://github-readme-stats.vercel.app/api?username=anuraghazra&card_width=500)](https://github.com/anuraghazra/github-readme-stats)
```

### Hide_title TRUE

#### Default with

[![Anurag's GitHub stats](https://github-readme-stats.vercel.app/api?username=anuraghazra&hide_title=true)](https://github.com/anuraghazra/github-readme-stats)

```md
[![Anurag's GitHub stats](https://github-readme-stats.vercel.app/api?username=anuraghazra&hide_title=true)](https://github.com/anuraghazra/github-readme-stats)
```

#### Width 399

[![Anurag's GitHub stats](https://github-readme-stats.vercel.app/api?username=anuraghazra&card_width=399&hide_title=true)](https://github.com/anuraghazra/github-readme-stats)

```md
[![Anurag's GitHub stats](https://github-readme-stats.vercel.app/api?username=anuraghazra&card_width=399&hide_title=true)](https://github.com/anuraghazra/github-readme-stats)
```

#### Width 500

[![Anurag's GitHub stats](https://github-readme-stats.vercel.app/api?username=anuraghazra&card_width=500&hide_title=true)](https://github.com/anuraghazra/github-readme-stats)

```md
[![Anurag's GitHub stats](https://github-readme-stats.vercel.app/api?username=anuraghazra&card_width=500&hide_title=true)](https://github.com/anuraghazra/github-readme-stats)
```

### Hide_title TRUE before width

#### Default with

[![Anurag's GitHub stats](https://github-readme-stats.vercel.app/api?username=anuraghazra&hide_title=true)](https://github.com/anuraghazra/github-readme-stats)

```md
[![Anurag's GitHub stats](https://github-readme-stats.vercel.app/api?username=anuraghazra&hide_title=true)](https://github.com/anuraghazra/github-readme-stats)
```

#### Width 399

[![Anurag's GitHub stats](https://github-readme-stats.vercel.app/api?username=anuraghazra&hide_title=true&card_width=399)](https://github.com/anuraghazra/github-readme-stats)

```md
[![Anurag's GitHub stats](https://github-readme-stats.vercel.app/api?username=anuraghazra&hide_title=true&card_width=399)](https://github.com/anuraghazra/github-readme-stats)
```

#### Width 500

[![Anurag's GitHub stats](https://github-readme-stats.vercel.app/api?username=anuraghazra&hide_title=true&card_width=500)](https://github.com/anuraghazra/github-readme-stats)

```md
[![Anurag's GitHub stats](https://github-readme-stats.vercel.app/api?username=anuraghazra&hide_title=true&card_width=500)](https://github.com/anuraghazra/github-readme-stats)
```
