### ISSUE TITLE
Something went wrong! file an issue at https://tiny.one/readme-stats

### ISSUE THREAD

**Issue by BunyaminYavuz** [anuraghazra/github-readme-stats#2610]
Something went wrong! file an issue at https://tiny.one/readme-stats
Maximum retries exceeded Please add an env variable called PAT_1 with your github token in vercel

What is the quick-fix???

_Originally posted by @BunyaminYavuz in https://github.com/anuraghazra/github-readme-stats/issues/2404#issuecomment-1502097635_

**Comment by rickstaa** [comment]
@BunyaminYavuz Thanks for your bug report. This is a known issue, see https://github.com/anuraghazra/github-readme-stats/issues/1471). For now, please [deploy your own Vercel instance](https://github.com/anuraghazra/github-readme-stats#deploy-on-your-own).
