### ISSUE TITLE
Medium Stats

### ISSUE THREAD

**Issue by 0p3r4t0r** [anuraghazra/github-readme-stats#2615]
### Is your feature request related to a problem? Please describe.

Create a tile to pull stats or perhaps recent publications from https://medium.com

### Describe the solution you'd like

Use the [medium API](https://docs.mediumapi.com/) to show recently published articles

### Additional context

I would be happy to implement this and make a PR if there is any interest.

**Comment by PencilNavigator** [comment]
hm, this is "github-readme-stats" not "medium-readme-stats", so i think the devs are likely not going to support it.
You can try edit the source code of GRS yourself.

**Comment by 0p3r4t0r** [comment]
That's a very good point :laughing:. Thanks!
