### ISSUE TITLE
Is it possible for the stat card to include all the public repos created under my account instead of repos created in the past year?

### ISSUE THREAD

**Issue by Battery233** [anuraghazra/github-readme-stats#262]
**Is your feature request related to a problem? Please describe.**
It seems that the stat card will only calculate the data of this year, thus my old repos (more than a year old) are not included in the stat card

**Describe the solution you'd like**
Please add an option for customizing the time range for the stats card

**Describe alternatives you've considered**
... or add an option of "stat of this year" & "stat of all repos"

Thanks!

**Comment by Battery233** [comment]
> Hi @Battery233 can you be specific of which others stats are you talking about ?? `calculate all stats in the history`

Hi, sorry for the confusion. I mean that the repositories created during the previous years may not be included in the cards. It seems that some of old repos are not counted for the commits in the stats card and favourite languages in the language card (e.g. in my GitHub, there is a llvm repo but llvm is not listed in my favourite programming language list)😊

**Comment by anuraghazra** [comment]
> (e.g. in my GitHub, there is a llvm repo but llvm is not listed in my favourite programming language list)

Having a llvm repo does not mean it would show up in the language card, as it says its "Most Used Languages"

>  The problem is that some of the repositories created during the previous years may not be included when calculating

All repos are being calculated there is not year limit on that, only limit is 100 repo max fetch limit and you only have 17repos
