### ISSUE TITLE
Something went wrong! file an issue at https://tiny.one/readme-stats

### ISSUE THREAD

**Issue by mohamedmehdigara** [anuraghazra/github-readme-stats#2620]
### Describe the bug

Github status not appearing on my readme.

### Additional context

Something went wrong! file an issue at https://tiny.one/readme-stats
Maximum retries exceeded Please add an env variable called PAT_1 with your github token in vercel

**Comment by tifandotme** [comment]
![image](https://user-images.githubusercontent.com/33323177/232543953-8df4e23e-9410-4264-82e8-33caf42e47de.png)

**Comment by Deku333** [comment]
Same error here

**Comment by Kenny1291** [comment]
https://github.com/anuraghazra/github-readme-stats/issues/1471

**Comment by AyomideA-S** [comment]
Same here!

**Comment by eduardoAmroginski** [comment]
Same here!

**Comment by tifandotme** [comment]
> ![image](https://user-images.githubusercontent.com/33323177/232543953-8df4e23e-9410-4264-82e8-33caf42e47de.png)

I fixed mine by creating my own Vercel instance

**Comment by AyomideA-S** [comment]
> > ![image](https://user-images.githubusercontent.com/33323177/232543953-8df4e23e-9410-4264-82e8-33caf42e47de.png)
> 
> I fixed mine by creating my own Vercel instance

And, if I may ask, how exactly did you go about that?

**Comment by larrasu** [comment]
> > > ![image](https://user-images.githubusercontent.com/33323177/232543953-8df4e23e-9410-4264-82e8-33caf42e47de.png)
> > 
> > 
> > I fixed mine by creating my own Vercel instance
> 
> And, if I may ask, how exactly did you go about that?

It says here on the README: https://github.com/anuraghazra/github-readme-stats#on-vercel

**Comment by IT21266300** [comment]
same here

**Comment by PencilNavigator** [comment]
https://github.com/anuraghazra/github-readme-stats/issues/2415
solution here

**Comment by rickstaa** [comment]
This is a known issue (see https://github.com/anuraghazra/github-readme-stats/issues/1471).
