### ISSUE TITLE
file an issue at https://tiny.one/readme-stats

### ISSUE THREAD

**Issue by IT21266300** [anuraghazra/github-readme-stats#2626]
### Describe the bug

Github status not appearing on my readme. Yesterday it work perfectly.  

### Expected behaviour

I want display my GitHub status on my readme file

### Screenshots / Live demo link

![image](https://user-images.githubusercontent.com/88578813/233452765-cd0f669d-6502-441c-95e0-93c940a42ba0.png)

### Additional context

error message is "Something went wrong! file an issue at https://tiny.one/readme-stats
Maximum retries exceeded Please add an env variable called PAT_1 with your github token in vercel"

**Comment by IT21266300** [comment]
now it works perfectly.

**Comment by PencilNavigator** [comment]
Create your own vercel instance or use https://github.com/anuraghazra/github-readme-stats/issues/2415 to avoid this issue.
