### ISSUE TITLE
 Look at that error .How to fix this ??

### ISSUE THREAD

**Issue by RohanDhalpe** [anuraghazra/github-readme-stats#2648]
### Describe the bug

![Screenshot (55)](https://user-images.githubusercontent.com/90591344/234612414-82baeb43-e1f1-449a-853e-cf0148f722d9.png)

**Comment by sollambert** [comment]
Looks like their limit was reached for content requests. Might need to deploy to our own vercel instances if it doesn't iron itself out.

**Comment by qwerty541** [comment]
See #1471

**Comment by PencilNavigator** [comment]
https://github.com/anuraghazra/github-readme-stats/issues/2415
