### ISSUE TITLE
Stats do not appear when using 'Safari'

### ISSUE THREAD

**Issue by viniciusml** [anuraghazra/github-readme-stats#265]
**Describe the bug**
When adding the stats to the 'README.md' file, the 'stats' appear empty. They appear if I open the box in a separate tab. Also, If I open on 'Chrome', it works fine.

**Expected behavior**
The stats are expected to appear.

**Screenshots / Live demo link (paste the github-readme-stats link as markdown image)**
<img width="482" alt="Screenshot 2020-07-30 at 11 58 37" src="https://user-images.githubusercontent.com/44158512/88911109-a594b800-d25d-11ea-9460-7dee8e1dae43.png">

**Comment by nthnchu** [comment]
What is your macOS version and your Safari version @viniciusml? It works fine for me on Safari 13.1.1.

---
### Live demo:
![Anurag Hazra's GitHub Stats](https://github-readme-stats.vercel.app/api?username=anuraghazra)

**Comment by viniciusml** [comment]
I am using Safari Version 13.1, macOS Catalina Version 10.15.4.

This is how the attachments you sent appear to me:

<img width="711" alt="Screenshot 2020-07-30 at 18 42 28" src="https://user-images.githubusercontent.com/44158512/88950094-6df53280-d294-11ea-9942-aca44dfa6611.png">

**Comment by anuraghazra** [comment]
related to #120 #59

**Comment by rickstaa** [comment]
I just checked this in the latest version of safari, and I can not reproduce the problem anymore. I am closing this for now. Please comment below if the problem still exists on your system.
