### ISSUE TITLE
Gruvbox Theme 

### ISSUE THREAD

**Issue by JawherBenjeddou** [anuraghazra/github-readme-stats#2658]
### Describe the bug

When chosing gruvbox theme its not working

**Comment by rickstaa** [comment]
![Anurag's GitHub stats](https://github-readme-stats.vercel.app/api?username=anuraghazra&theme=gruvbox)

```md
![Anurag's GitHub stats](https://github-readme-stats.vercel.app/api?username=anuraghazra&theme=gruvbox)
```` 

[![Top Langs](https://github-readme-stats.vercel.app/api/top-langs/?username=anuraghazra&theme=gruvbox)](https://github.com/anuraghazra/github-readme-stats)

```md
[![Top Langs](https://github-readme-stats.vercel.app/api/top-langs/?username=anuraghazra&theme=gruvbox)](https://github.com/anuraghazra/github-readme-stats)
```

[![Readme Card](https://github-readme-stats.vercel.app/api/pin/?username=anuraghazra&repo=github-readme-stats&theme=gruvbox)](https://github.com/anuraghazra/github-readme-stats)

```md
[![Readme Card](https://github-readme-stats.vercel.app/api/pin/?username=anuraghazra&repo=github-readme-stats&theme=gruvbox)](https://github.com/anuraghazra/github-readme-stats)
```
