### ISSUE TITLE
wakatime card stopped working suddenly

### ISSUE THREAD

**Issue by jNaimXIII** [anuraghazra/github-readme-stats#2671]
I've been using the wakatime card for a while to show my most used languages. it randomly started showing an error saying my username doesn't exist even though it's completely fine.

<img width="646" alt="image" src="https://user-images.githubusercontent.com/115424698/235397553-3f16a3af-49a9-44b3-9026-ceaf26a6e8fc.png">
<img width="1199" alt="image" src="https://user-images.githubusercontent.com/115424698/235397591-eb03c0c3-b03a-4878-946d-9ce8a9d953d9.png">

https://wakatime.com/jNaimXIII

**Comment by brutalzinn** [comment]
I having the same issue.

**Comment by Enaium** [comment]
same here

**Comment by Yoak3n** [comment]
same issue

**Comment by sabin5105** [comment]
Me either

**Comment by brutalzinn** [comment]
Wakatime reported issues on generate stats yesterday at 01:30 AM.

**Comment by chrisK824** [comment]
+1 here

**Comment by forgetfulskybro** [comment]
+1 here

**Comment by ArikSetyawan** [comment]
same issue

**Comment by SwiftlyAside** [comment]
same here.

**Comment by Aleksey-Voko** [comment]
Adding a parameter worked for me: `&range=all_time`

**Comment by aylmerbolzan** [comment]
Even putting the `&range=all_time` parameter at the end of the URL didn't work for me 🤔

**Comment by HassanYu7** [comment]
> Even putting the `&range=all_time` parameter at the end of the URL didn't work for me 🤔

Me either

**Comment by Aleksey-Voko** [comment]
> Even putting the `&range=all_time` parameter at the end of the URL didn't work for me thinking

Perhaps this is due to the presence of compound parameters in the URL, where the values are separated by commas.

`&hide=text,git,other,xml&...`

If you remove such parameters, it will work.
Or maybe somehow enclose them in quotation marks...
Or move to the beginning, before commas...

**Comment by alidehkhodaei** [comment]
I having the same issue.

**Comment by alidehkhodaei** [comment]
Hello, i found a solution.

Add the parameter 'range=last_7_days' and langs_count=5 to the URL.
'range=last_year' or  'range=all_time'  also works.

You can see my link.
https://github-readme-stats.vercel.app/api/wakatime?username=alidehkhodaei&theme=dark&langs_count=5&range=last_7_days

**Comment by aylmerbolzan** [comment]
That's weird, @alidehkhodaei.

The link you pasted there, it didn't work when I tested it in the browser:
https://github-readme-stats.vercel.app/api/wakatime?username=alidehkhodaei&theme=dark&langs_count=5&range=last_7_days
![image](https://user-images.githubusercontent.com/110077540/236158580-c1fdc849-17e8-401b-a5dc-288e4ef71b77.png)

Taking advantage of your observation, I just included the `&range=last_7_days` to my code and it worked. It could be a bug related to the range 🤔
https://github-readme-stats.vercel.app/api/wakatime?username=aylmerbolzan&theme=dracula&hide=text,git,other,xml&langs_count=6&range=last_7_days&custom_title=Desenvolvido%20essa%20semana:
![image](https://user-images.githubusercontent.com/110077540/236159176-469aef6b-1dd5-47e2-8427-ccfeed8371e5.png)

Talvez, o `&range=all_time` até funcione para quem é WakaTime Premium e o `&range=last_7_days` para quem é Free.

**Comment by Aleksey-Voko** [comment]
> Talvez, o `&range=all_time` até funcione para quem é WakaTime Premium e o `&range=last_7_days` para quem é Free.

I have a free account on WakaTime. And `&range=all_time` works well.

https://github-readme-stats.vercel.app/api/wakatime?username=Voko&theme=gotham&hide_border=true&layout=compact&hide_title=true&langs_count=14&range=all_time

**Comment by alidehkhodaei** [comment]
> That's weird, @alidehkhodaei.
> 
> The link you pasted there, it didn't work when I tested it in the browser: https://github-readme-stats.vercel.app/api/wakatime?username=alidehkhodaei&theme=dark&langs_count=5&range=last_7_days ![image](https://user-images.githubusercontent.com/110077540/236158580-c1fdc849-17e8-401b-a5dc-288e4ef71b77.png)
> 
> Taking advantage of your observation, I just included the `&range=last_7_days` to my code and it worked. It could be a bug related to the range 🤔 https://github-readme-stats.vercel.app/api/wakatime?username=aylmerbolzan&theme=dracula&hide=text,git,other,xml&langs_count=6&range=last_7_days&custom_title=Desenvolvido%20essa%20semana: ![image](https://user-images.githubusercontent.com/110077540/236159176-469aef6b-1dd5-47e2-8427-ccfeed8371e5.png)
> 
> Talvez, o `&range=all_time` até funcione para quem é WakaTime Premium e o `&range=last_7_days` para quem é Free.

It don't work for me now😮🤔

**Comment by aylmerbolzan** [comment]
@alidehkhodaei,

Parametrizei seu link dessa forma com `&range=all_time` e deu certo:
https://github-readme-stats.vercel.app/api/wakatime?username=alidehkhodaei&theme=dark&langs_count=5&range=all_time
![image](https://user-images.githubusercontent.com/110077540/236181707-299db95c-455a-4b61-bf03-b2b8f7960bbc.png)

**Comment by alidehkhodaei** [comment]
> @alidehkhodaei,
> 
> I parameterized your link this way with `&range=all_time` and it worked: https://github-readme-stats.vercel.app/api/wakatime?username=alidehkhodaei&theme=dark&langs_count=5&range=all_time ![image](https://user-images.githubusercontent.com/110077540/236181707-299db95c-455a-4b61-bf03-b2b8f7960bbc.png)

Thank you but i want last 7 days😪.

**Comment by nikgalkin** [comment]
I have noticed that API response depends on `Display code time publicly` setting on [settings/profile](https://wakatime.com/settings/profile). If it's set to `Last 7 days` then last_7_days would work fine and so on

**Comment by CodeSteel** [comment]
> I have noticed that API response depends on `Display code time publicly` setting on [settings/profile](https://wakatime.com/settings/profile). If it's set to `Last 7 days` then last_7_days would work fine and so on

This did it!

You can use one of these arguments to configure your embed.

```
&range=last_7_days
&range=last_year
&range=all_time
```

**Comment by nikgalkin** [comment]
>This did it!
>
>You can use one of these arguments to configure your embed.
>
>&range=last_7_days
>&range=last_year
>&range=all_time

Hmm, when I tested I set "Display code time publicly" to "Last 7 days" and any other value like "Last_30_days" was returning forbidden. Perhaps the problem was in the API.

**Comment by rickstaa** [comment]
It should be fixed now that #2662 was merged.

**Comment by rickstaa** [comment]
It looks like the `range` variable is still broken. This bug is tracked at https://github.com/anuraghazra/github-readme-stats/issues/2698.

**Comment by rickstaa** [comment]
It looks that for some users, the solution by @fabianocouto still doesn't fix their card. For example, the user in https://github.com/anuraghazra/github-readme-stats/issues/1348 does have a public profile and the stats can be requested through the browser but through Axios something is broken:

https://wakatime.com/@AbhJ

https://wakatime.com/api/v1/users/AbhJ/stats/all_time?is_including_today=true

**Comment by rickstaa** [comment]
Let's track this in#2671.

**Comment by rickstaa** [comment]
Guys, I just created https://github.com/anuraghazra/github-readme-stats/pull/2707 to make the WakaTime card compatible with the new Wakatime API. I would appreciate it if you could review it, since I don't use the card myself.
