### ISSUE TITLE
readme-stat isn't working

### ISSUE THREAD

**Issue by abirett2** [anuraghazra/github-readme-stats#2676]
### Describe the bug

readme-stat isn't working

**Comment by Jor-ban** [comment]
I'm having the same problem, so I'madding some screenshots
![image](https://user-images.githubusercontent.com/51119083/235735020-debf1058-abde-4d49-a747-e36b9b307e50.png)

**Comment by HimanshuMohanty-Git24** [comment]
Same issue

**Comment by qwerty541** [comment]
Temporary solution there: #2668. Will be fixed automatically after merging #2670.

**Comment by IvanaXu** [comment]
> https://github-readme-stats.vercel.app/api/wakatime?username=willianrod


Same issue

**Comment by Jbziscool** [comment]
> ### Describe the bug
> 
> readme-stat isn't working
> ### Expected behaviour
> 
> _No response_
> ### Screenshots / Live demo link
> 
> _No response_
> ### Additional context
> 
> _No response_


@abirett2 try and have a bit more information since saying readme-stat isn't working isnt doing much, fill out the bug thing

**Comment by abirett2** [comment]
The issue is fixed now.
