### ISSUE TITLE
Wakatime stats  is not working

### ISSUE THREAD

**Issue by IsfetShen** [anuraghazra/github-readme-stats#2683]
### Describe the bug

The card that I use is this: https://github-readme-stats.vercel.app/api/wakatime?username=IsfetShen&theme=midnight-purple 

I checked the readme official and there's also not working

### Screenshots / Live demo link

![image](https://user-images.githubusercontent.com/102725289/236316603-ba0977b6-84b6-4e48-ab42-96526bb744c9.png)

**Comment by qwerty541** [comment]
See #2668

**Comment by rickstaa** [comment]
Should be fixed now that #2662 was merged.
