### ISSUE TITLE
[Feature Request] Assign weight to particular repos for "Most Used Languages"

### ISSUE THREAD

**Issue by isayakmondal** [anuraghazra/github-readme-stats#2693]
### Discussed in https://github.com/anuraghazra/github-readme-stats/discussions/2692

<div type='discussions-op-text'>

<sup>Originally posted by **isayakmondal** May  5, 2023</sup>
So one of my repo has a very large `.ipynb file`, which is messing with my language card statistics, so ideally, I want to give less weight to that repo if possible. I read through the docs and find out that it was possible globally, but I was wondering if it's possible for a particular repository. 
Thank you!</div>

**Comment by rickstaa** [comment]
@isayakmondal Thanks for your request. This feature is currently not yet supported. The only thing we support is changing the [weights of the language algorithm](https://github.com/anuraghazra/github-readme-stats#language-stats-algorithm), [hiding languages](https://github.com/anuraghazra/github-readme-stats#hide-individual-languages) and [excluding repositories](https://github.com/anuraghazra/github-readme-stats#exclude-individual-repositories). It might be possible to create the language stats of your liking if https://github.com/anuraghazra/github-readme-stats/pull/2409 is merged in the future.
