### ISSUE TITLE
Something went wrong! file an issue at https://tiny.one/readme-stats

### ISSUE THREAD

**Issue by alnahian2003** [anuraghazra/github-readme-stats#2695]
### Describe the bug

![image](https://user-images.githubusercontent.com/61485238/236499782-31bd87b6-0e0d-4923-8e32-1c85dcc88268.png)

Hey, I've been using this excellent solution for the last couple of years, and I LOVE this!
But now it seems like it's **having some issues showing the stats on my GitHub readme**, or **is there any changes I need to configure manually**?

For your convenience, I already hard-reload the cache on my browser, in case it's only occurring on my side. 

Thank you, have a great day!

- Al Nahian

### Screenshots / Live demo link

https://camo.githubusercontent.com/757bd6c48ed4f361b2126772b6ecc5be87208ddd64aca93e0afd09445a406768/68747470733a2f2f6769746875622d726561646d652d73746174732e76657263656c2e6170702f6170693f757365726e616d653d616c6e616869616e323030332673686f775f69636f6e733d74727565267468656d653d76756526696e636c7564655f616c6c5f636f6d6d6974733d74727565

**Comment by qwerty541** [comment]
See #1471

**Comment by PencilNavigator** [comment]
https://github.com/anuraghazra/github-readme-stats/issues/2415

**Comment by alnahian2003** [comment]
Great thanks! Will look into this
