### ISSUE TITLE
[Feature Request] Organization stats

### ISSUE THREAD

**Issue by angeousta** [anuraghazra/github-readme-stats#2702]
### Is your feature request related to a problem? Please describe.

https://github.com/anuraghazra/github-readme-stats is about an user stats, but I'd like to have stats of an org

Like what's the most used language in the org? what are the highest star a repo has received? and so on...

**Comment by rickstaa** [comment]
Duplicate of https://github.com/anuraghazra/github-readme-stats/issues/654.
