### ISSUE TITLE
All stats seem to be lost after changing github username

### ISSUE THREAD

**Issue by kristinabrueva** [anuraghazra/github-readme-stats#2703]
### Describe the bug

All stats seem to be lost after changing username despite still having the data in gGthub. 
Currently, the app shows 0 repo contributions (should be more than 5) and doesn't show stats for any commits that were made **before changing github username**

### Expected behaviour

Expect to see all stats before and after username change. Same ways as in Github Contribution activity

### Screenshots / Live demo link

<img width="624" alt="Screen Shot 2023-05-08 at 12 11 39" src="https://user-images.githubusercontent.com/2128531/236718750-053d5a11-1802-4a3a-918d-5957df502a38.png">
<img width="463" alt="Screen Shot 2023-05-08 at 12 08 46" src="https://user-images.githubusercontent.com/2128531/236718756-8c06f5ff-0117-4ba5-9d7a-89aa7df3502f.png">

### Additional context

New username: kristinabrueva
Old username: Bruuu

**Comment by rickstaa** [comment]
@kristinabrueva I checked your stats, and it looks like everything is going okay from our side. You can check this out yourself in [the GraphQL explorer](https://docs.github.com/en/graphql/overview/explorer) which we use to retrieve GitHub data. Please be aware that we use caching, so cards are only updated once every 4 hours further. Also, we have no access to your private contributions, so if you want to include those you have to deploy your own Vercel instance (see https://github.com/anuraghazra/github-readme-stats#deploy-on-your-own).

```graphql
query userInfo($login: String!) {
  user(login: $login) {
    name
    login
    contributionsCollection {
      totalCommitContributions
      restrictedContributionsCount
    }
    repositoriesContributedTo(first: 1, contributionTypes: [COMMIT, ISSUE, PULL_REQUEST, REPOSITORY]) {
        totalCount
      }
  }
}
```

```graphql
{"login": "kristinabrueva"}
```

**Cards**

[![Anurag's GitHub stats](https://github-readme-stats.vercel.app/api?username=kristinabrueva)](https://github.com/anuraghazra/github-readme-stats)

```md
[![Anurag's GitHub stats](https://github-readme-stats.vercel.app/api?username=kristinabrueva)](https://github.com/anuraghazra/github-readme-stats)
```
