### ISSUE TITLE
The total number of commits is incorrect

### ISSUE THREAD

**Issue by jyoketsu** [anuraghazra/github-readme-stats#271]
The total number of commits is incorrect and the number of commits is not updated after commit

**Comment by anuraghazra** [comment]
Total commit only counts commits of 1 previous year max. 

> commits is not updated after commit

It is because of 30min cache.

**Comment by anuraghazra** [comment]
related to #14 #15 #211 #92

**Comment by anuraghazra** [comment]
Should be fixed in #211
