### ISSUE TITLE
I still don't know how to use it, can anyone help me?

### ISSUE THREAD

**Issue by ToulthG** [anuraghazra/github-readme-stats#272]
问题

**Comment by anuraghazra** [comment]
Please translate the issue to english.

**Comment by ToulthG** [comment]
> 请将问题翻译成英文。

I still don't know how to use it, can anyone help me?
It's best to tell me step by step
thank you

**Comment by anuraghazra** [comment]
Read the docs, there is literally no STEPS to follow.

**Comment by anuraghazra** [comment]
```md
[![ToulthG's github stats](https://github-readme-stats.vercel.app/api?username=ToulthG)](https://github.com/anuraghazra/github-readme-stats)
```

**Comment by ToulthG** [comment]
> 阅读文档，实际上没有要遵循的步骤。

I know where markdown is

**Comment by anuraghazra** [comment]
Please explain exactly what you don't know, and only use english.

**Comment by ToulthG** [comment]
> 

> question

**Comment by ToulthG** [comment]
> Please explain exactly what you don't know, and only use english.

I saw putting the code in the markdown file
But I don’t know where in the markdown file

**Comment by anuraghazra** [comment]
Create a new repository named same as your github username and add the link there.

**Comment by ToulthG** [comment]
> Create a new repository named same as your github username and add the link there.

Thanks, forgive me for being a beginner

**Comment by anuraghazra** [comment]
> > Create a new repository named same as your github username and add the link there.
> 
> Thanks, forgive me for being a beginner

No worries, i was just confused with your question because it was in chinese & half explained. :) nothing wrong with being beginner.

**Comment by anuraghazra** [comment]
Hopefully you got your answer closing this now.
