### ISSUE TITLE
Wakatime card can't find account

### ISSUE THREAD

**Issue by SingularisArt** [anuraghazra/github-readme-stats#2720]
### Describe the bug

Around last week, I started to realize that the [link](https://github-readme-stats.vercel.app/api/wakatime?username=SingularisArt&hide_title=true&hide_border=true&bg_color=00000000&text_color=777) doesn't work anymore. My account is public. You can find it [here](https://wakatime.com/@SingularisArt).

**Comment by qwerty541** [comment]
Your wakatime account data is public, but only last week. You should add `&range=last_7_days` to fix your problem.

`https://github-readme-stats.vercel.app/api/wakatime?username=SingularisArt&hide_title=true&hide_border=true&bg_color=00000000&text_color=777&range=last_7_days`

<img src="https://github-readme-stats.vercel.app/api/wakatime?username=SingularisArt&hide_title=true&hide_border=true&bg_color=00000000&text_color=777&range=last_7_days"  />
