### ISSUE TITLE
Using layout parameter twice in top-langs gives toLowerCase not a function error

### ISSUE THREAD

**Issue by feikname** [anuraghazra/github-readme-stats#2737]
EDIT: I was giving two layout parameters without noticing, ignore the PR reference! Nonetheless here's the bug report

If layout parameter is given two times such as in `https://github-readme-stats.vercel.app/api/top-langs/?username=feikname&layout=compact&layout=compact`

Then this happens

![image](https://github.com/anuraghazra/github-readme-stats/assets/4926869/6891a637-b5f7-40b3-8ebb-e406b7ff3f05)

**Comment by qwerty541** [comment]
Remove extra layout parameter then. I'm not sure that it is a bug. What do you think @rickstaa ?

If we are going to fix it the source of problem is the following code string:

https://github.com/anuraghazra/github-readme-stats/blob/f9427b2a54bbab31aa7874da25a2e3227dbb4e77/src/cards/top-languages-card.js#L719

**Comment by rickstaa** [comment]
@feikname thanks for your bug report. I fixed the issues your having in #2746.

**Comment by rickstaa** [comment]
Fixed in https://github.com/anuraghazra/github-readme-stats/pull/2770.
