### ISSUE TITLE
Why bot would ban the Pull Requests?

### ISSUE THREAD

**Issue by yuhan2680** [anuraghazra/github-readme-stats#2741]
### Is your feature request related to a problem? Please describe.

Because of I found that the Chinese document is not the newest document as English document. So I update the Chinese documen. But a bot called Vercel refused my Pull Request. But why a bot can refuse it? Should I do something to make Pull Request?

**Comment by rickstaa** [comment]
@yuhan2680 first, thanks for your contribution. The bot doesn't refuse your pull request. It just wants a confirmation from anybody on the GRS team that it can build the Vercel deployment. This is a safety measure 😅. You therefore don't have to worry about the check failing. Me or the other collaborators will likely approve the workflow when they look at your pull request.
