### ISSUE TITLE
https://github-readme-stats-git-masterrstaa-rickstaa.vercel.app not updating total commits

### ISSUE THREAD

**Issue by NacarateJ** [anuraghazra/github-readme-stats#2744]
### Describe the bug

I use https://github-readme-stats-git-masterrstaa-rickstaa.vercel.app and I noticed that the total commits has been the same for a while. I checked the FAQ #1770 and ran the suggested syntax in the GraphQL explorer. The returned data is almost 200 commits over the number I see in my profile.

### Expected behavior

The total number of commits.

### Screenshots / Live demo link

<img width="458" alt="Screenshot 2023-05-23 at 8 01 48 PM" src="https://github.com/anuraghazra/github-readme-stats/assets/114256348/617ad3f0-9192-4eec-90a9-bd694a9630ae">
<br>
<img width="505" alt="Screenshot 2023-05-23 at 8 01 23 PM" src="https://github.com/anuraghazra/github-readme-stats/assets/114256348/9a8b7541-42c2-4fd2-94b9-02c312826d87">

**Comment by NacarateJ** [comment]
Hi @rickstaa, thank you for your answer. I'll definitely check out the suggested link to deploy my own Vercel instance then. However, I was wondering why the data I get back  in the GraphQL explorer is not the same as the data I see on the attached screenshot. On my end I see all the commits shown as `totalCommitContributions`.

<img width="1382" alt="Screenshot 2023-05-24 at 10 18 45 AM" src="https://github.com/anuraghazra/github-readme-stats/assets/114256348/162b265e-008a-4bc8-824d-a5e780f467d0">

**Comment by rickstaa** [comment]
> Hi @rickstaa, thank you for your answer. I'll definitely check out the suggested link to deploy my own Vercel instance then. However, I was wondering why the data I get back in the GraphQL explorer is not the same as the data I see on the attached screenshot. On my end I see all the commits shown as `totalCommitContributions`.
> 
> <img alt="Screenshot 2023-05-24 at 10 18 45 AM" width="1382" src="https://user-images.githubusercontent.com/114256348/240692990-162b265e-008a-4bc8-824d-a5e780f467d0.png">

The difference is caused because you are logged in with your account to the GraphQL tool. As a result, you have permission to see your private data, while I do not have this permission.
