### ISSUE TITLE
Cards not updating if information changes.

### ISSUE THREAD

**Issue by Lekesoldat** [anuraghazra/github-readme-stats#275]
**Describe the bug**
Images loaded in the README does not update.

**Expected behavior**
When I delete files / add code / do changes, my stats should update.

**Screenshots / Live demo link (paste the github-readme-stats link as markdown image)**
Have a look at my profile, - stats are not updated.

**Additional context**
Read more [here](https://docs.github.com/en/github/authenticating-to-github/about-anonymized-image-urls#an-image-that-changed-recently-is-not-updating). It's a problem due to caching.

Server should send cache headers stating that cache should be turned off or very time limited.

**Comment by anuraghazra** [comment]
Github readme stat uses minimum of 30min caching, and it's expected behaviour.

**Comment by nombrekeff** [comment]
We should pin this issue or some other similar one, as people have reported it multiple times already

**Comment by anuraghazra** [comment]
> We should pin this issue or some other similar one, as people have reported it multiple times already

I think its ok we don't need to that, maybe we can add notes on common issues in the issue template itself.

**Comment by pandyaved98** [comment]
MY GitHub read me stats isn't updating. I've created a new repo and committed some files in it but it's still showing the same as before no increment in numbers.

**Comment by nombrekeff** [comment]
@pandyaved98 hey there! 

As the issue and [docs indicate](https://github.com/anuraghazra/github-readme-stats#gradient-in-bg_color), there is a cache in place, I don't know how long it is currently. But it should reflect the changes in some time, 30min/1h I'm guessing!

> Note on cache: Repo cards have a default cache of 4 hours (14400 seconds) if the fork count & star count is less than 1k, otherwise, it's 2 hours (7200 seconds). Also, note that the cache is clamped to a minimum of 2 hours and a maximum of 24 hours.

**Comment by danglequocbao001** [comment]
My github read me stats updated, but when I display it by html in read me on github it not update same as go to the link by direct

**Comment by thedocscripts** [comment]
> 

have the same issue

**Comment by rickstaa** [comment]
We use caching to decrease the server load. Due to high server loads, the caching time has recently been updated to 4 hours in 2bfd9d8f00f6fc5229d0174a220ba04dbc4ee8.

**Comment by sanjanastyles** [comment]
> We use caching to decrease the server load. Due to high server loads, the caching time has recently been updated to 4 hours in [9d2bfd9](https://github.com/anuraghazra/github-readme-stats/commit/9d2bfd9d8f00f6fc5229d0174a220ba04dbc4ee8).

Honestly, its been quite few days I've_ been using this stat card, and it has never once updated since then. Please look into the issue, or at least tell us how to update it even if its manual. Thanks

**Comment by rickstaa** [comment]
@sanjanastyles I checked your account using [the graphql explorer](https://docs.github.com/en/graphql/overview/explorer) and it looks the card is up to date. You can check this yourself using the following syntax:

```graphql
query userInfo($login: String!) {
  user(login: $login) {
    name
    login
    contributionsCollection {
      totalCommitContributions
      restrictedContributionsCount
    }
    repositoriesContributedTo(
      first: 1
      contributionTypes: [COMMIT, ISSUE, PULL_REQUEST, REPOSITORY]
    ) {
      totalCount
    }
    pullRequests(first: 1) {
      totalCount
    }
    openIssues: issues(states: OPEN) {
      totalCount
    }
    closedIssues: issues(states: CLOSED) {
      totalCount
    }
    followers {
      totalCount
    }
    repositories(
      first: 100
      ownerAffiliations: OWNER
      orderBy: {direction: DESC, field: STARGAZERS}
    ) {
      totalCount
      nodes {
        stargazers {
          totalCount
        }
      }
    }
  }
}
```

```graphql
{"login": "sanjanastyles"}
```

Gives:

```graphql
{
  "data": {
    "user": {
      "name": "KANATA",
      "login": "sanjanastyles",
      "contributionsCollection": {
        "totalCommitContributions": 67,
        "restrictedContributionsCount": 0
      },
      "repositoriesContributedTo": {
        "totalCount": 1
      },
      "pullRequests": {
        "totalCount": 0
      },
      "openIssues": {
        "totalCount": 0
      },
      "closedIssues": {
        "totalCount": 0
      },
      "followers": {
        "totalCount": 4
      },
      "repositories": {
        "totalCount": 5,
        "nodes": [
          {
            "stargazers": {
              "totalCount": 0
            }
          },
          {
            "stargazers": {
              "totalCount": 0
            }
          },
          {
            "stargazers": {
              "totalCount": 0
            }
          },
          {
            "stargazers": {
              "totalCount": 0
            }
          },
          {
            "stargazers": {
              "totalCount": 0
            }
          }
        ]
      }
    }
  }
}
```

[![GitHub stats](https://github-readme-stats.vercel.app/api?username=sanjanastyles)](https://github.com/anuraghazra/github-readme-stats)

**Comment by KimeriTenko** [comment]
Mine stopped updating weeks ago and I've added new repos since

**Comment by rickstaa** [comment]
@KimeriTenko Thanks for your comment. Please be aware that we are using a 4-hour cache time before results show up (see https://github.com/anuraghazra/github-readme-stats#gradient-in-bg_color). I checked your cards but the results look up to date:

**Comment by vaishnav-mandlik** [comment]
GitHub Stats as it is since added in README

**Comment by BeatrizARibeiro** [comment]
My GitHub read me Stats not updtating

**Comment by vaishnav-mandlik** [comment]
> My GitHub read me Stats not updtating

GitHub read me stats updates after 12 am

**Comment by rickstaa** [comment]
@BeatrizARibeiro @vaishnav-mandlik is right we use a caching mechanism to reduce the server load (see https://github.com/anuraghazra/github-readme-stats#common-options).

**Comment by thaisalesz** [comment]
I'm having a similar issue, one of my cards is not showing any information for a few days now, but if I open de link directly it seems to be working fine.

**Comment by rickstaa** [comment]
@thaisalesz Thanks for your question. I checked your card and your stats seem to be updated.  You can check this by using the following syntax in the [GraphQL explorer](https://docs.github.com/en/graphql/overview/explorer):

```graphql
query userInfo($login: String!) {
  user(login: $login) {
    name
    login
    contributionsCollection {
      totalCommitContributions
      restrictedContributionsCount
    }
  }
}
```

```graphql
{"login": "thaisalesz"}
```

[![Anurag's GitHub stats](https://github-readme-stats.vercel.app/api?username=thaisalesz)](https://github.com/anuraghazra/github-readme-stats)

```md
[![Anurag's GitHub stats](https://github-readme-stats.vercel.app/api?username=thaisalesz)](https://github.com/anuraghazra/github-readme-stats)
```
I think you are experiencing the problem because we use a min caching period of 4 hours (see https://github.com/anuraghazra/github-readme-stats#common-options). Every update, therefore, takes 4 hours to be visible on the card. I created #2266 to allow users to set lower values for their own Vercel instances.

**Comment by sban2009** [comment]
Hi @rickstaa I have 2 repos using JS. The [link ](https://github-readme-stats.vercel.app/api/top-langs/?username=sban2009&layout=compact&card_width=450&hide_border=true&hide_title=true&hide=Jupyter%20%Notebook&langs_count=10&theme=github_dark)is opening up to the correct stats but in my README, it is not showing. Any suggestions?

**Comment by rickstaa** [comment]
> Hi @rickstaa I have 2 repos using JS. The [link ](https://github-readme-stats.vercel.app/api/top-langs/?username=sban2009&layout=compact&card_width=450&hide_border=true&hide_title=true&hide=Jupyter%20%Notebook&langs_count=10&theme=github_dark)is opening up to the correct stats but in my README, it is not showing. Any suggestions?

@sban2009 we use caching to reduce the server load. Your  README will likely update in 4 hours (see https://github.com/anuraghazra/github-readme-stats#common-options).

**Comment by sban2009** [comment]
@rickstaa added one of the JS ones a long time back

**Comment by rickstaa** [comment]
@sban2009 I checked the results we retrieved from GitHub, and it looks like your card is correct. You can test it out yourself using the following syntax in the GraphQL API:

```graphql
query userInfo($login: String!) {
  user(login: $login) {
    # fetch only owner repos & not forks
    repositories(ownerAffiliations: OWNER, isFork: false, first: 100) {
      nodes {
        name
        languages(first: 10, orderBy: {field: SIZE, direction: DESC}) {
          edges {
            size
            node {
              color
              name
            }
          }
        }
      }
    }
  }
}
```
```graphql
{"login": "sban2009"}
```

The https://github.com/sban2009/carbon-tutorial results do not show up since it is a fork, and we currently do not include results of forks (see https://github.com/anuraghazra/github-readme-stats/discussions/1255).

**Comment by KimeriTenko** [comment]
Thank you for taking a look at it

**Comment by rickstaa** [comment]
> @rickstaa I'm having the same issue please check https://github-readme-stats.vercel.app/api?username=mrv8x&line_height=40&show_icons=true&theme=radical `{ "data": { "user": { "name": "B. Hamza", "login": "mrv8x", "contributionsCollection": { "totalCommitContributions": 90, "restrictedContributionsCount": 0 } } } }`

@mrv8x No problem you can your stats yourself in [the GraphQL explorer](https://docs.github.com/en/graphql/overview/explorer) using the following syntax:

```graphql
query userInfo($login: String!) {
  user(login: $login) {
    name
    login
    contributionsCollection {
      totalCommitContributions
      restrictedContributionsCount
    }
  }
}
```

```graphql
{"login": "mrv8x"}
```

or for the language card:

```graphql
query userInfo($login: String!) {
  user(login: $login) {
    # fetch only owner repos & not forks
    repositories(ownerAffiliations: OWNER, isFork: false, first: 100) {
      nodes {
        name
        languages(first: 10, orderBy: {field: SIZE, direction: DESC}) {
          edges {
            size
            node {
              color
              name
            }
          }
        }
      }
    }
  }
}
```

```graphql
{"login": "mrv8x"}
```


You can add a random parameter (i.e. `radfasf&arasfda`) to force the cache to reset.

```md
[![Anurag's GitHub stats](https://github-readme-stats.vercel.app/api?username=mrv8x&radfasf&arasfda`)](https://github.com/anuraghazra/github-readme-stats)
```

[![Anurag's GitHub stats](https://github-readme-stats.vercel.app/api?username=mrv8x&radfasf&arasfda`)](https://github.com/anuraghazra/github-readme-stats)

```md
[![Top Langs](https://github-readme-stats.vercel.app/api/top-langs/?username=mrv8x&radfasf&arasfda`)](https://github.com/anuraghazra/github-readme-stats)
```

[![Top Langs](https://github-readme-stats.vercel.app/api/top-langs/?username=mrv8x&radfasf&arasfda`)](https://github.com/anuraghazra/github-readme-stats)

**Comment by rickstaa** [comment]
The results on your cards look correct.

```graphql
{
  "data": {
    "user": {
      "name": "B. Hamza",
      "login": "mrv8x",
      "contributionsCollection": {
        "totalCommitContributions": 4,
        "restrictedContributionsCount": 92
      }
    }
  }
}
```

You can include the [count_private](https://github.com/anuraghazra/github-readme-stats#adding-private-contributions-count-to-total-commits-count) argument.

**Comment by Edmartt** [comment]
> The results on your cards look correct.
> 
> ```graphql
> {
>   "data": {
>     "user": {
>       "name": "B. Hamza",
>       "login": "mrv8x",
>       "contributionsCollection": {
>         "totalCommitContributions": 4,
>         "restrictedContributionsCount": 92
>       }
>     }
>   }
> }
> ```
> 
> You can include the [count_private](https://github.com/anuraghazra/github-readme-stats#adding-private-contributions-count-to-total-commits-count) argument.

I have 143 pull request, this 4 hours turned to be several weeks, friend, counting juts 108, something is wrong

**Comment by qwerty541** [comment]
> 



> > The results on your cards look correct.
> > ```graphql
> > {
> >   "data": {
> >     "user": {
> >       "name": "B. Hamza",
> >       "login": "mrv8x",
> >       "contributionsCollection": {
> >         "totalCommitContributions": 4,
> >         "restrictedContributionsCount": 92
> >       }
> >     }
> >   }
> > }
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > You can include the [count_private](https://github.com/anuraghazra/github-readme-stats#adding-private-contributions-count-to-total-commits-count) argument.
> 
> I have 143 pull request, this 4 hours turned to be several weeks, friend, counting juts 108, something is wrong

I checked your profile and detected that most of your contributions are private. Most likely it is the source of your problem. Query parameter `count_private` was recently removed (#2736) due to it's confusing behaviour and to include your private contributions you should [deploy you own vercel instance](https://github.com/anuraghazra/github-readme-stats#on-vercel) using own GitHub API token.

**Comment by rickstaa** [comment]
> > > 
> > 
> > 
> > > > The results on your cards look correct.
> > > > ```graphql
> > > > {
> > > >   "data": {
> > > >     "user": {
> > > >       "name": "B. Hamza",
> > > >       "login": "mrv8x",
> > > >       "contributionsCollection": {
> > > >         "totalCommitContributions": 4,
> > > >         "restrictedContributionsCount": 92
> > > >       }
> > > >     }
> > > >   }
> > > > }
> > > > ```
> > > > 
> > > > 
> > > >     
> > > >       
> > > >     
> > > > 
> > > >       
> > > >     
> > > > 
> > > >     
> > > >   
> > > > You can include the [count_private](https://github.com/anuraghazra/github-readme-stats#adding-private-contributions-count-to-total-commits-count) argument.
> > > 
> > > 
> > > I have 143 pull request, this 4 hours turned to be several weeks, friend, counting juts 108, something is wrong
> > 
> > 
> > @Edmartt I checked your profile and detected that most of your contributions are private. Most likely it is the source of your problem. Query parameter `count_private` was recently removed (#2736) due to it's confusing behaviour and to include your private contributions you should [deploy you own vercel instance](https://github.com/anuraghazra/github-readme-stats#on-vercel) using own GitHub API token.
> 
> ![imagen](https://user-images.githubusercontent.com/47486245/248301090-8fe2cd56-fd61-4bc0-8d01-52490ac48d19.png)

Looks like a Vercel API error. I think you should wait a bit and try again 🤔. The Vercel status can be found [here](https://www.vercel-status.com/).

**Comment by Edmartt** [comment]
> > 
> 
> > > The results on your cards look correct.
> > > ```graphql
> > > {
> > >   "data": {
> > >     "user": {
> > >       "name": "B. Hamza",
> > >       "login": "mrv8x",
> > >       "contributionsCollection": {
> > >         "totalCommitContributions": 4,
> > >         "restrictedContributionsCount": 92
> > >       }
> > >     }
> > >   }
> > > }
> > > ```
> > > 
> > > 
> > >     
> > >       
> > >     
> > > 
> > >       
> > >     
> > > 
> > >     
> > >   
> > > You can include the [count_private](https://github.com/anuraghazra/github-readme-stats#adding-private-contributions-count-to-total-commits-count) argument.
> > 
> > 
> > I have 143 pull request, this 4 hours turned to be several weeks, friend, counting juts 108, something is wrong
> 
> @Edmartt I checked your profile and detected that most of your contributions are private. Most likely it is the source of your problem. Query parameter `count_private` was recently removed (#2736) due to it's confusing behaviour and to include your private contributions you should [deploy you own vercel instance](https://github.com/anuraghazra/github-readme-stats#on-vercel) using own GitHub API token.

It was solved, I forgot about forking the repo, thanks.

**Comment by 0x5b62656e5d** [comment]
I know the caching time is 4 hours or so, but the data just stopped updating some time while ago. The commits are stuck at 155 but when I counted mine (including priv repos), its 271. I just created a new vercel instance and it's not updated either

**Comment by qwerty541** [comment]
@0x5b62656e5d It is not an erro from our side since it is exactly what GitHub API returns.

![image](https://github.com/anuraghazra/github-readme-stats/assets/53787217/ae9c4da3-05d8-4b56-ab8b-a8dcc8aee72b)

If commits count not changed after deploying own vercel instance most likely your GitHub API personal access token permissions was configured not correctly.

**Comment by SakshamShandilya** [comment]
Hello @rickstaa, I'm experiencing the same problem; it's not updating and displaying significantly low statistics.

**Comment by rickstaa** [comment]
> Hello @rickstaa, I'm experiencing the same problem; it's not updating and displaying significantly low statistics.

Hey @SakshamShandilya. We use caching to decrease server load, so it might take up to 6 hours for your stats to be visible on the cards (see https://github.com/anuraghazra/github-readme-stats?tab=readme-ov-file#important-notices-). Furthermore, due to upstream limitations, we currently don't include data from forks and organization repositories 😅 (see https://github.com/anuraghazra/github-readme-stats/issues/3109 and https://github.com/anuraghazra/github-readme-stats/issues/1). You can use the GraphQL queries at https://github.com/anuraghazra/github-readme-stats/issues/275#issuecomment-1326526039 to see if something else is happening. I hope this helps you. If you have any more questions feel free to let me know 👍🏻.

**Comment by Soumilgit** [comment]
Facing same issue here...lots of Javascript files in my repo https://github.com/Soumilgit/YourStory-Digital-Innovation-Hackathon-HackerEarth but the total proportion of Javascript in the languages card of the repo itself is showing Javascript proportion as 11.7 % only,even on visually checking the files,it seems to be higher(inside node_modules).Please help!

**Comment by Soumilgit** [comment]
OK,fine 👍

**Comment by immark007** [comment]
My statistics on github are not updating, it is stuck at 28 commits, although I have much more

**Comment by rohansx** [comment]
@anuraghazra 
my stats are not updating even tho you can see I have done more than 128 PR and its still showing 83 PRs

![image](https://github.com/user-attachments/assets/e51ef164-e969-4e7b-9b0f-908b049c6078)
![image](https://github.com/user-attachments/assets/a674b307-bc2e-4d33-8885-dba0443cb2e7)

**Comment by mhuzaifi0604** [comment]
@rickstaa I utilized the same code you used above for other people with my own username as shown in this image below:

![image](https://github.com/user-attachments/assets/f1f1173a-ac5b-4ff6-b9bc-2c7573d7bb41)

As you can see I have ```366 Public``` and ```99 private``` commits making a total of ```460 Commits```. But Still When i try to collect my stats via this api:
 ```https://github-readme-stats.vercel.app/api?username=mhuzaifi0604&count_private=true&include_all_commits=true```
 
 and as you can see I have used count_private to allow counting my private commits as well but I am getting a total of ```388 Commits```. Can you share some details on this as to why I might not be getting correct updates for my stats?
 
 And then the stats from my api and card on github readme do not match either. Here are pictures for both:
 
 
![image](https://github.com/user-attachments/assets/ec8a3aa0-168e-4de9-a4cd-fd0a1a9e063b)

</br>

![image](https://github.com/user-attachments/assets/96e3f263-3dd7-4b7a-935b-42a502e74556)

**Comment by ats1999** [comment]
In case you want to immediately update the card, then invalidate cache by adding and random characters in url query param.

**Comment by qwerty541** [comment]
In case you want your cards to be updated more often the best solution would be [deploying own Vercel instance](https://github.com/anuraghazra/github-readme-stats?tab=readme-ov-file#deploy-on-your-own) using own GitHub API token. There you would be able to set `CACHE_SECONDS` environment variable with any positive integer to bypyss the rate limit protection created for public deployment.

Invalidating the cache by adding a random characters to the URL query string is just a workaround. I think that doing this each time when you want the stats on card to be updated would not be good for you.
