### ISSUE TITLE
@ev1025 @KraXen72 hey guys, sorry for the tag but I just encountered this issue as well, just want to know how did you resolve it ? It says adding an environment variable PAT_1 with the GitHub token but I am not sure what its usage ?

### ISSUE THREAD

**Issue by ev1025** [anuraghazra/github-readme-stats#2759]
I think you'd better look at this on https://github.com/anuraghazra/github-readme-stats/issues/1471#issuecomment-979201779 .

The vercel site of the repository owner has an error with too many requests. In order to solve the problem, it is to proceed with the personal distribution on the VERCEL. You can find out how to deploy it in the comments above. Entering the GitHub token in the environment variable seems to be a procedure to authenticate whether it is connected to GitHub.

Since I am not an English speaker, there can be some difficulties in translating sentences!
Tag me if you have any more questions!

**Comment by rickstaa** [comment]
Thanks!
