### ISSUE TITLE
wakatime stats image not finding user

### ISSUE THREAD

**Issue by Yakiyo** [anuraghazra/github-readme-stats#2763]
### Describe the bug

Im trying to use the wakatime stats endpoint. Until a month or so ago, it was working fine. But suddenly it started showing error "user not found". My wakatime username is [Yakiyo](https://wakatime.com/@Yakiyo) and its public. 

### Expected behavior

The demo image used in the project's readme is working. So my one should look something similar to that ig.

![img](https://github-readme-stats.vercel.app/api/wakatime?username=Harlok&layout=compact&show_icons=true&title_color=4F8CC9&text_color=9f9f9f&bg_color=00000000&hide_border=true&icon_color=00000000&count_private=true).

### Screenshots / Live demo link

![img](https://github-readme-stats.vercel.app/api/wakatime?username=Yakiyo&layout=compact&show_icons=true&title_color=4F8CC9&text_color=9f9f9f&bg_color=00000000&hide_border=true&icon_color=00000000&count_private=true)

### Additional context

Im using the image in my github profile readme at https://github.com/Yakiyo/Yakiyo

I've tried using a few random wakatime users from the leaderboards, some of them work. some of them dont. Not sure whats wrong.

Doesn't work: 
- https://github-readme-stats.vercel.app/api/wakatime?username=Phosphorus&layout=compact&show_icons=true&title_color=4F8CC9&text_color=9f9f9f&bg_color=00000000&hide_border=true&icon_color=00000000&count_private=true
- https://github-readme-stats.vercel.app/api/wakatime?username=melike2d&layout=compact&show_icons=true&title_color=4F8CC9&text_color=9f9f9f&bg_color=00000000&hide_border=true&icon_color=00000000&count_private=true

Does Work:
- https://github-readme-stats.vercel.app/api/wakatime?username=shivashp&layout=compact&show_icons=true&title_color=4F8CC9&text_color=9f9f9f&bg_color=00000000&hide_border=true&icon_color=00000000&count_private=true

( I randomly picked the users. Since i can view their profiles, im assuming those profiles are public? or does making profile public mean something else?)

**Comment by rickstaa** [comment]
@Yakiyo this is a known bug (see https://github.com/anuraghazra/github-readme-stats/issues/2698) which I already fixed in https://github.com/anuraghazra/github-readme-stats/pull/2707. However, @Zo-Bro-23 or @anuraghazra have to approve the pull request for me to be able to merge it.
