### ISSUE TITLE
Count the stars of the repositories created by the user but under an organization

### ISSUE THREAD

**Issue by mominul** [anuraghazra/github-readme-stats#2765]
### Is your feature request related to a problem? Please describe.

Thanks for the project! But I am facing the following issue currently:

The current GitHub readme stats code doesn't take the stars of the repositories created by the user but under an organization into account. For example my profile stats
![](https://github-readme-stats.vercel.app/api?username=mominul)

Only enlists 21 stars, while [a repository](https://github.com/OpenBangla/OpenBangla-Keyboard) created by me already has 407 stars, which is under a GitHub organization, also created by me.

### Describe the solution you'd like

All the stars of the repositories created by the user should be collected whether it is under their own profile or not.

**Comment by rickstaa** [comment]
@mominul please check https://github.com/anuraghazra/github-readme-stats/issues/1. Although this is not yet supported in the upstream, there are ways to achieve what you want to achieve,
