### ISSUE TITLE
GitHub Stats are not Getting Updated

### ISSUE THREAD

**Issue by mukulwadhwa** [anuraghazra/github-readme-stats#2769]
### Describe the bug

Right now, it is showing my GitHub stats as follows:

Total Stars Earned:
3
Total Commits (2023):
41
Total PRs:
0
Total Issues:
2
Contributed to (last year):
0

### Expected behavior

It should have updated following stats: 

Total Commits (2023):
41
Total PRs:
0

**Comment by qwerty541** [comment]
By default stats card shows only public contributions. I do not want to repeat myself, see the answer here https://github.com/anuraghazra/github-readme-stats/issues/2768#issuecomment-1576106113

**Comment by rickstaa** [comment]
> By default stats card shows only public contributions. I do not want to repeat myself, see the answer here [#2768 (comment)](https://github.com/anuraghazra/github-readme-stats/issues/2768#issuecomment-1576106113)

I feel you. This question is being asked a lot. I am starting to think we need to update the documentation. I think https://github.com/anuraghazra/github-readme-stats/pull/2736 will already remove some confusion 🤔.
