### ISSUE TITLE
Different default langs count for different languages card layouts

### ISSUE THREAD

**Issue by qwerty541** [anuraghazra/github-readme-stats#2771]
### Is your feature request related to a problem? Please describe.

Currently, all language card layouts are set to the same default number of languages (5), and because of this, there is an empty space on some layouts.

![image](https://github.com/anuraghazra/github-readme-stats/assets/53787217/52655792-ca5b-4215-8803-48010f1c62db)

 I suggest setting another value that is a multiple of 2 for the `compact`, `pie` and `donut-vertical` layouts, such as 6 or 4.

What do you think, @rickstaa?

**Comment by rickstaa** [comment]
@qwerty541 I'm more than okay with merging your proposal 👍🏻. I was not aware that we use 5 languages as the default. I overwrite the default behaviour immediately after finding GRS.

**Comment by rickstaa** [comment]
#2774 merged into main.
