### ISSUE TITLE
Maximum retries exceeded.

### ISSUE THREAD

**Issue by vineetjaiss** [anuraghazra/github-readme-stats#2772]
### Describe the bug

When someone views readme stats the GitHub stats shows something went wrong! 

### Screenshots / Live demo link

![image](https://github.com/anuraghazra/github-readme-stats/assets/118113801/ebf0f9f8-a06b-42fd-b0dd-ae804e6ec438)

**Comment by amnezziaa** [comment]
Related to #1471

**Comment by rickstaa** [comment]
> Related to #1471

Closing as this is discussed in #1471. I gave @anuraghazra a new PAT which he can add to mitigate the problem. You can solve the problem by deploying your own Vercel instance (see https://github.com/anuraghazra/github-readme-stats#deploy-on-your-own). Eventually, we will release a GitHub action-based version that people can use to never have this problem.
