### ISSUE TITLE
Error: Something went wrong while using readme-stats; maximum retries exceeded, request to add env variable 'PAT_1' with GitHub token in Vercel

### ISSUE THREAD

**Issue by Madhav-MKNC** [anuraghazra/github-readme-stats#2784]
### Describe the bug

When attempting to use the "readme-stats" feature on the GitHub repository, an error message is displayed indicating that something went wrong. The error message suggests filing an issue at the provided URL, but upon visiting the URL, it shows a message stating that the maximum number of retries has been exceeded. Additionally, the error message requests the addition of an environment variable called "PAT_1" with the GitHub token in Vercel

### Expected behavior

The expected behavior is that the "readme-stats" feature should work without any errors or issues. It should retrieve the necessary data and display the appropriate statistics on the repository's readme file. There should be no need to manually add environment variables or encounter any maximum retries exceeded errors.

### Screenshots / Live demo link

![194050569-619c3be7-fbac-4a09-b046-44f02ecc2bbd](https://github.com/anuraghazra/github-readme-stats/assets/78339236/6c3fb5ad-aa6c-4116-954f-c0a5a8972aaa)

**Comment by dntfindmel** [comment]
I have the same error, can you pls tell me how you fixed?

**Comment by dntfindmel** [comment]
I got the same error too! For those who dont know how to fix, just add &PAT_1 in the end of your link on read me

**Comment by OribiaDev** [comment]
same here, getting the same error

**Comment by Kameronjan** [comment]
add    &PAT_1    at the end of your link and issue resolved 🤝

**Comment by qwerty541** [comment]
Related to #1471

**Comment by H-Alireza** [comment]
I used HTTP instead of HTTPS and it worked.
