### ISSUE TITLE
error most used language no detect

### ISSUE THREAD

**Issue by KevinASaputra** [anuraghazra/github-readme-stats#2790]
### Describe the bug

help me bro, i can't show most language in my github readme.md  

### Screenshots / Live demo link

[![Top Langs](https://github-readme-stats.vercel.app/api/top-langs/?username=KevinASaputra&layout=compact)](https://github.com/KevinASaputra)

**Comment by KevinASaputra** [comment]
should i show all my projects first??

**Comment by qwerty541** [comment]
By default, the language card shows language results only from public repositories. To include languages used in private repositories, you should [deploy your own instance](https://github.com/anuraghazra/github-readme-stats#deploy-on-your-own) using your own GitHub API token. Please read documentation more carefully.

**Comment by KevinASaputra** [comment]
> By default, the language card shows language results only from public repositories. To include languages used in private repositories, you should [deploy your own instance](https://github.com/anuraghazra/github-readme-stats#deploy-on-your-own) using your own GitHub API token. Please read documentation more carefully.
