### ISSUE TITLE
Lambda Deploy

### ISSUE THREAD

**Issue by metaskills** [anuraghazra/github-readme-stats#28]
I did a little work to deploy this to AWS Lambda. I rather like your setup so this is not really an issue and more of info sharing.

https://github.com/metaskills/github-readme-stats-lambda

**Comment by anuraghazra** [comment]
Awesome work! Seems nice. 

Although I don't have much experience on AWS so it looks complicated to me. 😅

Great work though. Is this deployed yet?

**Comment by metaskills** [comment]
Yup, I have it running now building out my first metaskills/README.md

**Comment by anuraghazra** [comment]
Yup looks good

![Lambdy](https://8zqkewwfb2.execute-api.us-east-1.amazonaws.com/prod/api/pin/?username=anuraghazra&repo=github-readme-stats)

**Comment by anuraghazra** [comment]
Btw @metaskills if have any ideas of how to solve the issue of rate limiting then let me know because github api only allows 5k requests per hour so eventually if lot of people use it it'll hit the limit.

**Comment by metaskills** [comment]
Well, on Lambda if I hit the rate limit, I would do some ClickOps and setup a CloudFront distribution but there a few ways to do that and some involve a custom domain name too. Then return a `public, max-age=` of some 10m or something. Or... the Lambda could write to /tmp or memory cache and return that for some time. Lot's of ways.

**Comment by anuraghazra** [comment]
Yup, i'll see what i can do, thanks for opening the isssue and your awesome lambda deployment :D closing this for now, feel free to open another one if you have any questions or queries :rocket:
