### ISSUE TITLE
Vercel deprecates node 16.x in two months, migration to node 18.x

### ISSUE THREAD

**Issue by qwerty541** [anuraghazra/github-readme-stats#2818]
Vercel announced that node `14.x` and `16.x` will be deprecated in two months on 15 August. See: https://vercel.com/changelog/node-js-14-and-16-are-being-deprecated

Currently during deployment of own vercel instance you can notice the following error:

![image](https://github.com/anuraghazra/github-readme-stats/assets/53787217/32639f7a-4f0c-464d-81a6-2c0b799ccaa4)

Since this project running on node `16.x` it's code base and continuous integration needs migration to latest stable version. After this @anuraghazra should update node version in vercel deployment settings. Also every user who have deployed his own instance should do the same.

TODO:

- [x] Create an announcement for community
- [x] Code base migration to node `18.x`
- [x] Continuous integration should use node `18.x`
- [x] Update node version for production deployment

**Comment by rickstaa** [comment]
Perfect. What are the next steps? @anuraghazra needs to update the node version? Looks like you can also use the `package.json` (see https://vercel.com/changelog/node-js-version-now-customizable-in-the-project-settings) 🤔.

**Comment by qwerty541** [comment]
> Perfect. What are the next steps? @anuraghazra needs to update the node version? Looks like you can also use the `package.json` (see https://vercel.com/changelog/node-js-version-now-customizable-in-the-project-settings) thinking.

According to vercel documentation `engines` property inside `package.json` take precedence over Project settings. I think that most likely it will be enough to merge #2823 to update node version and no actions required from @anuraghazra. 

I have changed yesterday node version to 18 on my own vercel deployment, looks like it works fine.

**Comment by rickstaa** [comment]
Merged! Thanks for the fixes @qwerty541!

**Comment by qwerty541** [comment]
> Merged! Thanks for the fixes @qwerty541!

Hey, Rick! Judging by failed e2e test after merging #2820 node version was not updated by merging #2823. Wakatime stats card currently doesn't work at all. I think that @anuraghazra should manually change project settings. 

It's duplicate of message which i sent you in discord. I don't know where you can answer more quickly.

**Comment by rickstaa** [comment]
> > Merged! Thanks for the fixes @qwerty541!
> 
> Hey, Rick! Judging by failed e2e test after merging #2820 node version was not updated by merging #2823. Wakatime stats card currently doesn't work at all. I think that @anuraghazra should manually change project settings.
> 
> It's duplicate of message which i sent you in discord. I don't know where you can answer more quickly.

I don't see a discord message 🤔. This behaviour is strange since https://vercel.com/docs/concepts/functions/serverless-functions/runtimes/node-js#node.js-version clearly states that the `engine` property takes precedence over the project settings.

**Comment by rickstaa** [comment]
I checked and the node version is applied:

![image](https://github.com/anuraghazra/github-readme-stats/assets/17570430/053450f0-cff0-43c0-8b10-1429986b9ec6)

I'm not certain why the waka time card is failing. Let me check some things.

**Comment by rickstaa** [comment]
@qwerty541 I'm uncertain if https://nodejs.org/api/esm.html#import-assertions are supported without an experimental flag (see https://nodejs.org/api/esm.html#import-assertions). I tried to make it work, but couldn't in the time I had. Since this feature is experimental anyway, we can also just decide not to remove the JSON import workaround for now?

**Comment by qwerty541** [comment]
> @qwerty541 I'm uncertain if https://nodejs.org/api/esm.html#import-assertions are supported without an experimental flag (see https://nodejs.org/api/esm.html#import-assertions). I tried to make it work, but couldn't in the time I had. Since this feature is experimental anyway, we can also just decide not to remove the JSON import workaround for now?

Yes, i agree, let's leave JSON import workaround as it is now. Anyway removing it is desirable but not required.

**Comment by qwerty541** [comment]
> I don't see a discord message 🤔

Looks like users who are not inside your fiend list are unable to send you messages due to your privacy settings and my message was not delivered 🤔

**Comment by rickstaa** [comment]
> 

Ah, I see. I fixed it :).
