### ISSUE TITLE
stat image fail to load will show the line code till you click enter before the line

### ISSUE THREAD

**Issue by yasinnaal** [anuraghazra/github-readme-stats#2822]
### Describe the bug

show case image fail to load will show the line code till you click enter before the line in case there are another line of codes
before it instead it will load the line code syntax

### Expected behavior

stat image should load directly after line code paste otherwise must instruct the users to click enter before paste the line code if there are another lines used

**Comment by rickstaa** [comment]
I think this is a duplicate of #2603. Can you maybe elaborate what your problem is?

**Comment by yasinnaal** [comment]
> I think this is a duplicate of #2603. Can you maybe elaborate what your problem is?

My issue is different. If you are using many lines of code in your read me file when you paste the image state code in between it will not load the image if you didn't break the line by clicking enter key.

**Comment by qwerty541** [comment]
> > I think this is a duplicate of #2603. Can you maybe elaborate what your problem is?
> 
> My issue is different. If you are using many lines of code in your read me file when you paste the image state code in between it will not load the image if you didn't break the line by clicking enter key.

Most likely your issue related not to this repository, but to misunderstanding of markdown syntax specs.
Can you provide an example of markdown code which you expected to work?

**Comment by yasinnaal** [comment]
> > > I think this is a duplicate of #2603. Can you maybe elaborate what your problem is?
> > My issue is different. If you are using many lines of code in your read me file when you paste the image state code in between it will not load the image if you didn't break the line by clicking enter key.
> 
> Most likely your issue related not to this repository, but to misunderstanding of markdown syntax specs. Can you provide an example of markdown code which you expected to work?

if no one else reported the same issue maybe it is related to the way markdown syntax works.
i will close the issue<

Thanks for all responses.

**Comment by rickstaa** [comment]
> > > > I think this is a duplicate of #2603. Can you maybe elaborate what your problem is?
> > > > My issue is different. If you are using many lines of code in your read me file when you paste the image state code in between it will not load the image if you didn't break the line by clicking enter key.
> > 
> > 
> > Most likely your issue related not to this repository, but to misunderstanding of markdown syntax specs. Can you provide an example of markdown code which you expected to work?
> 
> if no one else reported the same issue maybe it is related to the way markdown syntax works. i will close the issue<
> 
> Thanks for all responses.

Feel free to post the code you use so we can check it for you here :+1:.
