### ISSUE TITLE
Wakatime stats not loading

### ISSUE THREAD

**Issue by Tomgxz** [anuraghazra/github-readme-stats#2827]
### Describe the bug

Github says error fetching resource, URL has 500 internal server error (see image below)

### Expected behavior

For an image to be loaded

### Screenshots / Live demo link

![image](https://github.com/anuraghazra/github-readme-stats/assets/75934344/51c58181-116b-486b-8848-1620fa082ebe)

**Comment by qwerty541** [comment]
Resolved in #2829
