### ISSUE TITLE
I hope the theme can adapt to shallow and deep modes.

### ISSUE THREAD

**Issue by DevLiuSir** [anuraghazra/github-readme-stats#2837]
### Is your feature request related to a problem? Please describe.

I hope the theme can adapt to shallow and deep modes. For example, in macOS dark mode, the browser is also in dark mode, and the card theme also adapts to dark mode. On the contrary, light mode.

**Comment by rickstaa** [comment]
@DevLiuSir dynamic theming is done through Markdown and explained in https://github.com/anuraghazra/github-readme-stats#responsive-card-theme. You can use the `theme` query to select the dark and light mode themes.

**Comment by DevLiuSir** [comment]
Thank you. I completed my requirements using transparent themes
