### ISSUE TITLE
issue on dynamic card height 

### ISSUE THREAD

**Issue by rjoydip** [anuraghazra/github-readme-stats#284]
**Describe the bug**

I found when working to create card height dynamic. It not working always properly.

Without issue           |  With issue
:-------------------------:|:-------------------------:
https://github-readme-stats.rjoydip.vercel.app/api?username=rjoydip&plang_row_items=4 | https://github-readme-stats.rjoydip.vercel.app/api?username=rjoydip&plang_row_items=3
![image](https://user-images.githubusercontent.com/15318294/89109767-dc3b2000-d461-11ea-8faa-ebfbe410a018.png)  | ![image](https://user-images.githubusercontent.com/15318294/89109804-26240600-d462-11ea-92e8-60c0eeae1f4e.png)

Working PR #241

**Comment by MirayXS** [comment]
what
