### ISSUE TITLE
Take into account user reviewed PRs count during rank calculation and update other weights

### ISSUE THREAD

**Issue by qwerty541** [anuraghazra/github-readme-stats#2846]
Since stats card able to show users total reviewed PRs count after merging #1404 i suggest to consider possibility of taking into account this value during rank calculation. I think that any experienced programmer at a certain stage begins not only to write code, but also to review someone else's code, it would be logical that in order to achieve the highest rank, it would be necessary to score a certain number of reviews. What do you think about this @francois-rozet @rickstaa?

**Comment by francois-rozet** [comment]
I am also favorable to take reviews into account. However, the weight should be fairly low (same as Issues maybe). I also have no idea of a good "target" amount of reviews.

**Comment by rickstaa** [comment]
> I am also favorable to take reviews into account. However, the weight should be fairly low (same as Issues maybe). I also have no idea of a good "target" amount of reviews.

@qwerty541 if the stats master, aka @francois-rozet 👑, thinks it's a good idea, I'm also okay with it 👍🏻. 

@qwerty541, maybe you can give us an example PR with a review weight and mean. For the weight, I think this should be `1` same as issues and followers. For the mean value, at first, though I think it should be higher than PRs since reviews are easier to do. However, I noticed that @francois-rozet set issues lower than PRs. I think this is because the issue weight is lower, and the weight and mean are connected 🤔 . @francois-rozet, do you have a suggestion for the review mean?

**Comment by francois-rozet** [comment]
Actually, the median number of issues was kind of arbitrary. Some decs never submit issues but submit PRs that fix issues. You often see maintainers with more PRs than issues.

**Comment by rickstaa** [comment]
> Actually, the median number of issues was kind of arbitrary. Some devs never submit issues but submit PRs that fix issues. You often see maintainers with more PRs than issues. That's why I set it to a lower median, but it is not linked to the weight.
> 
> For the reviews, I think it should not be based on the easiness of the task, but on the actual frequency of reviews. Would a typical dev have more PRs or reviews? I don't know honestly

@francois-rozet Ah, thanks for the explanation. I just created some scripts that can help us retrieve the mean reviews done by the 52k stargazers of our repository. You can check it out [here](https://github.com/rickstaa/get-stargazers-info). I think if we let this run for a while we would have the mean number of reviews of our user base. Would this help you define a `reviews` weight and mean value?

**Comment by qwerty541** [comment]
> > I am also favorable to take reviews into account. However, the weight should be fairly low (same as Issues maybe). I also have no idea of a good "target" amount of reviews.
> 
> @qwerty541 if the stats master, aka @francois-rozet crown, thinks it's a good idea, I'm also okay with it 👍🏻.
> 
> @ qwerty541, could you give us an example PR with a review weight and mean? I think this should be `1` for the weight, the same as issues and followers. For the mean value, at first, though, I think it should be higher than PRs since reviews are easier to do. However, I noticed that @francois-rozet set issues lower than PRs. Maybe this is because the issue weight is lower, and the weight and mean are connected thinking . @francois-rozet, do you have a suggestion for the review mean?

@rickstaa @francois-rozet I have opened a draft pull request which implements this feature (#2857), please take a look. I think that reviews median should be low, even lower than issues, because only experienced developers start making reviews. Most beginner and intermediate developers don't do them or do very little, the exceptions are very rare. Personally i registered on GitHub 5+ years ago and most of my 170+ reviews i have done i last 1,5 year. What do you think? Feel free to update my PR.

**Comment by rickstaa** [comment]
> > > I am also favorable to take reviews into account. However, the weight should be fairly low (same as Issues maybe). I also have no idea of a good "target" amount of reviews.
> > 
> > 
> > @qwerty541 if the stats master, aka @francois-rozet crown, thinks it's a good idea, I'm also okay with it 👍🏻.
> > @ qwerty541, could you give us an example PR with a review weight and mean? I think this should be `1` for the weight, the same as issues and followers. For the mean value, at first, though, I think it should be higher than PRs since reviews are easier to do. However, I noticed that @francois-rozet set issues lower than PRs. Maybe this is because the issue weight is lower, and the weight and mean are connected thinking . @francois-rozet, do you have a suggestion for the review mean?
> 
> @rickstaa @francois-rozet I have opened a draft pull request which implements this feature (#2857), please take a look. I think that reviews median should be low, even lower than issues, because only experienced developers start making reviews. Most beginner and intermediate developers don't do them or do very little, the exceptions are very rare. Personally i registered on GitHub 5+ years ago and most of my 170+ reviews i have done i last 1,5 year. What do you think? Feel free to update my PR.

I agree I only started to do reviews in the last 2 years. Thanks for the pull request. Maybe, let's wait for the results of the https://github.com/rickstaa/get-stargazers-info script before setting the mean value 🤔? I ran it tonight but it crashed because one of the stargazers, strangely enough didn't have GraphQl data. I fixed this in https://github.com/rickstaa/get-stargazers-info/commit/bd9f994722935ecf1fc1f908f7902f6a0732a2e9 and now have it running again.

**Comment by francois-rozet** [comment]
> I just created some scripts that can help us retrieve the mean reviews done by the 52k stargazers of our repository.

That's super useful! In fact, it would be great to get the distribution of all statistics, not only the reviews. If you can give me a table with a column for each stat and a row for each user, I could analyze it in depth and improve the ranking.

**Comment by rickstaa** [comment]
> > I just created some scripts that can help us retrieve the mean reviews done by the 52k stargazers of our repository.
> 
> That's super useful! In fact, it would be great to get the distribution of all statistics, not only the reviews. If you can give me a table with a column for each stat and a row for each user, I could analyze it in depth and improve the ranking.

Great! I now updated https://github.com/rickstaa/get-stargazers-info to get all the information we use in the rank calculation. It will output the following JSON array:

[stargazers-info.zip](https://github.com/anuraghazra/github-readme-stats/files/11786097/stargazers-info.zip)

```json
[
    {
        "name": "rickstaa",
        "yearCommits": 2306,
        "totalCommits": 9094,
        "prs": 950,
        "issues": 644,
        "repos": 257,
        "stars": 514,
        "followers": 248,
        "reviews": 323,
        "discussionsStarted": 61,
        "discussionsAnswered": 95
    },
    {
        "name": "anuraghazra",
        "yearCommits": 138,
        "totalCommits": 15630,
        "prs": 627,
        "issues": 146,
        "repos": 158,
        "stars": 59872,
        "followers": 10524,
        "reviews": 192,
        "discussionsStarted": 6,
        "discussionsAnswered": 7
    },
    {
        "name": "sindresorhus",
        "yearCommits": 1258,
        "totalCommits": 155186,
        "prs": 1461,
        "issues": 4508,
        "repos": 1067,
        "stars": 619626,
        "followers": 56612,
        "reviews": 296,
        "discussionsStarted": 22,
        "discussionsAnswered": 28
    }
]
```

Is this something you can work with, or do you want a different format?

**Comment by rickstaa** [comment]
> totalCommits

Cool, I will run it and give you the data. It will take around 16 hours to fetch the data with the `totalCommits` field and eight without 😅. I will just let it run in the background 😅.

**Comment by rickstaa** [comment]
@francois-rozet I got the data without the `total commits`:

[anuraghazra-github-readme-stats-stargazers.zip](https://github.com/anuraghazra/github-readme-stats/files/11819063/anuraghazra-github-readme-stats-stargazers.zip)
[anuraghazra-github-readme-stats-stargazers-info.zip](https://github.com/anuraghazra/github-readme-stats/files/11819065/anuraghazra-github-readme-stats-stargazers-info.zip)

I will now also retrieve the total commits.

**Comment by rickstaa** [comment]
[This script](https://github.com/rickstaa/get-stargazers-info/blob/main/calculate-stargazers-info-stats.js) gives me the following results:

**Mean stars**: 164.45062779314748
**Median stars**: 7
**Standard deviation stars**: 1503.4046121553863
**Mean year commits**: 194.39910973966093
**Median year commits**: 38
**Standard deviation year commits**: 1551.4546577079814
**Mean PRs**: 46.67255444420799
**Median PRs**: 8
**Standard deviation PRs**: 195.57893780534928
**Mean issues**: 32.82964460523516
**Median issues**: 4
**Standard deviation issues**: 389.919161039066
**Mean repos**: 48.97575725331631
**Median repos**: 24
**Standard deviation repos**: 425.98899453331535
**Mean reviews**: 6.503688728098177
**Median reviews**: 0
**Standard deviation reviews**: 59.65160166741443
**Mean followers**: 53.13736965311769
**Median followers**: 14
**Standard deviation followers**: 350.6815682596224
**Mean discussions answered**: 0.2761225792721856
**Median discussions answered**: 0
**Standard deviation discussions answered**: 5.338483934207007
**Mean discussions started**: 0.7714229978009506
**Median discussions started**: 0
**Standard deviation discussions started**: 5.618898164394903

**Comment by qwerty541** [comment]
> I quickly used the [simple-statistics](https://simple-statistics.github.io/) library to create [this script](https://github.com/rickstaa/get-stargazers-info/blob/main/calculate-stargazers-info-stats.js) which gives me the following results:
> 
> **Mean stars**: `164.45062779314748` **Median stars**: `7` **Standard deviation stars**: `1503.4046121553863` **Max stars**: `134904` **Mean year commits**: `194.39910973966093` **Median year commits**: `38` **Standard deviation year commits**: `1551.4546577079814` **Max year commits**: `172824` **Mean PRs**: `46.67255444420799` **Median PRs**: `8` **Standard deviation PRs**: `195.57893780534928` **Max PRs**: `22098` **Mean issues**: `32.82964460523516` **Median issues**: `4` **Standard deviation issues**: `389.919161039066` **Max issues**: `84349` **Mean repos**: `48.97575725331631` **Median repos**: `24` **Standard deviation repos**: `425.98899453331535` **Max repos**: `85443` **Mean reviews**: `6.503688728098177` **Median reviews**: `0` **Standard deviation reviews**: `59.65160166741443` **Max reviews**: `4010` **Mean followers**: `53.13736965311769` **Median followers**: `14` **Standard deviation followers**: `350.6815682596224` **Max followers**: `44002` **Mean discussions answered**: `0.2761225792721856` **Median discussions answered**: `0` **Standard deviation discussions answered**: `5.338483934207007` **Max discussions answered**: `640` **Mean discussions started**: `0.7714229978009506` **Median discussions started**: `0` **Standard deviation discussions started**: `5.618898164394903` **Max discussions started**: `799`
> 
> The max of the individual stats of this sample group is staggering (i.e. `44002` followers, `85443` repos, `22098` pull requests, `134904` stars, `172824` yearly commits) exploding_head. It, however, looks from the median that we have a lot of inactive users thinking.

Good job @rickstaa!

I have updated my pull request https://github.com/anuraghazra/github-readme-stats/pull/2857 by fixing docs and e2e test. The last thing is to decide whether we will change any median and weight values. And will we do it in this or the next pull request.

In my opinion, the best option would be to have special monthly workflow which will fetch actual median users data and update ranking system. Thus, if the user is inactive for some time and the median grows, his rank will be able to fall and vice versa.

What do you think @rickstaa @francois-rozet ?

**Comment by francois-rozet** [comment]
Not a fan of the rank that can fall. It can be discouraging. Also updating the medians every month would effectively make the rank a contest, instead of a scale. Which i don't like.

**Comment by francois-rozet** [comment]
@rickstaa Maybe we can actually filter out inactive users from the stats. I'll try to work out a way to transform this data into a "ranking function"', probably using the quantiles.

**Comment by rickstaa** [comment]
> @rickstaa Maybe we can actually filter out inactive users from the stats. I'll try to work out a way to transform this data into a "ranking function"', probably using the quantiles.

This happens when we remove all users with `0` stats:

Retrieved info of `56388` stargazers.
Removed `261` users with `0` values in all stats.
Data of `56127` users remaining.
**Mean stars: `164.45062779314748`
**Median stars: `7`
**Standard deviation stars: `1503.4046121553863`
**Max stars: `134904`
**Mean year commits: `194.39910973966093`
**Median year commits: `38`
**Standard deviation year commits: `1551.4546577079814`
**Max year commits: `172824`
**Mean PRs: `46.67255444420799`
**Median PRs: `8`
**Standard deviation PRs: `195.57893780534928`
**Max PRs: `22098`
**Mean issues: `32.82964460523516`
**Median issues: `4`
**Standard deviation issues: `389.919161039066`
**Max issues: `84349`
**Mean repos: `48.97575725331631`
**Median repos: `24`
**Standard deviation repos: `425.98899453331535`
**Max repos: `85443`
**Mean reviews: `6.503688728098177`
**Median reviews: `0`
**Standard deviation reviews: `59.65160166741443`
**Max reviews: `4010`
**Mean followers: `53.13736965311769`
**Median followers: `14`
**Standard deviation followers: `350.6815682596224`
**Max followers: `44002`
**Mean discussions answered: `0.2761225792721856`
**Median discussions answered: `0`
**Standard deviation discussions answered: `5.338483934207007`
**Max discussions answered: `640`
**Mean discussions started: `0.7714229978009506`
**Median discussions started: `0`
**Standard deviation discussions started: `5.618898164394903`
**Max discussions started: `799`

and this happens when you remove all `0` values:

Retrieved info of `56388` stargazers.
**Mean stars**:`207.85049536020082`
**Median stars**:`13`
**Standard deviation stars**:`1687.5119988036495`
**Max stars**:`134904`
**Mean year commits**:`233.04583625656397`
**Median year commits**:`62`
**Standard deviation year commits**:`1696.031033151175`
**Max year commits**:`172824`
**Mean PRs**:`59.31422132071219`
**Median PRs**:`15`
**Standard deviation PRs**:`218.77371579488073`
**Max PRs**:`22098`
**Mean issues**:`46.57336218174499`
**Median issues**:`10`
**Standard deviation issues**:`463.72968176371495`
**Max issues**:`84349`
**Mean repos**:`49.58871271839256`
**Median repos**:`25`
**Standard deviation repos**:`428.6109786296062`
**Max repos**:`85443`
**Mean reviews**:`32.84933715514153`
**Median reviews**:`4`
**Standard deviation reviews**:`130.79438085467305`
**Max reviews**:`4010`
**Mean followers**:`56.94566394891385`
**Median followers**:`15`
**Standard deviation followers**:`362.7317979118462`
**Max followers**:`44002`
**Mean discussions answered**:`5.5706618962432914`
**Median discussions answered**:`2`
**Standard deviation discussions answered**:`23.355300289637782`
**Max discussions answered**:`640`
**Mean discussions started**:`4.034035055179449`
**Median discussions started**:`2`
**Standard deviation discussions started**:`12.326369951922501`
**Max discussions started**:`799`

**Comment by rickstaa** [comment]
> > I quickly used the [simple-statistics](https://simple-statistics.github.io/) library to create [this script](https://github.com/rickstaa/get-stargazers-info/blob/main/calculate-stargazers-info-stats.js) which gives me the following results:
> > **Mean stars**: `164.45062779314748` **Median stars**: `7` **Standard deviation stars**: `1503.4046121553863` **Max stars**: `134904` **Mean year commits**: `194.39910973966093` **Median year commits**: `38` **Standard deviation year commits**: `1551.4546577079814` **Max year commits**: `172824` **Mean PRs**: `46.67255444420799` **Median PRs**: `8` **Standard deviation PRs**: `195.57893780534928` **Max PRs**: `22098` **Mean issues**: `32.82964460523516` **Median issues**: `4` **Standard deviation issues**: `389.919161039066` **Max issues**: `84349` **Mean repos**: `48.97575725331631` **Median repos**: `24` **Standard deviation repos**: `425.98899453331535` **Max repos**: `85443` **Mean reviews**: `6.503688728098177` **Median reviews**: `0` **Standard deviation reviews**: `59.65160166741443` **Max reviews**: `4010` **Mean followers**: `53.13736965311769` **Median followers**: `14` **Standard deviation followers**: `350.6815682596224` **Max followers**: `44002` **Mean discussions answered**: `0.2761225792721856` **Median discussions answered**: `0` **Standard deviation discussions answered**: `5.338483934207007` **Max discussions answered**: `640` **Mean discussions started**: `0.7714229978009506` **Median discussions started**: `0` **Standard deviation discussions started**: `5.618898164394903` **Max discussions started**: `799`
> > The max of the individual stats of this sample group is staggering (i.e. `44002` followers, `85443` repos, `22098` pull requests, `134904` stars, `172824` yearly commits) exploding_head. It, however, looks from the median that we have a lot of inactive users thinking.
> 
> Good job @rickstaa!
> 
> I have updated my pull request #2857 by fixing docs and e2e test. The last thing is to decide whether we will change any median and weight values. And will we do it in this or the next pull request.
> 
> In my opinion, the best option would be to have special monthly workflow which will fetch actual median users data and update ranking system. Thus, if the user is inactive for some time and the median grows, his rank will be able to fall and vice versa.
> 
> What do you think @rickstaa @francois-rozet ?

@qwerty541, thanks for your suggestion. Although this would be desired in an ideal world, I agree with @francois-rozet that, currently, it is not a good idea. First, it will lead to a lot of issues opening with people complaining that their rank has changed. We already saw this after changing the rank the last time and when the total commits, for example, temporary, go to `0`. Secondly, retrieving these stats takes about 24 hours and might trigger GitHub action and GraphQL limits 😅 .

**Comment by rickstaa** [comment]
@francois-rozet I now also have the total commits data:

[total-commits-anuraghazra-github-readme-stats-stargazers-info.zip](https://github.com/anuraghazra/github-readme-stats/files/11852581/total-commits-anuraghazra-github-readme-stats-stargazers-info.zip)

This will give:

**Mean total commits:** ``804496.4495142611``
**Median total commits:** ``325``
**Standard deviation total commits:** ``27410915.258541238``
**Max total commits:** ``1058654487``

and when I remove zero values:

**Mean total commits:** ``804496.4495142611``
**Median total commits:** ``325``
**Standard deviation total commits:** ``27410915.258541238. ``
**Max total commits:** ``1058654487``

The mean and standard deviation are big because of [this issue](https://github.com/anuraghazra/github-readme-stats/issues/564).

**Comment by francois-rozet** [comment]
So here are some quantiles (every 5%) for each stats. We could use the quantiles to improve/affine the ranking scheme. Note that some of the current medians (commits, prs, issues and followers) are actually pretty good!

```
      yearCommits      prs    issues    repos      stars  followers  reviews
0.00          0.0      0.0      0.00      0.0       0.00        0.0      0.0
0.05          0.0      0.0      0.00      3.0       0.00        0.0      0.0
0.10          0.0      0.0      0.00      5.0       0.00        1.0      0.0
0.15          0.0      0.0      0.00      7.0       0.00        2.0      0.0
0.20          1.0      0.0      0.00      9.0       0.00        3.0      0.0
0.25          4.0      1.0      0.00     12.0       1.00        5.0      0.0
0.30          7.0      2.0      1.00     14.0       2.00        6.0      0.0
0.35         12.0      3.0      1.00     16.0       2.00        8.0      0.0
0.40         19.0      4.0      2.00     19.0       3.00        9.0      0.0
0.45         27.0      6.0      3.00     21.0       5.00       11.0      0.0
0.50         38.0      8.0      4.00     24.0       7.00       14.0      0.0
0.55         51.0     11.0      5.00     28.0       9.00       16.0      0.0
0.60         68.0     14.0      7.00     31.0      13.00       20.0      0.0
0.65         90.0     19.0     10.00     36.0      18.00       24.0      0.0
0.70        118.0     25.0     14.00     41.0      26.00       29.0      0.0
0.75        156.0     34.0     20.00     47.0      36.00       36.0      0.0
0.80        209.0     47.0     28.00     56.0      52.00       46.0      0.0
0.85        286.0     66.0     41.00     68.0      83.00       61.0      1.0
0.90        415.0    100.0     66.00     87.0     156.00       89.0      4.0
0.95        698.0    188.0    125.65    129.0     427.65      164.0     16.0
1.00     172824.0  22098.0  84349.00  85443.0  134904.00    44002.0   4010.0
```

Here are also the top quantiles:

```
       yearCommits        prs    issues      repos       stars  followers   reviews
0.950      698.000    188.000    125.65    129.000     427.650    164.000    16.000
0.955      747.585    204.000    138.00    137.000     496.585    178.000    19.000
0.960      806.000    223.520    153.00    146.000     585.000    197.000    23.000
0.965      867.455    249.000    170.00    158.000     691.000    217.000    29.000
0.970      958.000    280.000    192.00    173.000     842.390    248.390    38.000
0.975     1078.000    319.325    222.00    192.000    1038.000    291.325    49.000
0.980     1228.000    373.000    263.00    216.260    1373.000    348.260    65.000
0.985     1446.000    464.000    327.00    258.195    1937.780    444.000    94.000
0.990     1815.130    588.130    433.13    337.000    2833.260    628.390   139.130
0.995     2712.715    956.195    666.13    527.195    5569.195   1092.455   253.065
1.000   172824.000  22098.000  84349.00  85443.000  134904.000  44002.000  4010.000
```

**Comment by rickstaa** [comment]
> 1.000   172824.000  22098.000  84349.00  85443.000  134904.000  44002.000  4010.000

Ah, great info! Thanks for putting it together. The data is more normal than expected, just a bit skewed on the right side with outliers. I will check the results if you create a pull request with the new medians 👍🏻.

**Comment by francois-rozet** [comment]
Sorry for the delay, I've been very busy. I'll try to make a PR using the quantiles before the end of the month.

**Comment by rickstaa** [comment]
> Sorry for the delay, I've been very busy. I'll try to make a PR using the quantiles before the end of the month.

@francois-rozet, no need to apologise or to hurry. This is an OS project; we work on it when we have time and feel like it 🦄! We are happy to have you on our team! I think people are already pleased after the last improvements you made 🚀. Take all the time you need 👍🏻.
