### ISSUE TITLE
Error: Incorrect Total Commit Count When include_all_commits=true

### ISSUE THREAD

**Issue by Madhav-MKNC** [anuraghazra/github-readme-stats#2851]
I am experiencing an issue with the GitHub Readme Stats tool where the total commit count (with include_all_commits=true) is lower than the commit count for a specific period, such as commits from this year.

Expected Behavior: The total commit count, including all commits from all branches, should be equal to or greater than the commit count for a specific period, such as commits from this year.

Actual Behavior: The total commit count is lower than the commit count for the specified period, indicating an incorrect calculation.

**Comment by rickstaa** [comment]
@Madhav-MKNC, we use the [GraphQL API](https://docs.github.com/en/graphql) to fetch the yearly commits and the [GitHub Rest API](https://docs.github.com/en/rest?apiVersion=2022-11-28) to get all commits. Unfortunately, the GitHub Rest API is known to be buggy. The discussion of this problem and possible future solutions are found at https://github.com/anuraghazra/github-readme-stats/issues/1515. This problem becomes less clear when you have more total commits (see my profile).

#### Without include_all_commits

[![Anurag's GitHub stats](https://github-readme-stats.vercel.app/api?username=Madhav-MKNC)](https://github.com/anuraghazra/github-readme-stats)

```md
[![Anurag's GitHub stats](https://github-readme-stats.vercel.app/api?username=Madhav-MKNC)](https://github.com/anuraghazra/github-readme-stats)
```

#### With include_all_commmits=true
[![Anurag's GitHub stats](https://github-readme-stats.vercel.app/api?username=Madhav-MKNC&include_all_commits=true)](https://github.com/anuraghazra/github-readme-stats)

```md
[![Anurag's GitHub stats](https://github-readme-stats.vercel.app/api?username=Madhav-MKNC&include_all_commits=true)](https://github.com/anuraghazra/github-readme-stats)
```
