### ISSUE TITLE
Rank going down instead of up

### ISSUE THREAD

**Issue by HorridModz** [anuraghazra/github-readme-stats#2860]
### Describe the bug

When I first applied this to my profile, my rank was an A+. Since then, it has progressively went down, even though I have been making many more commits, collecting many more stars, etc. It is currently at a B.

I am guessing this behavior is because only the percentile is checked, regardless of how good or bad the stats actually are, i.e. it only matters how much you deviate from the average, regardless of whether your stats are better or worse than the average, So, someone who's stats are very bad will have a high rating because their stats deviate a lot from the average. I am guessing this is what happened to me, as I was very new to github when I first added this to my profile.

### Expected behavior

As I get more stars, make more commits, etc., my rank should go up rather than down.

### Screenshots / Live demo link

[![GitHub stats](https://github-readme-stats.vercel.app/api?username=HorridModz)](https://github.com/anuraghazra/github-readme-stats)

### Additional context

I am guessing this behavior is because only the percentile is checked, regardless of how good or bad the stats actually are, i.e. it only matters how much you deviate from the average, regardless of whether your stats are better or worse than the average, So, someone who's stats are very bad will have a high rating because their stats deviate a lot from the average. I am guessing this is what happened to me, as I was very new to github when I first added this to my profile.

**Comment by qwerty541** [comment]
See #2815
