### ISSUE TITLE
Add leetcode stats card

### ISSUE THREAD

**Issue by rickstaa** [anuraghazra/github-readme-stats#2866]
### Is your feature request related to a problem? Please describe.

The GRS repository currently doesn't have a way to show [Leetcode](https://leetcode.com/) statistics.

### Describe the solution you'd like

I think including this card in the GRS card family will be nice.

### Describe alternatives you've considered

A Leetcode card can be found at https://github.com/JacobLinCool/LeetCode-Stats-Card, but it would be nicer to have it available in the GRS repository so that the styling and themes of GRS can be used.

**Comment by anuraghazra** [comment]
Let's not do this, we can keep "github"-readme-stats for github only, We already have Wakatime card which I initially added without much thought. But adding more and more services / cards will only lead to increased maintenance efforts and downtimes.

**Comment by rickstaa** [comment]
@anuraghazra I agree. I think releasing the npm package so people can create cards based on our repository is a nice addition (see https://github.com/anuraghazra/github-readme-stats/issues/2152). We can then even migrate to an organization and transfer cards well under that organization (see https://github.com/anuraghazra/github-readme-stats/issues/1867).
