### ISSUE TITLE
Maximum indentation level

### ISSUE THREAD

**Issue by Reginald-Gillespie** [anuraghazra/github-readme-stats#2901]
### Is your feature request related to a problem? Please describe.

Nope

### Describe the solution you'd like

The ability to set maximum tab indentation as a github stat.

### Describe alternatives you've considered

Hosting it myself.

### Additional context

A great stat that I think would be cool to show is maximum indentation level used in code.

(This is mostly satirical but would be funny.)

**Comment by rickstaa** [comment]
Interesting 🤔. But not worth complicating our code base for 🤣. Feel free to open a pull request so people can merge it in their fork if they have the same sense of humour 👍🏻.
