### ISSUE TITLE
extra space after hiding rank

### ISSUE THREAD

**Issue by rjoydip** [anuraghazra/github-readme-stats#291]
**Describe the bug**
There are extra space after hiding rank.

**Expected behavior**
Extra space should hide while hiding rank.

**Screenshots / Live demo link**
![issue_on_width](https://user-images.githubusercontent.com/15318294/89121813-ec91e000-d4df-11ea-89fe-7ac8540cbb0b.PNG)

**Comment by dineshyadav3169** [comment]
is the issue solved?

**Comment by anuraghazra** [comment]
closed by #721
