### ISSUE TITLE
Changing weightages

### ISSUE THREAD

**Issue by geeky01adarsh** [anuraghazra/github-readme-stats#2929]
### Is your feature request related to a problem? Please describe.

Gaining followers on GitHub is hard and if you have some, then it might be a sign that you are doing something good, this is not related to how skillful you are but yes it is related to how much you are helping others to grow. 
Moreover, reviewing any PR is also a tough task; many developers lack this skill. If GitHub considers it for showing the graph, then I think we must add this for calculating the rank.

### Describe the solution you'd like

I suggest considering increasing the weightage of the followers and also adding PR reviews for calculating the rank of the project.

**Comment by rickstaa** [comment]
@GamingGeek Thanks for your feature request. We are still fine-tuning the weights, so feedback is always welcome. The latest discussion about the consequences can be found at https://github.com/anuraghazra/github-readme-stats/issues/2846. @francois-rozet and I retrieved the GRS distribution and will adjust the weights based on that. Feel free to join in.
