### ISSUE TITLE
Theme 

### ISSUE THREAD

**Issue by RahulMahesh62** [anuraghazra/github-readme-stats#295]
**Describe the bug**
I contributed a theme named "bear" and the theme currently is not looking as it wants to be. The hex codes are changed and also the screenshot doesn't match the given hex-codes.

**Expected behavior**
The hex codes given by me got changes and the theme now have an whole different appearance.

**Screenshots / Live demo link (paste the github-readme-stats link as markdown image)**
How the theme should look actually..
![233](https://user-images.githubusercontent.com/41413029/89124895-0e975c80-d4f8-11ea-9e4f-63dbb0f5ab3a.PNG)

What it is currently..
![2](https://user-images.githubusercontent.com/41413029/89124905-1bb44b80-d4f8-11ea-897a-27073b7a6770.PNG)

**Comment by anuraghazra** [comment]
It's not deployed yet.

**Comment by anuraghazra** [comment]
I'll deploy in few minutes
