### ISSUE TITLE
Total Commits number error

### ISSUE THREAD

**Issue by minji-o-j** [anuraghazra/github-readme-stats#298]
**Describe the bug**
Total Commits "include_all_commits=true" error

**Expected behavior**
![image](https://user-images.githubusercontent.com/45448731/89127494-d0fef780-d528-11ea-823a-8211c988f909.png)
![image](https://user-images.githubusercontent.com/45448731/89127506-d8be9c00-d528-11ea-9c00-767c277fbee7.png)
![image](https://user-images.githubusercontent.com/45448731/89127508-de1be680-d528-11ea-8048-f7fab8fd8730.png)

I expected 3.2k, but the live demo counted 6k... 

**Screenshots / Live demo link (paste the github-readme-stats link as markdown image)**

![Minji's Stats](https://github-readme-stats.vercel.app/api?username=minji-o-j&hide=stars&hide_title=true&show_icons=true&icon_color=333&title_color=333&text_color=777&count_private=true&include_all_commits=true)

```
![Minji's Stats](https://github-readme-stats.vercel.app/api?username=minji-o-j&hide=stars&hide_title=true&show_icons=true&icon_color=333&title_color=333&text_color=777&count_private=true&include_all_commits=true)
```

And when I changed like that `include_all_commits=false`, the counter counted my total Commits.

![Minji's Stats](https://github-readme-stats.vercel.app/api?username=minji-o-j&hide=stars&hide_title=true&show_icons=true&icon_color=333&title_color=333&text_color=777&count_private=true&include_all_commits=false)

```
![Minji's Stats](https://github-readme-stats.vercel.app/api?username=minji-o-j&hide=stars&hide_title=true&show_icons=true&icon_color=333&title_color=333&text_color=777&count_private=true&include_all_commits=false)
```

**Comment by anuraghazra** [comment]
Hi @minji-o-j thanks for reporting the issue, yeah it seems like we are currently adding the private commits + public commits which is causing the commits to be larger than expected. will fix it.
