### ISSUE TITLE
help with hosting

### ISSUE THREAD

**Issue by 1UC1F3R616** [anuraghazra/github-readme-stats#30]
I am new to vercel hosting,
When I clicked on deploy I got an error related to code not found,
I belive I did a mistake in setting the correct directory of code on vercel. Can you please be adding more info for self hosting.
- Thanks

**Comment by anuraghazra** [comment]
After clicking the deploy button you should get this screen

![image](https://user-images.githubusercontent.com/35374649/87246603-153c3200-c46c-11ea-8cf5-cf040ff70a91.png)

**Comment by 1UC1F3R616** [comment]
@anuraghazra yes after here please

**Comment by anuraghazra** [comment]
Then just click continue and select your account and again click continue, after that you have to create a personal access token from github to add it in the environment variables

**Comment by 1UC1F3R616** [comment]
@anuraghazra 
![image](https://user-images.githubusercontent.com/41824020/87246853-7ca6b180-c46d-11ea-8e2e-58ff75b7c710.png)

**Comment by anuraghazra** [comment]
yeah just select the personal account

**Comment by 1UC1F3R616** [comment]
![image](https://user-images.githubusercontent.com/41824020/87246937-40c01c00-c46e-11ea-8533-2117969e4436.png)
Continue from here

![image](https://user-images.githubusercontent.com/41824020/87246945-56cddc80-c46e-11ea-806f-50dfe46cab1e.png)
Environment variable set here any other change required? @anuraghazra

**Comment by anuraghazra** [comment]
It should just work. try it

**Comment by 1UC1F3R616** [comment]
@anuraghazra 
Below is the error that is coming
![image](https://user-images.githubusercontent.com/41824020/87247063-0014d280-c46f-11ea-995b-2472838572a7.png)

**Comment by 1UC1F3R616** [comment]
Tried after cleaning also but no benefit

**Comment by anuraghazra** [comment]
Make sure your vercel account is connected to Github

**Comment by 1UC1F3R616** [comment]
It got deployed, recived a mail
I found that the repo that it created was empty so I cloned the code and added in it's created repo and then used a different name.
I am not sure if this is the reason that solved the issue. But maybe someone can try this in future.
Thankyou again

**Comment by anuraghazra** [comment]
I see, well vercel should automatically clone the repo to your account if you have github integration enabled

**Comment by 1UC1F3R616** [comment]
Yes it's enabled without that it wasn't letting me go ahead.
Btwn this is a really nice project, thanks for this.
Issue is solved.

**Comment by anuraghazra** [comment]
Great!

**Comment by olets** [comment]
I had the same issue: Vercel created a new empty repo. I'm new to Vercel so don't know if this is a Vercel bug.

My solution was to fork this repo, then at https://vercel.com/import, "Import Git Repository" _not_ "Import Template"

Might even be better than using this repo as a template, because GitHub recognizes my repo as a fork. So your fork count goes up, and I get the convenient UI for seeing if my repo is behind.

**Comment by 1UC1F3R616** [comment]
Thanks @olets , This is perfect.
