### ISSUE TITLE
Theme preview workflow broken

### ISSUE THREAD

**Issue by qwerty541** [anuraghazra/github-readme-stats#3013]
Theme preview workflow is currently broken. most likely because recent dependencies updates. Error can be found there:

  - https://github.com/anuraghazra/github-readme-stats/pull/3009
  - https://github.com/anuraghazra/github-readme-stats/actions/runs/5698447987/job/15446339665?pr=3009

**Comment by rickstaa** [comment]
Looks like the GraphQL API got updated, and the createReview method is no longer found 🤔.

https://github.com/anuraghazra/github-readme-stats/blob/79545927f19c19dbe7a874e4b48ca2b7982e7571/scripts/preview-theme.js#L203C9-L209

Wil check later what the new syntax is 👍🏻.

**Comment by qwerty541** [comment]
@rickstaa Merging https://github.com/anuraghazra/github-readme-stats/pull/3017 improved sutiation since previous error gone but not resolved the whole problem. Currently it fails with another unexpected error: https://github.com/anuraghazra/github-readme-stats/actions/runs/5721747511/job/15503797772

Please take a look if you have a time or i will later.

**Comment by qwerty541** [comment]
@rickstaa I have opened #3034 with second attempt to fix error. Looks like i missed one place with `.rest` property ti insert.

**Comment by rickstaa** [comment]
Great thanks for solving this issue!
