### ISSUE TITLE
[Feature] Time by percentage on the wakatime card

### ISSUE THREAD

**Issue by qwerty541** [anuraghazra/github-readme-stats#3016]
Tracking issue for: 
https://github.com/anuraghazra/github-readme-stats/discussions/2948

**Comment by ritik48** [comment]
Hi, I would like to work on this issue. 
Can you please assign it to me ?

**Comment by qwerty541** [comment]
Hey, @ritik48! Thanks for considering contributing to our project. I'm looking forward to your pull request.

**Comment by ritik48** [comment]
Hey @qwerty541 , Thank you for assigning the issue to me. Could you please tell me if my contributions to this repository will be considered for Hacktoberfest 2023?

**Comment by qwerty541** [comment]
> Hey @qwerty541 , Thank you for assigning the issue to me. Could you please tell me if my contributions to this repository will be considered for Hacktoberfest 2023?

Honestly, i don't know anything about this event, i have never participated in Hacktoberfest.

Most likely @rickstaa and @anuraghazra can answer that.

**Comment by rickstaa** [comment]
> > Hey @qwerty541 , Thank you for assigning the issue to me. Could you please tell me if my contributions to this repository will be considered for Hacktoberfest 2023?
> 
> Honestly, i don't know anything about this event, i have never participated in Hacktoberfest.
> 
> Most likely @rickstaa and @anuraghazra can answer that.

@qwerty541 and @ritik48 GRS I hosted the hacktoberfest this year (see https://github.com/anuraghazra/github-readme-stats/discussions/2076) and @anuraghazra did it the years before that. I would love if we could also participate this year and are planning to look at all pull request when I come back for my holiday 😎⛱️

**Comment by qwerty541** [comment]
> > > Hey @qwerty541 , Thank you for assigning the issue to me. Could you please tell me if my contributions to this repository will be considered for Hacktoberfest 2023?
> > 
> > 
> > Honestly, i don't know anything about this event, i have never participated in Hacktoberfest.
> > Most likely @rickstaa and @anuraghazra can answer that.
> 
> @qwerty541 and @ritik48 GRS I hosted the Hacktoberfest this year (see #2076) and @anuraghazra did it the years before that. I would love if we could also participate this year and are planning to look at all pull request when I come back for my holiday 😎⛱️. @qwerty541 if you want, you can already start hosting the Hacktoberfest. You can sign up as a maintainer at https://hacktoberfest.com and create a discussion post for this year (e.g. #2076).

@rickstaa Recently i have signed up as maintainer, created an announcement discussion about Hacktoberfest 2023 using provided example (https://github.com/anuraghazra/github-readme-stats/discussions/3317) and assigned some guys on issues. We will take part in this event as you wish.

**Comment by ritik48** [comment]
@qwerty541 please review this pr #3326

**Comment by ritik48** [comment]
@qwerty541 @rickstaa please review this pr #3326

**Comment by qwerty541** [comment]
> @qwerty541 @rickstaa please review this pr #3326

@ritik48 I left my review, please check it out https://github.com/anuraghazra/github-readme-stats/pull/3326#pullrequestreview-1690806695
