### ISSUE TITLE
Removing language from top language cards

### ISSUE THREAD

**Issue by X3llus** [anuraghazra/github-readme-stats#302]
**Is your feature request related to a problem? Please describe.**
When using the top languages card, if you hide a language it doesn't get replaced.

**Describe the solution you'd like**
If one of the languages is hidden replace it with the next one (to keep it at 5 languages)

**Comment by anuraghazra** [comment]
This is expected behaviour that we want.

**Comment by X3llus** [comment]
Just for clarification, if a language is hidden it isn't supposed to get replaced?

**Comment by anuraghazra** [comment]
No it's not suppose to get replaced, its just that you hide from 5 languages.

**Comment by vn7n24fzkq** [comment]
@X3llus 
Hi, I don't see this issue before my PR #307, does this can solved your problem?

**Comment by X3llus** [comment]
> @X3llus 
> Hi, I don't see this issue before my PR #307, does this can solved your problem?
> @ahmadawais 
> Is the behavior in PR #307 allowed?

That is exactly what I'm looking for

**Comment by wilmol** [comment]
Surely you can add a parameter to specify max number of languages to show? If hiding languages it uses lesser used ones to meet the number.

**Comment by lrusso96** [comment]
> Surely you can add a parameter to specify max number of languages to show?

@wilmol you can use `langs_count` parameter to achieve this ( see e9019c1453dc81b967417a1511c275052d31ba1f).

**Comment by whoami-anoint** [comment]
<img height="180em" src="https://github-readme-stats-eight-theta.vercel.app/api/top-langs/?username=whoami-anoint&langs_count=8&layout=compact&hide=html&title_color=ffab91&text_color=80cbc4&bg_color=263238&border_radius=10" />
