### ISSUE TITLE
In "Top Languages Card" not displayed Kotlin

### ISSUE THREAD

**Issue by alexxxdev** [anuraghazra/github-readme-stats#303]
**Describe the bug**
In "Top Languages Card" not displayed Kotlin, although I have a repo on Kotlin

**Expected behavior**
I expect to see a line here with Kotlin: https://github.com/alexxxdev/alexxxdev

**Screenshots / Live demo link (paste the github-readme-stats link as markdown image)**
https://github.com/alexxxdev/alexxxdev
![image](https://user-images.githubusercontent.com/975579/89253832-e61e7800-d647-11ea-96c5-4b7af965d03b.png)

**Additional context**

**Comment by vn7n24fzkq** [comment]
Hi, I

**Comment by vn7n24fzkq** [comment]
Hi, I just see your issue after I pull request #307 .

I try you stats on my branch, and ignore some language, seems your numbers of kotlin code not more then c++ and c which generated by framework.

Before ignore C++, C, html and makefile
![image](https://user-images.githubusercontent.com/20241522/89322985-a5f6de00-d6b7-11ea-89ae-f1982095bc29.png)

After ignore
![image](https://user-images.githubusercontent.com/20241522/89323112-d63e7c80-d6b7-11ea-9c40-6111740bbee2.png)

**Comment by alexxxdev** [comment]
looks very strange
kotlin has more percentages than python, but python is shown, but not kotlin

also if i set hide = java then 4 languages remain, 5 does not appear
![image](https://user-images.githubusercontent.com/975579/89363693-ff343100-d6fa-11ea-9370-179385a47cad.png)

**Comment by lrusso96** [comment]
Hi @alexxxdev, I think that #435 should fix this.

Take a look at the new results.
![image](https://user-images.githubusercontent.com/26090639/91862636-83cc8d80-ec6e-11ea-9e2f-82a7d0a099a8.png)
