### ISSUE TITLE
New Platform: Codeberg

### ISSUE THREAD

**Issue by RaptaG** [anuraghazra/github-readme-stats#3031]
### Is your feature request related to a problem? Please describe.

No.

### Describe the solution you'd like

I love to see statistics for [Codeberg](https://codeberg.org), the open source git hosting service. It has gained quite some traction lately and I believe it is worth it.

### Describe alternatives you've considered

None.

### Additional context

This could suggest support for platforms such as GitLab too.

**Comment by qwerty541** [comment]
Thanks for your feature request. Our team going to keep "github"-readme-stats for github cards only. We already have Wakatime card which was added without much thought. Adding more and more services / cards will only lead to increased maintenance efforts and downtimes. In the future, we plan to move to an organization and then the Codeberg or GitLab statistics card could be one of the subprojects if there is enough request from the community, but I don't want to make any promises.

**Comment by anuraghazra** [comment]
Closing this as "not planned".
