### ISSUE TITLE
[GitHub Gist] hide_border not working

### ISSUE THREAD

**Issue by VydrOz** [anuraghazra/github-readme-stats#3071]
## Describe the bug

The common options like `theme`, `border_color` or `bg_color`, seems to be working properly but not the option `hide_border`.

## Expected behavior

`hide_border=true` should hide border of the card regardless of its type (stats, repo, gist, etc.).

## Screenshots / Live demo link

Examples with the theme "transparent"

### Github Gist

`hide_border=false`
```md
https://github-readme-stats.vercel.app/api/gist?id=260f39ecd845648c7e749fde1a18687b&theme=transparent&hide_border=false
```
![image](https://github.com/anuraghazra/github-readme-stats/assets/61025448/b5a4adc7-e179-4ddb-964a-b8282d683841)

`hide_border=true`
```md
https://github-readme-stats.vercel.app/api/gist?id=260f39ecd845648c7e749fde1a18687b&theme=transparent&hide_border=true
```
![image](https://github.com/anuraghazra/github-readme-stats/assets/61025448/1daf5d22-5ec0-421c-9236-f7eb90b16b38)

### Repos
`hide_border=false`
```md
https://github-readme-stats.vercel.app/api/pin/?username=anuraghazra&repo=github-readme-stats&theme=transparent&hide_border=false
```
![image](https://github.com/anuraghazra/github-readme-stats/assets/61025448/83cc180a-d6de-4e6a-9184-3b4fe62edc76)

`hide_border=true`
```md
https://github-readme-stats.vercel.app/api/pin/?username=anuraghazra&repo=github-readme-stats&theme=transparent&hide_border=true
```
![image](https://github.com/anuraghazra/github-readme-stats/assets/61025448/460baa57-e8fa-4f28-8eba-02402d8c0a69)

**Comment by qwerty541** [comment]
@VydrOz Thanks for the report. Will be fixed after merging of #3080.
