### ISSUE TITLE
Sometimes the stats card dosen't load

### ISSUE THREAD

**Issue by allwin199** [anuraghazra/github-readme-stats#3092]
### Describe the bug

I have created a new instance in Vercel.

Sometimes whenever I visit my Github page, I see the broken image icon. After refreshing the stats show up.

Let me know if this issue is already addressed.

**Comment by dxnsav** [comment]
I also see this problem on page of my gf

![17-20-50-38-chrome](https://github.com/anuraghazra/github-readme-stats/assets/45544178/692aebc0-5674-4240-ac77-39936190db2b)

**Comment by allwin199** [comment]
@dxnsav Have you created your own Vercel instance? 

If not, follow this to resolve this issue https://github.com/anuraghazra/github-readme-stats/issues/1471#issuecomment-979201779

**Comment by qwerty541** [comment]
@allwin199 This is a known issue caused by timeout of GitHub CDN. See: https://github.com/anuraghazra/github-readme-stats/issues/2603

**Comment by allwin199** [comment]
@qwerty541 thanks!

**Comment by allwin199** [comment]
Known Issue #2603

**Comment by qwerty541** [comment]
> I also see this problem on page of my gf
> 
> ![17-20-50-38-chrome](https://user-images.githubusercontent.com/45544178/261407958-692aebc0-5674-4240-ac77-39936190db2b.png)

@dxnsav Your issue was caused by public deployment downtime due to GitHub API rate limits. @allwin199 correctly told that the only solution for this is [deploying your own Vercel instance](https://github.com/anuraghazra/github-readme-stats#on-vercel) using your own GitHub API Personal Access Token (PAT).
