### ISSUE TITLE
should not include commits to empty repository

### ISSUE THREAD

**Issue by vivic04** [anuraghazra/github-readme-stats#3115]
### Describe the bug

 Even initialising an empty repository counts as a commit. This is can be fixed for better stat display and more accurate grading.

### Expected behavior

Remove Empty repository as counter in commit graph

**Comment by TechWizard9999** [comment]
😊 "I'd be delighted to work on this issue, @vivic04 ! Could you please assign it to me?"

**Comment by qwerty541** [comment]
Hey, @vivic04! I have no idea why you think that creating an empty repository counted as a commit. I checked total count of commits in your repositories, it's exactly same as shown on your stats card. Anyway even if this behavior was as you explained, we fetch commits count from GitHub API, we cannot modify their commits calculation algorithm. I think that we can close this.
