### ISSUE TITLE
Something went wrong! file an issue at https://tiny.one/readme-stats Maximum retries exceeded Please add an env variable called PAT_1 with your github token in vercel

### ISSUE THREAD

**Issue by faeztgh** [anuraghazra/github-readme-stats#3177]
### Describe the bug

Something went wrong! file an issue at https://tiny.one/readme-stats
Maximum retries exceeded Please add an env variable called PAT_1 with your github token in vercel

**Comment by ZainAmjad68** [comment]
getting the same issue:
<img width="589" alt="Screenshot 2023-08-30 at 7 29 43 PM" src="https://github.com/anuraghazra/github-readme-stats/assets/53145353/77438a2f-877b-47f6-bca8-b7386d5759db">

**Comment by L1468999760** [comment]
how to solve it?

**Comment by akinmustafa** [comment]
I did some research. Looks like there are 3 options to fix the issue.

**- First Option**
[Deploying your own Vercel](https://github.com/anuraghazra/github-readme-stats/issues/2402#issuecomment-1382721986)

**- Second Option**
Adding "sigma-five" inside the domain name so it resets the maximum retries.

For example, this gives error:

```<a href=""> <img align="center" src="https://github-readme-stats.vercel.app/api/top-langs/?username=YulietM&theme=react&line_height=40&hide=css"/> </a>```

and code down below is the one with added "sigma-five" text, it fixes the issue.

```<a href=""> <img align="center" src="https://github-readme-stats-sigma-five.vercel.app/api/top-langs/?username=YulietM&theme=react&line_height=40&hide=css"/> </a>```

Even though the second option fixed the issue, it removes custom themes for some reason. So deploying your own Vercel might be a better option.

**- Third Option**
Wait for the developers to increase maximum retries amount.

**Comment by qwerty541** [comment]
@faeztgh @ZainAmjad68

This happens because our public instance is being rate-limited by underlying GitHub API (see https://github.com/anuraghazra/github-readme-stats/issues/1471). As noticed @akinmustafa, you can [deploy your own instance](https://github.com/anuraghazra/github-readme-stats#deploy-on-your-own) using your own GitHub API token in order to fix this or wait until the public instance is longer rate-limited.
