### ISSUE TITLE
[BUG] Total Commits (2023)

### ISSUE THREAD

**Issue by pranshugupta54** [anuraghazra/github-readme-stats#3196]
### Describe the bug

Total Commits (2023) should show commits >=2023-01-01 but it actually shows for last 1 year.

Like it's 03 Sept 2023 today, I tried fetching total commits with >=2022-09-02 and it matched the count with "Total Commits (2023)" in the stats card.

### Expected behavior

instead of 1 year, it should be >=2023-01-01

### Screenshots / Live demo link

https://github-readme-stats.vercel.app/api?username=pranshugupta54

https://api.github.com/search/commits?q=author:pranshugupta54+author-date:%3E=2023-01-01

**Comment by rickstaa** [comment]
@pranshugupta54, thanks for your bug report. We are aware of this bug and are planning to fix it in the future (see https://github.com/anuraghazra/github-readme-stats/issues/1053) . It will be fixed when https://github.com/anuraghazra/github-readme-stats/pull/2107 is merged. I'm unfortunately didn't find time yet to review that pull request. You can, however already use it on your own fork.

**Comment by bryce0516** [comment]
![image](https://github.com/anuraghazra/github-readme-stats/assets/51251258/209e55ad-1307-42ab-838b-5e19110672fc)

It seems like my GitHub commits don't match the total number of commits.

**Comment by qwerty541** [comment]
> ![image](https://user-images.githubusercontent.com/51251258/272911530-209e55ad-1307-42ab-838b-5e19110672fc.png)
> 
> It seems like my GitHub commits don't match the total number of commits.
> 
> ![image](https://user-images.githubusercontent.com/51251258/272912321-baa5c2f9-595c-42bc-8c2d-767be89987ff.png) It is my commits

Hey, @bryce0516! By default, the stats card only shows statistics only from public repositories. To show private statistics on the stats card, you should [deploy your own instance](https://github.com/anuraghazra/github-readme-stats#deploy-on-your-own) using your own GitHub API token. Our documentation contains that information.

![image](https://github.com/anuraghazra/github-readme-stats/assets/53787217/d2745ae3-8a5b-47f5-b776-9d0594c2e60f)

**Comment by AlessioQuercia** [comment]
Hi, for me it does not seem to work, even when using the private Vercel solution:

![immagine](https://github.com/anuraghazra/github-readme-stats/assets/18620868/5c31a30e-7f68-42d0-b4b0-4e9d980383a9)
Generated with these options: username=AlessioQuercia&include_all_commits=true&show_icons=true&theme=radical.

![immagine](https://github.com/anuraghazra/github-readme-stats/assets/18620868/a728a6ae-ead4-44f8-b989-daff43187149)

Am I missing something?

**Comment by qwerty541** [comment]
> Hi, for me it does not seem to work, even when using the private Vercel solution:
> 
> ![immagine](https://private-user-images.githubusercontent.com/18620868/291066571-5c31a30e-7f68-42d0-b4b0-4e9d980383a9.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDI4NDI1ODAsIm5iZiI6MTcwMjg0MjI4MCwicGF0aCI6Ii8xODYyMDg2OC8yOTEwNjY1NzEtNWMzMWEzMGUtN2Y2OC00MmQwLWI0YjAtNGU5ZDk4MDM4M2E5LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzEyMTclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMjE3VDE5NDQ0MFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWYxMmIyNTMxYzhkYmRhYzgyZjU4ZTg4YTUwZGFiYTcwMmYxNTc2OTU0NDFlNWYyZmY3YTgzNGRjMzQ3ZjVhNTQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.mjKGClMei_7vqO71lDuHkwYANvdYXmYuCupyPW8RIAs) Generated with these options: username=AlessioQuercia&include_all_commits=true&show_icons=true&theme=radical.
> 
> ![immagine](https://private-user-images.githubusercontent.com/18620868/291066592-a728a6ae-ead4-44f8-b989-daff43187149.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDI4NDI1ODAsIm5iZiI6MTcwMjg0MjI4MCwicGF0aCI6Ii8xODYyMDg2OC8yOTEwNjY1OTItYTcyOGE2YWUtZWFkNC00NGY4LWI5ODktZGFmZjQzMTg3MTQ5LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzEyMTclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMjE3VDE5NDQ0MFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWNkOTY0Yzc1M2Y0OGRlMDdjYmNlZjAyMzk1OTc1NmZjNDU0OTUzMmFkMTBjMjBhMTQ3YmMwYzNkZTAxNjI0Y2UmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.kcPNASR4N0a5MmqeBNUNUtXnhT-9J_p-1Smy7u4KBfg)
> 
> Am I missing something?

Answered in https://github.com/anuraghazra/github-readme-stats/discussions/2959#discussioncomment-7878916
