### ISSUE TITLE
Feature request: Creating a new stat card for those users who have used a lot of languages

### ISSUE THREAD

**Issue by yaten2302** [anuraghazra/github-readme-stats#3197]
### Is your feature request related to a problem? Please describe.

Currently there is a card which shows the most used languages like this: <br>
![image](https://github.com/anuraghazra/github-readme-stats/assets/129659514/1e14eba0-eaa3-45c2-bef5-3ee8daa7468e)

But there is no card which shows how many languages the user has used and has knowledge about those.

### Describe the solution you'd like

My solution to this is issue:

A new stat card can be made named - "Multi Lingual" or "Rainbow User".
For example:

If a user has worked on 10 or more languages(say), then a card with a rainbow icon and heading as "Rainbow User" or something similar will be awarded to the user. If suppose the user has worked on <10 languages, then an error message will be generated.

I'll also first make a prototype of the card and then share the sample pic here for further improvements.

**Comment by yaten2302** [comment]
> ### Is your feature request related to a problem? Please describe.
> Currently there is a card which shows the most used languages like this: ![image](https://user-images.githubusercontent.com/129659514/265260159-1e14eba0-eaa3-45c2-bef5-3ee8daa7468e.png)
> 
> But there is no card which shows how many languages the user has used and has knowledge about those.
> 
> ### Describe the solution you'd like
> My solution to this is issue:
> 
> A new stat card can be made named - "Multi Lingual" or "Rainbow User". For example:
> 
> If a user has worked on 10 or more languages(say), then a card with a rainbow icon and heading as "Rainbow User" or something similar will be awarded to the user. If suppose the user has worked on <10 languages, then an error message will be generated.
> 
> I'll also first make a prototype of the card and then share the sample pic here for further improvements.
> 
> ### Describe alternatives you've considered
> _No response_
> 
> ### Additional context
> _No response_

![image](https://github.com/anuraghazra/github-readme-stats/assets/129659514/f3a8c8d9-ab45-435e-ae1a-4c7f4ce41b3c)
<br>
Here is a sample that how this stat card will look like.

**Comment by qwerty541** [comment]
> > ### Is your feature request related to a problem? Please describe.
> > Currently there is a card which shows the most used languages like this: ![image](https://user-images.githubusercontent.com/129659514/265260159-1e14eba0-eaa3-45c2-bef5-3ee8daa7468e.png)
> > But there is no card which shows how many languages the user has used and has knowledge about those.
> > ### Describe the solution you'd like
> > My solution to this is issue:
> > A new stat card can be made named - "Multi Lingual" or "Rainbow User". For example:
> > If a user has worked on 10 or more languages(say), then a card with a rainbow icon and heading as "Rainbow User" or something similar will be awarded to the user. If suppose the user has worked on <10 languages, then an error message will be generated.
> > I'll also first make a prototype of the card and then share the sample pic here for further improvements.
> > ### Describe alternatives you've considered
> > _No response_
> > ### Additional context
> > _No response_
> 
> ![image](https://user-images.githubusercontent.com/129659514/265324960-f3a8c8d9-ab45-435e-ae1a-4c7f4ce41b3c.png) Here is a sample that how this stat card will look like.

@yaten2302 Thanks for your feature request and interest to the project. I don't think that we need additional separate card to show users languages count since you can extend languages card to show up to 20 languages using `&langs_count=n` parameter.

In theory, if necessary, we can increase the maximum number of languages to a larger number.

<img src="https://github-readme-stats.vercel.app/api/top-langs?username=rickstaa&langs_count=20" />
