### ISSUE TITLE
Feature Request: Designing a new stat card for those users who have a lot of stars

### ISSUE THREAD

**Issue by yaten2302** [anuraghazra/github-readme-stats#3198]
### Is your feature request related to a problem? Please describe.

This repo has a feature of showing all the stats of a user in one single card(including stars, commits, prs etc...), like this: <br>
![image](https://github.com/anuraghazra/github-readme-stats/assets/129659514/4271bfab-01a9-4e85-85c7-ee80d21699c1)

But there is no separate card for showing only the number of stars.

### Describe the solution you'd like

My solution to this issue:

A new stat card can be made for only showing the stars. I'll create a prototype of the card and then post the image here for suggestions.

Also if the user has a lot of stars(let's say more than 100), then a title of "Starstuck" or "Stargazer" will be added on the stat card.

**Comment by yaten2302** [comment]
> ### Is your feature request related to a problem? Please describe.
> This repo has a feature of showing all the stats of a user in one single card(including stars, commits, prs etc...), like this: ![image](https://user-images.githubusercontent.com/129659514/265261411-4271bfab-01a9-4e85-85c7-ee80d21699c1.png)
> 
> But there is no separate card for showing only the number of stars.
> 
> ### Describe the solution you'd like
> My solution to this issue:
> 
> A new stat card can be made for only showing the stars. I'll create a prototype of the card and then post the image here for suggestions.
> 
> Also if the user has a lot of stars(let's say more than 100), then a title of "Starstuck" or "Stargazer" will be added on the stat card.
> 
> ### Describe alternatives you've considered
> _No response_
> 
> ### Additional context
> _No response_

![image](https://github.com/anuraghazra/github-readme-stats/assets/129659514/63149a45-4c2a-4834-a807-6ea23a6f479f)
<br>
Here is a sample that how the stat card will look like.

**Comment by cieko** [comment]
It's nice

**Comment by qwerty541** [comment]
> > ### Is your feature request related to a problem? Please describe.
> > This repo has a feature of showing all the stats of a user in one single card(including stars, commits, prs etc...), like this: ![image](https://user-images.githubusercontent.com/129659514/265261411-4271bfab-01a9-4e85-85c7-ee80d21699c1.png)
> > But there is no separate card for showing only the number of stars.
> > ### Describe the solution you'd like
> > My solution to this issue:
> > A new stat card can be made for only showing the stars. I'll create a prototype of the card and then post the image here for suggestions.
> > Also if the user has a lot of stars(let's say more than 100), then a title of "Starstuck" or "Stargazer" will be added on the stat card.
> > ### Describe alternatives you've considered
> > _No response_
> > ### Additional context
> > _No response_
> 
> ![image](https://user-images.githubusercontent.com/129659514/265319954-63149a45-4c2a-4834-a807-6ea23a6f479f.png) Here is a sample that how the stat card will look like.

Hi, @yaten2302! Thanks for your feature request and interest to the project. I don't think that we need separate card for showing only stars because we can reach almost same result using the following query parameters:

`https://github-readme-stats.vercel.app/api?username=anuraghazra&hide=prs,issues,contribs,commits&theme=merko&custom_title=This+user+is+a+stargazer&show_icons=true&hide_rank=true`

<img src="https://github-readme-stats.vercel.app/api?username=anuraghazra&hide=prs,issues,contribs,commits&theme=merko&custom_title=This+user+is+a+stargazer&show_icons=true&hide_rank=true" />

**Comment by rickstaa** [comment]
> > > ### Is your feature request related to a problem? Please describe.
> > > This repo has a feature of showing all the stats of a user in one single card(including stars, commits, prs etc...), like this: ![image](https://user-images.githubusercontent.com/129659514/265261411-4271bfab-01a9-4e85-85c7-ee80d21699c1.png)
> > > But there is no separate card for showing only the number of stars.
> > > ### Describe the solution you'd like
> > > My solution to this issue:
> > > A new stat card can be made for only showing the stars. I'll create a prototype of the card and then post the image here for suggestions.
> > > Also if the user has a lot of stars(let's say more than 100), then a title of "Starstuck" or "Stargazer" will be added on the stat card.
> > > ### Describe alternatives you've considered
> > > _No response_
> > > ### Additional context
> > > _No response_
> > 
> > 
> > ![image](https://user-images.githubusercontent.com/129659514/265319954-63149a45-4c2a-4834-a807-6ea23a6f479f.png) Here is a sample that how the stat card will look like.
> 
> Hi, @yaten2302! Thanks for your feature request and interest to the project. I don't think that we need separate card for showing only stars because we can reach almost same result using the following query parameters:
> 
> `https://github-readme-stats.vercel.app/api?username=anuraghazra&hide=prs,issues,contribs,commits&theme=merko&custom_title=This+user+is+a+stargazer&show_icons=true&hide_rank=true`
> 
> ![](https://camo.githubusercontent.com/df665096c1a4105d7eeefd08ef337d65fc6c4771aac2dbfa50e4442bfe86288c/68747470733a2f2f6769746875622d726561646d652d73746174732e76657263656c2e6170702f6170693f757365726e616d653d616e7572616768617a726126686964653d7072732c6973737565732c636f6e74726962732c636f6d6d697473267468656d653d6d65726b6f26637573746f6d5f7469746c653d546869732b757365722b69732b612b7374617267617a65722673686f775f69636f6e733d7472756526686964655f72616e6b3d74727565)

@yaten2302 Congrats on your first GRS PR. It is fantastic to see that you managed to create such a good-look card 🎉! I hope you had fun doing it and gave you a bit of insight into how the codebase works.

Unfortunately, I agree with @qwerty541 that the card is redundant since users can create a similar card by hiding all the other stats 😅 .
