### ISSUE TITLE
github-readme-stats shows discrepant data

### ISSUE THREAD

**Issue by daniel1kp** [anuraghazra/github-readme-stats#3199]
### Describe the bug

I was trying to get my private contributions/commits to show up on the stats page so I created my own vercel instance and used my personal access token to do so. While I run the rest call on my browser, I'm able to see all my private contributions perfectly but when I run the rest call  in my README.md page it doesn't reflect the same data even though it's the same link. I'm somehow able to pull the most languages used data but I'm not able to pull the stats. Can someone help me figure this out?

### Expected behavior

[GitHub Stats Link](https://github-readme-stats-daniel1kp.vercel.app/api?username=daniel1kp&include_all_commits=true&show_icons=true&theme=midnight-purple&hide_border=true&hide=stars)

![image](https://github.com/anuraghazra/github-readme-stats/assets/62495751/76a08ca2-dfcc-4420-bdfc-5f41adcc32a3)

### Screenshots / Live demo link

![image](https://github.com/anuraghazra/github-readme-stats/assets/62495751/77b8904d-2ebc-4bda-8d13-37b8c7cccbb7)

**Comment by daniel1kp** [comment]
I'm not sure what happened but it seems to be working now, guessing it took time to load(?).
I was trying to debug this for the last 2 hours but it seems to resolve automatically somehow.
![image](https://github.com/anuraghazra/github-readme-stats/assets/62495751/98302724-7244-4043-bba0-b0ca98373a21)

**Comment by rickstaa** [comment]
> I'm not sure what happened but it seems to be working now, guessing it took time to load(?). I was trying to debug this for the last 2 hours but it seems to resolve automatically somehow. ![image](https://user-images.githubusercontent.com/62495751/265265320-98302724-7244-4043-bba0-b0ca98373a21.png)

@daniel1kp sorry for the confusion and for wasting your time debugging this issue. We use caching to reduce the load of our public instance (see https://github.com/anuraghazra/github-readme-stats?tab=readme-ov-file#common-options). I agree that the documentation could be improved 😅. Feel free to create a pull request.
