### ISSUE TITLE
Feature Request: Designing a new stat card for showing GitHub streak

### ISSUE THREAD

**Issue by yaten2302** [anuraghazra/github-readme-stats#3209]
### Is your feature request related to a problem? Please describe.

The GRS has a lot of stats cards included, but there is no card for showing the streak of the user.

### Describe the solution you'd like

My solution to this issue:

Creating a new stat card for showing the total contributions, current streak and the longest streak of the user(along with date)
I'll also share the sample template that how the stat card will look like, once this issue gets approved.

**Comment by qwerty541** [comment]
Hi, @yaten2302! Thanks for your feature request! The following repository already provides such card https://github.com/DenverCoder1/github-readme-streak-stats. I have nothing against having streak stats card in this project, but on condition that this card will have unique design, significatly different from the one you provided. I don't see the point in two different projects providing the same card.

**Comment by yaten2302** [comment]
> Hi, @yaten2302! Thanks for your feature request! The following repository already provides such card https://github.com/DenverCoder1/github-readme-streak-stats. I have nothing against having streak stats card in this project, but on condition that this card will have unique design, significatly different from the one you provided. I don't see the point in two different projects providing the same card.

Yeah😅, actually, this project is made using `php`, so that's why I thought of creating this issue, since it's in `JavaScript`. If not required may I close this issue?

**Comment by qwerty541** [comment]
> > Hi, @yaten2302! Thanks for your feature request! The following repository already provides such card https://github.com/DenverCoder1/github-readme-streak-stats. I have nothing against having streak stats card in this project, but on condition that this card will have unique design, significatly different from the one you provided. I don't see the point in two different projects providing the same card.
> 
> Yeah😅, actually, this project is made using `php`, so that's why I thought of creating this issue, since it's in `JavaScript`. If not required may I close this issue?

Having a streak stats card may be a good feature for this project, we can keep this issue open if you or anyone else are up to create unique design. If you do not want to do this feel free to close.

**Comment by yaten2302** [comment]
Yeah sure😃, I would love to work on this issue, will try to make a better design and then will send it here for more modifications and improvements 👍

**Comment by rickstaa** [comment]
> > > Hi, @yaten2302! Thanks for your feature request! The following repository already provides such card https://github.com/DenverCoder1/github-readme-streak-stats. I have nothing against having streak stats card in this project, but on condition that this card will have unique design, significatly different from the one you provided. I don't see the point in two different projects providing the same card.
> > 
> > 
> > Yeah😅, actually, this project is made using `php`, so that's why I thought of creating this issue, since it's in `JavaScript`. If not required may I close this issue?
> 
> Having a streak stats card may be a good feature for this project, we can keep this issue open if you or anyone else are up to create unique design. If you do not want to do this, feel free to close.

@yaten2302, thanks for wanting to contribute to GRS. Providing users with a streak card is logical. Since it is a good design, I am okay with the card being close to https://github.com/DenverCoder1/github-readme-streak-stats. But I agree with @qwerty541 that having a unique design would make it less redundant 👍🏻.

**Comment by yaten2302** [comment]
![image](https://github.com/anuraghazra/github-readme-stats/assets/129659514/f319cafe-4dae-4a9d-9ea2-df5799793938)
<br>
This is how the card will look like. It will be great if someone wants to suggest some modifications or improvements in it.

**Comment by yaten2302** [comment]
> ![image](https://user-images.githubusercontent.com/129659514/267853058-205ca7c9-92ba-49d0-aae6-2acd5b83da6e.png)
> 
> 
> This is how the card will look like. It will be great if someone wants to suggest some modifications or improvements in it. Alternatively the days will be added in place of weeks, as per the user's requirements.

Hi @rickstaa , @qwerty541 is this design looking good or should I make some changes in it?

**Comment by qwerty541** [comment]
> > ![image](https://user-images.githubusercontent.com/129659514/267853058-205ca7c9-92ba-49d0-aae6-2acd5b83da6e.png)
> > This is how the card will look like. It will be great if someone wants to suggest some modifications or improvements in it. Alternatively the days will be added in place of weeks, as per the user's requirements.
> 
> Hi @rickstaa , @qwerty541 is this design looking good or should I make some changes in it?

Hi, @yaten2302. Looks the same as our stats card, nothing special, but I think it will suit us. But I would have written "Person's streak stats" instead of "Person's streak info". Also I wouldn't make the title in italics. I also hope that you understand that this card should support all our themes as well as other cards and this blue coloring is only for example, by default the card should be displayed in the standard GItHub theme.

**Comment by qwerty541** [comment]
> > > > ![image](https://user-images.githubusercontent.com/129659514/267853058-205ca7c9-92ba-49d0-aae6-2acd5b83da6e.png)
> > > > This is how the card will look like. It will be great if someone wants to suggest some modifications or improvements in it. Alternatively the days will be added in place of weeks, as per the user's requirements.
> > > 
> > > 
> > > Hi @rickstaa , @qwerty541 is this design looking good or should I make some changes in it?
> > 
> > 
> > Hi, @yaten2302. Looks the same as our stats card, nothing special, but I think it will suit us. But I would have written "Person's streak stats" instead of "Person's streak info". Also I wouldn't make the title in italics. I also hope that you understand that this card should support all our themes as well as other cards and this blue coloring is only for example, by default the card should be displayed in the standard GItHub theme.
> 
> Sure, I'll change the heading to "Person's streak stats" and remove the italics. Yes, this theme is just for example, all the themes will be made available for the user and the default will also be set to standard GitHub theme.

Nice, let's wait also for @rickstaa's thoughts about this.

**Comment by idkbharti** [comment]
![Screenshot 2023-09-23 201127](https://github.com/anuraghazra/github-readme-stats/assets/69758977/c438fcc2-8946-4aa7-a4f7-56e224ca40d4)
How about this ?

**Comment by yaten2302** [comment]
Hi @rickstaa, @qwerty541, I've made the streaks card. Everything is working fine, but I'm facing 2 problems:

1. How to change the page title <br>
![image](https://github.com/anuraghazra/github-readme-stats/assets/129659514/45496057-58e6-40b5-8742-eb8442103509)
If the page title should be "Person's Streak Stats", I'm not able to do that. <br><br><br><br><br>
2. In the streaks card, by default all the info will be shown, and then the user can hide the unnecessary things using `hide`, but in the card only the first 2 are showing up and the rest are not visible, rather, the space is visible. <br>
![image](https://github.com/anuraghazra/github-readme-stats/assets/129659514/d9dbe1e4-4efa-44cc-97b0-88b952bba2a0) <br>
![image](https://github.com/anuraghazra/github-readme-stats/assets/129659514/89f5c223-0eea-45a8-9374-2c3e6c8cd32e)

**Comment by yaten2302** [comment]
Hi @rickstaa, @qwerty541 <br>
I've created the [PR for Streaks Card](https://github.com/anuraghazra/github-readme-stats/pull/3338/commits) <br>
Could you please review and merger it. <br><br>
Also could you please add the `hacktoberfest` label to this issue.

**Comment by airwakz** [comment]
@rickstaa can i do this task now as most of them have alerady been assigned

**Comment by rickstaa** [comment]
Closed since the core team decided that adding this card is currently not the best thing to do. For more information see https://github.com/anuraghazra/github-readme-stats/pull/3338#issuecomment-1762966088.
