### ISSUE TITLE
Сonfusing behavior of showing 0 commits when upstream API fails.

### ISSUE THREAD

**Issue by qwerty541** [anuraghazra/github-readme-stats#3225]
Related to https://github.com/anuraghazra/github-readme-stats/pull/3186#issuecomment-1713454738

### Problem

I think that current behavior of stats card which shows 0 commits when upstream API fails and `&include_all_commits=true` query parameter specified is wrong bacause such behavior is not obvious for users and confuse them. Recently i also had to answer some issues/discussions with questions from users about why their card showing 0 commits. I think it would be pretty stupid to show users zero statistics for every error instead of error message, but for some reason the total number of commits is done this way, I personally don’t see any particular reason to leave this behavior.

### Suggested solution

I think that it will be better to render error card with message aksking user to try later in this case.

@rickstaa Let me know if you are up to approve such changes, then i will try to find time for creating a pull request.

**Comment by rickstaa** [comment]
@ qwerty541 such an improvement would be remarkable since the current behavoir is strange. We can improve the caching behavoir to make the card try earlier when this endpoint fails. See all comments at https://github.com/anuraghazra/github-readme-stats/pull/2448 👍🏻. I don't have enough OS budget to implement such a think; feel free to take this on if you have the time.

**Comment by qwerty541** [comment]
@rickstaa Recently i have opened https://github.com/anuraghazra/github-readme-stats/pull/3238 which should resolve this issue, check it please when you have free time.

Pull request https://github.com/anuraghazra/github-readme-stats/pull/2448 with improving of error caching behavior looks good to me, i will try to find time to merge it with master.
