### ISSUE TITLE
Application Crash

### ISSUE THREAD

**Issue by Dev-CasperTheGhost** [anuraghazra/github-readme-stats#324]
_This is not 100% a bug but I'll put it here so you can notice it._

**Describe the bug**
Pins/stats not showing because the application on vercel crashed/was deleted (see screenshot)

**Screenshots / Live demo link (paste the github-readme-stats link as markdown image)**
[demo-link](https://github-readme-stats.vercel.app/api/pin?username=dev-caspertheghost&repo=ghostybot&title_color=fff&icon_color=4c71f2&text_color=9f9f9f&bg_color=151515)
![image](https://user-images.githubusercontent.com/53900565/89615403-d50f7a00-d886-11ea-80f6-75951f9b566a.png)

**Comment by anuraghazra** [comment]
read #325

**Comment by Dev-CasperTheGhost** [comment]
Alright, thanks
