### ISSUE TITLE
ReadMe stats not working with "Could not fetch total commits" error message

### ISSUE THREAD

**Issue by Iamtsquare07** [anuraghazra/github-readme-stats#3243]
### Describe the bug

The readme stats for the GitHub contribution failed to load and give a link to this repo. The error message: Could not fetch total commits

### Expected behavior

Was supposed to show stats including total commits

### Screenshots / Live demo link

https://github-readme-stats.vercel.app/api
https://github.com/Iamtsquare07/issues-images/blob/main/Images/Screenshot%202023-09-17%20194120.png

**Comment by qwerty541** [comment]
Hey, @Iamtsquare07! Thanks for the report! You can see this when upstream GitHub API respond with error due to some reason during fetching stats card data. Should be resolve automatically after some time. Currently stats card in your profile works well.

@rickstaa I think that we can improve error message in case of total commits fetch error to contain words like "try again later". Error message should be more clear and tell user what he can do about the error. Are you up to approve pull request with such changes? Do you have a better idea about error message content?

**Comment by rickstaa** [comment]
> Hey, @Iamtsquare07! Thanks for the report! You can see this when upstream GitHub API respond with error due to some reason during fetching stats card data. Should be resolve automatically after some time. Currently stats card in your profile works well.
> 
> @rickstaa I think that we can improve error message in case of total commits fetch error to contain words like "try again later". Error message should be more clear and tell user what he can do about the error. Are you up to approve pull request with such changes? Do you have a better idea about error message content?

@qwerty541 I agree that the current message could improved even further to prevent people from continuing to open new issues 👍🏻.

**Comment by Iamtsquare07** [comment]
Thanks for providing the update @rickstaa yes it was resolved after a few minutes, and as @qwerty541 suggested if this is not a serious error that does not require any action from the user, then there shouldn't be an error directing users to open an issue since this could cause many not so important pull requests.

**Comment by nu11secur1ty** [comment]
> ### Describe the bug
> The readme stats for the GitHub contribution failed to load and give a link to this repo. The error message: Could not fetch total commits
> 
> ### Expected behavior
> Was supposed to show stats including total commits
> 
> ### Screenshots / Live demo link
> https://github-readme-stats.vercel.app/api https://github.com/Iamtsquare07/issues-images/blob/main/Images/Screenshot%202023-09-17%20194120.png
> 
> ### Additional context
> _No response_

Fix the URL:[https://github.com/anuraghazra/github-readme-stats/blob/master/themes/README.md] BR ;)

**Comment by rickstaa** [comment]
We merged https://github.com/anuraghazra/github-readme-stats/pull/3255 to improve the error message.
