### ISSUE TITLE
Request Top Language Stats

### ISSUE THREAD

**Issue by wiefunkdai** [anuraghazra/github-readme-stats#3244]
### Is your feature request related to a problem? Please describe.

Language Stat showing is good, but I need include language with my contribute on another repo.

### Describe the solution you'd like

Show languange with contribute on organization and another people/state.

**Comment by rickstaa** [comment]
Duplicate of #https://github.com/anuraghazra/github-readme-stats/issues/1. This is one of our most requested features, and we will release it in the future. You can already use it on your own Vercel instance. Please check https://github.com/anuraghazra/github-readme-stats/issues/1.
