### ISSUE TITLE
NOTICE: DEPLOYMENT IS CURRENTLY DISABLED

### ISSUE THREAD

**Issue by anuraghazra** [anuraghazra/github-readme-stats#325]
Hi everyone, currently github-readme-stats is down because of this ->

![vercel-support](https://user-images.githubusercontent.com/35374649/89615630-a7392e00-d8a4-11ea-9818-443c8b32703f.PNG)

**Comment by anuraghazra** [comment]
Meanwhile consider deploying on your own fork. follow the guide -> https://github.com/anuraghazra/github-readme-stats#deploy-on-your-own-vercel-instance

**Comment by TanishShinde** [comment]
Is there a timeline in which it will be fixed?

**Comment by anuraghazra** [comment]
> Is there a timeline in which it will be fixed?

It should be fixed right now. but now sure if it will happen again.

**Comment by TanishShinde** [comment]
Ok Thanks! 😇

**Comment by Spiderpig86** [comment]
Heads up, seems to be down again.

**Comment by meganyin13** [comment]
Yup, my README stats seem to be down as well

**Comment by GideonWolfe** [comment]
Can confirm!

**Comment by JubayerJoy** [comment]
Still down!

**Comment by hector-manny** [comment]
still down

**Comment by AbdElraoufSabri** [comment]
still an issue

**Comment by AnmolTomer** [comment]
> > Is there a timeline in which it will be fixed?
> 
> It should be fixed right now. but now sure if it will happen again.

Still down. Let us know if you need help with testing or in any way we can help.

**Comment by J2TeamNNL** [comment]
![image](https://user-images.githubusercontent.com/26674308/89700915-a4017900-d95c-11ea-8834-aa1502bfe626.png)
I have deploy my own Vercel but have this issue

**Comment by chandan-reddy-k** [comment]
@J2TeamNNL did you create your own token and save it in vercel environment as described in point 9?

> Select root and keep everything as is, just add your environment variable named PAT_1 (as shown), which will contain a personal access token (PAT), which you can easily create here (leave everything as is, just name it something, it can be anything you want)

**Comment by ravenCrown0627** [comment]
Same here, and I had tried to create my own token and both vercel environment and GitHub too, and it is still not working 

> @J2TeamNNL did you create your own token and save it in vercel environment as described in Readme.md point 9?
> 
> > Select root and keep everything as is, just add your environment variable named PAT_1 (as shown), which will contain a personal access token (PAT), which you can easily create here (leave everything as is, just name it something, it can be anything you want)

**Comment by ajaygalagali** [comment]
Still down

**Comment by J2TeamNNL** [comment]
> @J2TeamNNL did you create your own token and save it in vercel environment as described in Readme.md point 9?
> 
> > Select root and keep everything as is, just add your environment variable named PAT_1 (as shown), which will contain a personal access token (PAT), which you can easily create here (leave everything as is, just name it something, it can be anything you want)

I did

**Comment by anserwaseem** [comment]
I deployed 7 hours ago, but nothing is running. Followed all the steps, just don't know what is missing.

**Comment by Livenow14** [comment]
@anuraghazra  Is it should be deployed to fix error?

**Comment by chandan-reddy-k** [comment]
> Same here, and I had tried to create my own token at both vercel environment and GitHub too, and it is still not working
> 
> I'm guessing, maybe I had taken a wrong link? Or somewhat problem I missed out?
> 
> > @J2TeamNNL did you create your own token and save it in vercel environment as described in Readme.md point 9?
> > > Select root and keep everything as is, just add your environment variable named PAT_1 (as shown), which will contain a personal access token (PAT), which you can easily create here (leave everything as is, just name it something, it can be anything you want)

The moment I created the token, gave necessary permissions and **re-deployed** on vercel (after including the token in environments), it started working for me. Not sure why it's not working. 😕

<img width="1110" alt="Screenshot 2020-08-08 at 10 56 25 AM" src="https://user-images.githubusercontent.com/43699825/89703227-496d1a80-d966-11ea-8373-f8aa563843a5.png">

**Comment by Mins0o** [comment]
I got it [working](https://github.com/Mins0o) by creating my own repo and importing it.
Before uploading the clone to the repository, I deleted the git/vercel related files just in case.
also, remeber you should change the URL to your own deplyment URL

**Comment by Mins0o** [comment]
...And I think it's fixed for [Anuraghazra](https://github.com/anuraghazra) too!

**Comment by mrdulin** [comment]
Hit this issue. After I changed the environment variable from `github_readme_stats` to `PAT_1` and re-deployed. It works.

**Comment by SukkaW** [comment]
@anuraghazra 

Considering adding Cloudflare in front of Vercel? Cloudflare supports 100TB reasonable bandwidth usage on free plan, and 
 can be used to cache with `cache-control` header.

**Comment by filiptronicek** [comment]
We would need a different domain for that, CloudFlare is nice, but I think Vercel is enough. They don't limit the usage of the serverless functions, it just seems something went wrong with our code. @SukkaW

**Comment by SukkaW** [comment]
> We would need a different domain for that, CloudFlare is nice, but I think Vercel is enough. They don't limit the usage of the serverless functions, it just seems something went wrong with our code.

I do agree, since if `cache-control` is set, GitHub Camo will cache the response as well (Which means no extra CDN is required).

**Comment by anuraghazra** [comment]
> I do agree, since if cache-control is set GitHub Camo will cache the response as well (Which means no extra CDN is required).


This is correct Github Camo CDN caches the renspose svg. so no need for an extra CDN. 

> it just seems something went wrong with our code.
Which i don't know whats wrong nor Vercel support has any idea.

**Comment by TanishShinde** [comment]
I agree with @filiptronicek

**Comment by TanishShinde** [comment]
> We would need a different domain for that, CloudFlare is nice, but I think Vercel is enough. They don't limit the usage of the serverless functions, it just seems something went wrong with our code. @SukkaW

I do agree

**Comment by ridays2001** [comment]
When will this be back up again?

**Comment by anuraghazra** [comment]
> When will this be back up again?

Don't have any expected schedule for fix. consider deploying on your own vercel instance.

**Comment by ridays2001** [comment]
> 
> 
> > When will this be back up again?
> 
> Don't have any expected schedule for fix. consider deploying on your own vercel instance.

Yea, after reading multiple issues, I found out that a lot of people are using this one. So, I decided to make my own... Thanks thought 👍🏻

**Comment by qinyihao** [comment]
@anuraghazra Now I still can't access the instance though my own vercel instance.
It says something like this([Link](https://github-readme-stats-beta-ebon.vercel.app/api?hide_border=true&count_private=true&username=qinyihao&show_icons=true)):
![image](https://user-images.githubusercontent.com/40647091/90374634-614f4780-e0a6-11ea-93c3-2176c4027b2c.png)

**Comment by anuraghazra** [comment]
@qinyihao 

You are missing PAT_1, make sure you redeploy. 
Please read the docs carefully and there is also a youtube videos.

**Comment by qinyihao** [comment]
> @qinyihao
> 
> You are missing PAT_1, make sure you redeploy.
> Please read the docs carefully and there is also a youtube video.

@anuraghazra Thanks. I've get it resolved.

**Comment by qinyihao** [comment]
@anuraghazra The server is on again.
`![](https://github-readme-stats.vercel.app/api?username=anuraghazra&show_icons=true&hide_border=true&count_private=true)`
![](https://github-readme-stats.vercel.app/api?username=anuraghazra&show_icons=true&hide_border=true&count_private=true)

**Comment by anuraghazra** [comment]
Get ready for downtime 😆 

![image](https://user-images.githubusercontent.com/35374649/101359411-3f323d00-38c2-11eb-87e0-538f2bcab830.png)

**Comment by qinyihao** [comment]
> Get ready for downtime 😆
> 
> ![image](https://user-images.githubusercontent.com/35374649/101359411-3f323d00-38c2-11eb-87e0-538f2bcab830.png)

OK, thank you for notifying me.

**Comment by anuraghazra** [comment]
Hey everyone my vercel account is again blocked. 

![image](https://user-images.githubusercontent.com/35374649/101527059-88ae8500-39b3-11eb-8c16-0b8c144cbd67.png)


Please consider deploying github-readme-stats on your own vercel instance for further use. 
Tutorial: https://www.youtube.com/watch?v=n6d4KHSKqGk&feature=youtu.be&t=107

**Comment by jrnewton** [comment]
If anyone is interested I've added a small shim to run the code via Express.  See [this commit](https://github.com/jrnewton/github-readme-stats/commit/779289e6c8900ff9b2652c70de622007afd39286) on my fork.  It will automagically setup each route based on the contents API directory like Vercel seems to do (that's just a guess since I don't use that service).

**Comment by TheOddGarlic** [comment]
It is back apparently?

**Comment by HamzaAnis** [comment]
> It is back apparently?

Yes somehow it is.

**Comment by anuraghazra** [comment]
> > It is back apparently?
> 
> Yes somehow it is.

Because vercel is now sponsoring github-readme-stats and we now have their Pro team subscription, which gives 1000GB of serverless function quota.

So hopefully we don't have to worry about deployments getting disabled for overusing. 
#703

**Comment by vybhav72954** [comment]
@anuraghazra Server down again?

**Comment by anuraghazra** [comment]
> @anuraghazra Server down again?

No it's fine

**Comment by flamerged** [comment]
Can someone elaborate the use of the github token? I have never seen them before and the guide does not go into detail what access rights to give to the token. Would appreciate some feedback.

**Comment by anuraghazra** [comment]
@flamerged 

> I redeployed after following the video tutorial. It did not work in the beginning, but after retrying a dozen time to edit my readme it worked.

It was probably got cached. 

--------

If your issue is not fixed yet, I would recommend you to see your vercel serverless function logs that might give you some detailed error information. 

Or first try to deploy on your localmachine (localhost) via Vercel CLI and test things out. 


> Although if you followed the video tutorial correctly everything should work fine.

**Comment by flamerged** [comment]
> @flamerged
> 
> > I redeployed after following the video tutorial. It did not work in the beginning, but after retrying a dozen time to edit my readme it worked.
> 
> It was probably got cached.
> 
> If your issue is not fixed yet, I would recommend you to check your vercel serverless function logs that might give you some detailed error information.
> 
> Or first try to deploy on your localmachine (localhost) via Vercel CLI and test things out.
> 
> > Although if you followed the video tutorial correctly everything should work fine.

It did thank you :)

**Comment by ruchern-chong** [comment]
Is this still a problem because this is still pinned.

**Comment by filiptronicek** [comment]
@ruchern-chong this is pinned, because it may happen on self hosted instances or on the official one if something goes wrong, so for future reference this is pinned.
