### ISSUE TITLE
[Feature] Render error card in same theme as requested card

### ISSUE THREAD

**Issue by qwerty541** [anuraghazra/github-readme-stats#3259]
I think we should render the error card using the same theme to not break user's profile color scheme.

![image](https://github.com/anuraghazra/github-readme-stats/assets/53787217/b6189ff0-26a9-42b5-b812-a224ac1dac53)

**Comment by rickstaa** [comment]
Great idea!

**Comment by notpritam** [comment]
can you please assign this to me , i want to work on this..
thanku

**Comment by qwerty541** [comment]
> can you please assign this to me , i want to work on this.. thanku

Hey, @notpritam! Thanks for considering contributing to our project. I'm looking forward to your pull request.

**Comment by notpritam** [comment]
> > can you please assign this to me , i want to work on this.. thanku
> 
> Hey, @notpritam! Thanks for considering contributing to our project. I'm looking forward to your pull request.

thanks a lot for giving this task to me...

**Comment by GuntreddyHemanth** [comment]
Can you please assign me, I make sure you feel happy after my work...

**Comment by notpritam** [comment]
@qwerty541 , Hi, i have fixed the error you can check it here : - [Here](https://github-readme-stats-azure-zeta.vercel.app/api?username=notpritam&hide=contribs,prs&theme=dark&title_color=fff)

also i wanted to ask , i have fixed it by introducing a new parmas (bg is still remaining , i will fix that to before creating PR) , 

``` js
res.send(
      renderError(err.message, err.secondaryMessage, {
        title_color,
        text_color,
        bg_color,
        border_color,
        theme,
      }),
    );
```

is this way acceptable ?
this is going to be my first open source contributions so sorry for asking a lot of questions.

**Comment by notpritam** [comment]
@qwerty541 , hello i have created the pull request [link](https://github.com/anuraghazra/github-readme-stats/pull/3298) for this feature,
please review it and merge it whenever you come online.
thank you...

**Comment by qwerty541** [comment]
> Can you please assign me, I make sure you feel happy after my work...

Hey, @GuntreddyHemanth! Thanks for your interest in our project! We already have approved pull request which will resolve this issue. Feel free to choose another issue that you are interested to work on and contact me.

**Comment by qwerty541** [comment]
> @qwerty541 , hello i have created the pull request [link](https://github.com/anuraghazra/github-readme-stats/pull/3298) for this feature, please review it and merge it whenever you come online. thank you...

I left my review, check it out https://github.com/anuraghazra/github-readme-stats/pull/3298#pullrequestreview-1671447090
