### ISSUE TITLE
"Could not fetch total commits."

### ISSUE THREAD

**Issue by Xytriza** [anuraghazra/github-readme-stats#3264]
### Describe the bug

**Something went wrong! file an issue at https://tiny.one/readme-stats
Could not fetch total commits.**

### Expected behavior

should show a profile banner not an error

### Screenshots / Live demo link

![](https://github.com/anuraghazra/github-readme-stats/assets/144849202/2edde734-4260-4dd1-bdea-ac4b07a4966c)

**Comment by Xytriza** [comment]
**https://github-readme-stats.vercel.app/api?username=Xytriza&show_icons=true&bg_color=333&text_color=fff&title_color=D1D1D1&icon_color=D1D1D1&border_radius=8&hide=prs&include_all_commits=true**

**Comment by Xytriza** [comment]
it seemed to fix after i commited

**Comment by Xytriza** [comment]
and it broke

**Comment by Xytriza** [comment]
im pretty sure that **&include_all_commits=true** is causing the issue

**Comment by rickstaa** [comment]
Merged #3255. Thanks @qwerty541!

**Comment by CamilaDziubat** [comment]
It was actually a statistical error, it was automatically corrected after a while.

**Comment by qwerty541** [comment]
> You can see this when upstream GitHub API respond with error due to some reason during fetching stats card data. Should be resolve automatically after some time. Currently stats card in your profile works well.

Hey @ak47us. You can see this when upstream GitHub API respond with error due to some reason during fetching stats card data. Should be resolve automatically after some time. Currently stats card in your profile works well.

**Comment by diogorangel** [comment]
Thank you so much . I had this problem today and I solve with this solution 👍🏾 : https://github.com/anuraghazra/github-readme-stats/issues/3264#issuecomment-1728503867

I'd apllied here: https://github.com/diogorangel/diogorangel/blob/main/README.md
