### ISSUE TITLE
[enhancment] Show number of `followers` on the Github Stats card

### ISSUE THREAD

**Issue by BobAnkh** [anuraghazra/github-readme-stats#327]
**Is your feature request related to a problem? Please describe.**

It's just an idea to add number of `followers` on the card. Have this already discussed or implemented?

**Describe the solution you'd like**

Just get the number of `followers` through Github API and show it on the card.

**Describe alternatives you've considered**

**Additional context**

**Comment by nombrekeff** [comment]
Hmm, is this needed? I mean, follower count is already displayed on the Github profile...

**Comment by BobAnkh** [comment]
Well, I just thought of showing them all at one place :joy:, which I think is one of the  rankings.

Maybe it is duplicate.  Or maybe can this be an option?

**Comment by nombrekeff** [comment]
yeah, I guess the best option would be to not show it by default. And each one decides whether to show it or not, I think this is what @rjoydip did in his PR

**Comment by BobAnkh** [comment]
Yeah. I totally agree with you. I think this should be set not to show by default. And I just discovered @rjoydip PR. That's great. Thank you @nombrekeff  and @rjoydip

**Comment by anuraghazra** [comment]
> Hmm, is this needed? I mean, follower count is already displayed on the Github profile...

Yeah @BobAnkh We don't want to add any stats which is already visible from Github's UI.

**Comment by rjoydip** [comment]
@anuraghazra But this will be helpful for external use. When someone works on markdown based documentation or `mdx` based application.

**Comment by anuraghazra** [comment]
Well i'm not sure if stats card are even useful in other markdown pages, there are no regular use case.

Only the RepoCards have good external use case for blogposts & stuff.

We can of course add all the stats but it would just bloat it with lots of options.

**Comment by rjoydip** [comment]
> We can of course add all the stats but it would just bloat it with lots of options.
Right.

**Comment by BobAnkh** [comment]
> We can of course add all the stats but it would just bloat it with lots of options.

@anuraghazra Understand that. I will close this issue then.
