### ISSUE TITLE
Repository creation failed.

### ISSUE THREAD

**Issue by hi-dhl** [anuraghazra/github-readme-stats#328]
hi:

I've already read guide on setting up Vercel 

when I deploy the project in the Vercel,  the Vercel has tip "Repository creation failed."

**Comment by nombrekeff** [comment]
Hey @hi-dhl take a look at this issue https://github.com/anuraghazra/github-readme-stats/issues/325

**Comment by hi-dhl** [comment]
![image](https://user-images.githubusercontent.com/16751752/89780357-df11d100-db43-11ea-96e9-50afb93c6c9e.png)

i have another question, can u help me how to solve it ?

**Comment by nombrekeff** [comment]
Is this happening on your own deployment?

**Comment by hi-dhl** [comment]
en, deployed success, then I want to use my domain to use the API but isn't work

**Comment by nombrekeff** [comment]
You must configure PAT_ env variables, with a personal token. Have you set them?

ie:
`PAT_1=<token>`

You can have up to 8 of them If I recall correctly.

**Comment by anuraghazra** [comment]
After setting PAT_1 make sure you redeploy.

**Comment by hi-dhl** [comment]
thanks @anuraghazra  @nombrekeff
