### ISSUE TITLE
Username not found error.

### ISSUE THREAD

**Issue by Harkirattttt** [anuraghazra/github-readme-stats#3286]
### Describe the bug

My username is not getting detected please help me fix this.

### Screenshots / Live demo link

![image](https://github.com/anuraghazra/github-readme-stats/assets/102346627/76a5668b-eb54-4f1f-8311-5d908d5b04eb)

**Comment by Pratik1603** [comment]
Please assign this to me

**Comment by qwerty541** [comment]
@Harkirattttt It works, looks like you made a mistake in URL.

![image](https://github.com/anuraghazra/github-readme-stats/assets/53787217/04175e04-bfe9-4e33-ae32-d03f79abffeb)

```html
<img src="https://github-readme-stats.vercel.app/api?username=Harkirattttt" />
```

<img src="https://github-readme-stats.vercel.app/api?username=Harkirattttt" />
