### ISSUE TITLE
404 Not found, DEPLOYMENT_DISABLED

### ISSUE THREAD

**Issue by jopemachine** [anuraghazra/github-readme-stats#331]
**Describe the bug**
404 Not found, DEPLOYMENT_DISABLED

<hr />

**Expected behavior**
Display the badge image correctly.

<hr />

**Markdown Code**
```
[![github stats](https://github-readme-stats.vercel.app/api?username=jopemachine&count_private=true)](https://github.com/jopemachine/jopemachine)
```

Result: 

[![github stats](https://github-readme-stats.vercel.app/api?username=jopemachine&count_private=true)](https://github.com/jopemachine/jopemachine)

<hr />

**Screenshots / Live demo link (paste the github-readme-stats link as markdown image)**

<img width="843" alt="2020-08-07_18-05-04" src="https://user-images.githubusercontent.com/18283033/89698913-a7532100-d8d8-11ea-8fde-a221e10b621e.png">

<hr />

**Additional context**

I think something goes wrong in the server....

None of the demos of README.md are properly displayed.

<img width="929" alt="2020-08-07_18-09-12" src="https://user-images.githubusercontent.com/18283033/89699030-41b36480-d8d9-11ea-92a2-97e64e8b0bc1.png">

**Comment by potreco** [comment]
Same here 👋🏻

**Comment by J2TeamNNL** [comment]
I just check, the same error

Hope fix soon

**Comment by roeintheglasses** [comment]
Just checked. Got the same error.

**Comment by GuilhermeTerriaga** [comment]
Same here

**Comment by felipe-allmeida** [comment]
I'm with the same error  🤕

**Comment by AbdElraoufSabri** [comment]
same here

**Comment by rajitbanerjee** [comment]
> **Describe the bug**
> 404 Not found, DEPLOYMENT_DISABLED

> I think something goes wrong in the server....
> 
> None of the demos of README.md are properly displayed.

@jopemachine Look at notice #325. Deploy a fork of the repository on your own Vercel instance to resolve the issue.

**Comment by Itsbeenalongday** [comment]
same here

**Comment by StevenJokes** [comment]
+1

**Comment by kitae0522** [comment]
same here

**Comment by calvinchankf** [comment]
> > **Describe the bug**
> > 404 Not found, DEPLOYMENT_DISABLED
> 
> > I think something goes wrong in the server....
> > None of the demos of README.md are properly displayed.
> 
> @jopemachine Look at notice #325. Deploy a fork of the repository on your own Vercel instance to resolve the issue.

Thanks! It works

**Comment by gunyu1019** [comment]
Same here

**Comment by imba-tjd** [comment]
No more "same here" or "+1" pls 🙏. You can simply subscribe this.

**Comment by h5jam** [comment]
I saw your stats returned to normal. But not to me. Did you fix it?

**Comment by anuraghazra** [comment]
Hey everyone please be patient, see #325 we are looking into the issue.

**Comment by jopemachine** [comment]
> I saw your stats returned to normal. But not to me. Did you fix it?

Yes, see #325 as @rajitbanerjee mentioned.

You can deploy and use a fork of the repository on your own.

Refer to the below section.

https://github.com/anuraghazra/github-readme-stats#deploy-on-your-own-vercel-instance

**Comment by TanishShinde** [comment]
@anuraghazra Thanks for the update

**Comment by felipe-allmeida** [comment]
It is working now, thanks!

**Comment by anuraghazra** [comment]
@felipe-allmeida although i would still encourage you to host on your own vercel instance. :)

**Comment by felipe-allmeida** [comment]
> @felipe-allmeida although i would still encourage you to host on your own vercel instance. :)

Already did that, thanks man!
