### ISSUE TITLE
[Feature] Stats card: fetch only requested data from GitHub API

### ISSUE THREAD

**Issue by qwerty541** [anuraghazra/github-readme-stats#3311]
Currently during stats card generation we fetch from GitHub API  data which is hidden by default like count of started and answered discussions or count and percentage of merged pull requests. I think it will be better to request only required data to reduce load on PATs.

Tracking issue for https://github.com/anuraghazra/github-readme-stats/pull/3208

**Comment by Ritwikrajsingh** [comment]
I want to work on this issue!

**Comment by qwerty541** [comment]
Hey, @Ritwikrajsingh! Thanks for your interest to our project and considering contribution! We already have a pull request which will solve this issue, feel free to choose another issue that you are interested to work on.
