### ISSUE TITLE
Documentation missing list of available locales

### ISSUE THREAD

**Issue by qwerty541** [anuraghazra/github-readme-stats#3332]
Readme file should contains table with available locales.

**Comment by Harishprethiv7** [comment]
I can do it.
Kindly assign it to me.

**Comment by qwerty541** [comment]
> I can do it. Kindly assign it to me.

Hey, @Harishprethiv7! Thanks for your interest! We already have pull request which will resolve this (https://github.com/anuraghazra/github-readme-stats/pull/3331), feel free to choose another issue that you want to work on.
