### ISSUE TITLE
Star count not working.

### ISSUE THREAD

**Issue by mrsid-31** [anuraghazra/github-readme-stats#338]
Hey @anuraghazra bro,  I am facing these issues...

- Star count is not working for me- is there any solution?

- I tried show_owner=false but still showing my name.

Let me know if there is any fix for this problems.

**Comment by anuraghazra** [comment]
please provide more info & screenshots. 

What do you mean by "Star count is not working for me- is there any solution?" not working in which manner?

**Comment by anuraghazra** [comment]
You are hiding the stars in options. please read the documentation carefully.

```diff
- <img align="center" src="https://github-readme-stats.vercel.app/api?username=mrsid-31&show_icons=true&hide=stars&theme=dark&count_private=true&include_all_commits=true" alt="mrsid-31" />

+ <img align="center" src="https://github-readme-stats.vercel.app/api?username=mrsid-31&show_icons=true&theme=dark&count_private=true&include_all_commits=true" alt="mrsid-31" />

 ```

**Comment by mrsid-31** [comment]
It was not working that is why I have disabled it.
![Screenshot (94)](https://user-images.githubusercontent.com/52076969/89717581-8fad9280-d9d5-11ea-8824-f62f933c8d0b.png)

**Comment by jopemachine** [comment]
> It was not working that is why I have disabled it.

63 is the numbers of repositories you pressed star.

And total star of Github stat displays the number of stars your repository has received.

So, it is working properly.

**Comment by mrsid-31** [comment]
okay, I got it. thankyou so much @jopemachine and @anuraghazra .
