### ISSUE TITLE
Update documentation with Haktoberfest 2023 guidelines

### ISSUE THREAD

**Issue by Prof-anabi** [anuraghazra/github-readme-stats#3382]
Update the documentation with the new  guidelines for Hacktoberfest 2023.

**Comment by qwerty541** [comment]
Hey, @Prof-anabi! Thanks for opening an issue! We already have an announcement post https://github.com/anuraghazra/github-readme-stats/discussions/3317 which contains Hacktoberfest 2023 guidelines. I don't think that it worth to add this exactly inside repository readme file, especially considering that today is 17th October and half of Hacktoberfest already gone. In my opinion it's enough to have a post in repository discussions. Let's also wait for another maintainers input about it.

@rickstaa @anuraghazra
