### ISSUE TITLE
Add `card_width` argument to pin card

### ISSUE THREAD

**Issue by yaten2302** [anuraghazra/github-readme-stats#3406]
### Is your feature request related to a problem? Please describe.

Currently there is no way to set the width of the `pin card` manually,.

### Describe the solution you'd like

Adding the `card_width` argument to the pin card endpoint.

**Comment by parthasdey2304** [comment]
Would you please assign that to me!

**Comment by bikrantjajware** [comment]
Hello @yaten2302 , linked a PR to fix this issue please review

**Comment by yaten2302** [comment]
Hi @bikrantjajware, I'm not the maintainer of GRS. I just created the issue so that the maintainers could assign it to me, but it's perfectly fine if you have created the PR👍

**Comment by rickstaa** [comment]
Duplicate of #3368 will be fixed when #3359 is merged.
