### ISSUE TITLE
bug when using a wakatime card with the compact layout: display_format option is ignored

### ISSUE THREAD

**Issue by gabrieldiaspereira** [anuraghazra/github-readme-stats#3503]
### Describe the bug

using the default layout it is possible to view the values ​​in percentages:
![image](https://github.com/anuraghazra/github-readme-stats/assets/38802740/bd58c81b-4247-4b84-a936-e2456cf985ea)

but using compact layout the display_format option is ignored
![image](https://github.com/anuraghazra/github-readme-stats/assets/38802740/342b0a69-e1c9-44cd-894c-d27b1dd5ebfc)

### Expected behavior

The expected behavior would be to display the percentage because the display_format parameter is being set

### Screenshots / Live demo link

<img height="300em" src="https://github-readme-stats.vercel.app/api/wakatime?username=gabrieldiaspereira&custom_title=Percentage-Stat-Bug&display_format=percents&layout=compact"/>

**Comment by qwerty541** [comment]
Hey, @gabrieldiaspereira! Thanks for your report! This issue will be fixed after merging pull request https://github.com/anuraghazra/github-readme-stats/pull/3504.

**Comment by rickstaa** [comment]
Merged into main. Thanks @gabrieldiaspereira and @qwerty541.
