### ISSUE TITLE
The image show an error

### ISSUE THREAD

**Issue by ZhengLinLei** [anuraghazra/github-readme-stats#3513]
### Describe the bug

The image doesn't work 
<img height=200 align="center" src="https://github-readme-stats.vercel.app/api?username=ZhengLinLei&include_all_commits=true" />

I've seen the issue #1515 and it was fixed by #1691 but still not working 

### Screenshots / Live demo link

<img width="1680" alt="Screenshot 2023-11-30 at 15 24 03" src="https://github.com/anuraghazra/github-readme-stats/assets/77938581/a51fb069-3866-4296-ae63-262e691097da">

**Comment by ZhengLinLei** [comment]
It worked for me when I replace ["https://github-readme-stats.vercel.app/api?username=ZhengLinLei&include_all_commits=true"](https://github-readme-stats.vercel.app/api?username=ZhengLinLei&include_all_commits=true) to ["https://github-readme-stats.vercel.app/api?username=ZhengLinLei"](https://github-readme-stats.vercel.app/api?username=ZhengLinLei) 

<img src="https://github-readme-stats.vercel.app/api?username=ZhengLinLei">

**Comment by qwerty541** [comment]
Hey, @ZhengLinLei! Thanks for your report! We're using GitHub HTTP API to fetch total commits count, you can experience this error when it respond with error for some reason, unfortunately we can't fix it from our side. It should be resolved automatically after some time.

**Comment by ZhengLinLei** [comment]
> .

Thanks for your reply. 👍
