### ISSUE TITLE
Hey, how can I hide jupyter notebook for Top Languages Card?

### ISSUE THREAD

**Issue by davidleitw** [anuraghazra/github-readme-stats#352]
I try to hide jupyter notebook for top languages card?
How should i do?
I try 

[![Top Langs](https://github-readme-stats.vercel.app/api/top-langs/?username=davidleitw&hide=Jupyter Notebook)](https://github.com/anuraghazra/github-readme-stats)

and 

[![Top Langs](https://github-readme-stats.vercel.app/api/top-langs/?username=davidleitw&hide=JupyterNotebook)](https://github.com/anuraghazra/github-readme-stats)

it doesn't work .
Thanks for your help.

**Comment by anuraghazra** [comment]
jupyter%20notebook

please read the docs https://github.com/anuraghazra/github-readme-stats/#language-card-exclusive-options

**Comment by anuraghazra** [comment]
Duplicate of #201 #320

**Comment by davidleitw** [comment]
Thx, thank for your help!

**Comment by ichisadashioko** [comment]
We need to add some documentation about the `ID` of the languages.

**Comment by sajid-munawar** [comment]
Thanks.

**Comment by sasha1107** [comment]
Thanks a lot!

**Comment by QI-XIANG** [comment]
Thanks for help.
