### ISSUE TITLE
Missing "OSCDIMAGE.EXE" while click on (Select Windows ISO) at MicroWin in Chris Titus Tech's Windows Utility

### ISSUE THREAD

**Issue by cat139lyleb** [anuraghazra/github-readme-stats#3529]
I already been looking in Google, DuckDuckGo on that "OSCDIMAGE.EXE" nothing much info on that so, please help! Thank you!

**Comment by rickstaa** [comment]
@cat139lyleb I think you are posting this in the wrong repository. Please open an issue [here](https://github.com/ChrisTitusTech/winutil).
