### ISSUE TITLE
[align the repo cards]: When adding [align: "left"] attribute, will add a 20px padding.

### ISSUE THREAD

**Issue by isArtJay** [anuraghazra/github-readme-stats#359]
**Describe the bug**
When adding [align: "left"] or [align: "right"] attribute, there will be a 20px padding.

**Expected behavior**
When adding [align: "left"] or [align: "right"] attribute, there will be a 20px padding. Cause the two cards cannot be in the same row.

**Screenshots / Live demo link (paste the github-readme-stats link as markdown image)**
- add [align: "left"]
![image](https://user-images.githubusercontent.com/48620527/89849403-0788e200-dbbb-11ea-8a28-d0b0dbfa50c1.png)

- don't add [align: "left"]
![image](https://user-images.githubusercontent.com/48620527/89849583-64849800-dbbb-11ea-9b77-5db49592d474.png)

- others
![2](https://user-images.githubusercontent.com/48620527/89850172-90ece400-dbbc-11ea-9ec2-f4c672038d66.gif)

**Comment by anuraghazra** [comment]
Please search on internet for markdown layouts or find someone who did something similar. This is not related to GitHub readme stats. 

Or checkout the https://github.com/anuraghazra/github-readme-stats#quick-tip-align-the-repo-cards

**Comment by WaqarTabish2807** [comment]
how to align the complete box at the center?

**Comment by rickstaa** [comment]
@WaqarTabish2807 I use `<div align="center"></div>`. You can checkout https://github.com/rickstaa/rickstaa/ for an example.

**Comment by praveenrider784** [comment]
> how to align the complete box at the center?

<p align="center">
  <img width="600" height="200" src="https://www.python.org/python-.png">
</p>

**Comment by praveenrider784** [comment]
> how to align the complete box at the center?
<p align="center">
  <img width="600" height="200" src="https://www.python.org/python-.png">
</p>
