### ISSUE TITLE
Name Kian-Merchant returning null

### ISSUE THREAD

**Issue by Kian-Merchant** [anuraghazra/github-readme-stats#36]
When trying to use:
```
![Kian's github stats](https://github-readme-stats.vercel.app/api?username=kian-merchant&show_icons=true&hide_border=true)
```

it returns this:
![Kian's github stats](https://github-readme-stats.vercel.app/api?username=kian-merchant&show_icons=true&hide_border=true)

____

am I doing something wrong? I think it might be my "-" in my name

**Comment by anuraghazra** [comment]
Hi @Kian-Merchant thanks for opening the issues seems like you don't have a name set in your github profile. 

Related to #18

**Comment by Kian-Merchant** [comment]
Thanks for the reply, that works!
