### ISSUE TITLE
Adding space to the Most Used Language card?

### ISSUE THREAD

**Issue by KarthikNayak024** [anuraghazra/github-readme-stats#360]
When the layout is compact in the **Most Used Languages** Card, space between language and usage percentage is too less, either you may try the space, or change the color of the usage percentage, or make the languages as bold.

[My Readme](https://github.com/KarthikNayak024)

**Comment by KarthikNayak024** [comment]
If you are going to add this feature I would like to help in adding this feature.

**Comment by anuraghazra** [comment]
We can just decrease the opacity of the percentage text.

**Comment by KarthikNayak024** [comment]
Okay I'll try to do that

**Comment by KarthikNayak024** [comment]
In the Contribution.md you have mentioned about creating a .env file in the root directory and PAT (Personal Access Token) to it. 
I did not understand how to do that. I mean should I add just a token to the .env file or is there any kind of syntax for that. I am using **vercel** for the first time. Can you guide me through it?

**Comment by KarthikNayak024** [comment]
[Issue](https://drive.google.com/file/d/1VMsTHzXed_Xx-cZ3gD1rLjnWgEBmEDVp/view?usp=drivesdk)
How to fix this issue?

**Comment by KarthikNayak024** [comment]
Shall I add a hyphen between the language and the percentage?
