### ISSUE TITLE
Private PRs counter

### ISSUE THREAD

**Issue by kalebers** [anuraghazra/github-readme-stats#3629]
### Is your feature request related to a problem? Please describe.

I have some private PR's that I wanted the include in the total counts, but as far as I know there's no function for that yet.

### Describe the solution you'd like

Would be interesting to see a function as "count_private_prs=true", being possible to set true or false as default.

**Comment by DylanBT928** [comment]
Private PR's can actually be shown by deploying your own instance.

> To show private statistics on the stats card, you should [deploy your own instance](https://github.com/anuraghazra/github-readme-stats#deploy-on-your-own) using your own GitHub API token.

You can check out [this video](https://www.youtube.com/watch?v=n6d4KHSKqGk&t=107s) for a quick tutorial on how to do so. By doing so, you may not even have to worry about hitting the GitHub API's rate limit. 

> Since the GitHub API only allows 5k requests per hour, my https://github-readme-stats.vercel.app/api could possibly hit the rate limiter. If you host it on your own Vercel server, then you do not have to worry about anything. Click on the deploy button to get started!

**Comment by kalebers** [comment]
Thank you for your answer, will help a lot!

**Comment by qwerty541** [comment]
Thanks for answering @DylanBT928! Closing this issue as resolved.
