### ISSUE TITLE
allow show include_all_commits and total current year at same time

### ISSUE THREAD

**Issue by bluelovers** [anuraghazra/github-readme-stats#365]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by anuraghazra** [comment]
Please explain what you are requesting for in detail.

**Comment by bluelovers** [comment]
![image](https://user-images.githubusercontent.com/167966/89931631-06999400-dc3f-11ea-8445-8808251c2c61.png)

1 + 2 at same time

**Comment by Math-O5** [comment]
@anuraghazra I'm searching project externals to contributs. Is it open yet, right?

**Comment by Math-O5** [comment]
@anuraghazra I didn't found, so I did it. How I should do proper do the pull request liking this post?
