### ISSUE TITLE
Card_Width hides the language Percentage

### ISSUE THREAD

**Issue by Karthik-Nayak98** [anuraghazra/github-readme-stats#368]
**Describe the bug**
When I reduce the size of the **Most used languages** card It hides the languages and usage percentage.

**Expected behavior**
It should push the language and usage percentage to the left.

**Screenshots / Live demo link (paste the github-readme-stats link as markdown image)**
[My readme](https://drive.google.com/file/d/1YkCHpWj77RYDudQOncZP6-optn6ExBy1/view)

**Additional context**
There should be a minimum width set to the card below that it shouldn't resize.

**Comment by anuraghazra** [comment]
Thanks for reporting the issue, I'll look into this.

**Comment by tusharnankani** [comment]
Hi! @anuraghazra @KarthikNayak024 

Adding `overflow-wrap: break-word;` or `overflow-wrap: anywhere;` here should fix the issue.

Thank you,
Tushar Nankani

**Comment by anuraghazra** [comment]
> Hi! @anuraghazra @KarthikNayak024
> 
> Adding `overflow-wrap: break-word;` or `overflow-wrap: anywhere;` here should fix the issue.
> 
> Thank you,
> Tushar Nankani

Not that easy i'm afraid. it's svg not native html.

**Comment by tusharnankani** [comment]
> Not that easy i'm afraid. it's svg not native html.

My bad! @anuraghazra 
I will look into it.

**Comment by tusharnankani** [comment]
Hi! @anuraghazra 

> I will look into it.

https://github.com/anuraghazra/github-readme-stats/blob/67b434dc79b0f024b5d432c5f3317042a963558e/src/cards/top-languages-card.js#L107

This piece of code can be replaced by:
`  let width = isNaN(card_width) ? 300 : Math.max(card_width, 200);`

> Additional context
There should be a minimum width set to the card below that it shouldn't resize.

This piece of code, can address this issue^

> Expected behavior
It should push the language and usage percentage to the left.

To address this, we will have to look at some factors:
- string length of languages (i.e. JavaScript, Python)
- then for `&layout=default`, we don't have to worry much, In the above code, we just have to replace 200 with `Math.max(card_width, <max_string_length>)` with some added padding.
- for `&layout=compact`, we can do the same thing, but it gets too complex;
    - So we can two _lexographically_ longest languages: like ("Jupyter Notebook", "JavaScript"), sum of these lengths + added padding, and replace `200` by that, thereby we can take care of all the possible cases, by taking the worst case!


Please let me know, if this would work!

Thank you! ^_^
Tushar Nankani

**Comment by tusharnankani** [comment]
Hi @anuraghazra!
Let me know if this works, I would be more than happy to make a PR! ^_^

**Comment by rickstaa** [comment]
#### Normal layout

[![Top Langs](https://github-readme-stats.vercel.app/api/top-langs/?username=anuraghazra&card_width=100)](https://github.com/anuraghazra/github-readme-stats)

```md
[![Top Langs](https://github-readme-stats.vercel.app/api/top-langs/?username=anuraghazra&card_width=100)](https://github.com/anuraghazra/github-readme-stats)
````

[![Top Langs](https://github-readme-stats.vercel.app/api/top-langs/?username=anuraghazra&card_width=200)](https://github.com/anuraghazra/github-readme-stats)

```md
[![Top Langs](https://github-readme-stats.vercel.app/api/top-langs/?username=anuraghazra&card_width=200)](https://github.com/anuraghazra/github-readme-stats)
````

[![Top Langs](https://github-readme-stats.vercel.app/api/top-langs/?username=anuraghazra&card_width=300)](https://github.com/anuraghazra/github-readme-stats)

```md
[![Top Langs](https://github-readme-stats.vercel.app/api/top-langs/?username=anuraghazra&card_width=300)](https://github.com/anuraghazra/github-readme-stats)
````

[![Top Langs](https://github-readme-stats.vercel.app/api/top-langs/?username=anuraghazra&card_width=400)](https://github.com/anuraghazra/github-readme-stats)

```md
[![Top Langs](https://github-readme-stats.vercel.app/api/top-langs/?username=anuraghazra&card_width=400)](https://github.com/anuraghazra/github-readme-stats)
````

[![Top Langs](https://github-readme-stats.vercel.app/api/top-langs/?username=anuraghazra&card_width=500)](https://github.com/anuraghazra/github-readme-stats)

```md
[![Top Langs](https://github-readme-stats.vercel.app/api/top-langs/?username=anuraghazra&card_width=500)](https://github.com/anuraghazra/github-readme-stats)
````

#### Compact layout

[![Top Langs](https://github-readme-stats.vercel.app/api/top-langs/?username=anuraghazra&card_width=100&layout=compact)](https://github.com/anuraghazra/github-readme-stats)

```md
[![Top Langs](https://github-readme-stats.vercel.app/api/top-langs/?username=anuraghazra&card_width=100&layout=compact)](https://github.com/anuraghazra/github-readme-stats)
````

[![Top Langs](https://github-readme-stats.vercel.app/api/top-langs/?username=anuraghazra&card_width=200&layout=compact)](https://github.com/anuraghazra/github-readme-stats)

```md
[![Top Langs](https://github-readme-stats.vercel.app/api/top-langs/?username=anuraghazra&card_width=200&layout=compact)](https://github.com/anuraghazra/github-readme-stats)
````

[![Top Langs](https://github-readme-stats.vercel.app/api/top-langs/?username=anuraghazra&card_width=300&layout=compact)](https://github.com/anuraghazra/github-readme-stats)

```md
[![Top Langs](https://github-readme-stats.vercel.app/api/top-langs/?username=anuraghazra&card_width=300&layout=compact)](https://github.com/anuraghazra/github-readme-stats)
````

[![Top Langs](https://github-readme-stats.vercel.app/api/top-langs/?username=anuraghazra&card_width=400&layout=compact)](https://github.com/anuraghazra/github-readme-stats)

```md
[![Top Langs](https://github-readme-stats.vercel.app/api/top-langs/?username=anuraghazra&card_width=400&layout=compact)](https://github.com/anuraghazra/github-readme-stats)
````

[![Top Langs](https://github-readme-stats.vercel.app/api/top-langs/?username=anuraghazra&card_width=500&layout=compact)](https://github.com/anuraghazra/github-readme-stats)

```md
[![Top Langs](https://github-readme-stats.vercel.app/api/top-langs/?username=anuraghazra&card_width=500&layout=compact)](https://github.com/anuraghazra/github-readme-stats)
````
