### ISSUE TITLE
Add query parameter for last year of languages shown in languages card 

### ISSUE THREAD

**Issue by kibotu** [anuraghazra/github-readme-stats#371]
**Is your feature request related to a problem? Please describe.**
Currently it shows that I have 55% c# language, even though I barely coded c# in last 2 years. 

**Describe the solution you'd like**
Show only main languages from last year. 

**Describe alternatives you've considered**
Hiding doesn't make it show my last year most used languages (mainly kotlin)

**Comment by bartolomej** [comment]
I will handle this issue! Although the only way I can implement this is by excluding repositories (into language stats count) that received no contributions (from the user) after the specified date.
