### ISSUE TITLE
The submission of private warehouses cannot be calculated

### ISSUE THREAD

**Issue by EternityJune25** [anuraghazra/github-readme-stats#3713]
Added parameters as required in the document, but it doesn't seem to work (private warehouse submission is not counted)

**Comment by qwerty541** [comment]
Answered your question there https://github.com/anuraghazra/github-readme-stats/discussions/3712#discussioncomment-8966617

**Comment by EternityJune25** [comment]
> Answered your question there [#3712 (comment)](https://github.com/anuraghazra/github-readme-stats/discussions/3712#discussioncomment-8966617)

Thank you. Problem solved.
