### ISSUE TITLE
Private Repository

### ISSUE THREAD

**Issue by FredGSF** [anuraghazra/github-readme-stats#3726]
### Is your feature request related to a problem? Please describe.

I have a private Repository with lets 100 commits if i make it public would it count for the stats or only new ones after its public will count ?

**Comment by Zo-Bro-23** [comment]
It should count the stats once made public.

**Comment by qwerty541** [comment]
Hey, @FredGSF. You also can [deploy you own Vercel instance](https://github.com/anuraghazra/github-readme-stats?tab=readme-ov-file#on-vercel) using your own GItHub API key in order to keep your repository private and include it's stats on the card.

**Comment by omarahmedx14** [comment]
> Hey, @FredGSF. You also can [deploy you own Vercel instance](https://github.com/anuraghazra/github-readme-stats?tab=readme-ov-file#on-vercel) using your own GItHub API key in order to keep your repository private and include it's stats on the card.

but it will show the repos stats that you OWN only.

**Comment by qwerty541** [comment]
You're right, it will show the stats only anout owned repositories. If you want to include the data from organizations repositories, then you can deploy the following branch on your own Vercel instance https://github.com/anuraghazra/github-readme-stats/pull/2459. May be it will be merged in master branch soon after a small rework. Anyway this feature will be available only on users own instances to reduce the load on public instance and less downtimes.
