### ISSUE TITLE
Inaccurate streak count

### ISSUE THREAD

**Issue by Mohsin370** [anuraghazra/github-readme-stats#3729]
### Describe the bug

**Describe the bug**
The stats card does not display correct streak stats or it is consistent.  I added this streak card to my profile weeks ago and I almost check my streak stat every day. Given the number of commits that I have made each day, the card stats will show incorrect numbers, sometimes higher than expected or sometimes lower than expected.
I checked in the morning it was showing 10 stars, in the evening it was 11 but it should have been 8.
Also, 8 is my longest streak which is also my current streak but it is showing 14 and that should be incorrect. it also change time to time.

**To Reproduce**
Steps to reproduce the behaviour:

1. Add a stats card to your profile
2. Start committing and check results multiple times in a day.
3. The count will be incorrect (but near to right number of streaks)

**Screenshots**
Current stats:
![image](https://github.com/DenverCoder1/github-readme-streak-stats/assets/62910365/c82417f7-3f9d-4d48-93f4-ed7be6671858)

Commits chart:
![image](https://github.com/DenverCoder1/github-readme-streak-stats/assets/62910365/572dab9d-c1e1-4a1c-9812-380e4fcd788f)

Since there were no commits on the 8th, my streak should have started on the 9th of April.

### Expected behavior

The streak count should be accurate based on the commits made on consecutive days.

**Comment by Steven-Jarmell** [comment]
![image](https://github.com/anuraghazra/github-readme-stats/assets/76745546/00b1aaf6-f78f-482e-ac53-3c6eddf14307)

Looking at your profile you have an 11 day streak? Further showed that you have a commit on the day you claim not to have one.

**Comment by Mohsin370** [comment]
Strange and Interesting.

If I look at my profile I can't see any commit made on that day (8th April). 

![image](https://github.com/anuraghazra/github-readme-stats/assets/62910365/5de79b86-c00b-4f15-b7e6-abe3753c2db4)

Since you can see that my profile repo was created on the 8th, I checked the repo created date and it's mentioned as the 9th of April. See below:

![image](https://github.com/anuraghazra/github-readme-stats/assets/62910365/a2b5a855-214e-44cc-9695-c4ff66745ef3)

So I was wondering if this could be due to the timezone difference at which the commit was made. (Possibly)

So I reached out to this GitHub API, which shows the created_at field for the repository with time.
API Link: https://api.github.com/repos/Mohsin370/Mohsin370
Mohsin370 Repo created_at:

![image](https://github.com/anuraghazra/github-readme-stats/assets/62910365/8797b27f-474a-4e9c-850a-98c93f723e55)


Given the response, the repository must have been created on 9th April but due to the timezone difference, the card is not displaying the accurate result.

**Comment by Mohsin370** [comment]
The streak count changed again. Based on my commit history this looks right but just like before it will be back to the old state. so I think it's inconsistent.

![image](https://github.com/anuraghazra/github-readme-stats/assets/62910365/884e1349-aa05-4161-955f-31a5befbca12)

**Comment by qwerty541** [comment]
Hey, @Mohsin370. This repository does not provide streak stats card. Looks like you mixed up this repository with https://github.com/DenverCoder1/github-readme-streak-stats, all corresponding questions and issue discussions should be there.

Most likely the source of your problem is a difference between your local timezone and streak stats server timezone. This is [link](https://github.com/DenverCoder1/github-readme-streak-stats/issues/288#issuecomment-1200029137) on answer of streak stats creator about similar problem which I found, hope this helps.

**Comment by ashiqYousuf** [comment]
Same issue here
![image](https://github.com/anuraghazra/github-readme-stats/assets/91784076/d43d9981-4210-424f-b304-b7d06e22108f)
![image](https://github.com/anuraghazra/github-readme-stats/assets/91784076/f0767723-6f93-4364-ac82-034ee6ab8d86)

**Comment by qwerty541** [comment]
@ashiqYousuf Answered your question here https://github.com/anuraghazra/github-readme-stats/issues/1871#issuecomment-2144003802
