### ISSUE TITLE
Why the stars of repo from my organization are not counted?

### ISSUE THREAD

**Issue by Kyfafyd** [anuraghazra/github-readme-stats#373]
Thanks for this amazing tool!!! 

Here I contributed to other repos of a github organization (with several stars of this repo). But the total stars seems don't include these stars. I wonder if this is a bug or this tool can not support this now?

Looking forward to your feedback!

**Comment by filiptronicek** [comment]
Thanks @Kyfafyd for the issue!
This is a limitation of the GraphQL API. We can only count the stars attributed directly to **You** and you specifically, so only the repos, which you are the owner of can be counted. No organizations. Maybe @anuraghazra will have something more to say, but that's where I stand at least.

**Comment by Kyfafyd** [comment]
@filiptronicek Thanks a lot for your response!
But I still wonder if these stars can be counted? @ahmadawais

**Comment by filiptronicek** [comment]
I think you would have to then only count the stars of every repo you ever contributed to... @Kyfafyd

**Comment by ahmadawais** [comment]
> @filiptronicek Thanks a lot for your response!
> But I still wonder if these stars can be counted? @ahmadawais 

Why do people keep tagging me in this project. It's not mine. 🤦‍♂️

**Comment by anuraghazra** [comment]
@Kyfafyd Please please don't tag anyone who is not currently discussing the matter. They do get a DING! notification. (or did you accidentally mentioned ahmed?)

**Comment by Kyfafyd** [comment]
@anuraghazra I am so sorry for this accident.
So can you give a reply for my question?

**Comment by anuraghazra** [comment]
> So can you give a reply for my question?

Probably can be. but we currently don't count them. since Stars should only be counted which users actually achieved, not from any org.

**Comment by Kyfafyd** [comment]
@anuraghazra If this will be a future work?

**Comment by filiptronicek** [comment]
I don't think this would be a wise idea. Orgs are here for people to join in the fun of creating something together, so I don't see a reason to add this. Orgs should be separated from our own work IMO. If you have any thoughts pro-adding org stars, @Kyfafyd, I'll be happy to hear them!

**Comment by anuraghazra** [comment]
> I don't think this would be a wise idea. Orgs are here for people to join in the fun of creating something together, so I don't see a reason to add this. Orgs should be separated from our own work IMO. If you have any thoughts pro-adding org stars, @Kyfafyd, I'll be happy to hear them!

I agree.

**Comment by KnowsCount** [comment]
ahhh, just a quick thought—maybe list another line like `Total Stars (containing organisation repos): xxx`.

**Comment by VidarDev** [comment]
> I don't think this would be a wise idea. Orgs are here for people to join in the fun of creating something together, so I don't see a reason to add this. Orgs should be separated from our own work IMO. If you have any thoughts pro-adding org stars, @Kyfafyd, I'll be happy to hear them!

For example, I have all my projects, even the ones I work on alone, in my organization. I don't think I'm the only one.

**Comment by rickstaa** [comment]
> > I don't think this would be a wise idea. Orgs are here for people to join in the fun of creating something together, so I don't see a reason to add this. Orgs should be separated from our own work IMO. If you have any thoughts pro-adding org stars, @Kyfafyd, I'll be happy to hear them!
> 
> For example, I have all my projects, even the ones I work on alone, in my organization. I don't think I'm the only one.

@VidarDev This issue was closed a long time ago. It, however, is an often requested feature. You can add your support for it by adding a like to https://github.com/anuraghazra/github-readme-stats/issues/1.
