### ISSUE TITLE
Align

### ISSUE THREAD

**Issue by iibrahemali** [anuraghazra/github-readme-stats#3740]
### Describe the bug

Cannot Align Stats w Langs

### Expected behavior

It should be more flexible

**Comment by qwerty541** [comment]
You can find an example of aligning the stats card with top languages card in our documentation: https://github.com/anuraghazra/github-readme-stats?tab=readme-ov-file#quick-tip-align-the-cards

Another example can be found in my GItHub profile.

Looks like you're doing something wrong.

**Comment by iibrahemali** [comment]
> You can find an example of aligning the stats card with top languages card in our documentation: https://github.com/anuraghazra/github-readme-stats?tab=readme-ov-file#quick-tip-align-the-cards
> 
> Another example can be found in my GItHub profile.
> 
> Looks like you're doing something wrong.

Actually, weeks ago when I put it on my readme, it was giving me that bug, so I followed ur exact way of code from ur profile to fix it, it gave me the same bug. I think the reason behind it was, I used to have only a few languages back in this time, so maybe that's why. Later, I solved it by separating em in a good design as possible.

**Comment by iibrahemali** [comment]
Fixed.
