### ISSUE TITLE
Width BUG

### ISSUE THREAD

**Issue by iibrahemali** [anuraghazra/github-readme-stats#3741]
### Describe the bug

I cannot edit the width of them

### Expected behavior

I wanna make em all same width

**Comment by vishal100coder** [comment]
Could you please elaborate the issue and attach some kind of screenshot if posible?

**Comment by qwerty541** [comment]
Actually you can edit the width by using `width` attribute of `img` html tag. Here is an example:

```html
<img width="500" src="https://github-readme-stats.vercel.app/api?username=anuraghazra" />
```

<img width="500" src="https://github-readme-stats.vercel.app/api?username=anuraghazra" />

**Comment by iibrahemali** [comment]
> Actually you can edit the width by using `width` attribute of `img` html tag. Here is an example:
> 
> ```html
> <img width="500" src="https://github-readme-stats.vercel.app/api?username=anuraghazra" />
> ```
> 
> <img width="500" src="https://github-readme-stats.vercel.app/api?username=anuraghazra" />

Yea that's basically what I did. However, it's working with that, if I put the width as 300 it's gonna be the same thing as 600 width, uk what im saying?

**Comment by iibrahemali** [comment]
I solved it, u can check PR w it.
