### ISSUE TITLE
[Feature Request] Include language stats from specified organization repos

### ISSUE THREAD

**Issue by QuantumlyTangled** [anuraghazra/github-readme-stats#375]
I sort most of my repos into organizations and also contribute there. So it would be beneficial to allow the language card insights to those as well. I presume there are many more people who sort repos like this.

**Comment by Certseeds** [comment]
maybe you can fork it back to statistics it？

**Comment by QuantumlyTangled** [comment]
Closing this since I have already implemented it on my fork.
