### ISSUE TITLE
The deployment has been disabled on vercel.app

### ISSUE THREAD

**Issue by mahmoud-eskandari** [anuraghazra/github-readme-stats#378]
Hi
Why are the samples disabled?

‍‍‍‍‍‍
```
451: DEPLOYMENT_DISABLED
Code: DEPLOYMENT_DISABLED
```

451 error occurred on vercel.app

[![Top Langs](https://github-readme-stats.vercel.app/api/top-langs/?username=anuraghazra)](https://github.com/anuraghazra/github-readme-stats)

**Comment by LumitoLuma** [comment]
I also have this problem with my stats.

**Comment by LumitoLuma** [comment]
@mahmoud-eskandari Please see #325 for a temporal solution.

**Comment by filiptronicek** [comment]
This is weird though, last non-documentation commit was four days ago. Wondering what could break...

**Comment by anuraghazra** [comment]
closing in favour of #325

**Comment by vali-ceel** [comment]
Why website acereus not work

**Comment by Beem00** [comment]
.

**Comment by LikeioooXD** [comment]
.
