### ISSUE TITLE
Github Langs Stats for a single repo is erroneous imo..

### ISSUE THREAD

**Issue by Soumilgit** [anuraghazra/github-readme-stats#3792]
### Describe the bug

Lots of Javascript files in my repo https://github.com/Soumilgit/YourStory-Digital-Innovation-Hackathon-HackerEarth but the total proportion of Javascript in the languages card of the repo itself is showing Javascript proportion as 11.7 % only,even on visually checking the files,it seems to be higher(inside  Backend->node_modules + Frontend).Please help!

### Expected behavior

It should show Javascript language proportion much higher,at the top,with atleast 33% share.

### Screenshots / Live demo link

![kkkk](https://github.com/anuraghazra/github-readme-stats/assets/120581772/0c98d9c6-b3f4-453e-9eb4-1328c68fa88d)

**Comment by qwerty541** [comment]
Answered your question there https://github.com/anuraghazra/github-readme-stats/issues/275#issuecomment-2150765478
