### ISSUE TITLE
Total commits count is wrong

### ISSUE THREAD

**Issue by dingyuqi** [anuraghazra/github-readme-stats#3842]
### Describe the bug

I deployed the repo on vercel but the count of my total commits seems wrong. It doesn't match the contribution. Here is my url:
```
<div align='left'>
    <picture>
        <source media="(prefers-color-scheme: dark)" srcset="https://github-readme-stats-black-zeta-98.vercel.app/api?username=dingyuqi&show_icons=true&count_private=true&include_all_commits=true&custom_title=Dingyuqi's%20Stats&hide_border=true&theme=github_dark">
        <img src='https://github-readme-stats-black-zeta-98.vercel.app/api?username=dingyuqi&show_icons=true&count_private=true&include_all_commits=true&custom_title=Dingyuqi's%20Stats&hide_border=true' alt='Dingyuqi's%20Stats'>
    </picture>
    <picture>
        <source media="(prefers-color-scheme: dark)" srcset="https://github-readme-stats-black-zeta-98.vercel.app/api/top-langs/?username=dingyuqi&custom_title=Top%20Language&langs_count=4&hide=c%2B%2B&hide_border=true&layout=compact&theme=github_dark">
        <img src='https://github-readme-stats-black-zeta-98.vercel.app/api/top-langs/?username=dingyuqi&custom_title=Top%20Language&langs_count=4&hide=c%2B%2B&hide_border=true&layout=compact' alt='Top%20Language'>
    </picture>
</div>
```

### Expected behavior

I expect that the count of my total commits is the same as the contribution count below:
![image](https://github.com/anuraghazra/github-readme-stats/assets/55981710/62719b30-b35a-4ff0-be7d-bb403eee4bc2)

there is 195 commits in 2024. Actually, I use `&count_private=true&include_all_commits` in url, so it should be a larger number than  195.

### Screenshots / Live demo link

![image](https://github.com/anuraghazra/github-readme-stats/assets/55981710/40bde08b-875e-4217-8eb3-47792ad914bc)

**Comment by dingyuqi** [comment]
> But not all contributions are commits. Some are opening issues and pull requests.但并非所有贡献都是提交。有些是打开问题和拉取请求。 Also, joining GitHub is one, though that wasn't this year for you.此外，加入 GitHub 也是其中之一，尽管今年不适合您。

I know that not all contributions are commits, but in July 2024 I had 61 commits. I don't know why the commit count is much less than 61. 
![image](https://github.com/user-attachments/assets/4cee233a-d1e9-436f-9ee3-8576723a5cb4)

**Comment by fsantamaria1** [comment]
Did you enable the `repo` and `user` permissions when you created your PAT?

**Comment by dingyuqi** [comment]
> Did you enable the `repo` and `user` permissions when you created your PAT?

yes, you are right!!! I forgot to enable `repo` and `user` permissions. I updated the PAT and the commit count turned to be 84.  Thanks a lot!
