### ISSUE TITLE
Star Count Issue?

### ISSUE THREAD

**Issue by kingthorin** [anuraghazra/github-readme-stats#39]
Maybe I'm not understanding what "Total Stars" is supposed to represent but shouldn't these values match?

![image](https://user-images.githubusercontent.com/7570458/87303080-887f8b80-c4e0-11ea-8620-cca476fcd96d.png)

**Comment by anuraghazra** [comment]
Those are two different values.

In the first image those are the repos that i starred, and on the second image it count how many stars i gained.

**Comment by kingthorin** [comment]
Do you mean across a dev's repos? Or is there a way to actually give a github user stars? (That might be a newb question, but I honestly don't see user/account stars functionality anywhere, but could be overlooking it.)

Either way something still seems off. For example for myself it shows 1.4k stars, however, I have like one actual repo with one star and one fork with one star (dunno who would star a fork).

**Comment by anuraghazra** [comment]
Okay i think it's also fetching the forked repo's stars, will fix it.

**Comment by kingthorin** [comment]
I'll keep poking around and see if I can figure out what's going on.

**Comment by anuraghazra** [comment]
Ahh i see got it. i think it's also fetching the repos you contributed to and counting those stars too.

**Comment by anuraghazra** [comment]
The updated gql query should be like this to filter only the OWNER repos and also filtering forked repos

```gql
repositories(first: 100, ownerAffiliations: OWNER, isFork: false, orderBy: {direction: DESC, field: STARGAZERS}) {
      totalCount
      nodes {
        nameWithOwner
        url
        stargazers {
          totalCount
        }
      }
    }
```

**Comment by kingthorin** [comment]
That seems logical.

**Comment by anuraghazra** [comment]
Well yes, after testing it out with the new query, you have total of 1 star @kingthorin

**Comment by kingthorin** [comment]
Thanks that makes sense. Sad stat but that's not on you :wink:

**Comment by anuraghazra** [comment]
although you still got S+ rank :smile:

**Comment by kingthorin** [comment]
Well I'm a heavy contributor and just started the single star public repo in the last few months. So it probably makes sense.... I'm also not really a stats junky, I just came across this with the news of profile READMEs 👍 Where do you see the S+ rank you mentioned?

**Comment by anuraghazra** [comment]
Its a new feature, just deployed few mins ago.

**Comment by kingthorin** [comment]
So I don't mean to be a pest or anything but do you plan to deploy the fix for this soon'ish? 😀

**Comment by anuraghazra** [comment]
Yup don't worry I'll fix it but firstly I need to fix 2 things. 

#51 (high priority) 
#49 (medium priority) 

Then this one otherwise it'll make the rating system more biased

**Comment by kingthorin** [comment]
Thanks for tackling this!

**Comment by elliottzheng** [comment]
I think that's not right, I am the creator and the main contributor to an organization with more than 8k stars, but I have just 51 stars, it makes me feel terrible. Besides, the API didn't count the archived repo, e.g. [elliottzheng/copytranslator](https://github.com/elliottzheng/copytranslator)
[![ReadMe Card](https://github-readme-stats.vercel.app/api/pin/?username=copytranslator&repo=copytranslator)](https://github.com/copytranslator/copytranslator)

![Elliott Zheng's GitHub stats](https://github-readme-stats.vercel.app/api?username=elliottzheng&show_icons=true)


[![ReadMe Card](https://github-readme-stats.vercel.app/api/pin/?username=elliottzheng&repo=copytranslator)](https://github.com/elliottzheng/copytranslator)

**Comment by anuraghazra** [comment]
@elliottzheng Forked and organization stars are not counted as personal star counts. it'll only show stars from repos which you directly own. 

related to #1

**Comment by sayantani11** [comment]
I am still facing the issue. Although I have 8 starred repo, it shows 2

**Comment by anuraghazra** [comment]
> I am still facing the issue. Although I have 8 starred repo, it shows 2

https://github.com/anuraghazra/github-readme-stats/issues/39#issuecomment-657538988

As i said in this comment that what github-readme-stats shows is "how many stars you've gained in your repos" and what github shows in "how many repos you've stars" they are not the same.

**Comment by yashu1wwww** [comment]
Github Tools:
https://yashawanthtechprojects.on.drv.tw/GitHub/uploaddatefinder.html
