### ISSUE TITLE
Maximum retries exceeded

### ISSUE THREAD

**Issue by IvanHornung** [anuraghazra/github-readme-stats#390]
![image](https://user-images.githubusercontent.com/51543158/90288789-6eaecc80-de2f-11ea-8623-f7f91a8a8d23.png)

![image](https://user-images.githubusercontent.com/51543158/90288802-7a01f800-de2f-11ea-90ef-325cbfe97280.png)

How can I fix this?

**Comment by LastRoze** [comment]
Deploy your own go [here](https://github.com/anuraghazra/github-readme-stats#deploy-on-your-own-vercel-instance)

**Comment by IvanHornung** [comment]
> Deploy your own go [here](https://github.com/anuraghazra/github-readme-stats#deploy-on-your-own-vercel-instance)

Thank you!

**Comment by anuraghazra** [comment]
Make sure you have a ENV var named PAT_1 with your Github token in  vercel. 

See the docs. 
I hope you get it resolved. closing it now, feel free to ask any questions if you haven't solved it. :)
