### ISSUE TITLE
Repo Cards are not working

### ISSUE THREAD

**Issue by driftywinds** [anuraghazra/github-readme-stats#3921]
### Describe the bug

https://github-readme-stats.vercel.app/api/pin?username=anuraghazra\&repo=github-readme-stats\&title_color=fff\&icon_color=f9f9f9\&text_color=9f9f9f\&bg_color=151515

Repo Cards do not work. Going to this URL in the browser says "Something went wrong"

![image](https://github.com/user-attachments/assets/fa04c9ca-97bc-49e1-a3a6-ecc12b903c0e)

### Expected behavior

The Repo Card should work as normal

### Screenshots / Live demo link

![image](https://github.com/user-attachments/assets/fa04c9ca-97bc-49e1-a3a6-ecc12b903c0e)

### Additional context

Doesn't seem to work on my self-hosted Vercel setup either, indicating it might be a Vercel issue or a code issue: - 

https://stats.drifty.win/api/pin?username=driftywinds\&repo=ytm-builds\&title_color=fff\&icon_color=f9f9f9\&text_color=9f9f9f\&bg_color=151515

**Comment by d3v7** [comment]
Hi,
Kindly remove `\`  or `%5C` from the URL and try again
The URL you provided is
![image](https://github.com/user-attachments/assets/db5f5b32-3e99-43f6-bb69-5308acb032c1)
After removing `\` or  `%5C`  from the username and repo name it works fine 
![image](https://github.com/user-attachments/assets/bc20ddaa-4eca-4eb6-bf36-f13f443d1d48)
![image](https://github.com/user-attachments/assets/ec1c6059-0f46-47ac-88d4-7c4d9300c999)

From your self-hosted 
![image](https://github.com/user-attachments/assets/dc6e64d5-f8f2-4895-9209-34dcf2fdc254)
![image](https://github.com/user-attachments/assets/a6ee6a5f-14e0-4714-b81f-2d5b5b1b5a56)

**Comment by driftywinds** [comment]
Yes thank you, that solved it!!
