### ISSUE TITLE
"Something went wrong! file an issue" instead of repo card

### ISSUE THREAD

**Issue by Depact** [anuraghazra/github-readme-stats#3925]
### Describe the bug

Cards for those repos return errors

*  <sup>**[[F-Droid](https://f-droid.org/app/com.apps.adrcotfas.goodtime)]**</sup><br>
[![Readme Card](https://github-readme-stats.vercel.app/api/pin/?username=goodtime-productivity\&repo=Goodtime&cache_seconds=86400&theme=shadow_blue)](https://github.com/goodtime-productivity/Goodtime)
*  <sup>**[[F-Droid](https://f-droid.org/app/com.danefinlay.ttsutil)]**</sup><br>
[![Readme Card](https://github-readme-stats.vercel.app/api/pin/?username=Danesprite\&repo=tts-util-app&cache_seconds=86400&theme=shadow_blue)](https://github.com/Danesprite/tts-util-app)
*  <sup>**[[F-Droid](https://f-droid.org/app/com.serwylo.beatgame)]**</sup><br>
[![Readme Card](https://github-readme-stats.vercel.app/api/pin/?username=beat-game\&repo=beat-game&cache_seconds=86400&theme=shadow_blue)](https://github.com/beat-game/beat-game)

### Expected behavior

Card show repo

**Comment by d3v7** [comment]
Hi,

For the first card
Username changed from "goodtime-productivity" to "adrcotfas"
![image](https://github.com/user-attachments/assets/fada9851-8145-4b4d-a694-6927acc7d0b8)

For the second card
Username changed from "Danesprite" to "drmfinlay"
![image](https://github.com/user-attachments/assets/6f6590a9-89f1-4934-b33c-9edd9ee275d9)

For the third card
Both the username and repository name is "beat-feet" but you are providing username and repository name as "beat-game"
maybe both changed?
![image](https://github.com/user-attachments/assets/320f72f5-82c6-4101-b211-b310349f4f25)


I believe that's the issue
