### ISSUE TITLE
The total commit and pull request count display isn't loading, with an error message in its place. There's no error code.

### ISSUE THREAD

**Issue by ahiyantra** [anuraghazra/github-readme-stats#3942]
### Describe the bug

It gives "something went wrong! - couldn't fetch total commits - please try again later" as an error message. There's no error code.

### Expected behavior

It should display the total count of commits and pull requests with an overall grade for github activity as an alphabet.

### Screenshots / Live demo link

Code:

`<img height="185em" src="https://github-readme-stats.vercel.app/api?username=ahiyantra&show_icons=true&theme=tokyonight&include_all_commits=true&count_private=true"/>`

Result:

![image](https://github.com/user-attachments/assets/3590a961-9f56-4942-a3aa-f283643ad7b8)

**Comment by ahiyantra** [comment]
The issue was resolved on its own overnight after i reported it. Maybe it was a server side problem.

**Comment by AZCodingAccount** [comment]
> The issue was resolved on its own overnight after i reported it. Maybe it was a cloud service provider server side problem.

I often have this problem, which suggests that the cloud doesn't seem to be very stable
