### ISSUE TITLE
GitHub Stats and Languages Card Not Updating

### ISSUE THREAD

**Issue by tarunganesh2004** [anuraghazra/github-readme-stats#3966]
### Describe the bug

When I hide certain programming languages in my GitHub README using the `hide` parameter, the displayed percentages for the remaining languages do not accurately reflect their contributions. For example, hiding Jupyter Notebook inflates the percentage of HTML disproportionately.

I have noticed that the language statistics do not update correctly when specific languages are hidden. This can lead to misleading representations of my programming skills and contributions.

### Expected behavior

- **Expected Behavior**: The stats and languages card should reflect my most recent contributions and the programming languages used. The percentages should be recalculated accurately based on the visible languages only.

### Screenshots / Live demo link

![image](https://github.com/user-attachments/assets/a8f1b51f-818a-46d9-9076-6c6e5351e9eb)

### Additional context

- **Username**: `tarunganesh2004`
- **Steps to reproduce**:
  1. Add a language card to my README with multiple languages.
  2. Use the `hide` parameter to hide one or more languages.
  3. Observe the changes in the percentages of the remaining languages.
  
- **Observed Behavior**: The remaining languages percentages do not accurately reflect their contributions based on the code in the repository.

**Comment by asifrahman479** [comment]
I can take a look at this. Assign it to me
