### ISSUE TITLE
Server is down?

### ISSUE THREAD

**Issue by yihong0618** [anuraghazra/github-readme-stats#398]
**Describe the bug**
Do not show the stats bange.

**Screenshots / Live demo link (paste the github-readme-stats link as markdown image)**
![image](https://user-images.githubusercontent.com/15976103/90373495-9195e680-e0a4-11ea-9820-a5167116cb9f.png)
![image](https://user-images.githubusercontent.com/15976103/90373411-732feb00-e0a4-11ea-8d96-4686edce0eab.png)

**Comment by anuraghazra** [comment]
See #325
