### ISSUE TITLE
Stars on the public repos not getting updated automatically 

### ISSUE THREAD

**Issue by ZU3AIRE** [anuraghazra/github-readme-stats#4015]
### Describe the bug

My public repo got the 3 stars but it didn't updated the status on card in my readme.md

### Expected behavior

Should update the star counts without any update

**Comment by LorenzoPegorari** [comment]
Hi, I am having the same issue.

### This is what happened:
- my public repo was at 4 stars when I initially inserted the repo card in my profile's README,
- when it got the 5th star, I noticed that the card wasn't updating, even after 72-96 hours,
- I then committed a change of the repo card's theme in my profile's README, and the number of stars finally got updated,
- after a few days I changed the description of the repo in question, and the same thing happened, meaning that the repo card in my profile isn't updating (even after more then 48 hours).

### Links:
- my profile: https://github.com/LorenzoPegorari
- the repo in question: https://github.com/LorenzoPegorari/SimplyColorful

### My profile's README 48 hours after changing the repo's description:

![screen-capture](https://github.com/user-attachments/assets/83caec84-f7a3-4600-8f5d-eedbdd704a58)

**Comment by LorenzoPegorari** [comment]
## Update

> * after a few days I changed the description of the repo in question, and the same thing happened, meaning that the repo card in my profile isn't updating (even after more then 48 hours).

Ok so apparently today, probably a few hours ago, it finally updated.

But this still means that it took just over a week to update the repo card, while in theory (if I am not mistaken) it should take around 6 hours, 24 hours at max.
