### ISSUE TITLE
Top lang bug

### ISSUE THREAD

**Issue by willin** [anuraghazra/github-readme-stats#403]
**Describe the bug**

- I did not write any php code for 5 years or more

**Expected behavior**

- the most used language is javascript

**Screenshots / Live demo link (paste the github-readme-stats link as markdown image)**

![](https://github-readme-stats.vercel.app/api/top-langs/?username=willin)

```
https://github-readme-stats.vercel.app/api/top-langs/?username=willin
```

**Additional context**

i do not want to hide manually, and i think it's a bug.

**Comment by szdytom** [comment]
It seems that it doesn't count repo in organizations

**Comment by TobiasPrt** [comment]
It does not even show Dart for me even though I do use it very frequently. And I never wrote PHP in a forked repo, only for some private stuff and it is way up. So it might not only use forked repos.

**Comment by KevinHubert-Dev** [comment]
For me i have about 4 repositories using javascript (js) which are all public and javascript is not even part of the statistic.

**Comment by ZephiroRB** [comment]
+1

**Comment by lrusso96** [comment]
> 
> 
> In my case: i have about 4 repositories using javascript (reactjs) which are all public and javascript is not even part of the statistic.

@KevinHubert-Dev This is due to the fact that GitHub API returns **the number of bytes of code written in that language**.
Your Highway-Drive repo contains a lot of Fortran code, for example. And that is much more than all your JS!


>   I did not write any php code for 5 years or more
>
>   the most used language is javascript

@willin You have an archived repo with a lot of PHP code: that's the reason.

**Comment by mchelen-gov** [comment]
> > In my case: i have about 4 repositories using javascript (reactjs) which are all public and javascript is not even part of the statistic.
> 
> @KevinHubert-Dev This is due to the fact that GitHub API returns **the number of bytes of code written in that language**.
> Your Highway-Drive repo contains a lot of Fortran code, for example. And that is much more than all your JS!
> 
> > I did not write any php code for 5 years or more
> > the most used language is javascript
> 
> @willin You have an archived repo with a lot of PHP code: that's the reason.

@lrusso96 thanks for explaining! maybe if some of these details were added to the [README](https://github.com/anuraghazra/github-readme-stats#top-languages-card) it would clear up some confusion?

**Comment by crazy-max** [comment]
Same issue for [my profile](https://github.com/crazy-max/):

![Top Langs](https://github-readme-stats.vercel.app/api/top-langs/?username=crazy-max&layout=compact)

Top langs should be closed to https://coderstats.net/github/#crazy-max
