### ISSUE TITLE
Jupyter Notebook is out of grid

### ISSUE THREAD

**Issue by DefinetlyNotAI** [anuraghazra/github-readme-stats#4042]
### Describe the bug

Its a visual bug, where because Jupyter Notebook is a mouthful, it escapes the visual border set:
![image](https://github.com/user-attachments/assets/fffbc8a1-191d-491d-a455-ac411eec3bd1)

### Expected behavior

The words Jupyter Notebook are not crossing the border

### Screenshots / Live demo link

https://camo.githubusercontent.com/744ac884996b83c3cdce1efaca76889c8816a30a316979aeaaf735cc357968f4/68747470733a2f2f6769746875622d726561646d652d73746174732e76657263656c2e6170702f6170692f746f702d6c616e67732f3f757365726e616d653d446566696e65746c794e6f7441492673697a655f7765696768743d302e313526636f756e745f7765696768743d302e35266c61796f75743d636f6d70616374267468656d653d766973696f6e2d667269656e646c792d6461726b

**Comment by DefinetlyNotAI** [comment]
Maybe just make it truncate to `Jupyter`?

**Comment by FajarKim** [comment]
You can resize the card width with the `card_width` option to a value greater than the default value. For example, if we use `340`, the result will be like this:

```markdown
https://github-readme-stats.vercel.app/api/top-langs/?username=DefinetlyNotAI&size_weight=0.15&count_weight=0.5&layout=compact&theme=vision-friendly-dark&hide=jupyter-notebook,cython,css,cuda,cmake,shell&card_width=340
```

![Stats](https://github-readme-stats.vercel.app/api/top-langs/?username=DefinetlyNotAI&size_weight=0.15&count_weight=0.5&layout=compact&theme=vision-friendly-dark&hide=jupyter-notebook,cython,css,cuda,cmake,shell&card_width=340)

**Comment by DefinetlyNotAI** [comment]
Thanks m8,
