### ISSUE TITLE
Layout is little off in Ubuntu Firefox

### ISSUE THREAD

**Issue by saurabhdaware** [anuraghazra/github-readme-stats#42]
Hi, Layout is off in Firefox - Ubuntu.

![screenshot of README stats that show the total commits are shifted to right](https://user-images.githubusercontent.com/30949385/87320641-c87a5900-c548-11ea-8972-9071a2aab67e.png)

**Comment by anuraghazra** [comment]
Thanks for reporting the issue @saurabhdaware i'll try to fix it ASAP

**Comment by kingthorin** [comment]
I think this is a general Firefox issue, I experienced the same in 78.0.2 on WIn10 earlier today: ![image](https://user-images.githubusercontent.com/7570458/87310114-7e16bf00-c4eb-11ea-877f-f8fa595d71c3.png)
