### ISSUE TITLE
Robot Framework code files scanning and displaying on the widget

### ISSUE THREAD

**Issue by YauheniPo** [anuraghazra/github-readme-stats#425]
is it possible to add a display in statistics of code written using the ROBOT Framework?
https://i.imgur.com/poZ4Hq7.png

**Comment by anuraghazra** [comment]
Hi @YauheniPo 

It will only show it, if you have enough ROBOT Framework code in bytes relative to other code languages

**Comment by YauheniPo** [comment]
Thanks, @anuraghazra . I understood
