### ISSUE TITLE
Why doesn't `TOTAL_VALUES` include `RANK_DOUBLE_A_VALUE`?

### ISSUE THREAD

**Issue by ngzhio** [anuraghazra/github-readme-stats#428]
https://github.com/anuraghazra/github-readme-stats/blob/e3d6f9503123cafb4b1084bc859800967197bb64/src/calculateRank.js#L51

Why doesn't `TOTAL_VALUES` include `RANK_DOUBLE_A_VALUE`?

**Comment by bert2** [comment]
Was just wondering the same thing. Looks like a bug to me.

**Comment by bert2** [comment]
Also weird: `ALL_OFFSETS` does not include `COMMITS_OFFSET`.

**Comment by bert2** [comment]
Is this something to worry about, @anuraghazra?
