### ISSUE TITLE
Profile visit counter

### ISSUE THREAD

**Issue by deep5050** [anuraghazra/github-readme-stats#43]
Is it possible to track a profile visitors count?

**Comment by anuraghazra** [comment]
It does not have this feature yet but you can use this instead.

https://visitor-badge.glitch.me/#docs

**Comment by ABSphreak** [comment]
or https://hits.dwyl.com/

**Comment by anuraghazra** [comment]
Hi @deep5050 after thinking a bit through i decided that i wont add any visitors count stats because this project solely focused on providing github statistics :D i hope you understand the point, anyways thanks for the feature request, do open another issues if you have any queries

**Comment by JiuBanA1** [comment]
Can I change the color
