### ISSUE TITLE
Top Languages Card doesn't detect Java language.

### ISSUE THREAD

**Issue by pablohs1986** [anuraghazra/github-readme-stats#432]
**Describe the bug**
Top Languages Card doesn't detect Java language. I have various repositories (13),  6 of them are Java projects, but Top Languages Card doesn't show information about Java language. 

**Expected behavior**
Top Languages Card detect Java language.

**Screenshots / Live demo link (paste the github-readme-stats link as markdown image)**
<img align="center" src="https://github-readme-stats.vercel.app/api/top-langs/?username=pablohs1986&theme=dracula&hide=python,html,css"/>
`"https://github-readme-stats.vercel.app/api/top-langs/?username=pablohs1986&theme=dracula&hide=python,html,css"`
[profile](https://github.com/pablohs1986/pablohs1986)

Thanks!!!

**Comment by dheerajpoonia29** [comment]
I also have the same issue

**Comment by lrusso96** [comment]
> Top Languages Card doesn't detect Java language. I have various repositories (13), 6 of them are Java projects, but Top Languages Card doesn't show information about Java language.

pablohs1986 This is due to an error in sorting languages: it relies on Object.keys method which is unreliable.
I have prepared a lazy fix for this, and I will open a PR as soon as I can.

Your top languages should be (according to my patched version): CSS, HTML, Java, PowerShell and Python. Since you specified `hide=python,html,css`, the top used language should be Java, followed by PowerShell, etc. Is this ok?

**Comment by pablohs1986** [comment]
@lrusso96  thanks for check it! I have noticed that JavaScript does not detect me either... I think my languages should be CSS, HTML, Java, JavaScript and Python (ya hide python, html and css).

**Comment by pablohs1986** [comment]
Hey👋 @lrusso96 do you know when to upload the solution?

**Comment by lrusso96** [comment]
> Hey👋 @lrusso96 do you know when the solution will come up?

Hi @pablohs1986, we need to wait for @anuraghazra's review: he is the owner, I'm only a contributor.

In the meanwhile, you could fork my repo with the fix and deploy your own instance on vercel.
