### ISSUE TITLE
I can't run the application

### ISSUE THREAD

**Issue by Math-O5** [anuraghazra/github-readme-stats#438]
HI @anuraghazra  I'am trying commit the application but I got stuck in the test "jest --coverage": 

""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""
 FAIL  tests/retryer.test.js
  ● Test suite failed to run

    Jest encountered an unexpected token

""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""

Before that he was saying that I should add a plugin "  "@babel/plugin-syntax-class-properties" of babel. 

What I should try?

**Comment by lrusso96** [comment]
Hi @Math-O5, which version of npm, node, and jest are you using?

**Comment by Math-O5** [comment]
> which version of npm, node, and jest are you using?
Hi @lrusso96! 
I'm using "npm 6.14.4" and "jest": "^26.1.0" and node 10.21.0.

**Comment by Math-O5** [comment]
Obs: I update node to "node-v12.18.3", solved. Thanks @lrusso96

**Comment by lrusso96** [comment]
> I'm using "npm 6.14.4" and "jest": "^26.1.0" and node 10.21.0.

Try to upgrade to node 12.x (it is the one tested on GitHub Actions).

> My branch: https://github.com/Math-O5/stackoverflow-readme-stats/tree/card-stackoverflow
> 
> Since you are a contributor, I'd like ask if you are interesting in merge a card stackoverflow in the future, that I'm working, or if is better I keep it in a separate repo for stackoverflow stats only. Thanks.

Better open a new issue and ask to  @anuraghazra. By the way, it is very nice.

**Comment by anuraghazra** [comment]
> Since you are a contributor, I'd like ask if you are interesting in merge a card stackoverflow in the future, that I'm working, or if is better I keep it in a separate repo for stackoverflow stats only. Thanks.

Actually one of my friend and early contributor to this repo @omidnikrah already built a really nice stackoverflow stats card :- https://github.com/omidnikrah/github-readme-stackoverflow

Well yes i can also add stackoverflow cards but i don't want to bloat the repo with lots of new cards, also as the name suggests this is **github**-readme-stats, so making a separate repo for the stackoverflow card makes sense.
