### ISSUE TITLE
Change in Language with '&layout=compact'

### ISSUE THREAD

**Issue by rahulbordoloi** [anuraghazra/github-readme-stats#439]
**Bug**
Change in Language Stats with `&layout=compact` attribute.

Whenever I opt-in '&layout=compact' to compact the layout of the top languages, my C++ stats get replaced by PHP stats.

<img width="176" alt="1" src="https://user-images.githubusercontent.com/51340365/91925946-bec4d480-ecf3-11ea-9363-a36566c8b54e.PNG">
The Above Screenshot is for the Code - 

```
[![Top Langs](https://github-readme-stats.vercel.app/api/top-langs/?username=rahulbordoloi&hide=Jupyter%20Notebook)](https://github.com/rahulbordoloi/github-readme-stats)
```

<img width="207" alt="2" src="https://user-images.githubusercontent.com/51340365/91925986-d9974900-ecf3-11ea-910d-441d6a6af586.PNG">

The Above Screenshot is for the Code - 
```
[![Top Langs](https://github-readme-stats.vercel.app/api/top-langs/?username=rahulbordoloi&hide=Jupyter%20Notebook&layout=compact)](https://github.com/rahulbordoloi/github-readme-stats)
```

Is this a client-side issue or a server-side? If I can rectify it by myself, it would be highly helpful. :)

**Comment by lrusso96** [comment]
Hi @rahulbordoloi, I cannot replicate your issue. This is what I receive:

![image](https://user-images.githubusercontent.com/26090639/91942421-377b5f00-ecfb-11ea-8753-872790d50c30.png)

**Comment by rahulbordoloi** [comment]
@lrusso96 did you use the same code as I did?

**Comment by lrusso96** [comment]
Yep @rahulbordoloi, look at these:

![Top Langs](https://github-readme-stats.vercel.app/api/top-langs/?username=rahulbordoloi&hide=Jupyter%20Notebook&layout=compact)

![Top Langs](https://github-readme-stats.vercel.app/api/top-langs/?username=rahulbordoloi&hide=Jupyter%20Notebook)

**Comment by rahulbordoloi** [comment]
@lrusso96 Yeah, It's resolved in my Side too. The problem might have raised due to a latency error in the API or might be cache problem in my PC. 
Thank You. You can close this issue now. :)

**Comment by lrusso96** [comment]
@rahulbordoloi you should close it, I don't have the permissions!

**Comment by rahulbordoloi** [comment]
Done.
