### ISSUE TITLE
Is there a way to hide the ranking?

### ISSUE THREAD

**Issue by TheAshwanik** [anuraghazra/github-readme-stats#44]
Hi,
Is there a way to hide the ranking until the issue fixed or algo improved ?

**Comment by anuraghazra** [comment]
yes you can `&hide_rank=true` query param

**Comment by ABSphreak** [comment]
@anuraghazra now at this point, setting up something like [Gitter](https://gitter.im/) would be a better way to communicate about minor issues.

**Comment by anuraghazra** [comment]
Thanks for the suggestion @ABSphreak maybe i'll consider that at some point :D

**Comment by anuraghazra** [comment]
@TheAshwanik I hope it solved your issue feel free to open another one if you have any queries :D

**Comment by TheAshwanik** [comment]
Thank you Anurag.. Cheers.
Its not an issue per se.. But I thought until the algo and offset (that you are discussing in  #41  ) have been standardized, this may be an option for some.
