### ISSUE TITLE
Why it looks different

### ISSUE THREAD

**Issue by kajweb** [anuraghazra/github-readme-stats#447]
[![wqxuetang_downloader](https://github-readme-stats.vercel.app/api/pin/?username=kajweb&repo=wqxuetang_downloader)

[![wqxuetang_downloader](https://github-readme-stats-ten.vercel.app/api/pin/?username=kajweb&repo=wqxuetang_downloader)

Why it looks different,and how can I fix it?

**Comment by kajweb** [comment]
![Screenshot_2020-09-10-07-54-02-88](https://user-images.githubusercontent.com/2993320/92666074-c4c04400-f2f7-11ea-94d4-ba21089e7f34.jpg)

**Comment by anuraghazra** [comment]
Hi @kajweb thanks for opening the issue, actually we do have few issues with line breaks and i think japanese letters are taking moe pixel space than english words so thats why layout breaks and it overflows the card.

related to #80

**Comment by kajweb** [comment]
Thanks for your answer.

By the way, this is Chinese.
