### ISSUE TITLE
Show last 'n' days contributions

### ISSUE THREAD

**Issue by nrchandan** [anuraghazra/github-readme-stats#449]
**Is your feature request related to a problem? Please describe.**
I am a volunteer for a local Hacktoberfest event. I was planning to use this tool to create a visualisation of recent GitHub activity of the participants. This tool shows GitHub activity of the last one year. I am interested in the most recent activity of the participants, say last 2 weeks or a month.

**Describe the solution you'd like**
Ideally, I would like to pass a 'sinceDays' / query param to this tool so that the visualisation generated shows the GitHub activity since last 'sinceDays' days 😄 

**Describe alternatives you've considered**
I have explored the GitHub GraphQL API a little bit and I am able to add a 'from' filter to get total commits since that date. I am planning to spend some more time on this. If this feature would be useful, I am happy to raise a PR.

**Additional context**
I'll update this graphQL gist with the date filter: https://gist.github.com/nrchandan/446316c97388eec12520fcb39c7991d2

**Comment by anuraghazra** [comment]
Hi @nrchandan Yeah we can add a parameter to control the contribution activity. 

As long as it's less than 1year we are fine, but github does not allow fetching more than 1 year's activity at once. :) 

I'll see what i can do, meanwhile you can also raise a PR implementing this, it would be very straightforward i'm sure.

**Comment by nrchandan** [comment]
On a second thought, I think contributions since a given date makes more sense e.g. all contributions since September 1. I'm able to get the filtered data for commits (`contributionsCollection`), but not pull requests or issues. Still trying to understand the GraphQL API.

**Comment by anuraghazra** [comment]
@nrchandan you can get issues, pr, contributions and sum them up.

```gql
    contributionsCollection {
      totalPullRequestContributions
      totalCommitContributions
      totalIssueContributions
      totalPullRequestReviewContributions
      restrictedContributionsCount
    }
```

**Comment by nrchandan** [comment]
Thanks for the info @anuraghazra! This is exactly what I was looking for. Instead of summing them up, I'm thinking of replacing the current stats with this one if the `from` parameter is passed. I guess the other parameters (`repositoriesContributedTo`, `pullRequests`, `issues`, `followers`, etc) are since the beginnning where as the contributionsCollection is only for the last one year or less depending on the `from` parameter passed.
