### ISSUE TITLE
How to exclude DIGITAL Command Language from the language card

### ISSUE THREAD

**Issue by subhaminion** [anuraghazra/github-readme-stats#451]
My Language card looks like this
<img width="303" alt="Screenshot 2020-09-11 at 3 49 10 PM" src="https://user-images.githubusercontent.com/13986359/92911242-576ef900-f446-11ea-95b4-206837d5dfc1.png">

I want to exclude DIGITAL Command Language from the list, how can I do that?

**Comment by anuraghazra** [comment]
Hi @subhaminion you can use the `hide` param

> https://github-readme-stats.vercel.app/api/top-langs/?username=subhaminion&hide=DIGITAL%20Command%20Language

![](https://github-readme-stats.vercel.app/api/top-langs/?username=subhaminion&hide=DIGITAL%20Command%20Language)

**Comment by anuraghazra** [comment]
I hope this answers your question, closing this for now.
