### ISSUE TITLE
top-langs card only includes local repos

### ISSUE THREAD

**Issue by GalaxySH** [anuraghazra/github-readme-stats#453]
**Is your feature request related to a problem? Please describe.**
The top-langs card only seems to include languages used in local repos. If this isn't the case, then this is a bug, since it isn't showing the language that I know for a fact I use the most.

**Describe the solution you'd like**
It would be nice if the card also included languages used as a member of organizations (since that's where most of my work is) through a parameter option.

**Additional context**
![image](https://user-images.githubusercontent.com/34115400/92999190-b3885a80-f4e4-11ea-9365-4b7ee57242d6.png)
This should be mostly JavaScript

**Comment by anuraghazra** [comment]
Hi @GalaxySH We do not calculate any organization stats see #1 for more info.

**Comment by GalaxySH** [comment]
relevant but the feature isn't going to happen anytime soon
