### ISSUE TITLE
change project about will not change the pined item

### ISSUE THREAD

**Issue by Cyberist-Edgar** [anuraghazra/github-readme-stats#454]
**Describe the bug**
change project description will not change the pinned item

**Expected behavior**
the pinned item should also change its description

**Screenshots / Live demo link (paste the github-readme-stats link as markdown image)**
I pinned this one on my readme states, but later I changed the description of the project, but the pinned item didn't change
<img src=https://user-images.githubusercontent.com/47896650/92999281-385d8d80-f552-11ea-9009-eeded152e185.png width=400>
<img src=https://user-images.githubusercontent.com/47896650/92999313-7e1a5600-f552-11ea-9e36-233775f01955.png width=400>

**Additional context**
if I change the repo name, using the lowercase letter or uppercase one, it works fine

**Comment by anuraghazra** [comment]
There is a 2 hour cache setup, wait for 2 hours or bust the cache by changing the URL

add any random query string at the end of the URL `&v=1`

**Comment by Cyberist-Edgar** [comment]
> There is a 2 hour cache setup, wait for 2 hours or bust the cache by changing the URL
> 
> add any random query string at the end of the URL `&v=1`

Got it, thanks a lot!
