### ISSUE TITLE
Images on Extra Pins

### ISSUE THREAD

**Issue by giansalex** [anuraghazra/github-readme-stats#46]
![image](https://user-images.githubusercontent.com/14926587/87385414-9fb38d00-c563-11ea-9fd8-69d5100dca2a.png)

**Comment by anuraghazra** [comment]
Hi @giansalex sorry for late response, yes this is a great idea but i wanted to make the `Github Extra Pins` feature look as close to as  original pinned repo cards.

**Comment by nthnchu** [comment]
Seems like this issue is gathering dust, I'll start working on a PR today 👍

**Comment by anuraghazra** [comment]
> Seems like this issue is gathering dust, I'll start working on a PR today 👍

Don't. we won't be adding this feature. Forgot to close the issue.
