### ISSUE TITLE
[Question/Feature Request] Does it fetch commits from public repos only?

### ISSUE THREAD

**Issue by rampatra** [anuraghazra/github-readme-stats#466]
I have made way more commits this year than what is shown here: https://github.com/rampatra. So, was wondering if they fetch only public commits?

If yes, what do you think about fetching commit count from private repos as well? Is it doable or is this feature already present (and I am ignorant)?

**Comment by AryanBeezadhur** [comment]
To count private commits, add this query parameter to the URL:

```
&count_private=true
```

Compare `https://github-readme-stats.vercel.app/api?username=rampatra&show_icons=true&count_private=true`:

![https://github-readme-stats.vercel.app/api?username=rampatra&show_icons=true&count_private=true](https://github-readme-stats.vercel.app/api?username=rampatra&show_icons=true&count_private=true)

To `https://github-readme-stats.vercel.app/api?username=rampatra&show_icons=true`:

![https://github-readme-stats.vercel.app/api?username=rampatra&show_icons=true](https://github-readme-stats.vercel.app/api?username=rampatra&show_icons=true)

**Comment by rampatra** [comment]
That's awesome. Thanks 👏
