### ISSUE TITLE
Stars from forks not included

### ISSUE THREAD

**Issue by SelfhostedPro** [anuraghazra/github-readme-stats#467]
**Describe the bug**
Total stars doesn't include stars from forks which I believe should be included.

**Expected behavior**
Stars from forks should be added to the total star count (possibly include them independently in `()` to the right).

**Screenshots / Live demo link (paste the github-readme-stats link as markdown image)**
You can see I have a fork with 250 stars which aren't added too my total count: https://github.com/SelfhostedPro

**Additional context**
Totally understand if this is an issue with the github api.

**Comment by anuraghazra** [comment]
No forked repos should not be counted, if any user forked reactjs then reactjs's stars aren't user's gained stars.

**Comment by anuraghazra** [comment]
Oh wait yeah right. I think forked repo's stars should be counted. Will do something for it.

**Comment by SelfhostedPro** [comment]
Awesome! Thanks!
