### ISSUE TITLE
Doesn't show any languages and can't remove border from repo card

### ISSUE THREAD

**Issue by Bas950** [anuraghazra/github-readme-stats#468]
**Describe the bug**
On my language card it doesn't show any languages, its empty.
On the pin card the border isn't gone.

**Expected behavior**
Show the languages and remove the border

**Screenshots / Live demo link (paste the github-readme-stats link as markdown image)**
https://github.com/Bas950/Bas950
Links used:
https://github-readme-stats.vercel.app/api/top-langs/?username=Bas950&hide_border=true&show_icons=true&theme=dark
https://github-readme-stats.vercel.app/api/pin/?username=PreMiD&repo=Presences&show_icons=true&hide_border=true&theme=dark
![image](https://user-images.githubusercontent.com/34792838/93406558-39632780-f890-11ea-9ba3-83dc35f167f9.png)

**Comment by anuraghazra** [comment]
I don't think we can add count_forks option since if we do that then, if some users forked any big third party lib it would also get counted which would make the stats wrong.

**Comment by Bas950** [comment]
> I don't think we can add count_forks option since if we do that then, if some users forked any big third party lib it would also get counted which would make the stats wrong.

Will see if I can make a exclude_repo for it

**Comment by anuraghazra** [comment]
> > I don't think we can add count_forks option since if we do that then, if some users forked any big third party lib it would also get counted which would make the stats wrong.
> 
> Will see if I can make a exclude_repo for it

We won't support any forks in here, since it would just make the API surface very wide. we cannot make it opt-in. we can although make it opt-out.

**Comment by Bas950** [comment]
> > > I don't think we can add count_forks option since if we do that then, if some users forked any big third party lib it would also get counted which would make the stats wrong.
> > 
> > 
> > Will see if I can make a exclude_repo for it
> 
> We won't support any forks in here, since it would just make the API surface very wide. we cannot make it opt-in. we can although make it opt-out.

I updated the PR, I made an exclude_repo, but do you want me to make the count_forks a opt-out instead of opt-in?
Or how do you wish for me to make it.

**Comment by Bas950** [comment]
@anuraghazra Want me to make it opt-out then?

**Comment by Bas950** [comment]
Hey @anuraghazra, would you want me to make it always get the forks, and then make it opt-out? (just by checking is "isFork" == true that is returned from the graphql). I also made an exclude_repo so you can exclude repositories from being counted towards the languages.

**Comment by Bas950** [comment]
Repo card hide border merged in #488

**Comment by Bas950** [comment]
Top Langs exclude repo merged in https://github.com/anuraghazra/github-readme-stats/pull/493
