### ISSUE TITLE
Last updated x repositories card would be nice.

### ISSUE THREAD

**Issue by ardacetinkaya** [anuraghazra/github-readme-stats#472]
I don't know if any new feature is going to be added to this repository, but if there is a new card to show last updated repositories, it would be nice in GitHub Profiles because currently in a profile page it is not possible to show last updated repositories without accessing all repositories.

And also it would be nice to have this info for other platforms such as WordPress and blogs... 

I have created a PR #471 which provides new API and card for showing last updated repositories..

## Demo
[![Repositories](https://ardacetinkaya-github-readme-stats.vercel.app/api/repos/?username=ardacetinkaya&top=7)](https://github.com/ardacetinkaya?tab=repositories)

**Comment by Bas950** [comment]
Updates on branches don't seem to count.
<details>
  <summary>Screen of branches not working</summary>
![image](https://user-images.githubusercontent.com/34792838/93655188-5fb8cc80-fa22-11ea-89b8-05d3e1f4a0c6.png)
https://github.com/Bas950/Presences/tree/programsReady
</details>


Would be nice if you could choose between MM/DD/YY and DD/MM//YY.

**Comment by ardacetinkaya** [comment]
Currently just main branches updates are considered due to GitHub's GraphQL API.

And you are right that date format options would be really nice.  
I know it is not best way but I changed to DD/MM/YYYY as default format, it is also possible to set format with query parameter;
`api/repos/?username=ardacetinkaya&top=15&date_format=MM-DD-YYYY`

Updated PR #471

**Comment by Bas950** [comment]
> Currently just main branches updates are considered due to GitHub's GraphQL API.

That's a RIP



> And you are right that date format options would be really nice.  
> I know it is not best way but I changed to DD/MM/YYYY as default format, it is also possible to set format with query parameter;
> `api/repos/?username=ardacetinkaya&top=15&date_format=MM-DD-YYYY`
> 
> Updated PR #471 
> 

Nice!

**Comment by ardacetinkaya** [comment]
PR #471 is updated to have hide border and title options via query string as ```....&top=7&hide_border=true&hide_title=true```

Result;
[![Repositories](https://ardacetinkaya-github-readme-stats.vercel.app/api/repos/?username=ardacetinkaya&top=7&hide_border=true&hide_title=true)](https://github.com/ardacetinkaya?tab=repositories)
