### ISSUE TITLE
stars from organisation not displayed on member card

### ISSUE THREAD

**Issue by Wafelack** [anuraghazra/github-readme-stats#478]
**Describe the bug**
Stars from organisation aren't displayed on member card

**Expected behavior**
I expect stars from organisation to be displayed

**Screenshots / Live demo link (paste the github-readme-stats link as markdown image)**
![Wafe](https://github-readme-stats.vercel.app/api?username=wafelack&show_icons=true&title_color=bbbbbb&text_color=dddddd&icon_color=990000&bg_color=111111&include_all_commits=true)

**Comment by rivenirvana** [comment]
See #1.

**Comment by anuraghazra** [comment]
Duplicate of #1
