### ISSUE TITLE
Total commits and ranking went down

### ISSUE THREAD

**Issue by alevosia** [anuraghazra/github-readme-stats#487]
When I checked my stats awhile ago, the total commits went down to 1.2K from 1.9K. I've checked other people's profile who I know use this as well and everyone's total commits and ranking went down as well.

I think it's probably the private commits not being counted anymore.

**Comment by AlBannaTechno** [comment]
### Also, a very strange thing happens
My Total Commits is about **3900**
And now it is only show **793** when `include_all_commits=true` 
But When using `include_all_commits=false` 
it is going up to **3.1K**
But still does not reach the old value **3.8K**

In all cases `count_private=true`
My Public commits are **560**

**Comment by anuraghazra** [comment]
Previously it was incorrect, see #391
