### ISSUE TITLE
include_all_commits does not work anymore

### ISSUE THREAD

**Issue by avgupta456** [anuraghazra/github-readme-stats#489]
**Describe the bug**
the include_all_commits flag should include all commits. However, as of 9/24/2020, it seems to only count commits from the past. This is not the expected behavior.

**Expected behavior**
I have 2.2k commits this year, and 1.5k commits from previous years. Without the include_all_commits flag, I get 2.2k which is my commit total this year. With the include_all_commits flag, I get 1.5k which is my previous years commit. Yesterday (or recently at least), I used to get 3.7k which is my total commits from all years.

**Screenshots / Live demo link (paste the github-readme-stats link as markdown image)**
Include all commits
<img align="center" width="49%" style="margin-right:1%" src="https://github-readme-stats.vercel.app/api?username=avgupta456&count_private=true&hide=stars,prs&show_icons=true&include_all_commits=true" />
Without include all commits
<img align="center" width="49%" style="margin-right:1%" src="https://github-readme-stats.vercel.app/api?username=avgupta456&count_private=true&hide=stars,prs&show_icons=true" />
![image](https://user-images.githubusercontent.com/16708871/94163080-6ba6f300-fe55-11ea-9bcb-87829c74eeb8.png)

**Additional context**
It was working a few days ago, so maybe a recent change broke this functionality.

**Comment by anuraghazra** [comment]
Hi @avgupta456 thanks for opening the issue, btw did you considered that what github shows is "total *contribution* in the last year" not "total *commits* in the last year"

**Comment by avgupta456** [comment]
At least for me, 97% of my contributions are commits so there shouldn't be such a large discrepancy. 

![image](https://user-images.githubusercontent.com/16708871/94167264-4ff21b80-fe5a-11ea-9ac6-2eed6952d9ba.png)

**Comment by anuraghazra** [comment]
Also i think yes this is technically a bug which happened because of the if statement order in the #391

**Comment by anuraghazra** [comment]
So as i'm fixing it... with your user name, setting include_all_commits & count_private  both to true you have total of 2.5k commits. (which is correct since previously we double added the total commits & current year commits which was incorrect that is fixed in #391)

**Comment by avgupta456** [comment]
I count roughly 2900 total contributions for me, so 2.5k commits sound around right.

**Comment by anuraghazra** [comment]
> I count roughly 2900 total contributions for me, so 2.5k commits sound around right.

Yup! pushing the fix right now. Here's a development preview link you can check now (don't use it) : https://github-readme-stats-j05el383g.vercel.app/api/?username=avgupta456

**Comment by avgupta456** [comment]
Great, thanks so much!

**Comment by anuraghazra** [comment]
@avgupta456 fix has been deployed (note there is 2 hour cache so it will take time to take an effect on readme)
