### ISSUE TITLE
Wakatime week stats error

### ISSUE THREAD

**Issue by Aryankpoor** [anuraghazra/github-readme-stats#492]
**Error showing when adding wakatime week status to readme**
When you add the wakatime week stats to your readme it is showing an error that 'Something went wrong! file an issue at https://git.io/JJmN9'

**Expected behavior**
The wakatime should have clearly shown up I even changed the username correctly

**Link to error**
![error](https://github.com/Aryankpoor/Aryankpoor]

**Comment by anuraghazra** [comment]
Do you even have a wakatime profile??? https://wakatime.com/@Aryankpoor

**Comment by Aryankpoor** [comment]
yes

**Comment by anuraghazra** [comment]
Whats your username then?

**Comment by Aryankpoor** [comment]
Aryankapoor

**Comment by anuraghazra** [comment]
You have a typo in your username which you put.
```diff
+ Aryankapoor
- Aryankpoor
