### ISSUE TITLE
Error 404 in wakatime

### ISSUE THREAD

**Issue by JoykishanSharma** [anuraghazra/github-readme-stats#494]
**Describe the bug**
hi, I got Error 404 when I tried wakatime api with my username :sob:. Url : `https://github-readme-stats.vercel.app/api/wakatime?username=JoykishanSharma)` also tried `https://github-readme-stats.vercel.app/api/wakatime?username=joykishansharma)`

**Expected behavior**
I was expecting to get [something like this](https://github-readme-stats.vercel.app/api/wakatime?username=willianrod) with my profile :smiley:.

**Screenshots / Live demo link (paste the github-readme-stats link as markdown image)**

![Got this 404 error](https://user-images.githubusercontent.com/47889468/94226579-9789ad80-ff15-11ea-8738-9e582ed8d3b6.png)

**Comment by anuraghazra** [comment]
If you don't even know your actual Wakatime username which one is correct i can't help you. 

https://wakatime.com/@Joykishansharma
https://wakatime.com/@JoykishanSharma

**Comment by JoykishanSharma** [comment]
ouch!! That was kinda rude brother :smile:,

1. My username is `JoykishanSharma` . 
2. I tried both of these 
> `https://github-readme-stats.vercel.app/api/wakatime?username=JoykishanSharma`
> `https://github-readme-stats.vercel.app/api/wakatime?username=joykishansharma`

coz those username worked just fine with these

> [https://github-readme-stats.vercel.app/api?username=JoykishanSharma&show_icons=true&theme=algolia&count_private=true&include_all_commits=true](https://github-readme-stats.vercel.app/api?username=JoykishanSharma&show_icons=true&theme=algolia&count_private=true&include_all_commits=true)
> [https://github-readme-stats.vercel.app/api?username=joykishansharma&show_icons=true&theme=algolia&count_private=true&include_all_commits=true](https://github-readme-stats.vercel.app/api?username=joykishansharma&show_icons=true&theme=algolia&count_private=true&include_all_commits=true) .

3. I got this URL `https://github-readme-stats.vercel.app/api/wakatime?username=myUsername` from `readme.md` file and more specifically from [HERE](https://github.com/anuraghazra/github-readme-stats/blob/master/readme.md#wakatime-week-stats). Worked just fine for our friend [Willian Rodrigues](https://github-readme-stats.vercel.app/api/wakatime?username=willianrod).

4. These links `https://wakatime.com/@Joykishansharma` `https://wakatime.com/@JoykishanSharma` aren't what I'm looking for :smile:.

Anyway, thanks for replying :smiley:.

**Comment by anuraghazra** [comment]
Firstly tell me, do you have a wakatime.com profile?

**Comment by JoykishanSharma** [comment]
> wakatime.com

nope.

**Comment by anuraghazra** [comment]
> > wakatime.com
> 
> nope.

Yeah so how can you expect your wakatime stats would work? of course it would show 404 since you don't even have a wakatime profile..

Please visit wakatime.com first and create an account.

**Comment by JoykishanSharma** [comment]
> > > wakatime.com
> > 
> > 
> > nope.
> 
> Yeah so how can you expect your wakatime stats would work? of course it would show 404 since you don't even have a wakatime profile..
> 
> Please visit wakatime.com first and create an account.

WakaTime Plugins are great but I'm not looking for plugins. I am trying to get this [Wakatime week stats](https://github-readme-stats.vercel.app/api/wakatime?username=willianrod) :smiley:

Let's not get confused.... I'm trying to get this :point_down: 

![This](https://user-images.githubusercontent.com/47889468/94338457-f03d7100-000f-11eb-8da2-654f40110ea9.png)

or

![This](https://user-images.githubusercontent.com/47889468/94338458-f2073480-000f-11eb-8175-8adcdaf4ea91.png)

As I [found mentioned here](https://github.com/anuraghazra/github-readme-stats/blob/master/readme.md#wakatime-week-stats) :point_down:

![1](https://user-images.githubusercontent.com/47889468/94338478-2a0e7780-0010-11eb-8d3a-40e6a680fe53.png)

**Comment by anuraghazra** [comment]
Bro this is wakatime stats, these stats are fetched from WakatimeAPI!
You need to have a wakatime profile in order to get the stats.

**Comment by JoykishanSharma** [comment]
> Bro this is **wakatime stats**, these stats are fetched from WakatimeAPI!
> You need to have a **wakatime profile** in order to get the stats.

Ok...thanks...sorry for any trouble.. :smile:

BTW, that link was really needed there.. :+1:

**Comment by anuraghazra** [comment]
> > Bro this is **wakatime stats**, these stats are fetched from WakatimeAPI!
> > You need to have a **wakatime profile** in order to get the stats.
> 
> Ok...thanks...sorry for any trouble.. 😄
> 
> BTW, that link was really needed there.. 👍

Yeah just put it on the readme, also changed the error message on the card to be more specific... #498
