### ISSUE TITLE
Something Went Wrong

### ISSUE THREAD

**Issue by skyrunner360** [anuraghazra/github-readme-stats#499]
**Describe the bug**

**Expected behavior**

**Screenshots / Live demo link (paste the github-readme-stats link as markdown image)**

**Additional context**

**Comment by anuraghazra** [comment]
Hi @skyrunner360 Can you please describe your issue in-depth, you did not give any useful information so that I can resolve your issues.

**Comment by anuraghazra** [comment]
Closing this because of lack of information & no response from author.
