### ISSUE TITLE
Gradient theme not working

### ISSUE THREAD

**Issue by Aryankpoor** [anuraghazra/github-readme-stats#500]
**Describe the bug**
When I set my github stats card's theme to gradient the theme did not change instead changed to the default theme.
I even tried changing the case of the word  I tried-'gradient', 'Gradient', 'GRADIENT' but it still would not work

**Expected behavior**
To change the theme to gradient

**Screenshots / Live demo link (paste the github-readme-stats link as markdown image)**
[link to my readme. Please view the code for any typo](https://github.com/Aryankpoor/Aryankpoor)

**Additional context**

**Comment by anuraghazra** [comment]
There is no theme named gradient, please read the docs first.

**Comment by anuraghazra** [comment]
Here's the list of available themes: https://github.com/anuraghazra/github-readme-stats/tree/master/themes

**Comment by sahdjfg** [comment]
Then why this exists at https://github.com/anuraghazra/github-readme-stats#all-demos? ![image](https://user-images.githubusercontent.com/83467454/127881825-7d4f5831-058a-46a6-a075-0fe9f525b9dc.png)

**Comment by Eldrick99** [comment]
![99's Github Stats](https://github-readme-stats.vercel.app/api?username=Eldrick99&bg_color=30,e96443,904e95&title_color=fff&text_color=fff)   
### This is how it works...

Code==
```
 ![99's Github Stats](https://github-readme-stats.vercel.app/api?username=Eldrick99&bg_color=30,e96443,904e95&title_color=fff&text_color=fff
```

**Comment by Eldrick99** [comment]
![99's Github Stats](https://github-readme-stats.vercel.app/api?username=Eldrick99&bg_color=30,0ff1ce,904e95&title_color=fff&text_color=fff)
 You can add your OWN HEX COLORS!... 
This code..
```
![99's Github Stats](https://github-readme-stats.vercel.app/api?username=Eldrick99&bg_color=30,0ff1ce,904e95&title_color=fff&text_color=fff)
```

**Comment by sahdjfg** [comment]
> ![99's Github Stats](https://camo.githubusercontent.com/051c7fbeecd4c84845aa8488f49d11d1c50bcece2fa360c735021de68cfd97ec/68747470733a2f2f6769746875622d726561646d652d73746174732e76657263656c2e6170702f6170693f757365726e616d653d456c647269636b39392662675f636f6c6f723d33302c6539363434332c393034653935267469746c655f636f6c6f723d66666626746578745f636f6c6f723d666666)
> 
> ### This is how it works...
> Code==
> 
> ```
>  ![99's Github Stats](https://github-readme-stats.vercel.app/api?username=Eldrick99&bg_color=30,e96443,904e95&title_color=fff&text_color=fff)
> ```

Ohhh, thank you!!

**Comment by Eldrick99** [comment]
Welcome!

**Comment by Johann-Goncalves-Pereira** [comment]
This helps me a lot.

**Comment by QuachRTX** [comment]
thank you
