### ISSUE TITLE
After my commit count crossed 1600 for 2020 it was still showing 1.5k - there's seems to be a lag in updating this number from 1.5k to 1.6k

### ISSUE THREAD

**Issue by rohan-paul** [anuraghazra/github-readme-stats#503]
**Describe the bug**

After my commit count for 2020 crossed today the number 1600 - the **Total commits** was still showing 1.5k

![image](https://user-images.githubusercontent.com/12703975/94367116-29521000-00fa-11eb-91f8-4d59ccf91e88.png)

But after my commit count for 2020 crossed beyond 1603 - only then the **Total commits** correctly showed 1.6k.

**Comment by anuraghazra** [comment]
Please not that there is a 2hour cache so it just takes time to update.

**Comment by rohan-paul** [comment]
Ahh.. I see. Cool, then that explains the lag. Thanks for the reply. Closing it.
