### ISSUE TITLE
[Feature Request] Compact Wakatime Card

### ISSUE THREAD

**Issue by nthnchu** [anuraghazra/github-readme-stats#504]
**Is your feature request related to a problem? Please describe.**
There should be a compact wakatime card, just like the compact top langs card.

**Describe the solution you'd like**
Reuse some code from the compact top langs card to make the compact wakatime card look similar.

**Describe alternatives you've considered**
N/A

**Additional context**
N/A

**Comment by WillianRod** [comment]
I'll work on that

**Comment by nthnchu** [comment]
Closed by #560
