### ISSUE TITLE
Translations for Cards

### ISSUE THREAD

**Issue by nthnchu** [anuraghazra/github-readme-stats#508]
**Is your feature request related to a problem? Please describe.**
Many people that use github-readme-stats speak other languages. There are translations of the docs for this reason, but no translations for the cards.

**Describe the solution you'd like**
A query parameter like `?lang=EN`.

**Describe alternatives you've considered**
Most people's READMEs that I've seen just show the cards in english.

**Additional context**
I'm already working on a PR. I only know english, so if you have translations, please comment on this issue.

### Full List of words needing to be Translated:
* Template
* Archived
* [name]'s GitHub Stats
* Total Stars
* Total Commits
* Total Issues
* Total PRs
* Contributed to
* Most Used Languages
* Wakatime Week Stats
* No coding activity this week

**Comment by anuraghazra** [comment]
Awesome @nthnchu yeah I think this feature would be really nice. we can have a localization object and get the alternative texts from there.

Anyone want to help @nthnchu  with the translations? ping! @nombrekeff @qwerty541 @lrusso96 @ooobsidian @jalenchuh

**Comment by nombrekeff** [comment]
Yeah sure, I don't have much time lately but I can help with the ES translations on the weekend.

**Comment by anuraghazra** [comment]
Awesome thanks @nombrekeff will ping you once nthnchu makes the PR

**Comment by nombrekeff** [comment]
That would be great, thanks!

**Comment by qwerty541** [comment]
> Awesome @nthnchu yeah I think this feature would be really nice. we can have a localization object and get the alternative texts from there.
> 
> Anyone want to help @nthnchu with the translations? ping! @nombrekeff @qwerty541 @lrusso96 @ooobsidian @jalenchuh

I can make translations into Russian and Ukrainian languages if needed

**Comment by jalenchuh** [comment]
I can help with the Chinese translations.

**Comment by schmelto** [comment]
Can help with German how can I contribute?

**Comment by lrusso96** [comment]
> Can help with German how can I contribute? 

Hi @schmelto, you should open a PR similar to [this one](https://github.com/nthnchu/github-readme-stats/pull/1).

**Comment by anuraghazra** [comment]
I'll be taking a look at this PR this weekend.

**Comment by harshhh-dev** [comment]
This is cool! I can help with Spanish and Hindi :)

**Comment by nombrekeff** [comment]
> This is cool! I can help with Spanish and Hindi :)

@harshhh-dev I was gonna do it this weekend but If you can do it, that would be great, I can revise it afterward if you'd like. (_I'm spanish btw_)
