### ISSUE TITLE
Wakatime card: "No coding activity this week"

### ISSUE THREAD

**Issue by nthnchu** [anuraghazra/github-readme-stats#515]
**Describe the bug**
The wakatime card displays "No coding activity this week"

**Expected behavior**
The card woud show the same stats as https://wakatime.com/@nthnchu

**Screenshots / Live demo link (paste the github-readme-stats link as markdown image)**
[![Wakatime Week Stats](https://github-readme-stats.vercel.app/api/wakatime?username=nthnchu)](https://github.com/anuraghazra/github-readme-stats)

**Additional context**
It's a new wakatime account so that might be the issue. It also works on my own vercel deployment (see my readme), but I still think that this is odd.

**Comment by nthnchu** [comment]
Never mind; It fixed itself somehow

**Comment by benihime91** [comment]
Even I am facing the same issue ... My dashboard in Wakatime shows stats that's not reflected in my github readme. 
@nthnchu  How'd you fix it ?

**Comment by nthnchu** [comment]
@benihime91 try going to https://wakatime.com/settings/profile, and checking the boxes "Display coding activity publicly" and "Display languages, editors, operating systems publicly". Does that work?

**Comment by benihime91** [comment]
@nthnchu Yeah it's working now thanks...

**Comment by HocheolJang** [comment]
@nthnchu Awesome.

**Comment by emondd4** [comment]
**even it wont work if you dont go on public leaderboard.**

**Comment by Sciroccogti** [comment]
> **even it wont work if you dont go on public leaderboard.**

This does don't work for me and I can't find myself on the public leaderboard. Is there anything else left to check?

**Comment by nathanchu** [comment]
Checking that your profile is publicly accessible by going to wakatime.com/@<your wakatime username> while signed out of wakatime will show whether it is a wakatime or github-readme-stats bug

**Comment by Sciroccogti** [comment]
Well mine is solved by **changing Display code time publicly to the default (Last 7 Days)** as mentioned here: https://github.com/anuraghazra/github-readme-stats/issues/838#issuecomment-774042124

**Comment by xun-girl** [comment]
I've completed my public activity, but I'm not a lawful person.
this is me
![image](https://user-images.githubusercontent.com/80450946/161429194-0d69c24c-6fe8-4ecc-aa14-5f2d7c6229ea.png)

**Comment by xun-girl** [comment]
@benihime91 How did you solve it, can you show me the code for that piece?

**Comment by Bogdan-Mykhailov** [comment]
@benihime91 try to add @ before your name
