### ISSUE TITLE
Divulgation Post- Karanalpe

### ISSUE THREAD

**Issue by karanalpe** [anuraghazra/github-readme-stats#517]
Hello,

I have a [blog](https://karanalpe.com.br/) and I wrote about Readme Stats in Portuguese. See in https://karanalpe.com.br/tecnologia/como-customizar-o-github-com-o-readme-stats/.

**Comment by anuraghazra** [comment]
Nice @karanalpe thanks for writing about github-readme-stats!

**Comment by anuraghazra** [comment]
Closing this :)
