### ISSUE TITLE
My stats aren't updating

### ISSUE THREAD

**Issue by Mad880** [anuraghazra/github-readme-stats#519]
My stats don't update, for example i have starred 9 repositories but it shows as 6
and the total commits count is wrong

I expected to give the right stats, that's the main reason why i use it but it's not accurate at all.

I would appreciate if you guys fix it or tell me if its intentional.

**Comment by anuraghazra** [comment]
It does not show how many repo you've **starred** it shows how many stars you **gained** 

Also.. There is 2 hour cache so it takes time to update. 

Please give more info about what do you mean by commit counts aren't right.

**Comment by Mad880** [comment]
I thought contributes and commits are the same thing... Thanks for helping me with the star thing though, i was so confused about how it works. Now i know at least. Thanks again

**Comment by panosru** [comment]
@anuraghazra I see there are a lot of similar issues and I don't want to open an issue, so I will comment here. I have the same issue but I have waited for 12+ hours and I haven't seen any update on the top languages widget. I placed `exclude_repo=repo-one,repo-two,etc` and normally the top languages stats should've been updated, but after 12 hours or so, they are not.

I have forked your repo and deployed it in vercel just in case your's reach the requests limit. If I delete the app from vercel and then redeploy it, then the widget is getting new values but then it is stuck with those, I guess that shouldn't be normal, yes?

Thank you for the awesome plugin!

**Comment by asrivastav-aag** [comment]
My stats are not updating. I've done more than 10 commits and contributing to 2 repos, but its showing total 6 commits and 0 contributions.
Thanks to look into this.

<img width="507" alt="image" src="https://user-images.githubusercontent.com/110137595/196798197-c9a2efdc-b777-4fd5-8600-f04ce015fd1b.png">

**Comment by rickstaa** [comment]
@asrivastav-aag Thanks for your question. We use caching to reduce our server load. Stats are updated every 4 hours (see https://github.com/anuraghazra/github-readme-stats#common-options).

**Comment by asrivastav-aag** [comment]
> @asrivastav-aag Thanks for your question. We use caching to reduce our server load. Stats are updated every 4 hours (see https://github.com/anuraghazra/github-readme-stats#common-options).

Thank you for the details!

**Comment by Sugarcothe** [comment]
![lol](https://user-images.githubusercontent.com/63057848/209084391-f6de7867-e995-464b-a3c5-e22c2f4a431a.png)
why is Github stat telling me i wrote more python, when i have done multiple projects in NodeJs. This cant be correct

**Comment by rickstaa** [comment]
> 

This issue is caused by limitations in the GraphQL API. We are working on solving this (see #1801).

**Comment by asrivastav-aag** [comment]
Stats are showing wrong data. I've done 23 commits in 2023 till yet, but stats says 77 commits.

![image](https://user-images.githubusercontent.com/110137595/211746598-fe3b38cc-7c7e-4548-b480-efc7ed751dab.png)

**Comment by hywing** [comment]
I got the same problem too.

**Comment by DhyegoTourinho** [comment]
Ninguém consegui consertar?

**Comment by qwerty541** [comment]
Currently we have 24 hours default cache timing on our public deployment. In case you want your cards to be updated more often you can [deploy own Vercel instance](https://github.com/anuraghazra/github-readme-stats?tab=readme-ov-file#deploy-on-your-own) using own GitHub API key. There you will be able to set `CACHE_SECONDS` environment variable with any positive integer.
