### ISSUE TITLE
Github Extra Pins | Doesn't work if a repository has no code language.

### ISSUE THREAD

**Issue by MirayXS** [anuraghazra/github-readme-stats#52]
## Github Extra Pins | Doesn't work if a repository has no code language.

Title. I was trying to get the image for my repository (With no code language, it's only images and a readme) [[this]](https://github-readme-stats.vercel.app/api/pin/?username=MirayXS&repo=MirayAPI) but i don't get an image, yet i get a **Application Error**. You can see more info if you click on the link. I also tried with another repository with no code language, same error.

**Comment by anuraghazra** [comment]
Thanks for reporting the bug @MirayXS i'll look into this tomorrow.

I think this is the reason why `?username=anuraghazra&repo=anuraghazra` does not work

**Comment by MirayXS** [comment]
exactly, the other repository i tried before was my own repository like yours (the new github function for the profile-readme) it usually only has the README.md file so it doesn't have code language

**Comment by MirayXS** [comment]
👍
