### ISSUE TITLE
[Feature Request]: Total views

### ISSUE THREAD

**Issue by nthnchu** [anuraghazra/github-readme-stats#545]
**Is your feature request related to a problem? Please describe.**
I've seen many readme widgets count the total views of the user's readme. Could this be added to github readme stats?

**Describe the solution you'd like**
It could be put as either another part of the stats card (Total Views) or could be at an api endpoint (/api/views).

**Describe alternatives you've considered**
https://github.com/antonkomarev/github-profile-views-counter
profile-counter.glitch.me

**Additional context**
It could use redis and lambda store to persist data. Since lambda store is paid for more than 5,000 requests per day (and github readme stats has twice as many stars as that), this could be a user deployment only feature. Another feature which is kind of related that I think would be interesting is analytics (to count the amount of requests to github readme stats per day.

**Comment by anuraghazra** [comment]
Closing this in favor of https://github.com/anuraghazra/github-readme-stats/issues/43#issuecomment-658834845
