### ISSUE TITLE
Resume website.io attachment

### ISSUE THREAD

**Issue by AtulSisodiya** [anuraghazra/github-readme-stats#546]
I have added website to the github card but it is showing no description whereas i have readme file in it

**Comment by anuraghazra** [comment]
Readme file is not the description of the repo.

**Comment by AtulSisodiya** [comment]
so bro how to change it

**Comment by anuraghazra** [comment]
Add a description in repo

**Comment by AtulSisodiya** [comment]
already added but showing no description provided.

**Comment by anuraghazra** [comment]
Give example. otherwise i can't see/investigate the issue

**Comment by AtulSisodiya** [comment]
you can check my profile.

**Comment by AtulSisodiya** [comment]
https://github.com/AtulSisodiya

**Comment by anuraghazra** [comment]
Try changing that Link to something other than the URL

**Comment by AtulSisodiya** [comment]
Showing same even after changing the description

**Comment by anuraghazra** [comment]
It has 2h cache you have to wait for a bit i guess

**Comment by AtulSisodiya** [comment]
thankyou for response and great work bro can you help me how to improve in javascript and get internship in web application development field.

**Comment by anuraghazra** [comment]
You can join our discord server or ping me on twitter for any further questions / information.

https://discord.gg/VK4k3Br
https://twitter.com/anuraghazru

**Comment by anuraghazra** [comment]
Hi Atul thanks for opening the issue, I hope you get your question resolved. closing this for now. feel free to open another one for further queries.
