### ISSUE TITLE
Off-centered user rank

### ISSUE THREAD

**Issue by MicaelJarniac** [anuraghazra/github-readme-stats#55]
The user rating ("A", in this example) inside the progress circle is off-center, a bit off to the right of the circle's center.

![](https://i.imgur.com/l7joRW7.png)

Above is a static screenshot. Here's it live:

![](https://github-readme-stats.vercel.app/api?username=MicaelJarniac&show_icons=true&title_color=fff&icon_color=79ff97&text_color=9f9f9f&bg_color=151515)

The URL that generated it is `https://github-readme-stats.vercel.app/api?username=MicaelJarniac&show_icons=true&title_color=fff&icon_color=79ff97&text_color=9f9f9f&bg_color=151515` (I used the dark mode preset)

**Comment by infinity-plus** [comment]
Same issue with me too, on light mode instead

**Comment by ApurvShah007** [comment]
The portfolio card is down for me too. I have used the light mode.

**Comment by anuraghazra** [comment]
Thanks for reporting the issue @MicaelJarniac i'll look into it and resolve it.
