### ISSUE TITLE
Add an image as a background in readme stats card

### ISSUE THREAD

**Issue by Dhruv-194** [anuraghazra/github-readme-stats#550]
**Add an image as a background to github readme stats card**
There can be a customization option of adding an image as the background of the stats card. Similar to the available themes there should also be themes with some cool background images. 

**Describe the solution you'd like**
The solution to this can be - just like the way we can customize the bg_color of stats card in the same way there should be a method by which we can apply a bg_image to stats card. Also there can be themes which has some cool images as the background, and let these themes be editable for applying custom image backgrounds.

**Describe alternatives you've considered**
No alternatives found yet.

**Additional context**
If there is already a way by which we can apply this feature then kindly please tell or mention it in the readme.

**Comment by susanta96** [comment]
Working on it ... But It already have gradient support and you can use it to make beautiful design as well.

**Comment by susanta96** [comment]
> Working on it ... But It already have gradient support and you can use it to make beautiful design as well.

![image](https://user-images.githubusercontent.com/29665000/95264652-5b2b4b00-084d-11eb-9b8b-da6d6efae1ce.png)

**Comment by nthnchu** [comment]
@susanta96 The odd thing that happened when I tried was that the image wouldn't work after embedding in markdown as svg, but would work in the browser. I had a similar issue with custom fonts, and the only way was to encode the images as base64. The solution here would then be to request images server side but that's quite slow.

**Comment by susanta96** [comment]
Same here... It would request the image that's take time if it's a large image.  Browser  the  dom and make a request for the image but not in markdown.
