### ISSUE TITLE
Add m sign

### ISSUE THREAD

**Issue by donno2048** [anuraghazra/github-readme-stats#556]
I think this thing speaks for itself:
<img width="167" alt="Screenshot 2020-10-06 180105" src="https://user-images.githubusercontent.com/61805754/95219369-f7c5fc80-07fd-11eb-9912-d4d329384c21.png">
it would be great to be able to use the m letter for a million or to be able to show to the whole count (or both)

**Comment by cxong** [comment]
https://www.npmjs.com/package/d3-format seems like a nice library to use for this
