### ISSUE TITLE
Add languages when hiding others

### ISSUE THREAD

**Issue by donno2048** [anuraghazra/github-readme-stats#557]
If I use `hide=c%2B%2B` for example, the maximum languages I can show in the language card is 9...

**Comment by anuraghazra** [comment]
Hi @donno2048 note that if you don't have lot of languages there is no way to fetch them.

**Comment by donno2048** [comment]
I have more than 10, for sure.

**Comment by donno2048** [comment]
Oops, this is because it won't look at my actual code files but rather the repository's language
