### ISSUE TITLE
Misaligned text and emojis

### ISSUE THREAD

**Issue by MicaelJarniac** [anuraghazra/github-readme-stats#56]
Emojis seem to be inconsistently sized, and that causes text following it to not end up left-aligned as it should be. The emojis themselves also seem misaligned.

![](https://i.imgur.com/l7joRW7.png)

![](https://i.imgur.com/Un6NDxN.png)

I believe an "easy" solution (or workaround, I should say) for this would be to have the emojis and the actual text in different "layers", with the text layer further to the right, so that the text can be left-aligned on its own layer, and the emojis can be centered on their layer, one not affecting the other.

I've tried to diagram what I meant:

![](https://i.imgur.com/eDYQDEH.png)

**Comment by MicaelJarniac** [comment]
After posting this issue I noticed #33 seems to be fixing this exact thing.

**Comment by anuraghazra** [comment]
Thanks for the detailed information and the issue @MicaelJarniac 

Yes #33 is fixing it but i had planned a better option to use SVG icons instead of ASCII icons #34 so that it'll be consistent but the current approach wont work because <tspan> tags don't render any svg contents inside them

**Comment by anuraghazra** [comment]
fixed in #33
