### ISSUE TITLE
count_private not adding private commits to total commits

### ISSUE THREAD

**Issue by Syntle** [anuraghazra/github-readme-stats#563]
**Describe the bug**
count_private being set to true doesn't private commits add to the total number of commits

**Expected behavior**
count_private being set to true adds private commits to the total number of commits

**Screenshots / Live demo link (paste the github-readme-stats link as markdown image)**
![1](https://github-readme-stats.vercel.app/api?username=syntle&show_icons=true&theme=dark&include_all_commits=true&count_private=true&hide_border=true)

**Additional context**
The live demo above shows I got 35 commits but after I checked my repos, I think I have around 400+

I also tried this with my own vercel instance.

**Comment by regisnew** [comment]
Same with me

**Comment by Syntle** [comment]
Closing this because I found the fix, you need to publicise your private contributions, you can do so by following [this guide](https://docs.github.com/en/free-pro-team@latest/github/setting-up-and-managing-your-github-profile/publicizing-or-hiding-your-private-contributions-on-your-profile)
