### ISSUE TITLE
调整图片宽度 | Adjust the width of the picture

### ISSUE THREAD

**Issue by jwjawa** [anuraghazra/github-readme-stats#575]
这是一个很棒的项目，我已经给你们点了star :+1: 
我希望可以添加一个选项，可以调整图片的宽度，因为如果图片的大小不合适可能会看起来让人不舒服。
[比如这个项目](https://github.com/wao3/luogu-stats-card)，在这里选项的设置方法是`&card_width=750`
希望你们能采纳我的建议。

---

This is a great project, I have ordered star for you. :+1: 
I'd like to add an option to adjust the width of the picture, because it might look uncomfortable if it doesn't fit.
[e.g. this project](https://github.com/wao3/luogu-stats-card), the option here is set by `&card_width=750`.
I hope you will take my advice.

**Comment by anuraghazra** [comment]
Hi @jwjawa thanks for the feature request. 

related to #65 #110
