### ISSUE TITLE
Rank is off-center

### ISSUE THREAD

**Issue by adamalston** [anuraghazra/github-readme-stats#580]
It appears that the rank is off-center both vertically and horizontally relative to the progress circle.

Screenshot
<img height="137px" src="https://user-images.githubusercontent.com/18297826/96355050-80b91f80-10ab-11eb-9e49-8fdfea19dad4.png" />

Live
<img align="" height="137px" src="https://github-readme-stats.vercel.app/api?username=adamalston&hide_title=true&hide_border=true&show_icons=true&include_all_commits=true&line_height=21&bg_color=0,EC6C6C,FFD479,FFFC79,73FA79&theme=graywhite" />

URL: `<img height="137px" src="https://github-readme-stats.vercel.app/api?username=adamalston&hide_title=true&hide_border=true&show_icons=true&include_all_commits=true&line_height=21&bg_color=0,EC6C6C,FFD479,FFFC79,73FA79&theme=graywhite" />`

**Comment by anuraghazra** [comment]
Hi @adamalston thanks for reporting the issue, we will look into it.

related to #55

**Comment by vSanjo** [comment]
Hey @anuraghazra, (and @adamalston!). 
I've pushed a small PR towards fixing this for you. It looks like some minor logic was pulling the information both ways - and I'd argue it isn't required providing the width of the `text` element is big enough. 

Hopefully that helps!

**Comment by adamalston** [comment]
I think this issue should be reopened
