### ISSUE TITLE
The graph doesn't show Dart statistics

### ISSUE THREAD

**Issue by jjeanjacques10** [anuraghazra/github-readme-stats#582]
**Describe the bug**
I connected the GitHub readme stats, but my Flutter repositories didn't show on stats. I tried to hid Python and the other languages, but Dart didn't show it even doing that.

**Expected behavior**
The Dart stats show.

**Screenshots / Live demo link (paste the github-readme-stats link as markdown image)**
![image](https://user-images.githubusercontent.com/32225403/96458623-815ecc80-11f7-11eb-9c16-7d251e35210c.png)

**Comment by anuraghazra** [comment]
Your repos are private

**Comment by jjeanjacques10** [comment]
Some are private, but most are not private. Look: 

https://github.com/jjeanjacques10?tab=repositories&q=&type=&language=dart

11 public repositories

**Comment by anuraghazra** [comment]
Most of them are forks too, which we don't count. also FYI that it does not matter if you have 100 repos with dart because we count by language code by bytes. so more code means it will be in the top.

@Bas950 in implementing a feature to add forks #505

**Comment by jjeanjacques10** [comment]
There are 4 forks, most of them are still valid, doesn't? 

If I hide the other languages, should the dart show? Because I did it and nothing...

https://github-readme-stats.vercel.app/api/top-langs/?username=jjeanjacques10&hide=html,TSQL,CSS,python,JavaScript,PHP,Jupyter%20Notebook&layout=compact&count_private=true

**Comment by anuraghazra** [comment]
You have huge amount of Python code in here https://github.com/jjeanjacques10/chatbot-whatsapp/tree/master/venv this is why python overtake the values and dart didn't even make it to the list. 

https://github.com/jjeanjacques10/chatbot-whatsapp/tree/master/venv

**Comment by jjeanjacques10** [comment]
Thank you! I am excluding this venv. But the dart has not yet appeared... I will look for other venv on my GitHub.
