### ISSUE TITLE
Status cards rendering on Chrome but not on Safari.

### ISSUE THREAD

**Issue by ApurvShah007** [anuraghazra/github-readme-stats#59]
I can't seem to see the status cards on safari. Is this for everyone or just me?

**Comment by anuraghazra** [comment]
@ApurvShah007 can you give me more info on your System? Browser version, OS etc etc

**Comment by ApurvShah007** [comment]
My laptop is on macOS Catalina v-10.15.4 and my Safari is on Version 13.1 (15609.1.20.111.8). I don't know if that helps, but I can go to chrome and open the same link and everything loads fine.

**Comment by anuraghazra** [comment]
Yup it's a safari rendering issue. i'll see what i can do, thanks for reporting

**Comment by filiptronicek** [comment]
This is how it looks on my phone if it helps in any way: ![image](https://user-images.githubusercontent.com/29888641/87778158-0fa76900-c82b-11ea-9d1f-ccee6409088d.png)

**Comment by anuraghazra** [comment]
@filiptronicek can you confirm that the animations are running? it could be possible that the animation is not running in @ApurvShah007's browser that why its blank

**Comment by ApurvShah007** [comment]
@anuraghazra  thats exactly how it looks on Safari on my laptop and iPhone. I think its the animations that wont render. The stats and other icons render fine. 
It works fine on my android phone on chrome and my laptop on chrome.

**Comment by filiptronicek** [comment]
The animations are indeed running, but the rank doesn't load.

**Comment by ApurvShah007** [comment]
Also Congrats on 1000 ⭐️

**Comment by filiptronicek** [comment]
https://files.catbox.moe/w36wsp.mp4 - how it looks like on my end

**Comment by anuraghazra** [comment]
> The animations are indeed running, but the rank doesn't load.

Ohhhh, okay. the issue is i can't debug this properly.. since i dont have any safari browser or apple devices :(

**Comment by filiptronicek** [comment]
Try Browserstack, it's free for OSS! @anuraghazra 

> 
> 
> > The animations are indeed running, but the rank doesn't load.
> 
> Ohhhh, okay. the issue is i can't debug this properly.. since i dont have any safari browser or apple devices :(

**Comment by edisonlee55** [comment]
I can also reproduce this issue on Chrome iOS.

It might be something to do with WebKit, cause Chrome iOS is using WebKit the same as Safari instead of Blink in other Chrome versions.

---

![IMG_0717](https://user-images.githubusercontent.com/5277788/87787256-e825c000-c86d-11ea-9b79-9ea7e42c4b73.jpg)

**Comment by ApurvShah007** [comment]
Yes I can confirm that's it's an iOS / MacOs issue.
