### ISSUE TITLE
Please add more languages in Language stats cards

### ISSUE THREAD

**Issue by arshsaxena** [anuraghazra/github-readme-stats#591]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by anuraghazra** [comment]
@arshsaxena please add more information about what you want and what issue you are facing, and what do you mean by "add more languages in Language stats cards"

**Comment by arshsaxena** [comment]
@anuraghazra your work is great. I was saying that the language card displays only 5 languages, make changes to so that more languages can be displayed.

**Comment by anuraghazra** [comment]
> @anuraghazra your work is great. I was saying that the language card displays only 5 languages, make changes to so that more languages can be displayed.

You don't have enough code in your github repos which it can display. if you have other langs it will show.

**Comment by arshsaxena** [comment]
Maximum languages it can display?

**Comment by harshhhdev** [comment]
It is 5 on the compact layout I believe.
