### ISSUE TITLE
Inaccurate Total Commit Number.

### ISSUE THREAD

**Issue by MattMarquise** [anuraghazra/github-readme-stats#593]
A simple bug with inaccurate total commits number.
It should be displaying the total number of commits for current year (currently 2020). Anyone else experiencing this?

**Comment by harshhhdev** [comment]
I believe it only counts public contributions...

![image](https://user-images.githubusercontent.com/69592270/97514071-429de480-1964-11eb-8957-57213a8275ce.png)

Here it shows you have 641 contributions, but going in and doing the math for all your repositories 

Profile readme - 103
SaplingOS - 259
CS50 course - 133
Covid-19-Testing-Program - 20 
WebBased-Social-Media-App - 22
CS50x-Web-Programming-with-Python-and-JavaScript-2020 - 5
COVID-DATA-COLLECTION - 8
Basic-software - 6

This totals out to 555, and then if you add your contributions to forked repositories, etc. it becomes 588, which is your stat count.

**Comment by MlgmXyysd** [comment]
same

**Comment by MattMarquise** [comment]
@harshhhdev Makes sense. thank you for helping me understand this
