### ISSUE TITLE
Bug: theme algolia commit stuck at 122

### ISSUE THREAD

**Issue by helloshantanu** [anuraghazra/github-readme-stats#596]
**Describe the bug**
I am using Readme stats for my github profile but the commits in theme algolia are stuck in 122 and by using other themes my commits are increasing.

**Expected behavior**
i expect it to increase

**Screenshots / Live demo link (paste the github-readme-stats link as markdown image)**

**Additional context**

**Comment by anuraghazra** [comment]
No it's not :p 

![image](https://user-images.githubusercontent.com/35374649/97398751-bb278580-1911-11eb-9437-55a915cc91cd.png)


There's min of 2hour cache btw.
I hope that resolved you question, closing this now.

**Comment by helloshantanu** [comment]
got it thanks
