### ISSUE TITLE
Question ? Anyone knows the algorithm to calculate Top languages

### ISSUE THREAD

**Issue by Zrealshadow** [anuraghazra/github-readme-stats#597]
😥  Not javascript programmer...
I am just curious about the algoritmn to select top langugaes. but there is no explaination on readme.
most of my repositories are created using python. 
But in card, C++ is the top language.
Just Curious 😹  Anyone can explain it

**Comment by qwerty541** [comment]
> disappointed_relieved Not javascript programmer...
> I am just curious about the algoritmn to select top langugaes. but there is no explaination on readme.
> most of my repositories are created using python.
> But in card, C++ is the top language.
> Just Curious joy_cat Anyone can explain it

Currently the top languages are calculated based on how much code in bytes you have in a particular language. You can have 10 repositories created using Python and only one with C++, but if repository with C++ contains more code than 10 with Python, than it will be in the top of your language card.

**Comment by anuraghazra** [comment]
> Currently the top languages are calculated based on how much code in bytes you have in a particular language. You can have 10 repositories created using Python and only one with C++, but if repository with C++ contains more code than 10 with Python, than it will be in the top of your language card.

I really need to create a `Saved reply` for this one

**Comment by Zrealshadow** [comment]
> > disappointed_relieved Not javascript programmer...
> > I am just curious about the algoritmn to select top langugaes. but there is no explaination on readme.
> > most of my repositories are created using python.
> > But in card, C++ is the top language.
> > Just Curious joy_cat Anyone can explain it
> 
> Currently the top languages are calculated based on how much code in bytes you have in a particular language. You can have 10 repositories created using Python and only one with C++, but if repository with C++ contains more code than 10 with Python, than it will be in the top of your language card.

Thanks !

**Comment by W8jonas** [comment]
The problem is: If i create a hello world in Jupyter Notebook (1 line of code) and then create a hello world in a .py file the result of the statistics is:
90% Jupyter Notebook and 10% Python

Of course, this makes no sense in the calculation.
