### ISSUE TITLE
[Feature request] add instructions for implementing the stats card in HTML

### ISSUE THREAD

**Issue by harshhhdev** [anuraghazra/github-readme-stats#599]
# Is your feature request related to a problem? Please describe.
There is only currently a tutorial on how to add markdown support in the documentation.

# Describe the solution you'd like
Add HTML support, and a guide in readme on how to do this.

# Additional context
If you decide to go ahead with this, can I update the docs and add it in?

**Comment by itzTheMeow** [comment]
but it's literally the same, just an img tag and not markdown...

**Comment by anuraghazra** [comment]
Hi @harshhhdev i think we don't need that. it's already pretty straight forward and we do have examples too.
