### ISSUE TITLE
Close old issues

### ISSUE THREAD

**Issue by nthnchu** [anuraghazra/github-readme-stats#613]
The project has many old and stale issues and PRs. I don't know if it helps, but I've gathered a list of some issues that are duplicates, fixed, questions that have been answered, wontfixes, and etc. that I think should be closed. Here it is:
#609 (duplicate)
#517 (answered)
#507 (duplicate)
#446 (answered/wontfix)
#414 (duplicate)
#259 (answered/duplicate)
There are also many duplicate bug reports, rank questions, and top-lang bug reports.
As far as PRs go there are a lot of [theme] PRs still open (33 right now)
If there is any way I can help please tell me, for now it makes it hard for me to decide which issues I should work on, which are rejected, and which are duplicates. If you could close these that would make the issues and PRs less cluttered.

**Comment by anuraghazra** [comment]
Wow Thanks for triaging the issues @nthnchu it was really helpful. i lost track of them :D there are some issues which i think could be open until resolved but i closed most of them

**Comment by anuraghazra** [comment]
btw feel free to hop into our discord server we can discuss about triaging and all the issues there too!

https://discord.gg/S8ufX3R

**Comment by nthnchu** [comment]
Just wondering, are you planning to enable GitHub discussions on this repository? It fits all of the requirements mentioned at <https://github.community/t/can-one-apply-for-github-discussions-beta/121120/376> to sign up for the beta:
* Public
* > 3 contributors 
* Not Empty
