### ISSUE TITLE
locale=id for Indonesia not found

### ISSUE THREAD

**Issue by nubbdev** [anuraghazra/github-readme-stats#619]
hi, @anuraghazra thank you for the beautiful Github stats. I searching **locale** for my country Indonesia (code=id) are not found.

**Comment by nthnchu** [comment]
@nubbdev As of right now we don't appear to have translations for Indonesia. If you'd like, you could translate them and submit a PR.

**Comment by nubbdev** [comment]
yeah, I see the source right now and can't find id locale. Maybe I wanna a fork for this one!

**Comment by nubbdev** [comment]
#621
