### ISSUE TITLE
Hello,

### ISSUE THREAD

**Issue by cachecleanerjeet** [anuraghazra/github-readme-stats#622]
Hello, @anuraghazra Da,
I also created a project like this: Have a look 😊
https://github.com/cachecleanerjeet/readme-stats-github

**Comment by anuraghazra** [comment]
Awesome work @cachecleanerjeet card looks nicer with profile picture! 
Would be a nice optional feature to add in our card as well :D

**Comment by cachecleanerjeet** [comment]
Thank you, you are the inspiration 🥰

**Comment by cachecleanerjeet** [comment]
I think commits and issues counts are not accurate
