### ISSUE TITLE
Permission android 

### ISSUE THREAD

**Issue by jackiebrewster307** [anuraghazra/github-readme-stats#628]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by jackiebrewster307** [comment]
Root permissions

**Comment by nthnchu** [comment]
@jackiebrewster307 could you please provide more details?

**Comment by nthnchu** [comment]
@anuraghazra I think this is spam. If not please elaborate @jackiebrewster307.

**Comment by anuraghazra** [comment]
closing this as invalid
