### ISSUE TITLE
Root permissions

### ISSUE THREAD

**Issue by jackiebrewster307** [anuraghazra/github-readme-stats#629]
Root permissions 

_Originally posted by @jackiebrewster307 in https://github.com/anuraghazra/github-readme-stats/issues/628#issuecomment-723513846_

**Comment by nthnchu** [comment]
@anuraghazra I think this is spam. If not please elaborate @jackiebrewster307.

**Comment by anuraghazra** [comment]
Let's give him a chance to reply. Then we will close it.

**Comment by anuraghazra** [comment]
closing this as invalid
