### ISSUE TITLE
Wakatime card doesn't show my stats

### ISSUE THREAD

**Issue by Khelthos** [anuraghazra/github-readme-stats#632]
Hi,
There seems to be something not working as it should, I thought it was an update latency problem, but after a week I still don't see Wakatime's data updated on the card.

From my dashboard and bees Wakatime, there are the data:
[https://wakatime.com/api/v1/users/khelthos/stats/last_7_days](https://wakatime.com/api/v1/users/khelthos/stats/last_7_days)

But when I use the card, I have this result:
[https://github-readme-stats.vercel.app/api/wakatime?username=khelthos&layuout=compact&theme=synthwave](https://github-readme-stats.vercel.app/api/wakatime?username=khelthos&layuout=compact&theme=synthwave)

Is it possible that there are problems?
Am I wrong in some way?

I haven't seen anyone with the same problem so I might be in the wrong.

Thanks

**Comment by mdeboute** [comment]
Hi, you might be able to fix it by adding &v=2 to the end of the card url so your browser is forced to re-request it !

**Comment by Khelthos** [comment]
Solved, thank you @mdeboute

**Comment by ThiagoAnd** [comment]
> Hi @Khelthos, try going to https://wakatime.com/settings/profile, and checking the boxes "Display coding activity publicly" and "Display languages, editors, operating systems publicly" moreover you might be able to fix it by adding &v=2 to the end of the card url so your browser is forced to re-request it!

Hi, on the start, the &v=2 worked, but now my stats don't update, the option Display coding, and Display languages are checked.

**Comment by Vladyan-dev** [comment]
> > Hi @Khelthos, try going to https://wakatime.com/settings/profile, and checking the boxes "Display coding activity publicly" and "Display languages, editors, operating systems publicly" moreover you might be able to fix it by adding &v=2 to the end of the card url so your browser is forced to re-request it!
> 
> 
> 
> Hi @mdeboute, on the start, the &v=2 worked, but now my stats don't update, the option Display coding, and Display languages are checked.
> 
> 

I have the same problem:(

**Comment by gokul-369** [comment]
I too have the same problem

**Comment by Sangeerththan** [comment]
I too have the Same Problem although as you mentioned  "Display coding activity publicly" and "Display languages, editors, operating systems publicly" moreover you might be able to fix it by adding &v=2 to the end of the card url so your browser is forced to re-request it!."
@Khelthos I have  made the above change but still the weekly stats are not shown.

**Comment by amgauna** [comment]
<img src="https://github-readme-stats.vercel.app/api/wakatime/?&USERNAME&layout=compact&&theme=default&link=https://www.github.com/USERNAME/">

**Comment by SushiWaUmai** [comment]
Having the same issue, despite trying all steps from above.

**Comment by w3samiulazim** [comment]
same problem.

**Comment by stperrakis** [comment]
It seems that there is a bug, because I make to share publicly my activity but nothing change at all.
To be specific, it says: This user has no coding activity, or has privacy settings that prevent showing it.

![image](https://github.com/anuraghazra/github-readme-stats/assets/26480407/c170a96a-c17d-4bf2-93ce-32ce4bf7d557)

**Comment by rickstaa** [comment]
[![Harlok's wakatime stats](https://github-readme-stats.vercel.app/api/wakatime?username=stperrakis)](https://github.com/anuraghazra/github-readme-stats)

**Comment by stperrakis** [comment]
It seems to be a bug since I have already configured it to share publicly my stats.

**Comment by stperrakis** [comment]
My case: I have a new profile in Wakatime, and it seems did not collect weekly data.

I've found a solution. If you're new to Wakatime like me, go to Settings -> Personal Preferences -> Set Default range to Today, and then switch back to your preferred range.

Hope it works for you ✌️

**Comment by reevee-codes** [comment]
I have exactly the same problem, and stperrakis's hint did nothing for me unfortunately.
