### ISSUE TITLE
Does not correctly count the number of commits for the current year

### ISSUE THREAD

**Issue by andrey-helldar** [anuraghazra/github-readme-stats#634]
**Describe the bug**
Does not correctly count the number of commits for the current year

**Expected behavior**
In the line "Total Commits (2020)" I want to see the real number of commits for 2020.

**Screenshots / Live demo link (paste the github-readme-stats link as markdown image)**

16 September 2020:
![image](https://user-images.githubusercontent.com/10347617/98651992-0b5c0a00-234c-11eb-861e-583e3774b946.png)

29 September 2020:
![image](https://user-images.githubusercontent.com/10347617/98651900-e9fb1e00-234b-11eb-9cdc-5c57b7939e0a.png)

10 November 2020:
![image](https://user-images.githubusercontent.com/10347617/98651948-fb442a80-234b-11eb-91ba-7c21c2d3f788.png)

My link is `https://github-readme-stats.vercel.app/api?username=andrey-helldar&show_icons=true&icon_color=805AD5&text_color=718096&bg_color=ffffff&hide_title=true`

**Comment by anuraghazra** [comment]
@andrey-helldar thanks for reporting the issue, this is kinda weird 🤔 i think this is happening because of Github API could only count maximum of 1 year date range.. so i think the default offsets of those date ranges changes as time goes by thus it results in commits getting lower and lower.

In the meantime you can also try to set `&include_all_commits=true` it will show you your all time commits since you joined github

**Comment by andrey-helldar** [comment]
@anuraghazra, yes, this shows the total number of commits. 

If the GitHub API shows the number of commits over an interval of 1 year, maybe it is worth transmitting the value for the current year, starting from January 1, and not for the last 12 months?

Or you can remove 2020 and write "last 12 months", for example.

**Comment by anuraghazra** [comment]
> @anuraghazra, yes, this shows the total number of commits.
> 
> If the GitHub API shows the number of commits over an interval of 1 year, maybe it is worth transmitting the value for the current year, starting from January 1, and not for the last 12 months?
> 
> Or you can remove 2020 and write "last 12 months", for example.

Good suggestion i would see which one works best and make the appropriate changes thanks!

**Comment by andrey-helldar** [comment]
Thanks! Best Regards    Andrey Helldar16:16, 14 ноября 2020 г., Anurag Hazra <notifications@github.com>:

@anuraghazra, yes, this shows the total number of commits.
If the GitHub API shows the number of commits over an interval of 1 year, maybe it is worth transmitting the value for the current year, starting from January 1, and not for the last 12 months?
Or you can remove 2020 and write "last 12 months", for example.

Good suggestion i would see which one works best and make the appropriate changes thanks!
