### ISSUE TITLE
Number of commits is wrong

### ISSUE THREAD

**Issue by AdityaInfinite** [anuraghazra/github-readme-stats#635]
**Describe the bug**
Wrong number of commits shown

**Expected behavior**
Correct number of commits to be displayed

**Screenshots**
In this it is showing that i have made 110 commits 
![GitHubStatsSS](https://user-images.githubusercontent.com/60790773/98794000-931a4500-242e-11eb-84f0-04403309b6bd.JPG)
I used this link https://github-readme-stats.vercel.app/api?username=AdityaInfinite&include_all_commits=true

**but i know as a fact that I have made only 104 commits,**
I calculated the total by going to each repository>insights>contributors 

I also wrote a script to count all my commits and then console log it. It is in my repository [**commitCounter**](https://github.com/AdityaInfinite/commitCounter)
```javascript
var username = "AdityaInfinite"

var commits = 0;
main();
async function main() {
    const reposResponce = await fetch(`https://api.github.com/users/${username}/repos`);
    var repos = await reposResponce.json();
    for (r of repos) {
        const reposCommits = await fetch(`https://api.github.com/repos/${username}/${r.name.toLowerCase()}/stats/contributors`);
        var repoCommits = await reposCommits.json();
        for(var s = 0; s < repoCommits.length; s++){
            if (repoCommits[s].author.login == username) {
                commits += repoCommits[0].total;
            }
        }
    }
    console.log(`total commits: ${commits}`);
}
```
this also logs 104 as my total commits

![ConsoleLog](https://user-images.githubusercontent.com/60790773/98795983-e392a200-2430-11eb-9f7c-5d289b85d19d.JPG)

I am new to GitHub and JavaScript and I might be doing something wrong.
ThnakYou

**Comment by anuraghazra** [comment]
@AdityaInfinite hmm i see. actually we don't counting this way since looping through and fetching the commits one by one for each and every repo is not really efficient. so we just use the Github GraphQL API v4 

And it returns 116 here. https://github-readme-stats.vercel.app/api?username=AdityaInfinite

![image](https://user-images.githubusercontent.com/35374649/98799162-c52ea580-2434-11eb-99bc-596c4fd13a31.png)

**Comment by AdityaInfinite** [comment]
thanks :smile:
