### ISSUE TITLE
No S after the apostrophe 

### ISSUE THREAD

**Issue by sudocode1** [anuraghazra/github-readme-stats#636]
**Describe the bug**
There is no s after the `'` in my name on the stats viewer. 

**Expected behavior**
The 's should be there.

**Screenshots / Live demo link (paste the github-readme-stats link as markdown image)**
![image](https://github-readme-stats.vercel.app/api?username=sudocode1&show_icons=true&theme=radical)

**Comment by w0rmr1d3r** [comment]
I found this @sudocode1 regarding the `X-case` and `S-case` in English:
https://ell.stackexchange.com/questions/6295/when-a-word-ends-in-s-or-x-do-you-add-s-or-just-an

**Comment by nthnchu** [comment]
This is by design:
https://github.com/anuraghazra/github-readme-stats/blob/94aeabe300c9f7dce6b6871500ceeb5122aaa296/src/cards/stats-card.js#L80

You can always use the `?custom_title` query parameter.

**Comment by sudocode1** [comment]
cheers
