### ISSUE TITLE
Option to disable javascript animations

### ISSUE THREAD

**Issue by alt-art** [anuraghazra/github-readme-stats#642]
I was seeing in the github application that the Stats Card does not show the information correctly, probably because the application does not accept execution of javascript in the README.

My solution is to make an option that only shows information without animation.
![photo_2020-11-13_20-45-11](https://user-images.githubusercontent.com/43281034/99131356-aa556000-25f1-11eb-8333-b5a0a42da84a.jpg)

**Comment by anuraghazra** [comment]
Oh yes! @alt-art i will add this. 

While building a discord bot i also faced the same issue and had to disable animations. will add a `?animations=false` field to disable it.

**Comment by anuraghazra** [comment]
Added disable_animation options

https://github-readme-stats-d0ysm0mlv.vercel.app/api/?username=anuraghazra&disable_animations=true
