### ISSUE TITLE
Amount of commits goes over year

### ISSUE THREAD

**Issue by RobinSchapendonk** [anuraghazra/github-readme-stats#644]
**Describe the bug**
The amount of commits goes over the year number
(the `204` goes over the `)`)

**Expected behavior**
They should be drawn next to eachother

**Screenshots / Live demo link (paste the github-readme-stats link as markdown image)**
![my profile](https://github-readme-stats.vercel.app/api?username=robinschapendonk&hide=stars&count_private=true&show_icons=true&theme=highcontrast)

**Additional context**
If you hide the icons it shows correct
![my profile](https://github-readme-stats.vercel.app/api?username=robinschapendonk&hide=stars&count_private=true&theme=highcontrast)

And with a different theme it still shows wrong
![my profile](https://github-readme-stats.vercel.app/api?username=robinschapendonk&hide=stars&count_private=true&show_icons=true)

**Comment by anuraghazra** [comment]
perfectly fine on my side tho 

![image](https://user-images.githubusercontent.com/35374649/99152217-68e2b480-26c6-11eb-804b-748f284eb762.png)

**Comment by RobinSchapendonk** [comment]
@anuraghazra I'll give you more details about my pc
Browser: Brave
OS: Arch Linux
Extensions: None (all disabled)

**Comment by anuraghazra** [comment]
Please give a screenshot of the card too and if possible which font family does your OS uses

**Comment by RobinSchapendonk** [comment]
[screenshot](https://ss.pokehunt.xyz/87UJ)
Font = pango:monospace 8

**Comment by hypernova7** [comment]
Using `include_all_commits=true` solves it
