### ISSUE TITLE
Provide option for adjusting box width

### ISSUE THREAD

**Issue by harshagv** [anuraghazra/github-readme-stats#65]
Currently there is an option available to control the line-height between text `&line_height=29`, but it would be better if there is an additional option to control the box width like `&box_width=11`.

**Comment by anuraghazra** [comment]
Thanks for requesting the feature @harshagv i'll see what i could do

**Comment by anuraghazra** [comment]
Hi @harshagv can you provide me some scenarios and use cases for having control over the width of the card?

**Comment by harshagv** [comment]
The scenario is when the README is divided into two sections, one for an image and other text/statistics..
Where if the image size is bigger and the statistics box is placed below the image. If the size of the statistics box can be reduced, it will allow the image and statistics box to be  placed next to each other rather than above and below.

![image](https://user-images.githubusercontent.com/4518005/87883177-edb60e00-ca05-11ea-806d-c2a973eaaea8.png)

**Comment by simarpreetsingh-019** [comment]
@harshagv  Thanks for creating this issue, I am also figuring on this, have you got any solution for this? if yes, please share here also.
@anuraghazra I was checking the reference of issues where this is mentioned but got a bit confused, is this issue solved, or is it in progress?

**Comment by sreedevi111** [comment]
![Screenshot 2022-03-04 at 1 37 57 PM](https://user-images.githubusercontent.com/72161804/156724262-c996b9be-3870-42c2-a991-fa8a93e2a7e7.png)
Is there any option to adjust the box height and width of the top languages card?

**Comment by vazome** [comment]
With HTML, you can adjust the card this way `width="495" height="195"` but the downside is constancy of width/height no matter of your screen resolution.

**Comment by vazome** [comment]
@anuraghazra, could you please share a way to make profile and top languages card size aligned with each other? 
<img width="702" alt="image" src="https://user-images.githubusercontent.com/46573198/160506126-9e44f7b5-a094-4104-bf84-9a6c5f5dfd5e.png">
