### ISSUE TITLE
Top language api doesn't count forked repo ?

### ISSUE THREAD

**Issue by ipankajsingh** [anuraghazra/github-readme-stats#651]
**Describe the bug**
I have 2 forked repo, and the top-lang card is showing empty.

**Comment by nthnchu** [comment]
This is by design. If you want you can change this on your own vercel instance.

https://github.com/anuraghazra/github-readme-stats/blob/f7f11d0b2500c0332535e6c3e5ec41819e9d813b/src/fetchers/top-languages-fetcher.js#L12

**Comment by fm-sys** [comment]
> 
> 
> This is by design. If you want you can change this on your own vercel instance.
> 
> https://github.com/anuraghazra/github-readme-stats/blob/f7f11d0b2500c0332535e6c3e5ec41819e9d813b/src/fetchers/top-languages-fetcher.js#L12

It could be made customizable via an attribute like `?includeForks=true`...
