### ISSUE TITLE
[status] Allow to Disable Fading

### ISSUE THREAD

**Issue by summetdev** [anuraghazra/github-readme-stats#660]
**Is your feature request related to a problem? Please describe.**
I am always frustrated when I see my status card fade and other cards (languages, etc.) not, also it causes visual bugs in some platforms.

**Describe the solution you'd like**
Add a URL parameter to disable fading, for example `?fade=false`.

**Describe alternatives you've considered**
Add fading for other cards.

**Comment by yendi158** [comment]
👍

**Comment by anuraghazra** [comment]
@summetdev we already have disable_animations flag

https://github-readme-stats.vercel.app/api?username=anuraghazra&disable_animations=true

![](https://github-readme-stats.vercel.app/api?username=anuraghazra&disable_animations=true)

**Comment by summetdev** [comment]
Thanks :heart:

**Comment by yendi158** [comment]
Y
