### ISSUE TITLE
Missing top languages from organization repositories

### ISSUE THREAD

**Issue by jvmachadorj** [anuraghazra/github-readme-stats#663]
**Describe the bug**
I'm the top developer from this repo from my organization that has this stats

![image](https://user-images.githubusercontent.com/41060584/100292546-900b7280-2f5f-11eb-9b2d-424d13b4f6a4.png)

But in my top langs card, it doesn't appear any groovy language

![image](https://user-images.githubusercontent.com/41060584/100292572-a285ac00-2f5f-11eb-97e5-a1b8ef12c458.png)

**Expected behavior**
The repos from another organization should show in the top lang card

**Comment by chahank** [comment]
I am having the same issue.

**Comment by anuraghazra** [comment]
see #1
