### ISSUE TITLE
Total Commits Rendering Bug

### ISSUE THREAD

**Issue by sci4me** [anuraghazra/github-readme-stats#664]
![](https://i.imgur.com/o97eZdh.png)

**Comment by sci4me** [comment]
I am only experiencing this on Linux (5.9.8-arch1-1) in Chromium (86.0.4240.198) and also in Firefox (83.0).

**Comment by ZerdoX-x** [comment]
![image](https://user-images.githubusercontent.com/49815452/101284914-5f032b80-3804-11eb-9711-cb8b10403366.png)
Same.
5.9.11-arch2-1
Mozilla Firefox 84.0b7
Chromium 87.0.4280.88

**Comment by sci4me** [comment]
This issue isn't stale, the bug still occurs.

**Comment by sci4me** [comment]
This issue isn't stale, the bug still occurs.

**Comment by hasufell** [comment]
Same here. I see it everywhere basically. Is there a quickfix, like hiding the year, for example?

**Comment by sci4me** [comment]
Still not stale ffs.

**Comment by sci4me** [comment]
Please forgive me for bumping but, I'm wondering if this is ever going to be fixed? I'm curious to know how many people are experiencing this issue; clearly not enough to make it a priority.

**Comment by sci4me** [comment]
Still not stale.

**Comment by Electrenator** [comment]
Currently also seeing this within the latest Firefox. Next to this the card title appears to be overflowing with the `hide_rank` setting set to true. As can be seen within the picture below :)
![Screenshot 2021-12-09 at 10-26-37 Electrenator - Overview](https://user-images.githubusercontent.com/18311389/145369783-3bd2968f-231b-434d-9d96-615552f6978f.png)

As far as I've seen, every chromium based browser I've tried seems to render the formatting without any problems.

**Comment by Electrenator** [comment]
It looks like that Firefox handles `font-weight` differently than chromium. The following Firefox specific css can be used to fix this. (applied in Electrenator/github-readme-stats@f82f70934e3380b3a1d15fc5a4bb49b1d0e240bf)
```css
@supports(-moz-appearance: auto) {
    .stat{ font-size:12px; }
    .header{ font-size: 15.5px }
}
```
But the current testing method doesn't support the `@supports` selector, which currently makes 15 tests fail. Unsure how to fix that but the cards should work.

**Comment by sci4me** [comment]
This bug is still occurring on my end, on Arch still. Is this in prod yet?

**Comment by Electrenator** [comment]
It looks like the change is in production, yes. Unsure what would keep it from working on Arch since I have never booted into that distro. Is that still happening and when so, are there any browser details you are able to share?
