### ISSUE TITLE
Top languages not show

### ISSUE THREAD

**Issue by luizfernandonb** [anuraghazra/github-readme-stats#666]
I'm using the link "https://github-readme-stats.vercel.app/api/top-langs/?username=luizfernandonb" to try to get the most used languages and it doesn't work, here is a printout of what appears for me:

![image](https://user-images.githubusercontent.com/42288418/100491689-7bb4aa80-3104-11eb-9cf8-ee2df2ca91ec.png)

What can it be? I have the slightest idea :/

**Comment by Vurv78** [comment]
You don't have any repos, I don't think contributions to other repositories that you didn't create count

**Comment by luizfernandonb** [comment]
But the repositories that I have are in my organization, I thought it also counted

**Comment by dumbcoder7** [comment]
Try creating a public repo, and write some code. See if the issue is resolved.

**Comment by luizfernandonb** [comment]
ok

**Comment by luizfernandonb** [comment]
thanks
