### ISSUE TITLE
Support for Organizations

### ISSUE THREAD

**Issue by kaaax0815** [anuraghazra/github-readme-stats#668]
**Is your feature request related to a problem? Please describe.**
I have many of my repositories on a organization 

**Describe the solution you'd like**
Be able to declare a Organisation for e. G. languages card

**Comment by Zethson** [comment]
I would like to second this request. I am mostly contributing to organizations and would like to have this reflected.

**Comment by BenMorel** [comment]
Same here. Most of my stars come from projects I own under an organization, so the card does not reflect my actual contributions.

**Comment by anuraghazra** [comment]
duplicate of #1

See #1 for more info.
