### ISSUE TITLE
Units for Stats Card's 'Contributed To' field

### ISSUE THREAD

**Issue by adityaraute** [anuraghazra/github-readme-stats#670]
**Issue**
The 'Contributed To' field in Stats Card shows an integer, without any semantic unit supporting it.

**Suggestion**
To add the word 'Projects' as the unit for this field.

**Example**
~~Contributed to: 257~~
Contributed to: 257 _projects_

**Comment by AryanBeezadhur** [comment]
That would disrupt the numbers:

![image](https://user-images.githubusercontent.com/34424160/100651335-33340180-333d-11eb-9b3b-2fe114a7cbf2.png)

**Comment by dumbcoder7** [comment]
> That would disrupt the numbers:


Sorry how? It is only in one field. Also without the word the field is a little difficult to understand

**Comment by AryanBeezadhur** [comment]
This is the line of code that stores the repos contributed to:

https://github.com/anuraghazra/github-readme-stats/blob/f7f11d0b2500c0332535e6c3e5ec41819e9d813b/src/fetchers/stats-fetcher.js#L99

The string "projects" would then have to be appended on.

**Comment by dumbcoder7** [comment]
Well yes I understand that it is not a single line solution. I did try appending `+'projects'` to the following line.

https://github.com/anuraghazra/github-readme-stats/blob/f7f11d0b2500c0332535e6c3e5ec41819e9d813b/src/cards/stats-card.js#L120

But, the tests are designed such that this becomes unacceptable.

---

**However, that does not mean that the issue does not exist. If the issue needs more editing in code, so be it. But the issue exists, and should be resolved if the owner feels it is important enough.**

**Comment by dumbcoder7** [comment]
@anuraghazra Is this issue worth taking up?
