### ISSUE TITLE
Total Commits - Rendering Bug

### ISSUE THREAD

**Issue by yanbrasiliano** [anuraghazra/github-readme-stats#677]
Hi!

The total commitments are with the 2020 image and makes it difficult to view commits.

Is there a solution?

**Comment by anuraghazra** [comment]
Please provide a screenshot.

**Comment by yanbrasiliano** [comment]
> Please provide a screenshot.

hey bro,
here's the print:

![bug](https://user-images.githubusercontent.com/72168914/101424160-50d30f00-38d9-11eb-9bdb-1cbc9dced222.png)

How to get 2020 out of Commits?

**Comment by Aryankpoor** [comment]
Can you please share the code of the readme-stats?

**Comment by yanbrasiliano** [comment]
> 
> 
> Can you please share the code of the readme-stats?

OK,

`[![Anurag's github stats](https://github-readme-stats.vercel.app/api?username=yanbrasiliano)](https://github.com/anuraghazra/github-readme-stats)`

In preview issue, 2020 appears with a larger space.

**Comment by yanbrasiliano** [comment]
Hello!
the problem was solved; tested today and rendering 2020 was OK.
thanks for attention.

**Comment by yanbrasiliano** [comment]
Hello !

I realized that this rendering problem occurs on GNU / Linux - Browser Mozilla Firefox

**Comment by Aryankpoor** [comment]
Ok, I will try visiting mine through virtual machine and see if the rendering problem occurs with me also

**Comment by yanbrasiliano** [comment]
> Ok, I will try visiting mine through virtual machine and see if the rendering problem occurs with me also

Ok!

**Comment by Aryankpoor** [comment]
I see the problem in ubuntu but not in fedora and arch, so maybe the problem is in the system.

**Comment by yanbrasiliano** [comment]
i'm use Debian Buster 10.7
