### ISSUE TITLE
PAYMENT_REQUIRED?

### ISSUE THREAD

**Issue by Bizarrus** [anuraghazra/github-readme-stats#684]
**Describe the bug**
When i try to create an URL, Example:

> https://github-readme-stats.vercel.app/api/top-langs/?username=Bizarrus

a error page appears.

**Screenshots / Live demo link (paste the github-readme-stats link as markdown image)**
![image](https://user-images.githubusercontent.com/1371300/101523843-6bfd5780-3989-11eb-9a99-0a46abe17de1.png)

**Additional context**
I can't found some informations about payments.

**Comment by IlluminatiFish** [comment]
Seeing this too, seems like his hosting went down

**Comment by Officialstrike** [comment]
Seems like he maybe went over the hosting limits?
https://vercel.com/docs/platform/fair-use-policy#typical-monthly-usage-guidelines
![image](https://user-images.githubusercontent.com/42299518/101526351-b4952080-3949-11eb-9f2b-20d6cf5dd09b.png)

**Comment by prakharrathi25** [comment]
Yes, looks like it became too popular. We need to start hosting it ourselves now. @

**Comment by lucascudo** [comment]
I am seeing it too when trying to reach https://github-readme-stats.vercel.app/api?username=lucascudo
and it looks like this at my README:
![image](https://user-images.githubusercontent.com/13350752/101526624-c5af5300-3984-11eb-8237-3ae148d281dd.png)

**Comment by DevLiuSir** [comment]
Yes, I met too. How to solve it?

**Comment by anuraghazra** [comment]
See #325 

Hi everyone, my vercel account is blocked for overuse. 

Please consider deploying github-readme-stats on your own Vercel instance for further use. 
Tutorial: https://www.youtube.com/watch?v=n6d4KHSKqGk&feature=youtu.be&t=107

**Comment by lucascudo** [comment]
> See #325
> 
> Hi everyone, my vercel account is blocked for overuse.
> 
> Please consider deploying github-readme-stats on your own Vercel instance for further use.
> Tutorial: https://www.youtube.com/watch?v=n6d4KHSKqGk&feature=youtu.be&t=107
> 
> Closing this in favor of #325

Deploying it resolved the issue.

**Comment by anuraghazra** [comment]
Yes @lucascudo 

Deploying on your own instance would resolve the issue.

**"I would highly encourage everyone to deploy it on their own instance"**

**Comment by justisGipson** [comment]
thanks

**Comment by apersonnamedlucas** [comment]
u might have more .vercel.app sites then u can have
