### ISSUE TITLE
"402 Payment required" error / statistics-cards are not rendering

### ISSUE THREAD

**Issue by joseywoermann** [anuraghazra/github-readme-stats#686]
**Describe the bug**
The cards that usually show the contributions and top-languages dont render anymore. 
 If you open the card as a website, it displays a "402 - payment required" message.

**Expected behavior**
An embedded square-ish card with statistics should show up.

**Screenshots / Live demo link (paste the github-readme-stats link as markdown image)**

The website:
![image](https://user-images.githubusercontent.com/67111271/101530169-d914eb00-3991-11eb-8a21-c217e327a13b.png)
What appears in the README.md:
![image](https://user-images.githubusercontent.com/67111271/101530232-ecc05180-3991-11eb-84d8-251a070f53bd.png)

My code:
![image](https://user-images.githubusercontent.com/67111271/101530455-3e68dc00-3992-11eb-954c-792ec0f5f212.png)

**Additional context**
This is likely an issue with the host.

**Comment by anuraghazra** [comment]
Closing this in favor of #684 #325
