### ISSUE TITLE
github-readme-stats usage results in 402:PAYMENT_REQUIRED error

### ISSUE THREAD

**Issue by justisGipson** [anuraghazra/github-readme-stats#687]
**Describe the bug**
`402:PAYMENT_REQUIRED` when trying to view stats

**Expected behavior**
I should be able to see my stats...

**Screenshots / Live demo link (paste the github-readme-stats link as markdown image)**
<img width="767" alt="Screen Shot 2020-12-08 at 1 57 25 PM" src="https://user-images.githubusercontent.com/42194039/101530244-a81bc280-395f-11eb-8abc-02411b0e318a.png">

**Additional context**

**Comment by IlluminatiFish** [comment]
Refer to #687

**Comment by anuraghazra** [comment]
Closing this in favor of #684 #325

**Comment by justisGipson** [comment]
@anuraghazra I see that now... thanks
