### ISSUE TITLE
Add support for dark mode

### ISSUE THREAD

**Issue by nategiraudeau** [anuraghazra/github-readme-stats#689]
**Is your feature request related to a problem? Please describe.**
The readme stats usually look like the rest of github, but they don't look good with github's new darkmode feature.

**Describe the solution you'd like**
It to change color when darkmode is enabled.

**Describe alternatives you've considered**
No alternatives.

**Additional context**
No additional context.

**Comment by nathanchu** [comment]
Duplicate of #66, #79

**Comment by wleoncio** [comment]
> Duplicate of #66, #79

Shouldn't this (and maybe #79) get a "duplicate" tag, then?

**Comment by andrey-helldar** [comment]
You can install the "dark" theme right now - for this you need to specify the background color with an alpha channel: `bg_color=ffffff00`

For example:

![image](https://user-images.githubusercontent.com/10347617/101827719-b3c6df00-3b41-11eb-871c-21b4a2a76c63.png)

![image](https://user-images.githubusercontent.com/10347617/101827745-b9bcc000-3b41-11eb-8ba2-8c08212a5298.png)

**Comment by wleoncio** [comment]
That helps, thanks! I also had to set `text_color=666666` to get something that sort of worked in both modes (tried different inbuilt themes first, no go), but that's good enough for now. :+1:

**Comment by nategiraudeau** [comment]
That works, thanks.
