### ISSUE TITLE
[Feature Request] Vertical Orientation

### ISSUE THREAD

**Issue by nathanchu** [anuraghazra/github-readme-stats#70]
There should be a way to change the orientation of the image. For example, [this jsFiddle](https://jsfiddle.net/5ujegnpk/).

**Comment by filiptronicek** [comment]
This looks very good, but I think it has a fairly limited use case. Some things to consider:
* what could be stacked next to it (it would have to be similar height, and if it was another GitHub readme widget, why)
* how it will look, if stacked on mobile.

**Comment by anuraghazra** [comment]
Thanks for requesting the feature @nthnchu i'll see what i can do

**Comment by nthnchu** [comment]
> - what could be stacked next to it (it would have to be similar height, and if it was another GitHub readme widget, why)

I was thinking text could be next to it, so the widget(s) would look like a sidebar. For example:
<hr>
<h1>Heading</h1><img width="228" height="367" align="right" src="https://user-images.githubusercontent.com/63111210/87593750-f29f5880-c6b9-11ea-95c0-fa13c2574a81.png">
Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut pharetra sit amet aliquam id diam maecenas. Aliquam sem fringilla ut morbi tincidunt augue interdum velit euismod. Vitae et leo duis ut. Pharetra massa massa ultricies mi quis hendrerit dolor. Tincidunt vitae semper quis lectus nulla at volutpat. Sit amet facilisis magna etiam tempor orci eu lobortis. Aliquam etiam erat velit scelerisque in dictum non consectetur a. Accumsan in nisl nisi scelerisque eu ultrices vitae auctor eu. Tristique risus nec feugiat in fermentum posuere urna nec tincidunt. Nisl nunc mi ipsum faucibus vitae.

Et netus et malesuada fames ac turpis egestas integer eget. Tortor pretium viverra suspendisse potenti nullam ac tortor. Blandit cursus risus at ultrices mi. Faucibus interdum posuere lorem ipsum dolor sit amet consectetur. Fermentum leo vel orci porta non pulvinar neque laoreet. Netus et malesuada fames ac turpis. Eu lobortis elementum nibh tellus molestie nunc. Sit amet purus gravida quis blandit turpis cursus. Dignissim convallis aenean et tortor at. Nisl condimentum id venenatis a. Commodo odio aenean sed adipiscing diam donec adipiscing tristique. Consectetur lorem donec massa sapien faucibus et molestie ac feugiat. Purus faucibus ornare suspendisse sed nisi. Neque volutpat ac tincidunt vitae semper quis lectus nulla. Volutpat blandit aliquam etiam erat velit scelerisque. Tellus elementum sagittis vitae et leo duis ut diam quam. Urna neque viverra justo nec ultrices dui sapien eget. Nullam non nisi est sit.

**Comment by filiptronicek** [comment]
I dig it. Looks awesome! @nthnchu
