### ISSUE TITLE
[ Bug ] Text not rendering properly on Chrome on Android

### ISSUE THREAD

**Issue by ADoesGit** [anuraghazra/github-readme-stats#71]
Some text on Android Chrome has incorrect spacing
![Screenshot_20200715-135812_Chrome](https://user-images.githubusercontent.com/42613600/87579086-63874600-c6a3-11ea-8f73-d866c826d3b5.jpg)

**Comment by ADoesGit** [comment]
This doesn't happen when opening the images in a new tab.

**Comment by anuraghazra** [comment]
Thanks for opening the issue @ADoesGit 

I think this is totally up how the browser would render the svg, AFAIK i can't do anything to fix it, but i'll take a look at the issue tomorrow.

**Comment by anuraghazra** [comment]
I also noticed this, and i think this randomly happens. i've faced this, we'll see what we can do to fix this, Closing this in favor of #38
