### ISSUE TITLE
Card size with statistics

### ISSUE THREAD

**Issue by uPagge** [anuraghazra/github-readme-stats#714]
![изображение](https://user-images.githubusercontent.com/40397740/101988528-3e771d80-3cab-11eb-8d73-08140bfa056d.png)

I would like to make the cards in one line, but I can't because I can't resize the right card. Even if I hide the rank - it doesn't reduce the size, it seems weird to me.

I would like to be able to resize the card with stats, and also to have the size change automatically if the rank is hidden

**Comment by uPagge** [comment]
I was able to do what I wanted by reducing the size of popular languages, but it's strange that you can't change the size of another card

**Comment by anuraghazra** [comment]
> I would like to make the cards in one line, but I can't because I can't resize the right card. Even if I hide the rank - it doesn't reduce the size, it seems weird to me.

Hi @uPagge this feature is added in #721

**Comment by uPagge** [comment]
thank you very much for the tip, I will definitely look
