### ISSUE TITLE
Wrong number of stars showing on GitHub readme stat? Just for me?

### ISSUE THREAD

**Issue by ApurvShah007** [anuraghazra/github-readme-stats#72]

**Comment by anuraghazra** [comment]
please provide more info.

**Comment by ApurvShah007** [comment]
I can clearly see that my stars are much more than what it shows on the stats card. I am wondering what all it is counting. It was showing around 41 but now it shows 25. Just wondering if you changed what it counts.

**Comment by anuraghazra** [comment]
Note: only owned repos are counted, not forked or contributed repos, checkout #39

**Comment by ApurvShah007** [comment]
@anuraghazra I thought so too but it changed today and threw me off. My bad. Also what about private repos?

**Comment by anuraghazra** [comment]
Yes there caching of 30mins

**Comment by ApurvShah007** [comment]
That should be it then.

**Comment by anuraghazra** [comment]
Yes, closing this in favour of #39 

Please hop into my discord server if you have confusing regarding stats.
