### ISSUE TITLE
Transparent bg color

### ISSUE THREAD

**Issue by Pugabyte** [anuraghazra/github-readme-stats#730]
Hi there, would it be possible to make the cards' background color transparent, to blend in with the user's chosen theme? i.e. mine currently uses dark theme's background color to blend in with dark theme.

**Comment by nathanchu** [comment]
You can use `&bg_color=00000000` 😄 

Demo:
![](https://github-readme-stats.vercel.app/api?username=nathanchu&bg_color=00000000)

**Comment by NoushadBug** [comment]
you can check out this, **https://github.com/NoushadBug**

**this stat theme is for any GitHub theme, made by me. It will be suitable. Have a check -** 
`https://github-readme-stats.vercel.app/api?username=noushadBug&title_color=FA8C00&icon_color=CC5160&text_color=949CA5&bg_color=00000000&show_icons=true`
