### ISSUE TITLE
Improvements to calculateRank

### ISSUE THREAD

**Issue by LeptoFlare** [anuraghazra/github-readme-stats#736]
**Is your feature request related to a problem? Please describe.**
Right now, ranks are displayed as grades, based on the percentile of contributions. However, there are 2 issues with this.

1. The way ranks are calculated make them somewhat arbitrary. Since the majority of people that have a github account do not actually use their account. It's quite easy to make `A+` through even just a couple of commits.
EX: 
![image](https://user-images.githubusercontent.com/47790183/102371149-e2064d80-3f8b-11eb-8454-13fb66aaac99.png)
![image](https://user-images.githubusercontent.com/47790183/102371168-e894c500-3f8b-11eb-81cd-75679f0afcef.png)

Thus, this doesn't provide a very good picture of how much someone has actually contributed.

Ranks are also a very opinionated way of looking at how "helpful" a person is on github.

2. The level of abstraction that displaying your percentile as a "grade" does doesn't provide a very good understanding of how much a person has actually done on .

**Describe the solution you'd like**
There are two parts to my preferred way of solving this.
1. Ranks should be displayed as an exact number, rather than an opinionated rank based off of manually chosen percentage ranges.
2. The way said number is calculated should be refactored, there are a couple different ways to implement this, but I'd like a way that takes into account the distribution of github users more.

**Describe alternatives you've considered**
- To avoid breaking changes, you can simply add a direct percentage as another option / parameter for the card.

**Comment by nathanchu** [comment]
Actually, you can make A+ with no commits 😄 

![](https://github-readme-stats.vercel.app/api?username=githu)

**Comment by nathanchu** [comment]
Any suggestions on how to calculate it rather than CDF? Or should we just change the offsets?

**Comment by LeptoFlare** [comment]
I was thinking something with standard deviations

**Comment by nathanchu** [comment]
We only have one value to work with (or really 5, but those are combined). So I don't really know how we'd code standard deviation because we only have one user's data at a time. This could be moved to a real server that would push data of each user to a database, and calculate that, but for now we only have one user's data.

**Comment by LeptoFlare** [comment]
I see, It could be estimated by, for each time the function to calculate rank is ran, adds that user's 5 values to a database. Then use the values from the database to calculate rank.

This means the score will become more and more accurate the more people use this.

Another thing is, it automatically biases the ranks based on the kind of person that *uses* this card anyway. So we don't need to worry about the millions of people that have 0 commits.

**Comment by nathanchu** [comment]
Hmm... But serverless functions don't persist data. I see what you mean, though, but I don't know if it's the most efficient to use a database for this that has to be queried on every request (this project uses lambda functions, not an actual server). The easiest solution is to come up with some kind of algorithm. Adding a database seems like too much work for a smaller thing.

The rank should, ideally, be able to be calculated with just one user's stats. I guess a database like fauna could be used though.

**Comment by LeptoFlare** [comment]
In terms of coming up with an algorithm, I don't know enough about github user distributions to really think of an algorithm that would be accurate without some kind of actual user data.

### Continuing with a score relative to other users
Implementing a database would probably cost some, Fauna does seem like a good option however, as it's built for this kind of stuff. There should still be discussion about the best way to query the database etc..

### Alternative 2
Rather than develop a percentage based on some kind of relative number, We could simply create some kind of "point system" to give an absolute value of a user's github. The point system, in order to keep it fit within a couple characters would cap at `9.9` maximum, rounded to a decimal place. However, I expect a good portion of users to have a score such as `0.7` with a fairly active user possibly being around `5.0`.

We'd still have to guess a bit. Figure out what values would a user need to get a 5.0 and work from there. But it's a lot less than needing to figure out a user's percentile for the entirety of github.

---
p.s: I like the elegance of the first alternative but I can understand if it's not viable
