### ISSUE TITLE
A solution so that the stats theme changes with the GitHub theme.

### ISSUE THREAD

**Issue by swapnanildutta** [anuraghazra/github-readme-stats#739]
**Is your feature request related to a problem? Please describe.**
"GitHub Stats" are a way to decorate our READMEs, and since GitHub introduced its dark mode, codes have become easy to eyes and less strainful, but our README stats remain the same and we cannot change how the other user looks at it and that decreases its aesthetic effect.

**Describe the solution you'd like**
A way to choose/select two themes, one for the light mode and another for dark, depending on which theme the user views that README. In that way it would be pretty cool I think.

**Comment by nathanchu** [comment]
GitHub doesn't support this (yet). You can use a transparent background if you want though with `&bg_colo=00000000`

**Comment by StevenPss** [comment]
This is a good idea actually. Having the **GitHub Stats** change themes depending on the GitHub theme selected will allow for flexibility in terms of aesthetics.

So what can be done is that you have 2 predefined themes for a toggle between light and dark theme.

**Comment by swapnanildutta** [comment]
> 
> 
> This is a good idea actually. Having the **GitHub Stats** change themes depending on the GitHub theme selected will allow for flexibility in terms of aesthetics.
> 
> So what can be done is that you have 2 predefined themes for a toggle between light and dark theme.

Yeah, that's exactly what I meant. Two preset themes, one for light and another for dark, also gives the user the option to customize both themes.

**Comment by preveenraj** [comment]
> GitHub doesn't support this (yet). You can use a transparent background if you want though with `&bg_color=00000000`

This indeed worked for me. Also you should set text_color to something that would contrast between dark and light theme.
You could try this and see : `hide_border=true&bg_color=00000000&text_color=3498db`

For reference, check my profile: https://github.com/preveenraj

**Comment by NoushadBug** [comment]
you can check out this, **https://github.com/NoushadBug**

**this stat theme is for any GitHub theme, made by me. It will be suitable. Have a check -** 
`https://github-readme-stats.vercel.app/api?username=noushadBug&title_color=FA8C00&icon_color=CC5160&text_color=949CA5&bg_color=00000000&show_icons=true`
