### ISSUE TITLE
Maximum retries exceeded

### ISSUE THREAD

**Issue by klaasnicolaas** [anuraghazra/github-readme-stats#74]
I've tried to set up a deploy in Vercel myself, but immediately from the first moment that I want to request the data via my own url, I receive an error message: **_"Maximum retries exceeded"_**.

Impossible that I could have exceeded my limits right away.

Link that I use: https://github-readme-stats-beryl.vercel.app/api?username=klaasnicolaas&show_icons=true&title_color=fff&icon_color=79ff97&text_color=9f9f9f&bg_color=151515

**Comment by anuraghazra** [comment]
@klaasnicolaas make sure you have a environment variable called PAT_1

**Comment by rahulrachh** [comment]
Could you add to the readme file how to do that?

**Comment by anuraghazra** [comment]
Yes actually sorry the readme's guide is outdated after #58 i'll update it :D

**Comment by rahulrachh** [comment]
I am still confused @anuraghazra.  do we have to put our GitHub generated token in variable PAT_1 instead of GITHUB_TOKEN variable?

**Comment by anuraghazra** [comment]
Yes.... just delete the GITHUB_TOKEN variable, and instead add a token named "PAT_1"

**Comment by klaasnicolaas** [comment]
I changed the variable, it just doesn't change anything. Maybe because I need to update the fork after all today's merges?

**Comment by anuraghazra** [comment]
Update your fork, and redeploy. and make sure that you have the tokens in vercel's env variable section. 

Use PullBot to automatically update your forks, https://probot.github.io/apps/pull/

**Comment by klaasnicolaas** [comment]
Awesome! I got it working 😄 

Thanks, by the way, for the pull probot app tip, which is super handy than that I always have to manually update everything.

**Comment by rahulrachh** [comment]
@anuraghazra it is working 😄 .  Yeah, thanks by the way for the pull bot.

**Comment by anuraghazra** [comment]
Hi @klaasnicolaas i hope your issue is solved, closing this now. feel free to open another one if you have any other queries :D  Thanks!
