### ISSUE TITLE
[FEATURE] Add URL params for Custom Theme Colors

### ISSUE THREAD

**Issue by IreTheKID** [anuraghazra/github-readme-stats#744]
As the title suggests I'd like to see URL parameters that allow for customization of the card colors. This way, users don't have to open a PR if they really want to use colors not in any currently available theme. Here are some implementation notes I came up with:

+ `title_color`: "2f80ed"
+ `icon_color`: "4c71f2'
+ `text_color`: "333"
+ `bg_color`: "fffefe"

All parameter values should be a 3 or 6 character HEX value without a preceding hashtag (e.g `#`). All color parameters that aren't provided (e.g `https://github-readme-stats.vercel.app/api?username=anuraghazra&title_color=2f80ed`) should be that of the theme provided, default if none.

I'd love to work on this myself and open a PR and get feedback, but I don't have the time because of school :P Feel free to add suggestions!

**Comment by nathanchu** [comment]
Don't these... already exist...?

https://github-readme-stats.vercel.app/api?username=anuraghazra&title_color=444444

**Comment by IreTheKID** [comment]
:O really? It didn't work for me, but I'll try again.

**Comment by nathanchu** [comment]
No problem 👍 `#2f80ed` is actually the color that's used by default (or close to it) so that's why you didn't see it.
