### ISSUE TITLE
Top languages is blank for me, I dont have that many repos.

### ISSUE THREAD

**Issue by dylanjamesdev** [anuraghazra/github-readme-stats#745]
**Describe the bug**
Top languages is blank for me.

**Expected behavior**
I expected the top languages to load.

**Screenshots / Live demo link (paste the github-readme-stats link as markdown image)**

[![Top Langs](https://github-readme-stats.vercel.app/api/top-langs/?username=dylanjamesdev&theme=dark)](https://github.com/anuraghazra/github-readme-stats)

**Additional context**
N/A

**Comment by anuraghazra** [comment]
Because,

You have 5 repos, 4 of them are forks which we don't count. and one is your own profile readme repo which does not have any languages.

Thus Top lang card is empty.

**Comment by dylanjamesdev** [comment]
Fair, can I add an org to the card? (Feel free to close)

**Comment by dylanjamesdev** [comment]
Oh also, I installed the wakatime plugin in Visual Studio Code and it hasn't updated yet in the repo embed, but in the website it's reflecting correctly.

![Wakatime Stats](https://github-readme-stats.vercel.app/api/wakatime?username=dylanjamesdev&theme=dark&custom_title=Weekly+Stats)

**Comment by anuraghazra** [comment]
> Oh also, I installed the wakatime plugin in Visual Studio Code and it hasn't updated yet in the repo embed, but in the website it's reflecting correctly.
> 
> ![Wakatime Stats](https://camo.githubusercontent.com/ceef83ed4cbd41ef09d5fa2faa1d9b62bb63cdca3179d1c0a69efb4f03bd1fc3/68747470733a2f2f6769746875622d726561646d652d73746174732e76657263656c2e6170702f6170692f77616b6174696d653f757365726e616d653d64796c616e6a616d6573646576267468656d653d6461726b26637573746f6d5f7469746c653d5765656b6c792b5374617473)

How long have you been using wakatime? maybe try waiting it will come up.
