### ISSUE TITLE
Total Stars Not Increasing

### ISSUE THREAD

**Issue by JayantGoel001** [anuraghazra/github-readme-stats#752]
**Describe the bug**
My Total Stars aren't getting increased

**Expected behavior**
As Soon As someone stars my repo, after some interval, it should get updated and should increase

**Screenshots / Live demo link (paste the github-readme-stats link as markdown image)**

**Additional context**
My total stars are not getting ahead of 378

**Comment by JayantGoel001** [comment]
@karelkryda Please Review my issue

**Comment by tanvirrb** [comment]
Same issue. Total star is not increasing.

**Comment by youthlql** [comment]
Same issue

**Comment by harshhhdev** [comment]
@youthlql 

![image](https://user-images.githubusercontent.com/69592270/105778460-76c07b80-5f3a-11eb-9f19-cb3f0fda838f.png)

Here, it shows that your star count is 17.

![image](https://user-images.githubusercontent.com/69592270/105778534-9192f000-5f3a-11eb-945a-11cb77b03f00.png)

You only have 1 repository with 17 stars. The star count is perfectly correct. You may be having some other misconception possibly? 

Hope this helped :smile:

**Comment by harshhhdev** [comment]
@JayantGoel001 

![image](https://user-images.githubusercontent.com/69592270/105778710-e6cf0180-5f3a-11eb-9e82-5ea2b69aa453.png)

Your star count is above 378 and is exactly how many stars you have.

**Comment by harshhhdev** [comment]
@tanvirrb your star count is accurate too, from my review.

Either this is a glitch that has been fixed, or there was some kind of misconception.

**Comment by JayantGoel001** [comment]
@harshhhdev I was observing changes for a long time and I have seen my stars are not increasing. 
When I commented this issue at that only I have 378 Stars and Its more than a month but still increase in stars is only 3?
You can see I have created at least 7 Repos  after that time that means at least 7 stars should increase.

Thank You in Advance

**Comment by youthlql** [comment]
I didn't synchronize yesterday. Maybe it was delayed. Thank you

**Comment by youthlql** [comment]
> @youthlql
> 
> ![image](https://user-images.githubusercontent.com/69592270/105778460-76c07b80-5f3a-11eb-9f19-cb3f0fda838f.png)
> 
> Here, it shows that your star count is 17.
> 
> ![image](https://user-images.githubusercontent.com/69592270/105778534-9192f000-5f3a-11eb-945a-11cb77b03f00.png)
> 
> You only have 1 repository with 17 stars. The star count is perfectly correct. You may be having some other misconception possibly?
> 
> Hope this helped 😄

I didn't synchronize yesterday. Maybe it was delayed. Thank you

**Comment by tanvirrb** [comment]
> @tanvirrb your star count is accurate too, from my review.
> 
> Either this is a glitch that has been fixed, or there was some kind of misconception.

@harshhhdev the problem is with github side's caching and theme, I guess. The start count doesn't change immediately in same theme. So, I've changed the theme and it's worked again.

**Comment by anuraghazra** [comment]
@tanvirrb we have minimum of 2 hours of caching and it is documented on readme  

Changing the theme changes the URL, so the cache busts and it got updated immediately.

**Comment by JayantGoel001** [comment]
> @harshhhdev I was observing changes for a long time and I have seen my stars are not increasing.
> When I commented this issue at that time only I had 378 Stars and Its more than a month but still increase in stars is only 3?
> You can see I have created at least 11 Repos after that time that means at least 11 stars should increase.
> 
> Thank You in Advance

@anuraghazra  Can You check my issue also?
Thanks in Advance
