### ISSUE TITLE
Why can't we add private repo's issues in statistics?

### ISSUE THREAD

**Issue by Rayawa** [anuraghazra/github-readme-stats#755]
I reken it;s better to add private repo's issuse count in statistics

**Comment by StudioLE** [comment]
I'd also be interested in seeing language statistics for private repositories. Could this be a possible feature?
Perhaps it would require a self hosted instance as I imagine I'd need to grant API access to my private repositories?

**Comment by anuraghazra** [comment]
> I'd also be interested in seeing language statistics for private repositories. Could this be a possible feature?
> Perhaps it would require a self hosted instance as I imagine I'd need to grant API access to my private repositories?

Yes self hosting with your own personal access token is the way.. because there is no way we can access anyone's private repo information.

**Comment by Gabertho** [comment]
> > I'd also be interested in seeing language statistics for private repositories. Could this be a possible feature?
> > Perhaps it would require a self hosted instance as I imagine I'd need to grant API access to my private repositories?
> 
> Yes self hosting with your own personal access token is the way.. because there is no way we can access anyone's private repo information.

How can we do this?

**Comment by Emaleth** [comment]
wouldn't it be possible to just point to secret same way we do with github actions?
