### ISSUE TITLE
Can I translate CONTRIBUTING.md in this project?

### ISSUE THREAD

**Issue by xiaopangju** [anuraghazra/github-readme-stats#759]
Hi!
I love this project very much.
It seems that CONTRIBUTING.md has not been translated yet. Can I translate it? 
Is there anything I need to pay attention to when I translate?

**Comment by anuraghazra** [comment]
Hi @xiaopangju thanks for your interest on this but I think we don't currently need to translate the CONTRIBUTING.md
Although you feel free to translate the README.md docs or update the outdated docs :)
