### ISSUE TITLE
Why aren't the themes in order with the image?

### ISSUE THREAD

**Issue by MateoElias** [anuraghazra/github-readme-stats#760]
It's pretty straight forward, it's hard to find the theme you are looking for, as it has to be trial and error until you get the one you want. Maybe order the themes to be synced with the image? Or vice-versa.

**Comment by anuraghazra** [comment]
We have all the themes here https://github.com/anuraghazra/github-readme-stats/tree/master/themes

I don't think is hard to find which theme you want.
