### ISSUE TITLE
Repo/Project Build Status (GitHub Workflow)

### ISSUE THREAD

**Issue by MSAdministrator** [anuraghazra/github-readme-stats#761]
**Is your feature request related to a problem? Please describe.**

As a user, I would like to display a repositories build status as part of the card (if available). This is specifically focused on GitHub Workflow build status but could be incorporated with other CI platforms later.

**Describe the solution you'd like**

display the current build status for a repository.

**Describe alternatives you've considered**

None.

**Additional context**

**Comment by anuraghazra** [comment]
Hi @MSAdministrator thanks for opening the issue.

Yes we can add a CI/build status card but I don't think it's too effective since github already provides ci build status badges which users can use. Seems overkill to have a whole separate card just for showing one single metric.

**Comment by anuraghazra** [comment]
Closing this as we are not interested in adding this metric.
