### ISSUE TITLE
Chinese localization: full-width colon

### ISSUE THREAD

**Issue by liyishuai** [anuraghazra/github-readme-stats#775]
**Describe the bug**
`locale=cn` uses semi-width colon `:`

**Expected behavior**
Use full-width colon `：` when `locale=cn`

**Comment by anuraghazra** [comment]
Closed by #774

**Comment by liyishuai** [comment]
Not resolved yet. The test suite still uses semi-width colon.
A solution could be changing the colon per locale, which was not included in #774.

**Comment by anuraghazra** [comment]
Ahh i see okay reopened 👍
