### ISSUE TITLE
Provide a functionality that inherits background of repo card according to git-hub dark/light mode

### ISSUE THREAD

**Issue by Abhijay007** [anuraghazra/github-readme-stats#777]
**Is your feature request related to a problem? Please describe.**

I want a feature that whenever users switch between GitHub dark-light mode, then the background of the repo card changes accordingly to the mode. Means if a user wants a specific theme in dark or white mode, then whenever he/she switches between modes the theme sets accordingly GitHub mode. In simple words, the repo card's background inherits the background color of the applied mode.

**Describe the solution you'd like**
one possible solution to this issue is that we can simply set the background color same as the Github's mode's backgrounds by just apply an if statement that when mode = light set the background color to this.

**Describe alternatives you've considered**

And the other possible solution is that we can give control to the user that he/she can set a theme according to their preferences in the dark/light mode . for example, I don't want to add any theme (just plain repo card) in light mode but whenever I switch to the dark mode I want the theme to changes to "material-palenight" (theme name)

***Idea by screenshots***

**In light mode of GitHub**

![light-github](https://user-images.githubusercontent.com/64387054/103456350-3bf06c80-4d1b-11eb-95e0-966bc5c4a478.PNG)

**but when I switch mode to dark I need it to be like this**

![dark-github](https://user-images.githubusercontent.com/64387054/103456371-63473980-4d1b-11eb-924e-4ad6dc4fe6e1.PNG)

**Comment by jinliming2** [comment]
You may provide `bg_color=00000000` or `bg_color=0000` to get a transparent background.

The colour form like `#rrggbbaa` or `#rgba` works in Chrome >= 62, Firefox >= 49 or Safari >= 10. See [#rrggbbaa hex color notation](https://caniuse.com/css-rrggbbaa)

I think, maybe it's a good idea to support colour form like `bg_color=rgba(0,0,0,0)`, this is more compatible.

**Comment by Abhijay007** [comment]
> You may provide `bg_color=00000000` or `bg_color=0000` to get a transparent background.
> 
> The colour form like `#rrggbbaa` or `#rgba` works in Chrome >= 62, Firefox >= 49 or Safari >= 10. See [#rrggbbaa hex color notation](https://caniuse.com/css-rrggbbaa)
> 
> I think, maybe it's a good idea to support colour form like `bg_color=rgba(0,0,0,0)`, this is more compatible.

Yeah, we can use transparent background, but suppose if someone using black text color, then if he/she switches between modes, then black text makes the problem with the dark mode because black text color is barely visible in dark mode. I think providing functionality to users will be more efficient.

**Comment by anuraghazra** [comment]
it's not possible to detect if users is using dark/light.
If detecting dark/light mode was possible we would have already done it. 

Only good way is to use a transparent color background and use text color which looks good on both light/dark mode. see https://github.com/anuraghazra/github-readme-stats/discussions/690

**Comment by Abhijay007** [comment]
> it's not possible to detect if users is using dark/light.
> If detecting dark/light mode was possible we would have already done it.
> 
> Only good way is to use a transparent color background and use text color which looks good on both light/dark mode. see #690

ok @anuraghazra sir got it.

But sir, I have one question that, can we able to detect if a user is using dark/white with the background color. 
For ex: that if the background-color of the profile is = "#112034" (which is the official color of GitHub dark mode) then change the card background-color to black or the user's desired color.

**Comment by anuraghazra** [comment]
> I have one question that, can we able to detect if a user is using dark/white with the background color.

As i said no it's not possible to detect which theme user is using *yet*

**Comment by 2br-2b** [comment]
Duplicate of #739

**Comment by liginthomasck** [comment]
> **Is your feature request related to a problem? Please describe.**
> A clear and concise description of what the problem is. Ex. I'm always frustrated when [...]
> 
> I want a feature that whenever users switch between GitHub dark-light mode, then the background of the repo card changes accordingly to the mode. Means if a user wants a specific theme in dark or white mode, then whenever he/she switches between modes the theme sets accordingly GitHub mode. In simple words, the repo card's background inherits the background color of the applied mode.
> 
> **Describe the solution you'd like**
> one possible solution to this issue is that we can simply set the background color same as the Github's mode's backgrounds by just apply an if statement that when mode = light set the background color to this.
> 
> **Describe alternatives you've considered**
> A clear and concise description of any alternative solutions or features you've considered.
> 
> And the other possible solution is that we can give control to the user that he/she can set a theme according to their preferences in the dark/light mode . for example, I don't want to add any theme (just plain repo card) in light mode but whenever I switch to the dark mode I want the theme to changes to "material-palenight" (theme name)
> 
> _**Idea by screenshots**_
> 
> **In light mode of GitHub**
> 
> ![light-github](https://user-images.githubusercontent.com/64387054/103456350-3bf06c80-4d1b-11eb-95e0-966bc5c4a478.PNG)
> 
> **but when I switch mode to dark I need it to be like this**
> 
> ![dark-github](https://user-images.githubusercontent.com/64387054/103456371-63473980-4d1b-11eb-924e-4ad6dc4fe6e1.PNG)

yes dudee im also wishing that..
