### ISSUE TITLE
Fetching Bug

### ISSUE THREAD

**Issue by nathanchu** [anuraghazra/github-readme-stats#778]
**Describe the bug**
It's January 2nd, and I don't think I've committed more than 1 time in the past 2 days. I have 666 commits according to the image.

**Expected behavior**
Less than 1 commit for 2021

**Screenshots / Live demo link (paste the github-readme-stats link as markdown image)**
Live:
![](https://github-readme-stats.vercel.app/api?username=nathanchu)

Screenshot:
![image](https://user-images.githubusercontent.com/63111210/103469949-94cefd80-4d39-11eb-937c-0fb15655fa40.png)

**Additional context**
I suspect that's from the last 1 year (January 2, 2020 to January 2, 2021), not just the current year (January 1st, 2021 to January 2nd, 2021)

**Comment by anuraghazra** [comment]
@nathanchu actually how github api works is that it shows "last year's" commits so basically it's showing previous 365days of commits.
Same with github contribution chart, it does not becomes empty on 1st january it shows previous 365days commits.

**Comment by nathanchu** [comment]
Ok, that's what I thought was happening. Could we change the labeling though? Since it says 2021 I expected 0 commits but if it said 52-week then I'd expect the 666 commits.

**Comment by anuraghazra** [comment]
> Ok, that's what I thought was happening. Could we change the labeling though? Since it says 2021 I expected 0 commits but if it said 52-week then I'd expect the 666 commits.

Yeah right.. i wanted to make the text shorter.. so i did not used `previous year` or `last 52weeks` any suggestions?

**Comment by nathanchu** [comment]
`Total Commits (52wk)` maybe?
