### ISSUE TITLE
Overlapping of text in names of most used languages in Mobile Version

### ISSUE THREAD

**Issue by ksdkamesh99** [anuraghazra/github-readme-stats#783]
**Describe the bug**
In GitHub mobile app version when I am loading my profile then there is the overlapping of text in names of most used languages in the mobile version

**Expected behavior**
Proper Padding is required with the text in names of languages

**Screenshots / Live demo link (paste the github-readme-stats link as markdown image)**

I am hereby attaching the screenshots 

![image](https://user-images.githubusercontent.com/46109386/103552623-32f5cb80-4ed2-11eb-9ef2-5ffa2d3051a2.png)

**Additional context**

I hope it will be solved soon

**Comment by sci4me** [comment]
Duplicate of #664
