### ISSUE TITLE
Year or number of total commits looks invalid

### ISSUE THREAD

**Issue by kam193** [anuraghazra/github-readme-stats#787]
**Describe the bug**
The `Total commits (2021)` reports value of 241 commits for me. As we have 6th January and I didn't spend last time on massive commiting, it looks like wrong value of commits or eventually the `2021` should be just `last year`.
 
**Expected behavior**
Correct value of commits (just from 2021) or correct year annotation (e.g. `last year`).

**Screenshots / Live demo link (paste the github-readme-stats link as markdown image)**

![obraz](https://user-images.githubusercontent.com/8472271/103769098-fe922480-5023-11eb-9051-50fbd00b4e91.png)

Live demo on [my profile](https://github.com/kam193)

**Comment by kingthorin** [comment]
Agreed, it seems like this has been off since the start. I recall issues last summer (or whatever when the project was new) about commit counts and it still seems to be incorrect. Supposedly I currently have 1.7k for 2021 (which is definitely not the case).

**Comment by kingthorin** [comment]
Stale therefore fixed, interesting 😉
