### ISSUE TITLE
[Feature] Dark mode

### ISSUE THREAD

**Issue by filiptronicek** [anuraghazra/github-readme-stats#79]
It is a really useful feature, that we can change the colors of the stats, but I would appreciate some sort of auto dark mode With [dark mode coming to GitHub](https://news.ycombinator.com/threads?id=natfriedman), I think it will have to be done sooner or later. 
![Nat Friedman's hacker news profile](https://user-images.githubusercontent.com/29888641/87659232-8c6c1180-c75d-11ea-94de-5cc6dfd6fce1.png)

I have a couple of proposed solutions, but none of them seems perfect.
1. If the auto theme is enabled, query a weather service such as [The Open Weather API](https://openweathermap.org/api), to get the sunset time for the current timezone - I am not sure how to get the time zone though.

Example: client => Vercel <= Weather API

2. It would be best if you could query the [@prefers-color-scheme data of the browser](https://developer.mozilla.org/en-US/docs/Web/CSS/@media/prefers-color-scheme), as no timezone or other preference data would be needed.

Query: `https://github-readme-stats.vercel.app/api?username=anuraghazra&prefers=dark`

3. The hardest solution - we could contact GitHub directly, to perhaps provide a feature, to set alternative image sources according to the current theme.

Something like: [GitHub README stats]({dark: https://darkmodeurl}, light: https://lightmodeurl) in markdown

**Comment by anuraghazra** [comment]
Thanks for requesting the feature @filiptronicek this sounds good, i'll see what i can do. 
related to #66

**Comment by SukkaW** [comment]
> 1. It would be best if you could query the [@prefers-color-scheme data of the browser](https://developer.mozilla.org/en-US/docs/Web/CSS/@media/prefers-color-scheme), as no timezone or other preference data would be needed.

It is nearly impossible to get the `media query` through an image element. And of course GitHub won't let you inject any `<style>` or `<script>` tag. It is just impossible.

An alternative is using `<picture>` and `<source>` tag:

```html
   <picture>
      <source 
        srcset="settings-dark.png"
        media="(prefers-color-scheme: dark)"
      />
      <source
        srcset="settings-light.png"
        media="(prefers-color-scheme: light), (prefers-color-scheme: no-preference)"
      />
      <img src="settings-light.png" id="screenshot" loading="lazy" />
    </picture>
```

But I am not sure whether GitHub will allow us to use the `<picture>` & `source` tag.

**Comment by anuraghazra** [comment]
@SukkaW true, but the issue is not about whether github supports style/script tags or not, we can put style tag on SVG and we are also doing CSS animations there, but the real problem is even if i put `prefer-color-scheme` media queries it would not change because the svg is rendered and uploaded to github's CDNs (although i did not tested if it works)

I have to do some testing to see if it works.

**Comment by filiptronicek** [comment]
Let's see if this works: @SukkaW @anuraghazra 
   <picture>
      <source 
        srcset="https://files.catbox.moe/shuph5.png"
        media="(prefers-color-scheme: dark)"
      />
      <source
        srcset="https://files.catbox.moe/zhopye.png"
        media="(prefers-color-scheme: light), (prefers-color-scheme: no-preference)"
      />
      <img src="https://files.catbox.moe/zhopye.png" />
    </picture>

**Comment by anuraghazra** [comment]
@filiptronicek worked? Also even if it's works, kinda too much boilerplate and same as just swaping the colors (which we are doing right now) 

So we can just render the white card on light mode and black on dark mode

**Comment by filiptronicek** [comment]
Tried changing my preference on Chrome Beta, doesn't look like it would work :(

**Comment by SukkaW** [comment]
@anuraghazra 

![image](https://user-images.githubusercontent.com/40715044/87778991-a8a3a780-c85e-11ea-9a44-cfcf7e202b08.png)

![image](https://user-images.githubusercontent.com/40715044/87779013-b5c09680-c85e-11ea-95f1-8736ef8c89eb.png)

No, it doesn't.

**Comment by rjoydip** [comment]
Hello folks, for dark mode it's working in my local. Hope I will able to produce some update after deploy it and verify it in live mode.

**Comment by filiptronicek** [comment]
@rjoydip that would be awesome! Super excited to see it in action

**Comment by anuraghazra** [comment]
> Hello folks, for dark mode it's working in local. Hope I will able to produce some update after deploy it and verify it in live mode.

Yes these stuff works locally but not in production because we are not serving directly from the server, github will reupload and serve from their CDNs. 

Same issue I faced when detecting user agent #45

**Comment by rjoydip** [comment]
@filiptronicek @anuraghazra 
Plese checkout below link of live deployment. It's working
https://github-readme-stats.rjoydip.vercel.app/api?username=rjoydip&show_icons=true

**Comment by anuraghazra** [comment]
@rjoydip cool then, open the PR! :100:

**Comment by rjoydip** [comment]
Yes, but I will check with this in my `README` once before PR.

**Comment by anuraghazra** [comment]
I'm still wondering why @filiptronicek's experiment failed, did you used the media queries inside the picture tag?

**Comment by SukkaW** [comment]
@anuraghazra I will bring up my own test again.


```html
<picture>
      <source 
        srcset="https://via.placeholder.com/1000x618.png?text=Dark+Mode"
        media="(prefers-color-scheme: dark)"
      />
      <source
        srcset="https://via.placeholder.com/1000x618.png?text=Light+Mode"
        media="(prefers-color-scheme: light), (prefers-color-scheme: no-preference)"
      />
      <img src="https://via.placeholder.com/1000x618.png?text=Light+Mode" />
</picture>
```

<picture>
      <source 
        srcset="https://via.placeholder.com/1000x618.png?text=Dark+Mode"
        media="(prefers-color-scheme: dark)"
      />
      <source
        srcset="https://via.placeholder.com/1000x618.png?text=Light+Mode"
        media="(prefers-color-scheme: light), (prefers-color-scheme: no-preference)"
      />
      <img src="https://via.placeholder.com/1000x618.png?text=Light+Mode" />
</picture>

**Comment by anuraghazra** [comment]
Yeah, Github does support SVG based CSS thats why we could do animations and stuff but not picture tags. so using media queries on picture tag wont work

``svg
<picture>
      <source 
        srcset="https://via.placeholder.com/1000x618.png?text=Dark+Mode"
        media="(prefers-color-scheme: dark)"
      />
      <source
        srcset="https://via.placeholder.com/1000x618.png?text=Light+Mode"
        media="(prefers-color-scheme: light), (prefers-color-scheme: no-preference)"
      />
      <img src="https://via.placeholder.com/1000x618.png?text=Fallback+Mode" />
</picture>
``

**Comment by k06a** [comment]
Was it solved?

**Comment by filiptronicek** [comment]
@k06a yes, in short, it can't be done as of now, sounds like a nice thing to request from GitHub over at https://github.com/github/feedback/discussions 👀

**Comment by RodrigoTomeES** [comment]
Hi everyone,

I got a workaround for prefers-color-scheme CSS media feature. I implemented it for [github-readme-activity-graph](https://github.com/Ashutosh00710/github-readme-activity-graph) in this [pull request](https://github.com/Ashutosh00710/github-readme-activity-graph/pull/107). I think it would be easy reply the same here.

I made a readme with the workaround and you can see [here](https://github.com/RodrigoTomeES/prefers-color-scheme-hack) but... here is a little spoiler

![example](https://user-images.githubusercontent.com/13077343/154822005-9f197ca4-4edb-4c17-92be-45ab5807d75a.svg)

So let's go 🚀

**Comment by anuraghazra** [comment]
> Hi everyone,
> 
> I got a workaround for prefers-color-scheme CSS media feature. I implemented it for [github-readme-activity-graph](https://github.com/Ashutosh00710/github-readme-activity-graph) in this [pull request](https://github.com/Ashutosh00710/github-readme-activity-graph/pull/107). I think it would be easy reply the same here.
> 
> I made a readme with the workaround and you can see [here](https://github.com/RodrigoTomeES/prefers-color-scheme-hack) but... here is a little spoiler
> 
> ![example](https://user-images.githubusercontent.com/13077343/154822005-9f197ca4-4edb-4c17-92be-45ab5807d75a.svg)
> 
> So let's go 🚀

I don't think this works, and we already tried this out. 
There is a better option available. with github's new darkmode switching URLs
https://github.com/anuraghazra/github-readme-stats/discussions/1415#discussioncomment-2152317

**Comment by RodrigoTomeES** [comment]
> 

Hi,

The SVG works, just change your browser preferences an check that Github setting follow this. But maybe you're right, I didn't know that functionality.


https://user-images.githubusercontent.com/13077343/154837756-b270948f-990c-43f0-a20d-3ec7d33c44f0.mp4

**Comment by jx11r** [comment]
@RodrigoTomeES Hi, I like the idea, but I tried this in the GitHub App, it didn't work.

**Comment by RodrigoTomeES** [comment]
> @RodrigoTomeES Hi, I like the idea, but I tried this in the GitHub App, it didn't work.

Hi, yes GitHub App isn't compatible because always return light them 😢

**Comment by Rudxain** [comment]
![](https://camo.githubusercontent.com/a73b2eab7473a74368a0c4c5b0523edc43131a951b6260621f45b3c4a6eb0860/68747470733a2f2f66696c65732e636174626f782e6d6f652f7a686f7079652e706e67)

```
<picture>
      <source 
        srcset="https://via.placeholder.com/1000x618.png?text=Dark+Mode"
        media="(prefers-color-scheme: dark)"
      />
      <source
        srcset="https://via.placeholder.com/1000x618.png?text=Light+Mode"
        media="(prefers-color-scheme: light), (prefers-color-scheme: no-preference)"
      />
      <img src="https://via.placeholder.com/1000x618.png?text=Fallback+Mode" />
</picture>
```

![example](https://user-images.githubusercontent.com/13077343/154822005-9f197ca4-4edb-4c17-92be-45ab5807d75a.svg)

@filiptronicek , @SukkaW , @RodrigoTomeES  All of these work in Firefox for GNU-Linux-x64 (Debian base) now! I still need to test in other browsers
