### ISSUE TITLE
Broken rendering

### ISSUE THREAD

**Issue by rishit-khandelwal** [anuraghazra/github-readme-stats#792]
![Screenshot](https://user-images.githubusercontent.com/65018379/104047795-3f4a9300-5208-11eb-81fa-95e405480ed3.jpg)

This is what I see on GitHub android app.

**Comment by sci4me** [comment]
Potential duplicate of/related to #776 and/or #664?

**Comment by rishit-khandelwal** [comment]
Oh... I will close the issue then
