### ISSUE TITLE
Problem with russian translation of statistics card

### ISSUE THREAD

**Issue by qwerty541** [anuraghazra/github-readme-stats#793]
I think it can be fixed by merging #614 

![image](https://user-images.githubusercontent.com/53787217/104075738-627f3d80-521c-11eb-84f7-b50e7e8bdcee.png)

**Comment by anuraghazra** [comment]
fixed by #614

**Comment by qwerty541** [comment]
> fixed by #614

When you have free time, please review #616. After merging this pull request card translations code will become shorter with the same functionality.
