### ISSUE TITLE
Unable to wrap the repo title when it gets too long

### ISSUE THREAD

**Issue by kishan0725** [anuraghazra/github-readme-stats#80]
**Bug description**
When the name of the repository gets too long, the `github-readme-stats` card hides some part of the repo name, instead of wrapping them up.

**Expected behavior**
When the repo name gets too long, it should come to the next line. 

**Screenshot**
![image](https://user-images.githubusercontent.com/36665975/87674331-7da05180-c793-11ea-8d80-fbf045b17c0d.png)

**Comment by anuraghazra** [comment]
Thanks for reporting the issue @kishan0725 i'll try to fix this asap.

**Comment by HaaLeo** [comment]
This was fixed in #206

**Comment by anuraghazra** [comment]
@HaaLeo no no he is talking about the Title of the Repo not the description.

**Comment by HaaLeo** [comment]
Yup sorry my bad 🤗

**Comment by kishan0725** [comment]
@anuraghazra @HaaLeo  - Still the description is not rendering properly.

![image](https://user-images.githubusercontent.com/36665975/88547401-4eaf9880-d03b-11ea-9e73-99b6b4a30bcb.png)

**Comment by HaaLeo** [comment]
The repo card description renders just fine when setting the default [`width`](https://github.com/anuraghazra/github-readme-stats/blob/11757dba428e93ef4d9497685b732109cc6592c9/src/utils.js#L131) to `55` again:

<img width="922" alt="image" src="https://user-images.githubusercontent.com/23164374/88557982-3899dc00-d02b-11ea-9f62-6ce9d74c92a9.png">

@anuraghazra you want to change it back to `55`?

**Comment by anuraghazra** [comment]
@HaaLeo yeah i'll change that

**Comment by kishan0725** [comment]
@anuraghazra Why don't we use `card_width` property to overcome this issue?
