### ISSUE TITLE
Github Status Card is showing invalid data for the stat: Total Commits(2021)

### ISSUE THREAD

**Issue by azhar-azad** [anuraghazra/github-readme-stats#802]

**Comment by jscastro76** [comment]
Same here... I have hundreds, and it only show's the commits in the personal repo.

**Comment by anuraghazra** [comment]
Please provide more info for debugging the issue. 

And for @jscastro76 
I see why your stats shows 14 commits. now see github's official contribution chart is showing data from jan 2020 to jan 2021 in your case..
![image](https://user-images.githubusercontent.com/35374649/104464355-d6349800-55d8-11eb-8cab-bda4a5c8313e.png)

But actually in 2021 your total commits are 15 only
URL: https://github.com/jscastro76?tab=overview&from=2021-01-01&to=2021-01-13
![image](https://user-images.githubusercontent.com/35374649/104464408-e6e50e00-55d8-11eb-8c9e-a36c44bc174d.png)


And here's graphql response which we just fetch: 
![image](https://user-images.githubusercontent.com/35374649/104464509-0419dc80-55d9-11eb-88d8-bc1d95676b61.png)

**Comment by jscastro76** [comment]
First of all @anuraghazra thanks for this plugin... it's super useful!!
So based on your comments `include_all_commits=true` only takes the commits from January 1st 2021, right??

**Comment by Andre601** [comment]
My card shows `2.2k` for the year 2021 (`Total Commits (2021): 2.2k`)

Why I would love to have those total commits for this single month do I highly doubt that this is actually accurate and doesn't represent the Total commits of 2021 since it just started yet.

**Comment by anuraghazra** [comment]
> First of all @anuraghazra thanks for this plugin... it's super useful!!
> So based on your comments `include_all_commits=true` only takes the commits from January 1st 2021, right?? Is there any option to show the total commits across different years?

Oh yeah right sorry I did not noticed that you had include_all_commits enabled... yeah i find it weird that even when it's enabled github is not returning all the commits.

For fetching all the commits we use github commit search API: https://docs.github.com/en/github/searching-for-information-on-github/searching-commits.

Here's the source code:
https://github.com/anuraghazra/github-readme-stats/blob/dff732adf54a34ae10b218dd36e0697d3c0b18d6/src/fetchers/stats-fetcher.js#L61-L71

And here's what is returned from the github API: 
![image](https://user-images.githubusercontent.com/35374649/104811846-64e92500-5824-11eb-8eb9-2c901bb58987.png)

**Comment by anuraghazra** [comment]
Oh wait @jscastro76 I think we are missing a crucial point. 

As far as i'm seeing most of your "contributions" are by opening issues on other repos. not actually committing to github.. that's why commit count is 17 which is actually correct.

And what github's contribution chart shows is all of them combined. issues/prs/commits/discussions all of them are counted as "contribution"

**Comment by anuraghazra** [comment]
> My card shows `2.2k` for the year 2021 (`Total Commits (2021): 2.2k`)
> 
> Why I would love to have those total commits for this single month do I highly doubt that this is actually accurate and doesn't represent the Total commits of 2021 since it just started yet.

It is accurate and it actually just shows previous 1 year's commits. 

note: https://github.com/anuraghazra/github-readme-stats/issues/802#issuecomment-759481539 this comment is outdated and wrong.

**Comment by jscastro76** [comment]
@anuraghazra you could be right but only in the main repo I’m contributing I’ve done 131 commits
![EFC3B041-4458-4C51-80B0-0CF4E4110D9E](https://user-images.githubusercontent.com/38470852/104814264-3eb88a80-580e-11eb-8af5-fc697f511163.jpeg)

**Comment by anuraghazra** [comment]
> @anuraghazra you could be right but only in the main repo I’m contributing I’ve done 131 commits
> ![EFC3B041-4458-4C51-80B0-0CF4E4110D9E](https://user-images.githubusercontent.com/38470852/104814264-3eb88a80-580e-11eb-8af5-fc697f511163.jpeg)

Forks won't count.

**Comment by jscastro76** [comment]
> 
> Forks won't count.

That’s the caveat then! Thanks for answering!

**Comment by anuraghazra** [comment]
Yes github also does not counts forked repo commits.

https://docs.github.com/en/github/setting-up-and-managing-your-github-profile/why-are-my-contributions-not-showing-up-on-my-profile
![image](https://user-images.githubusercontent.com/35374649/104836576-c8329000-58d4-11eb-9bfa-fbbd2ff94b2a.png)

**Comment by jscastro76** [comment]
@anuraghazra thanks again for your amazing work!
