### ISSUE TITLE
Problems with translations of statistics card

### ISSUE THREAD

**Issue by qwerty541** [anuraghazra/github-readme-stats#812]
Should be fixed by merging #804 

![chrome_m1qr54SEE3](https://user-images.githubusercontent.com/53787217/104682359-2147cb80-56fd-11eb-8f5e-96b12886f4c2.png)

![chrome_k4XQPdIlYz](https://user-images.githubusercontent.com/53787217/104682365-2573e900-56fd-11eb-8bce-08997c236a39.png)

![chrome_O00IfHUBQ1](https://user-images.githubusercontent.com/53787217/104682380-302e7e00-56fd-11eb-800d-0d740c761072.png)

![chrome_6gSvD5F0wY](https://user-images.githubusercontent.com/53787217/104682390-345a9b80-56fd-11eb-8174-7b83d88afda0.png)

![chrome_ujyXjGb7wi](https://user-images.githubusercontent.com/53787217/104682397-391f4f80-56fd-11eb-8e1a-69e04ffd3759.png)

**Comment by anuraghazra** [comment]
fixed in #804
