### ISSUE TITLE
For some languages the available options have not been updated

### ISSUE THREAD

**Issue by uskey512** [anuraghazra/github-readme-stats#815]
**Is your feature request related to a problem? Please describe.**
For some languages, the available options have not been updated.

**Describe the solution you'd like**
want to keep the parameters available on the documentation up to date.

**Additional context**
The following table summarizes the parameters described in the current document.

<table>
	<tr>
		<th>English</th>
		<th>Français</th>
		<th>简体中文</th>
		<th>Español</th>
		<th>Deutsch</th>
		<th>日本語</th>
		<th>Português Brasileiro</th>
		<th>Italiano</th>
		<th>한국어</th>
		<th>Nederlands</th>
		<th>Türkçe</th>
	</tr>
	<tr>
		<th>Common</th>
		<td></td>
		<td></td>
		<td></td>
		<td></td>
		<td></td>
		<td></td>
		<td></td>
		<td></td>
		<td></td>
		<td></td>
	</tr>
	<tr>
		<th>title_color</th>
		<td>o</td>
		<td>o</td>
		<td>o</td>
		<td>o</td>
		<td>o</td>
		<td>o</td>
		<td>o</td>
		<td>o</td>
		<td>o</td>
		<td>o</td>
	</tr>
	<tr>
		<th>text_color</th>
		<td>o</td>
		<td>o</td>
		<td>o</td>
		<td>o</td>
		<td>o</td>
		<td>o</td>
		<td>o</td>
		<td>o</td>
		<td>o</td>
		<td>o</td>
	</tr>
	<tr>
		<th>icon_color</th>
		<td>o</td>
		<td>o</td>
		<td>o</td>
		<td>o</td>
		<td>o</td>
		<td>o</td>
		<td>o</td>
		<td>o</td>
		<td>o</td>
		<td>o</td>
	</tr>
	<tr>
		<th>bg_color</th>
		<td>o</td>
		<td>o</td>
		<td>o</td>
		<td>o</td>
		<td>o</td>
		<td>o</td>
		<td>o</td>
		<td>o</td>
		<td>o</td>
		<td>o</td>
	</tr>
	<tr>
		<th>hide_border</th>
		<td>o</td>
		<td>o</td>
		<td>o</td>
		<td>o</td>
		<td>o</td>
		<td>o</td>
		<td>o</td>
		<td>o</td>
		<td>o</td>
		<td>o</td>
	</tr>
	<tr>
		<th>theme</th>
		<td>o</td>
		<td>o</td>
		<td>o</td>
		<td>o</td>
		<td>o</td>
		<td>o</td>
		<td>o</td>
		<td>o</td>
		<td>o</td>
		<td>o</td>
	</tr>
	<tr>
		<th>cache_seconds</th>
		<td>o</td>
		<td>o</td>
		<td>o</td>
		<td>o</td>
		<td>o</td>
		<td>o</td>
		<td>o</td>
		<td>o</td>
		<td>o</td>
		<td>o</td>
	</tr>
	<tr>
		<th>locale</th>
		<td>o</td>
		<td>o</td>
		<td>o</td>
		<td>o</td>
		<td>o</td>
		<td>o</td>
		<td>o</td>
		<td>o</td>
		<td>o</td>
		<td>o</td>
	</tr>
	<tr>
		<th></th>
		<td></td>
		<td></td>
		<td></td>
		<td></td>
		<td></td>
		<td></td>
		<td></td>
		<td></td>
		<td></td>
		<td></td>
	</tr>
	<tr>
		<th>StatsCard</th>
		<td></td>
		<td></td>
		<td></td>
		<td></td>
		<td></td>
		<td></td>
		<td></td>
		<td></td>
		<td></td>
		<td></td>
	</tr>
	<tr>
		<th>hide</th>
		<td>o</td>
		<td>o</td>
		<td>o</td>
		<td>o</td>
		<td>o</td>
		<td>o</td>
		<td>o</td>
		<td>o</td>
		<td>o</td>
		<td>o</td>
	</tr>
	<tr>
		<th>hide_title</th>
		<td>o</td>
		<td>o</td>
		<td>o</td>
		<td>o</td>
		<td>o</td>
		<td>o</td>
		<td>o</td>
		<td>o</td>
		<td>o</td>
		<td>o</td>
	</tr>
	<tr>
		<th>hide_rank</th>
		<td>o</td>
		<td>o</td>
		<td>o</td>
		<td>o</td>
		<td>o</td>
		<td>o</td>
		<td>o</td>
		<td>o</td>
		<td>o</td>
		<td>o</td>
	</tr>
	<tr>
		<th>hide_border</th>
		<td>o</td>
		<td>o</td>
		<td>o</td>
		<td>o</td>
		<td>o</td>
		<td>o</td>
		<td>o</td>
		<td>o</td>
		<td>o</td>
		<td>o</td>
	</tr>
	<tr>
		<th>show_icons</th>
		<td>o</td>
		<td>o</td>
		<td>o</td>
		<td>o</td>
		<td>o</td>
		<td>o</td>
		<td>o</td>
		<td>o</td>
		<td>o</td>
		<td>o</td>
	</tr>
	<tr>
		<th>include_all_commits</th>
		<td>o</td>
		<td>o</td>
		<td>o</td>
		<td>o</td>
		<td>o</td>
		<td>o</td>
		<td>o</td>
		<td>o</td>
		<td>o</td>
		<td>o</td>
	</tr>
	<tr>
		<th>count_private</th>
		<td>o</td>
		<td>o</td>
		<td>o</td>
		<td>o</td>
		<td>o</td>
		<td>o</td>
		<td>o</td>
		<td>o</td>
		<td>o</td>
		<td>o</td>
	</tr>
	<tr>
		<th>line_height</th>
		<td>o</td>
		<td>o</td>
		<td>o</td>
		<td>o</td>
		<td>o</td>
		<td>o</td>
		<td>o</td>
		<td>o</td>
		<td>o</td>
		<td>o</td>
	</tr>
	<tr>
		<th>custom_title</th>
		<td>x</td>
		<td>o</td>
		<td>x</td>
		<td>x</td>
		<td>x</td>
		<td>x</td>
		<td>x</td>
		<td>o</td>
		<td>o</td>
		<td>o</td>
	</tr>
	<tr>
		<th>disable_animations</th>
		<td>x</td>
		<td>x</td>
		<td>x</td>
		<td>x</td>
		<td>x</td>
		<td>x</td>
		<td>x</td>
		<td>o</td>
		<td>x</td>
		<td>o</td>
	</tr>
	<tr>
		<th></th>
		<td></td>
		<td></td>
		<td></td>
		<td></td>
		<td></td>
		<td></td>
		<td></td>
		<td></td>
		<td></td>
		<td></td>
	</tr>
	<tr>
		<th>RepoCard</th>
		<td></td>
		<td></td>
		<td></td>
		<td></td>
		<td></td>
		<td></td>
		<td></td>
		<td></td>
		<td></td>
		<td></td>
	</tr>
	<tr>
		<th>show_owner</th>
		<td>o</td>
		<td>o</td>
		<td>o</td>
		<td>o</td>
		<td>o</td>
		<td>o</td>
		<td>o</td>
		<td>o</td>
		<td>o</td>
		<td>o</td>
	</tr>
	<tr>
		<th></th>
		<td></td>
		<td></td>
		<td></td>
		<td></td>
		<td></td>
		<td></td>
		<td></td>
		<td></td>
		<td></td>
		<td></td>
	</tr>
	<tr>
		<th>Lang</th>
		<td></td>
		<td></td>
		<td></td>
		<td></td>
		<td></td>
		<td></td>
		<td></td>
		<td></td>
		<td></td>
		<td></td>
	</tr>
	<tr>
		<th>hide</th>
		<td>o</td>
		<td>o</td>
		<td>o</td>
		<td>o</td>
		<td>o</td>
		<td>o</td>
		<td>o</td>
		<td>o</td>
		<td>o</td>
		<td>o</td>
	</tr>
	<tr>
		<th>hide_title</th>
		<td>o</td>
		<td>o</td>
		<td>o</td>
		<td>o</td>
		<td>o</td>
		<td>o</td>
		<td>o</td>
		<td>o</td>
		<td>o</td>
		<td>o</td>
	</tr>
	<tr>
		<th>hide_border</th>
		<td>o</td>
		<td>o</td>
		<td>o</td>
		<td>o</td>
		<td>o</td>
		<td>o</td>
		<td>o</td>
		<td>o</td>
		<td>o</td>
		<td>o</td>
	</tr>
	<tr>
		<th>layout</th>
		<td>o</td>
		<td>o</td>
		<td>o</td>
		<td>o</td>
		<td>o</td>
		<td>o</td>
		<td>o</td>
		<td>o</td>
		<td>o</td>
		<td>o</td>
	</tr>
	<tr>
		<th>card_width</th>
		<td>o</td>
		<td>o</td>
		<td>o</td>
		<td>o</td>
		<td>o</td>
		<td>o</td>
		<td>o</td>
		<td>o</td>
		<td>o</td>
		<td>o</td>
	</tr>
	<tr>
		<th>langs_count</th>
		<td>x</td>
		<td>x</td>
		<td>x</td>
		<td>x</td>
		<td>x</td>
		<td>x</td>
		<td>x</td>
		<td>o</td>
		<td>o</td>
		<td>o</td>
	</tr>
	<tr>
		<th>exclude_repo</th>
		<td>x</td>
		<td>x</td>
		<td>x</td>
		<td>x</td>
		<td>x</td>
		<td>x</td>
		<td>x</td>
		<td>o</td>
		<td>o</td>
		<td>o</td>
	</tr>
	<tr>
		<th>custom_title</th>
		<td>x</td>
		<td>x</td>
		<td>x</td>
		<td>x</td>
		<td>x</td>
		<td>x</td>
		<td>x</td>
		<td>o</td>
		<td>o</td>
		<td>o</td>
	</tr>
</table>

**Comment by anuraghazra** [comment]
resolved in #816.

**Comment by uskey512** [comment]
@anuraghazra 
Oh, I'm sorry.

The pull request I made will only resolve the differences in the Japanese README.
For other languages, I don't think I can provide a translation of better quality than machine translation :( 

Other languages will continue to need to be supported.

The current translation status is as follows.
- English (original)
- [ ] Français
- [ ] 简体中文
- [ ] Español
- [ ] Deutsch
- [x] 日本語
- [ ] Português Brasileiro
- [ ] Italiano
- [x] 한국어
- [ ] Nederlands
- [x] Türkçe

**Comment by anuraghazra** [comment]
Then we can reopen this and progressively improve them
