### ISSUE TITLE
Top langs

### ISSUE THREAD

**Issue by GabiRP** [anuraghazra/github-readme-stats#831]
**Describe the bug**
Top Langs on my username are not showing.

**Expected behavior**
The top lags should show.

**Screenshots / Live demo link (paste the github-readme-stats link as markdown image)**
![image](https://user-images.githubusercontent.com/57387907/105520210-b12bdd80-5cda-11eb-91f9-ad26bac8ef11.png)

**Additional context**
I don't know if it's a bug, but is not working for me.

**Comment by harshhhdev** [comment]
This is because you don't have any languages for it to get data from.

Two forks, which it can't get language data from. And the your profile readme which has no language data.

![image](https://user-images.githubusercontent.com/69592270/105523433-5bd8d780-5cac-11eb-9a6a-1002e6083e5e.png)

**Comment by harshhhdev** [comment]
For it to show the languages, add some repos with normal code which aren't forks :smile:

**Comment by GabiRP** [comment]
Ok, thanks!
