### ISSUE TITLE
Wakatime week stats isn't working

### ISSUE THREAD

**Issue by FahimFBA** [anuraghazra/github-readme-stats#838]
**Describe the bug**
Wakatime week stats aren't working properly in profile README.md. The stats kept on showing about 10 hours+ in the dashboard but showing as null in the profile stats.

![Screenshot (972)](https://user-images.githubusercontent.com/64195132/105991946-a1433d80-60ce-11eb-9c98-cb7dcea5b075.png)

**Expected behavior**
The stats card should display the proper time stats as showing in the Wakatime site dashboard.
![Screenshot (973)](https://user-images.githubusercontent.com/64195132/105992054-cf288200-60ce-11eb-9725-501765a19a06.png)

**Screenshots / Live demo link (paste the github-readme-stats link as markdown image)**
Link: https://github.com/FahimFBA/FahimFBA
Screenshots have been added in the upper portion.

**Comment by ooobsidian** [comment]
I had the same problem.

**Comment by Sciroccogti** [comment]
Mine solved by #632

**Comment by ooobsidian** [comment]
thank you

**Comment by FahimFBA** [comment]
> Mine solved by #632

Thanks a bunch!
Solved the issue!!! @Sciroccogti

**Comment by Sciroccogti** [comment]
Sadly mine isn't working now... Maybe I just need to wait for some hours?

**Comment by FahimFBA** [comment]
> Sadly mine isn't working now... Maybe I just need to wait for some hours?

Can I check yours and if I can solve it, then can I send you a pull req?

**Comment by FahimFBA** [comment]
> Sadly mine isn't working now... Maybe I just need to wait for some hours?

Have you connected your Wakatime with your Github?

**Comment by Sciroccogti** [comment]
> Have you connected your Wakatime with your Github?

I signed up wakatime with my GitHub account. And I also installed the [GitHub Integration](https://wakatime.com/integrations/github), though I don't think this matters.

My profile seems to be accessible to public too: https://wakatime.com/@Sciroccogti

What else should I do? 😔

**Comment by Sciroccogti** [comment]
I noticed that yours is down again..

![图片](https://user-images.githubusercontent.com/32357397/106986028-7bd8c280-67a5-11eb-8171-aa5fd0abfad6.png)

**Comment by FahimFBA** [comment]
> I noticed that yours is down again...
> 
> ![图片](https://user-images.githubusercontent.com/32357397/106986028-7bd8c280-67a5-11eb-8171-aa5fd0abfad6.png)

You're right brother. Mine is down too whereas my wife's stats is working fine although we used the same method :(

**Comment by mmvanheusden** [comment]
Mine isn't working either...

**Comment by mmvanheusden** [comment]
ah, it seems changing Display code time publicly to the default (Last 7 Days) fixes the problem

**Comment by Sciroccogti** [comment]
> ah, it seems changing Display code time publicly to the default (Last 7 Days) fixes the problem
> 
> on the profile settings on the WakaTime website

Genius! It's working now! Thank you so much!
