### ISSUE TITLE
Total commits value shows arbitrary number of commits

### ISSUE THREAD

**Issue by kshitijzutshi** [anuraghazra/github-readme-stats#839]
**Describe the bug**
The Total commits shows arbitrary number of commits which are not correct

**Expected behavior**
Should be same number of commits as my GitHub contributions chart.
**Screenshots / Live demo link (paste the github-readme-stats link as markdown image)**
![image](https://user-images.githubusercontent.com/13203059/106002388-14e94880-60d7-11eb-9fae-7374db168c9d.png)

**Additional context**

**Comment by anuraghazra** [comment]
The stats shows commits from past 365days.

**Comment by kshitijzutshi** [comment]
Yes, So I have no commits till Feb 26 2020, from then if i see in stats its 504 in 2020 and 34 till now in 2021. I couldn't understand how 319 was calculated. 😅
![image](https://user-images.githubusercontent.com/13203059/106003231-02bbda00-60d8-11eb-864b-3d595c0a36e6.png)

**Comment by anuraghazra** [comment]
It counts from THIS day to previous 365days

Also you are not counting private commits and github contribution chart does not just shows `commits` it also shows `issues`, `prs` etc etc

**Comment by kshitijzutshi** [comment]
https://docs.github.com/en/github/setting-up-and-managing-your-github-profile/why-are-my-contributions-not-showing-up-on-my-profile

**Issues, pull requests and discussions will appear on your contribution graph if they were opened in a standalone repository, not a fork.**

Oh okay got it. @anuraghazra Thanks for the proactive response.

**Comment by kshitijzutshi** [comment]
@anuraghazra On a side note:  If its not too much to ask, I am looking for ways to contribute open source. If there is a task which i can handle or assist you in any way, It would be great if you could let me know!. 😃

**Comment by Nixinova** [comment]
> The stats shows commits from past 365days.

Then it should say that instead of saying &lt;current year>. Just confusing that way.

**Comment by anuraghazra** [comment]
> > The stats shows commits from past 365days.
> 
> Then it should say that instead of saying <current year>. Just confusing that way.

True lot of people are confused about it I'm trying to find a way to properly indicate that without ruining the whole card design 😆 because saying "Total commits (past 365days)" is long

I've tried with (vote with reactions)

👍 "Total commits (<365days)"
❤️ "Total commits (<1year)"
🎉 "Total commits (<1yr)"
🚀  "Total commits (prev year)"

**Comment by Nixinova** [comment]
Many "Total commits (annual)"?

**Comment by tfossum-bingo** [comment]
May I suggest: "Commits (<=365 days)"...?
