### ISSUE TITLE
Choose which Github Dark Theme

### ISSUE THREAD

**Issue by 2br-2b** [anuraghazra/github-readme-stats#844]
Since there's already 5 PRs about this (one of which is mine), there should probably be an issue for this.

Which dark mode theme should be added?

Our current options:

#691 by @ErickSimoes

![ErickSimoes](https://camo.githubusercontent.com/c2e66e9d2b159843ef1fda989421ed447062562f269c75d6c1f414ec282143f2/68747470733a2f2f6769746875622d726561646d652d73746174732e76657263656c2e6170702f6170693f757365726e616d653d616e7572616768617a7261267469746c655f636f6c6f723d6339643164392669636f6e5f636f6c6f723d38623934396526746578745f636f6c6f723d3862393439652662675f636f6c6f723d3064313131372673686f775f69636f6e733d74727565)

#758 by @issy

![issy](https://camo.githubusercontent.com/195dd6b27f87ab1a33a6443147982310e50442f1cf39ba3c25fd03d6d510a5c1/68747470733a2f2f6769746875622d726561646d652d73746174732e76657263656c2e6170702f6170693f757365726e616d653d616e7572616768617a7261267469746c655f636f6c6f723d3538413646462669636f6e5f636f6c6f723d31463646454226746578745f636f6c6f723d4333443144392662675f636f6c6f723d3044313131372673686f775f69636f6e733d74727565)

#811 by @microhod

![microhod](https://camo.githubusercontent.com/eecedf7a9c8a899df6c0351e1ff81efd9146aec16f04d1bb4ecacee4120876e8/68747470733a2f2f6769746875622d726561646d652d73746174732e76657263656c2e6170702f6170693f757365726e616d653d616e7572616768617a7261267469746c655f636f6c6f723d6666666666662669636f6e5f636f6c6f723d35384136464626746578745f636f6c6f723d3842393439452662675f636f6c6f723d3044313131372673686f775f69636f6e733d74727565)

#823 by @hd4y2t

![hd4y2t](https://camo.githubusercontent.com/4451e419e981a9a4dd6b1f49ad16c948d2ba990d766984134df0163906410cec/68747470733a2f2f6769746875622d726561646d652d73746174732e76657263656c2e6170702f6170693f757365726e616d653d616e7572616768617a7261267469746c655f636f6c6f723d6339643164392669636f6e5f636f6c6f723d63396431643926746578745f636f6c6f723d6339643164392662675f636f6c6f723d3064313131372673686f775f69636f6e733d74727565)

#843 by @2br-2b

![2br-2b](https://camo.githubusercontent.com/906c3ff1af3bc8b9ef3c12c5a60fb872af970bcc00ef29e18a653d7196ee0664/68747470733a2f2f6769746875622d726561646d652d73746174732e76657263656c2e6170702f6170693f757365726e616d653d616e7572616768617a7261267469746c655f636f6c6f723d3538613666662669636f6e5f636f6c6f723d38623934396526746578745f636f6c6f723d3862393439332662675f636f6c6f723d3064313131372673686f775f69636f6e733d74727565)

Related to issues #25, #79, #689, and many others

**Comment by ErickSimoes** [comment]
Can I vote for mine?

**Comment by ErickSimoes** [comment]
If I can't vote for mine, I choose #758 by @issy

**Comment by hd4y2t** [comment]
it's so hard

**Comment by 2br-2b** [comment]
When making my dark theme, I did my best to mirror the colors from a pinned repo from the Github profile screen. I'd post a screenshot, but my screenshot tool is changing the colors in the screenshot for some reason.

**Comment by antoniosuperba** [comment]
> wordpress theme with the same period last month that the world money cash APPLY to be the first to admit that are not only found one.[]( https://p2guide.wordpress.com/blog/)

**Comment by microhod** [comment]
> If I can't vote for mine, I choose #758 by @issy

Yeah I agree, if I ignore my preference for my own, I'd vote #758 (although I'd prefer if it was modified slightly so that all the shades of blue match).

In general I feel like the colours 'pop' better in the ones that include the blue.

**Comment by alik604** [comment]
if my vote matters: 
id say `#758 by @issy`. maybe with the offwhite text more white/bright

**Comment by 2br-2b** [comment]
Hi @alik604 ! Of course every opinion matters!

It seems quite clear that #758 is the most popular choice.

@microhod , could you post an example of what you're talking about so that we can compare it with the current version?

Also, could someone who has a working screenshot tool post a picture of #758 in a home screen? That way, we can see what the final result looks like.

**Comment by Karthik-Nayak98** [comment]
I would choose #758 by @issy. Because it looks much bright than others.

**Comment by 2br-2b** [comment]
Keep in mind that not everyone uses dark mode. The chosen theme should look good in dark mode and light mode.

**Comment by issy** [comment]
Here is a picture of my theme in action. First pic is in light mode
![IMG_20210213_202540.jpg](https://user-images.githubusercontent.com/48881813/107860855-c8716d00-6e39-11eb-83d9-b9864d9cb759.jpg)
![IMG_20210213_202733.jpg](https://user-images.githubusercontent.com/48881813/107860909-10908f80-6e3a-11eb-8acf-2e1debbd8592.jpg)
You can check this out yourself on my profile :)

**Comment by Karthik-Nayak98** [comment]
If there is border then we can differentiate between the colors of the card and background.

**Comment by issy** [comment]
> If there is border then we can differentiate between the colors of the card and background.

They are the same colour, there is no border

**Comment by 2br-2b** [comment]
If there are no objections, I think it's okay to merge #758 and close the other 4 PRs @anuraghazra

**Comment by ErickSimoes** [comment]
I agree 👍

**Comment by 2br-2b** [comment]
Any updates on this?

**Comment by anuraghazra** [comment]
Choosing #758 because of it's good contrast and visibility compared to others.

**Comment by anuraghazra** [comment]
Closed via #758
