### ISSUE TITLE
How to control the height of the repo card？

### ISSUE THREAD

**Issue by Fatpandac** [anuraghazra/github-readme-stats#851]
**Is your feature request related to a problem? Please describe.**
I want to control the height of the repo card.

**Additional context**
![image](https://user-images.githubusercontent.com/30423976/106377893-3601b000-63db-11eb-883a-cff4a4d9aadb.png)
This looks ugly.

^_^, thanks.

**Comment by anuraghazra** [comment]
Hi @Fatpandac 

Currently there is no way to control the height of cards because as you can see if we forcefully change the height the descriptions will get excerpted.

One way you can try out is to by using tables to organize the cards.

**Comment by Fatpandac** [comment]
Got it, thx

**Comment by mistic100** [comment]
Could it be possible to add a parameter to force the number of lines reserved for the description ? Truncating if too long and adding blank lines if too few.

**Comment by arthur-fontaine** [comment]
> Could it be possible to add a parameter to force the number of lines reserved for the description ? Truncating if too long and adding blank lines if too few.

+1
