### ISSUE TITLE
Server is down?

### ISSUE THREAD

**Issue by vybhav72954** [anuraghazra/github-readme-stats#852]
**Describe the bug**
I know this has happened a few times last year and was apparently sorted out in #702 but is the server down again?
I just noticed today morning that my stat card is not visible with error 

```Please add an env variable called PAT_1 with your github token in vercel```

**Expected behavior**
My Github stat card should work.

**Screenshots / Live demo link (paste the GitHub-readme-stats link as markdown image)**
![Screenshot](https://i.imgur.com/tDjYP5A.png)

**Additional context**
I looked up at others profile who use the stat card, it was working for them, so maybe am doing something wrong? was unable to find it in docs though.

**Comment by anuraghazra** [comment]
You are deploying on your own vercel instance? 

Then add PAT_1 env variable in your vercel project settings.

**Comment by vybhav72954** [comment]
> You are deploying on your own vercel instance?
> 
> Then add PAT_1 env variable in your vercel project settings.

Am pretty sure I haven't done that, I just changed followed the docs
I don't have a vercel project deployed

**Comment by anuraghazra** [comment]
This is not our vercel deployment.

> https://github-readme-stats-abserari.vercel.app/

![image](https://user-images.githubusercontent.com/35374649/106379078-912da580-63cf-11eb-9b94-96953037d5c0.png)

**Comment by vybhav72954** [comment]
Thanks for the quick response 😄 
It Worked

**Comment by xgqfrms** [comment]
same problem

**Comment by rohini-shinge** [comment]
Facing same even if using correct URL. Please help

URL: https://github-readme-stats.vercel.app/api?username=rohini-shinge&theme=github_dark&show_icons=true

Error:

![image](https://user-images.githubusercontent.com/67900281/169057197-b8397c8b-575d-4f8d-8fd2-1f7f4a5c6019.png)
