### ISSUE TITLE
Wrong total commits value

### ISSUE THREAD

**Issue by Giuliopime** [anuraghazra/github-readme-stats#853]
I have a total of 1022 contributions but my stats card shows "Total Commits: 679"
Here is the html I used for the card:
```html
<img align="center" src="https://github-readme-stats.vercel.app/api?username=Giuliopime&show_icons=true&count_private=true&theme=radical&include_all_commits=true" />
```

Also, private contributions are turned on in my contribution settings.

**Comment by anuraghazra** [comment]
@Giuliopime thanks for opening the issue.

The thing is that "contribution != commits"

GitHub contribution chart does not just shows commits it also shows PRs/Issues/Discussions etc etc stuff

https://docs.github.com/en/github/setting-up-and-managing-your-github-profile/viewing-contributions-on-your-profile#what-counts-as-a-contribution

**Comment by Giuliopime** [comment]
I don't think that's the issue, because most of my contributions are commits:
<img width="815" alt="Screenshot 2021-01-31 at 13 59 09" src="https://user-images.githubusercontent.com/60524738/106384722-976e5280-63cc-11eb-94c8-23fe7f581174.png">

**Comment by anuraghazra** [comment]
Try with `count_private` option

https://github-readme-stats.vercel.app/api?username=Giuliopime&count_private=true

**Comment by Giuliopime** [comment]
It's already in use

**Comment by anuraghazra** [comment]
looks fine to me. 1k commits

![Uploading image.png…]()

**Comment by anuraghazra** [comment]
You are using include_all_commits and count_private both at once. they are not meant to be used at once. 

Either use include_all_commits or count private

**Comment by Giuliopime** [comment]
So not both together ok, that was the issue I think

**Comment by anuraghazra** [comment]
> So not both together ok, that was the issue I think

Yeah just use https://github-readme-stats.vercel.app/api?username=Giuliopime&count_private=true

We cannot count both. and include_all_commits can't count private commits
