### ISSUE TITLE
Can we add C++ in stats

### ISSUE THREAD

**Issue by kaafivikrant** [anuraghazra/github-readme-stats#854]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by anuraghazra** [comment]
I checked you have c++ code in your repos but it's not showing up because other languages (html, css, js) have large amounts of code (in bytes) thus they are more saturated.

**Comment by anuraghazra** [comment]
Try using langs_count param to show more langs

https://github-readme-stats.vercel.app/api/top-langs?username=kaafivikrant&langs_count=10

and then hide which you don't want

https://github-readme-stats.vercel.app/api/top-langs?username=kaafivikrant&langs_count=10&hide=HTML,CSS,SCSS,Javascript

![](https://github-readme-stats.vercel.app/api/top-langs?username=kaafivikrant&langs_count=10&hide=HTML,CSS,SCSS,Javascript)

**Comment by kaafivikrant** [comment]
Thanks bro
