### ISSUE TITLE
Add language support for Golang and Haskell in language card.

### ISSUE THREAD

**Issue by willdoescode** [anuraghazra/github-readme-stats#855]
**Is your feature request related to a problem? Please describe.**
It is not a problem it would just be nice if I could see the distribution of my languages with all of the languages.

**Describe the solution you'd like**
I would like golang and haskell among other languages to be included in the language card so that they show on my profile.

**Additional context**
![Screen Shot 2021-01-31 at 14 44 31](https://user-images.githubusercontent.com/53620720/106400363-d69fa200-63d2-11eb-8b62-f864084991e5.png)
![Screen Shot 2021-01-31 at 14 44 50](https://user-images.githubusercontent.com/53620720/106400365-e15a3700-63d2-11eb-9adc-ff2117ad3343.png)

**Comment by anuraghazra** [comment]
Try using langs_count param to show more langs

https://github-readme-stats.vercel.app/api/top-langs?username=willdoescode&langs_count=10

and then hide which you don't want

https://github-readme-stats.vercel.app/api/top-langs?username=willdoescode&langs_count=10&hide=Python,Vue,javascript,rust

![](https://github-readme-stats.vercel.app/api/top-langs?username=willdoescode&langs_count=10&hide=Python,Vue,javascript,rust)

**Comment by willdoescode** [comment]
I will try that out.

**Comment by willdoescode** [comment]
That worked, thank you!
