### ISSUE TITLE
all projects showing as a Java project

### ISSUE THREAD

**Issue by leandroaugustolelis** [anuraghazra/github-readme-stats#860]
I don't know if it's a bug or something else but there was nothing wrong with stats card, except after mid january when all stats of my projects changed to Java and everytime I upload a new Project to my github counts as a 'Java Project' and they are not, most of them are 100% Typescript or Javascript.

**Comment by iRay** [comment]
The same behaviour to me:
I've a project where github's "Languages" sections says: Vue 53.4%, JavaScript 18.9%, Python 13.7%, SCSS 10.2%, Shell 1.5%
And at the same time in "readme-stats" i see only: Python 93.84%, Shell 6.16%
I use this url: `https://github-readme-stats.vercel.app/api/top-langs/?username=iRay&layout=compact&langs_count=10`
Maybe i missed something?
Thanks in advance!

**Comment by anuraghazra** [comment]
> I've a project where github's "Languages" sections says: Vue 53.4%, JavaScript 18.9%, Python 13.7%, SCSS 10.2%, Shell 1.5%

@iRay not sure but i can see that none of your repo contains Vue, nor Js, nor SCSS.

**Comment by anuraghazra** [comment]
> except after mid january when all stats of my projects changed to Java and everytime I upload a new Project to my github counts as a 'Java Project' and they are not

We just use github's linguist data. it's directly fetched from github graphql api. We are not responsible if any of your repo is showing java after you uploaded it. 

See: https://github.com/github/linguist


And in case of github readme stats, our card is showing java at top because you have a larger amount of java code (in bytes) compared to other languages.

**Comment by iRay** [comment]
oops... sorry guys. I just realized that i was looking at my private repository. Yes, public repos contains only python code.
