### ISSUE TITLE
Is it possible to configure the year?

### ISSUE THREAD

**Issue by eddynaka** [anuraghazra/github-readme-stats#861]
Today, when we create the url, it only searches for the current year commits / pr.

Do we have a configuration to do the same for a specific year? for example 2020?

Can we generate a trending comparing past years?

**Comment by johnkhansrc** [comment]
that interests me too

**Comment by sschuberth** [comment]
Sounds like a duplicate of https://github.com/anuraghazra/github-readme-stats/issues/764.
