### ISSUE TITLE
Wakatime Stats doesnt work

### ISSUE THREAD

**Issue by FC5570** [anuraghazra/github-readme-stats#863]
I'm trying to use the wakatime stats card for my readme, whenever I enter my username it says the user wasn't found even though I have a wakatime account, 

https://github-readme-stats.vercel.app/api/wakatime?username=FC5570 <-- as you can see it says the user doesnt exist, idk what to do at this point, I've even turned on these: https://fc5570.only-fans.club/ctqH

Is this a bug or am I doing something wrong?

**Comment by Milo123459** [comment]
yea i get this issue as well

**Comment by LevraGav** [comment]
Same for me, this is frustating

**Comment by LevraGav** [comment]
I have made a wakatime account but for some reason it keeps saying that i dont have an account (user doesn't exist), i've tried every method but none of them are working

**Comment by LevraGav** [comment]
https://github-readme-stats.vercel.app/api/wakatime?username=LevraGav, as you can see it's not working

**Comment by LevraGav** [comment]
<img width="428" alt="ss" src="https://user-images.githubusercontent.com/72689610/107148696-370c8180-6987-11eb-89f2-fd67baa0e6d1.PNG">

as you can see i already have an account on wakatime

**Comment by anuraghazra** [comment]
Oh well, seems like wakatime did some changes to their API and now the resources are only available if we provide access token, otherwise not  :( 

http://wakatime.com/api/v1/users/LevraGav

**Comment by anuraghazra** [comment]
Okay so seems like to fix this issue we need to use wakatime embeddable share links (as json response).

**Comment by LevraGav** [comment]
please can you help us how to provide the access token (:

**Comment by anuraghazra** [comment]
> please can you help us how to provide the access token (:

Only way is to deploy on your own vercel instance, even so we don't have any logic for handling that in our code currently. so it would not work.

**Comment by LevraGav** [comment]
could you show us an example about how to do it?

**Comment by anuraghazra** [comment]
Closing this in favor of #865

**Comment by anuraghazra** [comment]
> could you show us an example about how to do it?

See #865 for more info.

**Comment by LevraGav** [comment]
thank you very much, you are the best

**Comment by LevraGav** [comment]
i'm sorry but it's still not working for me (:

**Comment by LevraGav** [comment]
https://github-readme-stats.vercel.app/api/wakatime?shareid=LevraGav/604dd95a-d933-42e8-9c87-e3b6c7c61293
@anuraghazra

**Comment by SP-XD** [comment]
> https://github-readme-stats.vercel.app/api/wakatime?shareid=LevraGav/604dd95a-d933-42e8-9c87-e3b6c7c61293
> @anuraghazra

same issue bro
https://github-readme-stats.vercel.app/api/wakatime?username=sp-xd
https://wakatime.com/@spxd

**Comment by TserHub** [comment]
> same issue bro
> https://github-readme-stats.vercel.app/api/wakatime?username=sp-xd
> https://wakatime.com/@spxd

Delete "-", try again! 
https://github-readme-stats.vercel.app/api/wakatime?username=spxd

**Comment by ishusagar** [comment]
> https://github-readme-stats.vercel.app/api/wakatime?username=LevraGav, as you can see it's not working

I'm still facing this issue. I can see that your link is working. Can you help me out?
