### ISSUE TITLE
not updating python commits

### ISSUE THREAD

**Issue by BenRed06** [anuraghazra/github-readme-stats#866]
**Describe the bug**
i am doing a lot of python committing now and its not updating. 
everything else updates just not python. 

i have tried to make a new repo and test. new file. nothing works. even after 1/2 hour when it usually updates

**Comment by anuraghazra** [comment]
It does not matter if you have lot of python files. or lot of commits with python.

We count by *how much* code you have in bytes

**Comment by BenRed06** [comment]
oh ok. how much code do I need to commit to have it load?
