### ISSUE TITLE
After updating description Extra pins are not updated.

### ISSUE THREAD

**Issue by Gronx16** [anuraghazra/github-readme-stats#870]

**Comment by HawkeyePierce89** [comment]
How long to wait for the description update?

**Comment by Gronx16** [comment]
approximately 3 to 4 hrs

**Comment by R-N** [comment]
I'm experiencing this issue. It has been days and it's still not updating. I did Ctrl+F5 too, if that matters. Should I open a new issue?

**Comment by qwerty541** [comment]
At the moment the default cache timing on the public deployment for pin cards is 10 days. In case you want your cards to be updated more often then you can [deploy own instance](https://github.com/anuraghazra/github-readme-stats?tab=readme-ov-file#deploy-on-your-own) using own GitHub API token.
