### ISSUE TITLE
include_all_commits does not work on StatsCard

### ISSUE THREAD

**Issue by NiklasUllmann** [anuraghazra/github-readme-stats#872]
**Describe the bug**
I`ve added the include_all_commits=true to my StatsCard URL but it changes nothing. Also changing the boolean to false doesn`t change anything. 

**Expected behavior**
Stats Card should display all commits

Thx for your great work!

**Comment by GeneralMine** [comment]
Are you using `count_private` and `include_all_commits` at the same time?
According to this [issue](https://github.com/anuraghazra/github-readme-stats/issues/853) you cannot use both at the same time

**Comment by NiklasUllmann** [comment]
Thx :)
