### ISSUE TITLE
Impossible to have B+ rank

### ISSUE THREAD

**Issue by CrafterKolyan** [anuraghazra/github-readme-stats#883]
**Describe the bug**
Current rank calculation is broken due to it is not possible to get score more than `51.03597635931825`

**Expected behavior**
Score should be in range `[0; 100]` so that B+ rank would be obtainable.

**Screenshots / Live demo link (paste the github-readme-stats link as markdown image)**
![image](https://user-images.githubusercontent.com/9883873/108052980-e61f1c00-705d-11eb-955d-1a36fd2ff61a.png)

**Comment by CrafterKolyan** [comment]
The rating algorithm hasn't changed. It's still impossible to get a B+ rank

**Comment by itsjavi** [comment]
I only see A+ everywhere. I compared an active user with 10 PRs and 0 stars with another one with 2K stars and 220 PRs, both have the same A+ rating. Isn't that weird?

**Comment by CrafterKolyan** [comment]
Nothing changed, still an issue

**Comment by Anequit** [comment]
I would like to see the possibility of getting F+/-, D+/-, C+/-, and B+/-

**Comment by guikarist** [comment]
This classification is too rough :cry:

**Comment by rickstaa** [comment]
Closed in favour of #455.

**Comment by yuuuuuuan** [comment]
impossible

**Comment by qwerty541** [comment]
> impossible

@yuuuuuuan Currently to have B+ rank you should have approximately the following stats:

Commits: 250
Pull requests: 50
Issues: 25
Reviews: 10
Stars: 50
Followers: 10

**Comment by Nicat-dev** [comment]
that mainly about last year contribution because My profile B- right now

**Comment by qwerty541** [comment]
> that mainly about last year contribution because My profile B- right now

@Nicat-dev That about all time contributions, except commits count. Your profile does not match minimal requirements for B+ rank. You can check which stats you should have for each rank in tests file for rank calculation function: https://github.com/anuraghazra/github-readme-stats/blob/master/tests/calculateRank.test.js
