### ISSUE TITLE
White and dark theme working at the same time

### ISSUE THREAD

**Issue by AllanGame** [anuraghazra/github-readme-stats#897]
It would be better if the images do not have a white or dark background, simply the data in .png and that is how it would work in both themes since the background would be set by github by default 👍

**Comment by PassionPenguin** [comment]
but... the font need to be transparent, like #888888, alpha 50

need to know that the image is svg instead of png

**Comment by 2br-2b** [comment]
Duplicate of #777 and #739

**Comment by NoushadBug** [comment]
you can check out this, **https://github.com/NoushadBug**

**this stat theme is for any GitHub theme, made by me. It will be suitable. Have a check -** 
`https://github-readme-stats.vercel.app/api?username=noushadBug&title_color=FA8C00&icon_color=CC5160&text_color=949CA5&bg_color=00000000&show_icons=true`
