### ISSUE TITLE
GitHub Mobile, Incorrect Render Result

### ISSUE THREAD

**Issue by PassionPenguin** [anuraghazra/github-readme-stats#899]
On GitHub official mobile application, Android 10

You can see the first pic (Hoarfroster's GitHub Stats) has no content inside the rect

You can also find out that the font is not sans-serif as what we expected (as what it is on browser).

Does node js or vercel support to export svg as png and output the png stream? (interesting feature...)

![181614010844_ pic](https://user-images.githubusercontent.com/41184947/108736909-032b8180-756d-11eb-81d3-fe106d703d3c.jpg)

**Comment by alvaromartmart** [comment]
I can confirm this is still an issue

**Comment by PassionPenguin** [comment]
> I can confirm this is still an issue 

agree with

**Comment by PassionPenguin** [comment]
problem is still existed

**Comment by PassionPenguin** [comment]
PTAL @anuraghazra

**Comment by DenverCoder1** [comment]
The GitHub app renders most SVGs incorrectly

Related to #215

**Comment by sameer882000** [comment]
I can confirm this is still an issue.

**Comment by DenverCoder1** [comment]
This appears to have been fixed

![image](https://user-images.githubusercontent.com/20955511/125086464-56ddd800-e0d4-11eb-8730-b95eacc19ee3.png)

Should be able to close this now (also #571 #215 #776 related to the same issue)

**Comment by rickstaa** [comment]
@DenverCoder1 Thanks for the update. I double checked that it works on android. I will close the related issues for now. If anyone still experiencing issues feel free to leave a comment.
