### ISSUE TITLE
[Bug] Repo type Jupyter Notebook blends with the number of stars

### ISSUE THREAD

**Issue by ucalyptus** [anuraghazra/github-readme-stats#9]
Check this picture. Not just Jupyter, any language with that length of string would superimpose with the stars feature.
![Screenshot from 2020-07-10 11-06-52](https://user-images.githubusercontent.com/36279638/87120174-7a8df880-c29d-11ea-8114-34f54b334692.png)

**Comment by ucalyptus** [comment]
cc: @anuraghazra

**Comment by anuraghazra** [comment]
@ucalyptus thanks for reporting the bug. Its because of the text's length is large no problem I'll fix it asap. Thanks!

**Comment by anuraghazra** [comment]
@ucalyptus should be fixed now


[![Fixed](https://github-readme-stats.vercel.app/api/pin/?username=ucalyptus&repo=HybridSN-Pytorch)](https://github.com/anuraghazra/github-readme-stats)

**Comment by ucalyptus** [comment]
Absolutely. Thank you
