### ISSUE TITLE
question about the languages card

### ISSUE THREAD

**Issue by BenRed06** [anuraghazra/github-readme-stats#900]
hello. 

with the languages card. does it work on commits or total file size of all the repos you have?

**Comment by BenRed06** [comment]
@angeligareta which one?

**Comment by angeligareta** [comment]
I believe it is on the total file size for all the repositories, github-readme-stats use Github API, hence [linguist](https://github.com/github/linguist) library and there it is explained that the languages percentage is calculated from the files in the repository, it does not mention the commits.

**Comment by BenRed06** [comment]
ok that makes sense
