### ISSUE TITLE
Include Forks and PR's for Language Cards

### ISSUE THREAD

**Issue by EthanHannen** [anuraghazra/github-readme-stats#905]
**Is your feature request related to a problem? Please describe.**
Forks are excluded from language cards.

**Describe the solution you'd like**
I have far more C++ and Lua commits than any other language, yet my top language is shown as C# due to my own repos. This, as I can currently ascertain, is due to the fact that forked repos are being excluded from the language aggregation. Recommend that language cards be inclusive of all types of commits and span the entire history of the profile in order to get an accurate sense of the developer's experience.

**Describe alternatives you've considered**

**Additional context**

**Comment by SteveBronder** [comment]
Just bumping this as it would be nice, very cool project!

**Comment by rickstaa** [comment]
@EthanHannen Thanks for your feature request. This feature request has been requested multiple times in the past. Unfortunately, the current version of GraphQL API doesn't allow us to implement this feature in a stable way. For an explanation on why this is the case, see my comment in https://github.com/anuraghazra/github-readme-stats/pull/1122#issuecomment-1152066225.

> Since the current [GraphQL languages object](https://docs.github.com/en/graphql/reference/objects#language) returns the languages used in a repository, not those in the commits done by a specific user, the current version of the PR will make the language stats less accurate. I created a feature request to improve this behaviour on GitHub's side (see https://github.com/orgs/github-community/discussions/18230). You can show your support there. 

If you don't care about language accuracy, you can change the GraphQL request in your own fork. This can be done by changing

https://github.com/anuraghazra/github-readme-stats/blob/192170c1111333a2a6a65015c81ab1cdb4b86a6a/src/fetchers/top-languages-fetcher.js#L17

to

```js
repositories(ownerAffiliations: OWNER, isFork: true, first: 100) {
```

I will close this issue, for now, please feel free to comment below if the GraphQL API is changed in such a way that we can include forks.
