### ISSUE TITLE
Private commits count not updated

### ISSUE THREAD

**Issue by sisibeloved** [anuraghazra/github-readme-stats#908]
**Describe the bug**
The Number of private commits seems to be correct a few days ago, but since Feb 23th the count does not update in real-time;

**Expected behavior**
Show the correct total commit count including private repositories.

**Screenshots / Live demo link (paste the github-readme-stats link as markdown image)**
All the number of commits are in private repositories:
![image](https://user-images.githubusercontent.com/9612053/109135636-4155ba80-7792-11eb-8a98-705238b16e52.png)
![image](https://user-images.githubusercontent.com/9612053/109135789-69ddb480-7792-11eb-9eea-265e31c4da33.png)

**Additional context**
The link I use:
`https://github-readme-stats.vercel.app/api?username=sisibeloved&show_icons=true&theme=dracula&count_private=true`

**Comment by harshhhdev** [comment]
It will only get the amount of commits in public repositories. Not private ones.

There is also a 2hr update time, and it will not change instantly.

**Comment by sisibeloved** [comment]
> It will only get the amount of commits in public repositories. Not private ones.
> 
> There is also a 2hr update time, and it will not change instantly.

The param `count_private` is used to count private repositories, btw I haven't committed to any public repositories this year. All the commits are committed to private repositories. And the number hasn't updated for 2 days.

**Comment by Hardikdigiqt** [comment]
same with me , its a open issue for private commits

**Comment by Midorina** [comment]
I'm having the same issue, even though I'm running my own instance via Vercel.

**Comment by anuraghazra** [comment]
Hi @sisibeloved can you check this two stuff

1. make sure private contributions are visible to public 
![image](https://user-images.githubusercontent.com/35374649/120898924-c3cfff00-c64a-11eb-9c95-7fe44b01e7bf.png)


2. Check this box and press the update contribution button
![image](https://user-images.githubusercontent.com/35374649/120898941-d4807500-c64a-11eb-912c-3c242a94ae5f.png)

**Comment by Midorina** [comment]
> Hi @sisibeloved can you check this two stuff
> 
> 1. make sure private contributions are visible to public
>    ![image](https://user-images.githubusercontent.com/35374649/120898924-c3cfff00-c64a-11eb-9c95-7fe44b01e7bf.png)
> 2. Check this box and press the update contribution button
>    ![image](https://user-images.githubusercontent.com/35374649/120898941-d4807500-c64a-11eb-912c-3c242a94ae5f.png)

this fixed the issue for me. thanks!

**Comment by dimitri-dev** [comment]
> 
> 
> Hi @sisibeloved can you check this two stuff
> 
>     1. make sure private contributions are visible to public
>        ![image](https://user-images.githubusercontent.com/35374649/120898924-c3cfff00-c64a-11eb-9c95-7fe44b01e7bf.png)
> 
>     2. Check this box and press the update contribution button
>        ![image](https://user-images.githubusercontent.com/35374649/120898941-d4807500-c64a-11eb-912c-3c242a94ae5f.png)

I have both of these marked correctly, yet my counter is also still very wrong.

**Comment by HoveringGoat** [comment]
This is not working for me either. 4,500 vs 50

**Comment by HoveringGoat** [comment]
Update. Gave it a couple hours and it now reflects the correct value. I'd add a disclaimer on the readme that if you update your contributions to be public it may take a little while to reflect that.

**Comment by rickstaa** [comment]
@HoveringGoat thanks for letting us know. @sisibeloved, @dimitri-dev, @Hardikdigiqt is this issue also fixed for you when you use the steps provided in https://github.com/anuraghazra/github-readme-stats/issues/908#issuecomment-855264520.

**Comment by sisibeloved** [comment]
> @HoveringGoat, thanks for letting us know. @sisibeloved, @dimitri-dev, @Hardikdigiqt is this issue also fixed for you when you use the steps provided in [#908 (comment)](https://github.com/anuraghazra/github-readme-stats/issues/908#issuecomment-855264520).

Thank you for your attention. I counted the commits number and it matches the records in Github. Besides, it is more appropriate with the name 'Total commits in last 12 months' than 'Total commits in 2022'.

**Comment by rickstaa** [comment]
@sisibeloved Thanks for letting me know. I agree that we should look at the naming (see https://github.com/anuraghazra/github-readme-stats/issues/1053).
