### ISSUE TITLE
Repository Cards on MediaWiki markup file won't show properly

### ISSUE THREAD

**Issue by nattadasu** [anuraghazra/github-readme-stats#91]
**Describe the bug**
When trying to embed the image with `<img>` html tag or using embedding syntax (`[[File:https://github-readme-stats.vercel.app/api/pin/?username=ryuuganime&repo=Ryuuganime]]`) on MediaWiki README file, card are not behaving as it should be on like Markdown.

**Expected behavior**
Repository details were shown properly, behaving similar to Markdown.
![](https://media.discordapp.net/attachments/591889046020554772/733782304433897532/unknown.png)
```md
[![](https://github-readme-stats.vercel.app/api/pin/?username=ryuuganime&repo=Ryuuganime)](https://github.com/ryuuganime/Ryuuganime)
```
*Live preview from https://github.com/nattadasu/nattadasu/blob/master/README.md#Ryuuganime*

**Screenshots / Live demo link (paste the github-readme-stats link as markdown image)**
```mediawiki
[https://github.com/ryuuganime/Ryuuganime <img src="https://github-readme-stats.vercel.app/api/pin/?username=ryuuganime&repo=Ryuuganime">]
```
Live demo link (on Indonesian): https://github.com/nattadasu/nattadasu/blob/master/README.id.wiki#Ryuuganime

Screenshot:
![](https://media.discordapp.net/attachments/591889046020554772/733782203464679464/unknown.png)

**Comment by nattadasu** [comment]
However, user stats card is working properly by the way. :/
![](https://media.discordapp.net/attachments/591889046020554772/733783422664835142/unknown.png)
https://github.com/nattadasu/nattadasu/blob/master/README.id.wiki#statistik

**Comment by anuraghazra** [comment]
Hi @nattadasu thanks for reporting the issue, i'm not sure about the syntax of media wiki but github-readme-stats are obviously 
 working correctly maybe something is weird happening because of the syntax of media wiki?

**Comment by anuraghazra** [comment]
It says invalid username or repo that means the fetchRepo function isn't getting the username/repo

**Comment by anuraghazra** [comment]
Also @nattadasu i will highly recommend you to [host on your own vercel instance](https://github.com/anuraghazra/github-readme-stats#deploy-on-your-own-vercel-instance) because you are pinning a lot of repos.

**Comment by nattadasu** [comment]
> maybe something is weird happening because of the syntax of media wiki?

Yeah, its weird to see that one error. I've tried several method like using `img` html tag, still didn't work.

> i will highly recommend you to host on your own vercel instance because you are pinning a lot of repos.

I'm currently trying to host it by myself 😅

Maybe if I using my own instance, it would help a little bit, maybe?

**Comment by nattadasu** [comment]
*Can I off-topic a little bit?*
Things getting weirder now. Using my own host, and its won't work

![](https://github-readme-stats-navy.vercel.app/api/pin/?username=MALSync&repo=MALSync&show_owner=true)
`https://github-readme-stats-navy.vercel.app/api/pin/?username=MALSync&repo=MALSync&show_owner=true`

**Comment by anuraghazra** [comment]
I think you missed a step. Please read the docs carefully... You have to add your GitHub personal access token in your vercel env called "PAT_1

**Comment by anuraghazra** [comment]
> Maybe if I using my own instance, it would help a little bit, maybe?
No hosting on your own wont change anything, i'm just recommending to do so because you are embedding the repo card a lot of times

**Comment by nattadasu** [comment]
Ah, I see... the problem still occurs to be fair after changing the url&nbsp;&nbsp;<img src="https://i.imgur.com/Ulp2hk1.png" height="20">

**Comment by anuraghazra** [comment]
@nattadasu  OOOOOPPSS! got your issue i guess, 

```md
[https://github.com/ryuuganime/Ryuuganime <img src="https://github-readme-stats.vercel.app/api/pin/?username=ryuuganime&repo=Ryuuganime">]
```

Note the last quote **"**>] that is invalid, same issue faced #101

**Comment by nattadasu** [comment]
Uhm, I don't think that happened for HTML one. Quotation mark `"..."` inside HTML tag "value" is essential/important for the tag itself. If there's no mark between "value," the overall document would be "corrupted"

AFAIK, the #101 issue happened when they're using markdown image syntax `![]()` for embedding image rather using `<img src="">` HTML tag and accidentally typed quote. mark. It'd corrupt the image itself, not the document overall, as seen on `![]([....]&icon_color=333")`

<details><summary>Testing to embed the image using HTML tag in Markdown</summary>
<img src="https://gitreadme.nattadasu.my.id/api/pin/?username=ryuuganime&repo=Ryuuganime">

&lt;img src="https://gitreadme.nattadasu.my.id/api/pin/?username=ryuuganime&repo=Ryuuganime" /&gt;
</details>

**Comment by anuraghazra** [comment]
hmm i see well, working on my side i've checked :thinking:

**Comment by nattadasu** [comment]
Ok, I've talked this thing to my acquaintance, and he's also a FOSS developer. He mentioned that from GitHub end, can not read from `?username=...` part, and no request from my end at all. 
<details><summary>See proof</summary>
<img src="https://media.discordapp.net/attachments/604932802181595166/734833435339915304/unknown.png">
</details>

Removing the hyperlink (`[]()` or `<a>`) won't help this issue thou.

I think I should issuing this problem to MediaWiki repo. 😞
