### ISSUE TITLE
Name not updating on card

### ISSUE THREAD

**Issue by doublevcodes** [anuraghazra/github-readme-stats#910]
**Describe the bug**
When a user updates their name the card doesn't update

**Expected behavior**
My name on the card would be updated like the name on my profile

**Screenshots / Live demo link (paste the github-readme-stats link as markdown image)**

**Additional context**
Is it just because it takes a while for it to update in GitHub databases?

**Comment by anuraghazra** [comment]
We have minimum of 2hours cache.

**Comment by anuraghazra** [comment]
Seems like your name is updated. closing this as resolved.
