### ISSUE TITLE
The number of commits in THIS YEAR(2021) is not matched to ACTUAL numbers of commits

### ISSUE THREAD

**Issue by witheunjin** [anuraghazra/github-readme-stats#913]
Hello👋
I am the one of the lovers/users of your 'github-readme-stats' project and recently, I found some bugs of it like below.

#### SUMMARY
Same as the title(**The number of commits in THIS YEAR(2021) is not matched to ACTUAL numbers of commits**)

#### DETAIL
* The number of commits of **This Year(2021)** is not correct.
> 'Github-Readme-Stats' say it is 239.
However, the ACTUAL number of contributions in 2021 is ONLY 46(not including private, but it is still only 73 even though I include private contributions).

* Additionally, The number of commits **including PRIVATE** is not correct.
> Even though I used the query parameter `&count_private=true`, the 'Github-readme-stats' doesn't apply the change.

-----------
### Expected behavior
I want 'Github-Readme-Stats' to be improved like below.
* Count Commits of THIS YEAR(2021) correctly.
* Add the number of PRIVATE commits, when I use the query parament `&count_private=true`.

-------------
#### Screenshot 1: My Github Readme Stats
> **Descriptions** 
The above one is the screenshot without any options(like `&include_all_commits=true` or `&count_private=true`).
The Link of it is `https://github-readme-stats.vercel.app/api?username=witheunjin`
The below one is the screenshot with `&count_private=true`.
The Link of it is `https://github-readme-stats.vercel.app/api?username=witheunjin&count_private=true`.

![commmm](https://user-images.githubusercontent.com/50702052/109410228-35f5cf80-79dc-11eb-93ef-167234275599.PNG)

#### Screenshot 2: The number of contributions in 2021(@witheunjin)
ALL(Include 'Private') : 73
![commits_all_2021](https://user-images.githubusercontent.com/50702052/109409387-97ff0680-79d5-11eb-8270-9e9101bd706c.PNG)
ONLY Public : 46
![commits_2021](https://user-images.githubusercontent.com/50702052/109409396-a51bf580-79d5-11eb-879a-e87bc1ca713c.PNG)

#### Screenshot 3: The number of contributions in 2020(@witheunjin)
ALL(Include 'Private') : 264
![commits_all_2020](https://user-images.githubusercontent.com/50702052/109409443-15c31200-79d6-11eb-9e9c-090588292d64.PNG)
ONLY Public : 235
![commits_2020](https://user-images.githubusercontent.com/50702052/109409447-1bb8f300-79d6-11eb-8981-c1d8291c5837.PNG)

Thank you for your amazing project and I hope this issue to be resolved soon. 😊

**Comment by anuraghazra** [comment]
Hi thanks for the opening a detailed issue. 

Yeah actually the label is a bit misleading.

We count from THIS DAY to previous 365 DAYS. 
Or in other terms previous 1 year of stats. 

Duplicate of #802 #853 #839 https://github.com/anuraghazra/github-readme-stats/issues/839#issuecomment-770359983

**Comment by witheunjin** [comment]
Ohhh I see.
Thank you for your reply :)

**Comment by tony955084** [comment]
> Hi thanks for the opening a detailed issue. 
> 
> 
> 
> Yeah actually the label is a bit misleading.
> 
> 
> 
> We count from THIS DAY to previous 365 DAYS. 
> 
> Or in other terms previous 1 year of stats. 
> 
> 
> 
> Duplicate of #802 #853 #839 https://github.com/anuraghazra/github-readme-stats/issues/839#issuecomment-770359983
> 
> 
> 
> https://shopee.tw/product/8698831/1217604708?smtt=0.293761175-1614965437.9
