### ISSUE TITLE
Cannot properly wrap content that mixes with Chinese and English characters

### ISSUE THREAD

**Issue by willbchang** [anuraghazra/github-readme-stats#921]
github-readme-stats
![](https://github-readme-stats.vercel.app/api/pin/?username=willbchang&repo=shanbay-jk)

https://gh-card.dev/
![](https://gh-card.dev/repos/willbchang/shanbay-jk.svg)

Text Content:
```
在扇贝单词网页版上让 j 拥有 1 跟 d 的功能，k 拥有 2 的功能。
```
Repo Link:
https://github.com/willbchang/shanbay-jk

**Comment by jaredliw** [comment]
The problem is not resolved yet....

**Comment by jaredliw** [comment]
The problem is not resolved yet....

**Comment by jaredliw** [comment]
The problem has not resolved yet......

See: https://denvercoder1-github-readme-stats.vercel.app/api/pin/?username=jaredliw&repo=algorithm-base

**Comment by jaredliw** [comment]
@anuraghazra Attention needed.
