### ISSUE TITLE
[Feature Request] Hide 'name's GitHub Stats'

### ISSUE THREAD

**Issue by Dev-CasperTheGhost** [anuraghazra/github-readme-stats#93]
**Is your feature request related to a problem? Please describe.**
It would be nice if we could have an option to remove the `"name's GitHub Stats"` from the stats card

**Describe the solution you'd like**
Have an option `false` or `true` as a param in the URL to remove `"name's GitHub Stats"`, 

Thanks, casper.

**Comment by anuraghazra** [comment]
There is already an option `?hide_title=true` 

Check the docs for [all available options](https://github.com/anuraghazra/github-readme-stats#customization)

related to #88 #60

**Comment by Dev-CasperTheGhost** [comment]
oh, sorry lol, Thank you for your reply!
