### ISSUE TITLE
 Noticing something wrong to repos language

### ISSUE THREAD

**Issue by thititongumpun** [anuraghazra/github-readme-stats#931]
https://github-readme-stats.vercel.app/api/top-langs/?username=thititongumpun&layout=compact&langs_count=10&theme=buefy

refer to my repos https://github.com/thititongumpun
it seem unusual why i got tcl language and python 56.25% in my stats.

**Comment by anuraghazra** [comment]
All data is coming from GitHub API so you do have TCL in some of the repo (maybe as a vendor code or in some library) so it's fine. 

If you want you can hide the TCL language.
