### ISSUE TITLE
Number of repos contributed too is not updating

### ISSUE THREAD

**Issue by TanishT** [anuraghazra/github-readme-stats#932]
**Describe the bug**
The number of repos in my profile has been stagnant for a while, despite me contributing to many more repos. 

**Expected behavior**
The repo count should be around 7 - 10. Right now it is just at 5. It has been this way for about 1 week, I thought that it was because of the time it takes for the code to query the github API for repo count, but I doubt it queries less than once a week.

**Comment by hallzy** [comment]
Similar issue. My contributed to says 2 right now, but I have definitely contributed to far more than that.

For me it looks like It is actually displaying the number of projects I have contributed to in the last year, instead of total.

**Comment by TanishT** [comment]
> Similar issue. My contributed to says 2 right now, but I have definitely contributed to far more than that.
> 
> For me it looks like It is actually displaying the number of projects I have contributed to in the last year, instead of total.
> 
> edit:
> 
> I just noticed that the documentation for the API being used for this functionality literally says "A list of repositories that the user recently contributed to."... emphasis on 'recently'.
> 
> So, that would do it. Would be nice to get a full count though

https://github.com/anuraghazra/github-readme-stats/issues/932#issuecomment-797061772
