### ISSUE TITLE
Inaccurate commit count 

### ISSUE THREAD

**Issue by okorkov** [anuraghazra/github-readme-stats#935]
account https://github.com/okorkov

![Anurag's GitHub stats](https://github-readme-stats.vercel.app/api?username=okorkov&show_icons=true&theme=radical)

commits also says it's only 15 but my project from 2 week ago alone has 86. Please Advice

**Comment by mihai-db** [comment]
Happens to me also, regarding commits counting.

**Comment by irhrhd** [comment]
Me to it happens for me

**Comment by AdityaInfinite** [comment]
The app uses graph-ql api for commit counts so maybe the api is giving that response. I had similar issues. check #635

**Comment by Nirav-Madhani** [comment]
If you check the image URL, it is something like `https://camo.githubusercontent.com/4074ca1dd89b2e8ec59015a950085cd625f6869d08d6e99269e6624a7ed...`

The problem is that github is catching image.

This can be found here: https://github.com/atom/markdown-preview/issues/207

If you open the image URL directly, then it will show the correct stats. So it cannot be fixed until we find a workaround for clearing cache on github.

The same thing happens with me.
Github Md:
![image](https://user-images.githubusercontent.com/77914957/111858952-24607180-8963-11eb-82c0-aa3ec97ab838.png)

From Direct Link
![image](https://user-images.githubusercontent.com/77914957/111858965-40641300-8963-11eb-9372-7c433ca50446.png)

**Comment by okorkov** [comment]
> If you check the image URL, it is something like `https://camo.githubusercontent.com/4074ca1dd89b2e8ec59015a950085cd625f6869d08d6e99269e6624a7ed...`
> 
> The problem is that github is catching image.
> 
> If you open the image URL directly, then it will show the correct stats. So it cannot be fixed until we find a workaround for clearing cache on github.
> 
> The same thing happens with me.
> Github Md:
> ![image](https://user-images.githubusercontent.com/77914957/111858952-24607180-8963-11eb-82c0-aa3ec97ab838.png)
> 
> From Direct Link
> ![image](https://user-images.githubusercontent.com/77914957/111858965-40641300-8963-11eb-9372-7c433ca50446.png)

I see, good to know! I knew there was something going on.

**Comment by anuraghazra** [comment]
We have minimum of 2 hours of cache. 

![image](https://user-images.githubusercontent.com/35374649/111906055-cd4ac180-8a74-11eb-9ef9-7c20d9f419c9.png)

**Comment by okorkov** [comment]
Can close the issue, turns out I have had different email for local git config and GitHub account, that's why commits weren't counter properly.
If anyone has a similar issue please make sure your Github primary email is matching to whatever you have here
`$ git config --global user.email`

Closing the issue.

**Comment by predator2v0** [comment]
so how can be the cache duration reduced?

**Comment by florianbussmann** [comment]
@predator2v0 as stated above there is a minimum of 2 hours for caching and that should be the default already. If you want to go lower than that, you will have to remove this limitation in the code and deploy your own instance.

> Note on cache: Repo cards have a default cache of 4 hours (14400 seconds) if the fork count & star count is less than 1k, otherwise, it's 2 hours (7200 seconds). Also, note that the cache is clamped to a minimum of 2 hours and a maximum of 24 hours.

The clamping for the stats card can be found here
https://github.com/anuraghazra/github-readme-stats/blob/fef8bc3a4a4ddb12a5c779e7cae18438231845a7/api/index.js#L56-L60

If you alter this you can provide lower values for the the parameter `cache_seconds` as stated in the README (https://github.com/anuraghazra/github-readme-stats#common-options)
