### ISSUE TITLE
not showing c++ in top languages.

### ISSUE THREAD

**Issue by Dipeshgoyal44** [anuraghazra/github-readme-stats#939]
Hi,
I am trying to get the card to show all my languages but for some reason, it's not showing c++. I have gone through some previous issues but nothing seems to resolve this. Can someone help me with this?

Thanks.

Here's an image of the card.
[Image](https://camo.githubusercontent.com/722dbb58e2258f9846a1d1b55caf10ab27676ca9ca138c4c77550196818d7aa0/68747470733a2f2f6769746875622d726561646d652d73746174732e76657263656c2e6170702f6170692f746f702d6c616e67732f3f757365726e616d653d446970657368676f79616c3434266c61796f75743d636f6d7061637426636f756e745f707269766174653d74727565267468656d653d72656163742668696465)

**Comment by qwerty541** [comment]
it's showing c++, take a closer look. Or am I misunderstanding the problem?

![image](https://user-images.githubusercontent.com/53787217/111054514-e8ff0800-8475-11eb-8c3d-2d18b731f8ab.png)

**Comment by PluginPenguin** [comment]
Yes, I saw C++ in your Top Langs card. If it still isn't for you, it might:
1. Not have loaded
2. It might not be in your top-five most used languages

If it still does not show up, read about it at the Github Docs site.

**Comment by Dipeshgoyal44** [comment]
yeah, it's working now. thanks
