### ISSUE TITLE
[Bug] Few issues with a repo description

### ISSUE THREAD

**Issue by paveloom** [anuraghazra/github-readme-stats#94]
**Describe the bug**

1. Only one line of a description gets displayed on a repo card. This seems a bit confusing since GitHub usually displays few lines if needed. This makes these cards and GitHub's standard pins less interchangeable.
2. The description of one of my repositories didn't get trimmed at all for some reason (see the live demo below).

**Expected behavior**

1. Display few lines if needed, at least two.
2. Trim the description as expected.

**Live demo**

![](https://github-readme-stats.vercel.app/api/pin/?username=paveloom-d&repo=dev&show_owner=true)
![](https://github-readme-stats.vercel.app/api/pin/?username=Paveloom&repo=B1&show_owner=true)

**Comment by anuraghazra** [comment]
Thanks for reporting the issue @Paveloom 

This seems strange that string.slice failed because of russian language :thinking: 
Also i did not show multi lines because it is a pain to work with multiline text in svg, so i just trimmed them for the sake of simplicity

**Comment by xiaoyu2006** [comment]
> This seems strange that string.slice failed because of russian language 🤔

No it trims well:

```javascript
desc = "Шаблоны make-файлов для компиляции программ и публикаци.."
// => "Шаблоны make-файлов для компиляции программ и публикаци.."
desc.slice(0, 50)
// => "Шаблоны make-файлов для компиляции программ и публ"
```

It's the font problem. For example, characters like "D" are longer, while "i" is shorter. e.g.

1. ![Too long char](https://github-readme-stats.vercel.app/api/pin/?username=xiaoyu2006&repo=github-readme-stats-debug1)
2. ![Too short char](https://github-readme-stats.vercel.app/api/pin/?username=xiaoyu2006&repo=github-readme-stats-debug2)

**Comment by xiaoyu2006** [comment]
Since you use SVG, sizes are fixed and can't expand automatically like the stock pin card.

@anuraghazra I have a ***not-so-good*** fix:
1. Increase the SVG's height a little
2. Auto break if the desc is too long.

PLZ let me know if this is avliable.

**Comment by anuraghazra** [comment]
> Increase the SVG's height a little
> Auto break if the desc is too long.

This of course sounds simple, but isn't. SVG does not have auto text wrapping. I'll have to write a function to detect the text length (and not just text length also have to consider each word's width which is hard to figure out) 

And we cannot simply make the height large it will look bad, we have to auto resize the height depending on how many line breaks there are (it's possible tho)

**Comment by xiaoyu2006** [comment]
> SVG does not have auto text wrapping.
https://developer.mozilla.org/zh-CN/docs/Web/SVG/Element/foreignObject

**Comment by anuraghazra** [comment]
> > SVG does not have auto text wrapping.
> 
> @anuraghazra
> See [foreignObject](https://developer.mozilla.org/en-US/docs/Web/SVG/Element/foreignObject). By adding an `<p>` in it will fix this.

I know about foreignObject and github also supports it, but there is no guarantee that it will render on all browser as it's not in SVG v1.1 Spec

**Comment by xiaoyu2006** [comment]
> I'll have to write a function to detect the text length (and not just text length also have to consider each word's width which is hard to figure out, otherwise we face the issue what you mentioned about "DDDD" longer than "III")

@anuraghazra This is going to be tricky as we're handling some "rendered thing", but what we have on the server side are just texts.

By doing this we have to return with a js embedded.

Also, reimplement everything in HTML's way will be a choice.

~~I feel like I keep providing rubbish. My frontend knowledge is almost zero!😨~~

**Comment by anuraghazra** [comment]
This should be partially fixed in #206 

Although russian language text is now messing up.

**Comment by Paveloom** [comment]
> This should be partially fixed in #206

Well, that's progress. Thank you for the PR, @HaaLeo and @anuraghazra.

> Although russian language text is now messing up.

Yep:

![](https://github-readme-stats.vercel.app/api/pin/?username=paveloom-p&repo=p1)
![](https://github-readme-stats.vercel.app/api/pin/?username=paveloom-p&repo=p2)
![](https://github-readme-stats.vercel.app/api/pin/?username=paveloom-p&repo=p3)

Hopefully this problem will be solved too.

**Comment by Paveloom** [comment]
Bump.

**Comment by Zo-Bro-23** [comment]
Closing as stale.
