### ISSUE TITLE
Data update

### ISSUE THREAD

**Issue by pedromaironi** [anuraghazra/github-readme-stats#955]
Why or how often the cards are updated, since I have a couple of months and they have not been updated

**Comment by LucaArgentieri** [comment]
Same here

**Comment by Eeveelution** [comment]
im using it since quite recently, and ive removed some of my python code from github and it still shows 3% python even though i dont have any repos with any python code,

**Comment by otacrazy2123** [comment]
Anything new on this?

**Comment by rickstaa** [comment]
The update time is specified in [the docs](https://github.com/anuraghazra/github-readme-stats#common-options):

> Note on cache: Repo cards have a default cache of 4 hours (14400 seconds) if the fork count & star count is less than 1k, otherwise, it's 2 hours (7200 seconds). Also, note that the cache is clamped to a minimum of 2 hours and a maximum of 24 hours.

Anything longer than that might point to a bug. I will close this issue for now. Please comment below if your profile still is not updated.
