### ISSUE TITLE
`include_gists` - Includes gists in the language distribution

### ISSUE THREAD

**Issue by Yash-Singh1** [anuraghazra/github-readme-stats#967]
Currently the language distribution does not include calculations from gists. Maybe there could be a query paramater that does so when set to true.

**Comment by anuraghazra** [comment]
Currently we don't have any plans to include gists on the stats.

It's Github itself treats it as a separate entity and It will be more confusing to people about wrong language stats if we include the gists arbitrarily along with github source code languages. 

Also as far as i know there is no Official API to get gist languages data.

**Comment by Rudxain** [comment]
Can we revisit this possibility? What if we open a discussion [here](https://github.com/community)?

**Comment by qwerty541** [comment]
> Can we revisit this possibility? What if we open a discussion [here](https://github.com/community)?
> 
> I wish Py and Shell had a higher weight on my stats, since many of my gists use them

Hey, @Rudxain!

I just checked GraphQL GitHub API documentation. At the moment [gist entity](https://docs.github.com/en/graphql/reference/objects#gist) contains [gist files](https://docs.github.com/en/graphql/reference/objects#gistfile), and gist files in it's turn contain [language data](https://docs.github.com/en/graphql/reference/objects#language).

I think it is currently possible to implement this feature as separate endpoint which will return the same card as top languages endpoint, but with gists related data, or we can extend top languages endpoint with `include_gists` query string parameter, however in case of addition query string parameter top languages endpoint will become overcomplicated, slow to response and using too much API token points per request, so I'd like to enable it only for those who deployed own Vercel instance with own API token.

Feel free to open feature request issue, if there will be enough interest from the comminuty, then we can implement it. We use top issues dashboard (https://github.com/anuraghazra/github-readme-stats/issues/1935) to track community demand and prioritize.
