### ISSUE TITLE
New WakaTime API still has issues

### ISSUE THREAD

**Issue by Mongar23** [anuraghazra/github-readme-stats#971]
After trying everything on the closed issue page #865 the WakaTime card is still not displaying my stats. It gives the no user found error.

The snippet of my README.md file:
`[![Mathias' WakaTime stats](https://github-readme-stats.vercel.app/api/wakatime?shareid=Mongar23/89dd6ec5-fd88-4c30-a6a9-e978d0049e9d)](https://github.com/anuraghazra/github-readme-stats) `   

This results in this:
[![Mathias' WakaTime stats](https://github-readme-stats.vercel.app/api/wakatime?shareid=Mongar23/89dd6ec5-fd88-4c30-a6a9-e978d0049e9d)](https://github.com/anuraghazra/github-readme-stats)

The embedded code the WakaTime generated:
`$.ajax({
  type: 'GET',
  url: 'https://wakatime.com/share/@Mongar23/89dd6ec5-fd88-4c30-a6a9-e978d0049e9d.json',
  dataType: 'jsonp',
  success: function(response) {
    console.log(response.data);
  },
});`

And this is my WakaTime stats page: https://wakatime.com/api/v1/users/Mongar23/stats

I have no idea what I'm doing wrong and it would be nice if the documentation on the GitHub page is changed. 

Thanks in advance!

**Comment by anuraghazra** [comment]
We  don't support shareid. use your username

https://github-readme-stats.vercel.app/api/wakatime?username=Mongar23

**Comment by Mongar23** [comment]
Yess I've tried this as well but then I get the no coding activities:
[![Mathias' WakaTime stats](https://github-readme-stats.vercel.app/api/wakatime?username=Mongar23)](https://github.com/anuraghazra/github-readme-stats)
`[![Mathias' WakaTime stats](https://github-readme-stats.vercel.app/api/wakatime?username=Mongar23)](https://github.com/anuraghazra/github-readme-stats)`

**Comment by Mongar23** [comment]
For some reason it took a while to process, thanks for the help anyway.
