### ISSUE TITLE
Stats card doesn't work on GitHub's android app (beta)

### ISSUE THREAD

**Issue by stefoxp** [anuraghazra/github-readme-stats#974]
On GitHub's android app (in beta state) the stats card doesn't visualize the stats but only the title. See this screenshot for details: 

![Screenshot_20210328-134528.png](https://user-images.githubusercontent.com/33906742/112751087-62e1d600-8fcc-11eb-877e-a15a5a2bb457.png)

Markdown code

https://github-readme-stats.vercel.app/api?username=stefoxp&show_icons=true&theme=gruvbox&count_private=true

On repository:

https://github.com/stefoxp/stefoxp

**Comment by DenverCoder1** [comment]
The GitHub app renders most SVGs incorrectly

Related to #215

**Comment by rickstaa** [comment]
This appears to be fixed. See https://github.com/anuraghazra/github-readme-stats/issues/899#issuecomment-877199309. I will close the related issues for now. If anyone is still experiencing issues feel free to leave a comment.
