### ISSUE TITLE
Flag Red Issue!

### ISSUE THREAD

**Issue by InnerPulse** [anuraghazra/github-readme-stats#987]
**Describe the bug**

Screenshot is avalable ->
![Screenshot (370)](https://user-images.githubusercontent.com/64663281/113757430-71fd0e00-96c7-11eb-88ee-00010bed4cd2.png)

From today a issue I have is that apperantly variable called PAT_1 causing some sort of a problem where no data is displayed but instead, the following message is preset:

 "Something went wrong! file an issue at https://git.io/JJmN9

Maximum retries exceeded
Please add an env variable called PAT_1 with your github token in vercel"

**Comment by anuraghazra** [comment]
Please follow the tutorial properly from here: https://www.youtube.com/watch?v=n6d4KHSKqGk&t=107s

**Comment by anuraghazra** [comment]
You are using your own vercel instance i think: 

![image](https://user-images.githubusercontent.com/35374649/113758206-34cd6600-9731-11eb-8f2d-f0d59509d89e.png)

**Comment by anuraghazra** [comment]
If you are not using your own vercel instance and probably copy pasted those links mistakenly from somewhere you can directly use our link instead of that `eight-theta` link

**Comment by InnerPulse** [comment]
It's all sorted now, all the best!

**Comment by RWambui** [comment]
https://github-readme-stats.vercel.app/api/pin/?username=yourusername&amp;
